import json

upsc = []

# ==================================================================
# SECTION 1: DENUDATION PHASES
# ==================================================================

upsc.append({"q":"Consider the following statements about the process of denudation:\n1. Denudation is carried out in four phases: weathering, erosion, transportation and deposition.\n2. Weathering is defined as the gradual disintegration of rocks by atmospheric or weather forces, without any active removal of material by moving agents.\n3. All four phases occur strictly one after another in a fixed sequence across the entire globe at the same time.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that all four phases are taking place SIMULTANEOUSLY in different parts of the world at different rates, depending on relief, rock structure, climate and human interference, not in a fixed global sequence. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements distinguishing weathering from erosion:\n1. Weathering is the gradual disintegration of rocks by atmospheric or weather forces, occurring largely in place.\n2. Erosion is the active wearing away of the Earth's surface by moving agents such as running water, wind, ice and waves.\n3. Transportation refers to the dumping of eroded debris in certain parts of the earth where it may accumulate to form new rocks.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and describes deposition, not transportation — transportation is the REMOVAL of eroded debris to new positions, while deposition is the actual dumping/accumulation of that debris. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): The Earth's surface shows great diversity of present-day landforms.\nReason (R): This diversity results from the interaction between constructive internal forces (such as orogenesis, folding, faulting and volcanic activity) and destructive external forces (denudation).\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text explicitly attributes landform diversity to the interaction of constructive forces (mountain-building, folding, faulting, volcanism) working simultaneously with destructive denudational forces that wear the surface down."})

# ==================================================================
# SECTION 2: CHEMICAL WEATHERING - SOLUTION
# ==================================================================

upsc.append({"q":"Consider the following statements about chemical weathering:\n1. It is an extremely slow and gradual decomposition of rocks due to exposure to air and water.\n2. When a soil cover exists over rock, chemical weathering of the underlying rock ceases entirely because the soil acts as a protective barrier.\n3. Rain-water that has absorbed organic acids from soil becomes a stronger weathering agent than pure rain-water acting on bare rock.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect and reverses the actual relationship — the text states that chemical weathering under a soil cover is usually ENHANCED (not ceased), because the soil absorbs rain-water and keeps the underlying rock in prolonged contact with moisture. Statements 1 and 3 are correct."})

upsc.append({"q":"Consider the following statements about solution as a chemical weathering process:\n1. Rain-water containing dissolved carbon dioxide acts as a weak acid capable of dissolving many minerals.\n2. Solution is the most potent weathering process in limestone regions because rain-water dissolves the calcium carbonate of which limestone is chiefly composed.\n3. Limestone is the only rock type that is subject to solution weathering; all other rock types are entirely immune to it.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that ALL rocks are subject to solution to some extent, though the process is much slower than with limestone; limestone is not uniquely susceptible. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about factors affecting the rate of solution weathering:\n1. Sedimentary rocks often have pore-spaces between grains in which air and water can lodge and attack the rock.\n2. The density of joints or cracks in a rock is crucial to the speed of weathering, as clearly seen in the weathering of granite in Malaysia.\n3. In tropical countries, heavy rainfall and warm climate together slow down chemical reactions, producing shallow regoliths.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual effect — heavy rainfall and warm climate in tropical countries PROMOTE rapid chemical reactions, producing very DEEP regoliths, not shallow ones. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about core-stones:\n1. Core-stones are pieces of solid rock that have resisted weathering while all surrounding rock has been weathered.\n2. They are more resistant because they have fewer joints or cracks to harbour moisture, making them more slowly weathered by solution processes.\n3. Core-stones typically form in areas with unevenly spaced joints, a phenomenon described as differential weathering.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing how uneven joint spacing in rocks like granite leads to differential weathering, leaving behind more resistant, less-jointed blocks (core-stones) embedded within more thoroughly weathered surrounding material."})

upsc.append({"q":"Consider the following statements about the influence of climate on weathering:\n1. Warm wet climates promote rapid chemical weathering.\n2. Dry climates inhibit chemical weathering but provide good conditions for physical or mechanical weathering.\n3. Climate has no measurable influence on the rate or type of weathering that occurs in a region.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and directly contradicts statements 1 and 2 — the text explicitly links climate type to which weathering process dominates: warm and wet climates favour chemical weathering, while dry climates favour mechanical weathering instead. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 3: OXIDATION AND ORGANIC ACIDS
# ==================================================================

upsc.append({"q":"Consider the following statements about oxidation as a weathering process:\n1. Oxidation is the reaction of oxygen in air or water with minerals in the rock.\n2. Iron in rocks, when in contact with air, changes to iron oxide (rust), which crumbles easily and is far more easily eroded than the original iron.\n3. Oxidation strengthens the overall structure of rocks by binding mineral particles more tightly together.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual effect — oxidation WEAKENS the overall rock structure by converting iron into easily-crumbled iron oxide, which is then removed, loosening rather than strengthening the rock. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about decomposition by organic acids:\n1. Bacteria within soil that thrive on decaying plant or animal material produce acids that speed up weathering of underlying rocks.\n2. Micro-organisms and plants like mosses or lichens can live on bare rock as long as the surface is damp, absorbing chemical elements from rocks and producing organic acids.\n3. Organisms such as mosses and lichens act only as agents of chemical weathering and play no role whatsoever in mechanical weathering.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly describes such organisms as agents of BOTH chemical AND mechanical weathering, not chemical weathering alone. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 4: MECHANICAL WEATHERING
# ==================================================================

upsc.append({"q":"Consider the following statements about mechanical (physical) weathering:\n1. It is the physical disintegration of rock by the actual prising apart of separate particles.\n2. It can happen even with completely fresh rock, but works more easily once chemical weathering has already weakened the rock surface.\n3. Mechanical weathering processes are entirely independent of, and unrelated to, chemical weathering processes.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that the processes of chemical and mechanical weathering 'are closely interrelated', not independent of one another. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about weathering by repeated temperature changes (exfoliation):\n1. In deserts, the outer layers of rocks expand faster than the cooler interior during the day and contract faster than the interior at night, setting up internal stresses.\n2. In crystalline rocks such as granite, different minerals (quartz, mica, felspar) expand and contract at different rates, enhancing these stresses.\n3. The gradual splitting off of surface layers of rounded boulders, resembling the layers of an onion, is technically termed exfoliation.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, together describing how differential thermal expansion and contraction — both between a rock's outer and inner layers, and between its constituent minerals — produces the layered splitting known as exfoliation or 'onion peeling'."})

upsc.append({"q":"Consider the following statements about the products of mechanical weathering by temperature change:\n1. Well-bedded and jointed rocks tend to split along their joints or cracks, breaking into rectangular blocks.\n2. Shales and slates may split into platy fragments because of their platy structure.\n3. Fragments broken from rock outcrops always remain exactly where they formed and never accumulate elsewhere.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text states that fragments broken from large rock outcrops fall by gravity to the foot of the slope, where they may form screes or a litter of angular chips and small boulders, not remain exactly in place. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about repeated wetting and drying as a weathering agent:\n1. This process is confined strictly to hot desert regions and does not occur in tropical or coastal areas.\n2. When rocks are wetted, outer layers absorb moisture and expand; when dried, this moisture evaporates and the layers shrink, eventually splitting off when repeated.\n3. At the coast, rocks may be rapidly dried by sun and wind between tides, contributing to this weathering process.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — the text explicitly states this process is 'not confined to desert areas', also occurring in tropical regions like Malaysia (short downpours followed by hot sun) and at the coast (rapid drying between tides). Statements 2 and 3 are correct."})

upsc.append({"q":"Consider the following statements about frost action as a mechanical weathering process:\n1. Water expands by about one-tenth of its volume when it freezes, exerting a bursting pressure of almost 140 kg per square cm.\n2. Repeated freezing in rock cracks and crevices deepens and widens the cracks, breaking rock into angular fragments.\n3. Frost-shattered peaks with sharp pinnacles and angular outlines are a product of this process on mountain peaks.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, quantifying the pressure exerted by freezing water and describing how repeated freeze-thaw cycles progressively fracture rock, ultimately producing angular, frost-shattered mountain peaks and scree accumulations at slope bases."})

upsc.append({"q":"Consider the following statements about biotic factors in mechanical weathering:\n1. Plant roots that sprout in rock crevices penetrate along joints and lines of weakness, prising rocks apart as they grow.\n2. Human activities such as mining, road construction and farming can also contribute to mechanical weathering by excavating rocks and rendering them more vulnerable to denudation.\n3. Biotic weathering agents are found exclusively in tropical climates and have no effect in any other climatic zone.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and is not supported — the text gives the general, climate-independent example of trees near roads or courtyards prising open paving stones, without restricting this phenomenon to tropical climates alone. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 5: MASS MOVEMENT
# ==================================================================

upsc.append({"q":"Consider the following statements about mass movement in general:\n1. Mass movement is the movement of weathered materials down a slope due to gravitational forces.\n2. The movement may be gradual or sudden depending on the slope's gradient, the weight of the weathered debris, and the availability of lubricating moisture.\n3. Mass movement occurs only on very steep mountain slopes and never on gentle terrain.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — soil creep, a form of mass movement described in the text, occurs even on fairly gentle slopes; mass movement is not restricted to very steep terrain alone. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about soil creep:\n1. It is a slow, gradual, more or less continuous movement of soil down hill slopes.\n2. It is most common in damp soils, where water acts as a lubricant allowing soil particles to move over each other and the underlying rock.\n3. Evidence of soil creep includes trees, fences and posts being tilted, even though the movement itself cannot readily be seen in action.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, capturing the defining slow, continuous, often-invisible nature of soil creep and its characteristic visible evidence — tilted vegetation and structures, and soil accumulation at slope bases or against obstacles."})

upsc.append({"q":"Consider the following statements about soil creep triggers:\n1. Continuous trampling by grazing animals can set up vibrations that loosen soil and cause creep.\n2. Soil creep is most prominent and easily observed on bare, ungrassed slopes compared to vegetated ones.\n3. Soil accumulating at the foot of a slope or behind obstacles like walls may eventually burst the obstacle due to the weight of accumulated soil.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the text states the movement is 'not very noticeable, especially when the slope is fairly gentle or when the soil is well-covered with grass or other vegetation', implying vegetation tends to mask rather than reveal creep, not make it more prominent. Statements 1 and 3 are correct."})

upsc.append({"q":"Consider the following statements about soil flow (solifluction):\n1. When soil is completely saturated with water, individual particles become almost suspended and the soil behaves like a liquid.\n2. In temperate and tundra regions, soil flows occur when surface layers of frozen ground thaw in spring, with meltwater lubricating debris over the still-frozen subsoil.\n3. In Ireland, flows of saturated peaty soil downslope are known as 'bog-bursts'.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, covering the general mechanism of soil flow under saturation, its specific seasonal trigger in tundra/temperate regions (spring thaw over frozen subsoil), and the distinctive Irish term for saturated peat flows."})

upsc.append({"q":"Consider the following statements about landslides:\n1. Landslides are very rapid kinds of mass movement, occurring when a large mass of soil or rock falls suddenly.\n2. They usually occur on steep slopes such as mountainous areas, cliffs, or artificially steepened slopes like road or rail cuttings.\n3. Landslides can never be triggered by earthquakes or volcanic disturbances, only by rainfall.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that earthquakes or volcanic disturbances may loosen rocks and start off a landslide, in addition to rainfall's lubricating action. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about slumping in landslides:\n1. Slumping is particularly common where permeable debris or rock layers overlie impermeable strata such as clay.\n2. Water sinking through permeable material is halted by clay, and the damp clay provides a smooth, slippery surface over which upper layers can slide.\n3. Human clearance of natural vegetation for agriculture or housing reduces the possibility of landslides by stabilising the soil.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual effect — removing plant cover allows MORE water to penetrate soil and rocks, ENHANCING the possibility of landslides, as seen in the Cameron Highlands example. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about a notable historical landslide example cited in the text:\n1. The village of Ringlet in the Cameron Highlands was partially buried by a landslide in 1961.\n2. Spectacular landslides have also taken place in South Wales, British Columbia and Hong Kong.\n3. All landslides mentioned as examples in the text were caused exclusively by human interference, with no natural triggers involved.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text describes landslides as being caused by a mix of natural factors (undercutting by rivers/sea, earthquakes, rainfall lubrication) and human factors (artificial slope steepening, vegetation clearance), not exclusively human causes. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 6: GROUNDWATER, POROSITY AND PERMEABILITY
# ==================================================================

upsc.append({"q":"Consider the following statements about the hydrological cycle and groundwater:\n1. The hydrological cycle is the whole process of circulation of water between the land, sea and atmosphere.\n2. A considerable proportion of rainwater percolates downwards into soil and rocks, filling joints and pore-spaces to form groundwater.\n3. Groundwater re-enters the hydrological cycle only through direct evaporation from deep underground reservoirs, never by way of springs.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that groundwater re-enters the hydrological cycle 'by way of springs', not through direct deep evaporation. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the distribution of rainfall between run-off and groundwater:\n1. In very humid conditions, where the ground surface may already be moist, much water moves as run-off.\n2. In dry climates, much precipitation may be quickly evaporated into the dry atmosphere, so little moisture percolates into the ground.\n3. The proportion of rainfall absorbed as groundwater is entirely independent of the season of the year.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that the proportion of rainfall absorbed as groundwater 'may depend on the season of the year', contradicting the claim of complete independence from season. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about porosity and permeability of rocks:\n1. Porous rocks, like sandstone, have many pore-spaces between grains and can store water in these spaces.\n2. Permeable (pervious) rocks allow water to pass through them easily; most porous rocks are also permeable.\n3. All porous rocks are automatically permeable, since porosity and permeability always occur together without exception.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that some rocks are porous but IMPERMEABLE, citing clay as an example (highly porous due to fine particles, but the pore-spaces are too small for water to move through easily). Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about clay and granite in relation to porosity and permeability:\n1. Clay is highly porous, absorbing a great deal of water, but is impermeable because its pore-spaces are too small for water to move through easily.\n2. Granite, being a crystalline and non-porous rock, is often pervious because water can pass through its numerous joints or cracks.\n3. All granites are equally pervious, with no variation between different granite formations.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that 'some granites are, however, far more pervious than others', meaning perviousness varies between granite formations rather than being uniform. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 7: THE WATER-TABLE AND AQUIFER
# ==================================================================

upsc.append({"q":"Consider the following statements about the water-table and aquifers:\n1. Water seeping through the ground moves downward under gravity until it reaches an impermeable layer through which it cannot pass.\n2. The permeable rock in which groundwater is stored above an impermeable layer is called the aquifer, and the surface of the saturated area is called the water-table.\n3. The water-table is always found at a fixed, unvarying depth below the surface regardless of relief, rock type or season.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states the water-table's depth 'varies greatly according to relief and to the type of rocks', and also varies with the seasons (rising with rainfall, falling in dry periods). Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the water-table's variation with relief and season:\n1. The water-table is far below the surface of hilltops but close to the surface in valleys and flat low-lying areas.\n2. In flat low-lying areas, a water-table close to the surface may cause waterlogging and swampy conditions.\n3. During dry periods, the water-table rises because seepage into springs decreases, allowing water to accumulate closer to the surface.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual relationship — in dry periods, with no new rain supplies available, the water-table is LOWERED as groundwater is lost through seepages and springs, not raised. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 8: SPRINGS
# ==================================================================

upsc.append({"q":"Consider the following statements about springs:\n1. A spring is an outlet where the water-table reaches the surface, releasing stored groundwater.\n2. Water at a spring may seep gradually out of the rock or gush out as a fountain.\n3. All springs are of exactly the same type, regardless of the surrounding rock structure or the position of the water-table.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly describes springs as being 'of several kinds due to the nature of the rocks and the position of the water-table', not all of one uniform type. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Type of Spring) with List-II (Formation Context) and select the correct answer using the code below.\nList-I:\nA. Spring in tilted strata\nB. Dyke spring\nC. Scarp-foot / dip-slope spring\nD. Resurgence (vauclusian spring)\nList-II:\n1. Water re-emerges where an underground karst river meets impermeable rock after flowing through solution passages\n2. Water emerges at the base of permeable layers where permeable and impermeable rocks alternate\n3. An impermeable dyke or sill intruded through permeable rocks forces the water-table to reach the surface\n4. Water issues at the foot of a limestone or chalk escarpment, or near the foot of the dip-slope\nCodes:","o":["A-2, B-3, C-4, D-1","A-3, B-2, C-4, D-1","A-2, B-4, C-3, D-1","A-2, B-3, C-1, D-4"],"a":0,"e":"The correct match is A-2, B-3, C-4, D-1: springs in tilted strata emerge at the base of permeable layers; dyke springs form where an impermeable intrusion forces the water-table up; scarp-foot/dip-slope springs occur at limestone/chalk escarpments; and resurgences occur where underground karst rivers re-emerge."})

upsc.append({"q":"Consider the following statements about spring formation in well-jointed rocks and karst regions:\n1. In well-jointed rocks, water may percolate downwards until it reaches a joint through which it emerges at the surface.\n2. In karst regions, rivers often disappear underground, flow through solution-worn passages, and may re-emerge where limestone gives way to impermeable rock.\n3. This karst re-emergence phenomenon is more accurately termed a 'resurgence', though it is sometimes called a vauclusian spring.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. The text explicitly states this karst phenomenon 'is sometimes called a vauclusian spring but is better referred to as a resurgence', while also describing the general well-jointed-rock spring mechanism."})

upsc.append({"q":"Consider the following statements about types of geothermal/mineral features related to springs:\n1. Hot springs, mineral springs and geysers are described in the text as being covered in a different chapter dealing with volcanism.\n2. All the spring types described in the groundwater chapter (tilted strata, jointed rocks, dyke springs, scarp-foot springs, resurgences) are examples of ordinary groundwater-fed springs unrelated to volcanic heat.\n3. A dyke spring forms because an impermeable dyke or sill intruded through permeable rock allows water to pass through unimpeded.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the mechanism — a dyke or sill of IMPERMEABLE rock BLOCKS the downward passage of water, forcing the water-table to rise and reach the surface as a spring; it does not allow water to pass through unimpeded. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 9: WELLS AND ARTESIAN WELLS
# ==================================================================

upsc.append({"q":"Consider the following statements about ordinary wells:\n1. A well must be sunk to the depth of the permanent water-table if a constant supply of water is to be obtained.\n2. If a well is sunk only to the wet-season depth of the water-table, water will be unobtainable when the level drops in the dry season.\n3. Once bored, well water always rises to the surface naturally without any need for hand or mechanical pumping.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text states that for an ordinary well, water usually has to be raised BY HAND or BY MECHANICAL PUMPING; natural upward gushing without pumping is instead the distinctive feature of artesian wells specifically. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the formation of an artesian basin:\n1. It forms where rock layers have been down-folded into a basin shape, with a permeable stratum (aquifer) sandwiched between two impermeable layers.\n2. The permeable rock may come to the surface at the edges of the basin, allowing water to seep down to the lowest part of the basin under gravity.\n3. The impermeable layers both above and below the aquifer prevent the water from escaping either downward or upward, saturating the aquifer under pressure.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing the essential 'sandwich' structure of an artesian basin — permeable rock trapped between two impermeable layers, fed at its exposed edges, that builds up the pressurised conditions distinctive of artesian wells."})

upsc.append({"q":"Consider the following statements about artesian wells:\n1. When bored, the pressure of water from all around the basin is sufficient to force water up the bore-hole so that it gushes to the surface like a fountain.\n2. Over time, the pressure decreases and it becomes necessary to pump up the water.\n3. Artesian well depths are always uniform worldwide, ranging narrowly between a few metres only.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text states artesian well depth 'varies from place to place, from a few metres to thousands of metres', not a narrow uniform range. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the uses and value of artesian wells:\n1. Artesian well water is used to supply villages, as in the Great Plains of the U.S.A., and for sheep farming, as in Queensland, Australia.\n2. Artesian wells are especially valuable in desert areas such as parts of the Sahara and Australia, where aquifers receive water from areas of higher rainfall but accumulate beneath arid regions.\n3. Artesian well water is always suitable for agricultural and irrigation purposes without exception.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that artesian water is 'sometimes unsuitable for agricultural or irrigation purposes as it may be hot or contain an excessive amount of mineral salts'. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the depletion of groundwater by human activity:\n1. Wells bored by Man tend to deplete groundwater resources because water is extracted faster than under natural conditions.\n2. Groundwater extraction via wells is also typically much faster than the rate at which it can be replenished by rainfall.\n3. Because groundwater naturally regenerates instantly, no area in the world has ever experienced a reduction or exhaustion of groundwater supplies due to over-exploitation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that 'in many areas groundwater supplies have been greatly reduced or even exhausted by Man as a result of carelessness and over-exploitation', directly contradicting the claim of instant regeneration and no depletion anywhere. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): Wells in arid areas are particularly important for human water supply.\nReason (R): Arid areas typically have little surface water but the underlying rocks may still contain accessible groundwater.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text explicitly states 'wells are particularly important in arid areas where there is little surface water but where the underlying rocks contain groundwater', directly linking the scarcity of surface water to the importance of well-based groundwater access."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "weathering_mass_movement_groundwater",
    "title": "Weathering, Mass Movement and Groundwater",
    "desc": "Denudation and its phases; chemical weathering (solution, oxidation, organic acids); mechanical weathering (temperature change/exfoliation, wetting-drying, frost action, biotic factors); mass movement (soil creep, solifluction, landslides); groundwater, porosity and permeability; water-table and aquifers; springs and wells (including artesian wells)",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch04_weathering_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
