import json

upsc = []

# ==================================================================
# SECTION 1: STRUCTURE OF THE EARTH (SIAL, SIMA, MANTLE, CORE)
# ==================================================================

upsc.append({"q":"Consider the following statements about the composition of the Earth's crust (lithosphere):\n1. The upper part, called the sial, consists of granitic rocks rich in silica and alumina, and forms the continents.\n2. The lower part, called the sima, consists of denser basaltic rocks rich in silica, iron and magnesium, and forms the ocean floors.\n3. The sial has a higher average density (3.0) than the sima (2.7).\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 reverses the actual values — the sial has the LOWER average density (2.7), while the sima has the HIGHER average density (3.0); this density difference is precisely why the text describes continents as 'floating' on a sea of denser sima. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the thickness of the Earth's crust:\n1. The crust varies in thickness from only 5-6 km beneath the oceans to as much as 48 km under some parts of the continents.\n2. This means the crust is thinner under the oceans than under the continents.\n3. The uniform thinness of the crust everywhere is what allows continents to float on the denser sima below.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect on two counts — the crust's thickness is NOT uniform (it varies considerably, per statement 1), and the 'floating' of continents is explained by the DENSITY difference between sial and sima, not by crustal thinness. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the layers beneath the Earth's crust:\n1. Immediately beneath the crust lies the mantle (or mesosphere), about 2,900 km thick, composed mainly of dense rocks rich in olivine.\n2. The innermost layer is the core (or barysphere), about 3,476 km in radius, made up mainly of iron and nickel and called nife.\n3. Recent studies through earthquake waves suggest that the entire core, including its innermost part, is definitely in a liquid state.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — while the extremely high temperature and pressure would suggest a liquid core, the text notes that earthquake wave studies suggest the INNERMOST part of the core is probably a CRYSTALLINE or SOLID mass, contrary to a simple expectation of it being entirely liquid. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): The continents can be described as 'floating' on a sea of denser sima.\nReason (R): The sial, which forms the continents, has a lower average density than the sima, which forms the ocean floors.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text directly states that since the sial (density 2.7) is lighter than the sima (density 3.0), the continents can be said to be 'floating' on this denser layer beneath them, exactly analogous to a lighter substance resting atop a denser one."})

upsc.append({"q":"Match List-I (Layer of the Earth) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Sial\nB. Sima\nC. Mantle (mesosphere)\nD. Core (barysphere)\nList-II:\n1. About 2,900 km thick, composed mainly of dense rocks rich in olivine\n2. Made up mainly of iron and nickel, called nife, with an estimated temperature of about 1,927°C\n3. Upper crust of granitic rocks rich in silica and alumina, average density 2.7\n4. Lower crust of denser basaltic rocks forming ocean floors, average density 3.0\nCodes:","o":["A-3, B-4, C-1, D-2","A-4, B-3, C-2, D-1","A-3, B-4, C-2, D-1","A-1, B-2, C-3, D-4"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: the sial is the lighter, granitic upper crust; the sima is the denser, basaltic lower crust; the mantle is the thick olivine-rich zone beneath the crust; and the core (nife) is the innermost iron-nickel layer with extremely high estimated temperature."})

upsc.append({"q":"With reference to how scientists have inferred the internal structure of the Earth, consider the following statements:\n1. It is not possible to know exactly how the Earth was formed about 4,500 million years ago.\n2. Evidence from volcanic eruptions, earthquake waves, deep-mine operations and crustal borings has been used to establish facts about the Earth's internal structure.\n3. Direct physical drilling to the Earth's core has confirmed all the facts stated about the core's composition and temperature.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — no direct drilling has reached the Earth's core; deep-mine operations and crustal borings only reach the crust, while knowledge of the mantle and core rests on indirect evidence such as earthquake (seismic) wave behaviour. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the hydrosphere and atmosphere in relation to the Earth's structure:\n1. Parts of the Earth's crust immersed by oceans and seas form the hydrosphere.\n2. The atmosphere envelops the Earth, extending skywards for over 24 km.\n3. The hydrosphere and atmosphere together constitute the innermost layers of the Earth, beneath the crust.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the hydrosphere (oceans/seas) and atmosphere are OUTER envelopes associated with the Earth's surface and above it, not innermost layers; the innermost layers are the mantle and core, which lie beneath the crust (lithosphere). Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 2: CLASSIFICATION OF ROCKS - IGNEOUS
# ==================================================================

upsc.append({"q":"Consider the following statements about igneous rocks:\n1. They are formed by the cooling and solidification of molten rock (magma) from beneath the Earth's crust.\n2. They are normally crystalline in structure and do not occur in strata or contain fossils.\n3. Acid igneous rocks, such as granite, contain a high proportion of silica, are less dense, and are lighter in colour than basic igneous rocks.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. Igneous rocks form from cooling magma, lack the layering and fossils characteristic of sedimentary rocks, and are subdivided by silica content into acid types (like granite — lighter, less dense) and basic types (denser, darker, richer in iron/aluminium/magnesium oxides)."})

upsc.append({"q":"Consider the following statements distinguishing plutonic and volcanic igneous rocks:\n1. Plutonic rocks, such as granite, diorite and gabbro, cool and solidify slowly at depth, allowing large, easily-recognized crystals to form.\n2. Volcanic rocks are molten rocks poured out as lava, which solidify rapidly on the Earth's surface, producing small crystals.\n3. Plutonic rocks are exposed at the surface only through the processes of denudation and erosion removing the overlying material.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. The contrast between slow, deep cooling (plutonic, large crystals, e.g. granite) and rapid, surface cooling (volcanic, small crystals, e.g. basalt) explains crystal size differences, and plutonic rocks are described as becoming visible only after denudation strips away overlying rock."})

upsc.append({"q":"Consider the following statements about basalt:\n1. It is a common volcanic (extrusive) rock that forms lava flows, lava sheets and lava plateaux.\n2. Examples cited include the Antrim plateau in Northern Ireland, the Deccan Plateau in India, and the Columbia-Snake Plateau in the U.S.A.\n3. Some basalt solidifies to form long polygonal columns, as seen at the Giant's Causeway in Antrim.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, together describing basalt's role in forming extensive lava landscapes worldwide, including the famous columnar basalt formation of the Giant's Causeway."})

upsc.append({"q":"Assertion (A): Granite is classified as a less dense, lighter-coloured igneous rock.\nReason (R): Granite contains a high proportion of silica, which classifies it as an acid igneous rock, as opposed to basic igneous rocks that are richer in oxides of iron, aluminium or magnesium.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text's classification scheme directly links high silica content to being 'acid' and to lower density/lighter colour, contrasted with basic igneous rocks that have more iron/aluminium/magnesium oxides and are therefore denser and darker."})

# ==================================================================
# SECTION 3: SEDIMENTARY ROCKS
# ==================================================================

upsc.append({"q":"Consider the following statements about sedimentary rocks in general:\n1. They are formed from sediments accumulated over long periods, usually under water.\n2. They are distinguished by characteristic layer (stratified) formation and often contain fossils.\n3. They are crystalline in structure, similar to igneous rocks.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — sedimentary rocks are explicitly described as NON-crystalline, in direct contrast to the crystalline structure of igneous rocks; this is one of the key distinguishing features between the two rock types. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about mechanically formed sedimentary rocks:\n1. Sandstones are formed from sand grains, often quartz fragments derived from granites.\n2. Conglomerate is formed when larger pebbles are firmly cemented together and the pebbles are rounded, while breccia forms when the fragments are angular.\n3. Grit is a finer-textured type of sandstone than ordinary sandstone.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — grit is described as a COARSER type of sandstone, not a finer one; the finer sedimentary materials mentioned in the text form clay, shale or mudstone instead. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about organically formed sedimentary rocks:\n1. Calcareous rocks such as limestone and chalk form from the remains of organisms like corals or shellfish, whose hard shells remain after the fleshy parts decompose.\n2. Carbonaceous rocks such as peat, lignite and coal are also organically formed, but from vegetative matter in swamps and forests compressed under overlying sediments.\n3. Rock salt and gypsum are examples of organically formed sedimentary rocks.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — rock salt and gypsum are examples of CHEMICALLY formed sedimentary rocks (precipitated from solutions such as evaporating salt lakes), not organically formed rocks. Statements 1 and 2 correctly describe the calcareous and carbonaceous organic sedimentary rocks."})

upsc.append({"q":"Consider the following statements about chemically formed sedimentary rocks:\n1. Rock salts are derived from strata that once formed the beds of seas or lakes.\n2. Gypsum, or calcium sulphate, is obtained from the evaporation of highly saline salt lakes such as the Dead Sea.\n3. Potash and nitrates cannot be formed through chemical precipitation and are always mined from igneous rock deposits.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that potash and nitrates may be formed 'in similar ways' to rock salt and gypsum, i.e. through chemical precipitation from solution, not exclusively by mining from igneous deposits. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Sedimentary Rock) with List-II (Category of Formation) and select the correct answer using the code below.\nList-I:\nA. Sandstone\nB. Limestone\nC. Rock salt\nD. Coal\nList-II:\n1. Chemically formed\n2. Carbonaceous (organically formed from vegetative matter)\n3. Mechanically formed\n4. Calcareous (organically formed from marine organisms)\nCodes:","o":["A-3, B-4, C-1, D-2","A-3, B-1, C-4, D-2","A-4, B-3, C-2, D-1","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: sandstone is mechanically formed from cemented grains; limestone is a calcareous organic rock from marine organism remains; rock salt is chemically precipitated; and coal is a carbonaceous organic rock from compressed vegetative matter."})

# ==================================================================
# SECTION 4: METAMORPHIC ROCKS
# ==================================================================

upsc.append({"q":"Consider the following statements about metamorphic rocks:\n1. Both igneous and sedimentary rocks may become metamorphic under great heat and pressure, particularly during intense earth movements.\n2. Clay may be metamorphosed into slate, limestone into marble, and sandstone into quartzite.\n3. Granite, being an igneous rock, cannot undergo metamorphism under any circumstances.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states granite may be metamorphosed into gneiss; ALL rock types, whether igneous or sedimentary, can become metamorphic under sufficient heat and pressure. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Original Rock) with List-II (Metamorphosed Form) and select the correct answer using the code below.\nList-I:\nA. Shale\nB. Coal\nC. Sandstone\nD. Granite\nList-II:\n1. Quartzite\n2. Gneiss\n3. Schist\n4. Graphite\nCodes:","o":["A-3, B-4, C-1, D-2","A-4, B-3, C-2, D-1","A-3, B-1, C-4, D-2","A-1, B-2, C-3, D-4"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: shale metamorphoses into schist, coal into graphite, sandstone into quartzite, and granite into gneiss — each transformation explicitly listed in the text as an example of metamorphism under heat and pressure."})

# ==================================================================
# SECTION 5: INFLUENCE OF ROCK TYPES ON LANDSCAPE
# ==================================================================

upsc.append({"q":"Consider the following statements about the influence of rock type on landscape, using Peninsular Malaysia as an example:\n1. Resistant granites form the high ground of the Main Range and the Eastern Highlands, producing smooth slopes and rounded hilltops.\n2. The highest peak in Peninsular Malaysia, Gunung Tahan, is composed of quartzite, which is even more resistant than granite.\n3. Limestone in this region forms low, flat plains because it erodes faster than shales and sandstones.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — limestone, being resistant because of its permeability, forms PROMINENT STEEP-SIDED HILLS (such as those near Ipoh and in Perlis), not low flat plains; flat plains in the region are instead formed by recent river sediments. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 6: EARTH MOVEMENTS AND OROGENIES
# ==================================================================

upsc.append({"q":"Consider the following statements about orogenic (mountain-building) movements in Earth's history:\n1. No less than nine orogenic movements have taken place since the dawn of geological time, folding and fracturing the Earth's crust.\n2. The three most recent orogenies are the Caledonian, Hercynian and Alpine, occurring in that chronological order from oldest to most recent.\n3. Some orogenic movements occurred in Pre-Cambrian times, between 600 and 3,500 million years ago.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. The Caledonian (about 320 million years ago), Hercynian (about 240 million years ago) and Alpine (about 30 million years ago) orogenies are listed in the text in this exact chronological order as the three most recent of at least nine major orogenic episodes."})

upsc.append({"q":"Match List-I (Orogeny) with List-II (Associated Mountain Ranges) and select the correct answer using the code below.\nList-I:\nA. Caledonian orogeny\nB. Hercynian orogeny\nC. Alpine orogeny\nList-II:\n1. Alps, Himalayas, Andes and Rockies\n2. Ural Mountains, Pennines, Welsh Highlands, Harz Mountains, Appalachians\n3. Mountains of Scandinavia and Scotland\nCodes:","o":["A-3, B-2, C-1","A-1, B-2, C-3","A-2, B-3, C-1","A-3, B-1, C-2"],"a":0,"e":"The correct match is A-3, B-2, C-1: the Caledonian orogeny (about 320 million years ago) raised the mountains of Scandinavia and Scotland; the Hercynian (about 240 million years ago) formed the Urals, Pennines, Welsh Highlands, Harz Mountains and Appalachians; and the Alpine (about 30 million years ago) formed the Alps, Himalayas, Andes and Rockies."})

upsc.append({"q":"Consider the following statements about the Alpine orogeny and its resulting mountain ranges:\n1. The Alpine orogeny occurred about 30 million years ago, making it the most recent of the major orogenic movements.\n2. Ranges formed by the Alpine orogeny, such as the Himalayas and Andes, are generally the loftiest and most imposing because they are the most recently formed and least eroded.\n3. Mountains formed by the earlier Caledonian and Hercynian orogenies are today taller than the Alpine ranges because they have had more time to be uplifted further.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual relationship — the OLDER Caledonian and Hercynian mountains have been WORN DOWN over their much longer history and no longer exhibit the striking heights they once had, whereas the YOUNGER Alpine ranges remain the loftiest precisely because they have had less time to be eroded. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): The Himalayas, Andes, Alps and Rockies are among the loftiest and most imposing mountain ranges in the world today.\nReason (R): These ranges were formed by the Alpine orogeny, the most recent of the Earth's major mountain-building movements, and have therefore undergone comparatively less erosion than older ranges.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text explicitly attributes the loftiness of these ranges to their being 'the most recently formed', implying that less time has elapsed for denudation to wear them down compared to the much older Caledonian and Hercynian ranges."})

# ==================================================================
# SECTION 7: TYPES OF MOUNTAINS
# ==================================================================

upsc.append({"q":"Consider the following statements about fold mountains:\n1. They are caused by large-scale earth movements that subject rocks to compressive forces, producing wrinkling or folding.\n2. Folding effectively shortens the Earth's crust, with upfolded waves called anticlines and downfolds called synclines.\n3. Fold mountains are also known as mountains of accumulation because they are built up from materials ejected during volcanic activity.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and confuses fold mountains with volcanic mountains — fold mountains, since their rock strata have been elevated to great heights, are called mountains of ELEVATION, not accumulation; 'mountains of accumulation' specifically describes volcanic mountains built up from ejected volcanic materials. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the progressive stages of fold deformation:\n1. When the crest of a fold is pushed too far, an overfold is formed; if pushed further still, it becomes a recumbent fold.\n2. In extreme cases, the upper part of a recumbent fold may slide forward over the lower part along a thrust plane, forming an overthrust fold.\n3. The overriding portion of a thrust fold is termed a nappe.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing the escalating sequence of fold deformation from simple folding through overfolds, recumbent folds, and finally overthrust folds with their characteristic nappe structure."})

upsc.append({"q":"Consider the following statements about fold mountains' broader characteristics:\n1. Fold mountains are the most widespread and important type of mountain.\n2. They are closely associated with volcanic activity and contain many active volcanoes, especially in the Circum-Pacific fold mountain system.\n3. Fold mountains generally lack significant mineral resources compared to other mountain types.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that fold mountains contain RICH mineral resources such as tin, copper, gold and petroleum, contradicting the claim that they lack significant resources. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about block mountains and rift valleys:\n1. Faulting occurs when the Earth's crust cracks, as opposed to folding, which occurs when the crust bends.\n2. When a block enclosed by faults remains stationary or rises while the surrounding land subsides, the upstanding block becomes a horst or block mountain.\n3. A graben or rift valley is formed when the central portion is let down between two adjacent fault blocks.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, accurately distinguishing folding (bending) from faulting (cracking), and describing the two complementary landforms — horsts (upstanding blocks) and grabens (down-dropped blocks) — that result from tensional faulting."})

upsc.append({"q":"Consider the following statements about examples of block mountains and rift valleys cited in the text:\n1. The Hunsruck Mountains, the Vosges and the Black Forest of the Rhineland are examples of block mountains (horsts).\n2. The East African Rift Valley system is about 4,828 km long, stretching from East Africa through the Red Sea to Syria.\n3. Large-scale block mountains and rift valleys are generally attributed more to compressional forces than to tensional forces.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the text's stated relationship — large-scale block mountains and rift valleys are generally attributed more to TENSION than to compression; compressional forces are instead linked to thrust or reverse faults that shorten the crust. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about volcanic mountains and residual mountains:\n1. Volcanic mountains are built up from materials ejected from fissures in the Earth's crust, including molten lava, volcanic bombs, cinders, ashes, dust and liquid mud, and are common in the Circum-Pacific belt.\n2. Residual mountains, such as Mt. Monadnock in the U.S.A., are evolved through denudation of a generally lowered land surface, leaving behind highly resistant areas.\n3. Residual mountains can never evolve from plateaux, only from previously existing mountain ranges.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that residual mountains MAY ALSO evolve from plateaux that have been dissected by rivers into hills and valleys, citing the Highlands of Scotland, Scandinavia and the Deccan Plateau as examples of dissected plateaux forming mountains of denudation. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Type of Mountain) with List-II (Example) and select the correct answer using the code below.\nList-I:\nA. Fold mountain\nB. Block mountain\nC. Volcanic mountain\nD. Residual mountain\nList-II:\n1. Mt. Fuji (Japan)\n2. Mt. Monadnock (U.S.A.)\n3. Himalayas\n4. Vosges (Rhineland)\nCodes:","o":["A-3, B-4, C-1, D-2","A-3, B-1, C-4, D-2","A-4, B-3, C-2, D-1","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: the Himalayas are a classic fold mountain range; the Vosges is cited as a block mountain (horst) example; Mt. Fuji is a volcanic mountain; and Mt. Monadnock exemplifies a residual mountain formed by denudation."})

upsc.append({"q":"Which one of the following is NOT among the four main types of mountain classified by mode of formation in the text?","o":["Erosional mountains","Fold mountains","Block mountains","Volcanic mountains"],"a":0,"e":"The text identifies exactly four types of mountain by mode of formation: fold mountains, block mountains, volcanic mountains, and residual mountains (evolved by denudation) — there is no separately named category called 'erosional mountains'; that concept is instead covered under residual mountains."})

# ==================================================================
# SECTION 8: TYPES OF PLATEAU
# ==================================================================

upsc.append({"q":"Consider the following statements about tectonic plateaux:\n1. They are formed by earth movements that cause uplift and are normally of considerable size with fairly uniform altitude.\n2. Some tectonic plateaux may be tilted, like the Meseta of central Iberia, or faulted, like the Harz of Germany.\n3. Plateaux enclosed by fold mountains, called intermont plateaux, are generally among the lowest and least extensive plateaux in the world.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the text's description — intermont plateaux, such as the Tibetan Plateau (between the Himalayas and Kunlun) and the Bolivian Plateau (between two Andean ranges), are described as among the HIGHEST and MOST EXTENSIVE plateaux in the world, not the lowest. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about volcanic plateaux:\n1. They are formed when molten lava issues from the Earth's crust and spreads over the surface in successive sheets of basaltic lava, which then solidify.\n2. The Columbia-Snake Plateau is cited as the most remarkable lava-built plateau, covering an area almost twice as big as Malaysia.\n3. Each layer of lava flow in the Columbia-Snake Plateau is estimated to be over 30 metres thick, with total successive layers reaching almost 1.6 km in depth.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing the formation mechanism and the specific dimensions given in the text for the Columbia-Snake Plateau as an example of an especially large and thick volcanic plateau."})

upsc.append({"q":"Consider the following statements about dissected plateaux:\n1. In humid highlands, stream action and sometimes glaciation cut deep, narrow valleys into plateaux, producing dissected plateaux such as the Scottish Highlands.\n2. In drier countries, vertical corrasion by rivers and abrasion by winds dissect plateaux into steep-sided tabular masses called mesas and buttes, intersected by deep canyons.\n3. This mesa-and-butte landscape is a common feature of humid tropical regions rather than arid or semi-arid areas.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly identifies mesas, buttes and canyons as a common feature of ARID and SEMI-ARID areas (citing the south-western U.S.A. as an example), not humid tropical regions. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Plateau) with List-II (Principal Mineral Resource Mentioned) and select the correct answer using the code below.\nList-I:\nA. African Plateau\nB. Brazilian Plateau (Minas Gerais)\nC. Deccan Plateau\nD. Western Australian Plateau\nList-II:\n1. Manganese, coal and iron\n2. Gold and iron\n3. Gold, diamonds, copper, manganese and chromium\n4. Iron and manganese\nCodes:","o":["A-3, B-4, C-1, D-2","A-3, B-1, C-4, D-2","A-4, B-3, C-2, D-1","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: the African Plateau yields gold, diamonds, copper, manganese and chromium; Brazil's Minas Gerais area has huge iron and manganese resources; the Deccan Plateau has manganese, coal and iron; and Western Australia's plateau is rich in gold and iron."})

# ==================================================================
# SECTION 9: TYPES OF PLAIN
# ==================================================================

upsc.append({"q":"Consider the following statements about structural plains:\n1. They are structurally depressed areas formed by horizontally bedded rocks, relatively undisturbed by crustal movements.\n2. Examples include the Russian Platform, the Great Plains of the U.S.A., and the central lowlands of Australia.\n3. Structural plains are always formed through the deposition of river-borne alluvium.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and confuses structural plains with depositional plains — structural plains are defined by their relatively undisturbed, horizontally bedded rock structure, NOT by a process of alluvial deposition, which instead characterises depositional plains like alluvial and flood plains. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about depositional plains formed by rivers:\n1. Active erosion in a river's upper course results in alluvium being carried down and deposited in the lower course to form alluvial, flood and deltaic plains.\n2. The Nile delta is noted for rice and cotton cultivation, while the Ganges delta is noted for rice and jute growing.\n3. These river-deposited plains are generally the least productive and most sparsely populated agricultural plains in the world.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text describes these alluvial, flood and deltaic plains as among the MOST PRODUCTIVE agricultural plains in the world, intensively tilled and very densely populated, the opposite of least productive and sparsely populated. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about glacial depositional plains:\n1. Outwash plains are formed by a widespread mantle of unsorted fluvio-glacial sands and gravels deposited by glaciers and ice-sheets.\n2. Till plains (or drift plains) are formed from boulder clay, a mixture of various sizes of boulders and clay.\n3. Outwash plains, such as some parts of the Netherlands and northern Germany, are usually more fertile than boulder clay plains such as the Mid-West of the U.S.A.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual comparison — outwash plains are usually described as BARREN lands, while boulder clay (till) plains may be VERY VALUABLE farming land, such as the Mid-West of the U.S.A. and East Anglia in England. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about coastal and loess plains:\n1. Coastal plains may form from beach materials, mud, sand or shingle driven landwards by waves and winds, forming marine swamps, mudflats and estuarine lowlands.\n2. An emergent coastal plain forms when uplift raises coastal lowlands slightly, as seen along the coastal margins from Florida to Texas.\n3. Loess, a coarse aeolian deposit of large boulders, is blown from interior deserts to form loess plateaux and plains such as in north-west China.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — loess is described as VERY FINE aeolian particles, not large boulders; its fineness is precisely what allows wind to transport it over long distances and deposit it to fill up grooves and depressions, levelling undulating plains. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about erosional plains:\n1. Peneplains are plains of denudation, formed as rain, rivers, ice and wind smooth out irregularities and even reduce high mountains to low undulating plains over millions of years.\n2. Ice-scoured plains, found extensively in northern Europe and northern Canada, often contain numerous lakes formed in hollows scooped out by glaciers.\n3. Finland is estimated to have about 35,000 lakes, occupying roughly 10 per cent of its total land surface.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing how erosional processes in humid regions (peneplains) and glaciated regions (ice-scoured plains, with Finland's numerous lakes as a striking example) both reduce land to low-relief surfaces over long timescales."})

upsc.append({"q":"Consider the following statements about pediplains in arid and semi-arid regions:\n1. In arid and semi-arid regions, wind deflation sweeps away eroded desert materials, forming extensive gravelly or stony desert plains called reg in Africa.\n2. Mechanical weathering wears back mountain slopes to leave gently sloping pediments or pediplains, though some steep, isolated hills called inselbergs may remain.\n3. Pediplains form primarily through the deposition of river-borne alluvium in humid river deltas.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and confuses pediplains (an EROSIONAL landform of arid/semi-arid regions, formed by mechanical weathering wearing back mountain slopes) with depositional alluvial plains formed by humid river deltas — these are distinct plain types with different formation processes. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Type of Plain) with List-II (Formation Process) and select the correct answer using the code below.\nList-I:\nA. Peneplain\nB. Pediplain\nC. Till plain\nD. Loess plain\nList-II:\n1. Deposition of boulder clay by glaciers and ice-sheets\n2. Deposition of fine wind-blown particles from deserts or barren surfaces\n3. Denudation of high mountains into an undulating lowland in humid conditions\n4. Mechanical weathering wearing back mountain slopes in arid/semi-arid conditions, leaving inselbergs\nCodes:","o":["A-3, B-4, C-1, D-2","A-4, B-3, C-2, D-1","A-3, B-1, C-4, D-2","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: a peneplain forms through humid denudation of mountains; a pediplain forms through arid mechanical weathering leaving inselbergs; a till plain forms from glacial boulder-clay deposition; and a loess plain forms from fine wind-blown deposits."})

upsc.append({"q":"Which one of the following statements about plains, as described in the text, is INCORRECT?","o":["Plains generally rise more than a few thousand metres above sea-level","Plains usually form the best agricultural land of a country and often support concentrated population and settlement","Some of the most extensive temperate plains are grasslands such as the Russian Steppes and North American Prairies","Plains traversed by rivers are often of even greater economic importance"],"a":0,"e":"This statement is incorrect and is the false one being asked for — the text explicitly describes a plain as an area of lowland that 'seldom rises more than a FEW HUNDRED metres above sea-level', not several thousand metres; the other three statements accurately reflect the text's description of plains."})

upsc.append({"q":"Rocks differ from one another in various respects. Which one of the following is NOT among the respects in which rocks differ, as identified in the text?","o":["Salinity","Texture","Permeability","Mode of occurrence"],"a":0,"e":"The text states that rocks differ from one another in texture, structure, colour, permeability, mode of occurrence and degree of resistance to denudation — salinity is not listed among these distinguishing respects; this question mirrors a sample objective question given directly in the chapter."})

upsc.append({"q":"Consider the following statements about why a basic knowledge of rocks is important to a geographer:\n1. Rocks influence the appearance and characteristic features of landforms.\n2. Rocks form the basis for soil and determine, to some extent, the type of natural vegetation and land use.\n3. Only professional geologists, and not geographers, have any practical need to study rock composition and physical history.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — while geologists study rocks in more specialised depth, the text explicitly states that geographers ALSO need a basic knowledge of common rocks and their relationship with landforms, soil and vegetation. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the practical uses of igneous rocks mentioned in the text:\n1. Most igneous rocks are extremely hard and resistant, which makes them suitable for quarrying for road-making.\n2. Igneous rocks are also polished for use as monuments and grave-stones.\n3. Molten lava may push its way to the surface through clefts and passages, solidifying as vertical dykes or horizontal sills.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. The hardness and resistance of igneous rocks make them valuable for construction and monumental use, while the text also notes that igneous intrusions can take the form of vertical dykes (cutting across existing strata) or horizontal sills (running between layers of existing strata)."})

upsc.append({"q":"Match List-I (Volcanic Mountain) with List-II (Location) and select the correct answer using the code below.\nList-I:\nA. Mt. Fuji\nB. Mt. Merapi\nC. Mt. Agung\nD. Mt. Cotopaxi\nList-II:\n1. Bali\n2. Ecuador\n3. Japan\n4. Sumatra\nCodes:","o":["A-3, B-4, C-1, D-2","A-3, B-1, C-4, D-2","A-4, B-3, C-2, D-1","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: Mt. Fuji is in Japan, Mt. Merapi is in Sumatra, Mt. Agung is in Bali, and Mt. Cotopaxi is in Ecuador — all cited in the text as examples of volcanic mountains common in the Circum-Pacific belt (with Cotopaxi being an Andean example)."})

upsc.append({"q":"Assertion (A): Intermont plateaux, such as the Tibetan Plateau and the Bolivian Plateau, are among the highest and most extensive plateaux in the world.\nReason (R): Intermont plateaux are enclosed by fold mountains, which were themselves uplifted to great heights during recent orogenic movements, so the enclosed plateau surfaces also lie at very high elevations.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R offers a coherent explanation — the Tibetan Plateau lies between the Himalayas and the Kunlun, and the Bolivian Plateau lies between two Andean ranges; since both bounding fold mountain systems were raised to great heights by the (comparatively recent) Alpine orogeny, the enclosed plateaux themselves also sit at very high elevation, consistent with the text's description of intermont plateaux as among the highest and most extensive."})

upsc.append({"q":"Consider the following statements about the overall classification of rocks:\n1. All rocks may be classified into three major groups — igneous, sedimentary and metamorphic — according to their origin and appearance.\n2. Sedimentary rocks are classified according to their age, with rocks formed during the same period grouped together.\n3. Despite this age-based classification system, the text emphasises that knowing the characteristics of the various kinds of rock is more useful.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct. The text sets out the three-fold origin-based classification of all rocks, notes that sedimentary rocks are additionally classified by age, and then states that it is 'more useful to know the characteristics of the various kinds of rock' than to dwell on age-based grouping alone."})

upsc.append({"q":"Granite, diorite, gabbro and basalt are all igneous rocks. Which one of these is classified as a volcanic (extrusive) rock rather than a plutonic (intrusive) rock?","o":["Basalt","Granite","Diorite","Gabbro"],"a":0,"e":"The text explicitly groups granite, diorite and gabbro together as plutonic (intrusive) rocks that cool slowly at depth, forming large crystals, while basalt is named as the common volcanic (extrusive) rock that solidifies rapidly on the surface with small crystals."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "earths_crust",
    "title": "The Earth's Crust",
    "desc": "Structure and composition of the Earth (sial, sima, mantle, core); classification of rocks (igneous, sedimentary, metamorphic); influence of rock types on landscape; earth movements and orogenies; types of mountain, plateau and plain — UPSC-level questions only, covering every concept in the chapter",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch02_earths_crust_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
