import json

upsc = []

# ==================================================================
# SECTION 1: NATURE OF LIMESTONE, CHALK AND KARST TOPOGRAPHY
# (Goh Cheng Leong + NCERT XI Part 1, Ch.7 "Landforms and their Evolution")
# ==================================================================

upsc.append({"q":"Consider the following statements about limestone and chalk:\n1. Limestone and chalk are sedimentary rocks of organic origin, derived from the accumulation of corals and shells in the sea.\n2. In its pure state, limestone is made up of calcite or calcium carbonate; where magnesium is also present, it is termed dolomite.\n3. Chalk is a very pure, hard form of limestone, generally black in colour.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text describes chalk as a very pure form of limestone that is white and rather SOFT, not black and hard. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about karst topography:\n1. A region with a large stretch of limestone possesses a distinct topography because limestone is soluble in rain-water carrying carbon dioxide, which forms a weak acid.\n2. The term 'karst' is derived from the Karst district of Yugoslavia, in the Balkans adjacent to the Adriatic Sea, where such topography is particularly well developed.\n3. Karst topography can develop equally well in any type of rock, since it results purely from mechanical erosion by wind and running water.\nHow many of the above statements are correct?","o":["Only two","Only one","All three","None"],"a":0,"e":"Statements 1 and 2 are correct, matching both Goh Cheng Leong's and NCERT's account of karst's chemical origin and naming. Statement 3 is incorrect — karst topography specifically develops in limestone/dolomite rocks rich in calcium carbonate through CHEMICAL processes of solution and precipitation, not through mechanical wind/water erosion in any rock type."})

upsc.append({"q":"According to the NCERT account of groundwater's geomorphic work, which one of the following statements is NOT correct?","o":["Physical or mechanical removal of material by moving groundwater is the dominant process forming karst landforms","Groundwater erosion produces visible landforms only in rocks like limestone or dolomite that are rich in calcium carbonate","The two chief processes active in limestone/dolomite regions are solution and precipitation deposition","Surface water percolates well when rocks are permeable, thinly bedded, and highly jointed or cracked"],"a":0,"e":"This statement is incorrect and reverses the text's explicit claim — NCERT states that physical/mechanical removal of material by moving groundwater is 'insignificant' in developing landforms; it is the CHEMICAL processes of solution and precipitation that dominate in limestone/dolomite regions. The other three statements are correct."})

# ==================================================================
# SECTION 2: KARST REGION CHARACTERISTICS AND DRAINAGE
# ==================================================================

upsc.append({"q":"Consider the following statements about the general characteristics of a karst region:\n1. Karst regions typically have a bleak landscape, occasionally broken by precipitous slopes.\n2. There is a general absence of surface drainage because most surface water has gone underground.\n3. Streams rising on other (non-limestone) rocks may flow over limestone for a short distance before disappearing underground.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, directly reflecting the text's description of a karst landscape: bleak with occasional steep slopes, largely lacking surface drainage, and having streams that sink underground shortly after entering limestone terrain."})

upsc.append({"q":"Which one of the following statements about surface drainage in karst regions is NOT correct?","o":["Karst regions typically show a dense, well-integrated network of perennial surface rivers","When underground water reaches the base of the limestone and meets non-porous rock, it may re-emerge on the surface as a spring or resurgence","Surface valleys in karst regions are typically dry because water has cut underground channels along joints and fissures instead","Underground flow of water is more common than surface run-off in limestone areas because of the rock's high porosity, jointing and solubility"],"a":0,"e":"This statement is incorrect — karst regions are characterised by a general ABSENCE of surface drainage, not a dense network of perennial rivers, since most water sinks underground through joints and fissures. The other three statements correctly reflect both source texts."})

# ==================================================================
# SECTION 3: EROSIONAL LANDFORMS — PAVEMENTS, SWALLOW HOLES, LAPIES
# ==================================================================

upsc.append({"q":"Match List-I (Karst Erosional Feature) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Clints\nB. Grikes\nC. Lapies\nD. Swallow holes\nList-II:\n1. Small depressions carved by solution where rainwater sinks into the limestone at a point of weakness\n2. Isolated, rectangular blocks left standing on a limestone pavement\n3. Enlarged joints or trenches cut into a limestone pavement by solution\n4. An irregular surface with a maze of sharp pinnacles, grooves and ridges\nCodes:","o":["A-2, B-3, C-4, D-1","A-3, B-2, C-4, D-1","A-2, B-3, C-1, D-4","A-2, B-4, C-3, D-1"],"a":0,"e":"The correct match is A-2, B-3, C-4, D-1: clints are the isolated rectangular blocks; grikes are the enlarged joint-trenches between them; lapies (or lapiés) refer to the irregular maze of ridges and grooves; and swallow holes are the small solution depressions where rainwater sinks in."})

upsc.append({"q":"Consider the following statements about limestone pavements:\n1. A limestone pavement is formed by the progressive widening of joints and cracks through solution by rain-water or mild acid.\n2. Some limestone pavements may have originally formed beneath a soil cover and are now exposed by the later removal of that soil.\n3. Limestone pavements can only ever form on the surface and never develop beneath a soil mantle.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and directly contradicts statement 2 — the text explicitly notes limestone pavements 'may have been formed beneath the soil' and are 'now exposed by the removal of the soil cover', showing that sub-soil formation is indeed possible. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about sinkholes, drawing on the NCERT classification:\n1. A sinkhole is an opening more or less circular at the top and funnel-shaped towards the bottom.\n2. Solution sinks form purely through solution action, while collapse sinks occur when the roof of an underground void or cave beneath a sinkhole gives way.\n3. Collapse sinks are more common than solution sinks in most karst regions.\nHow many of the above statements are correct?","o":["Only two","Only one","All three","None"],"a":0,"e":"Statements 1 and 2 are correct, matching NCERT's description of sinkhole shape and the solution-sink/collapse-sink distinction. Statement 3 is incorrect — the text explicitly states 'solution sinks are more common than collapse sinks', reversing the claim made in this statement."})

upsc.append({"q":"Which one of the following best defines the karst term 'lapies' as given in the NCERT text?","o":["An irregular surface with a maze of sharp pinnacles, grooves and ridges formed by differential solution activity along parallel joints","A small to medium sized shallow depression formed solely through solution action","A landform whose opening is circular at the top and funnel-shaped towards the bottom","A column formed by the fusion of a stalactite and a stalagmite"],"a":0,"e":"Lapies (also spelt lapiés) are correctly defined as the irregular maze of sharp pinnacles, grooves and ridges that develop from differential solution activity along parallel to sub-parallel joints; the lapie field may eventually smooth into a limestone pavement. The other options describe a sinkhole and a pillar respectively, not lapies."})

# ==================================================================
# SECTION 4: DOLINE, UVALA, POLJE AND VALLEY SINKS
# ==================================================================

upsc.append({"q":"Consider the following statements about dolines, uvalas and poljes in Goh Cheng Leong's account of karst depressions:\n1. Where a number of swallow holes coalesce, a larger hollow called a doline is formed.\n2. Several dolines may merge as a result of subsidence to form a larger depression called an uvala.\n3. In Yugoslavia, some very large depressions called poljes, which may be as large as a hundred square kilometres, are partly due to faulting.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's described hierarchy of increasingly large karst depressions: doline (coalesced swallow holes) → uvala (merged dolines) → polje (very large, partly fault-controlled depression)."})

upsc.append({"q":"Consider the following statements about poljes:\n1. During the rainy season, parts of a polje floor at or near the water-table may become temporary lakes.\n2. The drier areas of a polje floor may be fertile enough to support large villages.\n3. Poljes are exclusively erosional features and never contain any faulting component in their origin.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes that large polje depressions in Yugoslavia are 'partly due to faulting', meaning they are not purely erosional/solutional features. Statements 1 and 2 are correct."})

upsc.append({"q":"According to NCERT, valley sinks or uvalas form through which one of the following processes?","o":["Sink holes and dolines joining together because of slumping of materials along their margins or due to roof collapse of caves","The steady deposition of calcium carbonate over thousands of years within a limestone cave","The faulting and subsidence of an entire limestone plateau under tectonic stress","The gradual widening of a single joint by frost action into a narrow gorge"],"a":0,"e":"NCERT describes valley sinks (uvalas) as forming when sink holes and dolines join together because of slumping of materials along their margins or due to roof collapse of caves, producing long, narrow to wide trenches — not through calcite deposition, tectonic faulting, or frost widening."})

upsc.append({"q":"Assertion (A): Karst depressions in limestone regions range enormously in scale, from small swallow holes to depressions covering a hundred square kilometres.\nReason (R): Larger karst depressions such as poljes can form through a combination of solutional widening of smaller features and structural faulting.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text describes a genuine scale progression from small swallow holes through dolines and uvalas to poljes 'as large as a hundred square kilometres', and explicitly attributes the largest poljes to a combination of solution processes and faulting, which is precisely why such a wide size range exists."})

# ==================================================================
# SECTION 5: CAVES, TUNNELS AND UNDERGROUND DRAINAGE
# ==================================================================

upsc.append({"q":"Consider the following statements about cave formation in karst regions:\n1. Cave formation is prominent where limestones are dense, massive and occur as thick beds, or where they alternate with rocks such as shales, sandstones and quartzites.\n2. Water percolating along bedding planes dissolves the limestone, producing long and narrow to wide gaps called caves.\n3. A cave with openings at both ends is called a tunnel.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching NCERT's description of the geological conditions favouring cave formation, the solutional mechanism along bedding planes, and the specific term 'tunnel' for a cave open at both ends."})

upsc.append({"q":"Which one of the following statements about underground streams and resurgence is NOT correct?","o":["Once water sinks underground in a karst region, it can never re-emerge on the surface again under any circumstance","Water descending through swallow holes can flow as underground streams and re-emerge downstream through a cave opening","When underground water meets non-porous rock at the base of the limestone, it may re-emerge on the surface as a spring or resurgence","A region honey-combed with caves and caverns fed by subterranean streams may contain ponds and lakes within the caves"],"a":0,"e":"This statement is incorrect — both source texts explicitly describe water re-emerging at the surface, either as a 'spring or resurgence' where it meets non-porous rock, or by flowing as underground streams that 're-emerge at a distance downstream through a cave opening'. The other three statements are correct."})

# ==================================================================
# SECTION 6: DEPOSITIONAL LANDFORMS — STALACTITES, STALAGMITES, PILLARS
# ==================================================================

upsc.append({"q":"Consider the following statements about stalactites and stalagmites:\n1. Stalactites hang from cave roofs, are normally broad at their base, and taper towards the free end.\n2. Stalagmites rise up from the cave floor, formed by water dripping from the surface or through the thin pipe of a stalactite immediately above.\n3. Over a long period, a stalactite and a stalagmite may eventually fuse together to form a pillar.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching both texts' description of stalactite and stalagmite growth direction, formation mechanism, and their eventual fusion into a pillar."})

upsc.append({"q":"Which one of the following statements about the chemistry of stalactite and stalagmite formation is NOT correct?","o":["Calcium carbonate is deposited when lime-charged water absorbs additional carbon dioxide from the surrounding cave air","Calcium carbonate is easily soluble in carbonated water formed when rainwater absorbs carbon dioxide","Calcite is deposited when water carrying it in solution evaporates or loses its carbon dioxide as it trickles over rough rock surfaces","Water percolating through limestone dissolves calcium carbonate, later depositing it as it moves through cave passages"],"a":0,"e":"This statement is incorrect and reverses the actual chemistry — calcium carbonate is deposited when water LOSES carbon dioxide (or evaporates), not when it absorbs MORE carbon dioxide; absorbing carbon dioxide is what makes water more acidic and better able to DISSOLVE limestone in the first place. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the shapes formed within limestone caves:\n1. Stalagmites may take the shape of a column, a disc, or a smooth, rounded bulging end.\n2. Stalactites and stalagmites are found only in temperate-climate caves and never occur in tropical limestone caves.\n3. The Batu Caves near Kuala Lumpur and the Mammoth Caves in Kentucky are cited as examples of well-developed limestone caves showing such features.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the text gives Batu Caves (Kuala Lumpur) as an example, which is a tropical location, directly disproving a claim that such features occur 'only' in temperate climates. Statements 1 and 3 are correct."})

# ==================================================================
# SECTION 7: WEATHERING TYPE AND NCERT EXERCISE-GROUNDED FACTS
# ==================================================================

upsc.append({"q":"According to the NCERT exercise on landform evolution, in which one of the following regions is chemical weathering dominant over mechanical weathering?","o":["Limestone region","Glacier region","Arid region","Humid mid-latitude upland region with granite bedrock"],"a":0,"e":"NCERT's own multiple-choice exercise identifies the limestone region as the one where chemical weathering (solution of calcium carbonate) is more dominant than mechanical weathering, consistent with the karst-forming processes described throughout the chapter."})

upsc.append({"q":"Consider the following statements comparing karst geomorphic processes with those of other environments:\n1. In limestone regions, the dominant and almost exclusive geomorphic process is chemical solution.\n2. In arid deserts, by contrast, mechanical weathering and wind action dominate over chemical solution.\n3. Underground flow of water is more common than surface run-off in limestone areas because of the rock's high porosity, jointing and solubility.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct: limestone karst landscapes are shaped overwhelmingly by chemical solution, arid deserts are instead dominated by mechanical weathering and wind processes, and limestone's porosity, jointing and solubility together explain why underground flow dominates over surface run-off there."})

# ==================================================================
# SECTION 8: MAJOR LIMESTONE REGIONS OF THE WORLD
# ==================================================================

upsc.append({"q":"Consider the following statements about the major limestone regions of the world:\n1. The most characteristic stretch of limestone occurs in north-west Yugoslavia, in the Karst district itself.\n2. The Causses district of southern France and the Pennines of Britain (Yorkshire and Derbyshire) are also notable limestone karst regions.\n3. The Yucatan Peninsula of Mexico and the Cockpit Country of Jamaica are examples of limestone regions found only in continental Europe.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Yucatan Peninsula (Mexico) and Cockpit Country (Jamaica) are located in the Americas/Caribbean, not continental Europe, directly contradicting the claim. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following pairs of limestone cave and its correct country/location is INCORRECTLY matched?","o":["Carlsbad Cave — United Kingdom","Mammoth Caves — Kentucky, U.S.A.","Postojna Caves — Yugoslavia","Batu Caves — Kuala Lumpur, Peninsular Malaysia"],"a":0,"e":"This pairing is incorrect — Carlsbad Cave is located in New Mexico, U.S.A., not the United Kingdom. Mammoth Caves (Kentucky), Postojna Caves (Yugoslavia), and Batu Caves (Kuala Lumpur) are all correctly matched to their locations in the text."})

# ==================================================================
# SECTION 9: HUMAN ACTIVITIES IN KARST REGIONS
# ==================================================================

upsc.append({"q":"Consider the following statements about human activities in karst regions:\n1. The porosity of karst rocks and the absence of surface drainage generally make vegetative growth difficult, limiting agriculture to poor grass and short turf with some sheep grazing.\n2. Limestone vegetation in tropical regions can nonetheless be luxuriant because of heavy year-round rainfall.\n3. Lead is cited as the only mineral of importance occurring in veins in association with limestone, besides its use as a building material and in the cement industry.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's description of typically poor karst agriculture, the exception of luxuriant tropical karst vegetation given adequate rainfall, and lead as the notable karst-associated mineral alongside limestone's use in construction and cement."})

upsc.append({"q":"In Peninsular Malaysia, limestone outcrops of the Kledang Range and the Main Range are chiefly quarried for which one of the following purposes?","o":["Supplying the Pan-Malaysia and Tasek Cement Works","Extracting lead ore for the electronics industry","Mining coal for thermal power generation","Producing dimension stone for temple architecture exclusively"],"a":0,"e":"The text specifically states these limestone outcrops are quarried for the Pan-Malaysia and Tasek Cement Works, reflecting limestone's common economic use as a raw material for cement production, not for lead, coal, or exclusively decorative stonework."})

# ==================================================================
# SECTION 10: CHALK LANDFORMS
# ==================================================================

upsc.append({"q":"Consider the following statements about chalk landforms:\n1. Like limestone, chalk regions have little or no surface drainage, and valleys that once contained rivers are now dry, often called coombes.\n2. Chalk forms low, rounded hills in southern and south-eastern England, locally called 'downs', and also occurs in northern France.\n3. Because of the friable (crumbly) nature of chalk, swallow holes and underground cave networks generally develop just as extensively as in hard limestone.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that because of chalk's friable nature, swallow holes and underground cave networks 'do not generally develop', unlike in harder, well-jointed limestone. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following is NOT a correct point of contrast between limestone karst regions and chalk regions, as described in the text?","o":["Chalk regions develop far more extensive swallow holes and cave networks than hard, jointed limestone regions","Chalk is used for pasture and sometimes arable farming, and is covered with short turf and, in places, woodland","'Karst' features are normally found in hard, jointed limestone hills rather than in softer, more porous chalk","Dry valleys called coombes are a characteristic surface feature of chalk country, analogous to dry valleys in limestone country"],"a":0,"e":"This statement is incorrect — it reverses the actual relationship. Because chalk is softer, more porous and friable than hard, jointed limestone, it develops FEWER swallow holes and cave networks than limestone, not more. The other three statements accurately reflect the text's contrast between the two rock types."})

upsc.append({"q":"Consider the following statements distinguishing 'limestone' from 'chalk':\n1. Chalk is described as a very pure, white and rather soft form of limestone.\n2. Karst-type features such as swallow holes and cave systems are typically better developed in hard, well-jointed limestone than in chalk.\n3. Neither limestone nor chalk is soluble in rain-water, so neither develops solutional landforms of any kind.\nHow many of the above statements are correct?","o":["Only two","Only one","All three","None"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is incorrect and contradicts the entire premise of the chapter — limestone is explicitly described as 'soluble in rain-water', which is exactly why karst solutional landforms (pavements, sinkholes, caves) develop in the first place; chalk, while less prone to well-developed cave systems, still forms dry valleys (coombes) through related processes."})

# ==================================================================
# SECTION 11: ADDITIONAL GROUNDED QUESTIONS (ENRICHMENT)
# ==================================================================

upsc.append({"q":"Consider the following features:\n1. Dolines\n2. Erratics\n3. Inselbergs\n4. Grikes\n5. Canyons\n6. Coombes\nHow many of the above features are associated with a karst or related limestone/chalk region?","o":["Only three","Only two","Only four","All six"],"a":0,"e":"Only three of the listed features — dolines, grikes, and coombes — are associated with karst or chalk regions. Erratics are glacial deposits, inselbergs are desert/semi-arid residual hills, and canyons are typically river-cut features in arid plateau country, none of which are characteristic karst/chalk landforms."})

upsc.append({"q":"The most characteristic feature commonly used to identify the karst region is which one of the following?","o":["The absence of surface drainage","The presence of extensive flood plains","The predominance of earthquakes","A lack of any mineral resources"],"a":0,"e":"The absence of surface drainage — caused by water sinking underground through joints and fissures in the limestone — is identified as the most characteristic feature of a karst region. Extensive flood plains, frequent earthquakes, and a complete lack of minerals are not defining karst characteristics."})

upsc.append({"q":"A well-developed, exposed limestone pavement with clints and grikes is chiefly the result of which one of the following processes?","o":["The action of rain-water on well-jointed limestone","Frost action on a horizontally bedded limestone plain","Rivers running directly over the surface of a karst region","Overgrazing in a chalk country"],"a":0,"e":"A limestone pavement with clints (blocks) and grikes (enlarged joints) forms chiefly through the solutional action of rain-water on well-jointed limestone, progressively widening the joints — not through frost action, surface river flow (karst regions largely lack surface rivers), or overgrazing, which is unrelated to pavement formation."})

upsc.append({"q":"Cave dwellers or explorers in limestone karst regions face a particular risk of being trapped by which one of the following hazards, given the text's description of subterranean stream behaviour?","o":["Being drowned by underground streams and cave flooding","Being frost-bitten due to permanently sub-zero cave temperatures","Being gas-poisoned by volcanic emissions within the caves","Being buried by volcanic ash falling from cave ceilings"],"a":0,"e":"Since limestone caves are honey-combed with cave streams, ponds and lakes fed by subterranean drainage, sudden rises in underground water levels pose a genuine drowning risk to cave explorers — a hazard directly tied to the karst region's underground hydrology, unlike frost-bite, volcanic gas, or ash, which are unrelated to limestone cave environments."})

upsc.append({"q":"Consider the following statements about the Dinaric Alps region of the former Yugoslavia:\n1. It is cited as containing one of the best-developed karst landscapes in the world.\n2. This is the same broad region after which the term 'karst topography' itself is named.\n3. The region owes its karst development entirely to volcanic activity rather than to limestone solution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — karst development in this region results from the solution of limestone by acidic rainwater, not from volcanic activity, which plays no role in the text's account of karst formation. Statements 1 and 2 are correct: the Dinaric Alps area is a classic, well-developed karst landscape and lies within the broader Balkan Karst region that gave the topography its name."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "limestone_and_chalk_landforms",
    "title": "Limestone and Chalk Landforms",
    "desc": "Karst topography (from Goh Cheng Leong's Physical Geography and NCERT XI Fundamentals of Physical Geography, Ch.7): nature of limestone and chalk; karst region characteristics and underground drainage; erosional landforms (limestone pavements, clints, grikes, swallow holes, solution/collapse sinks, lapies); doline, uvala and polje; caves and tunnels; depositional landforms (stalactites, stalagmites, pillars); dominance of chemical weathering; major world limestone regions; human activities in karst regions; and chalk landforms (coombes, downs)",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch08_limestone_chalk_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
