import json

upsc = []

# ==================================================================
# SECTION 1: EXPLORING THE OCEANS
# ==================================================================

upsc.append({"q":"Consider the following statements about ocean exploration:\n1. Formal oceanographic investigation began with the British expedition of the Challenger (1873-6), the first successful world-wide deep-sea expedition.\n2. The International Council for the Exploration of the Sea, headquartered in Copenhagen, is described as the most famous international oceanographic research centre.\n3. Because ocean exploration is inexpensive and simple, it is generally best undertaken by small private individuals rather than international bodies.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly describes ocean exploration as 'a very expensive matter' requiring specially equipped vessels for long periods, which is precisely why 'large-scale oceanographic researches are thus best undertaken by international bodies', not small private individuals. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 2: RELIEF OF THE OCEAN (GOH CHENG LEONG)
# ==================================================================

upsc.append({"q":"Consider the following statements about the continental shelf, as described by Goh Cheng Leong:\n1. It is the seaward extension of the continent from the shoreline to the continental edge, approximately marked by the 100-fathom isobath.\n2. Its width is fairly uniform worldwide, generally close to 80 km everywhere regardless of coastal geology.\n3. Off broad lowland coasts like Arctic Siberia, a maximum width of 1,200 km has been recorded, while off steep coasts like the Rockies and Andes, it may be entirely absent.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the text explicitly describes continental shelf width as varying 'greatly', from a few kilometres in some areas to over 1,200 km in Arctic Siberia, not a fairly uniform width worldwide. Statements 1 and 3 are correct."})

upsc.append({"q":"Which one of the following statements about the geographical significance of continental shelves is NOT correct?","o":["Continental shelves are generally poor fishing grounds because their shallow depth prevents sunlight penetration and plankton growth","Continental shelves are the richest fishing grounds in the world, e.g. the Grand Banks, the North Sea and the Sunda Shelf","The limited depth and gentle slope of continental shelves keep out cold under-currents and increase tidal heights","Many of the world's greatest seaports, including Southampton, London and Singapore, are located on continental shelves"],"a":0,"e":"This statement is incorrect and reverses the actual relationship — shallow continental shelves allow sunlight to penetrate, encouraging plankton growth that makes them the RICHEST fishing grounds in the world, not poor ones. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about ocean deeps (trenches), as described by Goh Cheng Leong:\n1. Most of the deepest ocean trenches are located in the midst of the open oceans, far from any continent.\n2. The Mariana Trench, near Guam Island, at over 10,900 metres deep, is the greatest known ocean deep, exceeding the height of Mount Everest.\n3. Other notable deeps mentioned include the Mindanao Deep, the Tonga Trench and the Japanese Trench, all in the Pacific Ocean.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — the text explicitly states that, contrary to expectation, most deep trenches are found 'close to the continents', particularly in the Pacific, not in the midst of the open oceans. Statements 2 and 3 are correct."})

upsc.append({"q":"Match List-I (Ocean Floor Deposit Type) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Muds\nB. Oozes\nC. Clays\nList-II:\n1. Pelagic deposits made of shelly/skeletal remains of marine micro-organisms\n2. Terrigenous deposits derived from land, mainly on continental shelves\n3. Deep-basin deposits, abundant in the Pacific, believed to include accumulated volcanic dust\nCodes:","o":["A-2, B-1, C-3","A-1, B-2, C-3","A-2, B-3, C-1","A-3, B-1, C-2"],"a":0,"e":"The correct match is A-2, B-1, C-3: muds are terrigenous (land-derived) deposits on continental shelves; oozes are pelagic deposits of marine organism remains; and clays (especially red clay) occur in deep ocean basins, partly from volcanic dust."})

# ==================================================================
# SECTION 3: OCEAN FLOOR RELIEF (NCERT XI PART 1, CH.13 "WATER (OCEANS)")
# ==================================================================

upsc.append({"q":"According to NCERT, the ocean floor can be divided into four MAJOR divisions. Which one of the following is NOT one of these four major divisions, but is instead classified as a minor relief feature?","o":["Guyot","Continental Shelf","Continental Slope","Deep Sea Plain"],"a":0,"e":"NCERT's own exercise identifies the guyot (a flat-topped seamount) as a MINOR relief feature, alongside seamounts and atolls — distinct from the four MAJOR divisions of the ocean floor: continental shelf, continental slope, deep sea plain, and oceanic deeps."})

upsc.append({"q":"Consider the following statements about the continental shelf and slope, according to NCERT:\n1. The continental shelf has an average gradient of about 1° or even less, ending at a steep drop called the shelf break.\n2. The continental slope has a steeper gradient, varying between 2° and 5°, with canyons and trenches observed in this region.\n3. The average width of continental shelves worldwide is about 80 km, though the Siberian shelf in the Arctic Ocean stretches to about 1,500 km.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, precisely matching NCERT's figures for continental shelf gradient and shelf break, continental slope gradient, and the contrast between average shelf width and the exceptionally wide Siberian shelf."})

upsc.append({"q":"Which one of the following statements about oceanic deeps (trenches), according to NCERT, is NOT correct?","o":["Oceanic deeps are found scattered evenly across all major oceans, with no particular concentration in any single ocean","Oceanic deeps are relatively steep-sided, narrow basins, some 3-5 km deeper than the surrounding ocean floor","Oceanic deeps occur at the bases of continental slopes and along island arcs, associated with active volcanoes and strong earthquakes","Of the 57 deeps explored so far, 32 are in the Pacific Ocean, 19 in the Atlantic Ocean, and 6 in the Indian Ocean"],"a":0,"e":"This statement is incorrect — NCERT's own figures show oceanic deeps are heavily concentrated in the Pacific Ocean (32 of 57 explored deeps), not evenly scattered across all oceans. The other three statements are correct."})

upsc.append({"q":"Consider the following minor relief features of the ocean floor, according to NCERT:\n1. Seamount: a volcanic, pointed-summit mountain rising from the seafloor that does not reach the surface, e.g. the Emperor Seamount.\n2. Guyot: a flat-topped seamount showing evidence of gradual subsidence.\n3. Submarine canyon: a deep valley cutting across continental shelves and slopes, often extending from large river mouths, e.g. the Hudson Canyon.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching NCERT's precise definitions and named examples of seamounts, guyots, and submarine canyons as minor ocean-floor relief features."})

upsc.append({"q":"Assertion (A): Mid-oceanic ridges and oceanic trenches are both geologically significant zones studied closely by plate tectonics researchers.\nReason (R): According to NCERT, oceanic deeps occur at the bases of continental slopes and along island arcs, and are associated with active volcanoes and strong earthquakes, making them important indicators of plate movement.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly links oceanic deeps to island arcs, active volcanism and strong earthquakes, which is exactly why such trenches (alongside mid-oceanic ridges, also volcanically active) are key features studied in plate tectonics research."})

# ==================================================================
# SECTION 4: THERMOCLINE AND OCEAN TEMPERATURE STRUCTURE (NCERT)
# ==================================================================

upsc.append({"q":"Consider the following statements about the thermocline, according to NCERT:\n1. The thermocline is the boundary region, typically beginning 100-400 m below the surface, where temperature decreases rapidly with depth.\n2. About 90 per cent of the total volume of ocean water lies below the thermocline, where temperatures approach 0°C.\n3. The thermocline layer itself is typically about 500-1,000 m thick.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching NCERT's precise description of the thermocline's depth range, thickness, and the fact that most ocean water by volume lies below it in near-freezing conditions."})

upsc.append({"q":"Which one of the following statements about the three-layer ocean temperature structure (middle and low latitudes), according to NCERT, is NOT correct?","o":["The Arctic and Antarctic circles show the same distinct three-layer structure as the tropics, with a clear warm surface layer year-round","The top warm layer, about 500 m thick with temperatures of 20-25°C, is present year-round in the tropics but only in summer in mid-latitudes","The thermocline layer lies below the top warm layer and shows a rapid decrease in temperature with depth","The third, coldest layer extends down to the deep ocean floor"],"a":0,"e":"This statement is incorrect — NCERT explicitly states that in the Arctic and Antarctic circles, only ONE layer of uniformly cold water exists from surface to floor (since temperature barely changes with depth there), unlike the three-layer structure found in middle and low latitudes. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about factors affecting ocean temperature distribution, according to NCERT:\n1. Offshore winds tend to drive warm surface water away from the coast, causing upwelling of cold water from below and lowering coastal temperature.\n2. Onshore winds tend to pile up warm water near the coast, raising coastal temperature.\n3. The unequal distribution of land and water between hemispheres has no bearing on ocean temperature, since water temperature depends only on latitude.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly lists 'unequal distribution of land and water' between hemispheres as a distinct factor affecting ocean temperature (the Northern Hemisphere, with more land, receives more heat), not something irrelevant beyond latitude. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 5: SALINITY OF THE OCEAN — GENERAL PRINCIPLES (BOTH BOOKS)
# ==================================================================

upsc.append({"q":"Consider the following statements about ocean salinity:\n1. Sodium chloride alone constitutes more than 77 per cent of the dissolved mineral matter in sea water.\n2. Due to the free movement of ocean water, the proportions of different salts remain remarkably constant across oceans and depths, even though overall concentration (salinity) varies by location.\n3. Salinity distribution is mapped using isohalines, lines joining places of equal salinity.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching Goh Cheng Leong's account of sodium chloride's dominance among dissolved salts, the constancy of salt proportions despite varying overall concentration, and the use of isohalines to map salinity."})

upsc.append({"q":"According to NCERT, a salinity value of 24.7 parts per thousand is significant because it represents which one of the following?","o":["The upper limit demarcating 'brackish water'","The average salinity of the open ocean worldwide","The minimum salinity required for coral polyps to survive","The salinity threshold below which sea water freezes at 0°C"],"a":0,"e":"NCERT specifically identifies 24.7‰ as the upper limit used to demarcate 'brackish water', distinct from the open ocean's typical salinity range (33-37‰ per NCERT), coral survival requirements, or freezing behaviour, which are unrelated concepts."})

upsc.append({"q":"Consider the following statements about factors affecting salinity variation, drawing on both textbooks:\n1. Waters near the high-pressure Trade Wind Desert belts (20°-30° N and S) tend to have high salinity due to high evaporation and low rainfall.\n2. Regions receiving large river inflows (e.g. from the Amazon, Ganges or Zaire) tend to have diluted, lower salinity.\n3. In wholly or partially enclosed seas that do not mix freely with ocean currents, salinity tends to be lower than in the open ocean.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Goh Cheng Leong explicitly states that in wholly or partially enclosed seas not penetrated by ocean currents (e.g. Caspian Sea, Mediterranean, Red Sea, Persian Gulf), salinity tends to be HIGH (often over 37‰), not lower than the open ocean. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the vertical distribution of salinity, according to NCERT:\n1. Salinity generally increases with depth, with a distinct zone called the halocline where it increases sharply.\n2. Higher-salinity, denser water tends to sink below lower-salinity water, producing stratification by salinity.\n3. Salinity at great ocean depths fluctuates wildly because deep water is constantly exchanged with the surface.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly states that salinity at depth is 'very much fixed' because there is no mechanism there for water to be lost or salt to be added, contrary to a claim of wild fluctuation from constant exchange with the surface. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 6: TEMPERATURE OF OCEAN WATER (GOH CHENG LEONG)
# ==================================================================

upsc.append({"q":"Which one of the following statements about ocean water temperature, per Goh Cheng Leong, is NOT correct?","o":["The annual range of ocean surface temperature is generally larger than that of adjacent land areas, because water heats and cools faster than land","Mean surface temperature decreases from about 21°C at the equator to around 13°C at 45° latitude, dropping near freezing at the poles","Warm currents like the North Atlantic Drift keep the Norwegian coast ice-free even at 60°-70°N","Cold currents like the Labrador Current keep eastern Canadian ports icebound for almost half the year even at 45°N"],"a":0,"e":"This statement is incorrect and reverses the actual relationship — the text explicitly states water warms and cools MORE SLOWLY than land, giving oceans a SMALLER (not larger) annual temperature range than adjacent land. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about vertical temperature variation in the ocean, per Goh Cheng Leong:\n1. Temperature decreases rapidly for the first 200 fathoms, then more slowly until about 500 fathoms.\n2. Below 2,000 fathoms, ocean water is uniformly cold, just a little above freezing point.\n3. Even in the deepest ocean trenches more than 10 km below the surface, the water never actually freezes.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's description of the two-stage rate of temperature decrease with depth, the uniformly cold deep zone below 2,000 fathoms, and the notable fact that even the deepest trench water remains just above freezing rather than freezing solid."})

# ==================================================================
# SECTION 7: MOVEMENTS OF OCEAN CURRENTS — CAUSES (GOH CHENG LEONG)
# ==================================================================

upsc.append({"q":"Consider the following statements about the factors influencing ocean current movement, per Goh Cheng Leong:\n1. Planetary winds are described as probably the dominant influence on ocean current flow.\n2. The earth's rotation deflects currents clockwise in the northern hemisphere and anti-clockwise in the southern hemisphere.\n3. A landmass has no significant effect on current direction, since currents simply pass through or around it without being diverted.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states 'a land mass always obstructs and diverts a current', citing the Brazilian 'shoulder' at Cape Sao Roque splitting the South Equatorial Current, directly contradicting a claim that land has no effect. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the North Indian Ocean currents is NOT correct?","o":["Currents in the North Indian Ocean remain constant in direction throughout the year, unaffected by seasonal wind changes","The direction of currents in the North Indian Ocean reverses completely between summer and winter","In summer, currents are driven by the South-West Monsoon as the South-West Monsoon Drift","In winter, currents are driven by the North-East Monsoon as the North-East Monsoon Drift"],"a":0,"e":"This statement is incorrect — the text explicitly describes the North Indian Ocean currents as demonstrating 'most convincingly the dominant effects of winds', with a complete reversal of direction between the South-West Monsoon Drift (summer) and the North-East Monsoon Drift (winter), not constancy throughout the year. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Gulf Stream Drift system:\n1. The Gulf Stream is described as one of the strongest ocean currents, 56 to 160 km wide and about 610 metres deep.\n2. On reaching Cape Hatteras, the current is deflected eastwards under the combined influence of the Westerlies and the earth's rotation, continuing to Europe as the North Atlantic Drift.\n3. In the middle of this circulatory ring lies an area with no perceptible current, called the Sargasso Sea, where floating seaweed gathers.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching the text's description of the Gulf Stream's scale, its deflection at Cape Hatteras into the North Atlantic Drift, and the still, seaweed-filled Sargasso Sea at the centre of the North Atlantic gyre."})

upsc.append({"q":"Consider the following statements about the Peruvian (Humboldt) Current and its associated effects:\n1. The cold Peruvian Current chills onshore winds, making the Chilean and Peruvian coasts practically rainless.\n2. The cold, nutrient-rich waters attract huge shoals of fish, which in turn attract vast numbers of sea-birds.\n3. The droppings of these sea-birds form thick deposits of guano, a valuable fertilizer, on coastal cliffs and islands.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's causal chain: the cold Peruvian Current chills onshore winds (creating a rainless coast), sustains rich marine life that attracts fish and sea-birds, whose droppings form valuable guano deposits."})

upsc.append({"q":"Assertion (A): The east coast of continents in low and middle latitudes is generally warmed by ocean currents, while the west coast in the same latitude band is generally cooled.\nReason (R): Trade Winds and the general clockwise (Northern Hemisphere) or anti-clockwise (Southern Hemisphere) gyre circulation typically carry warm equatorial water towards eastern continental coasts and cold water from higher latitudes towards western coasts in the low-to-middle latitude zone.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text's examples (warm Brazilian Current off eastern Brazil, warm Gulf Stream off the south-eastern U.S.A., versus cold Peruvian/Benguela/Californian Currents off western coasts) all follow exactly this gyre-driven pattern of warm currents reaching eastern coasts and cold currents reaching western coasts in low-to-middle latitudes."})

# ==================================================================
# SECTION 8: ADDITIONAL GROUNDED QUESTIONS (ENRICHMENT)
# ==================================================================

upsc.append({"q":"Consider the following statements about the circulation of the North Atlantic and North Pacific Oceans:\n1. In the North Atlantic, the Cayenne Current joins the North Equatorial Current and flows north-westwards, eventually feeding the Gulf Stream.\n2. In the North Pacific, the North Equatorial Current is blown by the North-East Trade Winds into the East China Sea as the Kuroshio (Japan Current), whose warm waters continue polewards as the North Pacific Drift.\n3. Both the North Atlantic and North Pacific gyres circulate anti-clockwise, in exactly the same rotational sense as their Southern Hemisphere counterparts.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Northern Hemisphere ocean gyres circulate CLOCKWISE (due to the earth's rotation), while Southern Hemisphere gyres circulate anti-clockwise; they are opposite, not the same rotational sense. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about cold currents in the Pacific Ocean:\n1. The cold Bering (Alaskan) Current creeps southwards from the Bering Strait and, joined by the Okhotsk Current, meets the warm Japan Current as the Oyashio off Hokkaido.\n2. Part of this cold water drifts southwards as the Californian Current along the western U.S.A. coast, eventually joining the North Equatorial Current.\n3. The cold Humboldt (Peruvian) Current in the South Pacific is diverted northwards along South America after being obstructed by the tip of southern Chile.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching the text's description of the Bering/Okhotsk/Oyashio convergence in the North Pacific, the Californian Current completing the North Pacific gyre, and the Humboldt Current's origin from the West Wind Drift being diverted north by southern Chile."})

upsc.append({"q":"Which one of the following statements about the Indian Ocean's current circulation is NOT correct?","o":["The South Indian Ocean has no organised current circuit at all, unlike the Atlantic and Pacific Oceans","In the South Indian Ocean, the Equatorial Current turns southwards past Madagascar as the Agulhas (Mozambique) Current before merging with the West Wind Drift","The West Australian Current forms part of the South Indian Ocean's current circuit, flowing equatorwards","The North Indian Ocean uniquely shows a complete seasonal reversal of current direction, driven by the changing monsoon winds"],"a":0,"e":"This statement is incorrect — the text explicitly describes the South Indian Ocean currents as forming 'a circuit' just like the other oceans (via the Agulhas/Mozambique Current, West Wind Drift, and West Australian Current), not lacking any organised circulation. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "the_oceans",
    "title": "The Oceans",
    "desc": "Ocean geography (from Goh Cheng Leong's Physical Geography and NCERT XI Fundamentals of Physical Geography, Ch.13 'Water (Oceans)'): ocean exploration; relief of the ocean floor (continental shelf, slope, deep sea plain, oceanic deeps, and minor features like seamounts, guyots, submarine canyons, mid-oceanic ridges); ocean floor deposits; salinity of the ocean and its variation; the thermocline and vertical/horizontal temperature structure; and the movement and circulation of ocean currents (Atlantic, Pacific and Indian Ocean systems)",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch12_oceans_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
