import json

upsc = []

# ==================================================================
# SECTION 1: WEATHER VS CLIMATE
# ==================================================================

upsc.append({"q":"Consider the following statements about the distinction between weather and climate:\n1. Weather refers to atmospheric conditions at a particular place and time, and can vary tremendously even within a small area.\n2. Climate refers to the average atmospheric conditions of an area over a considerable period, with a minimum of about 35 years desirable for climatic averages.\n3. The climate of temperate latitudes is generally far more variable than that of the tropics.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's definitions of weather versus climate, the 35-year benchmark for climatic averages, and the observation that temperate climates (e.g. Britain) are more variable than tropical ones (e.g. Egypt)."})

upsc.append({"q":"Which one of the following is NOT correctly identified in the text as being significantly affected by local weather conditions?","o":["A chess tournament","An airport ground control station","A geographical outing/expedition","Military operations in a river basin region"],"a":0,"e":"A chess tournament, being an indoor activity unaffected by outdoor atmospheric conditions, is the one activity NOT significantly affected by local weather, unlike airport operations, outdoor expeditions, and military operations, all of which depend heavily on weather conditions."})

# ==================================================================
# SECTION 2: MEASURING RAINFALL
# ==================================================================

upsc.append({"q":"Consider the following statements about the rain-gauge:\n1. It consists of a copper cylinder with a metal funnel leading into a smaller container, designed with a small hole to minimise evaporation of collected rain.\n2. The gauge should be sited close to tall buildings and trees so that wind does not disturb its readings.\n3. A 'rain-day' is reckoned as a 24-hour period with at least 0.25 mm of rain recorded, while a 'wet day' requires more than 1 mm.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the text explicitly states the gauge should be sited 'well away from tall buildings, high trees and other objects which would shelter it', not close to them. Statements 1 and 3 are correct."})

upsc.append({"q":"Which one of the following statements about rainfall mapping and recording is NOT correct?","o":["Places with equal mean annual rainfall are joined on maps by lines called isotherms","A rainfall histogram shows monthly rainfall regime over a year, while a dispersal diagram shows the range of dry and wet years over many years","The mean annual rainfall is derived from averages of annual rainfall over a long period, such as 35 years","An isohyet is a line joining places of equal mean annual rainfall"],"a":0,"e":"This statement is incorrect — lines joining places of equal rainfall are called ISOHYETS, not isotherms (which instead join places of equal temperature). The other three statements are correct, including the correct definition of isohyet in the fourth option."})

# ==================================================================
# SECTION 3: MEASURING PRESSURE
# ==================================================================

upsc.append({"q":"Consider the following statements about the mercury barometer:\n1. It was invented by the scientist Galileo and his assistant Torricelli in 1643.\n2. Mercury is used because it is the heaviest liquid known; if water were used instead, the column would need to be about 10 metres tall for normal atmospheric pressure.\n3. At sea-level, the mercury column normally stands at about 700 mm, rising during low pressure and falling during high pressure.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual relationship — at sea-level the mercury column normally stands at about 760 mm, RISING during high pressure (to about 790 mm) and FALLING during low pressure (to about 700 mm), not the other way round. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about atmospheric pressure units and corrections is NOT correct?","o":["A normal atmospheric pressure of 760 mm of mercury is equivalent to about 1,013 millibars","Pressure readings require no correction for altitude, since barometers automatically compensate for elevation","Pressure readings must be corrected for latitude, since the barometer is sensitive to gravitational variation","A sea-level pressure reading is roughly halved at an altitude of about 5.6 km above sea-level"],"a":0,"e":"This statement is incorrect — the text explicitly states that professional meteorological work 'requires very accurate readings' with 'corrections... made in respect to altitude, latitude and temperature', directly contradicting a claim that no altitude correction is needed. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the aneroid barometer and altimeter:\n1. An aneroid barometer uses a small metal container with most air driven out, registering pressure changes through the movement of its lid.\n2. An altimeter is a modified aneroid barometer used in aeroplanes, giving readings directly in units of altitude rather than pressure.\n3. Pressure decreases with altitude at an approximate rate of 25.4 mm mercury drop for every 270 metres of ascent.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching the text's description of aneroid barometer mechanics, the altimeter's specialised altitude-reading function, and the specific pressure-altitude conversion rate given."})

# ==================================================================
# SECTION 4: MEASURING TEMPERATURE
# ==================================================================

upsc.append({"q":"Consider the following statements about the Stevenson Screen:\n1. It is a white wooden box raised about 1.2 metres above the ground on stilts, with a double-layered roof and louvered sides to allow air circulation while excluding direct sun.\n2. It is painted white specifically to reflect as much heat as possible, rather than to look attractive.\n3. It typically houses maximum and minimum thermometers as well as dry- and wet-bulb thermometers.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's description of the screen's construction, its white colour serving to reflect heat (per the sample objective question), and its typical instrument contents."})

upsc.append({"q":"Which one of the following statements about maximum and minimum thermometers is NOT correct?","o":["The maximum thermometer typically records its highest reading in the middle of the night or early morning","The maximum thermometer's mercury expands on rising temperature, pushing a metal indicator that remains at the highest level reached","The minimum thermometer uses alcohol, whose contraction on cooling drags an indicator towards the bulb via surface tension","The mean daily temperature is calculated as the average of the day's maximum and minimum readings"],"a":0,"e":"This statement is incorrect and describes the MINIMUM thermometer's typical timing, not the maximum's — the text states the maximum temperature is reached during the day (daytime heating), while the minimum 'probably occurs in the middle of the night or early in the morning'. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about temperature ranges and conversions:\n1. The diurnal range of temperature is the difference between a day's maximum and minimum temperatures.\n2. The annual range of temperature is the difference between the hottest and coldest months of the year.\n3. To convert Fahrenheit to Centigrade, the correct formula is (°F − 32) × 1.8.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text gives the correct conversion formula as (°F − 32) ÷ 1.8, not multiplied by 1.8, to obtain Centigrade. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 5: HUMIDITY
# ==================================================================

upsc.append({"q":"Consider the following statements about humidity:\n1. Absolute humidity is the actual amount of water vapour present in the air, expressed in grams per cubic metre.\n2. Relative humidity is the ratio of the actual water vapour present to the total amount the air could hold at that temperature, expressed as a percentage.\n3. When relative humidity reaches 100 per cent, the air is said to be at dew-point and is completely saturated.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the standard definitions of absolute humidity, relative humidity, and saturation at dew-point."})

upsc.append({"q":"Which one of the following statements about the hygrometer (wet- and dry-bulb thermometers) is NOT correct?","o":["A large difference between the dry-bulb and wet-bulb readings indicates high relative humidity","The wet-bulb thermometer always shows a lower reading than the dry-bulb, due to evaporative cooling from its moist wick","If the wet-bulb and dry-bulb readings are identical, the relative humidity is 100 per cent (the air is saturated)","The dry-bulb thermometer is simply the ordinary thermometer measuring shade temperature"],"a":0,"e":"This statement is incorrect and reverses the actual relationship — a LARGE difference between dry- and wet-bulb readings indicates LOW relative humidity (more evaporative cooling occurring because the air is dry), while a SMALL difference indicates high relative humidity. The other three statements are correct."})

# ==================================================================
# SECTION 6: WINDS
# ==================================================================

upsc.append({"q":"Consider the following statements about wind measurement:\n1. Wind direction is measured using a wind vane or weather cock, and winds are named for the direction they blow FROM.\n2. A wind rose records the direction of prevailing winds at a place over a period such as a month, including days with no wind ('calms').\n3. Wind speed is measured by an anemometer, whose readings tend to be perfectly accurate even immediately after a gust subsides, due to its instant response.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly notes anemometer readings are 'not absolutely accurate because after the winds have abated, the rotation continues due to its own momentum', not perfectly instantaneous. Statements 1 and 2 are correct."})

upsc.append({"q":"According to the Beaufort Wind Scale as described in the text, which one of the following correctly orders these wind effects from LOWEST to HIGHEST Beaufort number?","o":["Smoke rises vertically → leaves rustle, vanes moved → whole tree in motion, walking inconvenienced → widespread devastation","Whole tree in motion, walking inconvenienced → leaves rustle, vanes moved → smoke rises vertically → widespread devastation","Widespread devastation → whole tree in motion → leaves rustle → smoke rises vertically","Leaves rustle, vanes moved → smoke rises vertically → whole tree in motion → widespread devastation"],"a":0,"e":"The correct ascending order is: calm (smoke rises vertically) → gentle breeze (leaves rustle, vanes moved) → strong breeze/gale-level (whole tree in motion, walking inconvenienced) → hurricane (widespread devastation) — matching the Beaufort Scale's progression from calm to hurricane-force winds described in the text."})

# ==================================================================
# SECTION 7: CLOUDS (GOH CHENG LEONG'S TEN-TYPE CLASSIFICATION)
# ==================================================================

upsc.append({"q":"Match List-I (Cloud Type) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Cirrus\nB. Cirrocumulus\nC. Cirrostratus\nD. Cumulonimbus\nList-II:\n1. A thin white sheet or veil producing a characteristic 'halo' around sun or moon\n2. Feathery, fibrous 'mares' tails' indicating fair weather\n3. A towering, anvil-topped 'thunder-cloud' bringing convectional rain, lightning and thunder\n4. White globular masses forming ripples in a 'mackerel sky'\nCodes:","o":["A-2, B-4, C-1, D-3","A-2, B-1, C-4, D-3","A-4, B-2, C-1, D-3","A-2, B-4, C-3, D-1"],"a":0,"e":"The correct match is A-2, B-4, C-1, D-3: cirrus gives feathery 'mares' tails'; cirrocumulus forms a rippled 'mackerel sky'; cirrostratus produces a milky sky with a halo; and cumulonimbus is the towering, anvil-topped thunder-cloud."})

upsc.append({"q":"Consider the following statements about cloud classification by height:\n1. High clouds, mainly cirrus types, occur at roughly 6,100-12,200 metres above ground.\n2. Medium clouds, mainly 'alto' types, occur at roughly 2,100-6,000 metres.\n3. Low clouds, mainly stratus types, occur below about 2,100 metres, while clouds of great vertical extent (cumulus types) have no fixed single height band.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching the text's height-based four-tier cloud classification: high (cirrus family), medium (alto family), low (stratus family), and vertically-developed (cumulus family) clouds."})

upsc.append({"q":"Which one of the following statements about stratus and nimbostratus clouds is NOT correct?","o":["Stratus clouds are associated with vigorous convectional uplift and typically bring short, intense thunderstorms","Stratus is a very low, uniformly grey cloud resembling a low ceiling or highland fog, bringing dull weather with light drizzle","Nimbostratus is a dark, clearly layered 'rain cloud' bringing continuous rain, snow or sleet","Stratus clouds can reduce aircraft visibility and pose a danger to aviation"],"a":0,"e":"This statement is incorrect — stratus clouds are low, layered clouds associated with gentle, prolonged dull weather, not vigorous convectional uplift or short intense thunderstorms (which are instead associated with cumulonimbus). The other three statements are correct."})

# ==================================================================
# SECTION 8: HAZE, MIST AND FOG (GOH CHENG LEONG)
# ==================================================================

upsc.append({"q":"Consider the following statements distinguishing haze, mist and fog, per Goh Cheng Leong:\n1. Haze occurs in regions of lower humidity (below 75%) and is caused by smoke, dust, or unequal light refraction, reducing visibility to below about 2 km.\n2. Mist occurs in wetter air (relative humidity over 75%) and reduces visibility to about 1,000 metres.\n3. Fog occurs when water condenses on dust and smoke particles in the lower atmosphere, reducing visibility to even less than 1,000 metres.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's specific humidity thresholds and visibility ranges distinguishing haze, mist and fog."})

upsc.append({"q":"Which one of the following statements about fog formation is NOT correct?","o":["Radiation fog (land fog) forms mainly over deserts during the hottest part of the afternoon, when solar heating is most intense","Sea fog can form when a warm ocean current meets a cold current, as off Newfoundland","Fogs also form when cold ocean currents meet hot desert air, as off the Atacama Desert of Peru and Chile","Radiation fog forms when clear, still nights allow the land surface to cool by radiation, chilling the lower air layers until water vapour condenses"],"a":0,"e":"This statement is incorrect — radiation (land) fog forms on clear, still nights through radiative COOLING of the land surface, not during the hottest, sunniest part of the afternoon, which is the opposite condition. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the general global distribution of fog, per Goh Cheng Leong:\n1. Fogs are generally more common over seas than over land, and most prevalent over coastal areas.\n2. Dry continental interiors typically experience haze or mist rather than dense fog.\n3. Dense fogs are more likely in the tropics than in the high and middle latitudes.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states dense fogs are 'more likely to occur in the high and middle latitudes rather than in the tropics', the reverse of this claim. Statements 1 and 2 are correct."})

# ==================================================================
# SECTION 9: FORMS OF CONDENSATION — DEW AND FROST (NCERT XI PART 1, CH.11)
# ==================================================================

upsc.append({"q":"Consider the following statements about dew and frost, according to NCERT:\n1. Dew forms when moisture is deposited as water droplets on cooler surfaces of solid objects, requiring the dew point to be above freezing point.\n2. Frost forms through the same general conditions as dew, except that air temperature must be at or below freezing point, depositing moisture as ice crystals instead of water droplets.\n3. Both dew and frost favour clear skies, calm air, high relative humidity, and long, cold nights.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, precisely matching NCERT's account of the shared ideal conditions for dew and frost, differing only in whether the dew point falls above or at/below freezing point."})

upsc.append({"q":"According to NCERT's account of fog and mist, which one of the following is NOT correct?","o":["Fog contains a thicker layer of moisture around each condensation nucleus than mist does","Smog is described as fog mixed with smoke, common in urban and industrial centres","Mists are frequent over mountains, where rising warm air up the slopes meets a cold surface","Fogs are typically drier than mist and prevail where warm and cold air currents meet"],"a":0,"e":"This statement is incorrect and reverses NCERT's own explicit claim — NCERT states MIST (not fog) contains more moisture, with each nucleus in mist carrying a 'thicker layer of moisture' than in fog. The other three statements correctly reflect NCERT's account."})

upsc.append({"q":"Consider the following statements about NCERT's four basic cloud types:\n1. NCERT groups clouds into four basic types: cirrus, cumulus, stratus and nimbus, based on height, expanse, density and transparency.\n2. Cumulus clouds are described as looking like cotton wool with a flat base, generally forming at lower heights than cirrus clouds.\n3. A combination of these four basic types, according to NCERT, gives rise to further sub-types such as cirrostratus, altostratus, stratocumulus and cumulonimbus.\nHow many of the above statements are correct?","o":["All three","Only one","Only two","None"],"a":0,"e":"All three statements are correct, matching NCERT's four-basic-type cloud framework, the relative height and appearance of cumulus versus cirrus, and the derivation of further named sub-types by combining these basic categories — broadly consistent with the ten specific cloud types described directly by Goh Cheng Leong."})

upsc.append({"q":"Assertion (A): Nimbus clouds, as described by NCERT, are associated with dull, overcast conditions rather than fair weather.\nReason (R): NCERT describes nimbus clouds as black or dark grey, extremely dense and opaque to sunlight, sometimes low enough to seem to touch the ground.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — a cloud type that is dense, dark and opaque to sunlight, sometimes touching the ground, is inherently associated with dull, overcast weather rather than the bright appearance of fair-weather clouds like cirrus or cumulus."})

# ==================================================================
# SECTION 10: ADDITIONAL GROUNDED QUESTIONS (ENRICHMENT)
# ==================================================================

upsc.append({"q":"Consider the following statements explaining why 'Britain has no climate, only weather':\n1. This reflects the high day-to-day variability of atmospheric conditions in temperate latitudes compared to the tropics.\n2. It implies that average conditions in Britain are so erratic that meaningful long-term climatic generalisation is difficult, unlike in a country like Egypt.\n3. It means Britain literally experiences no seasonal temperature change throughout the year.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the phrase is about day-to-day weather VARIABILITY, not an absence of seasons; it does not imply zero seasonal temperature change. Statements 1 and 2 correctly capture the intended meaning of the phrase."})

upsc.append({"q":"Which one of the following statements about wind speed with altitude is correct, as implied by the text's discussion questions?","o":["Wind speed at higher altitudes above the surface is generally greater than at ground level, due to reduced surface friction","Wind speed is always identical at all altitudes, since friction plays no role in wind movement","Wind speed decreases steadily with altitude up to the stratosphere","Wind speed depends solely on temperature and has no relationship with altitude or friction"],"a":0,"e":"Wind speed increases with altitude near the surface mainly because frictional drag from the ground, vegetation and buildings slows near-surface winds; higher up, this frictional retardation is reduced, allowing greater wind speeds — consistent with the text's own discussion prompt about wind speed at height versus at the surface."})

upsc.append({"q":"Consider the following statements about evaporation as a meteorological process:\n1. Evaporation is the process by which a substance changes from liquid to vapour.\n2. Evaporation is essentially the same process as condensation, simply operating in reverse under identical conditions.\n3. Evaporation contributes water vapour to the air, which can later condense to form clouds once the dew point is reached.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — evaporation (liquid to vapour) and condensation (vapour to liquid) are opposite processes with different physical requirements (evaporation typically requires heat input, condensation requires cooling to dew point), not simply the same process happening in reverse under identical conditions. Statements 1 and 3 are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "weather",
    "title": "Weather",
    "desc": "Weather elements and instruments (from Goh Cheng Leong's Physical Geography and NCERT XI Fundamentals of Physical Geography, Ch.11 'Water in the Atmosphere'): the difference between weather and climate; measuring rainfall, pressure, temperature, humidity and wind; the Beaufort Wind Scale; cloud classification (cirrus, cirrocumulus, cirrostratus, altocumulus, altostratus, stratocumulus, stratus, nimbostratus, cumulus, cumulonimbus, and NCERT's four basic parent types); and visibility phenomena (haze, mist, fog, smog) including forms of condensation (dew, frost)",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch13_weather_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
