import json

upsc = []

# ==================================================================
# EXTRA UPSC BATCH (no dedup check): eco_agriculture (Ramesh Singh Ch.8, Food Management continued)
# Market Intervention Scheme, Procurement vs Issue Price, Buffer Stock norms, DCP scheme,
# storage capacity, economic cost of foodgrains, Shanta Kumar Committee, OMSS, Price
# Stabilisation Fund, farm subsidies (direct vs indirect), Bolsa Familia
# ==================================================================

upsc.append({"q":"The Market Intervention Scheme (MIS) is triggered on the request of state governments under which one of the following conditions?","o":["At least a 10 per cent increase in production or a 10 per cent decrease in ruling market rates over the previous normal year, for perishable/horticultural commodities","Any decline in production of foodgrains by more than 5 per cent","An increase in the Consumer Price Index beyond 6 per cent","A request from the Reserve Bank of India citing inflationary pressure"],"a":0,"e":"MIS is implemented, on state/UT request, for perishable and horticultural commodities when there is at least a 10% increase in production or a 10% fall in ruling market rates versus the previous normal year, with the state bearing 50% of the loss (25% for North-Eastern states)."})

upsc.append({"q":"Assertion (A): Since fiscal 1968-69, the Government of India stopped announcing a separate 'procurement price' distinct from the Minimum Support Price (MSP).\nReason (R): The procurement price, announced before harvesting rather than before sowing, failed to serve as a suitable production incentive to farmers.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A: because the procurement price (introduced 1966-67) was announced only before harvesting — too late to influence sowing decisions — it failed as an incentive, leading the government to rely solely on the pre-sowing MSP (also treated as the effective procurement price) from 1968-69 onward."})

upsc.append({"q":"Which one of the following correctly distinguishes the 'Issue Price' from the 'economic cost of foodgrains'?","o":["The Issue Price (at which FCI sells foodgrains) is deliberately kept lower than the economic cost (MSP plus procurement incidentals and distribution costs), with the gap constituting the food subsidy","The Issue Price always equals the economic cost of foodgrains, leaving no subsidy component","The economic cost of foodgrains excludes the MSP paid to farmers","The Issue Price is set by the CACP while the economic cost is set by the RBI"],"a":0,"e":"The Issue Price is intentionally kept below the economic cost (MSP + procurement incidentals + distribution cost) to keep foodgrains affordable for consumers; the resulting gap between the two is what constitutes the food subsidy borne by the government."})

upsc.append({"q":"Consider the following statements about India's Buffer Stock policy for foodgrains:\n1. Buffer stocking norms apply only to wheat and rice.\n2. The Buffer Stocking norms of 2005 were revised by mid-2014, partly due to the coming into force of the National Food Security Act.\n3. As BPL segment incomes rise over time, buffer stock norms are expected to be revised upward to maintain higher reserves.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — the text explicitly states that as BPL incomes grow, buffer norms are expected to be revised DOWNWARD, not upward, though the rationale for maintaining some stock for market intervention will remain."})

upsc.append({"q":"The Decentralised Procurement (DCP) Scheme, operationalised in 1997, involves which one of the following arrangements?","o":["Designated states procure, store and issue foodgrains under the TPDS themselves, with the Centre reimbursing the gap between the states' economic cost and the Central Issue Price as subsidy","The complete replacement of the Food Corporation of India by state government agencies nationwide","A scheme exclusively for procurement of pulses and oilseeds, excluding wheat and rice","Direct procurement by the RBI on behalf of the states"],"a":0,"e":"Under DCP, designated states themselves procure, store, and issue foodgrains under the TPDS, with the Centre compensating the gap between their economic cost and the Central Issue Price (CIP) — improving local-taste variety availability and reducing FCI transportation costs, without eliminating the FCI's role elsewhere."})

upsc.append({"q":"Which committee, set up by the government in August 2014, was tasked with suggesting the restructuring or 'unbundling' of the Food Corporation of India (FCI) to improve its operational efficiency and financial management?","o":["The Shanta Kumar Committee (High Level Committee)","The Ashok Dalwai Committee","The M.S. Swaminathan Committee","The Radhakrishna Committee"],"a":0,"e":"The Shanta Kumar-chaired High Level Committee (HLC), constituted in August 2014, was specifically tasked with reviewing the high economic cost of foodgrain procurement and recommending FCI restructuring/unbundling for better efficiency."})

upsc.append({"q":"Consider the following statements about the Open Market Sale Scheme (OMSS):\n1. Under it, the FCI sells wheat in the open market at pre-determined reserve prices.\n2. The reserve price is deliberately kept above the MSP but reasonably below the economic/acquisition cost of wheat.\n3. Its objectives include enhancing market supply, moderating open market prices, and offloading surplus stocks.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct: OMSS sells FCI wheat at pre-set reserve prices (above MSP, below economic cost, to keep buyers attracted while limiting profiteering), aiming to boost supply, moderate prices, and offload surplus stock, following a differential-price policy that encourages sale of older stock first."})

upsc.append({"q":"The Price Stabilisation Fund (PSF), launched in late March 2015 as a Central Sector Scheme, initially targeted market interventions for which two commodities?","o":["Onion and potato","Wheat and rice","Pulses and edible oils","Sugar and cotton"],"a":0,"e":"The PSF was launched to support price control interventions for perishable agri-horticultural commodities, initially commencing with only onion and potato, with costs shared equally between Centre and states (75:25 for North-Eastern states)."})

upsc.append({"q":"Which one of the following statements about India's foodgrain storage capacity, as highlighted by the Economic Survey 2014-15, is correct?","o":["Cold storage facility was available for only about 10 per cent of India's fruit and vegetable production, despite potato production alone being roughly comparable to the total available cold storage capacity","India's cold storage capacity fully matches the storage needs of all perishable commodities","Public procurement agencies have adequate scientific warehousing for all the wheat and rice they procure","Cover and Plinth (CAP) storage facilities are considered fully scientific and equivalent to covered godowns"],"a":0,"e":"The Survey highlighted that cold storage covered only ~10% of fruit/vegetable production, with total cold storage capacity (29 MT) roughly matching just potato production alone (~35 MT) — a stark shortfall; CAP storage was explicitly NOT considered scientific, and public agencies lacked adequate warehousing even for half their procured wheat/rice."})

upsc.append({"q":"With reference to farm subsidies in India, consider the following statements:\n1. India's farm subsidies as a share of GDP are higher than the corresponding share in developed countries' budgets.\n2. The bulk of indirect fertilizer subsidy has been observed to benefit large farmers disproportionately, since small and marginal farmers hold a minority share of farmland.\n3. A panel headed by Montek Singh Ahluwalia recommended direct-to-farmer electricity subsidy transfers via smart cards linked to a unique identity number.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1, 2 and 3","1 and 2 only","1 only"],"a":0,"e":"Statements 2 and 3 are correct. Statement 1 is false — India's farm subsidies are actually much LOWER as a share relevant metric compared to developed countries (which spend around 40% of their total budgetary outlay on agriculture subsidies, versus India's much smaller share)."})

upsc.append({"q":"Brazil's 'Bolsa Familia' programme, cited as the most prominent global example of direct cash transfer subsidies to the poor, is best described as:","o":["A conditional cash transfer programme, started in 2001 focusing on education and later expanded (2003) to cover food and fuel needs, now covering millions of families","An unconditional universal basic income scheme with no eligibility conditions","A scheme exclusively for agricultural input subsidies to Brazilian farmers","A World Bank-administered global food security fund"],"a":0,"e":"Bolsa Familia began in 2001 focused on education, expanding in 2003 to cover food and fuel, and operates as a CONDITIONAL cash transfer (subject to conditions like school attendance) reaching millions of families — not an unconditional UBI, farm-input subsidy, or World Bank fund."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only — no dedup check per updated instructions)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_agriculture_upsc2.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
