import json

upsc = []

# ==================================================================
# NEW UPSC TIER: BASIC CONCEPTS OF ECONOMICS (Ramesh Singh Ch.1: Introduction)
# Avoiding overlap with existing basic/intermediate/advanced (Smith/Keynes basics,
# opportunity cost, capitalism/socialism definitions, factors of production)
# ==================================================================

upsc.append({"q":"The term 'Washington Consensus' was coined in 1989 by which economist to describe a set of policy reforms recommended for crisis-driven Latin American economies?","o":["John Williamson","Joseph Stiglitz","Paul Krugman","George Soros"],"a":0,"e":"John Williamson coined 'Washington Consensus' in 1989, describing ten policy propositions (fiscal discipline, tax reform, trade/FDI liberalisation, privatisation, deregulation, etc.) recommended by Washington-based institutions (IMF, World Bank, US Treasury) for Latin America."})

upsc.append({"q":"Consider the following statements about the 'Washington Consensus':\n1. It originally comprised ten specific policy propositions aimed at Latin American economies.\n2. Its creator, John Williamson, later expressed discomfort with the term becoming synonymous with 'neo-liberalism' and 'market fundamentalism'.\n3. India's 1991 reforms, undertaken under IMF conditions during a Balance of Payments crisis, are viewed by some scholars as influenced by this policy framework.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — the Consensus did comprise ten specific propositions, Williamson explicitly distanced himself from its later 'neo-liberal'/'market fundamentalism' connotations, and India's 1991 IMF-conditioned reforms are widely linked to this broader policy framework."})

upsc.append({"q":"Which Polish economist suggested in the 1950s that state (socialist) economies should adopt 'market socialism', incorporating some features of capitalist economies — advice that was initially rejected but later validated by China's 1985 'open door policy'?","o":["Oscar Lange","Karl Marx","Vladimir Lenin","Mikhail Gorbachev"],"a":0,"e":"Oscar Lange (1904-65), a Polish economist, coined the term 'market socialism' in the 1950s, suggesting state economies incorporate capitalist elements — an idea rejected at the time but effectively validated when China adopted its 'open door policy' in 1985."})

upsc.append({"q":"Which one of the following statements about the transition of state (command) economies toward market-based systems is NOT correct?","o":["The Soviet Union's transition to market socialism, driven by 'glasnost' and 'perestroika', proceeded smoothly and strengthened the unified Soviet state","China's transition to a limited market economy under continued political dictatorship began with its 1985 'open door policy'","Experts describe the Soviet Union's economic mismanagement during its transition as having a significant 'political fallout', linked to the state's disintegration","China's smoother transition is attributed to preparatory groundwork done since Mao's era, particularly from 1975 onward"],"a":0,"e":"This statement is incorrect and reverses reality — the USSR's transition under glasnost/perestroika was NOT smooth; it culminated in the actual disintegration of the Soviet Union, described by experts as 'a political fallout of economic mismanagement', unlike China's comparatively smoother, better-prepared transition."})

upsc.append({"q":"The World Bank's World Development Report 1999, titled 'Entering the 21st Century', is significant in economic thought because it:","o":["Concluded that governments play a vital role in development but rejected any 'simple set of rules' prescribing state intervention, effectively endorsing a judicious mixed-economy approach over pure market or pure state models","Concluded that the free market model advocated by Adam Smith should be adopted universally with no role for the state","Rejected any possibility of state intervention in developing economies","Was the first World Bank document to advocate for a return to centrally planned economies"],"a":0,"e":"The WDR 1999 marked a turning point where the World Bank (traditionally a free-market advocate) explicitly endorsed a mixed, context-dependent state-market balance, rejecting both pure market fundamentalism and pure state control as universal prescriptions."})

upsc.append({"q":"Which World Bank study (1993) recognised the shift of certain East Asian economies (Malaysia, Thailand, South Korea) from one form of mixed economy to another since the mid-1960s, contrasting this with India's later and more obligatory transition?","o":["The East Asian Miracle","Entering the 21st Century","The World Economy: A Millennial Perspective","Growth and Interaction in the World Economy"],"a":0,"e":"The World Bank's 'The East Asian Miracle' (1993) study documented this shift among East Asian economies occurring by choice from the mid-1960s, contrasting with India's shift (1991-92), which came later and was described as 'obligatory' rather than voluntary."})

upsc.append({"q":"Consider the following statements about the three possible roles of the state in an economy:\n1. Regulating the economic system.\n2. Producing/supplying 'private goods and services' distributed via market mechanisms.\n3. Producing/supplying 'public' or 'social goods' viewed as essential for social justice and well-being.\n4. There has historically been no debate among economic systems regarding the state's regulatory role, unlike the other two roles.\nHow many of the statements given above are correct?","o":["All four","Only three","Only two","None"],"a":0,"e":"All four statements are correct. The text identifies exactly these three possible state roles, and separately notes that the regulatory role has faced no historical debate (all economic systems accept state regulation), unlike the more contested private-goods and public-goods production roles."})

upsc.append({"q":"Which one of the following statements about 'capitalistic', 'state', and 'mixed' economies' respective roles for the state is correct?","o":["Capitalistic economies restrict the state to a passive regulatory role only, state economies assign the state both private-goods and public-goods production roles under monopoly, while mixed economies retain at least the public-goods supply role for the state","Capitalistic economies assign the state a monopoly over public goods production, while state economies leave production entirely to private enterprise","Mixed economies assign the state no economic role whatsoever, identical to capitalistic economies","State economies and capitalistic economies are identical in their treatment of the state's economic role"],"a":0,"e":"The text precisely draws this three-way distinction: capitalism keeps the state to a passive regulatory role; state economies give the state monopoly control over both private- and public-goods production; mixed economies retain at least the public-goods supply function for the state while allowing market forces elsewhere."})

upsc.append({"q":"According to the classification of economies by sectoral share of output, an economy is termed 'agrarian' if its primary sector contributes what share (or more) of total GDP?","o":["50 per cent or more","25 per cent or more","75 per cent or more","10 per cent or more"],"a":0,"e":"An economy is classified as agrarian if the primary sector contributes 50 per cent or more of total GDP — a threshold India crossed below decades ago, even though a large share of its population still depends on agriculture for livelihood."})

upsc.append({"q":"Which one of the following statements about India's classification as an 'agrarian economy' is correct?","o":["In monetary/output terms India is no longer an agrarian economy (primary sector contributing around 18 per cent of GDP), yet its high dependency ratio (nearly half the population relying on agriculture for livelihood) makes it an unusual case in world economic history","India remains an agrarian economy by both output share and dependency ratio criteria, with primary sector output exceeding 50 per cent of GDP","India's primary sector's GDP contribution and population dependency ratio are both below 20 per cent, making it a clear service economy by all criteria","The dependency ratio on India's primary sector has fallen below the output-share percentage, aligning India with typical developed-economy patterns"],"a":0,"e":"India presents an unusual case: its primary sector's GDP SHARE has fallen well below the 50% agrarian threshold (around 18%), yet the DEPENDENCY RATIO remains high (around 49% of the population), a combination the text calls the first such example in world economic history."})

upsc.append({"q":"Which economist's 'Stages of Economic Growth: A Non-Communist Manifesto' (1960) is associated with describing the pattern of population/income shift from primary to secondary to tertiary sectors as an economy industrialises?","o":["Walt W. Rostow","John Maynard Keynes","Adam Smith","Joseph Stiglitz"],"a":0,"e":"Walt W. Rostow's 1960 work described the 'stages of growth' pattern, wherein economies see population dependency shift progressively from the primary sector to the secondary (industrial) sector, and eventually to the tertiary (services) 'post-industrial' sector."})

upsc.append({"q":"Which of the following economists identified the fundamental political-economic challenge as combining economic efficiency, social justice, and individual liberty?","o":["John Maynard Keynes","Adam Smith","Karl Marx","Milton Friedman"],"a":0,"e":"Keynes articulated that the political problem of mankind is to combine three things: economic efficiency, social justice, and individual liberty — a framing used to argue for a balanced state-market role rather than reliance on either alone."})

upsc.append({"q":"Which one of the following correctly distinguishes the three historically evolved 'distribution network models' for goods and services in an economy?","o":["State-led distribution (e.g., former USSR/Communist China), market-led distribution via price mechanism (Euro-American capitalist economies), and a state-market mix combining subsidised/free state supply with market-priced goods","Only two distribution models have historically existed: state-led and market-led, with no mixed variant ever developing","The state-market mix model developed before either the pure state or pure market models historically","All economies of the world today follow a purely state-led distribution model exclusively"],"a":0,"e":"The text identifies exactly three historical distribution network models — state, market, and state-market mix — with the mixed model emerging out of the experiences of the first two (not preceding them), and notes that almost all economies today follow one variant or another of these models, not a purely state-led model."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_basic_concepts_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
