import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_trade_fdi (Ramesh Singh Ch.15, External Sector in India —
# SEZ, GAAR, Foreign Trade Policy 2015-20, RTAs/FTAs/RCEP)
# ==================================================================

upsc.append({"q":"Consider the following statements about India's Special Economic Zone (SEZ) policy:\n1. The SEZ policy was first announced by the government in 2000 and was later given a statutory basis through the SEZ Act, 2005.\n2. India had already set up Asia's first export processing zone (EPZ) at Kandla as far back as 1965.\n3. SEZs in India can be set up only by the Central Government, with no role for state governments or the private sector.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct — the 2000 policy announcement, the 2005 Act, and Kandla's status as Asia's first EPZ (1965) are all accurate. Statement 3 is incorrect: SEZs can be set up by the Government of India, State Governments, OR the private sector, across the agriculture, industry, and services sectors."})

upsc.append({"q":"As per data cited up to March 2017, which one of the following correctly describes the scale and impact of India's SEZs?","o":["405 SEZ proposals had been approved (206 operational), with cumulative investment of about Rs. 4.06 lakh crore, employment generation of 16.88 lakh, and a 23 per cent share in India's total exports","Only 50 SEZ proposals had been approved with negligible impact on India's export performance","SEZs accounted for less than 1 per cent of India's total exports as of March 2017","All SEZs set up after the 2005 Act were mandatorily converted from existing Export Oriented Units (EOUs)"],"a":0,"e":"By March 2017, 405 SEZ proposals stood approved (206 operational, in addition to SEZs pre-dating the 2005 Act), with roughly Rs. 4.06 lakh crore invested, 16.88 lakh jobs created, and a 23% share in India's total exports — a substantial, not negligible, contribution."})

upsc.append({"q":"The General Anti-Avoidance Rules (GAAR), aimed at arrangements or transactions specifically designed to avoid taxes, were originally proposed in which one of the following, and from which financial year were they eventually implemented in India?","o":["Originally proposed in the Direct Taxes Code (DTC) 2010; implemented from financial year 2013-14","Originally proposed in the Insurance Laws (Amendment) Act, 2015; implemented from financial year 2015-16","Originally proposed in the SEZ Act, 2005; implemented from financial year 2005-06","Originally proposed in the FRBM Act, 2003; implemented from financial year 2003-04"],"a":0,"e":"GAAR was originally proposed in the Direct Taxes Code (DTC) 2010, with the government subsequently advancing and implementing it from financial year 2013-14 — unrelated to the SEZ Act, Insurance Laws Amendment Act, or FRBM Act."})

upsc.append({"q":"Which one of the following best describes the core doctrine underlying India's General Anti-Avoidance Rules (GAAR)?","o":["'Substance over form' — the real intention and purpose of an arrangement is examined for tax purposes, irrespective of its legal structure","'Form over substance' — the legal structure of a transaction is treated as conclusive, regardless of underlying intent","'First in, first out' — an accounting principle unrelated to tax avoidance","'Caveat emptor' — a consumer protection principle applied to cross-border trade disputes"],"a":0,"e":"GAAR codifies the 'substance over form' doctrine — tax authorities examine the real intent and purpose behind an arrangement rather than being bound by its formal legal structure, in order to counter arrangements designed mainly to secure a tax benefit."})

upsc.append({"q":"Under India's General Anti-Avoidance Rules (GAAR), an arrangement can be declared an 'impermissible avoidance arrangement' if it is entered into mainly to obtain a tax benefit AND satisfies at least one of four specified tests. Which one of the following is NOT among these four tests?","o":["The arrangement has received prior clearance from the jurisdictional High Court","It creates rights and obligations not at arm's length","It results in misuse or abuse of tax law provisions","It lacks commercial substance or is deemed to lack commercial substance"],"a":0,"e":"The four genuine GAAR tests are: rights/obligations not at arm's length, misuse/abuse of tax law provisions, lack of (or deemed lack of) commercial substance, and the arrangement not being carried out in a bona fide manner. 'Prior High Court clearance' is fabricated and not one of the actual criteria — GAAR determinations are made by tax officers, not pre-cleared by courts."})

upsc.append({"q":"Which one of the following statements about India's Foreign Trade Policy (FTP) 2015-20, announced on 1 April 2015, is correct?","o":["It introduced two new schemes — the Merchandise Exports from India Scheme (MEIS) and Services Exports from India Scheme (SEIS) — replacing multiple older schemes with varying eligibility conditions","It abolished all export incentive schemes in favour of a single unified GST-linked rebate mechanism","It was a ten-year policy framework running from 2015 to 2025","It applied exclusively to the manufacturing sector, excluding services exports entirely"],"a":0,"e":"FTP 2015-20 (a FIVE-year framework, not ten) introduced MEIS (for specified goods to specified markets) and SEIS (for notified services), replacing a plethora of earlier schemes with differing eligibility norms, and covered BOTH manufacturing and services sectors, in line with the 'Make in India' initiative."})

upsc.append({"q":"With reference to the duty credit scrips issued under India's MEIS and SEIS schemes (Foreign Trade Policy 2015-20), which one of the following is correct?","o":["The scrips, and goods imported against them, are fully transferable and carry no conditionality","The scrips are strictly non-transferable and can only be used by the original exporter","MEIS rewards range from 10 per cent to 20 per cent, far higher than SEIS rewards","SEIS rewards are given only in the form of direct cash subsidies, not duty credit scrips"],"a":0,"e":"Under FTP 2015-20, MEIS/SEIS duty credit scrips (and goods imported against them) are fully transferable with no conditionality attached — MEIS rewards actually range from 2% to 5% (based on a 3-group country categorisation) and SEIS rewards are 3% or 5%, both far lower than the fabricated 10-20% range."})

upsc.append({"q":"Regarding India's Regional Trade Agreements (RTAs) as of March 2017, which one of the following is correct?","o":["India had 12 Free Trade Agreements (FTAs) and 6 Preferential Trade Agreements (PTAs) in force, with 24 more FTAs (including reviews) under negotiation","India had no FTAs in force and relied solely on multilateral WTO commitments","India had signed FTAs only with WTO founding member countries","All of India's RTAs are legally required to be ratified by the WTO General Council before taking effect"],"a":0,"e":"As of March 2017, India had 12 FTAs and 6 PTAs already in force, alongside 24 FTAs (including reviews) under active negotiation — India follows a gradual, incremental approach to widening its FTA network, and RTAs, while broadly WTO-compliant, do not require WTO General Council ratification."})

upsc.append({"q":"The Regional Comprehensive Economic Partnership (RCEP), under negotiation since May 2013, is a proposed trade agreement among which one of the following groupings?","o":["The 10 ASEAN member states and their six FTA partners — Australia, China, India, Japan, South Korea, and New Zealand","Only the BRICS nations plus ASEAN","The G7 economies and India","The SAARC nations exclusively"],"a":0,"e":"RCEP brings together the 10 ASEAN members and their six FTA partner countries (Australia, China, India, Japan, South Korea, New Zealand) — negotiations commenced in May 2013 following the November 2012 ASEAN Summit Leaders' Declaration, unrelated to BRICS, the G7, or SAARC groupings."})

upsc.append({"q":"Assertion (A): India has generally supported Regional Trade Agreements (RTAs) as complementary to, rather than a substitute for, the multilateral trading system under the WTO.\nReason (R): While RTAs are broadly WTO-compliant, they are considered 'second-best' solutions because they are inherently discriminatory against non-member countries.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — India views RTAs as 'building blocks' supporting the multilateral WTO framework precisely because, while WTO-compliant, RTAs remain second-best (discriminatory against non-members, inefficient relative to true multilateralism), which is why India frames its RTA engagement as complementary rather than a replacement for WTO-based multilateralism."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_trade_fdi_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
