import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_money_monetary_policy (Ramesh Singh Ch.12, monetary
# policy tools section) - RBI functions, CRR/SLR history, Bank Rate, Repo/
# Reverse Repo, MSF, term repo, call money market
# ==================================================================

upsc.append({"q":"Consider the following statements about the Reserve Bank of India (RBI):\n1. It was originally set up in 1935 as a private bank under the RBI Act, 1934.\n2. It was nationalised in 1949, after which it ceased to remain a 'bank' in the technical sense and became India's central banking body.\n3. Coins and currency notes of all denominations, including the one-rupee note, are issued by the RBI.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — the one-rupee note and coin are issued by the Ministry of Finance (bearing the Finance Secretary's signature), not the RBI, which issues all other denominations."})

upsc.append({"q":"Which committee's recommendation is credited with sparking the debate on RBI autonomy regarding the announcement of credit and monetary policy, with then-Governor Bimal Jalan vocally supporting the idea?","o":["The Narasimham Committee-I","The Vaghul Committee","The Chore Committee","The S.H. Khan Committee"],"a":0,"e":"The Narasimham Committee-I (Committee on the Financial System, 1991) recommended greater RBI autonomy in monetary policy announcements, an idea Governor Bimal Jalan later championed — though no formal, officially open autonomy was ever legislated, unlike in many developed economies with clearer central bank independence."})

upsc.append({"q":"Consider the following statements about the Cash Reserve Ratio (CRR) in India:\n1. Prior to a 2007 amendment, the CRR was statutorily required to be maintained between 3 and 15 per cent.\n2. Following the Narasimham Committee-I's recommendations, CRR was reduced from a peak of 15 per cent in 1992 to 4.5 per cent by June 2003.\n3. The RBI has continuously paid interest on CRR balances to scheduled banks since 1999-2000 without any interruption.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — while the RBI began paying interest on CRR balances in FY 1999-2000, it DISCONTINUED this practice from mid-2007, meaning the interest payment was not maintained continuously."})

upsc.append({"q":"Which one of the following amendments removed the statutory floor for CRR (previously 3 per cent) and gave the RBI a free hand in fixing it without any floor or ceiling?","o":["The RBI (Amendment) Act, 2006","The Narasimham Committee-I recommendations, 1991","The Banking Regulation Act, 1949","The FRBM Act, 2003"],"a":0,"e":"The RBI (Amendment) Act, enacted in June 2006, removed the statutory minimum CRR floor of 3%, empowering the RBI to prescribe CRR for scheduled banks without any floor or ceiling constraint."})

upsc.append({"q":"With reference to the Statutory Liquidity Ratio (SLR), consider the following statements:\n1. SLR was cut to 25 per cent in October 1997 following recommendations of the Committee on Financial System (CFS), down from a peak as high as 38.5 per cent.\n2. The 2007 amendment removed the 25 per cent floor for SLR, giving the RBI freedom to fix it, with the ratio at 19.5 per cent by March 2018.\n3. The CFS recommended that instead of mandating banks to hold SLR-eligible G-Secs, the government should pay a market-based interest on such holdings — a recommendation that has been fully implemented.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — the CFS's recommendation for market-based interest on SLR-mandated G-Sec holdings was explicitly noted as having 'no follow up' by the governments, meaning it was never implemented."})

upsc.append({"q":"Which one of the following statements correctly describes the 'Bank Rate' as a monetary policy tool in India?","o":["It is the interest rate the RBI charges on its long-term lendings to the Government of India, state governments, banks, financial institutions, co-operative banks and NBFCs, and was realigned with the MSF rate in February 2012","It is the interest rate the RBI charges only on overnight interbank lending in the call money market","It is a rate paid by the RBI to banks that park surplus funds with it","It refers exclusively to the rate charged on housing loans by scheduled commercial banks"],"a":0,"e":"The Bank Rate is RBI's long-term lending rate to a range of institutional borrowers, realigned with the Marginal Standing Facility (MSF) rate from February 2012 onward, making the two rates move together — distinct from the overnight call money rate or a housing-loan-specific rate."})

upsc.append({"q":"Consider the following statements about the 'Repo Rate' in India:\n1. It is technically treated not as a conventional interest rate but as a discount on dated government securities deposited to borrow short-term funds from the RBI.\n2. The Call Money Market operates at the repo rate for interbank overnight borrowings.\n3. Since October 2013, the RBI has introduced 'term repos' of varying tenors (such as 7, 14, and 28 days) to inject liquidity over periods longer than overnight.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct. The repo rate operates as an effective 'discount' mechanism on government securities, underpins Call Money Market operations, and was supplemented since October 2013 by term repos of various tenors to serve money-market stability, better costing, and interest-rate signalling."})

upsc.append({"q":"Assertion (A): Since late 2013, the RBI has been actively discouraging banks from relying solely on the standard overnight repo route for short-term funds.\nReason (R): Banks are now permitted to borrow only 1 per cent of their Net Demand and Time Liabilities (NDTL) under the overnight repo facility, with the remaining 0.75 per cent of NDTL available only through term repos of varying tenors.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — by capping overnight repo borrowing at 1% of NDTL and channelling the remaining 0.75% through term repos (of different tenors), the RBI has structurally pushed banks toward term repos since late 2013, promoting stability and better interest-rate signalling."})

upsc.append({"q":"The Marginal Standing Facility (MSF), introduced in the RBI's 2011-12 Monetary Policy and effective from May 2011, allows banks to do which one of the following?","o":["Borrow overnight, up to 1 per cent of their Net Demand and Time Liabilities (NDTL), at a rate 1 percentage point higher than the prevailing repo rate","Borrow unlimited amounts overnight at a rate below the repo rate","Deposit surplus funds with the RBI at a rate higher than the repo rate","Access long-term credit at the Bank Rate without any NDTL-based ceiling"],"a":0,"e":"MSF permits banks to borrow overnight up to 1% of their NDTL at a penal rate 1 percentage point (100 basis points) above the repo rate — a facility later widened to a 3% gap in July 2013 (to defend a falling rupee) before being aligned back to a 1% gap and equalised with the Bank Rate by March 2018."})

upsc.append({"q":"Consider the following statements about India's Call Money Market:\n1. Current participants include scheduled commercial banks (excluding regional rural banks) and co-operative banks (other than land development banks), among others.\n2. The RBI specifies prudential limits on both outstanding borrowing and lending transactions for each participating entity type.\n3. By April 2016, banks were permitted to borrow only 1 per cent of their NDTL under the overnight facility at the repo rate, using term repos for the remaining permissible short-term requirement.\nWhich of the statements given above is/are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct, reflecting the Call Money Market's structured participant base, RBI-imposed prudential borrowing/lending limits, and the post-2016 shift steering banks toward term repos for the bulk of their short-term liquidity needs beyond the capped overnight repo facility."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_money_monetary_policy_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
