import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_taxation (Ramesh Singh Ch.17, Tax Structure in India)
# Incidence/impact, Progressive/Regressive/Proportional taxation, good tax
# system principles, VAT/GST history (Kelkar Task Force, 101st Amendment,
# GST Council, rate bands), MAT, corporate tax rationalisation, tax expenditure
# ==================================================================

upsc.append({"q":"With reference to the concepts of 'incidence' and 'impact' of a tax, consider the following statements:\n1. The 'incidence' of a tax refers to the point where the tax is initially imposed.\n2. The 'impact' of a tax refers to the point where its effect is ultimately felt.\n3. In a direct tax, incidence and impact fall on different persons, whereas in an indirect tax they fall on the same person.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 2 correctly define incidence (point of imposition) and impact (point where effect is felt). Statement 3 REVERSES the correct relationship: in a DIRECT tax (e.g., income tax), incidence and impact fall on the SAME person ('the person who is hit, the same person bleeds'), while in an INDIRECT tax (e.g., excise, sales tax), they fall on DIFFERENT persons — the producer/trader is hit but the consumer ultimately bears the burden."})

upsc.append({"q":"Which one of the following correctly distinguishes 'progressive', 'regressive', and 'proportional' methods of taxation?","o":["Progressive taxation has increasing tax rates with increasing value/volume; regressive has decreasing rates with increasing value/volume; proportional has a fixed rate regardless of value/volume","Progressive taxation has a fixed rate for all income levels; regressive taxation increases with income; proportional taxation decreases with income","Regressive taxation is the most popular and widely used method globally, being the base of India's income tax","Proportional taxation is typically used as an independent, standalone taxation method by most economies rather than as a complement to other methods"],"a":0,"e":"Progressive taxation (India's income tax being a typical example) has rising rates for rising income/value; regressive taxation has falling rates for rising value (India once used it on small-scale industry excise duties to promote them); proportional taxation applies a flat, fixed rate — usually used as a complementary check to prevent progressive/regressive rates from becoming extreme, rather than as a standalone method."})

upsc.append({"q":"India's income tax system, which taxes different income slabs at increasing rates, is an example of which method of taxation, and what is one commonly cited criticism of this method?","o":["Progressive taxation; it may unintentionally discourage higher earnings and encourage tax evasion through underreporting of income","Regressive taxation; it disproportionately burdens the poor","Proportional taxation; it fails to differentiate between rich and poor taxpayers","Progressive taxation; it was specifically designed to promote small-scale industries"],"a":0,"e":"India's income tax is progressive (higher rates on higher income slabs) — while considered pro-poor and the most widely used, popular method globally, it is criticised for potentially discouraging higher earnings and inducing evasion via underreporting of real income."})

upsc.append({"q":"Consider the following as being among the broadly-accepted principles/criteria of a 'good tax system':\n1. Fairness, comprising horizontal equity (similar taxpayers pay similar tax) and vertical equity (better-off taxpayers pay more)\n2. Efficiency, meaning the tax system raises revenue with minimum interference in resource allocation\n3. Administrative simplicity in computation, filing, and collection\n4. Complete elimination of any scope for future modification, to ensure permanence of tax rates\nHow many of the above are genuinely recognised principles of a good tax system?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Fairness (1), efficiency (2), and administrative simplicity (3) are three of the five broadly consensus principles (the other two being flexibility and transparency). Statement 4 is fabricated and indeed contradicts the actual principle of 'flexibility' — a good tax system must have SCOPE for desirable modification when needed, not permanent immutability."})

upsc.append({"q":"The Value Added Tax (VAT), implemented at the state level in India before the rollout of GST, is characterised by which one of the following features?","o":["It is a multi-point tax collected at every stage of value addition, thereby avoiding a 'cascading effect' on prices","It is a single-point tax collected only at the final point of retail sale to the consumer","It necessarily increases the tax burden through a cascading, tax-upon-tax effect at each stage of the supply chain","It was implemented uniformly across all Indian states simultaneously in a single financial year before 2005"],"a":0,"e":"VAT's defining feature is multi-point collection across the value-addition chain, which — unlike the older single-point (non-VAT) method — avoids imposing 'tax upon tax' and hence has no cascading effect on prices, making it suitable for a price-sensitive, high-poverty economy like India."})

upsc.append({"q":"With reference to the original GST design proposed by the Vijay Kelkar Task Force (on the FRBM Act, 2003), which of the following statements is/are correct?\n1. It proposed merging four central taxes and nine state taxes into a single GST.\n2. It proposed a single uniform GST rate of 20 per cent, split as 12 per cent to the Centre and 8 per cent to the states.\n3. It estimated that GST implementation had the potential to raise India's GDP by up to 2 per cent.\nSelect the correct answer using the code below.","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three are correct per the original Kelkar Task Force proposal: merger of 4 central taxes (CENVAT, service tax, stamp duty, central sales tax) and 9 state taxes into GST, a single 20% rate (12% Centre + 8% states), and an estimated GDP boost of up to 2% (a separate, conservative expert estimate cited alongside the Kelkar proposal)."})

upsc.append({"q":"Arrange the following milestones in the actual implementation of India's Goods and Services Tax (GST) in the correct chronological order:\n1. The GST Council (GSTC) was constituted.\n2. The Constitution (101st Amendment) Bill was cleared by Parliament.\n3. GST was formally enforced across the country.\n4. The Government decided, based on the Kelkar Committee report, to introduce GST from 2010-11 (a target later missed).","o":["4-2-1-3","2-4-1-3","4-1-2-3","1-4-2-3"],"a":0,"e":"Correct order: the Government decided in 2006 (based on the Kelkar Committee report) to target a 2010-11 rollout (4); the Constitution (101st Amendment) Bill was cleared by Parliament in early August 2016 (2); the GST Council was constituted by late September 2016 (1); GST was finally enforced on 1 July 2017 (3). The original 2010-11 target was missed by nearly seven years due to Centre-state consensus issues."})

upsc.append({"q":"Which one of the following is NOT among the goods/products explicitly kept outside the ambit of GST (either wholly or as of its initial enforcement in July 2017)?","o":["Automobiles and consumer electronics","Alcoholic liquor for human consumption","Petroleum and petroleum products","Entertainment tax levied specifically by local bodies (kept outside GST subsumption)"],"a":0,"e":"Alcoholic liquor for human consumption, petroleum and petroleum products (to be brought in on a later date), and entertainment tax levied by local bodies (as opposed to state-level entertainment tax, which WAS subsumed) were all explicitly excluded. Automobiles and consumer electronics, however, are very much covered under GST (typically in the higher rate slabs), making this the correct 'NOT' answer."})

upsc.append({"q":"With reference to the GST rate structure and administrative arrangements as implemented from July 2017, consider the following statements:\n1. Goods under GST are taxed under four standard rate bands of 5, 12, 18 and 28 per cent, apart from a category of exempt goods.\n2. A cess over and above the 28 per cent slab is levied on select goods like luxury cars and tobacco products, to fund compensation to states.\n3. States were guaranteed compensation for 5 years for GST-related revenue loss, computed using 2015-16 as the base year and an assumed revenue growth rate of 14 per cent.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct — the 5/12/18/28 per cent bands plus exempt goods, the compensation cess above 28% on luxury/sin goods, and the 5-year compensation guarantee to states (base year 2015-16, 14% assumed annual growth) were all genuine features of the GST rollout."})

upsc.append({"q":"Under the GST administrative-assessment arrangement for taxpayer compliance, which one of the following correctly describes the division of assessee jurisdiction between the Centre and the states?","o":["States assess 90 per cent of assessees with annual turnover below Rs. 1.5 crore, with the remaining 10 per cent assessed by the Centre; for assessees above Rs. 1.5 crore turnover, the split is 50:50","The Centre exclusively assesses all assessees regardless of turnover, with states playing no assessment role","States assess 100 per cent of assessees below Rs. 1.5 crore turnover, and the Centre assesses 100 per cent of assessees above this threshold","The split is a fixed 50:50 between Centre and states for assessees at every turnover level, without any threshold-based distinction"],"a":0,"e":"For assessees below Rs. 1.5 crore turnover, the split is 90% (states) to 10% (Centre); for those above Rs. 1.5 crore, it is an even 50:50 split — reflecting the practical reality that the vast majority of small taxpayers are more efficiently handled by state tax administrations."})

upsc.append({"q":"The Minimum Alternate Tax (MAT), introduced via Section 115JB of the Income Tax Act in 1997-98, is best described as:","o":["A tax imposed on 'zero tax' companies at a fixed rate on their 'book profit', ensuring companies that show nil/negative taxable income due to exemptions and depreciation benefits still pay a minimum tax","A tax exclusively applicable to foreign companies operating in India, with no applicability to domestic companies","A tax that has been fully abolished since the Union Budget 2015-16","A surcharge applied only on companies operating in the infrastructure and power sectors"],"a":0,"e":"MAT targets 'zero tax' companies that, despite high 'book profit' under the Companies Act (and even paying dividends), show nil or negative taxable income under the Income Tax Act due to exemptions, deductions, and accelerated depreciation — MAT is levied on book profit to ensure a minimum tax payment; it explicitly EXEMPTS infrastructure/power sector companies, free trade zones, charitable activities, and venture/angel funds, and applies to both domestic AND foreign companies with Indian income sources."})

upsc.append({"q":"A company reports a 'book profit' of Rs. 20 lakh. After claiming permissible deductions, exemptions, and depreciation, its taxable income under the Income Tax Act comes down to Rs. 8 lakh. Assuming a flat corporate income tax rate of 30 per cent and a MAT rate of 18.5 per cent on book profit, which one of the following is correct regarding the tax the company must actually pay?","o":["The company must pay Rs. 3.7 lakh, since the MAT liability (18.5% of Rs. 20 lakh book profit) exceeds the regular income tax liability (30% of Rs. 8 lakh taxable income, i.e., Rs. 2.4 lakh), and MAT requires payment of whichever amount is higher","The company must pay only Rs. 2.4 lakh, since regular income tax always takes precedence over MAT","The company pays both taxes cumulatively, i.e., Rs. 3.7 lakh plus Rs. 2.4 lakh","The company pays no tax at all since its book profit exceeds its taxable income"],"a":0,"e":"Regular income tax = 30% of Rs. 8 lakh = Rs. 2.4 lakh. MAT = 18.5% of Rs. 20 lakh book profit = Rs. 3.7 lakh. Since MAT law requires the company to pay whichever of the two amounts is HIGHER, the company must pay Rs. 3.7 lakh (and can carry forward the MAT credit — the excess over regular tax — for set-off against future regular tax liability, within the prescribed carry-forward period)."})

upsc.append({"q":"With reference to India's 'MAT credit' mechanism, which one of the following statements is correct?","o":["The excess of MAT paid over regular income tax liability can be carried forward and set off against regular tax payable in future years, with the carry-forward period extended from 10 to 15 years by the Union Budget 2017-18","MAT credit refers to a permanent tax exemption granted to companies operating in Special Economic Zones","MAT credit can only be utilised in the same financial year in which it arises, with no carry-forward permitted","The carry-forward period for MAT credit was reduced from 15 years to 10 years by the Union Budget 2017-18"],"a":0,"e":"MAT credit — the excess of MAT paid over the regular tax liability in a given year — can be carried forward and adjusted against future regular tax dues; the Union Budget 2017-18 extended this carry-forward window from 10 years to 15 years, even as it simultaneously began phasing out MAT exemptions for companies from April 2017."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_taxation_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
