import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_survey_budget_indices (Ramesh Singh Ch.18/22) —
# Zero-Base Budgeting, Charged Expenditure, Golden Rule, Gender Budgeting,
# Outcome vs Performance Budget, Cut Motion types, Guillotine, Gini
# Coefficient, PARA/bad bank (Economic Survey 2016-17)
# ==================================================================

upsc.append({"q":"Which one of the following statements about Zero-Base Budgeting (ZBB) is correct?","o":["It was first proposed for government budgeting by US financial expert Peter Phyrr, with Jimmy Carter (as Governor of Georgia, and later as US President in 1979) being the first elected executive to introduce it to the public sector","ZBB originated in India before being adopted by the United States government","ZBB requires the government to double public expenditure allocations every fiscal year","ZBB has been in continuous, universally successful use across all Indian PSUs since 1991"],"a":0,"e":"ZBB was proposed for government budgeting by Peter Phyrr, with Jimmy Carter first introducing it to the public sector as Georgia's Governor and later applying it to the 1979 US Budget as President — India is believed to have adopted ZBB practices since around 1997-99, with mixed, not universal, success even among profit-making PSUs."})

upsc.append({"q":"Under Zero-Base Budgeting (ZBB), which one of the following are the three essential questions that must be answered before any expenditure allocation?","o":["Should we spend? How much should we spend? Where should we spend?","Who authorised the spending? When was it authorised? Why was it delayed?","What is the previous year's allocation? Should it be increased? By how much?", "Is the expenditure charged or voted? Is it plan or non-plan? Is it capital or revenue?"],"a":0,"e":"ZBB's three defining questions — should we spend, how much should we spend, and where should we spend — require each department to justify every activity from a hypothetical 'zero base' each budget cycle, contrasting with the traditional approach of incrementally adjusting the previous year's allocation."})

upsc.append({"q":"Consider the following statements about 'Charged Expenditure' in the Indian Budget:\n1. It refers to expenditure that is directly withdrawn from the Consolidated Fund of India without requiring a vote by Parliament.\n2. Examples include the emoluments of the President, the Speaker and Deputy Speaker of the Lok Sabha, and Judges of the Supreme Court and High Courts.\n3. All defence expenditure in India is classified as 'charged expenditure'.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe charged expenditure (a small category of expenditure exempted from Parliamentary voting, covering constitutional functionaries' emoluments). Statement 3 is incorrect — defence expenditure is NOT generally classified as charged expenditure and remains subject to the normal voted-expenditure process, unlike Zero-Base Budgeting's own separate observation that defence, being hard to subject to cost-benefit analysis, poses a distinct challenge."})

upsc.append({"q":"The 'Golden Rule' of public finance, as discussed in the context of India's fiscal policy, refers to which one of the following propositions?","o":["A government should borrow only to finance investment (capital expenditure) and not to fund current spending (revenue expenditure)","A government must always maintain a balanced budget with zero fiscal deficit","A government should borrow exclusively from external sources rather than domestic markets","A government must spend an equal amount on defence and social sectors each year"],"a":0,"e":"The Golden Rule holds that borrowing should finance only capital/investment expenditure, not revenue/current spending — a prudent principle, though the text cautions its soundness depends on spending being honestly classified as investment, on such investment being efficient, and on it not crowding out private investment."})

upsc.append({"q":"With reference to 'Gender Budgeting' in India, which one of the following statements is correct?","o":["It began with the Union Budget 2006-07, which proposed an outlay of Rs. 28,737 crore for women-focused programmes and created gender budgeting cells in 32 ministries and departments","Gender budgeting refers to a separate, standalone budget presented exclusively by the Ministry of Women and Child Development","It was introduced through a constitutional amendment mandating equal budgetary allocation by gender","Gender budgeting cells exist in only two ministries in India as of the book's reference period"],"a":0,"e":"Gender budgeting in India commenced with the Union Budget 2006-07 (Rs. 28,737 crore outlay, gender budgeting cells created across 32 ministries/departments) — it is a general budget allocating funds and responsibilities by gender consideration, not a standalone separate budget, and was introduced through budgetary practice rather than constitutional amendment."})

upsc.append({"q":"Which one of the following correctly distinguishes 'Outcome Budget' from 'Performance Budget' in India's result-oriented budgeting framework?","o":["Outcome Budget is presented at the micro level by individual departments/divisions of a ministry, while Performance Budget is a macro-level document presented by the Ministry of Finance on behalf of the government","Outcome Budget and Performance Budget are identical documents, differing only in name","Performance Budget is prepared only for defence-related ministries, while Outcome Budget covers all other ministries","Outcome Budget is a purely qualitative document with no quantitative targets, unlike the Performance Budget"],"a":0,"e":"Outcome Budgets are micro-level documents from individual departments/divisions, while the Performance Budget is a single macro-level document from the Ministry of Finance summarising overall government performance — there are many outcome budgets within one performance budget, and both incorporate quantitative AND qualitative progress reporting."})

upsc.append({"q":"Consider the following types of 'Cut Motions' that Parliament may move to reduce demands for grants proposed in the Union Budget:\n1. Token Cut — reduces the demand by Rs. 100 to express a specific grievance within government responsibility\n2. Economy Cut — reduces the demand by a specified amount representing possible economy in expenditure\n3. Disapproval of Policy Cut — reduces the demand to Re. 1, representing disapproval of the underlying policy\nHow many of the above are genuine categories of Cut Motion in Indian parliamentary practice?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three are genuine, distinct categories of Cut Motion under Indian parliamentary procedure — Token Cut (Rs. 100, specific grievance), Economy Cut (specified expenditure reduction), and Policy Disapproval Cut (Re. 1, opposing the underlying policy) — each confining debate to its specific scope."})

upsc.append({"q":"With reference to the 'Guillotine' procedure in the context of the Union Budget's passage through Parliament, which one of the following is correct?","o":["It is the process by which the Speaker puts all outstanding demands for grants directly to vote, ending further discussion, and has never resulted in a government being voted out of power in India to date","It refers to the automatic rejection of the entire Union Budget if not passed within a fixed number of days","It is a provision under which the President can unilaterally amend the Budget without parliamentary approval","It applies only to Budgets presented during a national Emergency"],"a":0,"e":"The Guillotine allows the Speaker to put all remaining demands for grants to vote at once, curtailing further discussion — while risky in principle (as voting could theoretically take the character of a confidence vote), the text notes this has never actually resulted in an Indian government being voted out of power, unlike the President amending the budget unilaterally or Emergency-specific rules, neither of which describes the Guillotine."})

upsc.append({"q":"The Gini Coefficient, commonly used to measure income inequality within an economy, is best described by which one of the following?","o":["It ranges from zero (perfect equality, every household earning the same income) to one (absolute inequality, a single household earning the entire income)","It ranges from negative one (perfect equality) to positive one (absolute inequality)","It measures only wealth inequality, not income inequality, and cannot be applied to income distribution","A Gini Coefficient of zero indicates the highest possible level of inequality in an economy"],"a":0,"e":"The Gini Coefficient ranges from 0 (perfect equality) to 1 (absolute inequality, all income concentrated in a single household) — it is a standard income (and can also be adapted for wealth) inequality measure, and a value of ZERO represents perfect equality, not the highest inequality."})

upsc.append({"q":"The Economic Survey 2016-17 proposed the creation of a 'Public Sector Asset Rehabilitation Agency' (PARA), popularly referred to as a 'bad bank'. Which one of the following correctly describes its intended purpose?","o":["To clear the 'twin balance sheet' (TBS) problem by addressing both high non-performing assets (NPAs) in public sector banks and negative balance sheets among corporate borrowers, drawing on the experience of South East Asian economies during the 1996-97 currency crisis","To directly recapitalise private sector banks using funds exclusively sourced from foreign direct investment","To replace the Reserve Bank of India as India's banking sector regulator","To manage only the retail deposit insurance function currently performed by the DICGC"],"a":0,"e":"PARA was proposed to tackle India's 'twin balance sheet' problem — high NPAs weighing on public sector banks alongside stressed corporate borrowers unable to service their loans — drawing explicitly on South East Asian economies' use of similar bad-bank-style agencies during their 1996-97 currency crisis; it was not conceived as a recapitalisation-only vehicle, a regulatory replacement for the RBI, or a deposit insurance function (which remains with the DICGC)."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_survey_budget_indices_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
