import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_banking (Ramesh Singh Ch.12, Banking in India)
# Fresh territory confirmed via keyword scan (all zero hits): Regional Rural Banks
# history/Kelkar Committee, Bhandari/Basu Committees, cooperative bank 3-tier
# structure (PACS/DCCB/SCB, UCB dual regulation), Narasimham Committee-I (CFS, 1991)
# detailed recommendations across 5 sub-heads
# ==================================================================

upsc.append({"q":"Consider the following statements about Regional Rural Banks (RRBs) in India:\n1. They were first set up in 1975 with only five banks, aimed at extending banking services to rural areas.\n2. Their share capital is contributed by the Government of India, the concerned state government, and the sponsoring nationalised bank in the ratio 50:15:35.\n3. Following the Kelkar Committee's suggestions, the government stopped opening new RRBs in 1987.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct: RRBs were established on 2 October 1975 with five banks; their capital structure follows the 50:15:35 ratio among GoI, state government and sponsoring bank; and the Kelkar Committee's recommendations led to a halt on opening new RRBs in 1987, by when their number had reached 196."})

upsc.append({"q":"Which two committees were specifically set up in the mid-1990s to address the restructuring and strengthening of loss-making Regional Rural Banks?","o":["The Bhandari Committee (1994-95) and the Basu Committee (1995-96)","The Narasimham Committee-I and Narasimham Committee-II","The Kelkar Committee and the Rangarajan Committee","The Vaghul Committee and the Chakravarty Committee"],"a":0,"e":"The Bhandari Committee (1994-95) and the Basu Committee (1995-96) were specifically tasked with restructuring and strengthening RRBs, which by 1998-99 had 171 out of the total running in losses — distinct from the Narasimham Committees (banking sector reform generally) or Kelkar Committee (which recommended halting new RRBs)."})

upsc.append({"q":"Assertion (A): By the late 1990s, the Government of India abolished RRBs' obligation to extend only concessional loans and freed them to lend to any clientele.\nReason (R): This policy shift was intended to help RRBs recover from the huge losses caused by excessive social banking obligations towards economically weaker sections.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A: RRBs' excessive lean towards social/concessional banking for weaker sections caused heavy losses by the early 1980s, prompting the 1998-99 policy change abolishing the concessional-lending obligation and freeing RRBs to lend commercially to any borrower, helping them recover."})

upsc.append({"q":"Match List-I (tier of India's co-operative banking structure) with List-II (its level of operation) and select the correct answer using the code below.\nList-I:\nA. Primary Credit Societies (PCS)\nB. District Central Co-operative Banks (DCCBs)\nC. State Co-operative Banks (SCBs)\nList-II:\n1. Apex level (state)\n2. District level\n3. Grassroots/local level (agricultural or urban)\nCodes:","o":["A-3, B-2, C-1","A-2, B-3, C-1","A-3, B-1, C-2","A-1, B-2, C-3"],"a":0,"e":"India's co-operative banks follow a three-tier structure: Primary Credit Societies (A) at the grassroots level (3), District Central Co-operative Banks (B) at the district level (2), and State Co-operative Banks (C) at the apex/state level (1)."})

upsc.append({"q":"Consider the following statements about Urban Co-operative Banks (UCBs) in India:\n1. They are governed under state co-operative societies acts as well as the Banking Regulation Act, 1949, making them subject to dual regulatory control.\n2. Registration, management and administration of UCBs are controlled by the RBI, while banking-related matters are regulated by state governments.\n3. Well-managed primary UCBs with deposits over Rs. 50 crore may be allowed to operate in more than one state subject to certain norms.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 3 are correct. Statement 2 reverses the actual division of control — managerial aspects (registration, management, administration, recruitment) are controlled by STATE GOVERNMENTS, while banking-related matters are regulated by the RBI, not the other way round."})

upsc.append({"q":"Which one of the following statements about the supervisory structure of District Central Co-operative Banks (DCCBs) and State Co-operative Banks (SCBs) is correct?","o":["They were originally under RBI supervision, with this function later delegated to NABARD","They have always been supervised exclusively by the Registrar of Co-operative Societies of the respective states","They are supervised jointly by SEBI and IRDAI","One district may have any number of DCCBs, with no restriction"],"a":0,"e":"DCCBs and SCBs were originally supervised by the RBI, a function later delegated to NABARD; also, only one DCCB is permitted per district (reporting to the apex SCB) — the other options misstate both the supervisory history and structural rule."})

upsc.append({"q":"The high-level Committee on the Financial System (CFS), popularly known as the Narasimham Committee-I, was set up on 14 August 1991 based on which core assumption about banking resources?","o":["That bank resources come from the general public and are held in trust to be deployed for the maximum benefit of depositors, meaning the government has no right to use them for its own fiscal purposes at below-market rates","That banks exist primarily as instruments of state economic planning and social banking objectives","That priority sector lending should be permanently expanded to cover all sectors of the economy","That the RBI should have no regulatory authority over public sector banks"],"a":0,"e":"The CFS's recommendations flowed from the core assumption that bank deposits are held in trust for depositors' benefit, implying the government had no business endangering bank solvency for planning/social-banking purposes, nor any right to appropriate bank funds cheaply to finance its own fiscal/revenue deficits."})

upsc.append({"q":"Consider the following recommendations of the Narasimham Committee-I (1991) regarding directed investment (CRR/SLR):\n1. The RBI should progressively reduce CRR from 15 per cent to 3-5 per cent and rely increasingly on Open Market Operations rather than CRR as the principal monetary control instrument.\n2. SLR should be cut from 38.5 per cent to a minimum of 25 per cent over the next five years.\n3. The RBI should discontinue paying any interest on CRR balances held by banks.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct (SLR was indeed cut to 25% by October 1997, as recommended). Statement 3 is false — the Committee actually recommended that the RBI PAY interest on CRR balances above the basic minimum, at a rate equal to banks' one-year deposit rate, not discontinue such payments."})

upsc.append({"q":"Which one of the following statements about the Narasimham Committee-I's recommendations on Priority Sector Lending (PSL) is correct?","o":["It recommended redefining PSL to cover only the weakest sections (marginal farmers, rural artisans, village/cottage industries, tiny sector) with a fixed target of 10 per cent of aggregate bank credit","It recommended expanding PSL to cover all sectors of the economy uniformly at 40 per cent of aggregate bank credit","It recommended abolishing the concept of Priority Sector Lending altogether with immediate effect","It recommended that PSL composition be reviewed only once every ten years"],"a":0,"e":"The Committee recommended a redefined, narrower PSL targeting only the weakest rural sections, fixed at 10% of aggregate bank credit (not the general 40% PSL target that exists separately), phasing out broader directed credit, with composition reviewed every three years — not abolishing PSL nor reviewing it only decennially."})

upsc.append({"q":"Which one of the following was NOT among the Narasimham Committee-I's recommendations on the structural reorganisation of banks?","o":["Nationalisation of all remaining private sector banks to create a fully state-owned banking system","Substantial reduction in the number of public sector banks through mergers and acquisitions","Ending dual control of RBI and the Banking Division of the Ministry of Finance, making RBI the primary regulator","Appointment of bank chief executives (CMDs) based on professionalism and integrity rather than political considerations"],"a":0,"e":"Nationalisation of remaining private banks was never recommended — in fact, the Committee's spirit favoured LESS government control and greater autonomy, and its recommendations directly enabled the opening of NEW private sector banks in 1993, the opposite of further nationalisation."})

upsc.append({"q":"The Narasimham Committee-I's suggestion to tackle the menace of high non-performing assets (NPAs) of banks and financial institutions, inspired by the US experience, was the establishment of:","o":["Asset Reconstruction Companies/Funds","The Insolvency and Bankruptcy Board of India","The Banking Ombudsman Scheme","The Prompt Corrective Action Framework"],"a":0,"e":"The Committee recommended setting up Asset Reconstruction Companies/Funds to address NPAs, drawing on the US experience — a concept later realised in India (e.g., ARCIL). The Insolvency and Bankruptcy Code, Banking Ombudsman Scheme, and Prompt Corrective Action framework are all separate, later regulatory developments."})

upsc.append({"q":"Which one of the following statements about the Narasimham Committee-II (1998) is correct?","o":["It was set up in December 1997 under the chairmanship of M. Narasimham, tasked with reviewing banking sector reform progress and charting a programme to make India's financial system internationally competitive","It was set up before the Narasimham Committee-I and provided the original blueprint for 1991-92 banking reforms","It was headed by Bimal Jalan and focused exclusively on cooperative bank reform","It recommended reversing the 1993 decision to permit new private sector banks"],"a":0,"e":"The Narasimham Committee-II, set up in December 1997 under M. Narasimham himself (reporting in April 1998), reviewed banking reform progress since 1991-92 and proposed further steps for international competitiveness — it came AFTER Committee-I (not before), was not headed by Bimal Jalan, and did not seek to reverse private bank entry."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_banking_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
