import json

upsc = []

# ==================================================================
# NEW UPSC TIER: ECONOMIC REFORMS (Ramesh Singh Ch.6)
# Avoiding overlap with existing basic/intermediate/advanced (BoP crisis basics,
# NIP 1991, FEMA/FERA, Narasimham Committee, MRTP, SEBI, licensing)
# ==================================================================

upsc.append({"q":"Which one of the following correctly lists the three 'alternative development strategies' whose shifting sequence, per Ramesh Singh's framework, defines the historical meaning of 'economic reform'?","o":["The Planning Model, the Washington Consensus, and the Mixed Economy (East Asian-style)","Capitalism, Feudalism, and Mercantilism","Import Substitution, Export Promotion, and Autarky","Gold Standard, Bretton Woods, and Floating Exchange Rates"],"a":0,"e":"The text frames global economic reform history as a shift among three alternative development strategies: the state-led Planning Model (inspired by the USSR), the market-fundamentalist Washington Consensus (1980s), and the balanced Mixed Economy model (validated by the East Asian economies) — not the other listed groupings."})

upsc.append({"q":"Consider the following statements about India's Balance of Payments crisis and IMF conditionalities of 1991:\n1. The IMF's Extended Fund Facility required devaluation of the rupee by about 22 per cent.\n2. Peak import tariffs were to be drastically reduced from around 130 per cent to 30 per cent.\n3. All government expenditure was required to be increased by 10 per cent annually to boost demand.\n4. Excise duties were to be hiked to neutralise revenue shortfalls from customs tariff cuts.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 4 are correct IMF conditionalities. Statement 3 is false and reverses the actual condition — government expenditure was required to be CUT by 10 per cent annually (not increased), as part of fiscal consolidation, not demand-boosting."})

upsc.append({"q":"Which one of the following statements about the origins of India's 1991 reforms, as distinguished from many other reforming nations, is correct?","o":["Unlike several other countries that voluntarily chose reform, India's reforms were an involuntary/obligatory response to conditionalities attached to the IMF's Extended Fund Facility support during the Balance of Payments crisis","India's 1991 reforms were entirely self-initiated with no external conditionalities of any kind","The IMF provided support to India with no conditions attached, unlike its dealings with other countries","India's reforms were mandated directly by a public referendum held in 1991"],"a":0,"e":"The text explicitly distinguishes India's reforms as 'obligatory' (tied to IMF Extended Fund Facility conditionalities during the BoP crisis) rather than a voluntary policy choice, unlike some other reforming economies — not a no-conditions scenario or a referendum-driven process."})

upsc.append({"q":"Assertion (A): India's economic reforms are often criticised as being 'anti-poor' and 'pro-rich' despite pushing the economy to a higher growth path.\nReason (R): Structural reform measures, aimed at boosting aggregate supply, are carried out by producers/capitalists, making them appear 'pro-industrialist' even though rising income eventually takes time to reach and benefit the wider population.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are accurate and R directly explains A — the text argues structural reforms necessarily involve producers/capitalists first, creating a superficial 'pro-rich' appearance, even though the ultimate aim is broader income growth that takes time to percolate to the masses."})

upsc.append({"q":"Which one of the following correctly distinguishes the roles of 'liberalisation', 'privatisation' and 'globalisation' (the LPG framework) in India's reform process, as conceptually framed in the text?","o":["Liberalisation indicates the direction of reform (toward the market), privatisation indicates the path/route of reform, and globalisation represents the ultimate goal of the reform process","Privatisation indicates the direction, liberalisation indicates the path, and globalisation indicates a preliminary precondition","Globalisation indicates the direction, privatisation the ultimate goal, and liberalisation merely a side effect","All three terms are used interchangeably with no distinct conceptual role assigned to any of them"],"a":0,"e":"The text specifically frames liberalisation as showing the DIRECTION of reform (toward market dominance), privatisation as the PATH via which this direction is achieved, and globalisation as the ultimate GOAL — a specific three-part conceptual mapping, not an interchangeable or differently-ordered one."})

upsc.append({"q":"Which one of the following statements about the term 'privatisation' and its multiple meanings, as used globally and in India, is correct?","o":["Privatisation in its purest sense (100 per cent transfer of state ownership) has been rare among democracies, with the United Kingdom under Margaret Thatcher being cited as the boldest example, a route India has never adopted","India has, on several occasions, undertaken 100 per cent divestment of ownership in PSUs, similar to Thatcher-era UK","Privatisation, in all its senses used worldwide, refers exclusively to selling 100 per cent government stake in an enterprise","Disinvestment, unlike privatisation, always implies complete transfer of ownership regardless of the percentage of shares sold"],"a":0,"e":"The text specifically notes 100 per cent privatisation (pure de-nationalisation) is rare among democracies, with Thatcher-era UK as the boldest example — a route India has 'never ventured into'; disinvestment (a related but distinct term) refers to partial transfers, which may or may not shift majority ownership."})

upsc.append({"q":"According to the OECD's 1995 definition (as cited in the text), globalisation refers to:","o":["A shift from a world of distinct national economies to a global economy in which production is internationalised and financial capital flows freely and instantly between countries","Any cross-border investment by an OECD company outside its country of origin, and nothing more","The complete abolition of all forms of international trade barriers by a fixed target date","A purely cultural phenomenon unrelated to production or capital flows"],"a":0,"e":"The OECD's 1995 definition specifically describes globalisation as a shift toward internationalised production and free, instant cross-border financial capital flows — a broader definition superseding its earlier (narrower, 'cross-border investment by an OECD company') formulation."})

upsc.append({"q":"Consider the following statements about the historical periodisation of globalisation, as discussed in the text:\n1. An earlier phase of global economic integration lasted roughly from 1800 to around 1930.\n2. This earlier globalisation phase was interrupted by the Great Depression and the two World Wars, leading to new trade barriers.\n3. The concept of globalisation was popularised again by the OECD only in the mid-1980s.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — an earlier globalisation wave (1800-1930) was disrupted by the Great Depression and World Wars (leading to 1930s protectionism), and the OECD re-popularised the concept in the mid-1980s, ahead of the Uruguay Round/WTO's formal establishment in 1994-95."})

upsc.append({"q":"Which one of the following correctly matches India's 'generations' of economic reform with their principal defining focus?","o":["First Generation (1991-2000): private sector promotion, PSU/external/financial sector and tax reforms; Second Generation (2000-01 onward): factor market reforms (dismantling the Administered Price Mechanism) and legal/critical-area reforms; Third Generation: strengthening Panchayati Raj Institutions for inclusive reform delivery","First Generation: Panchayati Raj strengthening; Second Generation: private sector promotion; Third Generation: factor market/APM reforms","All three generations of reform focus exclusively on the financial sector, with no distinction between them","Third Generation reforms were officially launched before the First Generation reforms, in a reverse chronological sequence"],"a":0,"e":"The correct mapping is First Generation (1991-2000: private-sector promotion, PSU/external/financial/tax reforms) → Second Generation (2000-01 onward: factor market/APM reforms plus legal and critical-area reforms) → Third Generation (from the Tenth Plan era: strengthening PRIs for inclusive reform delivery) — not the reversed or conflated groupings in the other options."})

upsc.append({"q":"Which one of the following is NOT considered an official 'generation' of economic reform in India, despite being coined by some experts?","o":["The Fourth Generation, entailing a fully information-technology-enabled India","The First Generation (1991-2000)","The Second Generation (2000-01 onward)","The Third Generation (from the Tenth Plan era)"],"a":0,"e":"The 'Fourth Generation' of reforms (IT-enabled India, coined by some experts around 2002) is explicitly noted as NOT an official government-recognised generation of reform, unlike the First, Second and Third Generations, which were officially announced."})

upsc.append({"q":"Which one of the following statements about the 'Administered Price Mechanism' (APM), targeted under India's Second Generation reforms, is correct?","o":["Under the APM, prices of certain products (e.g., petroleum, sugar, fertilizers, drugs) were fixed/regulated by the government even though many were produced by the private sector, hindering profitability and industry expansion","The APM applied exclusively to goods produced by government-owned enterprises, never to privately produced goods","The APM was fully dismantled in its entirety immediately upon the launch of the Second Generation reforms in 2000-01","The APM has no connection whatsoever to petroleum product pricing in India"],"a":0,"e":"The APM specifically covered products like petroleum, sugar, fertilizers and drugs — many of which WERE produced by the private sector but sold at government-regulated (not market) prices, hindering profitability — and its dismantling has been a long-drawn, still-ongoing process (e.g., urea remains under APM), not an instant one-time event."})

upsc.append({"q":"Which one of the following correctly distinguishes the 'Gradualist Approach' (followed by India) from the 'Stop-and-Go Approach' (followed by countries like Brazil, Argentina and South Africa) to economic reform?","o":["The Gradualist Approach proceeds incrementally with occasional reversals and no big ideological U-turns, reflecting pluralistic democratic compulsions, while the Stop-and-Go Approach activates pinpointed prerequisite and substantive reforms simultaneously, yielding faster (if riskier) results","The Stop-and-Go Approach is the incremental one, while the Gradualist Approach involves simultaneous activation of all reforms at once","Both approaches are identical in practice, differing only in name","India abandoned the Gradualist Approach entirely in favour of the Stop-and-Go Approach after 2000"],"a":0,"e":"The Gradualist (incremental) Approach — India's path — proceeds with occasional reversals and no sharp ideological shifts due to pluralistic democratic constraints, whereas the Stop-and-Go Approach (Brazil, Argentina, South Africa, etc.) activates prerequisite and substantive reforms together, delivering results on more expected lines but with higher socio-political risk — not the reversed or merged characterisations in the other options."})

upsc.append({"q":"Which of the following are correctly identified in the text as examples of India's 'transformational reforms' as described in the Union Budget 2017-18?\n1. Setting up the Monetary Policy Committee and inflation targeting via an amendment to the RBI Act, 1934.\n2. Demonetisation of high-denomination currency notes.\n3. Enactment of a new Benami Transactions law and a Bankruptcy Law.\n4. Complete abolition of the Goods and Services Tax framework.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are genuine examples of 'transformational reforms' cited in the Union Budget 2017-18. Statement 4 is false and fabricated — GST was being introduced/implemented around this period, not abolished."})

upsc.append({"q":"Which one of the following statements about criticisms of India's economic reforms process, as candidly acknowledged even by government figures, is correct?","o":["A Union Minister publicly stated at the 2007 Davos World Economic Forum summit context that benefits of higher growth were accruing to select 'classes' rather than the 'masses'","No Indian government official has ever publicly acknowledged that reform benefits were unevenly distributed","The reform process has been universally praised without any criticism since its inception in 1991","The slogan 'reforms with a human face' has been widely credited with successfully building broad popular support for reforms"],"a":0,"e":"The text cites an Indian Cabinet Minister's 2007 acknowledgement (around the Davos World Economic Forum context) that growth benefits were going to select 'classes', not the 'masses' — directly contradicting the other options, which claim either no criticism or successful popular buy-in via the 'human face' slogan (which the text says 'utterly failed' to garner mass empathy)."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_reforms_1991_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
