import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_insurance_pension (Ramesh Singh Ch.13, Insurance in India)
# LIC/GIC nationalisation history, AICIL, Malhotra Committee/IRDA, Insurance Laws
# Amendment Act 2015 (FDI cap), reinsurance/GIC Re, DICGC history, FRDI Bill
# ==================================================================

upsc.append({"q":"Consider the following statements about the nationalisation of India's life and general insurance businesses:\n1. The life insurance business was nationalised in 1956, forming the LIC, which absorbed around 245 Indian and foreign companies then operating in the segment.\n2. The general insurance business was nationalised in 1971-72, forming the GIC, which absorbed around 107 Indian and foreign companies.\n3. Opening of private life insurance companies remained prohibited from 1956 until the passage of the IRDA Act in 1999.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct: LIC (1956) absorbed ~245 companies in life insurance, GIC (1971-72) absorbed ~107 companies in general insurance, and the private life insurance ban persisted until the IRDA Act, 1999 reopened the sector."})

upsc.append({"q":"Which one of the following was NOT among the four original holding companies of the General Insurance Corporation of India (GIC) when it commenced operations on 1 January 1973?","o":["Agriculture Insurance Company of India Limited","National Insurance Company Ltd.","New India Assurance Company Ltd.","Oriental Fire and Insurance Company Ltd."],"a":0,"e":"The four original GIC holding companies were National Insurance Company Ltd., New India Assurance Company Ltd., Oriental Fire and Insurance Company Ltd., and United India Insurance Company Ltd. The Agriculture Insurance Company of India Limited (AICIL) is a separate, dedicated agri-insurer set up much later, in December 2002."})

upsc.append({"q":"Consider the following statements about GIC's institutional evolution during the reform era:\n1. In November 2000, GIC was notified as the Indian Reinsurer, subsequently known as GIC Re.\n2. In March 2002, GIC was withdrawn from its holding-company status over the four public sector general insurance companies, which then came under direct Government of India ownership.\n3. GIC Re remains, to date, the only reinsurance company incorporated and headquartered in India.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is technically imprecise in context — while GIC Re was long the only Indian reinsurer, since March 2016 several FOREIGN reinsurance companies received initial (R1) regulatory approval to operate branches in India, ending GIC Re's status as the sole player in the market (though it remains the only India-incorporated one)."})

upsc.append({"q":"Which one of the following statements about the Agriculture Insurance Company of India Limited (AICIL) is correct?","o":["It is majority-owned by GIC (35 per cent) and NABARD (30 per cent), with the four public sector general insurance companies holding 8.75 per cent each","It is a wholly-owned subsidiary of the LIC","It was established in 1972 alongside the GIC to handle agricultural risk","It currently administers only the Modified National Agriculture Insurance Scheme (MNAIS), having no role in the PMFBY"],"a":0,"e":"AICIL (set up December 2002, commenced business April 2003) is jointly owned by GIC (35%), NABARD (30%), and the four public sector general insurers (8.75% each) — it was established decades after GIC, and since January 2016 administers the Pradhan Mantri Fasal Bima Yojana (PMFBY), which subsumed both NAIS and Modified NAIS."})

upsc.append({"q":"The Insurance Reforms Committee (IRC), whose January 1994 report catalysed India's insurance sector reforms including eventual passage of the IRDA Act, was chaired by which one of the following?","o":["R.N. Malhotra, former RBI Governor","M. Narasimham, former RBI Deputy Governor","Bimal Jalan, former RBI Governor","Y.V. Reddy, former RBI Governor"],"a":0,"e":"The Insurance Reforms Committee, set up in April 1993 and reporting in January 1994, was chaired by R.N. Malhotra, a former RBI Governor — hence it is also popularly known as the Malhotra Committee."})

upsc.append({"q":"Consider the following recommendations attributed to the Malhotra Committee (1994) on insurance sector reform:\n1. Decontrolling the insurance sector to allow Indian and foreign private companies entry.\n2. Cutting down government holding in LIC and GIC to 50 per cent.\n3. Setting up a dedicated regulatory authority for the insurance industry.\n4. Fully privatising LIC by transferring 100 per cent of government shares to private investors.\nHow many of the above are genuine Malhotra Committee recommendations?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are genuine recommendations (leading respectively to the IRDA Act 1999, an as-yet-unfulfilled 50% government-holding target, and the IRDA's establishment in 2000). Statement 4 is fabricated — full privatisation of LIC (100% divestment) was never among the Committee's recommendations; even the 50% target has seen no follow-up, with only limited LIC share sales to public sector undertakings starting late 2012."})

upsc.append({"q":"Which one of the following legislations increased the permissible FDI limit in India's insurance sector from 26 per cent to 49 per cent, with FDI up to 49 per cent allowed under the automatic route?","o":["The Insurance Laws (Amendment) Act, 2015","The IRDA Act, 1999","The Insurance Act, 1938","The Financial Resolution and Deposit Insurance (FRDI) Bill"],"a":0,"e":"The Insurance Laws (Amendment) Act, 2015 raised the FDI ceiling in insurance from 26% to 49%, permitting up to 49% under the automatic route (beyond which Ministry of Finance approval is required) — distinct from the original IRDA Act (1999, which established the regulator) or the Insurance Act, 1938 (the foundational insurance law)."})

upsc.append({"q":"Consider the following statements about reinsurance in India:\n1. Reinsurance emerged because insurance companies themselves face high financial risk exposure and need cover for their own underwriting business.\n2. In the absence of reinsurance, experts believe insurance companies would either avoid covering certain risk areas or charge very high premiums.\n3. In March 2016, IRDA granted initial (R1) regulatory approval to four foreign reinsurance companies, including Munich Re (Germany) and Swiss Re (Switzerland).\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — reinsurance addresses insurers' own risk exposure and market-development concerns, and in March 2016 IRDA gave R1 approval to four foreign reinsurers: Munich Re and Hannover Re (Germany), Swiss Re (Switzerland), and SCOR (France), with Reinsurance Group of America (USA) and XL Catlin (UK) still awaiting approval at that time."})

upsc.append({"q":"Which one of the following statements about the Deposit Insurance and Credit Guarantee Corporation (DICGC) is correct?","o":["It was formed in 1978 by merging the Deposit Insurance Corporation (1962) and the Credit Guarantee Corporation (1971)","It was established directly in 1978 with no predecessor institutions","It has, since the 1990s reforms, shifted its focus increasingly towards credit guarantees rather than deposit insurance","It currently insures unlimited deposit amounts per depositor per bank"],"a":0,"e":"DICGC (1978) resulted from merging the earlier Deposit Insurance Corporation (1962) and Credit Guarantee Corporation (1971) — post-1990s reforms actually shifted its focus BACK towards its core deposit insurance function (as credit guarantees were phased out), and deposit insurance coverage is capped (Rs. 1 lakh per depositor per bank, as per the book's reference period), not unlimited."})

upsc.append({"q":"Assertion (A): The Financial Resolution and Deposit Insurance (FRDI) Bill, proposed in 2017-18, faced significant public criticism and was referred to a Joint Parliamentary Committee.\nReason (R): Critics interpreted Section 52 of the Bill, empowering a proposed Resolution Corporation to 'write down failed banks' liabilities', as an effective 'bail-in' clause risking depositors' money.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — the 'bail-in' interpretation of Section 52 (empowering write-down of failed banks' liabilities) triggered widespread public apprehension, leading the government to refer the Bill to a Joint Parliamentary Committee, even as the government itself denied such apprehensions were warranted."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_insurance_pension_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
