import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_agriculture (Ramesh Singh Ch.8)
# Fresh territory confirmed via keyword-blob scan of existing 55 Qs (all zero hits):
# land reforms, zamindari/mahalwari/ryotwari, tenancy, land ceiling, bhoodan,
# land records modernisation, model land leasing law, land acquisition act,
# agriculture holdings census/classification, food philosophy of India (3 phases),
# animal rearing/dairy schemes (National Dairy Plan, Pig Rearing Scheme, fodder schemes)
# ==================================================================

# --- Food Philosophy of India (3 phases) ---

upsc.append({"q":"Ramesh Singh's 'Food Philosophy of India' framework divides India's post-Independence food challenge into three successive phases. Which one of the following correctly matches the phase with its primary objective?","o":["Phase I: physical access to food; Phase II: economic access to food; Phase III: ecologically sustainable access to food","Phase I: economic access to food; Phase II: physical access to food; Phase III: export competitiveness in food","Phase I: ecological sustainability; Phase II: physical access; Phase III: economic access","Phase I: export-led food surplus; Phase II: physical access; Phase III: economic access"],"a":0,"e":"Phase I (first three decades after Independence) targeted physical access to food (producing enough foodgrains); Phase II targeted economic access (affordability, purchasing power) once physical self-sufficiency was achieved by the late 1980s; Phase III, from the early 1990s, added the goal of ecologically sustainable food production, inspired by the Brundtland Report's critique of industrial agriculture."})

upsc.append({"q":"Consider the following statements regarding the 'second phase' of India's food philosophy as described in the Economic Survey:\n1. It emerged even as India was celebrating physical self-sufficiency in foodgrains achieved via the Green Revolution.\n2. A Public Interest Litigation by the People's Union for Civil Liberties led to Supreme Court intervention on hunger amid surplus buffer stocks.\n3. India emerged as the seventh largest exporter of wheat in 2002 despite widespread economic inability of many citizens to buy food.\n4. The government successfully resolved this phase entirely through steep cuts in food subsidies.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are correct and reflect the actual historical record (PUCL PIL, paradox of buffer stocks amid starvation deaths, India as 7th largest wheat exporter in 2002). Statement 4 is false — the crisis was instead managed by RAISING food subsidies (not cutting them), which strained government expenditure on agricultural infrastructure."})

upsc.append({"q":"Which international report is credited by the Economic Survey with prompting the 'third phase' of India's food philosophy, in which ecological sustainability was added as a food-security objective alongside physical and economic access?","o":["The Brundtland Report ('Our Common Future')","The Stern Review on the Economics of Climate Change","The Club of Rome's 'Limits to Growth'","The World Bank's World Development Report 1990"],"a":0,"e":"The Brundtland Report, from the 1987 'Our Common Future' summit on sustainable development, is credited with prompting global (and Indian) re-examination of industrial-style agriculture, adding ecological sustainability as a third pillar of India's food philosophy alongside physical and economic access to food, motivating the idea of a 'Second Green Revolution'."})

# --- Land Reforms Phase I ---

upsc.append({"q":"Consider the following land tenure systems that were targeted for abolition under 'Phase I' land reforms in India:\n1. Zamindari\n2. Mahalwari\n3. Ryotwari\n4. Bhoodan\nHow many of the above are genuine pre-Independence land tenure systems that were abolished under India's land reforms?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Zamindari, Mahalwari and Ryotwari were the three actual colonial-era land tenure/revenue systems abolished under the 'abolition of intermediaries' step of land reforms. Bhoodan ('land gift') was, in contrast, a voluntary land-donation movement led by Acharya Vinoba Bhave, not a tenure system requiring abolition."})

upsc.append({"q":"The three inter-related reforms carried out under 'Tenancy Reforms' in Phase I of India's land reforms included all of the following EXCEPT:","o":["Consolidation of scattered landholdings into single, compact plots","Regulation of rent so that a fixed and rational rate could be paid by share-croppers","Security of tenure for share-croppers","Conferring ownership rights on tenants under the principle of 'land to the tillers'"],"a":0,"e":"Consolidation of holdings was carried out under 'Reorganisation of Agriculture', a separate step from Tenancy Reforms. Tenancy Reforms specifically comprised rent regulation, security of tenure, and ownership rights to tenants."})

upsc.append({"q":"With reference to the numerical outcomes of India's Phase I land reforms by 1992, which one of the following statements is correct?","o":["Tenancy reforms conferred rights on only about 4 per cent of the total operated area, and ownership redistribution covered only about 2 per cent, together benefiting just around 6 per cent of the operated area","Tenancy reforms and redistribution together benefited more than 40 per cent of the total operated area of the country","Ownership redistribution alone covered over 25 per cent of the total operated area","Consolidation of landholdings succeeded uniformly across all major agricultural states"],"a":0,"e":"The actual figures cited are strikingly small: tenancy reforms covered only ~4% of operated area (14.4 million ha among 11 million tenants), redistribution only ~2% (under 2 million ha among 4.76 million people), totalling a negligible ~6% combined — while consolidation succeeded only in Green Revolution belt states (Punjab, Haryana, western UP), not uniformly."})

upsc.append({"q":"Assertion (A): Cooperative farming, envisaged as a step with a 'high socio-economic moral base' under land reform Phase I, largely failed to achieve its redistributive intent.\nReason (R): Cooperative farming was primarily used by big farmers as a device to circumvent land ceiling laws and protect their landholdings.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are accurate and R correctly explains A: the book explicitly notes cooperative farming, despite its moral appeal, was 'only used by the big farmers to save their lands from the draconian ceiling laws' — precisely why it failed to serve the poor as intended."})

upsc.append({"q":"Which of the following are cited among the key reasons for the failure of land reforms in India?\n1. Land being viewed as a symbol of social prestige and identity rather than a mere economic asset.\n2. Lack of political will to implement reforms effectively.\n3. Rampant corruption and leadership failure in the democratic system.\n4. Active support from land-owning caste lobbies for redistributive reforms.\nSelect the correct answer using the code below.","o":["1, 2 and 3 only","All four","2, 3 and 4 only","1 and 4 only"],"a":0,"e":"Statements 1, 2 and 3 are the three reasons explicitly cited for the failure of land reforms. Statement 4 is the reverse of the truth — land-owning caste lobbies actively OPPOSED land reforms (unlike the Green Revolution, which they did not oppose)."})

upsc.append({"q":"Which one of the following statements correctly explains why the Green Revolution effectively marginalised the agenda of land reforms in India?","o":["The Green Revolution favoured larger, economically viable holdings, working against the land reform goal of fragmenting land among a larger number of people, and faced no social opposition unlike land reforms","The Green Revolution was fully compatible with land redistribution and reinforced the land reform agenda","Land reforms had already been fully successfully implemented by the time the Green Revolution began","The Green Revolution was implemented only in states where land reforms had already redistributed all land"],"a":0,"e":"The book identifies an inherent tension: the Green Revolution suited bigger, economically consolidated holdings while land reforms sought fragmentation for equity; further, land-owning caste lobbies opposed land reforms but not the Green Revolution, which also had demonstrable yield benefits and World Bank/international backing — together marginalising the land reform agenda."})

# --- Land Reforms Phase II ---

upsc.append({"q":"The 'Phase II' of land reforms in India, as identified in the Economic Survey 2012-13, envisages a three-step policy approach. Which one of the following correctly lists these three steps?","o":["Careful mapping of land with conclusive title; a fair and speedy land acquisition process; a transparent and effective land leasing policy","Zamindari abolition; tenancy regulation; land ceiling enforcement","Cooperative farming promotion; consolidation of holdings; redistribution of ownership","Nationalisation of all agricultural land; state-run cooperative societies; abolition of private landholding"],"a":0,"e":"Phase II land reforms, per Economic Survey 2012-13, comprise: (i) mapping land carefully with conclusive title, (ii) devising a fair but speedy land acquisition process, and (iii) putting in place a transparent, effective land leasing policy — a shift from Phase I's redistributive focus towards facilitating land markets."})

upsc.append({"q":"Consider the following statements about the National Land Records Modernisation Programme (NLRMP):\n1. It was started in 2008 with the aim of digitising and updating land records.\n2. Its ultimate intent is to shift India from a 'conclusive title' system to a 'presumptive title' system.\n3. Digitisation is expected to lower the costs of land transactions and reduce legal uncertainty.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 3 are correct. Statement 2 reverses the actual intent — NLRMP aims to move FROM presumptive title (where registration does not guarantee legal validity of ownership) TO conclusive title (where it does), not the other way round."})

upsc.append({"q":"Which body proposed the 'Model Land Leasing Law' in 2016 to encourage a transparent land leasing market in the states?","o":["NITI Aayog","Planning Commission","Ministry of Rural Development","Commission for Agricultural Costs and Prices"],"a":0,"e":"The Model Land Leasing Law was proposed by NITI Aayog in 2016, aiming to give states a template for transparent and effective land leasing, part of the Phase II land reform agenda following the Planning Commission's dissolution and replacement by NITI Aayog in 2015."})

upsc.append({"q":"Which one of the following pieces of legislation, passed in 2013, sought to amend the Land Acquisition, Rehabilitation and Resettlement framework and was itself later proposed to be amended by a 2015 Bill on Right to Fair Compensation and Transparency in Land Acquisition?","o":["The Land Acquisition Bill, 2013","The Right to Fair Compensation Act, 2011","The National Land Records Modernisation Act, 2013","The Model Land Leasing Law, 2013"],"a":0,"e":"The Land Acquisition Bill, 2013 amended the Land Acquisition, Rehabilitation and Resettlement Act, 2011; it was itself sought to be amended by the 2015 Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Bill, which remained contested and only partially passed with about ten amendments."})

upsc.append({"q":"According to the Economic Survey-based discussion of Phase II land reforms, giving primacy to 'land leasing' over outright land acquisition is argued to have all of the following advantages EXCEPT:","o":["It nationalises agricultural land under direct government ownership","It keeps land ownership in the hands of existing farmers","It prevents mass landlessness and unemployment among farmers","It provides farmers a permanent source of income while enabling reskilling for industrial or service-sector employment"],"a":0,"e":"Land leasing does NOT involve nationalisation — it keeps ownership with existing farmers while enabling productive use, an income stream for farmers, and smoother rural-to-industry labour transition, avoiding landlessness. Nationalisation was never proposed under this reform agenda."})

# --- Agriculture Holdings ---

upsc.append({"q":"As per the 9th Agriculture Census (2010-11), which of the following observations about India's agricultural landholdings is/are correct?\n1. The average size of operational holdings declined compared to the previous Census (2005-06).\n2. The percentage share of female operational holders increased compared to the previous Census.\n3. Small and marginal holdings (below 2 hectares) together account for less than half of all operational holdings.\n4. Large holdings (10 hectares and above) constitute less than 1 per cent of total holdings.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 4 are correct (average size fell to 1.16 ha; female holder share rose to 12.79%; large holdings were just 0.73% of total). Statement 3 is false — small and marginal holdings together were 84.97% (a large majority), not less than half."})

upsc.append({"q":"Match List-I (category of agricultural holding) with List-II (its defining characteristic) and select the correct answer using the code below.\nList-I:\nA. Economic Holding\nB. Family Holding\nC. Optimum Holding\nList-II:\n1. The maximum size of holding that may be possessed by a family\n2. The minimum area needed to ensure a satisfactory standard of living through profitable agriculture\n3. A 'plough unit' sized to give work to an average family under traditional farming\nCodes:","o":["A-2, B-3, C-1","A-1, B-2, C-3","A-2, B-1, C-3","A-3, B-2, C-1"],"a":0,"e":"Economic Holding (A) is the minimum area for a satisfactory standard of living via profitable agriculture (2); Family Holding (B) is the 'plough unit' sized for an average family under traditional farming (3); Optimum Holding (C) is the maximum size a family may possess (1)."})

# --- Animal rearing / Dairy ---

upsc.append({"q":"Consider the following statements about India's livestock and dairy sector:\n1. India ranks first in the world in milk production.\n2. The livestock sector's growth rate during the 12th Plan exceeded both the overall farm sector growth rate and the foodgrains growth rate.\n3. India's per capita availability of milk was below the world average as of 2015-16.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct (India's #1 rank in milk production; livestock growth of 4.5% during the 12th Plan exceeded farm sector's 3.5% and foodgrains' ~1%). Statement 3 is false — India's per capita milk availability (326 grams) actually exceeded the world average (296 grams) in 2015-16."})

upsc.append({"q":"Which Government of India dairy scheme, launched in March 2012, aims to improve productivity of milch animals, strengthen village-level milk procurement infrastructure, and provide producers greater market access?","o":["National Dairy Plan, Phase I","Operation Flood","Intensive Dairy Development Programme","Dairy Entrepreneurship Development Scheme"],"a":0,"e":"The National Dairy Plan, Phase I (launched March 2012) specifically targets improving milch animal productivity, strengthening village-level procurement infrastructure, and enhancing producers' market access — distinct from the older Intensive Dairy Development Programme and Dairy Entrepreneurship Development Scheme, which are separate ongoing GoI dairy-sector schemes."})

upsc.append({"q":"The 'Pig Rearing Scheme' discussed in the context of India's animal husbandry sector is particularly targeted at assisting farmers, landless labourers and cooperatives in which category of states?","o":["The North-Eastern states","The Himalayan states","The coastal states","The drought-prone states of peninsular India"],"a":0,"e":"The Pig Rearing Scheme is aimed particularly at farmers, landless labourers, cooperatives and tribals in the North-Eastern states, encouraging scientific stall-fed pig rearing for quality pork production and organised marketing."})

upsc.append({"q":"Which one of the following statements about fodder and feed availability for livestock in India is correct?","o":["Green fodder shortage in the country is estimated at about 34 per cent, prompting a modified Centrally Sponsored Fodder and Feed Development Scheme since 2014","India faces no significant shortage of green fodder for its livestock population","The Accelerated Fodder Development Programme operates independently of the Rashtriya Krishi Vikas Yojana","Fodder development schemes in India are run exclusively by state governments without central sponsorship"],"a":0,"e":"Green fodder shortage is estimated at ~34%, addressed via a modified Centrally Sponsored Fodder and Feed Development Scheme (since 2014); the Accelerated Fodder Development Programme was in fact launched as a COMPONENT of the Rashtriya Krishi Vikas Yojana (2011-12), not independently of it, and is centrally sponsored, not exclusively state-run."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_agriculture_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
