import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_capital_market_instruments (Ramesh Singh Ch.11, Project
# Financing / Financial Institutions history)
# Fresh territory confirmed via keyword scan (all zero hits): AIFIs (IFCI/ICICI/IDBI/
# SIDBI/IIBI), Narasimhan Committee I & II, S.H. Khan Committee/Universal Banking,
# ICICI-IDBI reverse mergers, TFCI, IFCI Venture, LIC/UTI/GIC evolution as Investment Institutions
# ==================================================================

upsc.append({"q":"Match List-I (All India Financial Institution) with List-II (year of establishment) and select the correct answer using the code below.\nList-I:\nA. IFCI\nB. ICICI\nC. IDBI\nD. SIDBI\nList-II:\n1. 1990\n2. 1964\n3. 1948\n4. 1955\nCodes:","o":["A-3, B-4, C-2, D-1","A-3, B-2, C-4, D-1","A-4, B-3, C-2, D-1","A-3, B-4, C-1, D-2"],"a":0,"e":"IFCI (A) was established in 1948 (3), ICICI (B) in 1955 (4), IDBI (C) in 1964 (2), and SIDBI (D) in 1990 (1) — India's original All India Financial Institutions set up to support project financing for industrialisation."})

upsc.append({"q":"Consider the following statements about India's original All India Financial Institutions (AIFIs) — IFCI, ICICI, IDBI, SIDBI and IIBI:\n1. All of them were public sector financial institutions funded entirely by the Government of India, with no exceptions.\n2. They witnessed a sharp decline as banks acquired a wider capital base and cheaper deposit-based lending became more competitive than the AIFIs' relatively fixed interest rates.\n3. The Narasimhan Committee-I recommended converting them into Development Banks (AIDBs).\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1, 2 and 3","1 and 2 only","1 only"],"a":0,"e":"Statements 2 and 3 are correct. Statement 1 is false — ICICI was a joint-sector venture with initial capital from the RBI, foreign banks and other financial institutions, not a purely government-funded public sector FI like the others."})

upsc.append({"q":"Assertion (A): ICICI's 2000 reverse merger with ICICI Bank produced India's first 'universal bank' with no obligation of project financing.\nReason (R): The concept of Universal Banking in India was originally forwarded by the S.H. Khan Committee on Development Financial Institutions (1998).\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A: the S.H. Khan Committee (1998) first proposed the Universal Banking concept in India, which materialised when ICICI reverse-merged with ICICI Bank in 2000, becoming the first such All India Development Bank (AIDB) freed from mandatory project-financing obligations."})

upsc.append({"q":"Which one of the following statements about the reverse mergers of AIFIs with their banking arms is correct?","o":["Unlike ICICI, the IDBI-IDBI Bank reverse merger (2002) retained the obligation of carrying out project financing duties","Both the ICICI and IDBI reverse mergers resulted in banks with no project-financing obligations","The IDBI-IDBI Bank merger occurred before the ICICI-ICICI Bank merger","IFCI and IIBI were successfully merged with Punjab National Bank in 2002 to form a large universal bank"],"a":0,"e":"IDBI's 2002 reverse merger with IDBI Bank (the second AIDB) retained project-financing obligations, unlike ICICI's 2000 merger which shed them entirely. The IDBI merger came after ICICI's (2000), and the proposed 2002 merger of IFCI/IIBI with PNB did NOT succeed — PNB was reportedly unwilling given their heavy losses."})

upsc.append({"q":"Consider the following statements about the Narasimhan Committee-II's recommendations relevant to the proposed 2002 merger of IFCI and IIBI with Punjab National Bank (PNB):\n1. The Committee's 3-Tier Banking Structure framework was cited as partly supporting such consolidation.\n2. The Committee had explicitly advised against merging weak banks/financial institutions with either weak or strong ones.\n3. The proposed IFCI-IIBI-PNB merger was fully implemented as recommended by the Committee.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct — the proposal was 'part correct, part against' the Committee's actual recommendations, since it followed the 3-Tier structure logic but violated the advice against merging weak FIs with banks. Statement 3 is false, as the merger did not actually go through (PNB was unwilling given IFCI/IIBI's heavy losses)."})

upsc.append({"q":"At present, how many financial institutions operate in India as All India Financial Institutions (AIFIs) regulated by the RBI, and which are they?","o":["Four — NABARD, SIDBI, Exim Bank and NHB","Five — IFCI, ICICI, IDBI, SIDBI and IIBI","Three — NABARD, SIDBI and Exim Bank","Six — all the original AIFIs plus NABARD and NHB"],"a":0,"e":"Only four AIFIs remain today, regulated by the RBI: NABARD, SIDBI, Exim Bank, and the National Housing Bank (NHB) — the original AIFIs (IFCI, ICICI, IDBI, IIBI) have since been converted into banks or otherwise restructured."})

upsc.append({"q":"The Tourism Finance Corporation of India Ltd. (TFCI), incorporated in 1989 following the recommendations of the National Committee on Tourism, is best described as:","o":["A Specialised All-India Development Financial Institution catering to the financial needs of the tourism industry, promoted by IFCI along with other institutions and nationalised banks","A wholly government-owned corporation directly managing India's tourism infrastructure projects","A subsidiary of the Ministry of Tourism responsible for issuing tourist visas","A private equity fund exclusively for foreign hospitality chains investing in India"],"a":0,"e":"TFCI is a Specialised All-India Development Financial Institution promoted by IFCI (holding a 41.6% stake) along with other financial institutions and nationalised banks, notified as a Public Financial Institution in January 1990, to provide financial assistance to tourism-related projects — not a direct infrastructure manager, visa authority, or foreign-exclusive fund."})

upsc.append({"q":"Which one of the following statements about IFCI Venture Capital Funds Ltd. traces its correct institutional lineage?","o":["It began as the Risk Capital Foundation (1975) under IFCI, was converted into Risk Capital and Technology Finance Corporation Ltd. (RCTC) in 1988, and was renamed IFCI Venture Capital Funds Ltd. in February 2000","It began as a UTI subsidiary in 1964 and was later acquired by IFCI in 2000","It was established directly by the RBI in 1990 as India's first venture capital regulator","It has no historical connection to the Risk Capital Scheme or Technology Finance and Development Scheme"],"a":0,"e":"The correct lineage is: Risk Capital Foundation (1975, under IFCI) → Risk Capital and Technology Finance Corporation Ltd. (RCTC, 1988) → IFCI Venture Capital Funds Ltd. (renamed February 2000) — reflecting its shift from soft-loan risk capital assistance to full venture capital and asset management activities."})

upsc.append({"q":"Consider the following statements about India's public sector 'Investment Institutions' (IIs) — LIC, UTI and GIC:\n1. LIC (1956) remains a public sector insurance company and is the lone public sector player in the life insurance segment.\n2. GIC was converted into a public sector re-insurance company in 2000.\n3. UTI was converted into a mutual fund company in 2002 and continues to operate as the sole public sector entity in the Indian Mutual Fund industry.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct: LIC remains the sole public sector life insurer; GIC was converted to a public sector re-insurance company in 2000; and UTI became a mutual fund company in 2002, remaining the lone public sector player in that industry — these three, no longer termed DIIs/DFIs, now function as ordinary industry players competing with private firms."})

upsc.append({"q":"Which committee's recommendation, in 1988, formed the basis for the Government of India's decision to promote a separate All India Financial Institution dedicated to financing tourism-related activities?","o":["The National Committee on Tourism (Yunus Committee)","The Narasimhan Committee","The S.H. Khan Committee","The Vaghul Committee"],"a":0,"e":"The National Committee on Tourism, chaired by (Mohammad) Yunus and set up under the Planning Commission, recommended in 1988 the creation of a dedicated All India Financial Institution for tourism financing, which materialised as the Tourism Finance Corporation of India Ltd. (TFCI) in 1989."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_capital_market_instruments_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
