import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_poverty_unemployment (Ramesh Singh Ch.20/21 —
# Tendulkar Committee poverty estimates, NITI Aayog poverty task force,
# LFPR/unemployment data (5th EUS 2015-16), women's unpaid work, UBI debate
# ==================================================================

upsc.append({"q":"With reference to India's official poverty estimation methodology, which one of the following statements is correct?","o":["The Planning Commission's poverty line was based on Monthly Per Capita Consumption Expenditure (MPCE) data from NSSO large sample surveys, with the currently applicable methodology recommended by an Expert Group headed by Prof. Suresh D. Tendulkar (report submitted December 2009)","Poverty estimation in India has always been based on daily calorie intake alone, with no reference to consumption expenditure","The Tendulkar Committee's methodology was rejected by the government and never used for any official poverty estimates","NSSO conducts its large sample consumer expenditure surveys every year without fail"],"a":0,"e":"The Planning Commission's poverty estimation relied on MPCE data from NSSO's large sample surveys (conducted roughly every five years, not annually), with the currently applicable methodology stemming from the Tendulkar Committee's December 2009 report — this methodology WAS officially adopted and used for subsequent poverty estimates."})

upsc.append({"q":"As per poverty estimates for the period 2004-05 to 2011-12 (based on NSSO's 68th Round, 2011-12, using the Tendulkar methodology), which one of the following correctly reflects the decline in India's poverty ratio?","o":["Total poverty declined from 37.2 per cent to 21.9 per cent; rural poverty from 41.8 per cent to 25.7 per cent; urban poverty from 25.7 per cent to 13.7 per cent","Total poverty declined from 21.9 per cent to 37.2 per cent over the same period","Rural poverty remained unchanged at 41.8 per cent throughout the period","Urban poverty was higher than rural poverty throughout the 2004-05 to 2011-12 period"],"a":0,"e":"Per Tendulkar-methodology estimates: total poverty fell from 37.2% (2004-05) to 21.9% (2011-12), rural poverty from 41.8% to 25.7%, and urban poverty from 25.7% to 13.7% — urban poverty was consistently LOWER than rural poverty throughout, not higher."})

upsc.append({"q":"Owing to controversy and confusion surrounding per-day monetary poverty line estimates, the Government of India, in late 2015, set up a task force to suggest a new poverty estimation method. This task force was headed by which one of the following?","o":["Arvind Panagariya, Vice-Chairman of the NITI Aayog","Suresh D. Tendulkar, former Chairman of the Prime Minister's Economic Advisory Council","C. Rangarajan, former Chairman of the Prime Minister's Economic Advisory Council","Raghuram Rajan, former RBI Governor"],"a":0,"e":"The late-2015 task force on a new poverty estimation methodology was headed by Arvind Panagariya, then Vice-Chairman of the NITI Aayog — distinct from the earlier Tendulkar Committee (2009) or a separate C. Rangarajan-led poverty panel referenced in other contexts."})

upsc.append({"q":"As per the 5th Annual Employment and Unemployment Survey (EUS, 2015-16) conducted by the Labour Bureau, which one of the following correctly describes India's Labour Force Participation Rate (LFPR) and unemployment patterns?","o":["Overall LFPR stood at 50.3 per cent (males 75.0 per cent, females 23.7 per cent), while the unemployment rate for females (8.7 per cent) was higher than for males (4.0 per cent)","Overall LFPR stood at 90 per cent, with negligible gender disparity","The unemployment rate for males was higher than for females across all states","LFPR for females exceeded that of males in most Indian states"],"a":0,"e":"Per the 5th EUS (2015-16), overall LFPR was 50.3% (75.0% male, 23.7% female) — a wide gender gap — while the FEMALE unemployment rate (8.7%) exceeded the male rate (4.0%), the reverse of what the incorrect options suggest; LFPR for females was generally LOWER than males, though the North-Eastern and Southern states showed comparatively higher female LFPR than Northern states."})

upsc.append({"q":"Consider the following statements about employment trends highlighted in the Economic Survey (based on the 5th EUS 2015-16):\n1. There is a clear shift in employment from the primary sector towards the secondary and tertiary sectors.\n2. Employment growth by category shows an increase in both casual labour and contract workers, raising concerns about wage levels and job security.\n3. States with low unemployment rates also generally rank low in the share of manufacturing.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 2 are correct — the sectoral shift towards secondary/tertiary employment and the rise of casual/contract labour (with attendant wage and job-security concerns) are genuine findings. Statement 3 REVERSES the actual finding: states with LOW unemployment rates generally rank HIGH (not low) in the share of manufacturing."})

upsc.append({"q":"With reference to the economic treatment of unpaid work performed predominantly by women in India, which one of the following statements is correct?","o":["Globally, men's share of paid work is around 1.8 times that of women, while women's share of unpaid work is around three times that of men, with unpaid work remaining unaccounted for in the System of National Accounts (SNA)","Paid and unpaid work are both fully captured and valued within the System of National Accounts (SNA)","Women's unpaid work contribution is negligible compared to men's, per global data","Conventional employment and unemployment surveys fully capture the extent of women's unpaid domestic and care work"],"a":0,"e":"Globally, men dominate paid work (about 1.8 times women's share) while women dominate unpaid work (about three times men's share) — and crucially, unpaid work remains UNACCOUNTED for within the System of National Accounts (SNA), unlike paid work; conventional employment/unemployment surveys have similarly failed to capture this unpaid work adequately."})

upsc.append({"q":"With reference to the Universal Basic Income (UBI) proposal discussed in the Economic Survey 2016-17, consider the following statements:\n1. The NITI Aayog CEO proposed targeting the bottom 20 per cent of the Below Poverty Line (BPL) population at the scheme's launch.\n2. The NITI Aayog CEO proposed a monthly transfer of Rs. 1,000, whereas the Economic Survey's illustrative example proposed a considerably higher monthly transfer of Rs. 7,620.\n3. One argument for UBI is that it could reduce 'out of system' leakages, which in the case of the Public Distribution System (PDS) have been estimated at levels running up to 45 per cent.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct — the NITI Aayog CEO's proposal targeted the bottom 20% of BPL population with a Rs. 1,000/month transfer, contrasted with the Economic Survey's illustrative (and substantially higher) Rs. 7,620/month example, with PDS leakage of up to 45% cited as a key argument for UBI's leakage-reduction potential."})

upsc.append({"q":"Which one of the following is cited as a genuine advantage of a Universal Basic Income (UBI) approach over India's existing targeted welfare schemes?","o":["By directly transferring money to bank accounts and bypassing multiple layers of bureaucracy, UBI is less prone to exclusion errors and reduces the scope for 'out of system' leakages","UBI eliminates the need for any government revenue mobilisation, as it is entirely self-financing","UBI requires no identification or targeting mechanism whatsoever, unlike all existing schemes","UBI is guaranteed to cost less than all existing welfare schemes combined, regardless of the transfer amount chosen"],"a":0,"e":"UBI's cited advantage is minimising exclusion errors and reducing 'out of system' leakage by transferring money directly to bank accounts, bypassing bureaucratic layers — it does NOT eliminate the need for financing (the transfer amount and financing sources remain live policy questions), nor is it inherently cheaper than all existing schemes; that depends entirely on the transfer amount and beneficiary base chosen."})

upsc.append({"q":"Assertion (A): Employment generation is considered among the most effective tools for poverty alleviation in India.\nReason (R): Since the commencement of economic reforms, India's policy orientation has shifted focus from wage employment towards self-employment, aiming to create 'gainful employment' that alleviates poverty on a more permanent basis.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — the post-reform shift in emphasis from wage employment to self-employment reflects a deliberate policy strategy to generate durable, 'gainful' employment as the primary lever for permanently alleviating poverty, rather than relying on temporary wage-employment schemes alone."})

upsc.append({"q":"Which one of the following correctly identifies a persistent challenge in accurately measuring unemployment and underemployment in the Indian labour market, as highlighted in recent Economic Surveys?","o":["The rise of casual and contract labour arrangements makes conventional employment categories a poor proxy for job security, wage stability, and social security coverage","India's labour force surveys are conducted on a real-time daily basis, eliminating any measurement lag","Unemployment measurement in India ignores gender entirely, reporting only a single combined rate","There is no multiplicity of labour laws in India, making employment data collection straightforward"],"a":0,"e":"A genuine challenge flagged is that the rising share of casual and contract labour makes conventional 'employed'/'unemployed' categorisations inadequate proxies for actual job quality — surveys are NOT conducted daily (the EUS is an annual survey), unemployment data IS disaggregated by gender, and the multiplicity of labour laws is itself cited as an impediment to both compliance and clean data collection."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_poverty_unemployment_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
