import json

basic, intermediate, advanced, upsc = [], [], [], []

# ==================================================================
# NEW CHAPTER: GROWTH, DEVELOPMENT AND HAPPINESS (Ramesh Singh Ch.2)
# Avoiding overlap with eco_basic_concepts (growth vs development basics)
# and eco_human_development (HDI/GDI/GII/MPI/SDG mechanics)
# ==================================================================

# ---------------- BASIC ----------------

basic.append({"q":"In economics, the term 'progress' is generally understood as:","o":["A general term denoting betterment or improvement, without the specific technical meaning attached to 'growth' or 'development'","A strictly quantitative measure identical to GDP growth rate","A term used only to describe environmental improvement","A term coined exclusively by the UNDP in 1990"],"a":0,"e":"'Progress' remained a general, non-technical term denoting overall betterment; it was only during the 1960s-80s that 'growth' and 'development' acquired their distinct, technical meanings in economics."})

basic.append({"q":"Which Pakistani economist is credited with first clearly articulating the difference between economic growth and economic development, by the early 1970s?","o":["Mahbub ul Haq","Amartya Sen","Dudley Seers","Arthur Lewis"],"a":0,"e":"Mahbub ul Haq, a leading Pakistani economist, articulated the growth-development distinction by the early 1970s, and later led the team that created the Human Development Index for the UNDP in 1990."})

basic.append({"q":"Gross National Happiness (GNH) as a national development goal was first officially adopted by which country?","o":["Bhutan","Nepal","Sri Lanka","Thailand"],"a":0,"e":"Bhutan has officially followed Gross National Happiness since 1972, when its King declared happiness (rather than wealth/GDP) as the nation's guiding development goal."})

basic.append({"q":"Which international body publishes the annual World Happiness Report (WHR)?","o":["The Sustainable Development Solutions Network (SDSN), a UN body","The World Bank","The International Labour Organization","UNESCO"],"a":0,"e":"The World Happiness Report is published by the Sustainable Development Solutions Network, a UN body, and is edited by a small group of economists including John Helliwell, Richard Layard and Jeffrey Sachs."})

basic.append({"q":"The 'Easterlin Paradox' in the economics of happiness refers to the finding that:","o":["Happiness at a national level does not necessarily rise with wealth once basic needs are fulfilled","Poorer nations are always happier than richer nations","Happiness rises in direct proportion to a nation's GNP per capita","GDP growth automatically translates into higher life satisfaction"],"a":0,"e":"Richard Easterlin's 1974 finding — the Easterlin Paradox — showed that although richer individuals within a society tend to be happier than poorer ones at a point in time, the society as a whole does not necessarily become happier as its average income rises over time."})

basic.append({"q":"The UN General Assembly resolution inviting member countries to measure the happiness of their people and use it to guide public policy was passed in which year?","o":["2011","1990","2000","2015"],"a":0,"e":"In July 2011, the UN General Assembly passed a resolution titled 'Happiness: Towards a Holistic Approach to Development', inviting member states to measure happiness and use it to guide public policy."})

basic.append({"q":"The first UN high-level meeting on happiness and well-being (April 2012) was chaired by the Prime Minister of which country?","o":["Bhutan","Norway","Denmark","Finland"],"a":0,"e":"The first UN high-level meeting on happiness and well-being in April 2012 was chaired by the Prime Minister of Bhutan, the country that pioneered the Gross National Happiness concept."})

basic.append({"q":"Which of the following is NOT one of the six parameters used by the World Happiness Report to rank countries?","o":["Literacy rate","GDP per capita (at PPP)","Healthy life expectancy at birth","Freedom to make life choices"],"a":0,"e":"The WHR's six parameters are GDP per capita (PPP), social support, healthy life expectancy, freedom to make life choices, generosity, and perception of corruption — literacy rate is not among them."})

basic.append({"q":"As per the World Happiness Report 2018, which country was ranked as the happiest in the world?","o":["Finland","Norway","Denmark","Switzerland"],"a":0,"e":"Finland topped the World Happiness Report 2018 rankings, moving up from 5th position the previous year."})

basic.append({"q":"The term 'Anthropocene', used in discussions on sustainable development and happiness, refers to:","o":["A new geological epoch in which humanity has become the major driver of change to Earth's physical systems","A historical era before the Industrial Revolution","An economic theory about human rationality","A term describing purely urban, city-based development"],"a":0,"e":"'Anthropocene' combines the Greek roots for 'human' and 'new' (as in a new epoch), denoting the geological period in which human activity has become the dominant influence on Earth's climate, carbon cycle, water cycle and biodiversity."})

basic.append({"q":"The World Bank's World Development Report 2015, which focused on human behaviour and development policy, was subtitled:","o":["Mind, Society, and Behaviour","Development and Freedom","Entering the 21st Century","Cultural Liberty in Today's Diverse World"],"a":0,"e":"The World Development Report 2015 was titled 'Mind, Society, and Behaviour', focusing on how insights from behavioural economics and psychology can improve development policy design."})

basic.append({"q":"Bhutan's Gross National Happiness (GNH) framework rests on which of the following four pillars?","o":["Higher real per capita income, good governance, environmental protection, and cultural promotion","GDP growth, industrialisation, urbanisation, and trade liberalisation","Literacy, healthcare, sanitation, and gender equality","Defence spending, foreign policy, taxation, and monetary stability"],"a":0,"e":"Bhutan's GNH framework since 1972 rests on four pillars: higher real per capita income, good governance, environmental protection, and cultural promotion (inculcating ethical and spiritual values)."})

basic.append({"q":"Which economist's 1974 article, 'Does Economic Growth Improve the Human Lot? Some Empirical Evidence', gave rise to the concept now known as the Easterlin Paradox?","o":["Richard Easterlin","Amartya Sen","Joseph Stiglitz","Paul Krugman"],"a":0,"e":"Richard Easterlin's 1974 article is the origin of the paradox that bears his name, concerning the relationship between national income growth and happiness."})

basic.append({"q":"A 'welfare state' concept, and the branch of 'welfare economics', gained prominence in the aftermath of which major historical economic event?","o":["The Great Depression (1929)","World War I (1914-18)","The 1991 Indian economic reforms","The 2008 global financial crisis"],"a":0,"e":"The Great Depression broke the presumed automatic circular relationship between growth and development, leading to the concept of the welfare state and the emergence of welfare economics as a distinct branch."})

basic.append({"q":"Which of the following pairs correctly matches an economist with their idea on the meaning of development?","o":["Arthur Lewis — development as an increase in the range of human choice (freedom from servitude)","Dudley Seers — development measured purely by GDP per capita growth","W. Arthur Lewis — development as gross national happiness","Amartya Sen — development as industrialisation alone"],"a":0,"e":"Arthur Lewis (1963) saw the advantage of economic growth not in increased happiness directly, but in the expanded range of human choice it offers — a freedom-oriented view of development, distinct from Dudley Seers' employment/equality/poverty-based definition."})

basic.append({"q":"According to the World Happiness Report 2018, which country was ranked as the least happy in the world?","o":["Burundi","South Sudan","Central African Republic","Yemen"],"a":0,"e":"Burundi was ranked 156th (last) in the WHR 2018, just behind the Central African Republic and South Sudan."})

# ---------------- INTERMEDIATE ----------------

intermediate.append({"q":"Consider the following statements regarding the historical evolution of the idea of 'development':\n1. Dudley Seers defined development in terms of more employment, greater equality and falling poverty.\n2. The ILO's 1976 'Employment, Growth and Basic Needs' report introduced the concept of 'sustenance' as an element of development.\n3. The UNDP's 1994 Human Development Report explicitly excluded 'capabilities' from its idea of development.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false — the UNDP's 1994 HDR explicitly included the element of 'capabilities' in its conception of development, aligning it more closely with Amartya Sen's approach."})

intermediate.append({"q":"Consider the following statements about the World Happiness Report's measurement approach:\n1. Happiness is measured in at least two distinct ways — as an emotion, and as an evaluation of life as a whole.\n2. Respondents to WHR surveys have been found to systematically confuse these two senses of happiness, making the data unreliable.\n3. 'Affective happiness' refers to day-to-day emotional experiences, while 'evaluative happiness' concerns overall life satisfaction.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 3 are correct; statement 2 is false — the WHR explicitly found that respondents do NOT tend to confuse these two senses of happiness, and their responses to the two types of questions are highly distinct and meaningful."})

intermediate.append({"q":"Which of the following is one of the four reasons the World Happiness Report 2012 cites for the Easterlin Paradox (why average happiness does not rise even as a society gets richer)?","o":["Individuals compare their income/status to others, so when everyone's income rises together, relative social standing — and hence relative happiness — remains unchanged","Rising income always proportionally raises happiness with no diminishing returns","Government redistribution has no bearing on the paradox","The paradox applies only to developing countries, not to developed ones like the USA"],"a":0,"e":"One of the four cited reasons is the relative/positional nature of income comparison — since people compare themselves to others, an economy-wide rise in income does not change anyone's relative position, so aggregate happiness doesn't rise proportionally."})

intermediate.append({"q":"Consider the following statements about the World Development Report 2015 (Mind, Society, and Behaviour):\n1. It found that open defecation dropped when a Community-Led Total Sanitation programme was combined with subsidies and information on disease transmission.\n2. It found that changing microfinance repayment meeting frequency from weekly to monthly reduced loan defaults threefold.\n3. It found that revealing caste identity before a puzzle-solving test created a significant achievement gap disadvantaging backward-class boys in mixed-caste groups.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 3 are correct. Statement 2 reverses the actual finding — defaults reduced THREEFOLD when meeting frequency was changed from MONTHLY to WEEKLY (not the reverse), showing that more frequent social interaction reduced default risk."})

intermediate.append({"q":"Which of the following best explains the key conceptual difference between Bhutan's Gross National Happiness (GNH) and the UNDP's Human Development Index (HDI), as highlighted in development economics literature?","o":["GNH explicitly incorporates ethical/spiritual cultural values and good governance as core pillars, dimensions the HDI does not directly capture, while both share an emphasis on real per capita income","HDI incorporates spiritual and cultural values while GNH focuses only on income","GNH and HDI are mathematically identical indices differing only in name","GNH excludes any consideration of income, focusing purely on subjective emotional wellbeing"],"a":0,"e":"Both GNH and HDI value real per capita income, but GNH additionally and explicitly builds in cultural/spiritual promotion and good governance as core pillars — dimensions the HDI (built on health, education and income) does not directly incorporate."})

intermediate.append({"q":"Consider the following statements on 'social norms, culture and development' as discussed in recent Economic Survey literature:\n1. Societies with high levels of trust and honesty tend to perform better economically because enforcement of everyday contracts does not always require formal legal recourse.\n2. The 'broken windows theory' suggests that controlling low-level anti-social behaviour and improving the physical environment can deter more serious crime and corruption.\n3. Behavioural economics research has concluded that social norms and habits are permanently fixed and cannot change over time.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false — the literature explicitly finds that social norms and habits CAN change over relatively short periods, meaning countries can nurture more economically vibrant social norms over time."})

intermediate.append({"q":"Which of the following correctly describes the three possible combinations of growth and development discussed in development economics, illustrated historically by the Gulf countries?","o":["The Gulf countries were the first documented case of 'higher growth but lower development', prompting the emergence of 'development economics' as a distinct field","The Gulf countries exemplified 'lower growth but higher development'","The Gulf economies always showed a perfect one-to-one correspondence between growth and development","The Gulf states' experience proved that development is impossible without foreign aid"],"a":0,"e":"The Gulf countries were the first instance economists observed of high income/growth levels not being matched by comparable levels of development (health, education, etc.), which contributed to the emergence of development economics as a distinct branch."})

intermediate.append({"q":"Consider the following statements about the World Happiness Report's account of the United States' happiness trends:\n1. US life satisfaction has remained nearly constant for half a century despite GNP per capita roughly tripling since 1960.\n2. The WHR 2018 attributes America's declining happiness ranking partly to obesity, opioid-related substance abuse, and depression.\n3. Rising income inequality and declining social trust are cited as contributing factors to stagnant US happiness levels.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements accurately reflect the WHR's analysis — the US shows the Easterlin Paradox in action, with a dedicated WHR 2018 chapter on obesity/opioids/depression, plus contributing factors of inequality and declining trust noted in the WHR 2012 discussion."})

intermediate.append({"q":"With reference to India's ranking in the World Happiness Report 2018, which of the following is correct?","o":["India was ranked 133rd, below most other SAARC nations except war-affected Afghanistan","India was ranked 133rd, above all other SAARC nations including Bhutan and Nepal","India improved its rank compared to the WHR 2017","India was ranked in the top 50 countries globally"],"a":0,"e":"India was ranked 133rd in WHR 2018 (down 11 ranks from 122nd in 2017), placing it below all SAARC nations covered — Pakistan, Nepal, Bhutan, Bangladesh, Sri Lanka — except war-ravaged Afghanistan."})

intermediate.append({"q":"Which of the following statements about the philosophical evolution of 'development' thinking, as traced through various institutions and scholars, is correct?","o":["The ILO's 1976 report linked development to the elimination of absolute poverty, more employment and lessening income inequalities, going beyond mere income growth","The World Bank has never revised its understanding of development since the 1950s","Only Amartya Sen among economists linked development to human freedom and capabilities","The IMF's 1950s definition of development, based on 5-7% growth rates, remains the standard definition used today"],"a":0,"e":"The ILO's 1976 'Employment, Growth and Basic Needs' report explicitly tied development to eliminating absolute poverty, boosting employment and reducing inequality — part of a broader post-1960s shift away from the narrow 1940s-50s view of development as simply a 5-7% growth rate (a view later revised by the World Bank itself, e.g. in its 1991 report)."})

intermediate.append({"q":"Consider the following statements regarding the 'diminishing marginal utility of income' argument used to explain limits on happiness from rising GNP:\n1. A poor household needs a proportionally smaller increase in income than a rich household to raise its life satisfaction by the same amount.\n2. This principle provides an economic rationale for progressive tax-and-transfer systems in high-income OECD countries.\n3. OECD data shows that cash transfers and income taxes reduce inequality by roughly one-third on average.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1, 2 and 3","1 and 2 only","1 and 3 only"],"a":0,"e":"Statements 2 and 3 are correct; statement 1 is reversed — because of diminishing marginal utility, a RICH household needs a proportionally LARGER (not smaller) increase in income than a poor household to gain the same unit of life satisfaction/happiness."})

intermediate.append({"q":"Consider the following statements regarding the two-fold difficulty economists faced in developing a formula to measure 'development':\n1. There was difficulty in reaching consensus on which factors (income, healthcare, literacy, environment, etc.) actually constitute development.\n2. There was difficulty in quantifying development, since it has both quantitative and qualitative dimensions.\n3. Both difficulties were fully resolved before the first Human Development Report was published in 1990.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe the twin definitional and quantification challenges; statement 3 is incorrect, as the HDI (1990) represented one particular consensus-based attempt at resolution, not a universally settled resolution of the underlying debate, which continued afterward (e.g., the 1999 LSE satire)."})

intermediate.append({"q":"Which of the following is cited as evidence, in the 'social norms, culture and development' literature, for the innate and malleable nature of pro-social human behaviour?","o":["Research in psychology and evolutionary biology suggesting morality and other-regarding values are innate, while the social setting a person lives in can still nurture or stunt these traits","Research concluding that pro-social behaviour is entirely genetically fixed and cannot be influenced by social context","A finding that trustworthiness has no correlation with a society's economic performance","Research suggesting only formal legal systems, not social norms, can ever ensure contract compliance"],"a":0,"e":"The literature cites research finding morality/altruism to be innate to the human mind, while explicitly allowing that social context nurtures or stunts these traits — supporting the idea that policy and social example can shift social norms over time, not that they are immutable."})

intermediate.append({"q":"The Human Development Report titled 'Cultural Liberty in Today's Diverse World' was published in which year, reflecting post-9/11 introspection about multicultural coexistence and development?","o":["2004","1994","2011","1990"],"a":0,"e":"The HDR 2004 was titled 'Cultural Liberty in Today's Diverse World', reflecting the post-9/11 global introspection on whether multicultural co-existence was compatible with the dominant development paradigm."})

# ---------------- ADVANCED ----------------

advanced.append({"q":"Which one of the following best captures the World Happiness Report's explanation for why Latin American countries score relatively high on happiness despite high crime, corruption and inequality?","o":["The abundance of family warmth and supportive social relationships compensates, in the WHR's assessment, for weaknesses typically emphasised in conventional income-based development measures","Latin American nations have among the highest GDP per capita in the world","The WHR methodology excludes crime and corruption data for Latin American countries","Latin America's happiness scores are driven primarily by strong social trust in government institutions"],"a":0,"e":"The WHR specifically attributes Latin America's relatively high happiness scores to strong family and social support networks, factors that are often side-lined in income-focused development discourse but are heavily weighted in life-satisfaction surveys."})

advanced.append({"q":"Which of the following statements about the 'happiness of immigrants', as studied for the first time in the World Happiness Report 2018, is correct?","o":["Immigrant happiness levels closely track those of their host country, with only a modest drag from legacy factors of 10-25%","Immigrants' happiness depends entirely on their country of origin, regardless of host country conditions","The report found that migration from the Chinese countryside to cities had substantially raised the happiness of those who moved","Immigrant happiness was found to be unrelated to any host-country characteristics"],"a":0,"e":"WHR 2018 found immigrant happiness levels converge toward host-country levels, with only a 10-25% drag attributable to legacy factors — and specifically noted that China's massive rural-to-urban migration had NOT advanced happiness at all, contrary to the third option."})

advanced.append({"q":"Which one of the following best explains why, according to the World Happiness Report 2012's analysis, rich countries face inherent limits in raising happiness purely through further GNP growth?","o":["Once basic material deprivations are overcome, additional income yields diminishing marginal gains in life satisfaction, while affluence itself generates new afflictions such as obesity, addiction, and loss of social trust","GNP growth in rich countries mechanically and proportionally raises happiness with no limiting factors","Rich countries have no measurable happiness data, making the comparison impossible","Poor countries experience the same diminishing returns to income as rich countries, so there is no meaningful difference between them"],"a":0,"e":"The WHR's analysis holds that once basic needs are met, further income has diminishing marginal utility for happiness, and affluence brings its own set of afflictions (obesity, addictions, declining social trust) — a dynamic distinct from poorer societies where rising income still meaningfully raises life satisfaction."})

advanced.append({"q":"Which one of the following statements correctly reflects the World Happiness Report's critique of the standard economic model of 'rational' individual decision-making, as it pertains to happiness policy?","o":["It argues that human decisions are shaped by a complex interplay of emotion, unconscious priming, and social context, at odds with a purely rational, self-interested consumer model, with implications for how advertising and addiction operate","It endorses the traditional model of humans as fully rational, self-interested decision-makers without qualification","It concludes that behavioural economics has no relevance to happiness or development policy","It argues that advertising has no measurable economic scale or influence on consumer wants"],"a":0,"e":"The WHR explicitly challenges the purely rational-actor model, citing emotional/unconscious decision-making, priming effects, and the roughly $500 billion global advertising industry's role in manufacturing wants — directly relevant to understanding why rising income doesn't straightforwardly raise happiness."})

advanced.append({"q":"Which one of the following statements about the London School of Economics' 1999 satirical alternative development index (cited as an illustration of HDI's limitations) is correct?","o":["It concluded that Bangladesh ranked as the most developed country in the world, with the USA, Norway and Sweden ranking lowest — intended to expose the incompleteness rather than replace the HDI","It was formally adopted by the UNDP as a supplementary index to the HDI","It ranked the USA as the most developed country by a wide margin","It was based on exactly the same three dimensions used by the HDI (health, education, income)"],"a":0,"e":"This 1999 LSE exercise was a deliberate intellectual satire highlighting how arbitrary indicator choices (unrelated to conventional development measures) could invert rankings entirely — its purpose was to expose the HDI's conceptual limitations, not to replace it or gain UNDP adoption."})

advanced.append({"q":"Which one of the following best explains the significance of Finland's position in the World Happiness Report 2018, in relation to its education system?","o":["Finland's top international performance in student outcomes has been linked to fostering community and equality in schools, contrasting with education reform strategies emphasising testing and performance-linked teacher pay","Finland ranked poorly in the report despite having the world's best-performing schools","Finland's happiness ranking has no connection to its education policy according to the report","The report attributes Finland's happiness purely to its natural resource wealth"],"a":0,"e":"The WHR specifically cites analysis of Finland's schools achieving top international performance through fostering community and equality — a contrast to reform strategies (like the US's) built around testing, measurement and performance-linked teacher pay."})

advanced.append({"q":"Which one of the following statements correctly captures the 'introspecting development' critique that emerged after the 1990s, as discussed in the context of the developed world's HDI rankings?","o":["Despite topping HDI rankings, developed nations exhibited widespread crime, corruption, addiction and moral/social afflictions, suggesting material development alone does not guarantee happiness or well-being","The critique concluded that HDI rankings perfectly correlate with subjective happiness across all developed nations","The critique argued that developing nations, not developed ones, primarily suffer from social afflictions linked to development","The critique was fully resolved by the 2010 revision of HDI's education indicators"],"a":0,"e":"Scholars observed that despite high HDI rankings, developed nations showed significant social ills (crime, corruption, addiction, moral degradation), suggesting 'development' as conventionally measured (income, education, health) failed to deliver genuine happiness — prompting a broader introspective critique, not resolved simply by later HDI methodology tweaks."})

advanced.append({"q":"Which one of the following correctly describes the two distinct empirical measurement traditions the World Happiness Report 2013 sought to reconcile?","o":["The 'human development' (capability/conceptual) approach associated with the UNDP, and the 'life evaluation' (empirical, survey-based) approach associated with happiness economics, viewed as complementary lenses","Only GDP-based measurement and no alternative empirical tradition","The Multidimensional Poverty Index approach and the Gender Inequality Index approach","Purely subjective emotional measurement, entirely excluding any life-evaluation survey methodology"],"a":0,"e":"WHR 2013 explicitly reconciled the UNDP's conceptual 'human development'/capability approach with the empirical 'life evaluation' survey-based approach to happiness, presenting them as complementary rather than competing lenses on human progress."})

advanced.append({"q":"Which one of the following statements about the philosophical 'middle path' invoked in happiness economics literature, attributed jointly to Aristotle and the Buddha, is correct?","o":["Both counselled a path between asceticism on one side and excessive craving for material goods on the other, since psychological research finds those who place a high premium on income tend to be less happy and more vulnerable to psychological ills","Aristotle and the Buddha are cited as having advocated unlimited pursuit of material wealth as the surest path to happiness","The 'middle path' reference concerns only Buddhist economic thought and has no connection to Aristotelian philosophy","This teaching is used in the literature to argue that asceticism alone (without any material comfort) maximises happiness"],"a":0,"e":"The text explicitly invokes both Aristotle and the Buddha jointly for the 'middle path' between craving material goods and pure asceticism, tying this ancient wisdom to modern psychological findings that a high premium on income correlates with lower happiness and greater vulnerability to psychological ills."})

advanced.append({"q":"Which one of the following best illustrates the numerical logic of 'diminishing marginal utility of income' as applied to happiness, per the World Happiness Report's own illustrative example?","o":["A poor household at Rs. 1,000 income needs only an extra Rs. 100 to raise life satisfaction by one notch, while a household at Rs. 1,000,000 (a thousand times richer) needs a proportionally equivalent Rs. 100,000 increase for the same one-notch gain","Both poor and rich households require exactly the same absolute rupee increase to gain one notch of life satisfaction","The rich household requires a smaller proportional increase in income than the poor household to gain the same happiness benefit","This illustrative logic has been empirically disproven and is no longer used in happiness economics"],"a":0,"e":"The WHR's own numerical illustration shows that gains in income must be of EQUAL PROPORTION to a household's existing income to deliver the same unit of life satisfaction — meaning the rich household needs a proportionally equivalent (not smaller, and not identical in absolute terms) increase to match the poor household's happiness gain."})

advanced.append({"q":"Which one of the following statements about the economics of advertising, as discussed in the context of happiness and consumption behaviour, is correct?","o":["Advertising, estimated at around US$500 billion per year globally, is characterised as working partly by creating new material wants and preying on psychological weaknesses rather than merely informing consumers of existing needs","Advertising expenditure worldwide is estimated at under US$5 billion annually, a negligible figure in the global economy","The literature concludes advertising has no effect on consumer psychology or unconscious decision-making","Advertising is described as exclusively serving a neutral, purely informational economic function"],"a":0,"e":"The text specifically describes global advertising (~US$500 billion/year) as designed to overcome satiety by manufacturing new wants, exploiting psychological weaknesses and unconscious urges — not merely providing neutral product information, and far larger in scale than the alternative figure given."})

# ---------------- UPSC TIER ----------------

upsc.append({"q":"Which one of the following statements regarding the conceptual distinction between 'growth' and 'development' in economics, as it evolved historically, is correct?","o":["Economists failed to consciously distinguish growth from development until the 1960s, even though a difference existed, because growth was long assumed to automatically translate into improved quality of life","Growth and development have always been treated as synonymous terms in mainstream economics with no conceptual distinction ever emerging","Development was defined before growth in the historical evolution of economic thought","The distinction between growth and development was first formalised by the World Bank in 1999, not by academic economists earlier"],"a":0,"e":"Early economists (till the 1950s) assumed growth would automatically deliver improved quality of life, so the growth-development distinction was not consciously articulated until later economists (like Mahbub ul Haq, early 1970s) observed cases of high growth without corresponding development."})

upsc.append({"q":"Which one of the following statements about Bhutan's Gross National Happiness (GNH) and its relationship to global institutions is correct?","o":["The UN adopted Bhutan's call for a holistic approach to development in 2011, a move endorsed by 68 countries, without rejecting UNDP's human development framework","Bhutan rejected UNDP's human development framework entirely upon adopting GNH in 1972","The GNH framework was adopted by the UN as a binding replacement for GDP-based national accounting for all member states","GNH was created in response to, and subsequent to, the World Happiness Report's first publication in 2012"],"a":0,"e":"Bhutan's GNH predates the WHR by four decades (since 1972) and, per the text, does not reject the UNDP's human development idea — Bhutan officially follows GNH targets while UN member states endorsed a holistic development approach in 2011 without any binding GDP replacement mandate."})

upsc.append({"q":"Consider the following statements regarding the World Happiness Report's account of the 'Easterlin Paradox':\n1. At any given point in time within a society, richer individuals tend to report higher happiness than poorer individuals.\n2. Over time, as a society's average income rises, its average happiness level does not proportionally rise.\n3. One reason for the paradox is that income gains since 1960 in the United States have been evenly distributed across income groups.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe the Easterlin Paradox; statement 3 is factually false and reverses the actual explanation — the WHR notes that US income gains have gone disproportionately to those at the top of the income and education distribution, not evenly across groups."})

upsc.append({"q":"Which one of the following best explains why the World Happiness Report emphasises 'social norms and culture' as economically significant, beyond fiscal, monetary and taxation policy?","o":["Trustworthy and honest societies reduce the need for costly third-party contract enforcement, lowering transaction costs and enabling markets (such as housing finance) to develop more robustly","Social norms have been empirically shown to have zero measurable impact on any economic outcome","Fiscal and monetary policy alone fully determine a nation's economic trajectory, irrespective of social trust","Behavioural economics research concludes that social norms cannot be altered by public policy in any timeframe"],"a":0,"e":"The literature (citing Economic Survey references) argues that high-trust, honest societies reduce reliance on costly legal enforcement of everyday contracts (e.g., mortgages), directly aiding market development — and explicitly notes norms CAN change over time via policy and social example, contrary to the other options."})

upsc.append({"q":"Which one of the following statements about the World Bank's World Development Report 2015 (Mind, Society, and Behaviour) and its India-specific findings is correct?","o":["Combining a Community-Led Total Sanitation programme with standard subsidies and information reduced open defecation by 11 percent in the studied villages","The report found no measurable impact of combining sanitation programmes with behavioural interventions in India","The report's caste-identity puzzle-solving study found no difference in performance regardless of whether caste was revealed","The report's key India findings related solely to monetary policy transmission, not social behaviour"],"a":0,"e":"The WDR 2015 documented an 11 percent reduction in open defecation in villages where CLTS was combined with subsidies and disease-transmission information — one of several India-specific behavioural economics findings cited (alongside the caste-identity and microfinance-meeting-frequency studies)."})

upsc.append({"q":"Which one of the following statements about the 'diminishing marginal utility of income' rationale, as applied to tax-and-transfer policy in OECD countries, is correct?","o":["On average across OECD countries, cash transfers and income taxes reduce inequality by about one-third, and reduce poverty by roughly 60 percent compared to a no-tax-and-benefit scenario","OECD data shows tax-and-transfer systems have no measurable effect on inequality or poverty levels","The diminishing marginal utility argument suggests progressive taxation reduces overall societal welfare","Cash transfers exclusively benefit high-income households under this framework"],"a":0,"e":"OECD data (2008) cited in the WHR literature shows tax-and-transfer systems reduce inequality by about one-third on average and reduce poverty by around 60 percent relative to a no-redistribution baseline — directly grounded in the diminishing-marginal-utility-of-income logic, not the reverse claims in the other options."})

upsc.append({"q":"Which one of the following statements correctly distinguishes the two senses in which 'happiness' is measured in the World Happiness Report framework?","o":["'Affective happiness' captures day-to-day emotional experience (e.g., 'were you happy yesterday?'), while 'evaluative happiness' captures an overall assessment of life satisfaction (e.g., 'are you happy with your life as a whole?')","Affective and evaluative happiness are identical concepts used interchangeably in WHR methodology","Evaluative happiness measures only short-term emotional states, while affective happiness measures lifetime satisfaction","The WHR relies exclusively on evaluative happiness and does not measure affective happiness at all"],"a":0,"e":"The WHR explicitly distinguishes 'affective happiness' (emotional, moment-to-moment) from 'evaluative happiness' (an overall judgement of one's life) — both are measured, using distinct survey questions, and respondents' answers to the two are shown to be meaningfully distinct rather than confused or interchangeable."})

upsc.append({"q":"Which one of the following statements about the historical genealogy of 'development' as a concept — from the 1940s to the 1990s — is correct?","o":["Development was initially equated by the IMF/WB with achieving a 5-7 percent growth rate (1940s-50s), later expanded by scholars like Dudley Seers and the ILO to include employment, equality and basic needs, and eventually incorporated 'capabilities' by the UNDP's 1994 Human Development Report","Development has been defined identically as a pure growth-rate target from the 1940s through to the present day, with no conceptual evolution","The ILO's basic needs approach preceded and directly caused the IMF's original growth-rate-based definition of development","Amartya Sen's capability approach was formally adopted by the IMF in the 1950s, predating the UNDP's Human Development Report by decades"],"a":0,"e":"The correct chronology moves from a narrow 1940s-50s growth-rate-based IMF/WB definition, through Dudley Seers' and the ILO's (1976) employment/equality/basic-needs framing, to the UNDP's 1994 HDR explicitly including 'capabilities' — not a static, unchanged, or reverse-chronology definition as the other options suggest."})

upsc.append({"q":"Which one of the following statements about the 'Anthropocene' and its implications, as discussed in the World Happiness Report 2012, is correct?","o":["It warns that continuing along the current economic trajectory risks undermining Earth's life-support systems, with deterioration already visible in the dry lands of the Horn of Africa and parts of Central Asia","It is described as a purely theoretical concept with no observed real-world consequences to date","It refers exclusively to changes in the global financial system, unrelated to environmental systems","It concludes that human population growth has had no measurable effect on Earth's physical systems"],"a":0,"e":"The WHR 2012 explicitly cites the Anthropocene concept alongside real, already-observed deterioration in life-support systems in specific fragile regions (Horn of Africa drylands, parts of Central Asia) — not a purely theoretical or finance-only concept, and explicitly linking it to humanity's demographic and technological impact on Earth's systems."})

upsc.append({"q":"Which one of the following statements correctly reflects India's World Happiness Report ranking trajectory around 2016-2018?","o":["India's rank fell from 2016 to 2017 (by four ranks) and fell further from 2017 (122nd) to 2018 (133rd, an 11-rank drop)","India's rank improved consistently every year from 2016 to 2018","India was not ranked at all in the WHR before 2018","India's 2018 rank of 133rd represented an improvement over its 2017 rank"],"a":0,"e":"India's WHR ranking trajectory shows consistent decline: it was already four ranks lower in 2017 than 2016, and then fell a further 11 ranks from 122nd (2017) to 133rd (2018) — not an improving or newly-introduced ranking."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

chapter = {
    "id": "eco_growth_dev_happiness",
    "title": "Growth, Development and Happiness",
    "desc": "Progress vs growth vs development, Bhutan's Gross National Happiness, World Happiness Report, Easterlin Paradox, and behavioural insights into development policy",
    "questions": {
        "basic": basic,
        "intermediate": intermediate,
        "advanced": advanced,
        "upsc": upsc,
    }
}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("Total questions:", len(all_q))
print("basic:", len(basic), "intermediate:", len(intermediate), "advanced:", len(advanced), "upsc:", len(upsc))
print("unique texts:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_growth_dev_happiness_chapter.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
