import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_services_it (Ramesh Singh Ch.10, Services Sector)
# Fresh territory confirmed via keyword scan: FIPB phase-out, SEIS, R&D/GII rank,
# Atal Innovation Mission, space services, WTO services negotiations (LDC waiver,
# e-commerce moratorium, RCEP), and domestic regulatory barriers (ULCRA, accountancy/
# legal services FDI restrictions) — none previously tested
# ==================================================================

upsc.append({"q":"Consider the following statements about the Foreign Investment Promotion Board (FIPB):\n1. It was the body responsible for approving proposals requiring government route FDI clearance in India.\n2. The Government announced its phase-out in the Union Budget 2017-18, following the success of e-filing and online FDI application processing.\n3. Its functions were subsequently transferred entirely to the Reserve Bank of India.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct — the FIPB approved government-route FDI proposals and was announced for phase-out in Budget 2017-18 after over 90% of FDI approvals had moved to e-filing. Statement 3 is incorrect; FIPB's functions were distributed among the concerned administrative ministries/departments, not transferred to the RBI."})

upsc.append({"q":"Which one of the following scheme names correctly matches the Government of India's initiative to boost incentives for exports of notified services, enhanced during the mid-term review of the Foreign Trade Policy 2015-2020?","o":["Services Exports from India Scheme (SEIS)","Merchandise Exports from India Scheme (MEIS)","Production Linked Incentive (PLI) Scheme","Interest Equalisation Scheme"],"a":0,"e":"SEIS (Services Exports from India Scheme) specifically incentivises notified services exports (e.g., hotel/restaurant, hospital, educational services); MEIS is its merchandise-goods counterpart, while PLI and the Interest Equalisation Scheme serve different, non-services-specific purposes."})

upsc.append({"q":"Consider the following statements regarding India's services trade performance (as per Economic Survey 2017-18 data cited in the text):\n1. India was the 8th largest exporter of commercial services in the world in 2016, with a share roughly double its share of world merchandise exports.\n2. The ratio of India's services exports to merchandise exports rose from around 36 per cent in 2000-01 to over 58 per cent in 2016-17.\n3. India's net services surplus financed less than 10 per cent of its merchandise trade deficit in 2017-18 H1.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — the net services surplus actually financed about 49 per cent of India's merchandise deficit in 2017-18 H1, cushioning the current account deficit substantially, not marginally."})

upsc.append({"q":"The Atal Innovation Mission (AIM), a key government initiative to promote India's R&D and innovation ecosystem, has been established under which one of the following?","o":["NITI Aayog","Ministry of Science and Technology","Department for Promotion of Industry and Internal Trade","Council of Scientific and Industrial Research"],"a":0,"e":"The Atal Innovation Mission (AIM) has been established within NITI Aayog to promote innovation and entrepreneurship, distinct from the Ministry of Science & Technology, DPIIT, or CSIR, though it works in coordination with such bodies."})

upsc.append({"q":"Assertion (A): India's gross expenditure on Research and Development (R&D) as a share of GDP is comparatively low, at around 1 per cent.\nReason (R): Among the BRICS countries, India ranks ahead of all others, including South Africa, in R&D expenditure.\nWhich one of the following is correct?","o":["A is true, but R is false","Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is false, but R is true"],"a":0,"e":"A is true (India's R&D spend is around 1% of GDP), but R is false — the text notes that among BRICS countries, only South Africa ranks behind India in R&D expenditure, meaning India is second-LAST, not ahead of all others, in this specific ranking."})

upsc.append({"q":"Which one of the following statements about India's space services sector, per the Economic Survey 2017-18, is correct?","o":["Foreign exchange earnings from satellite mapping have declined in recent years, largely due to a free and open data policy adopted by many global space agencies","India's foreign exchange earnings from satellite mapping have risen consistently due to restrictive proprietary data policies worldwide","ISRO's marketing arm, Antrix, has ceased all satellite mapping and launching service operations","India's space programme contributes no significant foreign exchange earnings to the economy"],"a":0,"e":"The Economic Survey notes a decline in satellite-mapping forex earnings specifically because many global space agencies have adopted free and open data policies, reducing demand for paid mapping services — not due to ISRO/Antrix ceasing operations, and India's space sector remains a genuine forex earner via mapping and launch services."})

upsc.append({"q":"Consider the following outcomes attributed to WTO Ministerial Conferences on services trade, as discussed in the context of India's services sector:\n1. Implementation of preferential treatment in favour of services and service suppliers of Least Developed Countries (LDCs).\n2. A continued moratorium on imposing customs duties on electronic transmissions (e-commerce).\n3. India's 'Trade Facilitation in Services' (TFS) proposal, aimed partly at easing cross-border movement of skilled professionals and boosting medical tourism.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three are correct: the 10th WTO Ministerial Conference favoured LDC preferential treatment in services and maintained the e-commerce customs duty moratorium, while India separately proposed the Trade Facilitation in Services (TFS) framework covering professional mobility, social security portability, and medical tourism promotion, among other goals."})

upsc.append({"q":"Which one of the following is described as the 'only mega-regional Free Trade Agreement of which India is a part', involving the 10 ASEAN countries and six FTA partners including Australia, China, Japan, South Korea and New Zealand?","o":["Regional Comprehensive Economic Partnership (RCEP)","Trans-Pacific Partnership (TPP)","Comprehensive and Progressive Agreement for Trans-Pacific Partnership (CPTPP)","Trade Facilitation in Services (TFS)"],"a":0,"e":"RCEP (Regional Comprehensive Economic Partnership), combining the 10 ASEAN members with six FTA partner countries including India, is explicitly identified as India's only mega-regional FTA involvement, distinct from the US-led TPP/CPTPP (of which India is not a member)."})

upsc.append({"q":"Which one of the following statements about domestic regulatory barriers affecting India's construction and accountancy services sectors is correct?","o":["The Urban Land Ceiling and Regulation Act (ULCRA) continues to hamper construction development in some states that have not repealed it, while FDI is not permitted in accountancy services and foreign providers cannot conduct statutory audits","ULCRA has been fully repealed in all Indian states with no residual regulatory confusion, and FDI is fully permitted in accountancy services","Restrictions on floor area ratio (FAR) apply uniformly and without any state-to-state or project-to-project variation","Accountancy firms in India face no restriction on the number of partners or statutory audits handled per partner"],"a":0,"e":"ULCRA continues to hamper construction in some states (e.g., Andhra Pradesh, Assam, Bihar, West Bengal) that had not repealed it even after the 1999 Repeal Act was passed elsewhere; separately, FDI remains barred in accountancy services and foreign providers cannot conduct statutory audits — the other options misstate the facts (FAR restrictions do vary, and there IS a 20-partner/20-audit cap per partner in accountancy firms)."})

upsc.append({"q":"With reference to restrictions on legal services in India as a barrier to services trade liberalisation, which one of the following statements is correct?","o":["FDI is not permitted in legal services, and international law firms are not authorised to open offices, advertise, or have foreign nationals sign legal documents or represent clients in India","FDI is fully permitted in legal services, subject only to Bar Council registration","International law firms may freely open offices in India but cannot advertise their services","Indian advocates are permitted to enter into profit-sharing arrangements with foreign law firms"],"a":0,"e":"Legal services remain tightly closed: no FDI is permitted, foreign firms cannot open offices or advertise, foreign lawyers cannot sign legal documents or represent clients, and Indian advocates cannot enter profit-sharing arrangements with non-Indian-advocate entities — the Bar Council has consistently opposed foreign law firm entry."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_services_it_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
