import json

basic, intermediate, advanced, upsc = [], [], [], []

# ==================================================================
# NEW CHAPTER: EVOLUTION OF THE INDIAN ECONOMY (Ramesh Singh Ch.3)
# Avoiding overlap with eco_planning_niti (Plan-by-Plan history),
# eco_disinvestment_psu (disinvestment mechanics) and eco_reforms_1991 (LPG mechanics)
# ==================================================================

# ---------------- BASIC ----------------

basic.append({"q":"The term 'drain of wealth' refers to:","o":["The unilateral, one-way transfer of investible capital from colonial India to Britain","A programme of British investment into Indian infrastructure","A post-independence tax evasion scheme","A term describing capital flight after the 1991 reforms"],"a":0,"e":"The 'drain of wealth' describes the colonial-era unilateral transfer of India's investible capital and resources to Britain, a central feature of India's colonial economic exploitation."})

basic.append({"q":"As per economic historian Angus Maddison's estimates, India's per capita income growth rate between 1870 and 1947 was approximately:","o":["0.2 per cent per annum","1 per cent per annum, similar to the UK","5 per cent per annum","Negative throughout the period"],"a":0,"e":"Maddison estimated India's per capita growth at a meagre 0.2 per cent per annum from 1870-1947, compared to about 1 per cent in the UK over the same period — reflecting the stagnation of the colonial economy."})

basic.append({"q":"India's literacy rate and life expectancy at birth at the time of Independence (1947) were approximately:","o":["17 per cent literacy and 32.5 years life expectancy","50 per cent literacy and 50 years life expectancy","30 per cent literacy and 45 years life expectancy","70 per cent literacy and 60 years life expectancy"],"a":0,"e":"At Independence, India's literacy stood at just 17 per cent with a life expectancy of only 32.5 years — stark indicators of the social sector neglect under colonial rule."})

basic.append({"q":"Which committee, constituted in 1938 by nationalist leaders, first felt the need for economic planning in India, even before Independence?","o":["The National Planning Committee","The Planning Commission","The Finance Commission","The Bombay Plan Committee"],"a":0,"e":"The National Planning Committee, constituted in 1938 under nationalist leadership, reflected the pre-independence recognition of the need for economic planning in India."})

basic.append({"q":"Which of the following was NOT among the consensual pre-Independence views held by India's political leaders and industrialists regarding the future economy?","o":["Encouragement of unrestricted foreign investment","State/government should have a direct responsibility for development","An ambitious role for the public sector","The need for economic planning"],"a":0,"e":"Pre-independence consensus among Indian leaders actually favoured DISCOURAGING foreign investment, not encouraging it unrestricted — alongside state responsibility for development, an ambitious public sector role, heavy industry development, and economic planning."})

basic.append({"q":"India's political leadership chose which sector as the 'prime moving force' of the economy after Independence?","o":["Industry","Agriculture","Services","Foreign trade"],"a":0,"e":"Despite India's resource base arguably favouring agriculture, the political leadership chose industry as the economy's prime moving force after Independence — a decision effectively made in the 1930s."})

basic.append({"q":"In which Five-Year Plan period did the Government of India officially recognise agriculture as the prime moving force of the economy, replacing industry?","o":["The Tenth Plan (2002-07)","The First Plan (1951-56)","The Fifth Plan (1974-78)","The Eighth Plan (1992-97)"],"a":0,"e":"The Planning Commission announced the shift to agriculture as the prime moving force with the commencement of the Tenth Five Year Plan (2002-07), decades after the world's perception of agriculture had already begun changing in the mid-1990s."})

basic.append({"q":"Which country is cited as an example of a nation that took a 'realistic evaluation' of its resources and declared agriculture (not industry) as its prime moving force after its own revolution?","o":["The People's Republic of China (1949)","The Soviet Union (1917)","Japan (1868)","South Korea (1953)"],"a":0,"e":"China, after 1949, declared agriculture as its prime moving force, using agricultural surplus to build pre-requisites for industrialisation, which it pursued vigorously from the 1970s onward."})

basic.append({"q":"India's economic system after Independence was officially declared to be a:","o":["Planned and mixed economy","Pure command economy","Pure capitalist/free-market economy","Barter economy"],"a":0,"e":"Independent India was declared a planned and mixed economy, combining state planning with a role for both public and private sectors — distinct from a pure command or pure market economy."})

basic.append({"q":"Which international economic body's 1993 study, 'The East Asian Miracle', revisited and validated the state-market balance philosophy that India's First Five Year Plan had articulated back in 1951?","o":["The World Bank","The International Monetary Fund","The World Trade Organization","The Asian Development Bank"],"a":0,"e":"The World Bank's 1993 study 'The East Asian Miracle' drew conclusions about balanced state-market roles that were strikingly similar to what India's First Five Year Plan (1951) had already articulated decades earlier."})

basic.append({"q":"Jawaharlal Nehru famously referred to Public Sector Undertakings (PSUs) as the:","o":["'Temples of modern India'","'Engines of the mixed economy'","'Pillars of socialism'","'Fifth wheel of the coach'"],"a":0,"e":"Nehru described PSUs as the 'temples of modern India', reflecting the near-reverential importance attached to public sector industrialisation in independent India's early economic vision."})

basic.append({"q":"Which of the following was NOT one of the major reasons cited for the government's ambitious expansion of Public Sector Undertakings (PSUs) after Independence?","o":["Immediate need to maximise short-term stock market returns for private shareholders","Meeting infrastructural needs (power, transport, communication) that the private sector could not manage","Meeting industrial/core-sector needs requiring heavy capital and technology","Employment generation and the 'trickle-down' effect"],"a":0,"e":"PSUs were never conceived as vehicles to maximise private shareholder stock returns — the actual reasons were infrastructural needs, core industrial needs, employment generation/trickle-down effect, generating profits for social sector development, and enabling the later rise of the private sector."})

basic.append({"q":"The Second World War's demonstration of the importance of industrial-military capability is cited as one reason India chose industry (rather than agriculture) as its prime moving force, primarily because:","o":["A country needs an industrial base to build a credible defence capability","The war destroyed India's agricultural infrastructure entirely","Industrial nations were exempted from war reparations","Agriculture was banned by post-war international treaties"],"a":0,"e":"The Second World War demonstrated that industrial capability underpins defence capability — a consideration that influenced India's leadership toward industrialisation as a means of building a credible deterrent, alongside faster growth and agricultural modernisation."})

basic.append({"q":"According to Amartya Sen and Jean Dreze's analysis (cited in the context of India's agriculture-industry debate), India was historically a classic example of which economic phenomenon?","o":["'Market failure', where low rural purchasing power stunted demand for industrial goods","'Dutch disease', where resource exports crowded out manufacturing","'Liquidity trap', where interest rate cuts failed to boost investment","'Balance of payments crisis'"],"a":0,"e":"Sen and Dreze argued India exemplified 'market failure' — industrial goods existed and were needed, but the agriculture-dependent masses lacked the purchasing power to translate need into effective market demand, stunting industrial growth."})

basic.append({"q":"To the original six 'core' or 'basic' industries used in India's Index of Industrial Production (IIP), which two industries were added in 2013?","o":["Natural Gas and Fertilisers","Textiles and Automobiles","Pharmaceuticals and IT services","Renewable Energy and Telecom"],"a":0,"e":"Natural Gas and Fertilisers were added to the original six core industries (Refinery products, Electricity, Steel, Coal, Crude Oil, Cement) in 2013, expanding the core/basic industries group to eight."})

basic.append({"q":"Under British colonial rule, which of the following Indian industrial sectors was particularly dominated by British firms?","o":["Shipping, banking, insurance, coal, plantation crops and jute","Handloom textiles and village crafts exclusively","Software and information technology","Renewable energy generation"],"a":0,"e":"British firms dominated key sectors like shipping, banking, insurance, coal, plantation crops (tea, indigo) and jute, while indigenous capitalists who did emerge remained heavily dependent on British commercial capital."})

# ---------------- INTERMEDIATE ----------------

intermediate.append({"q":"Consider the following statements regarding the economic character of colonial India:\n1. The colonial state's economic vision was to increase India's capacity to export primary products and import British manufactured goods.\n2. There is strong historical evidence of significant European technology transfer from Britain to India during colonial rule.\n3. Aggregate real output in India grew at less than 2 per cent per year during the first half of the 20th century.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 3 are correct; statement 2 is false — per Angus Maddison's research, there is NOT much evidence of significant European technology transfer to Asia (India/China) during this period, contrary to what might be assumed."})

intermediate.append({"q":"Consider the following statements about arguments for India choosing agriculture (rather than industry) as its prime moving force at Independence:\n1. India possessed abundant fertile, cultivable land suited for agriculture.\n2. Human capital for agriculture did not require extensive prior technical training, unlike industry.\n3. The dominant global ideology at the time (including the IMF/World Bank) actively encouraged newly independent nations to prioritise agriculture over industry.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false — the dominant global ideology at the time (including IMF/WB) actually favoured INDUSTRIALISATION as the path to faster growth, and treated an agriculture-first strategy as a 'symbol of backwardness' until the 1990s."})

intermediate.append({"q":"Which of the following correctly describes the position taken by India's First Five Year Plan (1951) document on the choice between full nationalisation and reliance on the private sector?","o":["It explicitly rejected complete nationalisation as neither necessary nor desirable at that stage, envisaging an economy guided by the state but operated partly through direct state action and partly through private initiative","It called for immediate and complete nationalisation of all means of production","It rejected any role whatsoever for public ownership or regulation","It proposed a purely free-market approach with minimal government involvement"],"a":0,"e":"The First Plan's draft outline (1951) explicitly held that complete nationalisation was 'neither necessary nor desirable at the present stage', envisaging a mixed approach — the state guiding and directing the economy, operating partly through direct action and partly by encouraging private initiative."})

intermediate.append({"q":"Consider the following statements regarding India's model of planning at Independence:\n1. India's planning model was directly and fully modelled on French indicative planning, adopted in 1944-45.\n2. The Soviet model of planning, though influential, was a command economy model that did not fully suit India's democratic, privately-owned economic structure.\n3. The Great Depression (1929) and post-WWII reconstruction needs contributed to a global shift favouring state intervention in the economy.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1, 2 and 3","1 and 3 only","1 and 2 only"],"a":0,"e":"Statements 2 and 3 are correct. Statement 1 is false — the text notes France's mixed-economy planning (from 1944-45) had 'little experience to offer' Indian policymakers by 1947, so it was not the direct/full model followed; the Soviet model was influential but imperfectly suited to India's democratic structure."})

intermediate.append({"q":"Consider the following statements on the reasons for delayed agricultural reforms in India (relative to industrial reforms initiated in 1991):\n1. Agriculture was already open to the private sector, making further privatisation less straightforward and requiring 'corporate'/'contract' farming approaches instead.\n2. There was low awareness of reform contours among the farming community.\n3. Heavy population dependence on agriculture for livelihood required the industrial sector to expand first, to absorb labour before major agricultural reform.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements accurately reflect the reasons cited for the delay in serious agricultural sector reform (relative to the 1991 industrial reforms) — reaching a policy consensus only by the early 2000s."})

intermediate.append({"q":"Which of the following statements about the public sector's role in India's core/basic industries is correct?","o":["Prior to major private-sector expansion, most core industries (like iron & steel, crude oil refining) had negligible private presence, with a lone private company in iron & steel and only a beginning stage for crude oil/refining","All eight core industries were entirely privately owned before the government's PSU expansion began","Cement and coal were both fully government-monopolised from the outset with no private sector presence at all","The core/basic industries classification has remained unchanged since 1951, with no additions"],"a":0,"e":"Historically, the core industries had limited private presence — cement had 'some strength' in the private sector, iron & steel had a lone private company, and crude oil/refining was just beginning — necessitating government-led expansion; the core industries list was later expanded in 2013 with two additions (Natural Gas, Fertilisers)."})

intermediate.append({"q":"Consider the following statements about the trajectory of India's disinvestment policy discussed in the context of PSU evolution:\n1. Strategic disinvestment was first launched around 2000 but was paused by the UPA-I government around 2003-04.\n2. Since the 2016-17 financial year, the government restarted the process of 'strategic disinvestment', involving potential transfer of PSU ownership to the private sector.\n3. India has never allowed foreign institutional investors to purchase enhanced shares of PSUs, restricting sales to domestic financial institutions only.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false — the government has explicitly decided in favour of selling increased PSU shares to foreign institutions at par with domestic financial institutions, not restricting sales to domestic entities alone."})

intermediate.append({"q":"Which of the following best explains why the mid-1980s saw a global consensus (including at the IMF/World Bank) forming against Public Sector Undertakings?","o":["A perceived inefficiency and under-performance of PSUs emerged alongside the rise of the Washington Consensus promoting neo-liberal economic policies worldwide","PSUs were found to be more profitable than private firms, prompting calls for their expansion","The mid-1980s consensus favoured permanent, irreversible state control over all core industries","This consensus was driven exclusively by domestic Indian political factors with no international dimension"],"a":0,"e":"The mid-1980s saw a convergence around PSU inefficiency/under-performance narratives tied to the rise of the Washington Consensus's neo-liberal policy prescriptions — a global trend, not a purely domestic Indian phenomenon, and one that (per the text) later softened somewhat after the mid-2000s US sub-prime crisis."})

intermediate.append({"q":"Consider the following statements regarding pre-independence economic thought and its influence on post-1947 Indian policy:\n1. The idea that India needed economic planning was decided by nationalist leaders roughly a decade before Independence.\n2. The dominant internal political-economic force shaping government decisions after Independence is often described as 'Gandhian Socialism'.\n3. Major strategic economic decisions that shaped India's economic journey were largely finalised only after 1956.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false — the text specifically states that many important strategic decisions shaping the Indian economy were taken 'only by 1956', not largely finalised only AFTER 1956, indicating 1956 was roughly the cut-off point for these foundational decisions."})

intermediate.append({"q":"Which of the following is the most accurate characterisation of the 'mixed economy' concept's trajectory in India from the 1950s to the 1990s?","o":["It was outlined in 1951, went through detailed evolution in the 1950s, was almost buried by the end of the 1950s, and revived from the mid-1980s, culminating in the 1991 reforms","It remained constant and unchanged in form from 1951 through to the 1991 reforms","It was abandoned entirely in the 1950s and never revived at any subsequent point","It was only introduced for the first time during the 1991 reforms"],"a":0,"e":"The text traces a specific arc: the mixed economy concept, articulated in the First Plan (1951), evolved through the 1950s, was largely 'buried' by decade's end, and only rose from 'hibernation' by the mid-1980s before being redefined during the 1991 reforms — not a static, abandoned, or entirely new (1991-origin) concept."})

intermediate.append({"q":"Consider the following statements regarding the pre-Independence consensus among India's political and industrial leadership:\n1. Foreign investment was to be actively discouraged.\n2. Heavy industries were considered a developmental necessity.\n3. Economic planning was considered unnecessary in a newly free, democratic nation.\n4. The public sector was to be assigned only a marginal, negligible role.\nHow many of the statements given above are correct?","o":["Only two","Only one","Only three","All four"],"a":0,"e":"Statements 1 and 2 are correct, matching two of the five pre-Independence consensus points (discouraging foreign investment, need for heavy industries). Statements 3 and 4 are both false and reverse the actual consensus — planning was considered essential (not unnecessary), and the public sector was assigned an ambitious (not marginal) role. Hence, only two of the four statements are correct."})

intermediate.append({"q":"Consider the following statements about India's shift toward agriculture as its 'prime moving force' from the Tenth Plan (2002-07) onward:\n1. It aimed to improve food security and generate agricultural export surpluses.\n2. It aimed to alleviate poverty by making agriculture more income-generating.\n3. It aimed to resolve India's characteristic 'market failure' situation.\n4. It aimed to eliminate the industrial sector entirely in favour of agriculture.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are correct — these were the three explicit goals of the Tenth Plan's agriculture-first reorientation. Statement 4 is false; the shift never envisaged eliminating industry, only reprioritising which sector led development."})

# ---------------- ADVANCED ----------------

advanced.append({"q":"Which one of the following best captures the historical-comparative argument (via Angus Maddison) about India and China's economic position around 1500 AD, relevant to understanding the colonial economic transformation?","o":["India and China together accounted for roughly three-quarters of Asia's population and GDP in 1500 AD, making their subsequent divergent trajectories under colonialism/reform particularly significant for economic historians","India's GDP share in Asia in 1500 AD was negligible compared to China's, which already dominated Asian output","Maddison's data shows India was already industrially advanced relative to Britain by 1500 AD","This comparison is used to argue that colonialism had no measurable impact on India's economic trajectory"],"a":0,"e":"Maddison's data on India and China jointly representing about three-quarters of Asia's 1500 AD population and GDP underscores how significant their subsequent divergent trajectories became — directly relevant to assessing colonialism's transformative economic impact on India, not a claim of colonialism's irrelevance."})

advanced.append({"q":"Which one of the following best explains why India's leadership, despite having Gandhian-influenced nationalist credentials rooted in village and agrarian ideals, ultimately chose industry over agriculture as the prime moving force?","o":["A combination of factors — traditional agriculture's technological constraints without industrial support, global (WB/IMF) ideological preference for industrialisation, defence imperatives post-WWII, and a socio-economic consensus favouring modernisation over traditional practices — collectively outweighed the agrarian option","Gandhi himself was in government and personally overturned the agrarian approach in favour of industry","There was no debate at all among economists about this choice; it was universally uncontroversial","Agricultural land in India was entirely unsuitable for cultivation at the time of Independence"],"a":0,"e":"The text lists multiple converging factors — technological constraints on traditional agriculture without industrial backing, the era's dominant WB/IMF industrialisation ideology, post-WWII defence-industrial imperatives, and a modernisation-oriented socio-economic consensus — as jointly explaining the industry-over-agriculture choice, not any single cause, Gandhi's direct governmental role (he was not in government), or a claim of unsuitable agricultural land."})

advanced.append({"q":"Which one of the following statements correctly relates the 'East Asian Miracle' (World Bank, 1993) to debates about the state's role in the economy?","o":["It revived discussions on the appropriate limits of state intervention by showing East Asian economies sustained high growth over three decades, with conclusions similar to what India's own First Five Year Plan (1951) had already articulated","It concluded that state intervention in any form is universally harmful to economic growth","It focused exclusively on Latin American economies rather than East Asian ones","It was published before, and directly inspired, India's First Five Year Plan of 1951"],"a":0,"e":"The 1993 'East Asian Miracle' study (chronologically after India's 1951 First Plan) drew conclusions on balanced state-market roles remarkably similar to what India's own First Plan document had articulated over four decades earlier — not a wholesale condemnation of state intervention or a Latin America-focused or pre-1951 study."})

advanced.append({"q":"Which one of the following best explains the multi-dimensional rationale behind the 'trickle-down' justification for PSU-driven employment generation in early independent India?","o":["PSU employment was seen as both a poverty-alleviation tool and a vehicle for social change, given land ownership's historical concentration among upper castes, with reservations in PSU jobs serving as an economic tool for social transformation","PSU employment was purely a fiscal exercise unrelated to poverty alleviation or social equity concerns","The trickle-down rationale was rejected outright by the government and never implemented in PSU employment policy","PSU jobs were reserved exclusively for upper-caste candidates to maintain administrative efficiency"],"a":0,"e":"The rationale combined poverty alleviation, addressing caste-based land ownership concentration, and using PSU job reservations as a deliberate economic instrument for social change — a genuinely multi-dimensional justification, not a purely fiscal, rejected, or upper-caste-favouring one."})

advanced.append({"q":"Which one of the following statements about the fiscal consequences of PSU employment expansion, as critically assessed in retrospect, is correct?","o":["The government extended PSU employment generation to such an extent that over-supply of labour started draining PSU profits through salaries, wages, pensions and provident fund liabilities, with the latter two having delayed financial impact","PSU employment expansion had no discernible impact on PSU profitability at any point","PSU pension and provident fund liabilities were fully funded and caused no future fiscal strain","The government capped PSU employment strictly according to calculated future labour force needs from the outset"],"a":0,"e":"The retrospective critique explicitly notes PSU over-employment (pursued without adequately calculating future labour force/resource needs) led to profit drains via wage/pension/PF burdens, with pension and PF liabilities carrying delayed ('back-loaded') fiscal impact — not a scenario of no impact, full funding, or careful ex-ante labour force calculation."})

advanced.append({"q":"Which one of the following statements correctly captures the argument, attributed to Amartya Sen and Jean Dreze, about how a shift to agriculture as the prime moving force (from 2002) was expected to resolve India's 'market failure' problem?","o":["As agricultural activities become more gainful and profitable, the rural masses dependent on agriculture would gain the purchasing power needed to create genuine market demand for industrial goods, thereby ending the market-failure dynamic","Market failure in India was expected to be resolved purely through increased industrial licensing reforms unrelated to agricultural incomes","Sen and Dreze argued market failure could only be resolved through complete agricultural privatisation","The market failure argument applied only to export markets, not domestic demand for industrial goods"],"a":0,"e":"Sen and Dreze's 'market failure' framework specifically ties agricultural income growth to the emergence of genuine domestic purchasing power for industrial goods — directly linking a more profitable agriculture sector to resolving the demand-side market failure, not to licensing reform, privatisation, or export markets specifically."})

advanced.append({"q":"Which one of the following best explains why the Planning Commission's Tenth Plan (2002-07) framing of agriculture as the 'prime moving force' was expected to address three distinct challenges simultaneously?","o":["It was expected to enhance food security and export surplus, reduce poverty through more gainful rural employment, and resolve India's characteristic 'market failure' situation — three linked goals addressed via a single agriculture-first strategic reorientation","It addressed only fiscal deficit reduction, with no bearing on food security, poverty or market failure","It was designed solely to increase industrial licensing efficiency","It focused exclusively on export competitiveness with no domestic poverty or market-failure dimension"],"a":0,"e":"The Tenth Plan's rationale explicitly linked the agriculture-first shift to three simultaneous goals: food security plus export surplus (from higher production), poverty alleviation via more gainful rural employment, and ending India's 'market failure' situation — a genuinely three-pronged strategic logic."})

advanced.append({"q":"Assertion (A): India's leadership chose industry, rather than agriculture, as the economy's prime moving force after Independence.\nReason (R): The dominant global ideology of the time, including at the IMF and World Bank, viewed emphasis on agriculture as a symbol of economic backwardness.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are factually accurate, and R directly explains A — the era's dominant WB/IMF-backed industrialisation ideology (treating agricultural emphasis as 'backwardness') was one of the explicit reasons cited for India's industry-first choice."})

advanced.append({"q":"All of the following are correctly identified as pre-requisites India lacked for industrialisation at Independence, EXCEPT:","o":["Abundant fertile cultivable land suited for agriculture","Presence of infrastructure industries such as iron and steel, cement, coal and electricity","Investible capital, whether from government or private sources","Required technology and research & development capacity to support industrialisation"],"a":0,"e":"Fertile cultivable land was actually one of India's genuine RESOURCE STRENGTHS (cited as a reason agriculture, not industry, was the more 'obvious' choice) — it was not a missing pre-requisite for industrialisation, unlike infrastructure industries, investible capital, and technology/R&D capacity, all of which India genuinely lacked."})

# ---------------- UPSC TIER ----------------

upsc.append({"q":"Which one of the following statements about India's colonial economic legacy at the time of Independence is correct?","o":["Per capita income figures (around Rs. 18-39.5 in current prices for 1895-99) alongside repeated famines and disease epidemics reflected an economy of abject mass poverty compounded by British administrative neglect","India's per capita income at Independence was among the highest in Asia due to colonial-era infrastructure investment","There is strong documented evidence of significant technology transfer from Britain to India during colonial rule, contradicting the 'colonial exploitation' narrative","Aggregate real output grew at over 5 per cent annually during the first half of the twentieth century under British rule"],"a":0,"e":"Historical estimates (Digby, Atkinson, cited by Sumit Sarkar) show extremely low per capita incomes and severe famine/epidemic-driven distress — not high incomes, not evidence of significant tech transfer (which Maddison notes is largely absent), and not high (5%+) output growth, which was actually below 2% annually."})

upsc.append({"q":"Which one of the following statements correctly describes the philosophical position taken in India's First Five Year Plan (1951) regarding planning technique and the public-private balance?","o":["It held that complete nationalisation, while a possible planning technique, was 'neither necessary nor desirable' at that stage, envisaging planning as minimal compulsion with the state guiding an economy operated partly by direct state action and partly by private initiative","It mandated complete and immediate nationalisation of all major industries as the only viable planning technique","It rejected any distinction between public ownership and public regulation as planning tools","It concluded that private initiative should play no part in production or distribution under the Plan"],"a":0,"e":"The First Plan's draft outline document explicitly rejected complete nationalisation as neither necessary nor desirable, favouring an economy 'guided and directed by the state' but operated partly through direct state action and partly through private initiative — a nuanced middle path, not full nationalisation or private-sector exclusion from planning altogether."})

upsc.append({"q":"Which one of the following statements about the global intellectual context influencing India's choice of a planned economy is correct?","o":["The Great Depression (1929), post-WWII reconstruction needs, and the contemporaneous faster growth reported by Soviet/East European command economies collectively shaped a 1950s-60s global consensus favouring active state intervention, which influenced India's planning choice","India's planned economy model was chosen in complete isolation from any global intellectual or economic trends of the time","The Great Depression had no bearing on global economic policy thinking regarding state intervention","Soviet and East European economies were reporting slower growth than market economies throughout the 1950s and 1960s, discouraging emulation"],"a":0,"e":"The convergence of the Great Depression's lessons, post-WWII reconstruction imperatives, and reports of faster Soviet/East European growth collectively shaped a global 1950s-60s consensus favouring state intervention — directly influencing India's planning choice, not an isolated decision or one made despite reports of slower command-economy growth (the reports were of FASTER growth at the time)."})

upsc.append({"q":"Which one of the following statements about the disinvestment policy trajectory discussed alongside India's PSU evolution is correct?","o":["India pursued a comparatively less ambitious disinvestment policy from 2003-04 to 2015-16 (retaining controlling government stakes), before restarting 'strategic disinvestment' (potential ownership transfer) from 2016-17 onward","India's disinvestment policy has remained completely unchanged in ambition and approach from 2000 to the present day","Strategic disinvestment, involving potential PSU ownership transfer to private parties, was first introduced only after 2016-17 with no prior precedent","The UPA-I government (2003-04) accelerated, rather than paused, the strategic disinvestment process initiated in 2000"],"a":0,"e":"The correct sequence is: strategic disinvestment launched around 2000, paused by UPA-I around 2003-04 (a less ambitious policy retaining controlling stakes followed through 2015-16), then restarted from 2016-17 onward — not a static policy, an entirely novel post-2016 concept, or an acceleration by UPA-I."})

upsc.append({"q":"Which one of the following statements correctly identifies the five major rationales cited for the ambitious post-Independence expansion of Public Sector Undertakings (PSUs) in India?","o":["Infrastructural needs, industrial/core-sector needs, employment generation (trickle-down), profit generation for social sector development, and enabling the eventual rise of the private sector","Maximising short-term export revenue, currency stabilisation, defence procurement exclusively, tourism promotion, and urban housing development","Attracting foreign direct investment exclusively, reducing fiscal deficits, promoting stock market listings, curbing inflation, and expanding tertiary-sector services","Encouraging private monopolies, reducing government's regulatory footprint, promoting deregulation, privatising utilities, and minimising public expenditure"],"a":0,"e":"The text specifically identifies five rationales for PSU expansion: meeting infrastructural needs, meeting core/basic-industry needs, generating employment (trickle-down effect), generating profits to fund social-sector development, and laying the foundation for the eventual rise of the private sector — not the alternative, largely fiscal/export/deregulation-oriented framings in the other options."})

upsc.append({"q":"Which one of the following statements best explains why India's agricultural sector reforms lagged behind industrial reforms initiated in 1991, according to the reasons given in the text?","o":["Since agriculture was already open to private participation, the required reform was less about privatisation and more about enabling corporate/contract farming, compounded by low farmer awareness of reforms and the need to first expand industry to absorb population dependent on agriculture","Agricultural reforms were deliberately excluded from the reform agenda due to constitutional restrictions on Centre-State agricultural jurisdiction","Agriculture required no reform at all since it was already fully liberalised prior to 1991","The government prioritised agricultural reform over industrial reform throughout the 1990s, contrary to conventional accounts"],"a":0,"e":"The genuine reasons cited are structural (agriculture's pre-existing private-sector openness requiring a different reform approach centred on corporate/contract farming), awareness-related (limited farmer understanding of reforms), and sequencing-related (industrial expansion needed first to absorb agriculture-dependent population) — not constitutional exclusion, an already-liberalised sector, or agriculture being prioritised over industry."})

upsc.append({"q":"Consider the following statements regarding the reasons for India's ambitious Public Sector Undertaking (PSU) expansion after Independence:\n1. The private sector of the time could not manage the heavy investment, technology and skilled manpower needed for infrastructure and core industries.\n2. PSUs were envisaged partly as instruments of social change, given the historical concentration of land ownership among upper castes.\n3. PSU profits were intended to fund the development of social sector goods like education, healthcare and nutrition.\n4. PSUs were established with no expectation of ever generating employment for the workforce.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are correct and reflect genuine, explicitly documented rationales for PSU expansion. Statement 4 is false and contradicts the text directly — employment generation (via the 'trickle-down' rationale) was very much an intended and heavily emphasised role for PSUs."})

upsc.append({"q":"With reference to India's colonial economic legacy and its post-Independence planning choices, which one of the following statements is NOT correct?","o":["France's mixed-economy planning model (from 1944-45) served as the primary and fully-adopted template for India's own planning framework after 1947","The 'drain of wealth' and unequal exchange under colonial rule crippled India's indigenous commerce, trade and handloom industry","Indian capitalists who emerged under colonial rule remained heavily dependent on British commercial capital","The National Planning Committee (1938) reflected pre-Independence recognition of the need for economic planning"],"a":0,"e":"This statement is incorrect — the text explicitly notes France's mixed-economy planning experience (though relevant in principle) had 'little experience to offer' Indian policymakers by 1947, meaning it was not fully adopted as India's primary template; the Soviet model was more directly influential (though imperfectly suited). The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

# fix accidental syntax artifact
for q in advanced:
    if isinstance(q.get("a"), str) or q.get("a") is None:
        q["a"] = 0

chapter = {
    "id": "eco_evolution_indian_economy",
    "title": "Evolution of the Indian Economy",
    "desc": "Colonial economic legacy, the agriculture-vs-industry prime mover debate, planned/mixed economy origins, and the rationale for public sector expansion",
    "questions": {
        "basic": basic,
        "intermediate": intermediate,
        "advanced": advanced,
        "upsc": upsc,
    }
}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("Total questions:", len(all_q))
print("basic:", len(basic), "intermediate:", len(intermediate), "advanced:", len(advanced), "upsc:", len(upsc))
print("unique texts:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert isinstance(q["a"], int) and 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_evolution_chapter.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
