import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_external_sector (Ramesh Singh Ch.15, External Sector in India)
# Fixed/Floating/Managed exchange rate regimes, India's exchange-rate history,
# BoP, current/capital account convertibility (Tarapore Committees), LERMS,
# NEER/REER, EFF, IMF 1991 conditions
# ==================================================================

upsc.append({"q":"With reference to exchange rate regimes, consider the following statements:\n1. Under the fixed currency regime historically administered by the IMF, exchange rates were pegged against a basket of currencies including the UK£, US$, Japanese ¥, German Mark and French Franc.\n2. The United Kingdom shifted to the floating currency regime in 1973 after blaming the fixed system for its payment crisis of the late 1960s.\n3. A managed exchange rate system is a pure floating system with zero government intervention.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is incorrect — a managed exchange rate system is explicitly a HYBRID of fixed and flexible systems, where the government intervenes (directly by buying/selling currency, or indirectly via monetary policy) rather than allowing pure free float."})

upsc.append({"q":"Which one of the following correctly traces the evolution of India's exchange rate regime?","o":["Fixed link to the British Pound until 1948 → delinked from the Pound in September 1975 and pegged to a currency basket → floating 'dual exchange rate' regime adopted in 1992-93","Floating regime since Independence → fixed peg to the US Dollar adopted in 1992-93 → delinked from the Dollar in 2016","Fixed peg to the US Dollar since 1928 → floating regime adopted immediately after Independence in 1947","Dual exchange rate system adopted in 1975 → fixed Pound Sterling peg reinstated in 1992-93"],"a":0,"e":"The rupee was linked to the British Pound Sterling (fixed since 1928) until 1948, when India (via the IMF) committed to a gold/US Dollar-linked fixed exchange rate; it delinked from the Pound in September 1975, moving to a currency-basket-based system; and finally adopted the floating 'dual exchange rate' system (LERMS) in the 1992-93 financial year."})

upsc.append({"q":"India's 'dual exchange rate' system, operationalised through the Liberalised Exchange Rate Mechanism System (LERMS) announced in the Union Budget 1992-93, is characterised by which one of the following features?","o":["Two exchange rates for the rupee — an 'official rate' and a 'market rate' — with the everyday market-based rate influencing the official rate, and not the reverse","Two exchange rates fixed permanently by the IMF for the rupee against the US Dollar and the British Pound","A system under which the official rate solely determines and drives the market rate","A system that reinstated the fixed currency regime India had followed prior to 1975"],"a":0,"e":"Under LERMS' dual exchange rate arrangement, the market-driven rate (reflecting actual demand-supply of foreign currency) is what influences and shapes the official rate — not the other way around — a defining feature of India's shift towards a managed/floating regime from 1992-93."})

upsc.append({"q":"Consider the following statements about India's current account and its convertibility:\n1. India achieved full current account convertibility on 19 August 1994, as obligated under Article VIII of the IMF, which prohibits exchange restrictions on current international transactions.\n2. India recorded a surplus current account for three consecutive years, 2000-03 — the only such period in Indian economic history.\n3. As per an RBI release of April 2014, the sustainable level of current account deficit for India was estimated at 2.5 per cent of GDP.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct — full current account convertibility from 19 August 1994 under IMF Article VIII obligations, the unique 2000-03 current account surplus period, and the RBI's April 2014-stated sustainable CAD benchmark of 2.5% of GDP."})

upsc.append({"q":"Which one of the following statements about the S.S. Tarapore Committee(s) on Capital Account Convertibility (CAC) is correct?","o":["The first Tarapore Committee submitted its report in 1997, and a Second Committee, also chaired by S.S. Tarapore, submitted its report in September 2006","Both Tarapore Committee reports on CAC were submitted in the same year, 1997","The Tarapore Committee dealt exclusively with current account convertibility, not capital account convertibility","The recommendations of the Tarapore Committee resulted in India achieving full, unrestricted capital account convertibility by 2006"],"a":0,"e":"The first S.S. Tarapore Committee report on Capital Account Convertibility came in 1997; a Second Committee on CAC, again chaired by Tarapore, reported in September 2006. Despite reforms flowing from both, India remains only PARTIALLY convertible (approximately 40:60) on the capital account, not fully convertible."})

upsc.append({"q":"With reference to India's capital account convertibility provisions, consider the following statements:\n1. Indian corporates are allowed full convertibility under the automatic route for overseas investment up to USD 500 million per annum.\n2. Individuals are permitted to invest in foreign assets and shares up to USD 2,50,000 per annum.\n3. Unlimited import of gold is currently allowed under Indian regulations, exemplifying full current-account-route capital convertibility.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe genuine capital account convertibility provisions. Statement 3 is incorrect — while unlimited gold import WAS at one point a channel that effectively allowed capital convertibility via the current account route, the text explicitly notes this facility 'is not allowed now', making statement 3 a factual trap."})

upsc.append({"q":"Which one of the following pairs of terms relating to India's exchange rate is correctly matched with its definition?","o":["NEER — Real Effective Exchange Rate; REER — Nominal Effective Exchange Rate","NEER — a weighted average of the rupee's exchange rates against India's major trading-partner currencies; REER — the NEER adjusted for the weight of inflation","NEER and REER are two alternative names for the same exchange rate concept, differing only in terminology","NEER is calculated by the IMF while REER is calculated exclusively by the World Bank"],"a":1,"e":"NEER (Nominal Effective Exchange Rate) is the rupee's weighted-average exchange rate against major trading partners' currencies; REER (Real Effective Exchange Rate) additionally adjusts NEER for inflation differentials — the first option reverses these definitions."})

upsc.append({"q":"The 'Extended Fund Facility' (EFF), a service the IMF provides to member countries facing balance-of-payments difficulties, is best described by which one of the following?","o":["A facility authorising member countries to raise foreign exchange to address a BoP crisis, subject to conditions of structural economic reform, with India first signing such an agreement in 1981-82","A facility that provides unconditional, no-strings-attached foreign exchange assistance to any requesting member country","A facility exclusively available to developed economies facing current account surpluses","A facility introduced by the World Bank, not the IMF, to fund long-term infrastructure projects"],"a":0,"e":"The EFF authorises IMF member countries to draw foreign exchange to address BoP crises, conditional on structural reforms — described in the text as the first agreement of its kind, with India signing it in financial year 1981-82."})

upsc.append({"q":"Consider the following conditions that were part of the medium-term IMF loan extended to India during its early-1990s Balance of Payments crisis:\n1. Devaluation of the rupee by 22 per cent, carried out in two consecutive fortnights.\n2. A drastic cut in peak customs duty to 30 per cent from an earlier level of 130 per cent.\n3. An increase in excise duty by 20 per cent to neutralise revenue loss from the customs cut.\n4. An increase in government expenditure by 10 per cent per annum to boost demand.\nHow many of the above are genuine conditions of the IMF's early-1990s loan to India?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are genuine IMF conditions. Statement 4 is fabricated and in fact REVERSES the true condition — the IMF required government expenditure to be CUT by 10 per cent per annum (covering the burden of salaries, pensions, subsidies), not increased, as part of the fiscal consolidation demanded alongside the BoP-crisis lending."})

upsc.append({"q":"Assertion (A): A negative Balance of Payments (BoP) is not, by itself, necessarily unfavourable for an economy.\nReason (R): The BoP is calculated on the double-entry book-keeping principle, and a negative outcome is drawn from the country's foreign exchange reserves; it becomes unfavourable, and potentially a 'BoP crisis', only if forex reserves are insufficient to cover the shortfall.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — a negative BoP outcome is met by drawing down forex reserves; it only becomes a genuine crisis (requiring measures like IMF assistance as a last resort) when reserves are inadequate to cover the negativity, so negativity alone does not automatically imply an unfavourable outcome."})

upsc.append({"q":"Which one of the following statements correctly distinguishes the 'current account' from the 'capital account' in India's Balance of Payments?","o":["The current account records transactions like exports, imports, interest payments and private remittances, and can show a surplus or deficit; the capital account records transactions like external lending/borrowing, FDI and portfolio investment, and does not have a concept of surplus or deficit","The capital account records exports and imports of goods, while the current account records FDI and external borrowings","Both accounts are functionally identical and merely represent duplicate record-keeping for the same set of transactions","The current account, unlike the capital account, cannot show a deficit under any circumstances"],"a":0,"e":"The current account (exports, imports, interest payments, remittances/transfers) can register a surplus or deficit, whereas the capital account (external lending/borrowing, FDI, portfolio investment/QFI flows) has no surplus/deficit concept — it simply nets inflows against outflows of capital-nature transactions."})

upsc.append({"q":"Which one of the following statements about the 'currency board' arrangement, as an extreme form of a fixed/pegged exchange rate, is correct?","o":["It has worked well in Hong Kong, but a similar arrangement failed in Argentina in 2002","It refers to a purely market-determined exchange rate mechanism with no element of pegging","It was the exchange rate system historically used by India prior to 1948","It is a system exclusively used by economies with large current account surpluses"],"a":0,"e":"A currency board represents a 'hard fix' of a currency (an extreme, rigid form of pegging) — the text cites Hong Kong as a successful example, while a comparable currency board arrangement in Argentina collapsed in 2002, illustrating the risks of hard pegs when the anchor currency or economic fundamentals come under strain."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_external_sector_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
