import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_intl_orgs (Ramesh Singh Ch.16, International Economic
# Organisations & India) — IMF governance/quota, World Bank Group (IBRD/IDA/
# IFC/MIGA/ICSID), WTO (GATT/Uruguay Round/Ministerial Conferences), BRICS NDB
# & CRA, AIIB
# ==================================================================

upsc.append({"q":"With reference to India's representation at the International Monetary Fund (IMF), consider the following statements:\n1. India's Finance Minister serves as the Ex-officio Governor on the IMF's Board of Governors, with the RBI Governor as the Alternate Governor.\n2. India is represented on the IMF's Board of Executive Directors by an Executive Director who also represents Bangladesh, Sri Lanka and Bhutan in a shared constituency.\n3. The IMF reviews members' quotas once every five years, with the last review (as of the book's reference period) completed in December 2010.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — India's Finance Minister is Ex-officio Governor with the RBI Governor as Alternate; India's Executive Director represents a constituency including Bangladesh, Sri Lanka and Bhutan; and the IMF's quota review cycle is five-yearly, with the last one concluded in December 2010."})

upsc.append({"q":"Following the IMF quota review concluded in December 2010, which one of the following correctly describes the change in India's standing?","o":["India's quota share rose from 2.44 per cent to 2.75 per cent, and its ranking among the 24 constituencies improved from 11th to 8th largest quota holder","India's quota share fell from 2.75 per cent to 2.44 per cent, worsening its rank from 8th to 11th","India's quota remained unchanged, but its voting rights on the Executive Board were expanded","India became the single largest quota holder at the IMF, surpassing the United States"],"a":0,"e":"Post the December 2010 review, India's quota rose from 2.44% to 2.75% (in absolute terms, from SDR 5,821.5 million to SDR 13,114.4 million, roughly a US$11.5 billion / Rs. 56,000 crore increase), improving its ranking from 11th to 8th largest quota-holding constituency."})

upsc.append({"q":"Which one of the following correctly matches the five institutions of the World Bank Group with their year of establishment and core function?","o":["IBRD (1945) — reconstruction/development lending; IDA (1960) — soft, near-interest-free lending to low-income countries; IFC (1956) — private sector lending; MIGA (1988) — political risk insurance for foreign investors; ICSID (1966) — investment dispute settlement","IBRD (1960) — private sector lending; IDA (1945) — reconstruction lending; IFC (1988) — dispute settlement; MIGA (1956) — political risk insurance; ICSID (1966) — soft lending","All five institutions were established simultaneously in 1944 at the Bretton Woods Conference","IDA is the 'hard window' of the World Bank while IBRD is the 'soft window'"],"a":0,"e":"The correct pairings are: IBRD (1945, reconstruction/development), IDA (1960, soft/near-interest-free lending, the 'soft window'), IFC (1956, private sector lending, the 'private arm'), MIGA (1988, political risk insurance), and ICSID (1966, binding investment dispute settlement) — they were established at different times, not simultaneously."})

upsc.append({"q":"Which one of the following statements about India and the International Centre for Settlement of Investment Disputes (ICSID) is correct?","o":["India is not a member of ICSID, which is why the Enron-related dispute could not be brought within its purview","India is a founding member of ICSID and has used it to settle several investment disputes, including the Enron issue","ICSID is a World Bank institution created in 1988 exclusively for South Asian member nations","Membership of ICSID is mandatory for all World Bank Group member countries"],"a":0,"e":"India is NOT a member of ICSID (established 1966 under the Convention on the Settlement of Investment Disputes) — this is precisely why the Enron dispute could not be taken up before it. Being a signatory is seen as encouraging foreign investment flows but is also viewed as carrying risks to independent sovereign decision-making, which is why India has stayed out."})

upsc.append({"q":"With reference to India's standing in the International Bank for Reconstruction and Development (IBRD) following the World Bank's 2010 reform process, which one of the following is correct?","o":["India was allotted additional shares, emerging as the 7th largest shareholder in IBRD with voting power rising from 2.77 per cent to 2.91 per cent","India's shareholding in IBRD was reduced, and its rank fell from 7th to 11th largest shareholder","India became the single largest shareholder in IBRD, ahead of the United States and Japan","IBRD does not have a shareholding structure; voting rights are equally distributed among all member nations"],"a":0,"e":"Post the World Bank's 2010 reforms, India was allotted additional IBRD shares (56,739 shares worth about US$6,844.7 million), rising from 11th to 7th largest shareholder, with voting power increasing from 2.77% to 2.91%."})

upsc.append({"q":"The World Trade Organization (WTO) evolved out of which one of the following predecessor arrangements, and through which negotiation round?","o":["The General Agreement on Tariffs and Trade (GATT, 1947), formally succeeded by the WTO following the Uruguay Round negotiations (1986-1994)","The Bretton Woods Agreement (1944), succeeded by the WTO following the Doha Round negotiations","The International Trade Organization (ITO), which was successfully established in 1948 and later renamed the WTO","The Havana Charter (1948), which directly created the WTO without any intervening negotiation rounds"],"a":0,"e":"The WTO emerged from GATT (1947) via the protracted Uruguay Round negotiations (1986-1994), which also extended multilateral rules to agriculture (Agreement on Agriculture), services (GATS) and intellectual property (TRIPS). The proposed International Trade Organization (ITO) under the Havana Charter, by contrast, was NEVER actually established due to US opposition, despite its charter being drawn up."})

upsc.append({"q":"Consider the following statements regarding WTO's non-discrimination principles as they apply to India's trade:\n1. 'National Treatment' ensures that India's products, once imported into another WTO member's territory, are not discriminated against relative to that country's domestic products.\n2. 'Most Favoured Nation' (MFN) treatment ensures that WTO members do not discriminate among different WTO member countries.\n3. Both principles are enforceable only through bilateral trade agreements and have no basis within the WTO's own rules.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 2 correctly define National Treatment and MFN treatment as core WTO non-discrimination principles. Statement 3 is incorrect — these principles are foundational WTO RULES themselves (not merely bilateral arrangements), and a member believing these rules have been violated can invoke the WTO's own Dispute Settlement Mechanism (DSM)."})

upsc.append({"q":"Which one of the following statements about WTO Ministerial Conferences is correct?","o":["The 11th WTO Ministerial Conference was held in Buenos Aires, Argentina in December 2017, while the 10th was held in Nairobi, Kenya in December 2015 — the first Ministerial Conference hosted by an African nation","The 10th WTO Ministerial Conference was held in Buenos Aires and the 11th in Nairobi","Ministerial Conferences, the WTO's highest decision-making body, are mandated to meet only once every ten years","The Nairobi Ministerial Conference of 2015 was hosted by an East Asian nation for the first time"],"a":0,"e":"The 11th Ministerial Conference (Buenos Aires, 10-13 December 2017) followed the 10th (Nairobi, Kenya, 15-19 December 2015) — the latter being the first WTO Ministerial Conference ever hosted by an African nation. Ministerial Conferences, the WTO's highest decision-making body, are mandated to meet at least every TWO years, not ten."})

upsc.append({"q":"With reference to the New Development Bank (NDB), established via the Fortaleza Declaration (July 2014) of the BRICS nations, consider the following statements:\n1. The NDB was set up with an initial subscribed capital of $50 billion, shared equally among Brazil, Russia, India, China and South Africa.\n2. A Contingent Reserve Arrangement (CRA) of $100 billion was also created, providing currency-swap-based liquidity support during BoP pressures.\n3. Within the CRA, China contributes the largest share (41 per cent), followed by Brazil, India and Russia at 18 per cent each, and South Africa at 5 per cent.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct — $50 billion equally-shared NDB capital, a complementary $100 billion CRA for currency swaps during BoP stress, with China's 41% CRA contribution being the largest, followed by 18% each from Brazil/India/Russia and 5% from South Africa."})

upsc.append({"q":"Which one of the following is a distinctive governance feature of the New Development Bank (NDB) that its proponents contrast favourably with the Bretton Woods institutions (IMF and World Bank)?","o":["The NDB follows a 'one-nation, one-vote' principle, unlike the IMF/World Bank's quota/shareholding-weighted voting structures viewed by BRICS as inequitable","The NDB grants veto power exclusively to the largest capital contributor, China, mirroring the US's effective veto at the IMF","The NDB has no formal capital structure and instead relies entirely on annual donations from member states","The NDB's voting structure is identical to that of the IMF, with quotas determining voting weight"],"a":0,"e":"The Fortaleza Declaration is notably remarked upon for its adoption of a 'one-nation, one-vote' principle for the NDB — a deliberate departure from the Bretton Woods institutions' quota/shareholding-based structures, which BRICS members have criticised as inequitable and lacking legitimacy."})

upsc.append({"q":"Which one of the following statements about the Asian Infrastructure Investment Bank (AIIB) is correct?","o":["It was first proposed by Chinese President Xi Jinping in October 2013 and officially launched in Beijing a year later with 21 founding Asian member nations","It was proposed by the United States in 2013 as a complement to the Asian Development Bank","It was established under the Bretton Woods Conference alongside the IMF and World Bank","It exclusively finances agricultural development projects across Asia, similar to the IFAD"],"a":0,"e":"The AIIB was proposed by Chinese President Xi Jinping in October 2013, officially launched in Beijing in 2014 with 21 founding Asian member nations, and has since attracted additional applicants including several non-Asian nations (UK, Germany, France, Australia, New Zealand) — it is aimed at infrastructure financing, not agriculture, and is unrelated to the original Bretton Woods institutions."})

upsc.append({"q":"Assertion (A): Several analysts have described the AIIB as a potential rival to the IMF, World Bank and Asian Development Bank (ADB).\nReason (R): These existing institutions are viewed by such analysts as being dominated by developed countries, particularly the United States, whereas the AIIB is a China-led initiative aimed at 'scaling up financing for sustainable development'.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — analysts view the AIIB as a rival institution precisely because of perceived US/developed-country dominance of the existing Bretton Woods-era bodies, with China's AIIB positioned as an alternative avenue for infrastructure financing and enhanced voice for emerging economies."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_intl_orgs_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
