import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_disinvestment_psu (Ramesh Singh Ch.9, Industry —
# Disinvestment) — token vs strategic disinvestment, C. Rangarajan Commission,
# National Investment Fund, DIPAM, current policy (2009/2016)
# ==================================================================

upsc.append({"q":"Which one of the following correctly distinguishes 'token disinvestment' from 'strategic disinvestment' in the Indian context?","o":["Token disinvestment involves selling a small minority stake (typically 5-10 per cent) while retaining government control, whereas strategic disinvestment involves divesting a minimum of 51 per cent along with transfer of management control to a strategic partner","Token disinvestment involves full privatisation, while strategic disinvestment retains 100 per cent government ownership","Both terms refer to the same process, differing only in the historical period during which they were used","Token disinvestment applies only to loss-making PSUs, while strategic disinvestment applies only to profit-making PSUs"],"a":0,"e":"Token disinvestment (symbolic, minority stake sale, 5-10% in practice despite a nominal 49% ceiling) preserves government ownership and control, whereas strategic disinvestment requires divesting a minimum 51% stake with actual transfer of management control to a 'strategic partner' possessing international-class sectoral expertise."})

upsc.append({"q":"The C. Rangarajan Commission on Disinvestment of Public Sector Enterprises, which advised the Government of India on disinvestment strategy drawing on international experience, submitted its recommendations in which one of the following years?","o":["1991","1997","1999","2005"],"a":0,"e":"The C. Rangarajan Commission on Disinvestment reported in 1991, the same year India's disinvestment process formally began — distinct from the 1997 Disinvestment Commission (which advised on process details) and the 1999 policy announcement classifying PSEs into 'strategic' and 'non-strategic' categories."})

upsc.append({"q":"As per the Government's March 1999 classification of Public Sector Enterprises (PSEs) into 'strategic' and 'non-strategic' categories, which one of the following sectors was designated as 'strategic' (where majority government holding would be retained)?","o":["Arms and ammunition, atomic energy and related activities, and railways","Hotels and tourism", "Textiles and consumer goods","Fast-moving consumer goods (FMCG) manufacturing"],"a":0,"e":"The 1999 classification designated arms/ammunition, atomic energy-related activities, and railways as 'strategic' sectors warranting continued majority government holding, while non-strategic PSEs would see government stake reduced to 26 per cent or below if necessary — hotels/tourism, textiles, and FMCG were treated as non-strategic areas open to greater disinvestment (indeed, several ITDC/Hotel Corporation of India hotels were among early strategic sales)."})

upsc.append({"q":"Which one of the following was the first Public Sector Undertaking (PSU) to undergo strategic disinvestment (sale of a majority stake with management control transfer) in India?","o":["Modern Food Industries Ltd. (MFIL)","Bharat Aluminium Company (BALCO)","Videsh Sanchar Nigam Ltd. (VSNL)","Hindustan Zinc Ltd. (HZL)"],"a":0,"e":"Modern Food Industries Ltd. (MFIL) was the first PSU strategically disinvested, commencing the shift from token/minority stake sales to full strategic sales — BALCO followed shortly after and drew heavy political and expert criticism, with VSNL, HZL, IPCL, and others following as part of the same wave of about 13 PSU strategic sales."})

upsc.append({"q":"Consider the following statements about India's National Investment Fund (NIF):\n1. It was established as a channel to which disinvestment proceeds automatically flow.\n2. Proceeds credited to the NIF are treated as a capital receipt of the Union Government, similar to other borrowings.\n3. Prior to the NIF's establishment, disinvestment proceeds were primarily used to manage the fiscal deficit in the Union Budget.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 3 are correct. Statement 2 is incorrect — proceeds flowing into the National Investment Fund are explicitly NOT regarded as a capital receipt of the Union Government (unlike the pre-NIF era, when disinvestment proceeds up to around 2005 were largely used to plug the fiscal deficit as capital receipts)."})

upsc.append({"q":"With reference to India's current disinvestment policy framework, which one of the following statements is correct?","o":["The Department of Investment and Public Asset Management (DIPAM) identifies PSUs for minority stake sale in consultation with respective ministries, while strategic disinvestment (announced February 2016) involves NITI Aayog identifying PSUs, with the Core Group of Secretaries on Disinvestment (CGD) facilitating a final decision by the Cabinet Committee on Economic Affairs (CCEA)","DIPAM handles only strategic disinvestment, while NITI Aayog exclusively manages minority stake sales","The Ministry of Disinvestment, established in 1999, continues to independently manage all disinvestment decisions today","CCEA has no role in disinvestment decisions, which rest entirely with the concerned administrative ministry"],"a":0,"e":"Under current policy, DIPAM (Department of Investment and Public Asset Management) handles minority stake sales in consultation with ministries, while the February 2016-announced strategic disinvestment process involves NITI Aayog identifying candidate PSUs, the CGD reviewing NITI Aayog's recommendations, and the CCEA making the final decision — the standalone Ministry of Disinvestment (Arun Shourie's NDA-era ministry) was long since dismantled, with only a Department of Disinvestment (now DIPAM) under the Ministry of Finance continuing the function."})

upsc.append({"q":"As per the minority stake sale policy continuing since November 2009, which one of the following is a genuine feature of India's disinvestment approach?","o":["Listed PSUs are required to comply with a minimum public shareholding norm of 25 per cent, and new PSUs may be listed only if they have earned net profit in three preceding consecutive years","All PSUs, whether profitable or not, must be listed on stock exchanges within one year of the policy's announcement","The minority stake sale policy mandates that the government's shareholding must never fall below 75 per cent in any PSU","Follow-on public offers under this policy are prohibited regardless of capital investment needs"],"a":0,"e":"The November 2009 policy requires listed PSUs to meet a minimum 25% public shareholding norm, with new PSU listings conditioned on three consecutive years of net profit, and allows case-by-case follow-on public offers where capital investment is needed — there is no blanket one-year listing mandate for all PSUs nor an absolute 75% minimum government stake rule."})

upsc.append({"q":"Assertion (A): India's approach to public sector reform through disinvestment has historically been more cautious than the radical privatisation models adopted in some other countries.\nReason (R): Unlike the approach associated with leaders such as Margaret Thatcher in the UK, India did not pursue outright privatisation of commercially viable PSUs alongside closure of unviable ones.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — India's gradualist, phased approach (token disinvestment first, strategic disinvestment later, with continued emphasis on 'public ownership of PSUs as wealth of the nation') stands in explicit contrast to the more radical Thatcher-era UK model of outright privatisation, which the text notes has itself been empirically contested."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_disinvestment_psu_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
