import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_public_finance (Ramesh Singh Ch.18, Public Finance in India)
# Revenue/Effective Revenue/Fiscal/Primary Deficit definitions + numeric
# calculation questions (matching real UPSC 2020/2025 pattern), Plan/Non-Plan
# history (Sukhomoy Chakravarty Committee, Rangarajan Panel, 2017-18 switch)
# ==================================================================

upsc.append({"q":"Which one of the following correctly defines 'Revenue Deficit', a fiscal terminology used in India since 1997-98?","o":["The excess of total revenue expenditure over total revenue receipts of the government","The excess of total capital expenditure over total capital receipts of the government","The excess of total expenditure over total receipts excluding borrowings","The fiscal deficit after excluding interest payment liabilities"],"a":0,"e":"Revenue Deficit is the negative balance when total revenue expenditure exceeds total revenue receipts, indicating the government's Revenue Budget is running in deficit — distinct from fiscal deficit (which covers both revenue and capital sides) and primary deficit (fiscal deficit minus interest payments)."})

upsc.append({"q":"Which one of the following statements about 'Effective Revenue Deficit' (ERD), introduced in the Union Budget 2011-12, is correct?","o":["It is the Revenue Deficit excluding revenue expenditure incurred as Grants for Creation of Capital Assets (GoCA), such as grants under PMGSY or AIBP","It is identical to the conventional Revenue Deficit with no methodological difference","It excludes all grants given to state governments regardless of their purpose","It was discontinued from being reported after the Union Budget 2011-12"],"a":0,"e":"ERD nets out from the conventional Revenue Deficit those revenue expenditures made as Grants for Creation of Capital Assets (GoCA) — such as grants for PMGSY, AIBP, or JNNURM — on the reasoning that though booked as revenue expenditure, these actually contribute to asset creation and are not purely consumptive; despite reduced political emphasis by later governments, the data continues to be released."})

upsc.append({"q":"Consider the following statements about 'Fiscal Deficit' in India:\n1. It is the negative balance between the government's total receipts (revenue plus capital receipts) and total expenditure (revenue plus capital expenditure).\n2. It has been used as a fiscal terminology in India since 1997-98.\n3. It can be expressed either as an absolute currency value or as a percentage of GDP.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — Fiscal Deficit (used since fiscal 1997-98) captures the government's total receipts-expenditure gap and is reported both in absolute and GDP-percentage terms, with the percentage form preferred for domestic and international comparative analysis."})

upsc.append({"q":"'Primary Deficit', a term India began using in fiscal 1997-98 alongside Fiscal Deficit, is best defined as:","o":["Fiscal deficit excluding interest payment liabilities for the year","Fiscal deficit including all interest payment liabilities and past loan principal repayments","Revenue deficit excluding grants for creation of capital assets","The excess of capital expenditure over capital receipts"],"a":0,"e":"Primary Deficit equals Fiscal Deficit minus interest payment liabilities for the year, isolating the deficit that arises purely from current fiscal operations rather than from servicing past debt — considered a handy transparency tool for comparing government expenditure patterns across years."})

upsc.append({"q":"Suppose in a given year, a government's revenue expenditure is Rs. 90,000 crore and its revenue receipts are Rs. 65,000 crore. Its total expenditure (revenue plus capital) is Rs. 1,20,000 crore, and its non-debt capital receipts are Rs. 5,000 crore. Interest payments for the year are Rs. 8,000 crore. Which of the following statements are correct?\n1. The revenue deficit is Rs. 25,000 crore.\n2. The fiscal deficit is Rs. 50,000 crore.\n3. The primary deficit is Rs. 42,000 crore.\nSelect the correct answer using the code below.","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"Revenue deficit = 90,000 - 65,000 = Rs. 25,000 crore (statement 1 correct). Fiscal deficit = Total expenditure - (Revenue receipts + Non-debt capital receipts) = 1,20,000 - (65,000 + 5,000) = Rs. 50,000 crore (statement 2 correct). Primary deficit = Fiscal deficit - Interest payments = 50,000 - 8,000 = Rs. 42,000 crore (statement 3 correct). All three statements are correct."})

upsc.append({"q":"A country's fiscal deficit for a year stands at Rs. 60,000 crore. It received Rs. 12,000 crore through non-debt creating capital receipts, and its interest liabilities for the year are Rs. 9,000 crore. What is its primary deficit?","o":["Rs. 51,000 crore","Rs. 69,000 crore","Rs. 63,000 crore","Rs. 48,000 crore"],"a":0,"e":"Primary Deficit = Fiscal Deficit - Interest Payments = 60,000 - 9,000 = Rs. 51,000 crore. The non-debt capital receipts figure (Rs. 12,000 crore) is already factored into the given fiscal deficit figure and is not separately subtracted again when deriving the primary deficit."})

upsc.append({"q":"Which one of the following statements about the Sukhomoy Chakravarty Committee's contribution to Indian public finance terminology is correct?","o":["It recommended, in its 1985 report on the Review of the Working of the Monetary System, replacing 'developmental' and 'non-developmental' expenditure terminology with 'plan' and 'non-plan' expenditure, adopted from fiscal 1987-88","It recommended replacing 'plan' and 'non-plan' expenditure with 'revenue' and 'capital' expenditure","It first introduced the terms 'fiscal deficit' and 'primary deficit' into Indian budgetary practice","It recommended abolishing the distinction between revenue and capital receipts entirely"],"a":0,"e":"The Sukhomoy Chakravarty Committee (1985) recommended the 'plan'/'non-plan' terminology (replacing 'developmental'/'non-developmental'), adopted from fiscal 1987-88 — it was a LATER panel (the Rangarajan-headed panel, 2011) that recommended replacing plan/non-plan with capital/revenue classification, and fiscal/primary deficit as terms date to 1997-98, unrelated to the Chakravarty Committee."})

upsc.append({"q":"Consider the following statements about the high-power panel headed by Dr. C. Rangarajan (September 2011) on Plan and Non-Plan expenditure classification:\n1. It found the Plan/Non-Plan distinction to be 'dysfunctional', failing to properly capture developmental versus non-developmental dimensions of expenditure.\n2. It recommended redefining expenditure as Capital and Revenue instead, to better link expenditure with measurable outcomes.\n3. It recommended that the Finance Ministry, not the Planning Commission, take charge of firming up annual budgets.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct — the Rangarajan panel found the Plan/Non-Plan split dysfunctional, recommended a shift to Capital/Revenue classification for outcome-linked budgeting, and proposed the Finance Ministry take over annual budget firming while the Planning Commission focused on five-year plan formulation."})

upsc.append({"q":"Which one of the following statements about the actual transition away from India's 'Plan' and 'Non-Plan' expenditure classification is correct?","o":["The Government of India switched from 'plan'/'non-plan' to 'revenue'/'capital' classification of expenditure from fiscal 2017-18, as announced in the Union Budget 2017-18","The switch to revenue/capital classification occurred immediately following the Rangarajan panel's 2011 report","India still officially uses the 'plan'/'non-plan' classification as its primary budgetary framework","The switch was made from 'developmental'/'non-developmental' directly to 'revenue'/'capital', bypassing the 'plan'/'non-plan' phase entirely"],"a":0,"e":"Despite the Rangarajan panel's 2011 recommendation, the actual switch to revenue/capital classification took effect only from fiscal 2017-18 (Union Budget 2017-18) — a roughly six-year gap between recommendation and implementation, and 'plan'/'non-plan' itself had earlier replaced 'developmental'/'non-developmental' from 1987-88 per the Chakravarty Committee, so the transition was NOT direct."})

upsc.append({"q":"Consider the following items with reference to India's capital receipts and capital expenditure:\n1. Loan recovery by the government (principal repayment received from past borrowers)\n2. Interest earned by the government on loans it had extended\n3. External borrowings from the World Bank or IMF\n4. Accruals through Provident Fund, postal deposits, and small savings schemes\nHow many of the above are correctly classified as capital receipts (not revenue receipts)?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Loan recovery (1), external borrowings (3), and PF/postal/small-savings accruals (4) are all capital receipts. Statement 2 is the exception — INTEREST earned on loans extended by the government is classified as a REVENUE receipt, not a capital receipt (only the principal loan recovery counts as capital)."})

upsc.append({"q":"Assertion (A): A budget showing a revenue surplus is not automatically considered ideal fiscal management.\nReason (R): India's revenue-surplus position during the Second Five Year Plan period was criticised by experts, as the high tax rates that helped generate it also fuelled tax evasion, corruption, and black money creation.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — India's Second Plan-era revenue surplus is cited as a cautionary historical example: while revenue surplus can free up funds for productive investment, the specific policy mix (high tax rates) that produced it in that instance had serious adverse side effects, showing surplus alone doesn't guarantee sound fiscal policy."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_public_finance_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
