import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_financial_markets (Ramesh Singh Ch.11, Indian Money Market)
# Fresh territory confirmed via keyword scan (all zero hits): unorganised money market
# categories (chit funds/nidhis, indigenous bankers, money lenders), Vaghul Committee,
# the 8 organised money market instruments (TBs, CD, CP, CB, Call Money, MMMF, Repo/
# Reverse Repo, Cash Management Bills), Urjit Patel Committee term repo
# ==================================================================

upsc.append({"q":"Which committee is credited with laying the blueprint for the development of India's organised money market, leading to the introduction of most of its modern instruments from the mid-1980s onward?","o":["The Vaghul Committee (Working Group on Money Market, 1987)","The Narasimhan Committee","The Urjit Patel Committee","The Chakravarty Committee"],"a":0,"e":"The Vaghul Committee (M. Vaghul's Working Group on Money Market, set up in 1985, report 1987) laid the blueprint for organised money market development in India. The Narasimhan and Urjit Patel Committees dealt with the financial system and monetary policy framework respectively, while the Chakravarty Committee reviewed the working of the monetary system generally."})

upsc.append({"q":"Consider the following categories said to constitute India's unorganised money market:\n1. Unregulated Non-Banking Financial Intermediaries such as chit funds and nidhis\n2. Indigenous bankers such as Gujarati Shroffs, Multani/Shikarpuri Shroffs, Marwari Kayas and Chettiars\n3. Professional and non-professional money lenders\n4. Money Market Mutual Funds regulated jointly by RBI and SEBI\nHow many of the above genuinely belong to the unorganised money market?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are genuine unorganised-market categories. Money Market Mutual Funds (introduced 1992, under SEBI purview since March 2000) are, in fact, part of the ORGANISED money market, not the unorganised segment."})

upsc.append({"q":"Match List-I (Indigenous banker group) with List-II (region of primary operation) and select the correct answer using the code below.\nList-I:\nA. Gujarati Shroffs\nB. Multani or Shikarpuri Shroffs\nC. Marwari Kayas\nD. Chettiars\nList-II:\n1. Chennai and southern port cities\n2. Mainly Gujarat, with limited presence in Mumbai/Kolkata\n3. Mumbai, Kolkata and industrial/trading/port cities\n4. Assam tea gardens and North-Eastern India\nCodes:","o":["A-3, B-4, C-2, D-1","A-3, B-2, C-4, D-1","A-4, B-3, C-2, D-1","A-3, B-4, C-1, D-2"],"a":0,"e":"Gujarati Shroffs (A) operate in Mumbai/Kolkata/industrial-trading-port cities (3); Multani/Shikarpuri Shroffs (B) operate in Assam tea gardens/North-East besides Mumbai/Kolkata (4); Marwari Kayas (C) operate mainly in Gujarat (2); Chettiars (D) operate in Chennai and southern port cities (1)."})

upsc.append({"q":"Which one of the following statements about Treasury Bills (TBs) in India is NOT correct?","o":["All five historical variants of Treasury Bills (14-day intermediate, 14-day auctionable, 91-day, 182-day and 364-day) continue to be issued by the government today","TBs got organised as a money market instrument only in 1986, despite being present since Independence","TBs function as short-term investment avenues for banks and also help meet CRR/SLR requirements","91-day, 182-day and 364-day TBs are the currently issued variants, with the 14-day variants discontinued in 2001"],"a":0,"e":"This statement is incorrect — the two 14-day TB variants (intermediate and auctionable) were discontinued in 2001; only the 91-day, 182-day and 364-day TBs continue to be issued today. The other three statements are accurate."})

upsc.append({"q":"Consider the following statements about the Certificate of Deposit (CD) as a money market instrument:\n1. It was organised in 1989 and is issued by banks to depositors for a period generally less than one year.\n2. Since 1993, select financial institutions such as IFCI, IDBI and the Exim Bank have also been permitted to issue CDs, for maturities of more than one year up to three years.\n3. CDs are non-negotiable and cannot be traded in the secondary money market.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — CDs are explicitly described as negotiable and tradable in the money market, not non-negotiable."})

upsc.append({"q":"Which one of the following conditions must a company satisfy to issue Commercial Paper (CP) in India?","o":["It must be a listed company with working capital of not less than Rs. 5 crore, and must obtain a specified credit rating from an RBI-approved agency such as CRISIL or ICRA","It must be an unlisted private company with no minimum working capital requirement","It must obtain prior approval from NABARD before every issuance","It must be exclusively a Non-Banking Finance Company (NBFC)"],"a":0,"e":"Commercial Paper (organised 1990) requires the issuing company to be listed, hold working capital of at least Rs. 5 crore, and secure a credit rating from an RBI-approved agency (e.g., CRISIL, ICRA) — it is not restricted to NBFCs nor does it require NABARD approval."})

upsc.append({"q":"Which money market instrument, organised in 1990, is issued by All India Financial Institutions (AIFIs), NBFCs, Scheduled Commercial Banks, Merchant Banks, Co-operative Banks and Mutual Funds, and effectively replaced the older 'Bill Market' that had existed since 1952?","o":["Commercial Bill (CB)","Certificate of Deposit (CD)","Cash Management Bill (CMB)","Call Money Market instrument"],"a":0,"e":"The Commercial Bill (CB), organised in 1990, replaced the earlier Bill Market (1952) and can be issued by a wide range of institutions including AIFIs, NBFCs, scheduled commercial banks, merchant banks, co-operative banks and mutual funds."})

upsc.append({"q":"With reference to the Call Money Market (CMM) in India, consider the following statements:\n1. It is essentially an inter-bank market where funds are typically borrowed and lent overnight, though funds may be raised for up to 14 days under 'short notice'.\n2. LIC, GIC, Mutual Funds, IDBI and NABARD are permitted to operate in this market both as borrowers and as lenders.\n3. The State Bank of India functions in this market as the 'lender of intermediate resort', while the RBI functions as the 'lender of last resort'.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1, 2 and 3","1 and 2 only","3 only"],"a":0,"e":"Statements 1 and 3 are correct. Statement 2 is false — LIC, GIC, Mutual Funds, IDBI and NABARD are permitted to operate ONLY as lenders in the call money market, not as borrowers; only scheduled commercial banks and co-operative banks may operate as both borrowers and lenders."})

upsc.append({"q":"In which respective years did the RBI introduce the 'repo' and 'reverse repo' instruments in the Indian money market?","o":["Repo in December 1992; Reverse Repo in November 1996","Repo in November 1996; Reverse Repo in December 1992","Both introduced simultaneously in 1990","Repo in 1986; Reverse Repo in 1989"],"a":0,"e":"The RBI introduced Repo in December 1992 and Reverse Repo about four years later, in November 1996 — these instruments allow banks to borrow from (repo) or lend to (reverse repo) the RBI against government securities and have become key monetary policy tools."})

upsc.append({"q":"Accepting the recommendations of which committee did the RBI, in April 2014, announce the introduction of 'term repo' and 'term reverse repo' to improve interest rate signalling across loan markets?","o":["The Urjit Patel Committee","The Narasimhan Committee","The Vaghul Committee","The Raghuram Rajan Committee on Financial Sector Reforms"],"a":0,"e":"The RBI accepted the Urjit Patel Committee's recommendations and, in its first Bi-monthly Credit & Monetary Policy for 2014-15 (April 2014), announced the introduction of term repo and term reverse repo instruments, aimed at bringing greater stability and better interest-rate signalling."})

upsc.append({"q":"Consider the following statements about Cash Management Bills (CMBs):\n1. They have been issued by the Government of India, in consultation with the RBI, since August 2009 to address temporary cash-flow mismatches.\n2. They are non-standard, discounted instruments issued for maturities of less than 91 days.\n3. Investment in CMBs is NOT considered eligible investment in government securities for banks' SLR purposes.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — CMBs ARE considered an eligible investment in government securities for SLR purposes, sharing the generic character of Treasury Bills (issued at a discount, tradable, and qualifying for ready-forward/repo facility)."})

upsc.append({"q":"Assertion (A): Despite the existence of Treasury Bills, the Government of India found it necessary to introduce a separate Cash Management Bill (CMB) instrument in 2009.\nReason (R): Treasury Bills had been placed under the Ways and Means Advances (WMA) provisions since 1997, which meant they were no longer a discretionary route for the government to meet short-term fund requirements at will.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true, and R correctly explains A: because Treasury Bills were brought under WMA provisions in 1997 (removing government discretion in their use for short-term cash needs), a new discretionary instrument — the Cash Management Bill — was introduced in August 2009 to address temporary cash-flow mismatches."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_financial_markets_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
