import json

upsc = []

# ==================================================================
# NEW UPSC TIER (batch 2): PRE-INDEPENDENCE PLANNING BLUEPRINTS (Ramesh Singh Ch.5)
# Visvesvaraya Plan, FICCI proposal, National Planning Committee, Bombay Plan,
# Gandhian Plan, People's Plan, Sarvodaya Plan — none of this is tested yet
# ==================================================================

upsc.append({"q":"Match List-I (Pre-Independence planning blueprint) with List-II (its chief architect) and select the correct answer using the code below.\nList-I:\nA. The Bombay Plan\nB. The Gandhian Plan\nC. The People's Plan\nD. The Sarvodaya Plan\nList-II:\n1. Jayaprakash Narayan\n2. M.N. Roy\n3. Sriman Narayan Agarwal\n4. A group of eight leading Indian capitalists\nCodes:","o":["A-4, B-3, C-2, D-1","A-4, B-3, C-1, D-2","A-3, B-4, C-2, D-1","A-4, B-2, C-3, D-1"],"a":0,"e":"The correct match is A-4 (Bombay Plan: eight capitalists including Tata, Birla, Thakurdas), B-3 (Gandhian Plan: Sriman Narayan Agarwal, 1944), C-2 (People's Plan: M.N. Roy, 1945, Marxist-inspired), D-1 (Sarvodaya Plan: Jayaprakash Narayan, 1950, inspired by Vinoba Bhave's Sarvodaya concept)."})

upsc.append({"q":"Which one of the following is credited with proposing the very first blueprint for Indian economic planning, in his 1934 book 'The Planned Economy of India'?","o":["M. Visvesvaraya","Jawaharlal Nehru","Subhash Chandra Bose","M.N. Roy"],"a":0,"e":"M. Visvesvaraya, the noted civil engineer and former Dewan of Mysore, is credited with the first blueprint of Indian planning via his 1934 book, envisioning a 'democratic capitalism' model emphasising industrialisation and doubling national income within a decade."})

upsc.append({"q":"Consider the following statements about the FICCI proposal of 1934 for national planning:\n1. It was voiced by N.R. Sarkar, then President of the Federation of Indian Chambers of Commerce and Industry.\n2. It called for a high-powered 'National Planning Commission' to coordinate the whole planning process.\n3. It rejected the idea that the era of undiluted laissez-faire had ended.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 and 3 only"],"a":0,"e":"Statements 1 and 2 are correct; statement 3 is false and reverses the actual position — N.R. Sarkar explicitly proclaimed that the 'days of undiluted laissez-faire were gone forever', not that this idea should be rejected."})

upsc.append({"q":"Which one of the following statements about the National Planning Committee (NPC), set up in October 1938, is correct?","o":["It was established on the initiative of INC President Subhash Chandra Bose, with Jawaharlal Nehru as its chairman, and ultimately produced 29 volumes of recommendations through 29 sub-committees","It was established on Mahatma Gandhi's personal initiative, who fully supported centralised state planning","It produced its final report promptly in 1939, with no wartime interruption","It consisted of only economists and technocrats, excluding trade unionists, socialists or communists"],"a":0,"e":"The NPC was set up on Subhash Chandra Bose's initiative under Nehru's chairmanship, eventually producing 29 volumes via 29 sub-committees (15 core members, 350 total members) — not on Gandhi's initiative (who, along with some Gandhians, actually opposed centralised planning), and its final report was delayed until 1949 due to WWII and the Quit India Movement, with a broad membership including trade unionists, socialists and communists."})

upsc.append({"q":"Which one Gandhian member of the National Planning Committee brought its very first session to an impasse by questioning the Committee's authority to discuss industrialisation plans?","o":["J.C. Kumarappa","Sriman Narayan Agarwal","Acharya Vinoba Bhave","Jayaprakash Narayan"],"a":0,"e":"J.C. Kumarappa, the lone Gandhian among the NPC's 15 core members, questioned the Committee's authority to plan for industrialisation, arguing the Congress's actual priority was to restrict and eliminate modern industrialism — an impasse Nehru later resolved by clarifying that large-scale industry would be promoted only where it did not conflict with cottage industries."})

upsc.append({"q":"Consider the following statements about the Post-War Reconstruction Committee and related bodies set up by the colonial government in the 1940s:\n1. A Consultative Committee of Economists, chaired by Ramaswamy Mudaliar, was formed in 1941 to advise the Post-War Reconstruction Committees.\n2. The Planning and Development Department, created in 1944 under the Viceroy's Executive Council, included Ardeshir Dalal (also linked to the Bombay Plan) as an acting member.\n3. The Advisory Planning Board (1946) recommended creation of a single, compact, cabinet-responsible planning organisation, foreshadowing the 1950 Planning Commission.\n4. All of these wartime and post-war bodies were eventually judged by contemporary commentators to have had substantial, lasting practical impact on policy.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are correct. Statement 4 is false — the Consultative Committee of Economists' suggestions, for instance, are explicitly noted to have had 'negligible practical significance' due to academic biases, showing these bodies had mixed, not uniformly substantial, practical impact."})

upsc.append({"q":"Which one of the following statements about the 'Bombay Plan' (A Plan of Economic Development for India, 1944-45) is NOT correct?","o":["It was formulated exclusively by professional economists with no involvement of Indian industrialists","It allocated around 35 per cent of its total plan outlay to basic/heavy industries","Several of its eight authors, including J.R.D. Tata and G.D. Birla, had also served on National Planning Committee sub-committees","It favoured state ownership or extensive state control over trade, industry and banking"],"a":0,"e":"This statement is incorrect — the Bombay Plan was formulated precisely BY a group of eight leading Indian capitalists/industrialists (Tata, Birla, Thakurdas, and others), not by economists excluding industrialists. The other three statements are correct."})

upsc.append({"q":"Which of the following areas of agreement were common to BOTH the National Planning Committee and the Bombay Plan?\n1. Abolition of intermediaries in land tenure (zamindari abolition) and guaranteed minimum agricultural prices.\n2. Emphasis on heavy capital goods and basic industries alongside promotion of small-scale/cottage industries.\n3. An active state role in the economy through ownership or extensive control over trade, industry and banking.\n4. Complete rejection of any social welfare measures as fiscally unsustainable.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect genuine areas of agreement between the two plans. Statement 4 is false — both plans actually FAVOURED large-scale social welfare measures (minimum wage, social insurance, free education, subsidised utilities), not their rejection."})

upsc.append({"q":"Which one of the following statements about the Gandhian Plan (1944) is correct?","o":["Formulated by Sriman Narayan Agarwal, it emphasised agriculture and a decentralised economic structure of 'self-contained villages', diverging from the NPC/Bombay Plan's emphasis on heavy, large-scale industry","It was formulated by Mahatma Gandhi himself as a formal economic policy document","It fully endorsed the National Planning Committee's emphasis on centralised state planning and heavy industrialisation","It proposed doubling national income within a decade through rapid industrialisation, similar to the Visvesvaraya Plan"],"a":0,"e":"The Gandhian Plan (Sriman Narayan Agarwal, 1944) emphasised agriculture and decentralised, self-contained villages, explicitly diverging from the NPC and Bombay Plan's centralised, industrialisation-heavy approach — it was not authored by Gandhi personally, did not endorse centralised planning, and did not focus on doubling national income via rapid industrialisation (that was Visvesvaraya's idea)."})

upsc.append({"q":"Assertion (A): The 'People's Plan' (1945) is often credited by economists with having introduced socialist leanings into Indian planning thought.\nReason (R): The People's Plan was formulated by M.N. Roy, based on Marxist socialism, advocating that people be provided with the 'basic necessities of life'.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are accurate, and R directly explains A — M.N. Roy's explicitly Marxist-socialist People's Plan (1945) is the historical root economists cite for socialist leanings in Indian planning, with echoes even traced to later slogans like 'economic reforms with a human face' (1991) and subsequent Common Minimum Programmes."})

upsc.append({"q":"Which one of the following statements about the Sarvodaya Plan (January 1950) is correct?","o":["Formulated by Jayaprakash Narayan, it drew inspiration from Gandhian constructive work, trusteeship, and Acharya Vinoba Bhave's Sarvodaya concept, emphasising agriculture, self-reliant villages and decentralised participatory planning","It was formulated by Acharya Vinoba Bhave himself as a direct alternative to the Five Year Plans","It emphasised heavy industrialisation and centralised planning, similar to the Bombay Plan","It was fully adopted, without modification, as India's First Five Year Plan"],"a":0,"e":"The Sarvodaya Plan (Jayaprakash Narayan, January 1950) drew on Gandhian ideas and Vinoba Bhave's Sarvodaya concept, favouring agriculture, small-scale industry, self-reliance and decentralised planning — it was not authored by Vinoba Bhave himself, did not favour heavy industry/centralisation, and was only partially (not fully) reflected in subsequent Five Year Plans."})

upsc.append({"q":"Which one of the following statements about Jayaprakash Narayan's later relationship with Indian planning practice is correct?","o":["By the early 1960s he had become highly critical of Indian planning's increasingly centralising tendency and the dilution of people's participation, motivating a 1961 committee bearing his name","He remained an uncritical supporter of centralised Five Year Plan-based planning throughout his life","He was appointed as the first Deputy Chairman of the Planning Commission in recognition of his Sarvodaya Plan","His 1961 committee endorsed further centralisation of planning power away from Panchayati Raj institutions"],"a":0,"e":"By the early 1960s, Jayaprakash Narayan grew critical of planning's centralising tendency and the erosion of people's participation, leading to the Jayaprakash Narayan Committee (1961), which favoured Panchayati Raj-based decentralisation — not further centralisation, and he was never the Planning Commission's Deputy Chairman."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_planning_niti_upsc2.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
