import json

upsc = []

# ==================================================================
# NEW UPSC TIER: eco_human_development (Ramesh Singh Ch.20, Human Development
# in India) — HDR 2016/HDI, gender gaps, Accessible India Campaign, subsidy
# inequality
# ==================================================================

upsc.append({"q":"With reference to the Human Development Report (HDR) 2016 of the UNDP, consider the following statements:\n1. India was ranked 131st out of 188 countries, a fall of one rank from HDR 2015.\n2. The Human Development Index (HDI) measures progress across three basic dimensions — standard of living, life expectancy, and knowledge.\n3. India's HDI value placed it in the 'high human development' category, ahead of both Sri Lanka and the Maldives.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is incorrect — India's HDI value of 0.624 placed it in the 'medium human development' category, and India was ranked THIRD among SAARC countries, BEHIND both Sri Lanka (73rd) and the Maldives (105th), which featured in the 'high human development' category."})

upsc.append({"q":"As per HDR 2016, which one of the following correctly describes India's position relative to other country groupings?","o":["India's HDI ranking was the lowest among the BRICS countries, though it ranked third among SAARC countries","India's HDI ranking was the highest among the BRICS countries","India ranked first among SAARC countries, ahead of Sri Lanka and the Maldives","India's HDI ranking was identical to that of Norway, the world's top-ranked country"],"a":0,"e":"HDR 2016 placed India lowest among the BRICS nations on HDI, while it ranked third among SAARC countries (behind Sri Lanka and the Maldives) — Norway (0.949) was the world's top-ranked country, far above India's 0.624."})

upsc.append({"q":"Consider the following findings attributed to HDR 2016 regarding India:\n1. India's public health expenditure stood at just 1.4 per cent of GDP.\n2. Between ages 1-5, girls in India had a 30-50 per cent greater chance of dying than boys.\n3. The report found that untargeted subsidies on items like cooking gas, railways, power, and gold disproportionately benefited the poorest 20 per cent of India's population.\nHow many of the statements given above are correct?","o":["Only two","All three","Only one","None"],"a":0,"e":"Statements 1 and 2 are correct per HDR 2016. Statement 3 REVERSES the actual finding — the report found that the RICHEST (not poorest) 20 per cent of India's population enjoyed disproportionate benefits (about $16 billion) from untargeted subsidies on cooking gas, railways, power, aviation fuel, gold, and kerosene."})

upsc.append({"q":"HDR 2016 credited India with certain positive institutional developments despite its 'medium human development' ranking. Which one of the following was NOT among the specific measures praised in the report?","o":["Universal Basic Income implementation nationwide","The reservation policy, which raised the share of Dalits in civil services from 2 per cent (1965) to 11 per cent (2001)","The Rural Employment Guarantee scheme (MGNREGA)","The Right to Information Act and the Right to Education Act"],"a":0,"e":"HDR 2016 praised India's reservation policy (Dalit civil service share rising from 2% to 11% between 1965-2001), MGNREGA, RTI Act, National Food Security scheme, and RTE Act, along with the Mazdoor Kisan Shakti Sanghatan's social audit initiatives — Universal Basic Income was, at that time, still only a PROPOSAL under discussion (in the Economic Survey 2016-17), not an implemented, praise-worthy measure."})

upsc.append({"q":"With reference to India's Accessible India Campaign (Sugamya Bharat Abhiyan), consider the following statements:\n1. It was launched by the Department of Empowerment of Persons with Disabilities (DEPwD) with a focus on three verticals — Built Environment, Public Transportation, and ICT.\n2. Persons with disabilities constituted about 2.2 per cent of India's population as per Census 2011.\n3. The Rights of Persons with Disabilities Act, 2016 increased the reservation for persons with disabilities in government vacancies from 3 per cent to 4 per cent.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — the DEPwD-launched campaign's three verticals, the 2.2% disability share per Census 2011, and the Rights of Persons with Disabilities Act, 2016's increase in reservation from 3% to 4% are all accurately stated."})

upsc.append({"q":"Which one of the following best captures the conceptual shift in development thinking, as articulated by economists like Mahbub ul Haq and Amartya Sen and reflected in India's human development approach?","o":["Development should be measured not merely by income/growth figures but by the enlargement of 'people's choices' — access to knowledge, health, secure livelihoods, and political/cultural freedoms","Development is best measured exclusively through GDP growth rates, with all other indicators being secondary or irrelevant","Human development indices deliberately exclude health and education, focusing only on per capita income","The idea of 'human development' was first articulated by the World Bank, not the UNDP"],"a":0,"e":"Mahbub ul Haq (founding editor of UNDP's Human Development Report) and Amartya Sen's 'Development as Freedom' framework emphasise that development's purpose is to enlarge people's choices across income AND non-income dimensions (knowledge, health, freedoms) — the human development concept was articulated by the UNDP (from 1990), not the World Bank, and explicitly moves beyond a GDP-only view."})

upsc.append({"q":"Assertion (A): India's economically active population (15-59 years) share has been steadily increasing, positioning the country to potentially benefit from a 'demographic dividend'.\nReason (R): As per Sample Registration System (SRS) data, this proportion increased from 57.7 per cent to 63.3 per cent between 1991 and 2013, but realising the dividend requires matching investment in social infrastructure like health and education.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R explains A — the SRS-documented rise in the working-age population share (57.7% to 63.3%, 1991-2013) creates the POTENTIAL for a demographic dividend, but the text explicitly cautions that this potential can only be realised with matching investments in social infrastructure (health, education, skilling) for this young population."})

upsc.append({"q":"With reference to the JAM trinity and its role in social sector delivery, which one of the following is correct?","o":["JAM stands for Jan Dhan-Aadhaar-Mobile, a technology-enabled solution intended to strengthen Direct Benefit Transfers (DBT) by improving inclusion, reducing fake accounts, and preventing leakages","JAM stands for Joint Assessment Mechanism, a World Bank tool for evaluating India's social sector spending","JAM is a scheme exclusively for agricultural subsidy delivery, unrelated to broader social sector transfers","JAM was introduced prior to the launch of the Jan Dhan Yojana and served as its precursor"],"a":0,"e":"JAM (Jan Dhan-Aadhaar-Mobile number trinity) is a technology-enabled DBT delivery solution aimed at improving inclusion of the needy, excluding fake/duplicate accounts, and preventing corruption and leakages in the social sector delivery system — it followed, and built upon, the Jan Dhan Yojana rather than preceding it."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_human_development_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
