import json

industry = []
infra = []

# ==================================================================
# NEW UPSC TIER: eco_industry_policy (Ramesh Singh Ch.9, industry-policy portions)
# Fresh territory confirmed via keyword scan (all zero/near-zero hits in existing bank):
# MRTP Act mechanics, FEMA vs FERA, IDR Act licensing, industrial policy resolutions,
# MSME schemes (UAM, PMEGP, CGTMSE, SFURTI, cluster dev), sector policies
# (aluminium, apparel/footwear/leather, steel safeguard)
# ==================================================================

industry.append({"q":"Consider the following statements about the Monopolies and Restrictive Trade Practices (MRTP) Act:\n1. It was enacted to regulate the trading and pricing practices of large industrial houses.\n2. It empowered the government to give discretionary licensing decisions to check concentration of economic power.\n3. It was eventually replaced by the Competition Act, 2002 in the post-liberalisation era.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct. The MRTP Act regulated trading/pricing practices of large houses and underpinned discretionary industrial licensing to check concentration of economic power; it was later superseded by the more competition-friendly Competition Act, 2002 as India moved away from licence-permit-raj controls."})

industry.append({"q":"Which one of the following legislations was enacted to replace the Foreign Exchange Regulation Act (FERA) with a framework more compatible with the post-1991 liberalised economy, easing restrictions on foreign exchange transactions?","o":["Foreign Exchange Management Act (FEMA)","Industries (Development and Regulation) Act","Competition Act, 2002","Special Economic Zones Act"],"a":0,"e":"FEMA replaced the more restrictive FERA, reflecting India's shift towards a liberalised, market-friendly foreign exchange regime consistent with the 1991 economic reforms, easing the earlier restrictive control-oriented regime."})

industry.append({"q":"Assertion (A): The Industries (Development and Regulation) Act empowered the government with a licensing regime that classified industries under different schedules.\nReason (R): Industrial licensing under the IDR Act was primarily intended to curb concentration of economic power and channel investment according to plan priorities.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R correctly explains A: the IDR Act's licensing regime, sorting industries into schedules, was designed to steer private investment towards plan priorities and prevent excessive concentration of economic power in a few industrial houses."})

industry.append({"q":"Which one of the following statements about District Industries Centres (DICs) is correct?","o":["They were established to provide integrated administrative support at the district level for the promotion of small and village industries","They are apex financial institutions responsible for setting all-India industrial licensing policy","They were set up exclusively to manage disinvestment of central public sector enterprises","They regulate foreign direct investment approvals at the state level"],"a":0,"e":"District Industries Centres (DICs) were established to provide single-window, integrated administrative and promotional support at the district level specifically for small-scale and village industries, distinct from licensing, disinvestment, or FDI-approval functions."})

industry.append({"q":"The Micro, Small and Medium Enterprises (MSME) sector's classification into micro, small and medium categories, based on investment in plant and machinery, was established under which one of the following?","o":["The MSMED Act, 2006","The Companies Act, 2013","The Industries (Development and Regulation) Act, 1951","The Competition Act, 2002"],"a":0,"e":"The Micro, Small and Medium Enterprises Development (MSMED) Act, 2006 established the investment-based classification of enterprises into micro, small, and medium categories for both manufacturing and service enterprises."})

industry.append({"q":"Match List-I (MSME government scheme) with List-II (its primary purpose) and select the correct answer using the code below.\nList-I:\nA. PMEGP\nB. CGTMSE\nC. SFURTI\nD. UAM (Udyog Aadhaar Memorandum)\nList-II:\n1. Simplified online registration via a unique Udyog Aadhaar Number\n2. Credit guarantee support for collateral-free loans to micro and small enterprises\n3. Regeneration and cluster development of traditional industries\n4. Generating self-employment through new micro-enterprise establishment\nCodes:","o":["A-4, B-2, C-3, D-1","A-4, B-3, C-2, D-1","A-1, B-2, C-3, D-4","A-4, B-2, C-1, D-3"],"a":0,"e":"PMEGP (A) generates self-employment via new micro-enterprises (4); CGTMSE (B) provides collateral-free credit guarantee (2); SFURTI (C) supports regeneration of traditional industry clusters (3); UAM (D) is the simplified Udyog Aadhaar online registration scheme (1)."})

industry.append({"q":"The Udyog Aadhaar Memorandum (UAM) scheme, notified in September 2015 to ease MSME registration, is best described as which one of the following?","o":["A simplified, self-declared online entrepreneurs' memorandum replacing an earlier complex registration procedure","A subsidy scheme providing direct cash transfers to micro enterprises","A credit guarantee fund for technology upgradation loans","A trade agreement facilitating MSME exports to ASEAN countries"],"a":0,"e":"UAM allows entrepreneurs to simply file an online memorandum to obtain a unique Udyog Aadhaar Number, replacing the earlier cumbersome, multi-step registration process — a pure ease-of-doing-business reform, not a subsidy, credit, or trade instrument."})

industry.append({"q":"Consider the following statements about the sector-specific industrial challenges discussed in the context of India's manufacturing sector:\n1. India is the second largest producer of aluminium in the world, after China.\n2. The government imposed a safeguard duty on steel imports in response to a global glut caused by overcapacity, especially from China.\n3. Indian leather exports face tariff disadvantages relative to competitors like Bangladesh and Vietnam that enjoy preferential zero-tariff access in certain developed-country markets.\nHow many of the statements given above are correct?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three statements are correct: India ranks second globally in aluminium production (after China); the government imposed steel safeguard duties amid a global supply glut; and Indian leather exports face a competitive tariff disadvantage since Bangladesh (LDC status) and Vietnam enjoy zero-tariff access to markets like the EU, unlike India."})

industry.append({"q":"Which one of the following industries is highlighted for its potential to drive 'social transformation through women empowerment' and large-scale employment generation, alongside challenges from tariff disadvantages faced against competitors like Bangladesh and Vietnam?","o":["Apparel and footwear","Aluminium","Steel","Cement"],"a":0,"e":"The apparel and footwear sectors are specifically highlighted for their large employment generation potential (especially for women) and the 'historic opportunity' they present for India, while also facing tariff disadvantages against LDC/preferential-access competitors like Bangladesh and Vietnam."})

# ==================================================================
# NEW UPSC TIER: eco_infrastructure (Ramesh Singh Ch.9, infrastructure-financing portion)
# Fresh territory: social-sector infrastructure schemes funded via National Investment Fund
# income/proceeds — JNNURM, AIBP, RGGVY, Indira Awas Yojana, NREGS, and the 2013 NIF restructuring
# ==================================================================

infra.append({"q":"Consider the following schemes that were funded from the income generated by the National Investment Fund (NIF), as originally structured:\n1. Jawaharlal Nehru National Urban Renewal Mission (JNNURM)\n2. Accelerated Irrigation Benefits Programme (AIBP)\n3. Rajiv Gandhi Gramin Vidyutikaran Yojana (RGGVY)\n4. Pradhan Mantri Gram Sadak Yojana (PMGSY)\nHow many of the above were among the originally listed NIF-funded social sector schemes?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"JNNURM, AIBP and RGGVY (along with the Accelerated Power Development and Reform Programme, Indira Awas Yojana, and NREGS) were the schemes originally funded from NIF income. PMGSY (rural roads) was not among this specific originally listed set."})

infra.append({"q":"With reference to the restructuring of the National Investment Fund (NIF) over time, consider the following statements:\n1. In November 2009, a one-time exemption allowed disinvestment proceeds themselves (not just investment income) to be used for social sector schemes, in response to the global slowdown and a severe drought.\n2. Since the January 2013 restructuring, disinvestment proceeds are credited to the Public Account under the NIF head and used for purposes including recapitalisation of public sector banks and insurance companies.\n3. Under the 2013 policy, NIF funds cannot be used for equity infusion in metro rail projects.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","3 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is false — the 2013 NIF utilisation list explicitly includes equity infusion in various metro projects as one of its approved purposes, alongside recapitalisation of PSU banks/insurers, investment in RRBs/IIFCL/NABARD/Exim Bank, and capital expenditure in Indian Railways."})

infra.append({"q":"Under the January 2013 restructuring of the National Investment Fund, which of the following are listed as approved purposes for its utilisation?\n1. Subscribing to rights-issue shares of CPSEs (including public sector banks and insurers) to maintain at least 51 per cent government ownership\n2. Direct cash transfer of NIF proceeds to individual farmers as income support\n3. Investment towards capital expenditure of Indian Railways\n4. Investment in Bhartiya Nabhikiya Vidyut Nigam Limited and Uranium Corporation of India Ltd.\nSelect the correct answer using the code below.","o":["1, 3 and 4 only","All four","1 and 2 only","2, 3 and 4 only"],"a":0,"e":"Statements 1, 3 and 4 correctly reflect the 2013 NIF utilisation purposes. Statement 2 is fabricated — NIF funds were never designated for direct cash transfers to farmers; its purposes are focused on CPSE equity, PSU bank/insurer recapitalisation, railways, nuclear/uranium PSUs, and similar capital investments."})

infra.append({"q":"Which one of the following statements about the purpose behind the 2009 one-time exemption in NIF policy is correct?","o":["It was necessitated by the global economic slowdown of 2008-09 combined with a severe drought in 2009-10, prompting use of actual disinvestment proceeds (not merely their investment income) for social sector schemes","It was necessitated by a stock market boom that generated surplus disinvestment income requiring urgent deployment","It permanently abolished the National Investment Fund mechanism","It redirected NIF proceeds exclusively towards defence sector capital expenditure"],"a":0,"e":"The 2009 exemption was a response to twin shocks — the 2008-09 global slowdown and the 2009-10 drought — allowing disinvestment PROCEEDS themselves (rather than just income from investing the NIF corpus) to fund social sector schemes for that difficult period; it neither abolished NIF nor targeted defence spending."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

for name, arr in [("eco_industry_policy", industry), ("eco_infrastructure", infra)]:
    texts = [q["q"] for q in arr]
    print(name, "Total:", len(arr), "| unique:", len(set(texts)))
    for q in arr:
        assert len(q["o"]) == 4, ("option count", name, q["q"], len(q["o"]))
        assert 0 <= q["a"] <= 3, (name, q["q"])
        assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", name, q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_industry_policy_upsc.json", "w") as f:
    json.dump(industry, f, indent=2, ensure_ascii=False)
with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_infrastructure_upsc.json", "w") as f:
    json.dump(infra, f, indent=2, ensure_ascii=False)

print("Saved.")
