import json

upsc = []

# ==================================================================
# NEW UPSC TIER: ECONOMIC PLANNING / PLANNING IN INDIA (Ramesh Singh Ch.4 + Ch.5)
# Focused on planning THEORY/global origins (Ch.4), distinct from eco_planning_niti's
# existing India-specific Five-Year-Plan-by-Plan coverage
# ==================================================================

upsc.append({"q":"Which economist is widely regarded as having given the most accepted definition of economic planning — 'the making of major economic decisions... by the conscious decision of a determinate authority, on the basis of a comprehensive survey of the economic system as a whole'?","o":["H. D. Dickinson","Jan Tinbergen","Gunnar Myrdal","John Maynard Keynes"],"a":0,"e":"H. D. Dickinson's definition — emphasising conscious decision-making by a determinate authority based on a comprehensive survey of the economy — is widely regarded among economists as the most accepted definition of economic planning."})

upsc.append({"q":"Which body, set up in 1938 by the Indian National Congress, first attempted to define planning in India, describing it as encompassing not just economics but 'cultural and spiritual values, and the human side of life'?","o":["The National Planning Committee","The Planning Commission","The National Development Council","NITI Aayog"],"a":0,"e":"The National Planning Committee (1938, INC), whose final report was published only in 1949, offered arguably the broadest definition of planning, explicitly including cultural and spiritual values alongside economic coordination."})

upsc.append({"q":"Which of the following was the first country to use economic planning as a tool of development policy, doing so at the regional (not national) level through the Tennessee Valley Authority in 1916?","o":["The United States of America","The Soviet Union","France","The United Kingdom"],"a":0,"e":"The USA pioneered planning at the regional level via the Tennessee Valley Authority (1916), covering flood control, electricity and related development across parts of seven states — though it never adopted formal national-level planning."})

upsc.append({"q":"India's Damodar Valley Corporation (1948), inspired by the American Tennessee Valley Authority model, is an example of which type of planning?","o":["Regional planning","National imperative planning","Indicative planning at the national level","Normative planning"],"a":0,"e":"The Damodar Valley Corporation (1948) was explicitly modelled on the USA's Tennessee Valley Authority, making it an example of regional (not national, imperative, or normative) planning."})

upsc.append({"q":"Which one of the following statements about the origin of national-level economic planning is correct?","o":["The world's first official national planning experiment is rooted in the Bolshevik Revolution (1917), with Joseph Stalin announcing central planning (Gosplan) and the first Five Year Plan (1928-33) for the Soviet Union","National planning was first adopted at the global level by the United States through the Tennessee Valley Authority in 1916","France was the first country in the world to adopt national-level economic planning, doing so in 1928","China was the first communist country to adopt national planning, preceding the Soviet Union by two decades"],"a":0,"e":"The Soviet Union, following the 1917 Bolshevik Revolution, conducted the world's first official national planning experiment under Stalin's Gosplan system (announced 1928, first Five Year Plan 1928-33) — not the USA (regional only), France (which adopted planning later, in the 1940s), or China (which adopted planning only from 1949)."})

upsc.append({"q":"Which one of the following correctly distinguishes 'imperative planning' from 'indicative planning'?","o":["Imperative planning (followed by state/command economies) sets numerical targets achieved through centralised state ownership with almost no market role, while indicative planning (followed by mixed economies) works through the market/price system rather than replacing it","Imperative planning is followed exclusively by mixed economies, while indicative planning is followed exclusively by command economies","Both imperative and indicative planning eliminate any role for the price mechanism","Indicative planning involves complete state ownership of all resources, including labour"],"a":0,"e":"Imperative (directive/target) planning, used by state economies, relies on centralised ownership and target-setting with minimal market role; indicative planning, used by mixed economies, works alongside and through the market/price mechanism rather than replacing it — the reverse of the other incorrect pairings."})

upsc.append({"q":"Consider the following statements about France's 'Monnet Plan' (1947):\n1. It is regarded as a classic example of indicative planning.\n2. It involved near-imperative, state-monopoly planning specifically in eight selected 'basic sector' industries that had been nationalised by 1944.\n3. India's own emphasis on state-monopolised core/basic industries shows a French planning influence.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — the Monnet Plan is the archetypal indicative planning example, yet incorporated near-imperative state-monopoly control over eight nationalised basic industries, an approach the text explicitly notes influenced India's own core/basic industries policy."})

upsc.append({"q":"Which one of the following statements about the United Kingdom's brief experiment with indicative planning is correct?","o":["The UK commenced indicative planning with its 'National Plan' in 1965 but abandoned it in 1966 after a Balance of Payments crisis triggered a deflationary policy package","The UK's National Plan (1965) continues to operate to this day, unchanged","The UK was the first country in the world to adopt national indicative planning, preceding France","The UK adopted imperative (not indicative) planning through its National Plan"],"a":0,"e":"The UK's National Plan (1965) was abandoned within a year (1966) after a Balance of Payments crisis forced a deflationary policy response — it was indicative (not imperative) planning, and came after France's earlier Monnet Plan (1947), not before it."})

upsc.append({"q":"Which one of the following statements about Oskar Lange's advocacy of 'market socialism' is correct?","o":["Lange, a Polish economist who later served as Chairman of the Polish State Economic Council, coined 'market socialism' in the 1950s, but his ideas were rejected as blasphemous within the state-economy bloc at the time","Lange's market socialism proposal was immediately and enthusiastically adopted by the Soviet Union in the 1950s","Lange proposed market socialism while serving as a Chinese Communist Party official","Market socialism, as coined by Lange, called for the complete abolition of any state role in the economy"],"a":0,"e":"Oskar Lange, while heading Poland's State Economic Council, coined 'market socialism' in the 1950s, an idea considered heretical within the socialist bloc at the time (he reportedly feared arrest) — not one adopted by the USSR, proposed from within China, or calling for total state withdrawal."})

upsc.append({"q":"Which one of the following statements about the shift from 'systems planning' to 'normative planning' in Indian policy thinking is correct?","o":["The Economic Survey 2010-11 is considered probably the first Government of India document to explicitly advocate a normative approach to planning, emphasising the need to connect programmes with local customs, traditions and ethos","Normative planning was formally adopted by India's First Five Year Plan (1951) itself","Systems planning gives greater emphasis to socio-institutional factors like caste, religion and region compared to normative planning","Normative planning is considered ideally suited to societies with very high degrees of social diversity, unlike India's conditions"],"a":0,"e":"The Economic Survey 2010-11 is credited as probably the first Indian government document to advocate normative planning; the text explicitly notes normative planning (which DOES emphasise socio-institutional factors, unlike 'systems planning' which downplays them) is naturally NOT well-suited to highly diverse societies like India, though India has still moved toward it, e.g., through NITI Aayog's holistic approach."})

upsc.append({"q":"Consider the following statements regarding examples of 'normative' or social-norm-influenced policymaking cited in the Economic Survey 2015-16:\n1. Persuading the affluent to voluntarily give up subsidies they do not need.\n2. Reducing social prejudices against girls.\n3. Educating people about the health externalities of open defecation.\n4. Mandating compulsory military conscription to instil civic discipline.\nHow many of the statements given above are genuine examples cited?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 are genuine examples cited in the Economic Survey 2015-16 of behavioural/normative policy interventions. Statement 4 (military conscription) is not among the cited examples and is unrelated to the social-norm-influencing interventions discussed."})

upsc.append({"q":"Which one of the following statements about the classification of planning into 'sectoral' and 'spatial' types, and India's own planning approach, is correct?","o":["Indian planning has been essentially single-level with a greater historical reliance on the sectoral approach, though multi-level regional and normative dimensions have been increasingly emphasised since the early 1990s","Indian planning has always relied primarily on spatial planning, with sectoral planning introduced only after 2015","Sectoral planning refers to development viewed within a geographic/spatial framework, while spatial planning refers to a focus on economic sectors like agriculture or industry","India abandoned sectoral planning completely upon the creation of NITI Aayog in 2015"],"a":0,"e":"The text explicitly notes Indian planning has been predominantly sectoral and single-level in its historical approach, with regional/spatial and normative dimensions gaining emphasis only since the early 1990s — not a spatial-first history, a reversed sectoral/spatial definition, or complete sectoral abandonment post-2015."})

upsc.append({"q":"Assertion (A): India's planning process, especially after 1991, has moved decisively away from imperative planning toward indicative planning.\nReason (R): Since virtually all economies today are mixed economies, and the price mechanism plays a central coordinating role, only indicative planning remains a realistic model of national planning.\nWhich one of the following is correct?","o":["Both A and R are true, and R is a correct explanation of A","Both A and R are true, but R is not a correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are accurate, and R correctly explains A — the text notes that with the global dominance of mixed economies (post the Washington Consensus, WTO, and Santiago/New Consensus), imperative planning has effectively become obsolete, leaving indicative planning as the only viable model, which is precisely why India's heavy pre-1991 imperative bias was corrected only after the 1991 reforms."})

upsc.append({"q":"All of the following are correctly identified as basic features of 'imperative planning' as followed by state/command economies, EXCEPT:","o":["Extensive private-sector participation is actively encouraged alongside state enterprises","Numerical/quantitative targets of growth and development are centrally set by the plan","The state controls ownership rights over resources to help realise planned targets","There is almost no role for the market or the price mechanism in resource allocation"],"a":0,"e":"Private-sector participation is explicitly ABSENT (not encouraged) under imperative planning — only the state plays an economic role, unlike the other three genuinely correct features (numerical targets, state ownership control, and minimal market role) of imperative/command planning."})

upsc.append({"q":"Consider the following statements about the global spread and eventual decline of imperative (command) planning:\n1. Deng Xiaoping's 'open door policy' (1985) was an initiative in the direction of market socialism under continued communist political control in China.\n2. Mikhail Gorbachev's perestroika and glasnost (from 1985) were reform processes aimed at rescuing the failing Soviet state economy.\n3. Other East European command economies also began similar market-oriented reforms from 1989 onward.\n4. No country following imperative planning has transitioned toward market-oriented reform since the 1980s.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1, 2, 3 and 4","2 and 3 only","1 and 4 only"],"a":0,"e":"Statements 1, 2 and 3 accurately describe the sequence of command-economy reforms (China 1985, USSR from 1985, other East European states from 1989). Statement 4 is false and contradicts this entire sequence — since the late 1980s, essentially the whole world of state economies has moved toward market-oriented reform, and no country has continued following pure imperative planning since."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_planning_niti_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
