import json

upsc = []

# ==================================================================
# NEW UPSC TIER: INFLATION & BUSINESS CYCLE (Ramesh Singh Ch.7)
# Avoiding overlap with existing basic/intermediate/advanced (demand-pull/cost-push,
# WPI/CPI mechanics, GDP deflator, flexible inflation targeting framework basics)
# ==================================================================

# ---------------- Section A: Inflation-specific terms ----------------

upsc.append({"q":"Which one of the following pairs of economists is correctly associated with challenging the long-term validity of the Phillips Curve's inflation-unemployment trade-off in the early 1970s?","o":["Milton Friedman and Edmund Phelps","John Maynard Keynes and Alban William Phillips","Joseph Stiglitz and Paul Krugman","Adam Smith and David Ricardo"],"a":0,"e":"Milton Friedman and Edmund Phelps argued in the early 1970s that the inflation-unemployment trade-off was only short-term, since expected higher inflation would eventually push unemployment back to its 'natural rate' — giving rise to the concept of NAIRU."})

upsc.append({"q":"The 'Non-Accelerating Inflation Rate of Unemployment' (NAIRU) refers to:","o":["The rate of unemployment consistent with a constant (non-accelerating) rate of inflation, below which further reduction would trigger rising inflation","The rate of unemployment at which inflation is guaranteed to fall to zero","A fixed unemployment rate mandated by law in inflation-targeting countries","The unemployment rate that existed during the Great Depression of 1929"],"a":0,"e":"NAIRU is the unemployment rate at which upward and downward pressures on wages and prices neutralise each other, so inflation neither accelerates nor decelerates — pushing unemployment below this rate causes inflation to rise, per Friedman and Phelps's critique of the Phillips Curve."})

upsc.append({"q":"Which one of the following countries was the first in the world to adopt formal inflation targeting, doing so in 1989?","o":["New Zealand","United States","United Kingdom","Germany"],"a":0,"e":"New Zealand pioneered formal inflation targeting in 1989, initially with a target range of 0-2 per cent (with provision to remove the central bank governor if inflation crossed 2 per cent), later revised to 1-3 per cent."})

upsc.append({"q":"Which committee's recommendations, submitted in early 2014, are considered to have directly preceded India's formal Agreement on Monetary Policy Framework (February 2015)?","o":["The Urjit Patel Committee","The Narasimham Committee","The Rangarajan Committee","The Tarapore Committee"],"a":0,"e":"The Urjit Patel Committee, set up by the RBI on monetary policy, gave advice on inflation targeting by early 2014, which the 2015 Agreement on Monetary Policy Framework is seen as a direct follow-up to."})

upsc.append({"q":"'Skewflation', a term that appeared in the Economic Survey 2009-10, refers to:","o":["A sustained price rise confined to one or a small group of commodities over an extended period, distinct from both generalised inflation and a brief relative price spike","A sustained, across-the-board increase in the general price level of all goods and services","A short-term, one-time relative price increase in a single commodity, lasting only a few days","A situation where prices fall uniformly across all commodity groups"],"a":0,"e":"Skewflation describes a third category of price behaviour — a sustained rise confined to one or a small group of commodities (India's 2009-10 food price surge, with WPI overall inflation remaining much lower) — distinct from both across-the-board 'inflation' and a brief episodic 'relative price increase'."})

upsc.append({"q":"'Inflation tax', also known by which other term, refers to the situation where a government effectively gains at the cost of currency holders through deficit-financed money creation?","o":["Seigniorage","Bracket creep","Shoe leather cost","Inflation premium"],"a":0,"e":"'Inflation tax' is also known as seigniorage — the implicit gain a government makes by printing/circulating currency (deficit financing), effectively taxing money-holders through currency depreciation."})

upsc.append({"q":"Which one of the following statements about 'bracket creep', a tax-related distortion caused by inflation, is correct?","o":["It refers to inflation pushing a tax-payer's nominal income into higher official tax brackets even though their real purchasing power has not correspondingly increased","It refers to a reduction in tax rates announced specifically to counter inflation","It describes governments reducing tax brackets during periods of deflation","It refers exclusively to a distortion in indirect (not direct) taxation"],"a":0,"e":"'Bracket creep' specifically describes inflation pushing taxpayers' nominal (not real) income into higher direct tax brackets, effectively raising their tax burden despite no real increase in purchasing power — some countries (US, parts of Europe) index tax provisions to counter this."})

upsc.append({"q":"Consider the following statements regarding the 'inflationary gap' and 'deflationary gap':\n1. An inflationary gap arises when total government spending exceeds national income (i.e., a fiscal deficit), tending to push prices upward.\n2. A deflationary gap, also called the output gap, arises from a shortfall in total government spending relative to national income (a fiscal surplus).\n3. Both gaps refer exclusively to phenomena in the external (trade) sector, unrelated to fiscal policy.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 and 3 only"],"a":0,"e":"Statements 1 and 2 correctly describe the inflationary gap (fiscal deficit-driven) and deflationary/output gap (fiscal surplus-driven); statement 3 is false — both concepts relate to fiscal spending relative to national income, not to the external/trade sector specifically."})

upsc.append({"q":"Which one of the following best captures the phenomenon of 'inflation premium' in lending markets?","o":["The gap between the nominal interest rate charged by lenders and the real interest rate (adjusted for inflation), representing the erosion of lenders' actual returns due to inflation","A government subsidy given to banks to offset losses caused by deflation","An additional charge borrowers pay exclusively during periods of zero inflation","The portion of a loan that is waived entirely when inflation exceeds 10 per cent"],"a":0,"e":"The inflation premium is the difference between the nominal and real interest rates — as inflation erodes real returns, lenders sometimes raise nominal rates to offset this depleting profit, as Indian banks did in July 2003 when inflation crossed 7 per cent."})

upsc.append({"q":"Which one of the following statements correctly explains the 'base effect' in inflation measurement using a numerical illustration?","o":["If a price index rises by the same absolute number of points each year, the year-on-year percentage inflation rate will actually decline over successive years, because each year's percentage is calculated against a progressively higher base","The base effect implies that inflation percentages remain constant regardless of the previous year's price index level","A high base effect always leads to a higher current-year inflation rate, regardless of the absolute point increase","The base effect is only relevant for the Consumer Price Index and has no bearing on the Wholesale Price Index"],"a":0,"e":"The text's own numerical example shows a constant absolute point increase (e.g., 20 points annually) producing a DECLINING year-on-year percentage inflation rate over time, precisely because the base (denominator) keeps rising — a HIGH base last year mathematically lowers this year's percentage change for the same absolute rise, not the reverse."})

upsc.append({"q":"Which one of the following statements about 'core inflation' as first used by the Indian government (FY 2000-01) is correct?","o":["Core inflation excludes food and energy articles from the price index, which drew criticism in India's context since food and energy are of vital importance to the common people, unlike in Western economies","Core inflation includes only food and energy articles, excluding manufactured goods","Core inflation was first introduced in India during the 1991 economic reforms","Core inflation is identical in coverage and purpose to the Consumer Food Price Index"],"a":0,"e":"Core inflation (first invoked by the Indian government in FY 2000-01) excludes food and energy, a concept borrowed from Western economies where these segments matter less to ordinary consumers — critics noted this exclusion was less appropriate for India, where food and energy are central to mass welfare, not a food-and-energy-only or 1991-origin measure."})

upsc.append({"q":"Which one of the following historical examples of hyperinflation is correctly matched with its approximate magnitude?","o":["Germany (1923): prices roughly 36 billion times higher than two years earlier","Bolivia (1985): an annual inflation rate of about 100 per cent","Yugoslavia (1993): an annual inflation rate of about 5 per cent","The United States (1970s stagflation): inflation exceeding 1,000 per cent annually"],"a":0,"e":"Germany's 1923 hyperinflation saw prices roughly 36 billion times higher than two years prior (currency became more valuable as fuel than as money) — the other figures are wrong: Bolivia's 1985 hyperinflation was around 24,000% per annum, Yugoslavia's 1993 episode was around 20% PER DAY, and 1970s US stagflation involved single-digit-to-low-double-digit inflation, not 1,000%+."})

upsc.append({"q":"Which one of the following is an example of 'bottleneck' (or structural) inflation, as distinguished from other inflation types?","o":["A drastic fall in supply due to supply-side hurdles or mismanagement, with demand remaining unchanged, effectively falling within the demand-pull inflation category","A price rise caused purely by excessive wage demands from trade unions","A price rise caused entirely by excessive money printing with no supply-side element","A uniform, economy-wide price rise affecting all goods and services equally"],"a":0,"e":"Bottleneck (structural) inflation arises specifically from a drastic supply-side contraction (hurdles, hazards, mismanagement) with unchanged demand — the text places this within the broader demand-pull inflation category, not as a wage-driven, pure money-supply, or uniform economy-wide phenomenon."})

# ---------------- Section B: Business Cycle ----------------

upsc.append({"q":"Which one of the following correctly lists the four main phases of the business (trade) cycle, as distinguished from intermediate stages like stagnation and slowdown?","o":["Depression, Recovery, Boom, and Recession","Inflation, Deflation, Stagflation, and Reflation","Boom, Bust, Correction, and Rally","Growth, Maturity, Decline, and Renewal"],"a":0,"e":"The text identifies exactly four main business cycle phases — Depression, Recovery, Boom, and Recession — with stagnation and slowdown treated as additional intermediate stages, not among the core four."})

upsc.append({"q":"Which one of the following statements about the 'Depression' phase of the business cycle is correct?","o":["The world economy has experienced a true depression only once, in 1929, characterised by extremely low aggregate demand, low inflation, rapidly rising unemployment, and forced labour retrenchment by producers","Depressions occur regularly, roughly once every decade, in most major economies","During a depression, inflation is typically very high due to excessive money supply","Governments retain full control over the economy during a depression, unlike during a recession"],"a":0,"e":"The text specifically notes the world has seen a true 'Depression' only once (1929), marked by very low demand, low inflation, rising unemployment and forced retrenchment — with governments having 'almost no control' during this phase, not regular decade-cycle depressions, high inflation, or full governmental control."})

upsc.append({"q":"Which one of the following correctly distinguishes 'Recession' from 'Depression' as phases of the business cycle, per the text's own comparison?","o":["Recession shares nearly all traits of depression except that labour cuts in a recession are typically 'voluntary' (cost-adjustment driven) rather than the 'forced' retrenchment seen in a full depression","Recession involves higher inflation than depression, which is otherwise identical","Recession is a more severe phase than depression, historically preceding it","Depression and recession are entirely unrelated economic phenomena with no shared characteristics"],"a":0,"e":"The text explicitly notes recession mirrors depression's traits except that labour cuts remain 'voluntary' (cost-adjustment) rather than the 'forced' cuts marking a full depression — recession is a milder, not more severe, phase and can deepen into depression if unmanaged."})

upsc.append({"q":"Which one of the following statements about India's recessionary and recovery episodes cited in the text is correct?","o":["India experienced a recessionary phase from 1996-97 (linked to the South East Asian currency crisis) with recovery achieved only by the end of 2001-02","India's only recession occurred immediately after the 1991 Balance of Payments crisis","India has never experienced any recessionary phase since Independence","The 1996-97 Indian recession was caused entirely by domestic agricultural failure, unrelated to any external shock"],"a":0,"e":"The text specifically links India's 1996-97 recession to the South East Asian currency crisis (a domestic-plus-external demand downturn), with recovery only achieved by end-2001-02 — not the 1991 BoP crisis period, an absence of any recession, or a purely domestic agricultural cause."})

upsc.append({"q":"Which one of the following correctly defines 'growth recession', a term revived after the 2008 global financial crisis?","o":["An economy growing so slowly that more jobs are being lost than added, making it 'feel' like a recession even though real GDP is technically still advancing","A recession in which GDP contracts for two consecutive quarters while employment simultaneously rises sharply","A phase where GDP growth and employment both rise robustly, contradicting typical recession symptoms","A term describing recessions caused exclusively by agricultural sector contraction"],"a":0,"e":"'Growth recession' describes an economy still technically growing (positive real GDP) but so slowly that net job losses exceed job creation, making conditions 'feel' recessionary — not an actual GDP contraction with rising employment, robust dual growth, or an agriculture-specific phenomenon."})

upsc.append({"q":"Which one of the following correctly defines a 'double-dip recession'?","o":["A recession followed by a short-lived recovery, followed by another recession, with GDP growth sliding back to negative after only a quarter or two of positive growth","Two entirely unrelated recessions occurring in different countries simultaneously","A single, continuous recession lasting exactly two years without any recovery phase in between","A recession that is officially declared twice by two different government bodies for the same period"],"a":0,"e":"A double-dip recession is precisely a recession followed by brief recovery followed by renewed recession (negative GDP growth resuming after only a quarter or two of positive growth) — not unrelated recessions in different countries, a continuous two-year recession, or a dual-declaration technicality."})

upsc.append({"q":"Consider the following statements about 'Abenomics', the economic programme associated with Japanese PM Shinzo Abe:\n1. It consists of three components popularly called the 'Three Arrows' — fiscal stimulus, quantitative easing, and structural reforms.\n2. The quantitative easing arm aimed to double money in circulation by 2014 and achieve a 2 per cent annual inflation target.\n3. The structural reforms arm included Japan's plan to join the Trans-Pacific Partnership (TPP) to boost export potential.\n4. Abenomics is described in the text as being universally regarded by experts as a guaranteed success with no dissenting opinions.\nHow many of the statements given above are correct?","o":["Only three","All four","Only two","None"],"a":0,"e":"Statements 1, 2 and 3 accurately describe Abenomics' three arrows and their specific goals. Statement 4 is false — the text explicitly notes experts have 'mixed opinions' on Abenomics' success prospects, not universal agreement on guaranteed success."})

upsc.append({"q":"Which one of the following statements about the intellectual lineage of 'Abenomics'-style interventionist economic measures is correct?","o":["Such measures were first suggested by J. M. Keynes in response to the Great Depression of 1929, with Nobel laureate Paul Krugman cited as their most famous contemporary exponent","Such measures originated with Milton Friedman's monetarist school in the 1970s","These measures were first proposed by New Zealand's central bank in 1989 alongside its inflation-targeting framework","These measures have no historical precedent before Shinzo Abe's 2012 re-election"],"a":0,"e":"The text explicitly traces the intellectual origin of such interventionist 'arrows' to J.M. Keynes's response to the 1929 Great Depression, with Paul Krugman identified as their most prominent modern advocate — not a monetarist, New Zealand-central-bank, or entirely novel (2012-origin) idea."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

texts = [q["q"] for q in upsc]
print("Total:", len(upsc), "| unique:", len(set(texts)))
for q in upsc:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/eco_inflation_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
