import json

qs = []

qs.append({"q":"Consider the following statements regarding the factors responsible for the growth of modern Indian nationalism:\n1. Political, administrative and economic unification of the country under British rule.\n2. Introduction of Western thought and education, including exposure to writers like Mill, Rousseau and Spencer.\n3. Rediscovery of India's ancient past through historical research by scholars like Max Mueller and R.G. Bhandarkar.\n4. Growth of the press and vernacular literature.\nHow many of the above are correctly identified as factors in the growth of Indian nationalism?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors are correctly identified in the chapter as contributing to the rise of modern Indian nationalism."})

qs.append({"q":"According to Percival Spear, the new urban middle class that emerged under British rule was characterised as:","o":["A well-integrated all-India class with a common foreground of knowledge, ideas and values, and a sense of unity of purpose","A regionally fragmented class with no shared values","A class entirely opposed to Western education","A class limited exclusively to the landed aristocracy"],"a":0,"e":"Percival Spear described the new middle class as a well-integrated, dynamic, all-India minority with a shared foreground of ideas, values, and a sense of common purpose and hope."})

qs.append({"q":"Which of the following theories, put forward by European scholars during the rediscovery of India's past, gave a psychological boost to educated Indians?","o":["That the Indo-Aryans belonged to the same ethnic group from which other European nations had evolved","That India had no civilisation of its own before British contact","That Indian society had always been static and unchanging","That ancient India lacked any form of trade with the outside world"],"a":0,"e":"The theory of a shared Indo-Aryan ethnic ancestry with Europeans, along with the recovery of India's rich historical institutions and heritage, boosted Indian self-confidence against colonial myths of servility."})

qs.append({"q":"Lord Lytton's reactionary policies that provoked nationalist opposition included:\n1. Reduction of the maximum age limit for the I.C.S. examination from 21 to 19 years (1876).\n2. Holding the grand Delhi Durbar of 1877 amid a severe famine.\n3. The Vernacular Press Act (1878).\n4. The Arms Act (1878).\nHow many of the above are correctly attributed to Lytton's policies?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four measures — the ICS age reduction, the 1877 Delhi Durbar during famine, the Vernacular Press Act, and the Arms Act — were part of Lytton's reactionary policies that fuelled nationalist resentment."})

qs.append({"q":"The Ilbert Bill controversy arose when Lord Ripon's government attempted to:","o":["Abolish judicial disqualification based on race, giving Indian members of the covenanted civil service the same judicial powers as Europeans","Reduce the age limit for the Indian Civil Service examination","Impose the Vernacular Press Act on Indian newspapers","Introduce separate electorates for Muslims"],"a":0,"e":"Ripon's government sought to remove racial disqualification in judicial matters via the Ilbert Bill, but had to modify it substantially due to fierce opposition from the European community in India."})

qs.append({"q":"Which of the following best describes the nationalist lesson drawn from the Ilbert Bill episode?","o":["It became clear that justice and fair play could not be expected where European interests were at stake, but the European agitation also taught nationalists methods of organised protest","Indians concluded that racial equality had been fully achieved","It led directly to the repeal of the Vernacular Press Act","It convinced nationalists that constitutional agitation was futile and should be abandoned"],"a":0,"e":"The Ilbert Bill controversy exposed the limits of British fairness when European interests were threatened, while ironically the European agitation itself demonstrated organised protest techniques that nationalists later adopted."})

qs.append({"q":"The Zamindari Association, popularly known as the 'Landholders' Society', primarily represented the interests of:","o":["Landlords, and is considered the beginning of organised political activity and constitutional agitation in India","Industrial workers","Muslim peasants of Bengal","Educated middle-class professionals"],"a":0,"e":"The Landholders' Society (Zamindari Association) safeguarded landlord interests but is credited as marking the beginning of organised political activity and constitutional methods of agitation in India."})

qs.append({"q":"The Bengal British India Society (1843) and the Landholders' Society merged in 1851 to form:","o":["The British Indian Association","The Indian Association of Calcutta","The East India Association","The Poona Sarvajanik Sabha"],"a":0,"e":"In 1851, the Landholders' Society and the Bengal British India Society merged to form the British Indian Association, which petitioned for reforms in the renewed Company Charter."})

qs.append({"q":"The petition of the British Indian Association to the British Parliament regarding the renewed Charter Act included demands for:\n1. A separate legislature of a popular character.\n2. Separation of executive from judicial functions.\n3. Abolition of salt duty, abkari and stamp duties.\n4. Universal adult franchise.\nHow many of the above are correctly listed as its demands?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect the British Indian Association's demands; universal adult franchise was not among them, as such a demand was far ahead of the political context of the 1850s."})

qs.append({"q":"Some of the British Indian Association's demands were partially met when the Charter Act of 1853 provided for:","o":["Addition of six members to the governor-general's council for legislative purposes","Complete Indianisation of the civil services","Establishment of a fully elected Indian legislature","Abolition of the East India Company altogether"],"a":0,"e":"The Charter Act of 1853 added six members to the governor-general's council for legislative purposes, partially addressing the demand for a more representative legislature."})

qs.append({"q":"The East India Association, organised in London in 1866 to discuss the 'Indian question' and influence English public opinion, was founded by:","o":["Dadabhai Naoroji","Surendranath Banerjea","Sisir Kumar Ghosh","Ananda Mohan Bose"],"a":0,"e":"Dadabhai Naoroji organised the East India Association in London in 1866, later opening branches in prominent Indian cities."})

qs.append({"q":"The Indian League, founded in 1875 with the object of 'stimulating the sense of nationalism amongst the people', was started by:","o":["Sisir Kumar Ghosh","Surendranath Banerjea","Dadabhai Naoroji","M.G. Ranade"],"a":0,"e":"Sisir Kumar Ghosh founded the Indian League in 1875 to stimulate nationalist sentiment and encourage political education."})

qs.append({"q":"The Indian Association of Calcutta (also called the Indian National Association), founded in 1876, superseded the Indian League and was led by:","o":["Surendranath Banerjea and Ananda Mohan Bose","Dadabhai Naoroji and Pherozshah Mehta","Badruddin Tyabji and K.T. Telang","M. Viraraghavachari and P. Anandacharlu"],"a":0,"e":"Surendranath Banerjea and Ananda Mohan Bose, younger nationalists dissatisfied with the conservative British Indian Association, founded the Indian Association of Calcutta in 1876."})

qs.append({"q":"Consider the following statements about the Indian Association of Calcutta:\n1. It aimed to create strong public opinion and unify the Indian people on a common political programme.\n2. It led the campaign against the reduction of the age limit for the Indian Civil Service examination in 1877.\n3. It sponsored an all-India conference held in Calcutta in December 1883.\n4. It merged with the Indian National Congress in 1886.\nHow many of the above statements are correct?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four statements are correct; the Indian Association is regarded as the most important pre-Congress association and a direct forerunner of the INC, with which it merged in 1886."})

qs.append({"q":"The all-India agitation against the reduction of the maximum age limit for the Indian Civil Service examination, led by the Indian Association, is popularly known as:","o":["The Indian Civil Service agitation","The Ilbert Bill agitation","The Vernacular Press agitation","The Arms Act agitation"],"a":0,"e":"The campaign led by the Indian Association against the reduced ICS age limit is popularly known as the Indian Civil Service agitation."})

qs.append({"q":"The Poona Sarvajanik Sabha, founded in 1867 to serve as a bridge between the government and the people, was established by:","o":["Mahadeo Govind Ranade and others","Pherozshah Mehta and Badruddin Tyabji","M. Viraraghavachari and B. Subramaniya Aiyer","Dadabhai Naoroji and K.T. Telang"],"a":0,"e":"Mahadeo Govind Ranade and others founded the Poona Sarvajanik Sabha in 1867 to mediate between government and people."})

qs.append({"q":"The Bombay Presidency Association, started in 1885, was founded by:","o":["Badruddin Tyabji, Pherozshah Mehta and K.T. Telang","M.G. Ranade and Raghunath Rao","Surendranath Banerjea and Ananda Mohan Bose","Sisir Kumar Ghosh and Dadabhai Naoroji"],"a":0,"e":"Badruddin Tyabji, Pherozshah Mehta and K.T. Telang founded the Bombay Presidency Association in 1885."})

qs.append({"q":"The Madras Mahajan Sabha, founded in 1884, was established by:","o":["M. Viraraghavachari, B. Subramaniya Aiyer and P. Anandacharlu","Badruddin Tyabji and Pherozshah Mehta","Surendranath Banerjea and Ananda Mohan Bose","Sisir Kumar Ghosh"],"a":0,"e":"M. Viraraghavachari, B. Subramaniya Aiyer and P. Anandacharlu founded the Madras Mahajan Sabha in 1884."})

qs.append({"q":"Arrange the following pre-Congress political associations in chronological order of their founding:\n1. British Indian Association\n2. East India Association\n3. Indian Association of Calcutta\n4. Bombay Presidency Association","o":["1-2-3-4","2-1-3-4","1-3-2-4","4-3-2-1"],"a":0,"e":"Chronological order: British Indian Association (1851), East India Association (1866), Indian Association of Calcutta (1876), Bombay Presidency Association (1885)."})

qs.append({"q":"Which of the following was NOT among the pre-Congress campaigns organised by early political associations?","o":["Campaign for the introduction of universal adult franchise","Campaign for imposition of import duty on cotton (1875)","Campaign against the Vernacular Press Act (1878)","Campaign against the Arms Act (1878)"],"a":0,"e":"Universal adult franchise was not a pre-Congress campaign demand; the actual campaigns included cotton import duty, opposition to the Vernacular Press Act and Arms Act, Indianisation of services, and the ICS age-limit agitation, among others."})

qs.append({"q":"The pre-Congress campaign 'in support of the Ilbert Bill' by Indian political associations reflected their support for:","o":["Removing racial disqualification in the judiciary that denied Indian civil servants judicial powers over Europeans","Reducing the salaries of higher British officials","Imposing tariffs on British manufactured imports","Restricting the entry of Christian missionaries into India"],"a":0,"e":"Indian associations supported the Ilbert Bill because it sought to end racial discrimination that barred Indian judicial officers from trying European subjects."})

qs.append({"q":"The Bangabhasha Prakasika Sabha, one of the earliest political associations, was formed in 1836 by:","o":["Associates of Raja Rammohan Roy","Followers of Dayananda Saraswati","Disciples of Debendranath Tagore","Members of the Aligarh Movement"],"a":0,"e":"The Bangabhasha Prakasika Sabha (1836) was formed by associates of Raja Rammohan Roy, making it one of the earliest political associations in India."})

qs.append({"q":"Which of the following best explains why 'political, administrative and economic unification' of India under British rule aided the growth of nationalism, according to the chapter?","o":["It linked the economic fate of different regions together and enabled modern transport/communication to bring leaders from different regions together for political mobilisation","It eliminated all regional identities in favour of a single British identity","It ensured equal economic development across all regions of India","It had no bearing on the growth of nationalist sentiment"],"a":0,"e":"Unification linked regional economies together (e.g., crop failures affecting prices elsewhere) and modern transport/communication enabled leaders across regions to exchange ideas and organise collectively — both crucial for national political mobilisation."})

qs.append({"q":"Which of the following genuinely reflects the 'two-fold effect' of political and economic unification as identified by nationalists?","o":["Linking regional economic fates together, and enabling exchange of political ideas among leaders from different regions via modern transport and communication","Complete elimination of famine across India, and creation of full political democracy","Universal literacy across India, and abolition of caste distinctions","Total industrialisation of India, and equal wages for all workers"],"a":0,"e":"The chapter identifies the two effects as economic interlinkage of regions and the facilitation of political idea-exchange and mobilisation via improved transport and communication."})

qs.append({"q":"According to the chapter, most political associations of the early 19th century, prior to those dominated by the educated middle class later in the century, were chiefly composed of:","o":["Wealthy and aristocratic elements, often local or regional in character","Industrial workers and trade unionists","Peasants and agricultural labourers","Religious clergy across all faiths"],"a":0,"e":"Early 19th century political associations were mostly dominated by wealthy, aristocratic, and local/regional elements, in contrast to the broader, educated middle-class-led associations that emerged later."})

qs.append({"q":"Which liberal European thinkers are cited in the chapter as having influenced Indian nationalist thought through Western education?","o":["Milton, Shelley, John Stuart Mill, Rousseau, Paine, Spencer and Voltaire","Karl Marx, Friedrich Engels and Lenin alone","Only ancient Greek philosophers like Aristotle and Plato","Exclusively British conservative thinkers like Edmund Burke"],"a":0,"e":"The chapter cites Milton, Shelley, John Stuart Mill, Rousseau, Paine, Spencer and Voltaire as liberal/radical European thinkers whose ideas shaped Indian nationalist thinking through English education."})

qs.append({"q":"By 1877, approximately how many vernacular-language newspapers were being published in India, reflecting the growing role of the press in spreading nationalist ideas?","o":["About 169, with circulation reaching around 1,00,000","About 20, with negligible circulation","About 500, with circulation over 10,00,000","About 50, restricted only to Bengal"],"a":0,"e":"By 1877, roughly 169 vernacular newspapers were published in India with a combined circulation of about 1,00,000, illustrating the press's growing reach in spreading nationalist ideas despite restrictions."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_beginning_nationalism",
    "title": "Beginning of Modern Nationalism in India",
    "desc": "Factors behind the rise of Indian nationalism and political associations before the Indian National Congress",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch10_beginning_nationalism.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
