import json

qs = []

qs.append({"q":"The Revolt of 1857 began at Meerut on:","o":["May 10, 1857","May 3, 1857","April 24, 1857","June 4, 1857"],"a":0,"e":"The revolt began at Meerut on May 10, 1857, spreading rapidly after sepoys released their imprisoned comrades and marched to Delhi."})

qs.append({"q":"Consider the following statements regarding the economic causes of the Revolt of 1857:\n1. The new revenue settlement imposed heavy taxation on the peasantry.\n2. High tariff duties were imposed on Indian-made goods while British imports attracted low tariffs.\n3. Annexation of Indian states cut off royal patronage to artisans and craftsmen.\n4. In Awadh alone, about 21,000 taluqdars had their estates confiscated.\nHow many of the above statements are correct?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four are correct: the unpopular revenue settlement, discriminatory tariffs favouring British goods, loss of royal patronage for artisans, and confiscation of about 21,000 Awadh taluqdars' estates."})

qs.append({"q":"Which policies of the East India Company were chiefly responsible for the political causes of the Revolt of 1857?","o":["Doctrine of Lapse, Subsidiary Alliance and Effective Control","Permanent Settlement and Ryotwari Settlement","Charter Act of 1833 and Charter Act of 1853","Ilbert Bill and Vernacular Press Act"],"a":0,"e":"The political causes stemmed from Company policies of aggrandisement such as the Doctrine of Lapse, Subsidiary Alliance, and Effective Control, which bred suspicion among Indian ruling princes."})

qs.append({"q":"The Religious Disabilities Act of 1856, which caused socio-religious resentment before the Revolt of 1857, provided that:","o":["A change of religion would not debar a son from inheriting his father's property","Sati would be made a criminal offence","Widow remarriage would be legalised","Christian missionaries would require government licences to preach"],"a":0,"e":"The Religious Disabilities Act, 1856 declared that conversion to another religion would not disqualify a son from inheriting his 'heathen' father's property, which many Indians saw as interference in religious customs."})

qs.append({"q":"Which of the following 'outside events', in which the British suffered reverses, is believed to have psychologically emboldened Indians before the Revolt of 1857?","o":["The First Afghan War (1838-42), Punjab Wars (1845-49) and the Crimean War (1854-56)","The Anglo-Mysore Wars","The Anglo-Maratha Wars","The Battle of Plassey and Battle of Buxar"],"a":0,"e":"British setbacks in the First Afghan War, the Punjab Wars, and the Crimean War suggested to Indians that British power was not invincible."})

qs.append({"q":"The immediate spark for the Revolt of 1857 was:","o":["The introduction of greased cartridges for the Enfield rifle, rumoured to contain cow and pig fat","The annexation of Jhansi under the Doctrine of Lapse","The passage of the General Service Enlistment Act, 1856","The imposition of income tax on Indians"],"a":0,"e":"The greased cartridges of the new Enfield rifle, rumoured to be coated with cow and pig fat, provided the immediate spark, though the underlying discontent had been simmering for long."})

qs.append({"q":"Mangal Pande, whose action is often cited as an early flashpoint of the Revolt of 1857, was a sepoy of the:","o":["34th Native Infantry at Barrackpore","19th Native Infantry at Berhampore","3rd Native Cavalry at Meerut","7th Awadh Regiment"],"a":0,"e":"Mangal Pande, a sepoy of the 34th Native Infantry, fired at his sergeant major at Barrackpore on April 8, 1857 and was executed."})

qs.append({"q":"Arrange the following events of early 1857 in chronological order:\n1. Mangal Pande fires at the sergeant major at Barrackpore\n2. The 19th Native Infantry at Berhampore mutinies over the Enfield rifle\n3. Eighty-five sepoys of the 3rd Native Cavalry are imprisoned at Meerut\n4. The general mutiny breaks out at Meerut","o":["2-1-3-4","1-2-3-4","3-1-2-4","2-3-1-4"],"a":0,"e":"Order: Berhampore mutiny (February 1857) - Mangal Pande's action (April 8, 1857) - imprisonment of Meerut sepoys (May 9, 1857) - general mutiny at Meerut (May 10, 1857)."})

qs.append({"q":"After capturing Delhi, the rebel sepoys proclaimed which of the following as the symbolic head of the revolt?","o":["Bahadur Shah Zafar","Nana Saheb","Kunwar Singh","General Bakht Khan"],"a":0,"e":"The rebels proclaimed the aged Mughal emperor Bahadur Shah Zafar as the Emperor of India, transforming the mutiny into a wider political revolt."})

qs.append({"q":"At Delhi, though Bahadur Shah Zafar was the nominal head, the real command of the revolt lay with a court of soldiers headed by:","o":["General Bakht Khan","Lieutenant Willoughby","Simon Fraser","Nana Saheb"],"a":0,"e":"General Bakht Khan, who led the Bareilly troops to Delhi, headed the court of soldiers that actually directed the affairs of the revolt in the emperor's name."})

qs.append({"q":"Match List-I (Storm Centre) with List-II (Rebel Leader) and select the correct answer using the codes below:\nList-I:\nA. Kanpur\nB. Lucknow\nC. Jhansi\nD. Bihar (Jagdishpur)\nList-II:\n1. Rani Laxmibai\n2. Kunwar Singh\n3. Nana Saheb\n4. Begum Hazrat Mahal","o":["A-3, B-4, C-1, D-2","A-1, B-2, C-3, D-4","A-4, B-3, C-2, D-1","A-2, B-1, C-4, D-3"],"a":0,"e":"Kanpur - Nana Saheb (3); Lucknow - Begum Hazrat Mahal (4); Jhansi - Rani Laxmibai (1); Bihar/Jagdishpur - Kunwar Singh (2)."})

qs.append({"q":"Nana Saheb, who led the revolt at Kanpur, was:","o":["The adopted son of the last peshwa, Baji Rao II","The zamindar of Jagdishpur","A native of Madras who settled in Faizabad","The deposed nawab of Awadh"],"a":0,"e":"Nana Saheb was the adopted son of Baji Rao II, the last peshwa; he had been denied his family title and pension and was living near Kanpur when he joined the revolt."})

qs.append({"q":"At Lucknow, the rebellion (which broke out on June 4, 1857) was led on behalf of whom by Begum Hazrat Mahal?","o":["Her son Birjis Qadir, who was proclaimed nawab","Her husband, the deposed nawab of Awadh","General Bakht Khan","Maulvi Ahmadullah"],"a":0,"e":"Begum Hazrat Mahal governed on behalf of her son Birjis Qadir, who was proclaimed nawab of Awadh, with offices shared between Hindus and Muslims."})

qs.append({"q":"The siege of the Lucknow Residency saw the death of which British official?","o":["Henry Lawrence","John Nicholson","Sir Hugh Wheeler","Colonel James Neill"],"a":0,"e":"Sir Henry Lawrence, the British resident at Lucknow, was killed during the siege of the Residency; command then devolved on Brigadier Inglis."})

qs.append({"q":"Rani Laxmibai of Jhansi took up arms against the British primarily because:","o":["Lord Dalhousie refused to recognise her adopted son's succession and annexed Jhansi under the Doctrine of Lapse","She was denied the title of peshwa","Her husband Raja Gangadhar Rao was imprisoned by the British","The British imposed the Enfield rifle on her troops"],"a":0,"e":"After her husband Raja Gangadhar Rao's death, Lord Dalhousie refused to allow her adopted son to succeed and annexed Jhansi under the Doctrine of Lapse, driving Laxmibai to revolt."})

qs.append({"q":"Which British general famously paid tribute to Rani Laxmibai with the words \"Here lay the woman who was the only man among the rebels\"?","o":["Hugh Rose","John Nicholson","Colin Campbell","Henry Havelock"],"a":0,"e":"Hugh Rose, the British commander who defeated her at Jhansi and Gwalior, paid this tribute to Rani Laxmibai."})

qs.append({"q":"After the fall of Jhansi, Rani Laxmibai was joined by Tantia Tope, and together they marched towards which city, where they were hailed by Indian soldiers?","o":["Gwalior","Kanpur","Bareilly","Agra"],"a":0,"e":"Rani Laxmibai and Tantia Tope marched to Gwalior, where Indian soldiers welcomed them, though the Sindhia ruler sided with the British."})

qs.append({"q":"Khan Bahadur, who led the revolt at Bareilly with an army of about 40,000 soldiers, was:","o":["A descendant of the former ruler of Rohilkhand","The zamindar of Jagdishpur","The adopted son of Baji Rao II","A native of Madras settled in Awadh"],"a":0,"e":"Khan Bahadur, a descendant of the former ruler of Rohilkhand, led the Bareilly resistance, motivated partly by dissatisfaction with the British pension offered to him."})

qs.append({"q":"Kunwar Singh, who led the revolt in Bihar, was the zamindar of:","o":["Jagdishpur","Baghpat","Bareilly","Faizabad"],"a":0,"e":"Kunwar Singh, an old zamindar of Jagdishpur who had been deprived of his estates, led the Bihar uprising, joining the sepoys who reached Arrah from Dinapore."})

qs.append({"q":"Maulvi Ahmadullah, a prominent leader of the Revolt of 1857 in Awadh, was originally a native of:","o":["Madras","Bengal","Punjab","Rajputana"],"a":0,"e":"Maulvi Ahmadullah of Faizabad was originally from Madras before moving north, where he emerged as an important leader of the revolt in Awadh."})

qs.append({"q":"Shah Mal, a local leader in Pargana Baraut (Baghpat, Uttar Pradesh) during the Revolt of 1857, is notable for:","o":["Organising headmen and peasants of 84 villages (chaurasi desh) against British hegemony","Leading the siege of the Lucknow Residency","Commanding the sepoy court at Delhi","Proclaiming himself peshwa at Kanpur"],"a":0,"e":"Shah Mal mobilised the peasants and headmen of 84 villages, disrupted British communications, and turned an irrigation department bungalow into a 'hall of justice' before being killed in July 1857."})

qs.append({"q":"Consider the following statements about the suppression of the Revolt of 1857:\n1. Delhi was recaptured by the British on September 20, 1857.\n2. Bahadur Shah Zafar was exiled to Rangoon, where he died in 1862.\n3. Tantia Tope was captured while asleep and put to death in April 1859.\n4. Rani Laxmibai died on the battlefield in June 1858.\nHow many of the above statements are correct?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four statements are accurate: Delhi fell on September 20, 1857; Bahadur Shah was exiled to Rangoon (died 1862); Tantia Tope was captured and executed in April 1859; Rani Laxmibai died in battle in June 1858."})

qs.append({"q":"Which of the following is correctly identified as a reason for the failure of the Revolt of 1857?","o":["Absence of an all-India character, with the east, south and west remaining largely unaffected","Complete lack of participation by sepoys","Absence of any civilian involvement","Overwhelming superiority of Indian arms and equipment"],"a":0,"e":"The revolt's failure is attributed partly to its limited territorial spread — the eastern, southern and western regions remained largely unaffected, unlike the north and central regions."})

qs.append({"q":"Which of the following Indian rulers did NOT join the Revolt of 1857 and, in some cases, actively helped the British?","o":["The Sindhia of Gwalior, the Holkar of Indore and the Maharaja of Kashmir","Nana Saheb and Rani Laxmibai","Kunwar Singh and Khan Bahadur","Begum Hazrat Mahal and Maulvi Ahmadullah"],"a":0,"e":"Rulers such as the Sindhia of Gwalior, the Holkar of Indore, the rulers of Patiala and Sikh chieftains, and the Maharaja of Kashmir refrained from joining the revolt and often aided the British."})

qs.append({"q":"According to one estimate cited in the chapter regarding the geographic and demographic reach of the Revolt of 1857:","o":["Not more than one-fourth of the total area and one-tenth of the total population was affected","More than three-fourths of India's area was directly affected","The revolt affected all provinces of British India equally","Only Delhi and its immediate vicinity were affected"],"a":0,"e":"By one estimate, the revolt affected not more than one-fourth of the total area of India and not more than one-tenth of the total population."})

qs.append({"q":"Which of the following factors is cited as contributing to the poor military performance of the rebels during the Revolt of 1857?","o":["Rebels were poorly equipped, generally fighting with swords and spears against British Enfield rifles and the electric telegraph","The rebels had no sepoy participation at all","The British had no experienced commanders","The rebels possessed superior artillery"],"a":0,"e":"The rebels were poorly armed compared to the British, who had modern rifles and used the electric telegraph to coordinate troop movements against the rebels."})

qs.append({"q":"Which prominent British officers/administrators are associated with suppressing the revolt at the locations given?\n1. John Nicholson and Lieutenant Hudson - Delhi\n2. Sir Colin Campbell - Kanpur and Lucknow\n3. Sir Hugh Rose - Jhansi\n4. Colonel James Neill - Benaras\nHow many of the above pairs are correctly matched?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four pairs are correctly matched as per the chapter's list of British officers who suppressed the revolt at each centre."})

qs.append({"q":"During the Revolt of 1857, Hindu-Muslim unity was notably demonstrated by:","o":["The universal acknowledgement of Bahadur Shah Zafar, a Muslim, as emperor by both Hindu and Muslim rebels, and the banning of cow slaughter in rebel-controlled areas","The complete absence of Muslims from leadership positions","Separate and rival administrations set up by Hindus and Muslims","The exclusive participation of Muslim sepoys in the revolt"],"a":0,"e":"Rebels of both communities acknowledged Bahadur Shah Zafar as emperor, cow slaughter was banned once an area came under rebel control, and both communities shared leadership roles, as noted by Maulana Azad."})

qs.append({"q":"Which historian described the Revolt of 1857 as \"a wholly unpatriotic and selfish Sepoy Mutiny with no native leadership and no popular support\"?","o":["Sir John Seeley","V.D. Savarkar","S.N. Sen","R.C. Majumdar"],"a":0,"e":"Sir John Seeley dismissed the revolt as a mere sepoy mutiny lacking native leadership and popular support."})

qs.append({"q":"Which historian famously termed the Revolt of 1857 the \"First War of Indian Independence\" in his book?","o":["V.D. Savarkar","R.C. Majumdar","Percival Spear","Eric Stokes"],"a":0,"e":"V.D. Savarkar, in his book The Indian War of Independence, 1857, characterised the revolt as the first planned war of national independence."})

qs.append({"q":"Dr S.N. Sen, in his book Eighteen Fifty-Seven, characterised the Revolt of 1857 as one that:","o":["Began as a fight for religion but ended as a war of independence","Was purely a religious war against Christians","Was a conflict between civilisation and barbarism","Was entirely a peasant uprising with no sepoy involvement"],"a":0,"e":"Dr S.N. Sen viewed the revolt as beginning as a fight for religion but transforming, over its course, into a war of independence."})

qs.append({"q":"Which historian held that the Revolt of 1857 was \"neither the first, nor national, nor a war of independence\"?","o":["R.C. Majumdar","V.D. Savarkar","S.B. Chaudhuri","S.N. Sen"],"a":0,"e":"R.C. Majumdar argued that the revolt was neither the first uprising, nor truly national in character, nor a genuine war of independence, since large parts of the country remained unaffected."})

qs.append({"q":"Jawaharlal Nehru, in Discovery of India, characterised the Revolt of 1857 essentially as:","o":["A feudal uprising with some nationalistic elements","A purely religious uprising","A modern nationalist movement","A conflict solely between the peasantry and landlords"],"a":0,"e":"Nehru viewed the 1857 revolt as essentially a feudal uprising, though acknowledging that it contained some nationalistic elements."})

qs.append({"q":"According to Marxist historians, the Revolt of 1857 has been characterised as:","o":["A struggle of the soldier-peasant democratic combine against foreign imperialism as well as indigenous landlordism","A purely bourgeois-nationalist movement","A war exclusively between rival feudal lords","A movement led entirely by the educated middle class"],"a":0,"e":"Marxist historians described the revolt as a combined struggle of soldiers and peasants against both foreign imperialism and indigenous feudal landlordism."})

qs.append({"q":"Which of the following is a direct consequence of the Revolt of 1857 with respect to constitutional changes?","o":["The Act for the Better Government of India, 1858, transferred power from the East India Company to the British Crown","The Regulating Act of 1773 was passed","The Charter Act of 1833 ended the Company's trading rights","The Pitt's India Act, 1784 established dual control"],"a":0,"e":"The Act for the Better Government of India (1858) abolished Company rule and transferred administration directly to the British Crown, with a Secretary of State for India appointed."})

qs.append({"q":"The Queen's Proclamation, announcing the transfer of India's government to the British Crown, was issued at a durbar in Allahabad by Lord Canning on:","o":["November 1, 1858","August 2, 1858","September 20, 1857","May 10, 1857"],"a":0,"e":"The Queen's Proclamation was issued on November 1, 1858, at a durbar in Allahabad, and it was through this proclamation that the governor-general also acquired the title of Viceroy."})

qs.append({"q":"Consider the following statements regarding the Queen's Proclamation of 1858:\n1. It ended the era of territorial annexations by the British.\n2. It promised freedom of religion to Indians without interference from British officials.\n3. It promised equal opportunities in government service irrespective of race or creed.\n4. It abolished all Indian princely states immediately.\nHow many of the above statements are correct?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correct; statement 4 is incorrect as the proclamation actually promised to respect the dignity and rights of native princes rather than abolish princely states."})

qs.append({"q":"Following the Revolt of 1857, British military policy was reorganised around the concept of:","o":["'Division and counterpoise', increasing European troops and recruiting from so-called 'martial races'","Complete disbandment of the British Indian Army","Universal conscription of Indians into a single unified force","Abolition of separate caste/community-based units"],"a":0,"e":"Post-1857 military reorganisation emphasised 'division and counterpoise' — increasing the proportion of European troops, reducing Indian soldiers, and recruiting selectively from 'martial races' like Punjab and Nepal, with units organised by caste/community/region."})

qs.append({"q":"The 'White Mutiny' after the Revolt of 1857 refers to:","o":["Unrest among European Company troops who resented the compulsory transfer of allegiance to the Crown and the stoppage of batta allowances","A revolt of Indian sepoys who refused to accept British commissions","A protest by British civilians against the Queen's Proclamation","An uprising of European planters against indigo cultivation reforms"],"a":0,"e":"The White Mutiny arose when European Company troops resented the transfer of their allegiance to the Crown and the stoppage of batta (extra allowance), following the Army Amalgamation Scheme of 1861."})

qs.append({"q":"The Indian Civil Service Act of 1861, passed in accordance with the Queen's Proclamation, is best described as:","o":["Nominally promising equality of opportunity but in practice keeping higher services largely reserved for the colonisers","Opening half of all civil service posts to Indians immediately","Abolishing the civil service examination system entirely","Establishing reserved constituencies for Indians in the civil service"],"a":0,"e":"While the Act suggested equality irrespective of race, the detailed examination rules in practice kept the higher civil services almost exclusively in British hands."})

qs.append({"q":"Which of the following best summarises the overall significance of the Revolt of 1857 for the course of Indian nationalism?","o":["It was not a coordinated national war of independence, but it established local traditions of resistance and helped forge an early sense of collective political identity","It had no lasting impact on Indian political consciousness","It directly led to the formation of the Indian National Congress in 1857 itself","It ended all British interest in ruling India"],"a":0,"e":"Though not an organised national revolt, 1857 sowed early seeds of collective political consciousness and local traditions of resistance that influenced the later freedom struggle, even as the Congress was founded only decades later in 1885."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_revolt_1857",
    "title": "The Revolt of 1857",
    "desc": "Causes, spread, storm centres and leaders, suppression, historiographical debate, and consequences of the Revolt of 1857",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch7_revolt_1857.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
