import json

qs = []

qs.append({"q":"The debates on the future strategy of the national movement after the withdrawal of the Civil Disobedience Movement occurred in how many stages, and around what respective questions?","o":["Two stages — the immediate post-CDM strategy (1934-35), and office acceptance after the 1937 provincial elections","One stage focused solely on complete independence","Three stages, the last dealing with the Quit India Movement","Two stages, both dealing exclusively with communal representation"],"a":0,"e":"The debate unfolded in two stages: first on the immediate strategy after CDM's withdrawal (1934-35), and second on whether to accept office after the 1937 provincial elections under the 1935 Act."})

qs.append({"q":"In the first stage debate, which three perspectives were put forward regarding the nationalists' immediate course of action?","o":["Constructive work on Gandhian lines; constitutional struggle via council entry; and continuation of non-constitutional mass struggle","Armed revolution; complete boycott of all political activity; and alliance with the British government","Immediate acceptance of dominion status; rejection of all reforms; and unconditional surrender to British demands","Formation of a new political party; dissolution of the Congress; and merger with the Muslim League"],"a":0,"e":"The three perspectives were constructive work (Gandhian), constitutional participation via council entry, and continuation of non-constitutionalist mass struggle (the leftist position)."})

qs.append({"q":"Which nationalists advocated participation in elections to the Central Legislature (due in 1934) as a way to maintain political morale during the non-mass-struggle phase?","o":["M.A. Ansari, Asaf Ali, Bhulabhai Desai, S. Satyamurthy and B.C. Roy","Jawaharlal Nehru and Subhash Bose","Bhagat Singh and Chandra Shekhar Azad","Muhammad Ali Jinnah and the Muslim League"],"a":0,"e":"Leaders such as Ansari, Asaf Ali, Bhulabhai Desai, Satyamurthy and B.C. Roy advocated council entry to sustain political engagement during the lull after Civil Disobedience."})

qs.append({"q":"Jawaharlal Nehru, representing the leftist trend within Congress, described the withdrawal of Civil Disobedience and any move towards council entry as:","o":["\"A spiritual defeat\", \"a surrender of ideals\", and \"a retreat from revolutionary to reformist mentality\"","A necessary and welcome tactical adjustment","The only viable path to eventual independence","A minor administrative matter of no ideological significance"],"a":0,"e":"Nehru sharply criticised the withdrawal and any parliamentary turn as a betrayal of revolutionary momentum, framing it in stark ideological terms as a retreat from genuine anti-imperialist struggle."})

qs.append({"q":"Nehru argued that a genuine anti-imperialist struggle required incorporating which additional dimension?","o":["The class struggle of peasants and workers, organised through kisan sabhas and trade unions affiliated with the Congress","Exclusive reliance on urban middle-class leadership","Cooperation with British capitalists to strengthen the economy first","Abandonment of all mass organisations in favour of elite negotiation"],"a":0,"e":"Nehru believed anti-imperialism alone was insufficient; the movement needed to integrate the economic and class demands of workers and peasants through their own organisations for a truly transformative struggle."})

qs.append({"q":"The 'Struggle-Truce-Struggle' (S-T-S) strategy, associated with Gandhi and much of the Congress leadership, envisioned:","o":["A mass struggle phase followed by a truce phase to allow recuperation, before resuming struggle if the government failed to respond","Continuous, uninterrupted mass struggle with no truce phase ever","Permanent truce with no further mass action","Struggle only in provinces where Congress held a majority"],"a":0,"e":"The S-T-S strategy proposed cyclical phases: mass struggle, followed by truce to allow rest and government response, and renewed struggle if demands remained unmet."})

qs.append({"q":"In contrast to the S-T-S strategy, Nehru proposed which alternative approach?","o":["A Struggle-Victory (S-V) strategy involving continuous direct action without any interposing constitutionalist phase","A complete boycott of the Congress organisation","Immediate acceptance of dominion status","Alliance with the Muslim League against the Congress"],"a":0,"e":"Nehru's S-V (Struggle-Victory) strategy rejected any truce phase, advocating uninterrupted confrontation with imperialism until victory was achieved."})

qs.append({"q":"Gandhi ultimately reconciled Congress differences over council entry by:","o":["Permitting Congressmen who could not offer satyagraha or do constructive work to express their patriotic energies through council work","Banning all forms of council participation permanently","Expelling all Swarajist-minded members from the Congress","Insisting all Congressmen must contest elections regardless of preference"],"a":0,"e":"Gandhi accommodated council-entry proponents by allowing those unable to pursue satyagraha or constructive work to channel their energies into legislative politics, provided they avoided being 'sucked into constitutionalism'."})

qs.append({"q":"In May 1934, the All India Congress Committee (AICC) met at Patna to set up which body to fight elections under Congress auspices?","o":["A Parliamentary Board","The Congress Working Committee","The Swarajist Party","The Independence for India League"],"a":0,"e":"The AICC's Patna meeting (May 1934) established a Parliamentary Board to organise the Congress's electoral participation."})

qs.append({"q":"Gandhi announced his resignation from the Congress in October 1934, stating he wished to serve it better in:","o":["Thought, word and deed","Silence and seclusion","Exile abroad","A purely religious capacity"],"a":0,"e":"Gandhi resigned from formal Congress membership in October 1934, explaining he could better serve the organisation informally, given growing internal ideological diversity."})

qs.append({"q":"In the November 1934 elections to the Central Legislative Assembly, the Congress captured how many out of 75 seats reserved for Indians?","o":["45","30","60","75"],"a":0,"e":"The Congress won 45 out of 75 Indian-reserved seats in the November 1934 Central Legislative Assembly elections, reflecting its continued political strength despite internal debates."})

qs.append({"q":"The Government of India Act, 1935, passed by the British Parliament in August 1935, proposed an All India Federation comprising:","o":["All British Indian provinces, chief commissioner's provinces, and the princely states","Only British Indian provinces, excluding princely states entirely","Only the princely states, excluding British India","A federation limited to Bengal, Bombay, and Madras presidencies"],"a":0,"e":"The proposed federation under the 1935 Act was meant to unite British Indian provinces and chief commissioner's provinces with the princely states, though the federation was never actually implemented."})

qs.append({"q":"Why did the All India Federation proposed under the Government of India Act, 1935 never actually come into being?","o":["The conditions requiring sufficient princely states (accounting for 50% of their total population) to join were never fulfilled","The British Parliament repealed the federal provisions before implementation","The Indian National Congress vetoed the federation formally","World War II made federation legally impossible from the outset"],"a":0,"e":"The federation's establishment was conditional on enough princely states joining (representing at least half the princely population), a threshold never met, so the central government continued under the 1919 Act's provisions until 1946."})

qs.append({"q":"Under the Government of India Act, 1935, at the federal level, which subjects were classified as 'reserved', to be administered exclusively by the governor-general?","o":["Foreign affairs, defence, tribal areas and ecclesiastical affairs","Education, health and agriculture","Local government and industry","Currency and taxation"],"a":0,"e":"Reserved subjects at the federal level — foreign affairs, defence, tribal areas, and ecclesiastical affairs — remained under the governor-general's exclusive control, unaccountable to the legislature."})

qs.append({"q":"Under the 1935 Act's federal legislature, the bicameral structure consisted of the Council of States (upper house) and the Federal Assembly (lower house). Which of the following is correctly noted about their composition and election method?","o":["Election to the Council of States was direct while election to the Federal Assembly was indirect — an unusual reversal of typical practice","Both houses were directly elected by universal adult suffrage","Both houses were entirely nominated by the governor-general","The Federal Assembly was directly elected while the Council of States was entirely nominated by princes"],"a":0,"e":"Interestingly, the 1935 Act reversed the typical pattern — the Council of States (upper house) was directly elected while the Federal Assembly (lower house) was indirectly elected, a notable structural oddity."})

qs.append({"q":"Under the 1935 Act, what proportion of the federal budget remained non-votable by the legislature?","o":["80 per cent","50 per cent","20 per cent","100 per cent"],"a":0,"e":"A full 80 per cent of the federal budget remained outside legislative voting power under the 1935 Act, severely limiting real fiscal control even within the proposed federal structure."})

qs.append({"q":"At the provincial level, the Government of India Act, 1935 replaced dyarchy with:","o":["Provincial autonomy","Continued dyarchy with minor modifications","Direct rule by the governor-general","Complete abolition of provincial legislatures"],"a":0,"e":"The 1935 Act introduced provincial autonomy, ending the earlier dyarchic arrangement and granting provinces greater legal and administrative independence, deriving authority directly from the Crown."})

qs.append({"q":"Under provincial autonomy in the 1935 Act, ministers administering provincial subjects were made:","o":["Answerable to and removable by an adverse vote of the provincial legislature","Answerable only to the governor, with no legislative accountability","Permanently appointed with no removal mechanism","Directly appointed by the British Parliament"],"a":0,"e":"A key feature of provincial autonomy was that ministers, unlike under dyarchy, were now genuinely accountable to the provincial legislature and could be removed by an adverse vote."})

qs.append({"q":"Despite provincial autonomy, what proportion of the provincial budget remained non-votable under the 1935 Act?","o":["40 per cent","80 per cent","10 per cent","100 per cent"],"a":0,"e":"40 per cent of the provincial budget remained outside legislative control, a continuing limitation on genuine ministerial and legislative authority even under provincial autonomy."})

qs.append({"q":"Which of the following is a key criticism of the Government of India Act, 1935, as noted in the chapter's evaluation?","o":["Its extension of communal electorates promoted separatist tendencies that ultimately contributed to the partition of India","It abolished all forms of communal representation, angering minority communities","It granted full parliamentary sovereignty to Indian legislatures","It enfranchised the majority of the Indian population"],"a":0,"e":"The Act's extension of communal electorates and interest-based representation is seen as having deepened separatist political tendencies, a factor later contributing to the eventual partition of India."})

qs.append({"q":"According to the chapter, the 1935 Act enfranchised approximately what percentage of the British Indian population?","o":["14 per cent","50 per cent","5 per cent","30 per cent"],"a":0,"e":"The 1935 Act extended the franchise to about 14 per cent of British India's population, a significant expansion from earlier reforms but still far from universal suffrage."})

qs.append({"q":"Jawaharlal Nehru's famous critique of the Government of India Act, 1935 described it metaphorically as:","o":["\"A car, all brakes and no engine\"","\"A ship without a rudder\"","\"A house of cards\"","\"An empty vessel\""],"a":0,"e":"Nehru's memorable phrase captured the Act's abundance of restrictive 'safeguards' and 'special responsibilities' relative to any genuine power or forward momentum for self-government."})

qs.append({"q":"Which of the following describes the long-term British strategic thinking behind the reforms embodied in the 1935 Act?","o":["To integrate segments of the national movement into constitutional structures, thereby weakening the impetus for extra-legal mass struggle","To completely dismantle the Indian National Congress as an organisation","To grant immediate dominion status and withdraw from India entirely","To unite all Indian political groups into a single unified party"],"a":0,"e":"The British aimed to co-opt nationalist energy into constitutional and administrative structures, reasoning that participation in power would make Congressmen reluctant to return to sacrifice-based politics, while also fostering provincial power centres that could weaken central Congress leadership."})

qs.append({"q":"Which organisations, unlike the Congress, declared themselves in favour of working the 1935 Act at both central and provincial levels?","o":["The Hindu Mahasabha and the National Liberal Federation","The Communist Party of India and the AITUC","The Muslim League and the Khudai Khidmatgars","The Servants of India Society and the Arya Samaj"],"a":0,"e":"While the Congress unanimously rejected the 1935 Act, the Hindu Mahasabha and National Liberal Federation favoured cooperating with and working within its provisions."})

qs.append({"q":"Instead of the 1935 Act, the Congress demanded the convening of a body to frame India's constitution based on:","o":["A Constituent Assembly elected on the basis of adult franchise","A nominated council of princely state representatives","A body selected entirely by the British Parliament","An assembly restricted to propertied classes"],"a":0,"e":"The Congress's alternative demand was for a Constituent Assembly elected through universal adult franchise, to draft a constitution for a genuinely independent India."})

qs.append({"q":"In the second stage debate (early 1937), the central question dividing Congress leftists and moderates was:","o":["Whether the Congress should accept ministerial office in provinces if it won a majority in provincial elections","Whether to boycott the 1937 elections entirely","Whether to dissolve the Congress altogether","Whether to merge with the Muslim League"],"a":0,"e":"With provincial elections under the 1935 Act approaching, the key strategic question was whether the Congress, if victorious, should actually form and accept ministerial office."})

qs.append({"q":"Nehru, Subhash Bose, and Congress socialists/communists opposed office acceptance chiefly on the ground that:","o":["It would mean assuming responsibility without real power, undermining the movement's revolutionary character","It was legally prohibited under the 1935 Act","It would immediately trigger British suppression of the Congress","It contradicted the Congress's earlier support for the Nehru Report"],"a":0,"e":"Opponents of office acceptance argued that governing under the 1935 Act's constrained framework meant taking administrative responsibility without genuine power, risking dilution of the movement's revolutionary and anti-imperialist thrust."})

qs.append({"q":"As a counter-strategy, the leftists who opposed straightforward office acceptance proposed:","o":["Entering the councils with the aim of creating deadlocks to make the Act unworkable — an older Swarajist-style strategy","Complete withdrawal from all electoral activity","Immediate armed insurrection against provincial governments","Formation of a rival constituent assembly"],"a":0,"e":"The leftists revived a Swarajist-style tactic — entering legislatures specifically to obstruct and create deadlocks, thereby demonstrating the Act's unworkability rather than legitimising it through cooperative governance."})

qs.append({"q":"Proponents of office acceptance argued that provincial ministries, despite their limited powers, could serve which useful purpose?","o":["Promote constructive work and prevent the administrative field from being left entirely to pro-government reactionary forces","Achieve full independence for India immediately","Abolish the need for any future mass movement","Replace the Indian National Congress as the primary nationalist body"],"a":0,"e":"Advocates of office acceptance saw provincial governance as a way to advance constructive goals and deny administrative space to conservative, pro-government elements, while treating it as a tactical, not ideological, choice."})

qs.append({"q":"Gandhi's position on office acceptance evolved from initial opposition within the CWC to, by early 1936:","o":["Willingness to give a trial to the formation of Congress ministries","Permanent and irreversible opposition to any office acceptance","Complete withdrawal from Congress decision-making on the issue","Support for a boycott of the 1937 provincial elections"],"a":0,"e":"Gandhi initially opposed office acceptance but shifted by early 1936 to support giving Congress ministries a trial run, reflecting a pragmatic accommodation of the party's dominant sentiment."})

qs.append({"q":"The Congress sessions at Lucknow (early 1936) and Faizpur (late 1937) resolved to fight the 1937 elections while adopting which stance towards the 1935 Act?","o":["Not to submit to or cooperate with the constitution, but to combat it both inside and outside the legislatures until it was ended","Full cooperation with the Act's provisions","Complete boycott of the elections","Formal acceptance of dominion status under the Act"],"a":0,"e":"The Congress resolved to contest elections while explicitly rejecting the 1935 Act's legitimacy, aiming to combat it from both inside and outside the legislature until it was ended."})

qs.append({"q":"The February 1937 provincial elections were held in how many provinces, and approximately how many people were enfranchised?","o":["Eleven provinces, with about 30.1 million people (14% of the population) enfranchised","Five provinces, with about 5 million people enfranchised","All of British India as a single constituency, with universal suffrage","Eleven provinces, with only male voters enfranchised"],"a":0,"e":"Elections were held in eleven provinces, enfranchising approximately 30.1 million people (including 4.25 million women), about 14% of the total population, of whom 15.5 million actually voted."})

qs.append({"q":"The Congress manifesto for the 1937 elections included commitments to:","o":["Release of political prisoners, removal of gender/caste-based disabilities, agrarian reform, and rights to form trade unions and strike","Continuation of the salt tax and existing agrarian structure","Support for separate electorates for all communities","Full cooperation with the governor's reserved powers"],"a":0,"e":"The Congress manifesto promised prisoner releases, removal of gender and caste disabilities, radical agrarian reform, debt relief, and expanded labour rights including unionisation and strikes."})

qs.append({"q":"In the 1937 provincial elections, the Congress won how many of the 1,161 seats it contested (out of 1,585 total seats across the eleven provinces)?","o":["716","500","1,000","300"],"a":0,"e":"The Congress won 716 out of 1,161 contested seats, securing majorities in most provinces and emerging as the largest party even in some where it lacked an outright majority."})

qs.append({"q":"In which provinces did the Congress NOT secure an outright majority in the 1937 elections, though it emerged as the largest party in some of them?","o":["Bengal, Assam, Punjab, Sindh and the NWFP","Madras, Bombay and the Central Provinces","Bihar, Orissa and the United Provinces","All eleven provinces uniformly lacked a Congress majority"],"a":0,"e":"The Congress fell short of a majority in Bengal, Assam, Punjab, Sindh and the NWFP, though it became the largest single party in Bengal, Assam, and the NWFP."})

qs.append({"q":"Notably, Gandhi's personal involvement in the 1937 election campaign was limited in that he:","o":["Did not attend a single election meeting","Personally addressed every provincial constituency","Led the Congress Parliamentary Board directly","Contested a seat himself in the Central Provinces"],"a":0,"e":"Despite eventually supporting office acceptance, Gandhi notably abstained from campaigning, not attending any election meeting during the 1937 provincial polls."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_debates_future_strategy",
    "title": "Debates on the Future Strategy after Civil Disobedience Movement",
    "desc": "The first-stage strategy debate (constructive work vs council entry vs mass struggle), the Government of India Act 1935, and the second-stage debate on office acceptance leading to the 1937 provincial elections",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch20_debates_future_strategy.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
