import json

qs = []

qs.append({"q":"Raja Rammohan Roy, often called the 'father of Indian Renaissance', founded the Atmiya Sabha in 1814 with the aim of:","o":["Propagating the monotheistic ideals of the Vedanta and campaigning against idolatry and caste rigidities","Promoting the Sharia among Bengal Muslims","Reviving Vedic education exclusively for Brahmins","Establishing a purely political organisation against the British"],"a":0,"e":"The Atmiya Sabha (1814) was founded to propagate monotheism based on Vedanta and to campaign against idolatry, caste rigidities and meaningless rituals."})

qs.append({"q":"In which work did Raja Rammohan Roy attempt to separate the moral and philosophical message of the New Testament from its miracle stories?","o":["Precepts of Jesus (1820)","Gift to Monotheists (1809)","Satyarth Prakash","Tattvabodhini Patrika"],"a":0,"e":"Rammohan Roy's Precepts of Jesus (1820) extracted the moral teachings of Christ, distinguishing them from miracle narratives — a move that drew criticism from missionaries."})

qs.append({"q":"The Brahmo Sabha, founded by Raja Rammohan Roy in August 1828 (later renamed Brahmo Samaj), was opposed by the orthodox Dharma Sabha organised by:","o":["Raja Radhakant Deb","Debendranath Tagore","Keshab Chandra Sen","Ishwar Chandra Vidyasagar"],"a":0,"e":"Raja Radhakant Deb organised the Dharma Sabha in 1830 to counter Brahmo Samaj propaganda and defend socio-religious orthodoxy, including opposing the abolition of sati."})

qs.append({"q":"Consider the following statements about the features of the Brahmo Samaj:\n1. It denounced polytheism and idol worship.\n2. It denied ultimate authority to any scripture over human reason.\n3. It took a fixed position affirming karma and transmigration of the soul as compulsory beliefs.\n4. It criticised the caste system.\nHow many of the above statements are correct?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 4 are correct. Statement 3 is incorrect — the Samaj took no definite stand on karma and transmigration, leaving it to individual Brahmos to believe either way."})

qs.append({"q":"Maharishi Debendranath Tagore, who gave the Brahmo Samaj new life after joining in 1842, earlier headed which organisation founded in 1839?","o":["Tattvabodhini Sabha","Atmiya Sabha","Paramahansa Mandali","Sadharan Brahmo Samaj"],"a":0,"e":"Debendranath Tagore headed the Tattvabodhini Sabha (1839), whose organ Tattvabodhini Patrika propagated Rammohan Roy's ideas with a rationalist study of India's past."})

qs.append({"q":"Keshab Chandra Sen was dismissed as acharya of the Brahmo Samaj in 1865 mainly because of his:","o":["Radical views such as cosmopolitanisation of worship and support for inter-caste marriages, opposed by Debendranath Tagore","Support for sati","Opposition to widow remarriage","Refusal to accept the doctrine of monotheism"],"a":0,"e":"Debendranath Tagore disapproved of Keshab's radicalism, including incorporating teachings of all religions and strong support for inter-caste marriage, leading to his dismissal in 1865."})

qs.append({"q":"After Keshab Chandra Sen's controversial marriage of his minor daughter to the Maharaja of Cooch-Behar in 1878 with orthodox Hindu rituals, disgusted followers set up which new organisation?","o":["Sadharan Brahmo Samaj","Adi Brahmo Samaj","Brahmo Samaj of India","Arya Samaj"],"a":0,"e":"After the Cooch-Behar marriage controversy, followers formed the Sadharan Brahmo Samaj in 1878, led by Ananda Mohan Bose, Shibchandra Deb and Umesh Chandra Datta."})

qs.append({"q":"Match the following Brahmo Samaj offshoots with their founders/context:\n1. Brahmo Samaj of India (1866) - Keshab Chandra Sen\n2. Adi Brahmo Samaj - Debendranath Tagore's original samaj\n3. Sadharan Brahmo Samaj (1878) - Ananda Mohan Bose and others\nHow many of the above pairs are correctly matched?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three pairs are correctly matched, tracing the successive splits within the Brahmo movement."})

qs.append({"q":"The Prarthana Samaj, founded in Bombay in 1867 with the help of Keshab Chandra Sen, was preceded by which precursor organisation?","o":["Paramahansa Sabha","Atmiya Sabha","Tattvabodhini Sabha","Satyashodhak Samaj"],"a":0,"e":"The Paramahansa Sabha, a secret society for spreading liberal ideas and breaking caste barriers, was a precursor to the Prarthana Samaj in Maharashtra."})

qs.append({"q":"Mahadeo Govind Ranade, whose efforts gave the Prarthana Samaj an all-India character, worked on which of the following four-point social agendas of the Samaj?","o":["Disapproval of caste, women's education, widow remarriage, and raising the marriage age","Abolition of temple worship, opposition to Sanskrit learning, denial of the Vedas, and support for polygamy","Political independence, land reform, industrialisation, and universal suffrage","Conversion of lower castes to Christianity, English-only education, and abolition of Hindu law"],"a":0,"e":"The Prarthana Samaj's social agenda included disapproval of caste, women's education, widow remarriage and raising the age of marriage for both sexes."})

qs.append({"q":"The Young Bengal Movement of the late 1820s-1830s was led and inspired by which young Anglo-Indian teacher at Hindu College?","o":["Henry Vivian Derozio","David Hare","Alexander Duff","Ishwar Chandra Vidyasagar"],"a":0,"e":"Henry Vivian Derozio, who taught at Hindu College (1826-31), inspired the radical, rationalist Young Bengal Movement before being removed for his radicalism."})

qs.append({"q":"Which of the following is cited as a key reason for the limited long-term impact of the Derozians (Young Bengal Movement)?","o":["Their radicalism was largely bookish and lacked real links with the masses, including failure to take up the peasants' cause","They had strong support from the peasantry but lacked intellectual leadership","They were suppressed violently by the British government","They focused exclusively on economic issues and ignored social reform"],"a":0,"e":"The Derozians' radicalism, while intellectually bold, remained largely bookish and disconnected from the masses; they failed to engage with the peasantry's concerns."})

qs.append({"q":"Ishwar Chandra Vidyasagar, as principal of Sanskrit College from 1850, is notable for:","o":["Opening the Sanskrit College to non-Brahmins to break the priestly monopoly of scriptural knowledge","Founding the Arya Samaj","Leading the Wahabi Movement","Establishing the Theosophical Society in India"],"a":0,"e":"Vidyasagar opened Sanskrit College to non-Brahmins, seeking to break the priestly monopoly over scriptural knowledge, alongside his work on widow remarriage and women's education."})

qs.append({"q":"Balshastri Jambhekar, known as the father of Marathi journalism, started which newspaper in 1832 to spread awareness of social reforms?","o":["Darpan","Kesari","Rast Goftar","Hitavada"],"a":0,"e":"Balshastri Jambhekar started Darpan in 1832 in Bombay to spread social reform awareness and scientific thinking; he later started Digdarshan (1840) on scientific and historical subjects."})

qs.append({"q":"The Paramahansa Mandali, founded in 1849 in Maharashtra by Dadoba Pandurang and Mehtaji Durgaram, is particularly notable for its members':","o":["Practice of taking food cooked by lower-caste people at their meetings to break caste rules","Insistence on strict vegetarianism as an article of faith","Rejection of widow remarriage as un-Hindu","Alliance with orthodox Dharma Sabha"],"a":0,"e":"Members of the Paramahansa Mandali deliberately took food cooked by lower-caste people at their meetings as a practical means of breaking caste rules."})

qs.append({"q":"Jyotiba Phule founded the Satyashodhak Samaj (Truth Seekers' Society) in 1873, drawing its leadership mainly from:","o":["Backward classes such as malis, telis, kunbis, saris and dhangars","Brahmin scholars and priests","Wealthy zamindars and moneylenders","British-educated civil servants"],"a":0,"e":"The Satyashodhak Samaj's leadership came from backward classes — malis, telis, kunbis, saris and dhangars — reflecting its anti-Brahminical, mass-based orientation."})

qs.append({"q":"Which of Jyotiba Phule's works used the symbol of Raja Bali, as opposed to the Brahminical symbol of Rama, to inspire the common masses?","o":["Gulamgiri and Sarvajanik Satyadharma","Satyarth Prakash","Precepts of Jesus","Tahdhib-ul-Akhlaq"],"a":0,"e":"Phule's works Sarvajanik Satyadharma and Gulamgiri used the symbol of Raja Bali to inspire the depressed masses against Brahminical domination, and he was given the title 'Mahatma' for his social work."})

qs.append({"q":"Gopalhari Deshmukh, known by his pen name 'Lokahitawadi', is remembered for the statement:","o":["\"If religion does not sanction social reform, then change religion.\"","\"Back to the Vedas.\"","\"As many faiths, so many paths.\"","\"Educate, Agitate, Organise.\""],"a":0,"e":"Lokahitawadi (Gopalhari Deshmukh) argued for changing religion itself if it obstructed social reform, reflecting his rationalist, reformist stance."})

qs.append({"q":"Gopal Ganesh Agarkar, a co-founder of the Deccan Education Society and Fergusson College, later started which periodical opposing untouchability and caste?","o":["Sudharak","Kesari","Darpan","Hitavada"],"a":0,"e":"Agarkar, the first editor of Kesari (founded by Tilak), later started his own periodical Sudharak to campaign against untouchability and caste."})

qs.append({"q":"The Servants of India Society, founded in 1905 by Gopal Krishna Gokhale with the help of M.G. Ranade, aimed to:","o":["Train national missionaries devoted to selfless service of the country while staying aloof from political organisations like the INC","Directly lead the Indian National Congress","Organise armed resistance against British rule","Focus exclusively on temple entry issues in South India"],"a":0,"e":"The Servants of India Society trained selfless national workers for constitutional service to India but deliberately remained aloof from political bodies like the Congress."})

qs.append({"q":"Narayan Malhar Joshi, a follower of Gokhale, founded the Social Service League in Bombay and later also founded which major labour organisation in 1920?","o":["All India Trade Union Congress","Servants of India Society","Self-Respect Movement","Justice Movement"],"a":0,"e":"Narayan Malhar Joshi founded the Social Service League and later the All India Trade Union Congress (AITUC) in 1920."})

qs.append({"q":"The Ramakrishna Mission, founded by Swami Vivekananda in 1897 to fulfil the second objective of the Ramakrishna movement, has its headquarters (along with the Ramakrishna Math) at:","o":["Belur, near Calcutta","Aligarh","Lahore","Adyar, Madras"],"a":0,"e":"The Ramakrishna Math and Mission have their headquarters at Belur, near Calcutta, established after Vivekananda acquired land there in 1898."})

qs.append({"q":"Which of the following best captures Ramakrishna Paramahamsa's central spiritual teaching, as reflected in his sayings?","o":["\"As many faiths, so many paths\" — recognising the fundamental oneness of all religions","\"Back to the Vedas\" — insisting on the sole authority of Vedic scripture","\"Educate, Agitate, Organise\" — emphasising political mobilisation","\"One religion, one caste, one God for mankind\" — a call for religious unification of castes"],"a":0,"e":"Ramakrishna Paramahamsa taught that Krishna, Hari, Ram, Christ and Allah are different names for the same God, summarised in his statement 'As many faiths, so many paths.'"})

qs.append({"q":"At the Parliament of Religions held in Chicago in 1893, Swami Vivekananda's keynote address emphasised:","o":["The need for a healthy balance between spiritualism and materialism, blending Western materialism with Eastern spiritualism","The exclusive superiority of Hinduism over all other world religions","The necessity of converting Western audiences to Hinduism","A rejection of all Western scientific and technological advances"],"a":0,"e":"Vivekananda's Chicago address called for a harmonious blend of Western materialism and Eastern spiritualism to produce happiness for all mankind."})

qs.append({"q":"Which of the following distinguishes the Ramakrishna Mission from the Arya Samaj, as noted in the chapter?","o":["The Ramakrishna Mission recognises the utility and value of image worship, unlike the Arya Samaj which rejected idolatry","The Ramakrishna Mission rejected the Vedas while the Arya Samaj upheld them","The Ramakrishna Mission was founded before the Arya Samaj","The Arya Samaj was founded by Vivekananda"],"a":0,"e":"Unlike the Arya Samaj, which strongly opposed idolatry, the Ramakrishna Mission recognises the value of image worship in developing spiritual fervour, while emphasising the essential spirit over rituals."})

qs.append({"q":"Dayananda Saraswati, founder of the Arya Samaj (first unit established at Bombay in 1875), gave which famous slogan calling for a revival of Vedic learning and purity?","o":["\"Back to the Vedas\"","\"As many faiths, so many paths\"","\"One religion, one caste, one God for mankind\"","\"Service of man is the service of God\""],"a":0,"e":"Dayananda's slogan 'Back to the Vedas' called for reviving Vedic learning and religious purity, not a literal revival of Vedic-era society."})

qs.append({"q":"Dayananda Saraswati's views were expounded in his famous work:","o":["Satyarth Prakash","Gulamgiri","Tahdhib-ul-Akhlaq","Precepts of Jesus"],"a":0,"e":"Dayananda Saraswati's Satyarth Prakash (The True Exposition) laid out his vision for a classless, casteless, united and religiously reformed India."})

qs.append({"q":"According to Dayananda Saraswati's interpretation of the chaturvarna system, a person's varna (brahmin, kshatriya, vaishya or shudra) was to be determined by:","o":["Occupation and merit, not birth","Birth alone, as in traditional practice","Wealth and property ownership","Region of residence"],"a":0,"e":"Dayananda subscribed to a Vedic notion of chaturvarna based on occupation and merit rather than birth, differing from the hereditary caste system."})

qs.append({"q":"The Arya Samaj split in 1893 primarily over differences regarding the curriculum of which institution, leading to the College Party and the Mahatma (Gurukul) Party?","o":["Dayananda Anglo-Vedic (D.A.V.) College, Lahore","Aligarh's Mohammedan Anglo-Oriental College","Fergusson College, Poona","Darul Uloom, Deoband"],"a":0,"e":"The Arya Samaj split in 1893 over the D.A.V. College curriculum — the College Party favoured English/government curriculum while the Mahatma/Gurukul Party favoured Vedic/Sanskrit-based education."})

qs.append({"q":"Swami Shraddhanand (Lala Munshi Ram), leader of the Mahatma/Gurukul faction of the Arya Samaj, established the Gurukul Kangri near Haridwar after initially founding a gurukul in 1900 at:","o":["Gujaranwala, West Punjab","Lahore","Aligarh","Deoband"],"a":0,"e":"Swami Shraddhanand founded the original gurukul at Gujaranwala in 1900, later moved to Kangri near Haridwar in 1902, giving rise to the name Gurukul Kangri."})

qs.append({"q":"The shuddhi (purification) movement launched by the Arya Samaj aimed to:","o":["Reconvert Christian and Muslim converts back to the Hindu fold and uplift those regarded as untouchables into caste Hindu status","Convert Hindus to Christianity","Establish separate Muslim educational institutions","Promote inter-religious marriages between Hindus and Muslims"],"a":0,"e":"The shuddhi movement sought to reconvert converts to Christianity and Islam back to Hinduism, and also aimed to bring untouchables into the fold of caste Hindus, though it later contributed to communal tensions."})

qs.append({"q":"The Seva Sadan, founded in 1908 by the Parsi reformer B.M. Malabari along with Diwan Dayaram Gidumal, primarily served:","o":["Exploited and discarded women, providing education, medical and welfare services across castes","Orphaned children of freedom fighters","Widowed Brahmin men seeking remarriage","Muslim peasants displaced by indigo planters"],"a":0,"e":"The Seva Sadan catered to women who had been exploited and then discarded by society, offering education, medical and welfare services regardless of caste."})

qs.append({"q":"The Sree Narayana Dharma Paripalana (SNDP) movement, launched among the Ezhavas of Kerala, is associated with which symbolic act performed by Narayana Guru at Aruvippuram in 1888?","o":["Installing a stone taken from the Neyyar river as a Sivalinga, asserting that idol consecration was not the monopoly of higher castes","Burning the Manusmriti in public","Leading a satyagraha to open the Vaikom temple roads","Founding the Ezhava Memorial demanding job reservation"],"a":0,"e":"Narayana Guru installed a stone as a Sivalinga at Aruvippuram in 1888 to demonstrate that consecrating an idol was not an exclusive Brahminical privilege — sparking the Aruvippuram movement."})

qs.append({"q":"Which poet became a notable disciple of Narayana Guru and later served as general secretary of the SNDP Yogam (registered 1903)?","o":["Kumaran Asan","Subramaniyam Tirumambu","T.K. Madhavan","K. Kelappan"],"a":0,"e":"Kumaran Asan, a famous poet, was a disciple of Narayana Guru and became the general secretary of the SNDP Yogam."})

qs.append({"q":"The Vaikom Satyagraha of 1924 in Kerala, reinforced by jathas from Punjab and Madurai and supported by Gandhi's tour, demanded:","o":["Throwing open Hindu temples and roads to untouchables","Reservation of government jobs for non-Brahmins","Abolition of the zamindari system in Travancore","Formation of a separate legislature for depressed classes"],"a":0,"e":"The Vaikom Satyagraha (1924), led by K.P. Kesava, demanded that Hindu temples and the roads around them be opened to untouchables in Travancore."})

qs.append({"q":"The temple entry movement of 1931, in which poet Subramaniyam Tirumambu (the 'singing sword of Kerala') led volunteers to Guruvayur, culminated in which proclamation of 1936?","o":["The Maharaja of Travancore's proclamation opening all government-controlled temples to all Hindus","The Government of India Act's provision for reserved seats","The Sikh Gurudwaras Act transferring gurudwara control to the SGPC","The Age of Consent Act raising the marriage age"],"a":0,"e":"On November 12, 1936, the Maharaja of Travancore issued a proclamation throwing open all government-controlled temples to all Hindus, a landmark outcome of the temple entry movement."})

qs.append({"q":"The Self-Respect Movement, started by E.V. Ramaswamy Naicker in the mid-1920s, sought to undermine Brahminical dominance chiefly by:","o":["Formalising weddings without Brahmin priests","Establishing separate temples for non-Brahmins only","Advocating armed rebellion against zamindars","Promoting Sanskrit education among non-Brahmins"],"a":0,"e":"Periyar's Self-Respect Movement rejected Brahminical ritual authority, notably by conducting weddings without Brahmin priests."})

qs.append({"q":"The Indian Social Conference, founded by M.G. Ranade and Raghunath Rao, functioned effectively as:","o":["The social reform cell of the Indian National Congress, meeting annually at the same venue as the INC","A rival political party to the Congress","An exclusively Muslim reform body","A purely religious organisation with no social agenda"],"a":0,"e":"The Indian Social Conference met annually alongside the INC session from 1887, focusing on social reform issues like inter-caste marriage and the 'Pledge Movement' against child marriage."})

qs.append({"q":"The Wahabi/Walliullah Movement, inspired by Shah Walliullah's teachings, initially directed its activities against the Sikhs in Punjab, but after 1849 turned its focus against:","o":["The British, following the British annexation of Punjab","The Marathas","The Deoband ulema","The Aligarh Movement"],"a":0,"e":"After the British annexation of Punjab in 1849, the Wahabi Movement redirected its efforts against British rule, playing a role in spreading anti-British sentiment during 1857."})

qs.append({"q":"Titu Mir (Mir Nithar Ali), a disciple of Syed Ahmed Barelvi, organised Muslim peasants of Bengal chiefly against:","o":["Hindu landlords and British indigo planters","Wahabi missionaries","The Faraizi leadership","The Aligarh Movement"],"a":0,"e":"Titu Mir mobilised Muslim peasants against the mostly Hindu landlords and British indigo planters in Bengal, before being killed in 1831."})

qs.append({"q":"The Faraizi Movement, founded by Haji Shariatullah in 1818 in East Bengal, became revolutionary and organised under the leadership of his son:","o":["Dudu Mian","Titu Mir","Syed Ahmed Barelvi","Shah Abdul Aziz"],"a":0,"e":"Dudu Mian, son of Haji Shariatullah, gave the Faraizi Movement an organisational structure from village to provincial level and led its revolutionary phase from 1840 onward."})

qs.append({"q":"The Ahmadiyya Movement, founded by Mirza Ghulam Ahmad in 1889, is distinctive among Islamic sects for its belief that:","o":["The Messiah had come in the person of Mirza Ghulam Ahmad to end religious wars and reinstate morality","Jihad against non-Muslims is a fundamental religious duty","India must be converted into dar-ul-Islam by force","The four schools of Muslim jurisprudence should remain separate"],"a":0,"e":"The Ahmadiyya community uniquely believes the Messiah appeared as Mirza Ghulam Ahmad, and it opposed jihad against non-Muslims while promoting liberal, universalist principles."})

qs.append({"q":"Sir Syed Ahmed Khan, founder of the Aligarh Movement, established the Mohammedan Anglo-Oriental College at Aligarh (later Aligarh Muslim University) in:","o":["1875","1866","1905","1920"],"a":0,"e":"Sir Syed Ahmed Khan founded the Mohammedan Anglo-Oriental College at Aligarh in 1875, later developing into Aligarh Muslim University."})

qs.append({"q":"Sir Syed Ahmed Khan opposed active political participation by Muslims in the immediate term mainly because:","o":["He believed Muslims should first focus on education and employment before engaging in politics to avoid inviting government hostility","He supported the Indian National Congress's political programme fully","He believed Islam forbade any political engagement with a non-Muslim government","He wanted Muslims to join the Wahabi Movement instead"],"a":0,"e":"Syed Ahmed Khan felt Muslims needed to catch up educationally and economically with Hindus before engaging in politics, fearing premature political activity would invite government hostility."})

qs.append({"q":"The Deoband Movement, founded at the Darul Uloom in Saharanpur district in 1866 by Mohammad Qasim Nanotavi and Rashid Ahmed Gangohi, differed from the Aligarh Movement in that it:","o":["Aimed at moral and religious regeneration of Muslims through original Islamic education, rather than Western education and government support","Welcomed British patronage and supported Syed Ahmed Khan's organisations","Rejected the formation of the Indian National Congress","Advocated exclusively for Western scientific curricula"],"a":0,"e":"Unlike Aligarh, which sought Muslim welfare via Western education and British support, Deoband aimed at religious and moral regeneration through traditional Islamic learning, and it welcomed the formation of the INC, issuing a fatwa against Syed Ahmed Khan's organisations in 1888."})

qs.append({"q":"The Rahnumai Mazdayasnan Sabha (1851), a Parsi reform association whose leaders included Dadabhai Naoroji and Naoroji Furdonji, aimed at:","o":["Regeneration of Parsi social conditions and restoration of Zoroastrian religion to its pristine purity","Establishing Islamic law among the Parsi community","Converting Parsis to Christianity","Founding a new syncretic religion combining Hinduism and Zoroastrianism"],"a":0,"e":"The Rahnumai Mazdayasnan Sabha sought both social regeneration of the Parsi community and restoration of Zoroastrianism to its original purity, spreading its message via the newspaper Rast Goftar."})

qs.append({"q":"The Singh Sabha Movement, founded at Amritsar in 1873, had which two-fold objective?","o":["Spreading modern Western education among Sikhs and countering the proselytising activities of Christian, Brahmo, Arya Samaj and Muslim missionaries","Establishing a separate Sikh state and abolishing the SGPC","Merging Sikhism with the Arya Samaj","Promoting the Wahabi ideology among Sikhs"],"a":0,"e":"The Singh Sabha Movement aimed to spread modern education among Sikhs via Khalsa schools and to resist proselytising efforts by other religious missionaries."})

qs.append({"q":"The Akali Movement (Gurudwara Reform Movement), an offshoot of the Singh Sabha Movement, led to the passage of which Act in 1922, giving gurudwara control to the Sikh masses through the SGPC?","o":["Sikh Gurudwaras Act, 1922","Government of India Act, 1919","Indian Councils Act, 1909","Religious Endowments Act, 1863"],"a":0,"e":"The non-violent Akali satyagraha (from 1921) against corrupt Udasi mahants led to the Sikh Gurudwaras Act, 1922 (amended 1925), which vested gurudwara control in the Shiromani Gurudwara Prabandhak Committee (SGPC)."})

qs.append({"q":"The Theosophical Society, founded in New York in 1875 by Madame H.P. Blavatsky and Colonel M.S. Olcott, shifted its headquarters in 1882 to:","o":["Adyar, on the outskirts of Madras","Belur, near Calcutta","Aligarh","Lahore"],"a":0,"e":"The Theosophical Society moved its headquarters to Adyar, near Madras, in 1882."})

qs.append({"q":"Annie Besant, who became president of the Theosophical Society after Olcott's death in 1907, laid the foundation of the Central Hindu College at Benaras in 1898, which later became the nucleus for:","o":["Benaras Hindu University (1916)","Aligarh Muslim University","Gurukul Kangri","Fergusson College"],"a":0,"e":"Annie Besant's Central Hindu College at Benaras (1898) became the nucleus for the founding of Benaras Hindu University in 1916."})

qs.append({"q":"Which of the following is identified as a major limitation (negative aspect) of the 19th-20th century socio-religious reform movements as a whole?","o":["Their narrow social base, being confined largely to the educated urban middle classes while ignoring the peasantry and urban poor","Their complete failure to address the position of women","Their total rejection of religious authority and tradition","Their exclusive focus on economic issues at the expense of social reform"],"a":0,"e":"A key limitation was the narrow social base of these movements — confined mainly to the educated, urban middle classes — leaving the vast peasantry and urban poor largely untouched."})

qs.append({"q":"According to the chapter's assessment, the tendency of Hindu reformers to confine their praise to ancient Indian history, while some Muslim reformers looked to medieval or West Asian history for pride, contributed to:","o":["A notion of two separate peoples and increased communal consciousness","Complete religious unity between Hindus and Muslims","The rapid decline of all religious identities","Universal acceptance of a single composite Indian culture"],"a":0,"e":"This selective historical emphasis by different communities is cited as a factor that reinforced a sense of two separate peoples, contributing to the growth of communal consciousness alongside national consciousness."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_socio_cultural_survey",
    "title": "A General Survey of Socio-Cultural Reform Movements",
    "desc": "Reform movements among Hindus, Muslims, Parsis and Sikhs, key leaders and organisations, and the significance of the reform movements",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch9_socio_cultural_survey.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
