import json

qs = []

# ==================================================================
# History (UPSC) — Chapter 2: Major Approaches to the History of Modern India
# Source: Spectrum, "A Brief History of Modern India", Chapter 2
# ==================================================================

qs.append({"q":"Consider the following characteristics commonly attributed to the 'Colonial' (or Imperialist) approach/historiography of Indian history:\n1. An 'Orientalist' representation of India\n2. The view that the British brought unity to India\n3. Reliance on notions of Social Darwinism, portraying the English as the 'fittest to rule'\n4. Emphasis on the internal contradictions and inner class divisions within Indian society\nHow many of the above are genuine characteristics of the Colonial approach?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are genuine characteristics of the Colonial approach, along with viewing India as a stagnant society needing British guidance ('White Man's burden') and the idea of establishing 'Pax Britannica'. Statement 4 (emphasis on inner class contradictions) is actually a hallmark of the MARXIST approach, not the Colonial approach."})

qs.append({"q":"Which one of the following historians is NOT correctly associated with the Colonial/Imperialist school of historiography?","o":["Ranajit Guha","James Mill","Mountstuart Elphinstone","Vincent Smith"],"a":0,"e":"James Mill, Mountstuart Elphinstone and Vincent Smith are cited examples of colonial historiography. Ranajit Guha, by contrast, founded the SUBALTERN school of historiography in the early 1980s as a critique of elitist historical traditions, including colonial historiography."})

qs.append({"q":"With reference to the Nationalist approach/historiography of Indian history, which one of the following statements is correct?","o":["Nationalist historians of MODERN India did not exist before 1947; prior to independence, nationalist historiography mainly dealt with the ancient and medieval periods of Indian history","Nationalist historiography of modern India was fully developed well before 1900, predating the colonial approach itself","R.C. Majumdar and Tara Chand were prominent Marxist, not nationalist, historians","The nationalist approach emerged independently of, and with no relationship to, the colonial approach"],"a":0,"e":"The text explicitly states that nationalist historians of MODERN India did not exist before 1947 — pre-independence nationalist historiography focused on ancient and medieval India. R.C. Majumdar and Tara Chand were noted NATIONALIST (not Marxist) historians of modern India, and the nationalist approach developed specifically as a response to and in confrontation with the colonial approach."})

qs.append({"q":"Consider the following economic critics of colonial rule active in the last quarter of the 19th century, associated with developing a scientific critique of the adverse economic effects of British rule in India:\n1. Dadabhai Naoroji\n2. M.G. Ranade\n3. R.C. Dutt\n4. G.K. Gokhale\nHow many of the above are correctly identified as such early nationalist economic critics?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four — along with G.V. Joshi, K.T. Telang, and D.E. Wacha — are cited as the group of nationalists who developed a detailed and scientific critique of colonialism's adverse economic aspects in the late 19th century."})

qs.append({"q":"Which one of the following pairs of an early account of the Indian national movement and its author is correctly matched, as per the book's classification of 'nationalist leaders (not historians)'?","o":["Pattabhi Sitaramayya — an account of the national movement","R.C. Majumdar — an account of the national movement, being a nationalist leader rather than historian","A.R. Desai — an account of the national movement, being a nationalist leader rather than historian","Ranajit Guha — an account of the national movement, being a nationalist leader rather than historian"],"a":0,"e":"Pattabhi Sitaramayya (along with R.G. Pradhan, A.C. Mazumdar, and J.L. Nehru) is cited as a nationalist LEADER (not a professional historian) who wrote an account of the national movement. R.C. Majumdar was a nationalist HISTORIAN, A.R. Desai a Marxist historian, and Ranajit Guha the founder of the Subaltern school — none of these three are the 'leader, not historian' category referenced."})

qs.append({"q":"Which one of the following pairs of a Marxist historiographical work and its author/year of first publication is correctly matched?","o":["India Today — Rajni Palme Dutt, first published in England in 1940 (later published in India in 1947)","Social Background of Indian Nationalism — Rajni Palme Dutt, first published in 1940","India Today — A.R. Desai, first published in 1948","Social Background of Indian Nationalism — first published only after India's independence in 1950"],"a":0,"e":"India Today by Rajni Palme Dutt was first published in England in 1940 (for the Left Book Club) and later published in India in 1947. Social Background of Indian Nationalism was written by A.R. Desai (not Dutt) and first published in 1948, not 1940 or 1950."})

qs.append({"q":"Which one of the following criticisms has the Marxist historian Sumit Sarkar levelled against Rajni Palme Dutt's historiographical paradigm?","o":["That it represents a 'simplistic version of the Marxian class approach', with nationalist leaders acting as a kind of proxy for as-yet-passive social forces they had little organic connection with","That Dutt's paradigm gave excessive weight to caste and gender divisions at the expense of class analysis","That Dutt's paradigm entirely ignored the anti-imperialist contradiction in favour of class struggle alone","That Dutt failed to write about the Indian national movement at all"],"a":0,"e":"Sumit Sarkar criticised R.P. Dutt's paradigm as a 'simplistic version of the Marxian class approach', viewing nationalist leaders (the intelligentsia) as a kind of proxy for passive social forces with which they had little organic connection — Dutt's actual shortcoming, per the text, was an inability to fully integrate the primary anti-imperialist contradiction with secondary inner class contradictions, tending to over-emphasise the latter, not ignore imperialism."})

qs.append({"q":"A.R. Desai's analysis of the growth of the Indian national movement structured it around how many distinct phases, each based on the particular social classes that supported and sustained the movement at that stage?","o":["Five","Three","Seven","Two"],"a":0,"e":"A.R. Desai traced the growth of the national movement in FIVE phases, each phase defined by the particular social classes that supported and sustained it at that stage."})

qs.append({"q":"With reference to the Subaltern school of historiography, founded under the editorship of Ranajit Guha in the early 1980s, which one of the following statements is correct?","o":["It holds that the fundamental contradiction in colonial India was between the elite (Indian and foreign) and subaltern groups, and rejects the idea that Indian society could be analysed purely in class terms since capitalism was only nascent at the time","It fully endorses the Marxist theory of class-based exploitation as the primary explanatory framework for Indian nationalism","It views the Indian National Congress-led movement as a genuinely unified, all-class anti-imperialist struggle","It argues that Indian historiography, prior to its emergence, had a distinctly subaltern (rather than elitist) bias"],"a":0,"e":"The Subaltern school posits an elite-versus-subaltern contradiction as fundamental (not simply colonialism-versus-Indian-people), explicitly rejects the Marxist class-based framework since capitalism was still nascent, and views the INC-led movement as an elite-dominated 'bogus' national movement rather than a genuine all-class struggle — its founding premise was that PRIOR Indian historiography (including Marxist writing) had an ELITIST bias, which it sought to correct."})

qs.append({"q":"According to Subaltern historiography, Indian society during the colonial period did NOT experience a single, unified anti-imperialist national movement. Instead, it identifies which one of the following as the two distinct 'streams'?","o":["A genuine anti-imperialist stream of the subalterns, and a 'bogus' elite-led national movement centred on the 'official' leadership of the Indian National Congress","A Hindu nationalist stream and a Muslim nationalist stream","A Marxist proletarian stream and a bourgeois capitalist stream","A rural agrarian stream and an urban industrial stream"],"a":0,"e":"Subaltern historiography posits two distinct streams: the genuine anti-imperialist stream of subaltern groups, and a 'bogus' elite-dominated national movement, which it views as essentially a cloak for an elite struggle for power under the INC's 'official' leadership — this framework is distinct from a Hindu-Muslim, Marxist class-based, or rural-urban dichotomy."})

qs.append({"q":"The 'Communalist' approach to Indian historiography, which relies heavily on colonial-era historiography and textbooks of medieval India, is characterised by which one of the following views?","o":["Hindus and Muslims are portrayed as permanent, mutually hostile groups with antagonistic interests, framing India's medieval history as a continuous story of Hindu-Muslim conflict","It emphasises the shared, syncretic cultural heritage of Hindus and Muslims across medieval and modern India","It focuses primarily on caste-based, rather than religion-based, social divisions","It was developed by Marxist historians as an extension of class-based analysis"],"a":0,"e":"The Communalist approach frames India's medieval history as a continuous Hindu-Muslim conflict, portraying the two communities as permanently hostile and mutually antagonistic — a view the book notes ultimately fed into mutual hatred, communal riots, and contributed to the Partition of India; it is distinct from, and unrelated to, Marxist class analysis or caste-focused frameworks."})

qs.append({"q":"According to the Cambridge School's interpretation of Indian nationalism, which one of the following statements is correct?","o":["The fundamental contradiction under colonial rule was among the Indians themselves, with nationalist leaders driven by a quest for power and material benefits distributed by the British, rather than by genuine anti-colonial struggle","The fundamental contradiction was between British imperialism and the Indian people as a unified whole","Indian nationalism arose purely out of ideological and moral opposition to colonial exploitation","This school has been broadly praised, without significant criticism, for its nuanced treatment of Indian nationalist leaders' motivations"],"a":0,"e":"The Cambridge School views the primary contradiction as being AMONG Indians themselves (competing for British-distributed benefits), framing nationalist leaders as driven by a quest for power and material gain rather than genuine anti-colonial conviction — this view has in fact been criticised by many scholars for reducing nationalism to mere 'animal politics' by stripping out ideals/mind from human behaviour."})

qs.append({"q":"Proponents of the Liberal and Neo-Liberal interpretation of colonial economic history, such as Patrick O'Brien, Hopkins and Cain, argue which one of the following?","o":["The economic exploitation of colonies was not beneficial to the British people as a whole, as overseas capital investment (e.g., in Indian railways) may have discouraged domestic investment and delayed the development of 'new' industries in Britain","Colonial exploitation was overwhelmingly beneficial to the ordinary British working class","Investment in Indian railways significantly accelerated Britain's own industrial development","This school shares the Marxist view that colonialism was primarily driven by class conflict within Britain"],"a":0,"e":"The Liberal/Neo-Liberal interpretation (O'Brien, Hopkins, Cain) argues that colonial economic exploitation was NOT necessarily beneficial to the British people as a whole — capital diverted to overseas colonial investment (like Indian railways) may have discouraged domestic investment and delayed development of newer industries within Britain itself, a view distinct from both a purely triumphalist colonial narrative and the Marxist class-conflict framework."})

qs.append({"q":"With reference to Feminist historiography of Modern India, consider the following statements:\n1. Its emergence is linked to the women's movement of the 1970s, which provided the impetus for women's studies in India.\n2. Pandita Ramabai's 'The High Caste Hindu Woman' (1887) and Katherine Mayo's 'Mother India' (1927) are cited as colonial-period works on the women's question that attracted international attention.\n3. Feminist historiography's research focus has included how colonial legal structures affected women's lives and how denial of ownership of productive resources shaped women's vulnerability.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — Feminist historiography traces its roots to the 1970s women's movement, cites both Ramabai's and Mayo's colonial-era works as internationally significant, and has focused research on colonial legal structures and resource-ownership denial as shapers of women's vulnerability and gender relations."})

qs.append({"q":"Which one of the following is the correct chronological starting point associated with the emergence of the Subaltern school of historiography in India?","o":["Early 1980s, under the editorship of Ranajit Guha","1940, with the publication of Rajni Palme Dutt's India Today","1885, with the founding of the Indian National Congress","1970s, alongside the emergence of the women's movement"],"a":0,"e":"The Subaltern school began in the early 1980s under Ranajit Guha's editorship — distinct from the 1940 Marxist historiographical starting point (Dutt's India Today), the 1885 founding of the INC, or the 1970s emergence of the women's movement (which instead gave rise to Feminist historiography)."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in qs]
print("Total:", len(qs), "| unique:", len(set(texts)))
for q in qs:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch2_approaches.json", "w") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print("Saved.")
