import json

qs = []

qs.append({"q":"The Indian Statutory Commission, popularly known as the Simon Commission, was constituted under the Government of India Act, 1919's provision for a review commission to be appointed:","o":["Ten years from the date of the Act","Immediately upon passage of the Act","Twenty years from the date of the Act","Five years from the date of the Act"],"a":0,"e":"The 1919 Act provided for a review commission ten years after its passage to assess the working of the dyarchy scheme and recommend further reforms."})

qs.append({"q":"The Simon Commission, set up on November 8, 1927 under Stanley Baldwin's Conservative government, was named after its chairman:","o":["Sir John Simon","Lord Birkenhead","Lord Reading","Sir Stanley Baldwin"],"a":0,"e":"The Indian Statutory Commission was popularly called the Simon Commission after its chairman, Sir John Simon."})

qs.append({"q":"Which of the following is identified as a reason for the Conservative government's decision to set up the Simon Commission ahead of schedule?","o":["Fear of electoral defeat by the Labour Party, and a wish to avoid leaving India's constitutional future in 'irresponsible Labour hands'","A direct request from the Indian National Congress","Recommendations of the Nehru Report","Pressure from the Muslim League"],"a":0,"e":"The Conservatives, fearing a Labour victory, wanted to settle India's constitutional question on their own terms before potentially losing power, hence advancing the commission's appointment."})

qs.append({"q":"Which of the following prior inquiries/commissions are correctly matched with their subject of investigation?\n1. Lee Commission - recruitment of British officers\n2. Mudiman Commission - deadlock within the dyarchic dispensation\n3. Linlithgow Commission - crisis of Indian agriculture\nHow many of the above are correctly matched?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three commissions are correctly matched: Lee Commission (officer recruitment), Mudiman Commission (dyarchy deadlock), and Linlithgow Commission (agricultural crisis)."})

qs.append({"q":"The primary reason for the near-unanimous Indian anger against the Simon Commission was:","o":["The complete exclusion of Indians from its membership, seen as a violation of the principle of self-determination","Its recommendation for full dominion status","Its proposal for linguistic provinces","Its stance on separate electorates"],"a":0,"e":"Indians across the political spectrum were angered that an all-white commission would decide India's constitutional future without any Indian representation, seen as an affront to self-respect and self-determination."})

qs.append({"q":"At the Madras session of the Congress (December 1927), presided over by M.A. Ansari, the Congress decided to:","o":["Boycott the Simon Commission 'at every stage and in every form'","Cooperate fully with the Simon Commission","Boycott only the commission's final report","Send a delegation to negotiate terms with the commission"],"a":0,"e":"The Madras Congress session resolved on a complete boycott of the Simon Commission at every stage, reflecting near-unanimous Indian opposition to an all-white commission."})

qs.append({"q":"At the same Madras session (1927), Jawaharlal Nehru succeeded in getting a snap resolution passed declaring which goal for the Congress?","o":["Complete independence","Dominion status","Provincial autonomy","Federal self-government"],"a":0,"e":"Nehru's snap resolution at the 1927 Madras session declared complete independence as the Congress goal, an early marker of the younger leadership's radical ambitions."})

qs.append({"q":"Regarding the Muslim League's response to the Simon Commission, which of the following is correct?","o":["The League split, with Jinnah's faction at Calcutta opposing the commission while Muhammad Shafi's Lahore faction supported the government","The entire League unanimously boycotted the commission","The entire League unanimously supported the commission","The League refused to take any position on the issue"],"a":0,"e":"The Muslim League split into two factions in 1927: Jinnah's group at Calcutta opposed the Simon Commission, while Muhammad Shafi's Lahore faction supported cooperating with the government."})

qs.append({"q":"When the Simon Commission landed in Bombay on February 3, 1928, the Indian response included:","o":["A countrywide hartal, mass rallies, black flag demonstrations and slogans of 'Simon Go Back'","Complete public indifference to its arrival","Official welcome ceremonies organised by the Congress","Immediate cooperation from all political parties"],"a":0,"e":"The commission's arrival triggered a nationwide hartal, black flag protests and the famous 'Simon Go Back' slogan, marking a significant political mobilisation, especially among youth."})

qs.append({"q":"Dr Ambedkar, appointed by the Bombay Legislative Council to engage with the Simon Commission, argued before it (October 1928) for:","o":["Universal adult franchise for both men and women, provincial autonomy, and dyarchy at the Centre","Separate electorates for all minorities without exception","Complete abolition of the Central Legislative Assembly","Immediate dominion status with no further negotiation"],"a":0,"e":"Ambedkar advocated universal adult franchise for both sexes, provincial autonomy, and continued dyarchy at the Centre in his submission to the Simon Commission."})

qs.append({"q":"In his memorandum to the Simon Commission on behalf of the Bahishkrita Hitakarini Sabha, Ambedkar argued that the depressed classes should be regarded as:","o":["A distinct and independent minority, with no link to the Hindu community","An integral part of the Hindu community requiring no special protection","A subgroup entitled only to the same rights as caste Hindus","A group that should merge with the Muslim minority for representation purposes"],"a":0,"e":"Ambedkar contended that the depressed classes constituted a distinct, independent minority, deserving political protection at least equal to that granted to the Muslim minority, given their unique social and economic disabilities."})

qs.append({"q":"According to Ambedkar's submission, if universal adult franchise was not granted, he would campaign for the depressed classes to have:","o":["A separate electorate","No political representation at all","Representation only through nominated members","Joint electorates with no reserved seats"],"a":0,"e":"Ambedkar stated that absent universal franchise, he would demand a separate electorate for the depressed classes, similar to what Muslims had been granted."})

qs.append({"q":"The Simon Commission's report did grant reserved seats to the depressed classes, but attached which condition that displeased Ambedkar?","o":["Candidates had to have their competence endorsed by the provincial governor before contesting","Reserved seats would apply only in provinces where Muslims were also a minority","Depressed class candidates needed to secure Congress party endorsement","No woman could contest from a reserved seat"],"a":0,"e":"The report's requirement that depressed-class candidates get gubernatorial endorsement of their 'competence' was viewed by Ambedkar as patronising and restrictive; in any case the recommendation remained largely a dead letter."})

qs.append({"q":"During the anti-Simon Commission protests, Lala Lajpat Rai suffered fatal injuries from a police lathi-charge in October 1928 and died on:","o":["November 17, 1928","October 30, 1928","December 1928","March 1929"],"a":0,"e":"Lala Lajpat Rai died on November 17, 1928, from injuries sustained during the police lathi-charge on an anti-Simon Commission procession in Lahore."})

qs.append({"q":"Which two rising nationalist leaders were beaten up by police during anti-Simon Commission protests in Lucknow?","o":["Jawaharlal Nehru and G.B. Pant","Subhash Bose and Chandra Shekhar Azad","Bhagat Singh and Rajguru","Motilal Nehru and Vallabhbhai Patel"],"a":0,"e":"Jawaharlal Nehru and G.B. Pant were among those beaten by police during protests against the Simon Commission in Lucknow."})

qs.append({"q":"The Simon Commission published its final two-volume report in:","o":["May 1930","1928","1929","1927"],"a":0,"e":"The Simon Commission's report was published in May 1930, by which time it had been overtaken by subsequent political developments."})

qs.append({"q":"Which of the following was a recommendation of the Simon Commission's report?","o":["Abolition of dyarchy in the provinces, granting them autonomy, while rejecting parliamentary responsibility at the centre","Immediate grant of full dominion status to India","Introduction of universal adult franchise across India","Abolition of separate communal electorates entirely"],"a":0,"e":"The Simon Commission proposed abolishing dyarchy at the provincial level (granting provincial autonomy) but rejected any move towards responsible parliamentary government at the centre."})

qs.append({"q":"Regarding communal electorates, the Simon Commission recommended that separate electorates be:","o":["Retained (and even extended to other communities) until Hindu-Muslim tensions subsided","Abolished immediately and replaced with joint electorates","Retained permanently with no review","Replaced by proportional representation for all communities"],"a":0,"e":"The Commission recommended retaining, and even extending, separate communal electorates until communal tensions eased — a position that disappointed nationalists seeking joint electorates."})

qs.append({"q":"Which of the following territorial recommendations did the Simon Commission make?\n1. Separation of Sindh from Bombay.\n2. Separation of Burma from India.\n3. Local legislatures for the North-West Frontier Province and Baluchistan.\n4. Merger of Bengal and Assam into a single province.\nHow many of the above are correctly identified as Simon Commission recommendations?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect Simon Commission recommendations; a Bengal-Assam merger was never proposed — indeed, the earlier 1905 Bengal partition had already been reversed in 1911."})

qs.append({"q":"In response to Lord Birkenhead's challenge to Indians to draft an agreed constitution, an All Parties Conference in February 1928 appointed a sub-committee under the chairmanship of:","o":["Motilal Nehru","Jawaharlal Nehru","M.A. Ansari","Tej Bahadur Sapru"],"a":0,"e":"Motilal Nehru chaired the sub-committee tasked with drafting India's first indigenous constitutional framework, resulting in the Nehru Report (1928)."})

qs.append({"q":"Which of the following were members of the Nehru Committee that drafted the Nehru Report?\n1. Tej Bahadur Sapru\n2. Subhash Bose\n3. Ali Imam\n4. Muhammad Ali Jinnah\nHow many of the above are correctly listed as committee members?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Sapru, Bose and Ali Imam were members of the Nehru Committee; Jinnah was not a member, though he engaged with the report's proposals separately at the All Parties Conference."})

qs.append({"q":"The Nehru Report's recommendations were unanimous except on one key point, where the majority favoured 'dominion status' while a section (including younger leaders like Jawaharlal Nehru) wanted:","o":["Complete independence as the constitutional basis","Continuation of dyarchy","Retention of separate electorates","A unitary rather than federal structure"],"a":0,"e":"The chief point of disagreement was between dominion status (favoured by the majority) and complete independence (favoured by the younger, more radical section)."})

qs.append({"q":"Regarding electoral representation, the Nehru Report proposed:","o":["Joint electorates with reservation of seats for Muslims only in provinces where they were a minority","Separate electorates for all religious communities","Universal adult suffrage with no reservations of any kind","Reserved seats for Muslims even in Muslim-majority provinces like Punjab and Bengal"],"a":0,"e":"The Nehru Report rejected separate electorates in favour of joint electorates, with reserved Muslim seats only where Muslims were a minority — excluding majority provinces like Punjab and Bengal."})

qs.append({"q":"The Nehru Report proposed a bicameral central legislature with which composition?","o":["A 500-member House of Representatives elected by adult suffrage and a 200-member Senate elected by provincial councils","A 250-member unicameral legislature elected by limited franchise","A 1000-member House with no Senate","A Senate elected directly and a House nominated by the Governor-General"],"a":0,"e":"The Nehru Report envisioned a 500-member House of Representatives (5-year term, elected by adult suffrage) and a 200-member Senate (7-year term, elected by provincial councils)."})

qs.append({"q":"Which of the following was among the 19 fundamental rights proposed in the Nehru Report?","o":["Equal rights for women, right to form unions, and universal adult suffrage","Right to private property without any restriction","Right to secede from the Indian union","Right to maintain separate religious courts"],"a":0,"e":"The Nehru Report's list of 19 fundamental rights included gender equality, the right to unionise, and universal adult suffrage, among others."})

qs.append({"q":"The Nehru Report's stance on the relationship between religion and the State was:","o":["Complete dissociation of State from religion","State support for all major religions equally","Establishment of Hinduism as the state religion","Continuation of separate religious courts under state authority"],"a":0,"e":"The Nehru Report called for complete separation of religion and state, aligning with a broadly secular constitutional vision."})

qs.append({"q":"The 'Delhi Proposals' of December 1927, accepted by the Madras Congress session, included which of the following demands from Muslim leaders?\n1. Joint electorates with reserved Muslim seats.\n2. One-third Muslim representation in the Central Legislative Assembly.\n3. Formation of three new Muslim-majority provinces (Sindh, Baluchistan, NWFP).\n4. Reservation of seats for Hindus in Muslim-majority Punjab and Bengal.\nHow many of the above are correctly listed as part of the Delhi Proposals?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect the Delhi Proposals; there was no demand for reserving Hindu seats in Punjab and Bengal — rather, Muslims sought proportionate representation there."})

qs.append({"q":"The Hindu Mahasabha's opposition to the Delhi Proposals and later the League's demands centred on its rejection of:","o":["New Muslim-majority provinces and Muslim seat reservations in Punjab/Bengal that would ensure Muslim control of those legislatures","Any form of joint electorates","Dominion status as a constitutional goal","The concept of fundamental rights in the constitution"],"a":0,"e":"The Hindu Mahasabha strongly opposed creating new Muslim-majority provinces and proportional Muslim representation in Punjab/Bengal, fearing it would cement Muslim political control there, and it favoured a strictly unitary structure."})

qs.append({"q":"At the All Parties Conference in Calcutta (December 1928), Jinnah proposed three amendments to the Nehru Report, including:","o":["One-third Muslim representation in the central legislature, proportional reservation in Bengal/Punjab till adult suffrage, and residual powers to provinces","Complete rejection of dominion status in favour of immediate independence","Abolition of the Senate in the proposed bicameral legislature","Introduction of a unitary constitutional structure"],"a":0,"e":"Jinnah's three amendments sought one-third Muslim central representation, proportional Muslim reservation in Bengal and Punjab until adult suffrage was achieved, and greater provincial autonomy through residual powers — none of which were accepted."})

qs.append({"q":"Following the rejection of his amendments to the Nehru Report, Jinnah returned to the Shafi faction of the Muslim League and, in March 1929, formulated his famous:","o":["Fourteen Points","Twenty-One Demands","Delhi Proposals","Lahore Resolution"],"a":0,"e":"Jinnah's Fourteen Points (March 1929) became the foundational basis for future Muslim League constitutional demands."})

qs.append({"q":"Which of the following are correctly included among Jinnah's Fourteen Points (1929)?\n1. A federal constitution with residual powers vested in the provinces.\n2. Separate electorates for Muslims.\n3. One-third Muslim representation in the central legislature.\n4. Complete abolition of provincial legislatures.\nHow many of the above are correctly listed?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correctly included among Jinnah's Fourteen Points; the points sought stronger provincial autonomy, not the abolition of provincial legislatures."})

qs.append({"q":"Jinnah's Fourteen Points included a demand that no bill or resolution in any legislature be passed if what proportion of a minority community considered it against their interests?","o":["Three-fourths","One-half","Two-thirds","One-third"],"a":0,"e":"Point 9 of Jinnah's Fourteen Points demanded that no legislative bill or resolution proceed if three-fourths of an affected minority community opposed it — an early demand for a communal veto."})

qs.append({"q":"Following dissatisfaction with the Nehru Report's dominion status recommendation, Jawaharlal Nehru and Subhash Bose jointly set up which organisation?","o":["Independence for India League","Hindustan Socialist Republican Association","All India Trade Union Congress","Punjab Naujawan Bharat Sabha"],"a":0,"e":"Disagreeing with the Congress's dominion-status compromise in the Nehru Report, Nehru and Bose founded the Independence for India League to push for complete independence."})

qs.append({"q":"Which of the following best summarises the overall political impact of the Simon Commission's appointment on the Indian national movement?","o":["It gave a stimulus to radical forces demanding complete independence and socio-economic reform, while also spurring the first Indian attempt at drafting a constitution","It led to immediate and full self-government being granted to India","It ended all communal tensions in Indian politics permanently","It had no effect on Indian political mobilisation whatsoever"],"a":0,"e":"The Simon Commission's all-white composition galvanised both radical nationalist sentiment (demanding full independence) and constructive constitutional efforts (culminating in the Nehru Report), even as communal divisions persisted and ultimately undermined unity."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_simon_commission_nehru_report",
    "title": "Simon Commission and the Nehru Report",
    "desc": "The Simon Commission, Indian responses including Ambedkar's memorandum, government repression, the Nehru Report's recommendations, communal responses, the Delhi Proposals, and Jinnah's Fourteen Points",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch18_simon_commission_nehru_report.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
