import json

qs = []

qs.append({"q":"Consider the following statements regarding the social base of the 19th century reform movements in India:\n1. Their social base was the newly emerging middle class and educated intelligentsia.\n2. This intelligentsia largely grew out of trade and industrial capital.\n3. Their roots mainly lay in government service and professions like law, education, journalism and medicine.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"The reform intelligentsia's base was the emerging middle class rooted in government service and professions (law, education, journalism, medicine), not trade or industry, which remained under British control."})

qs.append({"q":"What gave the 19th century socio-religious reform movements their ideological unity, as identified in the chapter?","o":["Rationalism, religious universalism and humanism","Strict revivalism and rejection of all Western ideas","Marxist class analysis","Exclusive focus on temple entry rights"],"a":0,"e":"Rationalism, religious universalism, and humanism together gave ideological unity to movements as diverse as the Brahmo Samaj and the Aligarh Movement."})

qs.append({"q":"The reform movements of the 19th century are broadly classified into which two categories?","o":["Reformist movements (e.g., Brahmo Samaj, Prarthana Samaj) and revivalist movements (e.g., Arya Samaj, Deoband)","Nationalist movements and communal movements","Rural movements and urban movements","Hindu movements and Muslim movements only"],"a":0,"e":"The chapter classifies reform movements into reformist (Brahmo Samaj, Prarthana Samaj, Aligarh Movement) and revivalist (Arya Samaj, Deoband movement) streams, differing in their reliance on tradition versus reason."})

qs.append({"q":"Which of the following was the earliest legislative measure banning the practice of sati, and to which regions did it originally apply?","o":["Regulation XVII of 1829, applicable first to the Bengal Presidency and extended to Madras and Bombay in 1830","Hindu Widows' Remarriage Act, 1856, applicable across all of British India","Age of Consent Act, 1891, applicable to Bengal only","Sarda Act, 1930, applicable to the whole of India"],"a":0,"e":"Sati was declared illegal by Regulation XVII of 1829 (Bengal Code), first applicable in Bengal Presidency, extended in modified form to Madras and Bombay Presidencies in 1830."})

qs.append({"q":"Raja Rammohan Roy, whose efforts led to the abolition of sati, described the practice as:","o":["\"Murder according to every shastra\"","\"A necessary evil sanctioned by scripture\"","\"An expression of religious devotion\"","\"A dying custom of no social consequence\""],"a":0,"e":"Raja Rammohan Roy strongly condemned sati, describing it as murder according to every shastra."})

qs.append({"q":"Which Bengal regulations first declared female infanticide illegal and equivalent to murder?","o":["Bengal Regulations of 1795 and 1804","Bengal Regulation of 1829","Age of Consent Act, 1891","Native Marriage Act, 1872"],"a":0,"e":"The Bengal Regulations of 1795 and 1804 declared female infanticide illegal, treating it as equivalent to murder."})

qs.append({"q":"The Hindu Widows' Remarriage Act, 1856, which legalised the remarriage of widows, was passed primarily due to the efforts of:","o":["Pandit Ishwar Chandra Vidyasagar","Raja Rammohan Roy","Jyotiba Phule","B.R. Ambedkar"],"a":0,"e":"Pandit Ishwar Chandra Vidyasagar, principal of Sanskrit College Calcutta, was chiefly responsible for the Hindu Widows' Remarriage Act, 1856, citing Vedic texts to justify widow remarriage."})

qs.append({"q":"Which of the following correctly matches the reformer with their contribution to the widow remarriage movement?\n1. Karsondas Mulji - started Satya Prakash in Gujarati to advocate widow remarriage\n2. D.K. Karve - opened a widows' home in Poona and himself married a widow\n3. Vishnu Shastri Pandit - founded the Widow Remarriage Association\nHow many of the above pairs are correctly matched?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three pairs are correctly matched: Karsondas Mulji (Satya Prakash), D.K. Karve (widows' home in Poona, married a widow in 1893), and Vishnu Shastri Pandit (Widow Remarriage Association)."})

qs.append({"q":"The Native Marriage Act (or Civil Marriage Act) of 1872, aimed at controlling child marriage, had a limited impact because:","o":["It was not applicable to Hindus, Muslims and other recognised faiths","It was applied only to Christians and had no relevance to Indian society","It carried no penalty provisions at all","It applied only in the Bombay Presidency"],"a":0,"e":"The Native Marriage Act of 1872 excluded Hindus, Muslims and other recognised faiths from its ambit, sharply limiting its effect on child marriage."})

qs.append({"q":"The Age of Consent Act, 1891, which forbade the marriage of girls below the age of 12, was enacted largely due to the efforts of:","o":["B.M. Malabari","Ishwar Chandra Vidyasagar","Jyotiba Phule","Sri Narayana Guru"],"a":0,"e":"B.M. Malabari, a Parsi reformer, campaigned relentlessly for the Age of Consent Act, 1891."})

qs.append({"q":"The Sarda Act of 1930 raised the minimum age of marriage to:","o":["18 for boys and 14 for girls","21 for boys and 18 for girls","18 for boys and 15 for girls","15 for boys and 12 for girls"],"a":0,"e":"The Sarda Act, 1930 set the minimum marriage age at 18 for boys and 14 for girls; this was later revised by the Child Marriage Restraint (Amendment) Act, 1978, to 21 and 18 respectively."})

qs.append({"q":"Consider the following statements about women's education initiatives in colonial India:\n1. The Calcutta Female Juvenile Society (1819) was set up by Christian missionaries.\n2. The Bethune School (1849), founded by J.E.D. Bethune, was a landmark institution for women's education.\n3. Pandit Ishwar Chandra Vidyasagar was associated with about 35 girls' schools in Bengal.\n4. The Indian Women's University was established by Professor D.K. Karve in 1916.\nHow many of the above statements are correct?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four statements are correct as per the chapter's account of women's education initiatives."})

qs.append({"q":"Charles Wood's Despatch on Education, which laid stress on the need for female education, was issued in:","o":["1854","1870","1882","1904"],"a":0,"e":"Charles Wood's Despatch on Education (1854) emphasised the importance of female education."})

qs.append({"q":"Sarojini Naidu, a leading figure in the women's movement, served as:","o":["President of the Indian National Congress (1925) and later Governor of the United Provinces (1947-49)","Founder of the All India Women's Conference","Principal of Bethune School","Founder of the Arya Mahila Samaj"],"a":0,"e":"Sarojini Naidu became INC president in 1925 and later served as Governor of the United Provinces (1947-49)."})

qs.append({"q":"Sarla Devi Chaudhurani is credited with convening the first meeting of which organisation, considered the first major Indian women's organisation set up by a woman?","o":["Bharat Stree Mahamandal (1910)","All India Women's Conference (1927)","Arya Mahila Samaj","National Council of Women in India"],"a":0,"e":"Sarla Devi Chaudhurani convened the first meeting of the Bharat Stree Mahamandal in Allahabad in 1910, considered the first major Indian women's organisation founded by a woman."})

qs.append({"q":"Pandita Ramabai Saraswati founded which organisation to serve the cause of women, and also advocated for improved educational syllabi before the English Education Commission?","o":["Arya Mahila Samaj","Bharat Stree Mahamandal","All India Women's Conference","Ladies Social Conference"],"a":0,"e":"Pandita Ramabai Saraswati founded the Arya Mahila Samaj and pleaded for reform of the educational syllabus for Indian women before the English Education Commission."})

qs.append({"q":"The All India Women's Conference (AIWC), founded in 1927 and often regarded as the first women's organisation with an egalitarian approach, was founded by:","o":["Margaret Cousins","Sarla Devi Chaudhurani","Pandita Ramabai Saraswati","Ramabai Ranade"],"a":0,"e":"Margaret Cousins founded the AIWC in 1927; its first conference was held at Ferguson College, Pune."})

qs.append({"q":"Which of the following legislative reforms were pursued by the All India Women's Conference before and after India's independence?\n1. Hindu Women's Right to Property Act, 1937\n2. Hindu Marriage and Divorce Act, 1954\n3. Dowry Prohibition Act, 1961\n4. Equal Remuneration Act, 1958/1976\nHow many of the above are correct?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four are correctly listed among the legislative reforms the AIWC worked towards, per the chapter's summary."})

qs.append({"q":"The Ladies Social Conference (Bharat Mahila Parishad), founded in Bombay in 1904 under the parent National Social Conference, was established by:","o":["Ramabai Ranade","Sarla Devi Chaudhurani","Mehribai Tata","Margaret Cousins"],"a":0,"e":"Ramabai Ranade founded the Ladies Social Conference (Bharat Mahila Parishad) in Bombay in 1904."})

qs.append({"q":"Cornelia Sarabji, mentioned in connection with the National Council of Women in India (formed 1925), is notable as:","o":["India's first lady barrister","The founder of the All India Women's Conference","The first woman President of the Indian National Congress","The founder of the Arya Mahila Samaj"],"a":0,"e":"Cornelia Sarabji, who held an important position on the executive committee of the National Council of Women in India, was India's first lady barrister."})

qs.append({"q":"Which of the following factors is identified in the chapter as having (perhaps unintentionally) undermined caste consciousness during British rule?","o":["Creation of private property in land and free sale of land, which upset traditional caste-vocation linkages","Deliberate abolition of the caste system by the colonial government","Complete prohibition of caste-based marriage by British law","Reservation of government jobs exclusively for lower castes"],"a":0,"e":"The introduction of private property in land, free sale of land, modern commerce/industry, urbanisation, and equality before law weakened the traditional link between caste and vocation, without any deliberate colonial intent to abolish caste."})

qs.append({"q":"Which organisation, while crusading against the disintegration of Hindu society into sub-castes, aimed at reconstructing society on the original four-fold (chaturvarna) division while upholding the right of even the lowest castes to study the scriptures?","o":["Arya Samaj","Brahmo Samaj","Prarthana Samaj","Ramakrishna Mission"],"a":0,"e":"The Arya Samaj sought to reconstruct Hindu society on the original chaturvarna basis while upholding the right of all castes, including the lowest, to study the scriptures."})

qs.append({"q":"Jyotiba Phule, who led a movement against Brahminical domination of Hindu society in Maharashtra, belonged to which social background and gave special priority to which cause?","o":["A low-caste Mali family; he prioritised education of lower castes, especially girls","A Brahmin family; he prioritised Sanskrit education","A Kshatriya family; he prioritised military reform","A Parsi family; he prioritised age of consent legislation"],"a":0,"e":"Jyotiba Phule, born in a low-caste Mali family, prioritised educating lower castes and especially girls, opening several schools for this purpose."})

qs.append({"q":"Dr B.R. Ambedkar's Mahad Satyagraha (March 1927) is significant because:","o":["He led about 2,500 'untouchables' to the Chawdar tank in Mahad and drank water from it to assert the right to public water sources","He organised the burning of the Manusmriti for the first time in Indian history","He founded the All India Scheduled Castes Federation as its outcome","It resulted immediately in a constitutional ban on untouchability"],"a":0,"e":"At Mahad, Ambedkar led a procession of about 2,500 untouchables to the Chawdar tank and drank water from it to assert their right to use public water sources previously denied to them."})

qs.append({"q":"Following the Mahad Satyagraha, in December 1927 Dr Ambedkar and his colleagues performed which symbolic act at the same location?","o":["Burnt the Manusmriti","Built a new temple open to all castes","Organised the first All India Depressed Classes Conference","Founded the Bahishkrit Hitakarini Sabha"],"a":0,"e":"In December 1927, Ambedkar and his colleagues burnt the Manusmriti at Mahad as a gesture against caste-based inequality."})

qs.append({"q":"The Bahishkrit Hitakarini Sabha, established by Dr Ambedkar in 1924 to highlight the grievances of the dalits, had which motto?","o":["Educate, Agitate and Organise","Annihilation of Caste","One religion, one caste, one God for mankind","Back to the Vedas"],"a":0,"e":"The motto of the Bahishkrit Hitakarini Sabha, founded by Ambedkar in 1924, was 'Educate, Agitate and Organise'."})

qs.append({"q":"Sri Narayana Guru, who led a lifelong struggle against upper caste domination in Kerala, coined the slogan:","o":["\"One religion, one caste, one God for mankind\"","\"Educate, Agitate, Organise\"","\"Back to the Vedas\"","\"Annihilation of Caste\""],"a":0,"e":"Sri Narayana Guru's slogan was 'One religion, one caste, one God for mankind'; his disciple Sahodaran Ayyappan later modified it to 'no religion, no caste, no God for mankind'."})

qs.append({"q":"The Self-Respect Movement of the 1920s in South India, organised by the non-Brahmins, was led by:","o":["E.V. Ramaswamy Naicker","Jyotiba Phule","B.R. Ambedkar","Sri Narayana Guru"],"a":0,"e":"E.V. Ramaswamy Naicker (Periyar) led the Self-Respect Movement among non-Brahmins in South India during the 1920s."})

qs.append({"q":"The struggle of the depressed classes led to which of the following constitutional/legislative provisions during the colonial period?","o":["Special representation for depressed classes in the Government of India Act, 1935","Universal adult franchise in the Government of India Act, 1935","Reservation in government jobs under the Charter Act, 1833","Abolition of untouchability under the Indian Councils Act, 1909"],"a":0,"e":"The struggle of the depressed classes resulted in special representation being provided for them in the Government of India Act, 1935."})

qs.append({"q":"Consider the following statements regarding caste-related organisational efforts by Dr Ambedkar:\n1. He organised the All India Scheduled Castes Federation.\n2. He established the Bahishkrit Hitakarini Sabha in 1924.\n3. He led the Mahad Satyagraha in 1927.\n4. He founded the All India Harijan Sangh in 1932.\nHow many of the above statements are correctly attributed to Ambedkar?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correctly attributed to Ambedkar. Statement 4 is incorrect — the All India Harijan Sangh (1932) was founded by Mahatma Gandhi, not Ambedkar."})

qs.append({"q":"Which of the following best describes Gandhi's stance on untouchability, as reflected in the chapter?","o":["He argued the Shastras did not sanction untouchability, and even if they did, they should be ignored since truth cannot be confined within a book","He argued that untouchability should be maintained as a religious duty","He believed caste and untouchability should be abolished only through violent revolution","He opposed any reform of caste practices, considering them purely a British concern"],"a":0,"e":"Gandhi held that the Shastras did not sanction untouchability, and even where scriptural sanction seemed to exist, such practices should be rejected on grounds of truth and humanism."})

qs.append({"q":"According to the chapter, the socio-cultural regeneration of 19th century India was:","o":["Occasioned by the colonial presence, but not created by it","Entirely a product of British colonial policy with no indigenous roots","A direct continuation of pre-colonial reform traditions without any Western influence","Solely the result of Christian missionary activity"],"a":0,"e":"The chapter emphasises that the reform movements were occasioned, not created, by the colonial presence — indigenous social conditions and intellectual currents were equally responsible."})

qs.append({"q":"Which of the following organisations/individuals are cited as early instruments of social reform before the national movement took over leadership in this sphere?","o":["The Social Conference, Servants of India Society, Christian missionaries, and individuals like Jyotiba Phule and B.M. Malabari","Only the Indian National Congress","Only the British colonial government","Only religious orthodox organisations opposing reform"],"a":0,"e":"Early social reform was driven by organisations such as the Social Conference, Servants of India Society, Christian missionaries, and reformist individuals like Jyotiba Phule, D.K. Karve, B.M. Malabari and Sri Narayana Guru, before the national movement assumed this leadership role in the twentieth century."})

qs.append({"q":"Which constitutional provision of free India explicitly addresses the abolition of untouchability?","o":["Untouchability is abolished and its practice in any form is forbidden, along with a Directive Principle promoting a just social order","Only a Directive Principle recommends abolishing untouchability, with no enforceable provision","Untouchability is addressed only through ordinary legislation, not the Constitution","The Constitution is silent on untouchability, leaving it to state laws"],"a":0,"e":"The Constitution of free India abolishes untouchability, forbids restrictions based on it (e.g., on wells, tanks, temples), and includes a Directive Principle on securing a just social order."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_socio_religious_general",
    "title": "Socio-Religious Reform Movements: General Features",
    "desc": "Causes, social/ideological bases, women's reform, legislative measures, and struggle against caste-based exploitation",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch8_socio_religious_general.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
