import json

qs = []

qs.append({"q":"After the failure of the Cripps Mission, at which meeting did the CWC accept the idea of launching a struggle against British rule?","o":["Wardha (July 14, 1942)","Bombay AICC session (August 8, 1942)","Ramgarh session (March 1940)","Tripuri session (March 1939)"],"a":0,"e":"The CWC meeting at Wardha on July 14, 1942 accepted the idea of a struggle, which was later ratified by the AICC in Bombay on August 8, 1942."})

qs.append({"q":"Which of the following were among the reasons cited for launching a struggle in 1942?\n1. The failure of the Cripps Mission exposed Britain's unchanged attitude on constitutional advance.\n2. Popular discontent over rising prices, shortages, and commandeering of boats in Bengal and Orissa.\n3. News of British reverses in South-East Asia and fear of an imminent British collapse.\n4. The desire to condition the masses for a possible Japanese invasion.\nHow many of the above are correctly listed as reasons?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors — the Cripps failure, wartime economic hardship, perceived British weakness, and preparation against Japanese invasion — are cited as reasons for launching the movement."})

qs.append({"q":"During the British evacuation from South-East Asia, what practice exposed the racist attitude of colonial rulers, as highlighted in the chapter?","o":["Provision of a separate 'Black Road' for Indian refugees and a 'White Road' exclusively for European refugees","Complete refusal to evacuate any Indian civilians","Forced conscription of all Indian refugees into the British Army","Confiscation of all Indian-owned property in South-East Asia"],"a":0,"e":"The British provided two separate evacuation roads — the Black Road for Indian refugees and the White Road exclusively for Europeans — starkly exposing racist double standards."})

qs.append({"q":"The 'Quit India' Resolution was proposed by whom and seconded by whom at the Wardha CWC meeting?","o":["Proposed by Jawaharlal Nehru and seconded by Sardar Patel","Proposed by Gandhi and seconded by Rajendra Prasad","Proposed by Maulana Azad and seconded by Nehru","Proposed by Subhash Bose and seconded by Patel"],"a":0,"e":"The Quit India Resolution was proposed by Jawaharlal Nehru and seconded by Sardar Patel at Wardha, later ratified by the AICC at Gowalia Tank, Bombay."})

qs.append({"q":"On what date was the Quit India Resolution ratified at the Congress meeting at Gowalia Tank, Bombay?","o":["August 8, 1942","July 14, 1942","August 9, 1942","September 3, 1942"],"a":0,"e":"The Quit India Resolution was ratified at Gowalia Tank, Bombay, on August 8, 1942, with Gandhi named leader of the struggle."})

qs.append({"q":"Which of the following was NOT among the resolutions passed at the Gowalia Tank meeting ratifying Quit India?","o":["Immediate formal alliance with the Muslim League for a joint government","Demand for an immediate end to British rule in India","Commitment of free India to defend itself against Fascism and imperialism","Sanctioning a civil disobedience movement and forming a provisional government after British withdrawal"],"a":0,"e":"The Gowalia Tank resolutions demanded an end to British rule, committed free India to anti-Fascist defence, planned a provisional government, and sanctioned civil disobedience — there was no resolution on a Muslim League alliance."})

qs.append({"q":"Gandhi's instructions to government servants during the Quit India Movement were to:","o":["Not resign but declare their allegiance to the Congress","Immediately resign en masse from all government posts","Actively sabotage government files and records","Join the underground resistance in armed capacity"],"a":0,"e":"Gandhi instructed government servants not to resign, but to openly declare allegiance to the Congress — a more moderate approach than instructions to some other sections."})

qs.append({"q":"What was Gandhi's famous exhortation given at the time of launching the Quit India Movement?","o":["'Do or Die'","'Swaraj is my birthright'","'Inquilab Zindabad'","'Give me blood, I will give you freedom'"],"a":0,"e":"Gandhi gave the mantra 'Do or Die', declaring that India would either be freed or Indians would die in the attempt, rather than accept continued slavery."})

qs.append({"q":"With most senior Congress leaders arrested on August 9, 1942, who presided over the Congress committee session that day and hoisted the flag?","o":["Aruna Asaf Ali","Usha Mehta","Sucheta Kripalani","Kamaladevi Chattopadhyay"],"a":0,"e":"With senior leaders arrested, the relatively unknown Aruna Asaf Ali stepped forward to preside over the Congress committee session and hoist the national flag on August 9, 1942."})

qs.append({"q":"Under which legislation were the Congress Working Committee, AICC, and Provincial Congress Committees declared unlawful associations following the arrests of August 1942?","o":["The Criminal Law Amendment Act of 1908","The Rowlatt Act of 1919","The Government of India Act, 1935","The Defence of India Act, 1915"],"a":0,"e":"The Congress bodies were declared unlawful under the Criminal Law Amendment Act of 1908, while public meetings were banned under rule 56 of the Defence of India Rules."})

qs.append({"q":"Which regions saw the most intense mass activity — such as blowing up bridges, removing railway tracks, and cutting telegraph lines — during the Quit India Movement?","o":["Eastern United Provinces and Bihar","Punjab and Sindh","Kerala and Tamil Nadu","Kashmir and Himachal Pradesh"],"a":0,"e":"Eastern United Provinces and Bihar witnessed the most intense sabotage-style mass activity during the Quit India Movement, including attacks on transport and communication infrastructure."})

qs.append({"q":"Who among the following was known for starting an underground radio station in Bombay during the Quit India Movement?","o":["Usha Mehta","Aruna Asaf Ali","Sucheta Kripalani","Kamala Devi Chattopadhyay"],"a":0,"e":"Usha Mehta started an underground radio in Bombay to maintain morale and provide guidance during the underground phase of the Quit India Movement."})

qs.append({"q":"Match the parallel governments established during Quit India with their leaders/organisers:\n1. Ballia\n2. Tamluk (Midnapore)\n3. Satara\nA. Chittu Pandey\nB. Y.B. Chavan and Nana Patil\nC. Jatiya Sarkar under local leadership\nSelect the correct combination.","o":["1-A, 2-C, 3-B","1-B, 2-A, 3-C","1-C, 2-B, 3-A","1-A, 2-B, 3-C"],"a":0,"e":"Ballia's parallel government was led by Chittu Pandey; Tamluk's Jatiya Sarkar undertook relief and welfare work; Satara's 'Prati Sarkar' was organised under leaders like Y.B. Chavan and Nana Patil."})

qs.append({"q":"Which parallel government, organised as 'Prati Sarkar', ran village libraries, Nyayadan Mandals, and prohibition campaigns, and lasted from mid-1943 to 1945?","o":["Satara","Ballia","Tamluk","Midnapore"],"a":0,"e":"The Satara parallel government, called 'Prati Sarkar', organised village libraries, Nyayadan Mandals (justice-dispensing bodies), and prohibition campaigns from mid-1943 to 1945."})

qs.append({"q":"Which social/political group notably did NOT support the Quit India Movement, instead supporting the British war effort after Russia was attacked by Nazi Germany?","o":["The Communists","The Socialists","The Forward Bloc","Underground revolutionary nationalists"],"a":0,"e":"After Nazi Germany attacked the Soviet Union in June 1941, Indian communists began supporting the British war effort, terming it the 'People's War' rather than an 'Imperialist War', and thus did not join Quit India."})

qs.append({"q":"Regarding communal dynamics during the Quit India Movement, which of the following is correct?","o":["Muslims sheltered underground activists and there were no communal clashes during the movement, even as the Muslim League officially opposed it fearing Hindu domination after a British exit","There were widespread communal riots throughout the movement","The Muslim League actively participated in and led the movement","Muslims were entirely excluded from all participation in the movement"],"a":0,"e":"Despite the Muslim League's official opposition (fearing minority oppression if the British left), ordinary Muslims sheltered underground activists, and there were no communal clashes during the movement."})

qs.append({"q":"Approximately how many people are estimated to have been killed in the government repression of the Quit India Movement?","o":["Around 10,000","Around 1,000","Around 100,000","Around 500"],"a":0,"e":"Government repression, including lathi-charges, tear gas, and firing on crowds, is estimated to have killed around 10,000 people during the Quit India Movement."})

qs.append({"q":"According to the chapter's estimate of Quit India's significance, which of the following is correct?","o":["The movement placed the demand for independence firmly on the immediate national agenda, after which there could be no retreat, even though it lacked centralised leadership once senior leaders were arrested","The movement achieved immediate and complete Indian independence in 1942 itself","The movement was entirely suppressed with no lasting political impact","Only the upper classes and bureaucracy actively participated, while common people remained passive"],"a":0,"e":"Quit India placed independence irrevocably on the immediate agenda; leaderless after mass arrests, it saw high spontaneity, but its deeper significance lay in demonstrating that British rule without Indian consent had become untenable."})

qs.append({"q":"In February 1943, Gandhi undertook a fast primarily as:","o":["A response against the government's exhortation to condemn violence, directed as a protest against state violence","A hunger strike demanding his own release from prison","A protest against the Cripps Mission's proposals","A gesture of solidarity with the victims of the Bengal famine"],"a":0,"e":"Gandhi's February 1943 fast was a response to government pressure that he condemn the movement's violence; he instead directed his fast against the violence of the State itself."})

qs.append({"q":"What was one direct political consequence of Gandhi's 1943 fast?","o":["Three members of the Viceroy's executive council resigned in response","The British immediately released all Congress leaders","The Quit India Movement was formally called off by Gandhi","Britain agreed to grant full dominion status to India"],"a":0,"e":"Gandhi's fast triggered strong public reaction, including the resignation of three members of the Viceroy's executive council, while also raising morale and exposing government high-handedness."})

qs.append({"q":"Which regions were worst affected by the Bengal Famine of 1943, in which an estimated 1.5 to 3 million people perished?","o":["South-west Bengal (Tamluk-Contai-Diamond Harbour), Dacca, Faridpur, Tippera and Noakhali","Only urban Calcutta and its immediate suburbs","Punjab and the North-West Frontier Province","Assam and the north-eastern hill regions"],"a":0,"e":"The famine devastated south-west Bengal and districts including Dacca, Faridpur, Tippera and Noakhali, killing an estimated 1.5 to 3 million people through starvation, malnutrition and disease."})

qs.append({"q":"Which of the following were identified as causes of the 1943 Bengal Famine?\n1. Diversion of foodstuffs to feed a vast wartime army.\n2. Stoppage of rice imports from Burma and South-East Asia after Japanese occupation.\n3. Mismanagement and profiteering, with belated and city-confined rationing.\n4. A total absence of rainfall across all of eastern India that year.\nHow many of the above are correctly listed as causes?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correctly identified causes; the chapter frames the famine as fundamentally man-made through wartime diversion, import stoppage, and administrative failure, not primarily due to drought (statement 4 is not cited)."})

qs.append({"q":"The Rajagopalachari (CR) Formula of 1944 represented what kind of shift in the Congress's position on the communal question?","o":["A tacit acceptance of the Muslim League's demand for Pakistan, conditional on Muslim-majority areas deciding via plebiscite after the war","An outright rejection of any possibility of partition under any circumstances","A demand for the immediate and unconditional creation of Pakistan without any plebiscite","A proposal to permanently postpone any discussion of the communal question"],"a":0,"e":"The CR Formula tacitly accepted the League's Pakistan demand, proposing that Muslim-majority areas in the North-West and North-East decide by plebiscite after the war whether to form a separate sovereign state."})

qs.append({"q":"Why did Jinnah reject the Rajagopalachari (CR) Formula?","o":["He wanted the Congress to explicitly accept the two-nation theory, wanted only Muslims (not the entire population) of the North-West and North-East to vote in the plebiscite, and opposed a common centre","He believed the formula granted the Muslim League too much power over the interim government","He objected to any plebiscite being held at all under any circumstances","He wanted immediate merger of the League with the Congress"],"a":0,"e":"Jinnah demanded explicit Congress acceptance of the two-nation theory, restriction of plebiscite voting to Muslims only (not the whole population), and rejected the idea of a common centre for defence and commerce."})

qs.append({"q":"Who condemned the CR Plan from the Hindu nationalist side?","o":["Vir Savarkar","Madan Mohan Malaviya","Lala Lajpat Rai","K.M. Munshi"],"a":0,"e":"Hindu leaders led by Vir Savarkar condemned the CR Plan for its tacit acceptance of Pakistan's demand."})

qs.append({"q":"The Desai-Liaqat Pact was a draft proposal between which two leaders for forming an interim government at the centre?","o":["Bhulabhai Desai (Congress) and Liaqat Ali Khan (Muslim League)","C. Rajagopalachari and Muhammad Ali Jinnah","Jawaharlal Nehru and Liaqat Ali Khan","Bhulabhai Desai and Mohammad Ali Jauhar"],"a":0,"e":"Bhulabhai Desai, leader of the Congress Party in the Central Legislative Assembly, and Liaqat Ali Khan, deputy leader of the Muslim League, drafted the proposal for an interim central government."})

qs.append({"q":"What was a key proposal of the Desai-Liaqat Pact?","o":["An equal number of Congress and League nominees in the central legislature, with 20% of seats reserved for minorities","Complete Muslim League control of the central government","Abolition of the central legislature altogether","Reservation of 50% of seats exclusively for princely state nominees"],"a":0,"e":"The pact proposed equal numbers of Congress and League nominees in the central legislature, along with a 20% reservation of seats for minorities — establishing a notion of Congress-League parity."})

qs.append({"q":"Why was the British government keen on reaching a constitutional solution around 1945, leading to the Wavell Plan?\n1. General elections were scheduled in England for mid-1945 and the Conservatives wanted to appear sincere.\n2. There was Allied pressure to secure further Indian wartime cooperation.\n3. The government wanted to divert Indian energies into channels profitable to Britain.\n4. Britain had already decided to grant complete independence and needed only a formality.\nHow many of the above are correctly listed as reasons?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly explain British motivations; statement 4 is incorrect, as no decision for complete independence had yet been made at this stage."})

qs.append({"q":"The Wavell Plan was formulated at a conference convened by Viceroy Lord Wavell in June 1945 at:","o":["Shimla","Delhi","Lahore","Bombay"],"a":0,"e":"The Shimla Conference of June 1945, convened by Viceroy Lord Wavell, formulated the Wavell Plan for reconstructing the executive council."})

qs.append({"q":"Which of the following was a key feature of the Wavell Plan?","o":["All members of the executive council, except the governor-general and commander-in-chief, were to be Indians, with equal representation for caste Hindus and Muslims","The council was to function fully outside the framework of the 1935 Act with complete legislative sovereignty","The Congress alone would nominate all executive council members","Defence and finance were to be handed over completely to Indian control immediately"],"a":0,"e":"The Wavell Plan proposed an all-Indian executive council (barring the governor-general and commander-in-chief) with equal Hindu-Muslim representation, still functioning within the 1935 Act framework."})

qs.append({"q":"Why did the Muslim League object to the Wavell Plan's nomination process?","o":["It feared that since other minorities' aims (depressed classes, Sikhs, Christians) aligned with the Congress, the League would be reduced to a one-third minority, so it demanded that all Muslim members be League nominees","It wanted fewer Muslim representatives on the council overall","It demanded that only Hindus be allowed on the executive council","It rejected the entire concept of an executive council in principle"],"a":0,"e":"The League feared being outnumbered since other minorities' interests aligned with the Congress, so it insisted all Muslim nominees be exclusively from the League, along with a claimed communal veto."})

qs.append({"q":"How did the Congress respond to the Wavell Plan?","o":["It objected to the plan as an attempt to reduce it to the status of a purely caste Hindu party and insisted on its right to nominate members of all communities","It fully accepted the plan without any reservations","It demanded the plan be scrapped in favour of immediate full independence with no interim arrangement","It supported the League's demand for a communal veto"],"a":0,"e":"The Congress objected to being cast as a purely caste-Hindu party and insisted on retaining the right to include members of all communities, including Muslims, among its own nominees."})

qs.append({"q":"What was Wavell's key mistake regarding the breakdown of the Shimla Conference talks, and its consequence?","o":["Announcing the breakdown in a way that effectively gave the Muslim League a virtual veto, strengthening its position ahead of the 1945-46 elections","Refusing to meet with any Congress leaders throughout the conference","Publicly endorsing the Congress's position over the League's","Immediately resigning as Viceroy following the failed talks"],"a":0,"e":"Wavell's handling of the breakdown effectively granted the League a virtual veto power, which boosted Jinnah's political position, as reflected in the League's strong performance in the 1945-46 elections."})

qs.append({"q":"Subhash Chandra Bose resigned from the Indian Civil Services in 1921 despite securing which rank in the examination?","o":["Fourth position","First position","Tenth position","He failed the examination"],"a":0,"e":"Bose secured fourth position in the ICS examination but resigned in 1921 to join the freedom struggle, becoming a member of the Congress under the guidance of his political guru Chittaranjan Das."})

qs.append({"q":"In March 1940, Bose convened the Anti-Compromise Conference — a joint effort of the Forward Bloc and which other organisation?","o":["The Kisan Sabha","The Congress Socialist Party","The Hindu Mahasabha","The All India Trade Union Congress"],"a":0,"e":"The Anti-Compromise Conference at Ramgarh (March 1940) was a joint effort of the Forward Bloc and the Kisan Sabha, calling for non-cooperation with the imperialist war effort."})

qs.append({"q":"After escaping house arrest in January 1941, under what pseudonym did Bose travel to Peshawar, with the help of Bhagat Ram?","o":["Ziauddin","Orlando Mazzotta","Abid Hussain","Rash Behari"],"a":0,"e":"Bose escaped under the pseudonym Ziauddin and reached Peshawar with the help of Bhagat Ram on January 26, 1941, before eventually making his way to Europe."})

qs.append({"q":"Under which pseudonym did Bose meet Adolf Hitler in Germany?","o":["Orlando Mazzotta","Ziauddin","Abid Hussain","Netaji Rao"],"a":0,"e":"Bose met Hitler in Germany under the pseudonym Orlando Mazzotta, after which the 'Freedom Army' (Mukti Sena) of Indian POWs was formed with German assistance."})

qs.append({"q":"From where did Bose give the famous slogan 'Jai Hind'?","o":["The Free India Centre, Germany","Singapore","Tokyo, Japan","Rangoon, Burma"],"a":0,"e":"Bose gave the slogan 'Jai Hind' from the Free India Centre in Germany, where he was also popularly called 'Netaji' by Germans."})

qs.append({"q":"Who originally conceived the idea of forming the Indian National Army out of Indian prisoners of war, in its first phase?","o":["Mohan Singh","Rashbehari Bose","Subhash Chandra Bose","Shah Nawaz Khan"],"a":0,"e":"Mohan Singh, an Indian army officer who refused to retreat with the British in Malaya, conceived the idea of forming the INA and sought Japanese help to recruit from Indian POWs."})

qs.append({"q":"Who chaired the Indian Independence League (founded in Tokyo in 1942) and later transferred leadership of both the League and the INA to Subhash Bose in July 1943?","o":["Rashbehari Bose","Mohan Singh","H.C. Chatterjee","Chittaranjan Das"],"a":0,"e":"Rashbehari Bose, who had founded the Indian Independence League in Tokyo in 1942, transferred its leadership and that of the INA to Subhash Bose in July 1943, having done crucial organisational groundwork earlier."})

qs.append({"q":"On what date did Subhash Bose become Supreme Commander of the INA?","o":["August 25, 1943","October 21, 1943","July 1943","January 1944"],"a":0,"e":"Subhash Bose became Supreme Commander of the INA on August 25, 1943, shortly after Rashbehari Bose transferred leadership to him."})

qs.append({"q":"On October 21, 1943, Bose formed the Provisional Government for Free India at Singapore, which included which of the following in its cabinet?\n1. H.C. Chatterjee holding the Finance portfolio.\n2. M.A. Aiyar holding Broadcasting.\n3. Lakshmi Swaminathan heading the Women's Department.\n4. Rashbehari Bose as Foreign Minister.\nHow many of the above are correctly listed?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correct; Rashbehari Bose did not hold the Foreign Minister post in this government — Subhash Bose himself held the war and foreign affairs portfolio."})

qs.append({"q":"The famous slogan 'Give me blood, I will give you freedom' was given by Bose at which location?","o":["Malaya","Singapore","Rangoon","Tokyo"],"a":0,"e":"Bose gave the iconic slogan 'Give me blood, I will give you freedom' in Malaya while rallying support and recruits for the INA and the Provisional Government of Free India."})

qs.append({"q":"On November 6, 1943, the Japanese handed over the Andaman and Nicobar Islands to the INA, which renamed them respectively as:","o":["Shahid Dweep and Swaraj Dweep","Azad Dweep and Hind Dweep","Netaji Dweep and Bharat Dweep","Swatantra Dweep and Mukti Dweep"],"a":0,"e":"The Andaman and Nicobar Islands, handed over by Japan to the INA on November 6, 1943, were renamed Shahid Dweep and Swaraj Dweep respectively."})

qs.append({"q":"Who was the first person to address Mahatma Gandhi as 'Father of the Nation', doing so from Azad Hind Radio on July 6, 1944?","o":["Subhash Chandra Bose","Jawaharlal Nehru","Rashbehari Bose","Sarojini Naidu"],"a":0,"e":"Subhash Bose, in a broadcast from Azad Hind Radio on July 6, 1944, was the first to call Gandhi the 'Father of the Nation', seeking his blessings for 'India's last war of independence'."})

qs.append({"q":"On which date did INA units, under Colonel Malik of the Bahadur Group, first hoist the INA flag on Indian mainland soil, at Moirang in Manipur?","o":["April 14, 1944","March 18, 1944","August 15, 1945","November 6, 1943"],"a":0,"e":"On April 14, 1944, Colonel Malik's Bahadur Group hoisted the INA flag at Moirang, Manipur — the site of today's INA Memorial Complex — to cries of 'Jai Hind' and 'Netaji Zindabad'."})

qs.append({"q":"What ultimately happened to the INA following Japan's surrender in the Second World War?","o":["The INA surrendered along with Japan on August 15, 1945, following its retreat after Allied forces reclaimed Moirang and the broader Japanese retreat","The INA continued fighting independently and achieved India's liberation before Independence","The INA merged directly into the British Indian Army without any legal proceedings","The INA was formally absorbed into the post-independence Indian Army immediately upon Japan's surrender"],"a":0,"e":"After the Allied reclaiming of territory and a general Japanese retreat, the INA withdrew and ultimately surrendered along with Japan on August 15, 1945; INA POWs were later brought back to India for court martial, sparking a major nationalist movement in their defence."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert isinstance(q["a"], int) and 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, q["q"]
    assert len(q["e"]) > 0, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_quit_india_pakistan_ina",
    "title": "Quit India Movement, Demand for Pakistan, and the INA",
    "desc": "The Quit India Movement (1942), parallel governments, Gandhi's 1943 fast, the Bengal Famine, the CR Formula, Desai-Liaqat Pact, Wavell Plan/Shimla Conference, and the rise of Subhash Bose and the Indian National Army",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch23_quit_india_pakistan_ina.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
