import json

qs = []

qs.append({"q":"During the First World War, the nationalist response in India was three-fold. Which of the following correctly describes the position of the Extremists, including Tilak?","o":["They supported the war effort, mistakenly believing Britain would reward India's loyalty with self-government","They organised armed uprisings against British forces stationed in India","They completely boycotted all war-related activity","They demanded immediate complete independence as a precondition for any cooperation"],"a":0,"e":"The Extremists, including the newly released Tilak, supported the British war effort in the mistaken hope that this loyalty would be rewarded with self-government after the war."})

qs.append({"q":"Tilak was released from his sentence (imposed after the 1908 sedition trial) in:","o":["June 1914","September 1917","1919","1920"],"a":0,"e":"Tilak was released from his six-year sentence in June 1914, after which he took a conciliatory approach and later led the Home Rule League movement."})

qs.append({"q":"The Home Rule League Movement drew direct inspiration from a similar movement in:","o":["Ireland","Egypt","Turkey","Russia"],"a":0,"e":"The Home Rule League Movement was modelled on the Irish Home Rule League, aiming for self-government within the British Commonwealth."})

qs.append({"q":"Which of the following leaders were involved in the initial discussions to form a national alliance that eventually resulted in two separate Home Rule Leagues?\n1. Bal Gangadhar Tilak\n2. Annie Besant\n3. Mohammad Ali Jinnah\n4. G.S. Khaparde\nHow many of the above are correctly listed as being involved?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four — Tilak, Annie Besant, Jinnah and Khaparde — were among the leaders involved in the initial discussions for an all-India Home Rule League."})

qs.append({"q":"Which of the following is NOT among the factors that led to the formation of the Home Rule Movement?","o":["Complete satisfaction among nationalists with the Morley-Minto Reforms","Wartime miseries caused by high taxation and rising prices","The exposure of the myth of white superiority due to the World War","Tilak's readiness to assume leadership after his 1914 release"],"a":0,"e":"The Moderates were, in fact, disillusioned with the Morley-Minto Reforms, not satisfied with them — this disillusionment was one of the actual driving factors behind the Home Rule Movement."})

qs.append({"q":"Annie Besant campaigned for Home Rule through her newspapers:","o":["New India and Commonweal","Kesari and Maharatta","Al Hilal and Comrade","Bande Mataram and The Indian Sociologist"],"a":0,"e":"Annie Besant used her newspapers New India and Commonweal, along with public meetings and conferences, to campaign for Home Rule."})

qs.append({"q":"Tilak's Indian Home Rule League, set up in April 1916 with its headquarters at Poona, operated in which regions?","o":["Maharashtra (excluding Bombay city), Karnataka, Central Provinces and Berar","All of India including Bombay city","Only Bengal and Bihar","Only Punjab and Sindh"],"a":0,"e":"Tilak's league was restricted to Maharashtra (excluding Bombay city), Karnataka, Central Provinces and Berar, with six branches."})

qs.append({"q":"Annie Besant's All-India Home Rule League, set up in September 1916 in Madras with George Arundale as organising secretary, had how many branches, and covered which area?","o":["200 branches, covering the rest of India including Bombay city","Six branches, covering only Madras Presidency","50 branches, covering only Bengal","10 branches, covering only Punjab"],"a":0,"e":"Besant's league had 200 branches (more loosely organised than Tilak's) and covered the rest of India, including Bombay city."})

qs.append({"q":"Which of the following leaders led the Bombay division of Annie Besant's Home Rule League?","o":["Mohammad Ali Jinnah","Motilal Nehru","Chittaranjan Das","Lala Lajpat Rai"],"a":0,"e":"Mohammad Ali Jinnah led the Bombay division of Annie Besant's All-India Home Rule League."})

qs.append({"q":"Which of the following sections of Indian society is noted in the chapter as largely NOT joining the Home Rule agitation, fearing it would mean Hindu (especially upper-caste) majority rule?","o":["Most Muslims, Anglo-Indians, and non-Brahmins from the South","Educated middle-class professionals","Students in Madras and Bombay","Moderate Congressmen disillusioned with Congress inactivity"],"a":0,"e":"Anglo-Indians, most Muslims, and non-Brahmins from the South largely stayed away from the Home Rule Movement, fearing domination by the Hindu (especially high-caste) majority."})

qs.append({"q":"In June 1917, the government arrested Annie Besant along with which two associates, provoking nationwide protest?","o":["B.P. Wadia and George Arundale","Bal Gangadhar Tilak and G.S. Khaparde","C.P. Ramaswamy Aiyar and Joseph Baptista","Motilal Nehru and Chittaranjan Das"],"a":0,"e":"Annie Besant was arrested in June 1917 along with her associates B.P. Wadia and George Arundale, triggering widespread nationalist protest."})

qs.append({"q":"In protest against Annie Besant's arrest in 1917, which prominent figure renounced his knighthood?","o":["Sir S. Subramaniya Aiyar","Bal Gangadhar Tilak","Mohammad Ali Jinnah","Rabindranath Tagore"],"a":0,"e":"Sir S. Subramaniya Aiyar renounced his knighthood in protest against Annie Besant's arrest in June 1917."})

qs.append({"q":"Montagu, the Secretary of State for India, made a striking comment comparing the effect of interning Annie Besant to which mythological reference?","o":["Shiva cutting his wife into fifty-two pieces only to discover he had fifty-two wives","Ravana's ten heads multiplying with each cut","Krishna's Sudarshan Chakra returning to strike back","Hanuman's growing form when confronted"],"a":0,"e":"Montagu remarked that interning Besant was like Shiva cutting his wife into fifty-two pieces only to find he now had fifty-two wives — implying that repression only multiplied resistance."})

qs.append({"q":"Annie Besant was released from detention in:","o":["September 1917","June 1917","1918","1919"],"a":0,"e":"Annie Besant, arrested in June 1917, was released in September 1917 following widespread protest."})

qs.append({"q":"Which of the following factors contributed to the decline of the Home Rule agitation by 1919?\n1. Lack of effective organisation.\n2. Communal riots during 1917-18.\n3. Pacification of Moderates by Montagu's August 1917 statement and Besant's release.\n4. Tilak's departure abroad in 1918 over a libel case against Valentine Chirol.\nHow many of the above are correctly identified as reasons for decline?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors — organisational weakness, communal riots, pacification via reform promises, and Tilak's absence abroad — contributed to the movement's decline by 1919, along with Gandhi's rising influence."})

qs.append({"q":"Tilak went abroad in September 1918 in connection with a libel case against Valentine Chirol, author of which book that had portrayed Tilak as responsible for India's agitational politics?","o":["Indian Unrest","The Indian War of Independence","Discovery of India","Eighteen Fifty-Seven"],"a":0,"e":"Tilak pursued a libel case in England against Valentine Chirol over his book Indian Unrest, which held Tilak responsible for India's agitational politics."})

qs.append({"q":"In 1920, Gandhi accepted the presidentship of the All India Home Rule League and renamed the organisation to:","o":["Swarajya Sabha","Indian National Congress","Servants of India Society","Satyagraha Sabha"],"a":0,"e":"Gandhi renamed the All India Home Rule League as the Swarajya Sabha in 1920, before it merged with the Indian National Congress within a year."})

qs.append({"q":"Which of the following is cited as a positive, long-term contribution of the Home Rule Movement to the freedom struggle?","o":["It shifted the movement's emphasis from the educated elite to the masses and created an organisational link between town and country","It immediately achieved full self-government for India","It eliminated all communal tensions between Hindus and Muslims","It replaced the Indian National Congress entirely with the Home Rule Leagues"],"a":0,"e":"The Home Rule Movement's key legacy was shifting political focus toward mass mobilisation and forging organisational links between urban and rural areas, laying groundwork for the Gandhian mass phase."})

qs.append({"q":"The Lucknow Session of the Indian National Congress (1916), presided over by Ambika Charan Majumdar, is significant chiefly for:","o":["Readmitting the Extremists led by Tilak to the Congress fold and the signing of the Lucknow Pact with the Muslim League","The founding of the Indian National Congress itself","The declaration of Purna Swaraj as the Congress goal","The launch of the Non-Cooperation Movement"],"a":0,"e":"The Lucknow session (1916) achieved Moderate-Extremist reunion within Congress and produced the historic Lucknow Pact between the Congress and Muslim League."})

qs.append({"q":"Which of the following facilitated the Moderate-Extremist reunion at the Lucknow session in 1916?\n1. Realisation by both sides that the split had caused political inactivity.\n2. Efforts by Tilak and Annie Besant towards reconciliation.\n3. Tilak's declaration that he supported administrative reform, not overthrow of government.\n4. The deaths of Moderate leaders Gokhale and Pherozshah Mehta.\nHow many of the above are correctly identified as facilitating factors?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors — mutual recognition of the costs of division, the efforts of Tilak and Besant, Tilak's conciliatory declarations, and the deaths of key Moderate opponents — facilitated the 1916 reunion."})

qs.append({"q":"Under the Lucknow Pact (1916), the Congress accepted the Muslim League's position on:","o":["Separate electorates for Muslims","Universal adult franchise","Abolition of the zamindari system","Formation of linguistic provinces"],"a":0,"e":"The Congress agreed to accept separate electorates for Muslims as part of the Lucknow Pact, along with a fixed proportion of Muslim seats in legislatures."})

qs.append({"q":"Which of the following were among the joint demands presented by the Congress and Muslim League under the Lucknow Pact?\n1. Self-government to be conferred on Indians at an early date.\n2. Expansion of representative assemblies with an elected majority.\n3. Salaries of the Secretary of State for India to be paid by the British treasury, not Indian funds.\n4. Half the members of the viceroy's and provincial governors' executive councils to be Indian.\nHow many of the above are correctly listed as joint demands?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four were part of the joint Congress-League demands under the Lucknow Pact of 1916."})

qs.append({"q":"According to the chapter's critical assessment, the Congress's acceptance of separate electorates in the Lucknow Pact represented:","o":["A major landmark in the evolution of the Muslim League's two-nation theory, since Congress and League came together as separate political entities","A rejection of any communal basis for representation","The complete elimination of minority fears about majority domination","A temporary measure immediately reversed at the next Congress session"],"a":0,"e":"By accepting separate electorates, the Congress implicitly recognised the League as a distinct political entity representing Muslims separately — a step later seen as contributing to the two-nation theory's evolution."})

qs.append({"q":"Which of the following factors contributed to the shift in the Muslim League's attitude towards greater cooperation with the Congress before 1916?\n1. Britain's refusal to help Turkey (ruled by the Khalifa) in its wars in the Balkans and with Italy.\n2. Annulment of the partition of Bengal in 1911, which annoyed Muslims who had supported it.\n3. Refusal to set up a university at Aligarh with powers to affiliate colleges nationwide.\n4. Government repression of Al Hilal and Comrade during the war.\nHow many of the above are correctly identified as reasons?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors contributed to the growing anti-imperialist sentiment among younger League members, bringing them closer to Congress objectives before the 1916 Lucknow Pact."})

qs.append({"q":"Maulana Azad's journal Al Hilal and Mohammad Ali's journal Comrade, both suppressed during World War I, reflected the anti-imperialist sentiments of which group within the Muslim League?","o":["The younger 'Young Party' Muslims turning towards bolder nationalist politics","The Aligarh school loyal to the British government","The Ahmadiyya movement","The Deoband ulema exclusively"],"a":0,"e":"The younger, more militant nationalist Muslims (the 'Young Party'), represented by figures like Azad and Mohammad Ali, grew increasingly anti-imperialist, publishing journals that faced government suppression during the war."})

qs.append({"q":"The Calcutta session of the Muslim League (1912) committed the League to:","o":["Working with other groups for a system of self-government suited to India, provided it did not conflict with protecting Muslim interests","Complete rejection of any cooperation with the Indian National Congress","Unconditional loyalty to British rule with no self-government demand","Support for a fully separate Muslim state"],"a":0,"e":"The 1912 Calcutta session committed the League to cooperating with other groups towards self-government suited to India, while safeguarding Muslim interests — a step that eventually facilitated Congress-League cooperation."})

qs.append({"q":"Edwin Samuel Montagu's statement of August 20, 1917 (the 'August Declaration') in the British House of Commons announced government policy towards:","o":["Increasing Indian participation in administration and the progressive realisation of responsible self-government within the British Empire","Immediate grant of full independence to India","Abolition of separate electorates","Permanent continuation of Company-style administration"],"a":0,"e":"Montagu's August 1917 declaration announced a policy of increasing Indian participation in administration, with responsible government as the eventual goal within the British Empire — a marked shift from Morley's earlier position."})

qs.append({"q":"Which of the following distinguishes Montagu's 1917 statement from Lord Morley's earlier position on constitutional reform (in the context of the 1909 reforms)?","o":["Montagu explicitly made self-government a government policy goal, unlike Morley who had rejected any move towards parliamentary government in India","Montagu rejected any form of Indian participation in administration","Morley had promised immediate self-government while Montagu withdrew that promise","Both made identical commitments regarding self-government"],"a":0,"e":"Unlike Morley, who explicitly disavowed any intention of leading towards parliamentary government in India, Montagu's 1917 declaration made responsible self-government an official policy goal, even if without a fixed timeline."})

qs.append({"q":"Indian nationalist objections to Montagu's August 1917 statement centred on which two concerns?","o":["The absence of a specific timeframe, and the government alone deciding the pace and nature of advance towards responsible government","The complete absence of any mention of self-government","The statement's promise of immediate full independence, which nationalists found unrealistic","The statement's silence on separate electorates"],"a":0,"e":"Nationalists objected that Montagu's declaration gave no fixed timeline and left the pace and nature of reform entirely to British discretion, rather than Indian representatives."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_wwi_nationalist_response",
    "title": "First World War and Nationalist Response",
    "desc": "Nationalist responses to WWI, the Home Rule League Movement (Tilak and Annie Besant), the Lucknow session and Congress-League Pact, and Montagu's August 1917 Declaration",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch14_wwi_nationalist_response.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
