import json

qs = []

qs.append({"q":"After Gandhi's arrest in March 1922, the debate within Congress over council entry led to the emergence of which two groups?","o":["Swarajists and No-Changers","Moderates and Extremists","Responsivists and Non-responsivists","HRA and HSRA"],"a":0,"e":"The Swarajists (led by C.R. Das, Motilal Nehru, Ajmal Khan) favoured council entry, while the No-Changers (led by Rajagopalachari, Patel, Rajendra Prasad, Ansari) opposed it, favouring constructive work instead."})

qs.append({"q":"The Swarajists' strategy of entering the legislative councils is best described as an approach to:","o":["'End or mend' the councils — using them as an arena to expose weaknesses or obstruct government business","Fully cooperate with the government in administering the councils","Boycott elections entirely while criticising the councils from outside","Seek dominion status through negotiations within the councils"],"a":0,"e":"The Swarajists sought to 'end or mend' the councils — entering them to either force real reforms or, failing that, obstruct governance from within."})

qs.append({"q":"At which Congress session (December 1922) was the Swarajists' proposal of council entry defeated, leading C.R. Das and Motilal Nehru to resign their Congress positions?","o":["Gaya session","Nagpur session","Belgaum session","Ahmedabad session"],"a":0,"e":"At the Gaya session (December 1922), the Swarajist proposal was defeated, prompting C.R. Das and Motilal Nehru to resign and form the Congress-Khilafat Swarajya Party."})

qs.append({"q":"The Congress-Khilafat Swarajya Party (Swarajist Party), formed after the Gaya session, had which leaders as president and secretary respectively?","o":["C.R. Das as president and Motilal Nehru as one of the secretaries","Motilal Nehru as president and C.R. Das as secretary","Vallabhbhai Patel as president and Rajendra Prasad as secretary","M.A. Ansari as president and C. Rajagopalachari as secretary"],"a":0,"e":"C.R. Das served as president of the newly formed Swarajist Party, with Motilal Nehru as one of its secretaries."})

qs.append({"q":"The compromise between Swarajists and No-Changers, allowing Swarajists to contest elections as a group within Congress, was reached at a meeting in Delhi in:","o":["September 1923","December 1922","February 1924","December 1924"],"a":0,"e":"The September 1923 Delhi meeting allowed Swarajists to contest the November 1923 elections as a distinct group while remaining within the Congress fold."})

qs.append({"q":"According to the Swarajist Manifesto (October 1923), if their demand for self-government within councils was rejected, they would adopt a policy of:","o":["Uniform, continuous and consistent obstruction within the councils to make governance impossible","Immediate resignation from all council seats","Armed uprising against the government","Complete silence and non-participation in council debates"],"a":0,"e":"The manifesto declared that rejection of their self-government demand would be met with sustained obstructionist tactics designed to wreck the councils from within."})

qs.append({"q":"In the November 1923 elections to the legislative councils, the Swarajists won how many out of 141 elected seats, gaining a clear majority in the Central Provinces assembly?","o":["42","100","20","70"],"a":0,"e":"The Swarajists won 42 out of 141 elected seats and secured a clear majority in the Central Provinces provincial assembly."})

qs.append({"q":"Gandhi, initially opposed to council entry, gradually reconciled with the Swarajists after his release from prison in February 1924, and their agreement was formally endorsed at which Congress session, the only one Gandhi ever presided over?","o":["Belgaum session (December 1924)","Gaya session (1922)","Lahore session (1929)","Karachi session (1931)"],"a":0,"e":"The Belgaum Congress session of December 1924, the only session Gandhi ever presided over, formally endorsed the agreement allowing Swarajists to work within councils as part of Congress."})

qs.append({"q":"Which faction of Swarajists, including Lala Lajpat Rai, Madan Mohan Malaviya and N.C. Kelkar, advocated cooperation with the government and holding office, while also seeking to protect perceived Hindu interests?","o":["Responsivists","No-Changers","HSRA","Justice Party members"],"a":0,"e":"The Responsivists, including Lajpat Rai, Malaviya and Kelkar, favoured cooperation with the government and office-holding, and were associated with a communal (pro-Hindu) orientation that weakened Swarajist unity."})

qs.append({"q":"The Swarajist Party lost significant Muslim support chiefly because:","o":["The party failed to support the tenants' (mostly Muslim) cause against zamindars in Bengal","It refused to contest any elections in Muslim-majority areas","It banned Muslims from party membership","It supported the Simon Commission's recommendations"],"a":0,"e":"The Swarajists' failure to back Bengali tenants (mostly Muslim) against zamindars alienated Muslim support, compounding communal strains within the party."})

qs.append({"q":"Which Swarajist leader was elected speaker of the Central Legislative Assembly in 1925, considered a notable achievement of the party?","o":["Vithalbhai Patel","C.R. Das","Motilal Nehru","N.C. Kelkar"],"a":0,"e":"Vithalbhai Patel was elected speaker of the Central Legislative Assembly in 1925, a significant Swarajist achievement in parliamentary politics."})

qs.append({"q":"A notable Swarajist legislative achievement was the defeat of which bill in 1928, which aimed to empower the government to deport 'undesirable' foreigners suspected of spreading communist ideas?","o":["The Public Safety Bill","The Trade Disputes Bill","The Rowlatt Bill","The Ilbert Bill"],"a":0,"e":"The Swarajists, with coalition partners, defeated the Public Safety Bill in 1928, aimed at deporting foreigners believed to be spreading socialist/communist influence via the Comintern."})

qs.append({"q":"Which of the following is identified as a drawback of the Swarajist strategy?","o":["They lacked a policy to coordinate their council-based militancy with mass struggle outside, relying mainly on newspaper reporting","They refused to ever contest any elections","They had no support from coalition partners at any point","They completely avoided using obstructionist tactics"],"a":0,"e":"A key limitation was the disconnect between council-based activity and mass mobilisation outside — the Swarajists relied on newspapers to reach the public rather than sustained grassroots organisation."})

qs.append({"q":"The No-Changers' constructive work programme during the 1920s included which of the following activities?\n1. Establishing ashrams working among tribals and lower castes, especially in Kheda and Bardoli.\n2. Setting up national schools and colleges with a non-colonial ideological framework.\n3. Work for Hindu-Muslim unity and removal of untouchability.\n4. Direct armed resistance training for volunteers.\nHow many of the above are correctly listed as part of constructive work?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe No-Changer constructive work; armed resistance training was never part of the Gandhian constructive programme."})

qs.append({"q":"A key criticism of the 'constructive work' programme, as noted in the chapter, was that:","o":["National education mainly benefited the urban lower middle classes and rich peasants, while khadi remained costlier than imported cloth for the poor","It had no impact whatsoever on any social group","It was fully successful in eliminating untouchability's economic roots","It received unanimous support from all Congress leaders without dissent"],"a":0,"e":"Critics noted that national education's benefits were largely confined to relatively privileged groups, and khadi's higher cost compared to mill cloth limited its mass appeal among the poor."})

qs.append({"q":"The Communist Party of India (CPI) was founded in 1920 in which city, by M.N. Roy and Abani Mukherji among others?","o":["Tashkent","Kanpur","Moscow","Meerut"],"a":0,"e":"The CPI was founded in Tashkent in 1920 by M.N. Roy, Abani Mukherji and others, following the second Congress of the Comintern; M.N. Roy also became the first Indian elected to Comintern leadership."})

qs.append({"q":"The Kanpur Bolshevik Conspiracy Case of 1924, in which several communists including S.A. Dange, Muzaffar Ahmed, Shaukat Usmani and Nalini Gupta were jailed, was followed by which 1925 event that formalised the CPI's foundation within India?","o":["The Indian Communist Conference at Kanpur","The Meerut Conspiracy Case","The Belgaum Congress session","The formation of the AITUC"],"a":0,"e":"The 1925 Indian Communist Conference at Kanpur formally established the CPI's domestic organisational base, following the earlier 1924 Kanpur Bolshevik Conspiracy Case."})

qs.append({"q":"The Meerut Conspiracy Case (1929), a major government crackdown on the left, resulted in the arrest and trial of how many leading communists, trade unionists and left-wing leaders?","o":["31","10","50","100"],"a":0,"e":"In 1929, 31 leading communists, trade unionists and left-wing leaders were arrested and tried in the Meerut Conspiracy Case."})

qs.append({"q":"The All India Trade Union Congress (AITUC), founded in 1920, had which leader as its first president?","o":["Lala Lajpat Rai","Tilak","Dewan Chaman Lal","N.M. Joshi"],"a":0,"e":"Lala Lajpat Rai served as the first president of AITUC (1920), with Dewan Chaman Lal as general secretary; Tilak was also among its founding figures."})

qs.append({"q":"The Bombay Textile Mills strike during the 1920s, one of the major labour actions of the decade, involved approximately how many workers and lasted about how long?","o":["1,50,000 workers, lasting about 5 months","10,000 workers, lasting 1 week","50,000 workers, lasting 2 months","5,00,000 workers, lasting 1 year"],"a":0,"e":"The Bombay Textile Mills strike involved around 1,50,000 workers and continued for about five months, one of the largest labour actions of the 1920s."})

qs.append({"q":"The first May Day celebration in India took place in 1923 in which city?","o":["Madras","Bombay","Calcutta","Kanpur"],"a":0,"e":"India's first May Day celebration was held in Madras in 1923, reflecting the growing influence of socialist and labour movements."})

qs.append({"q":"The Bardoli Satyagraha of 1928, a notable peasant agitation in Gujarat, was led by:","o":["Vallabhbhai Patel","Jawaharlal Nehru","Subhash Chandra Bose","M.N. Roy"],"a":0,"e":"Vallabhbhai Patel led the Bardoli Satyagraha of 1928, a peasant agitation against enhanced land revenue assessment."})

qs.append({"q":"Which of the following caste-based movements/organisations of the 1920s are correctly matched with their regions and leaders?\n1. Self-respect movement (1925) under E.V. Ramaswamy Naicker - Madras\n2. Mahars under Ambedkar - Maharashtra\n3. Radical Ezhavas under K. Aiyappan and C. Kesavan - Kerala\n4. Unionist Party under Fazl-i-Hussain - Bengal\nHow many of the above are correctly matched?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correctly matched. Statement 4 is incorrect — the Unionist Party under Fazl-i-Hussain was active in Punjab, not Bengal."})

qs.append({"q":"The two main strands of revolutionary activity with a socialist turn during the 1920s operated respectively in:","o":["Punjab-UP-Bihar (Hindustan Republican Association) and Bengal (Yugantar/Anushilan groups, later Chittagong Revolt Group)","Madras and Bombay","Only in Bengal, with no activity elsewhere","Only in Punjab, with no activity in Bengal"],"a":0,"e":"Revolutionary activity of this period developed along two main geographic strands: Punjab-UP-Bihar under the HRA, and Bengal through Yugantar/Anushilan groups and later the Chittagong Revolt Group under Surya Sen."})

qs.append({"q":"The Hindustan Republican Association (HRA), founded in October 1924 at Kanpur by Ramprasad Bismil, Jogesh Chandra Chatterjee and Sachin Sanyal, aimed to establish which form of government?","o":["A Federal Republic of the United States of India based on adult franchise","A constitutional monarchy under an Indian prince","A theocratic state based on religious law","A dominion within the British Commonwealth"],"a":0,"e":"The HRA's founding goal was an armed revolution to establish a Federal Republic of the United States of India, with adult franchise as its basic principle."})

qs.append({"q":"The Kakori Robbery (August 1925), the HRA's most significant action, involved:","o":["Looting official railway cash from the 8-Down train near Kakori village, close to Lucknow","An assassination attempt on the Calcutta Police Commissioner","A bomb thrown in the Central Legislative Assembly","An armoury raid in Chittagong"],"a":0,"e":"The Kakori Robbery involved holding up the 8-Down train near Kakori village to seize official railway cash for funding revolutionary activities."})

qs.append({"q":"Following the Kakori Robbery crackdown, which four revolutionaries were hanged?","o":["Bismil, Ashfaqullah, Roshan Singh and Rajendra Lahiri","Bhagat Singh, Sukhdev, Rajguru and Azad","Surya Sen, Anant Singh, Ganesh Ghosh and Lokenath Baul","Jatin Das, Bhagwaticharan Vohra, Shiv Verma and Jaidev Kapur"],"a":0,"e":"Bismil, Ashfaqullah, Roshan Singh and Rajendra Lahiri were hanged following the Kakori conspiracy trial, a significant setback for the HRA."})

qs.append({"q":"The HRA was reorganised as the Hindustan Socialist Republican Association (HSRA) at a historic meeting in September 1928 at:","o":["The ruins of Ferozshah Kotla, Delhi","Kakori village, near Lucknow","Chittagong, Bengal","Lahore, Punjab"],"a":0,"e":"The HRA was reorganised as the HSRA at a meeting in the ruins of Ferozshah Kotla, Delhi, in September 1928, under Chandra Shekhar Azad's leadership, adopting socialism as its official goal."})

qs.append({"q":"The assassination of the police official Saunders in Lahore (December 1928) by Bhagat Singh, Azad and Rajguru was in retaliation for:","o":["The lathi-charge injuries that led to the death of Lala Lajpat Rai during an anti-Simon Commission protest","The Kakori Robbery arrests","The Meerut Conspiracy Case trials","The Jallianwala Bagh Massacre"],"a":0,"e":"Lala Lajpat Rai died from injuries sustained during a police lathi-charge on an anti-Simon Commission procession in October 1928; the HSRA revolutionaries assassinated Saunders, the officer they held responsible."})

qs.append({"q":"Bhagat Singh and Batukeshwar Dutt threw a bomb in the Central Legislative Assembly on April 8, 1929, to protest against:","o":["The Public Safety Bill and the Trade Disputes Bill, aimed at curtailing civil liberties","The Rowlatt Act","The Government of India Act, 1919","The partition of Bengal"],"a":0,"e":"The bomb, deliberately made harmless, was thrown to protest the Public Safety Bill and Trade Disputes Bill, which threatened civil liberties, especially of workers; the act was meant to 'make the deaf hear'."})

qs.append({"q":"Bhagat Singh, Sukhdev and Rajguru were tried in which conspiracy case, ultimately leading to their execution?","o":["The Lahore Conspiracy Case","The Kakori Conspiracy Case","The Meerut Conspiracy Case","The Alipore Conspiracy Case"],"a":0,"e":"Bhagat Singh, Sukhdev and Rajguru were tried in the Lahore Conspiracy Case and hanged on March 23, 1931."})

qs.append({"q":"Jatin Das, a revolutionary associated with the HSRA, became a martyr after dying on which day of a hunger strike demanding honourable treatment as a political prisoner?","o":["The 64th day","The 10th day","The 100th day","The 21st day"],"a":0,"e":"Jatin Das died on the 64th day of his hunger strike in jail, becoming a martyr for the cause of political prisoners' rights."})

qs.append({"q":"Chandra Shekhar Azad died in a police encounter in February 1931 at which location?","o":["A park in Allahabad","Ferozshah Kotla, Delhi","Kakori, near Lucknow","Lahore Central Jail"],"a":0,"e":"Chandra Shekhar Azad died in a gun battle with police in a park in Allahabad in February 1931, having evaded capture throughout his revolutionary career."})

qs.append({"q":"The book 'The Philosophy of the Bomb', articulating the revolutionary position of the HSRA, was written by:","o":["Bhagwaticharan Vohra","Bhagat Singh","Ramprasad Bismil","Sachin Sanyal"],"a":0,"e":"Bhagwaticharan Vohra authored The Philosophy of the Bomb, laying out the HSRA's evolving revolutionary ideology."})

qs.append({"q":"Bhagat Singh, moving away from a belief in individual heroic action towards Marxism, helped establish which open organisation in 1926 to carry out political work among youth, peasants and workers?","o":["Punjab Naujawan Bharat Sabha","Hindustan Republican Association","Lahore Students' Union","All India Trade Union Congress"],"a":0,"e":"Bhagat Singh helped found the Punjab Naujawan Bharat Sabha in 1926 as an open wing for political mobilisation among youth, peasants and workers."})

qs.append({"q":"Which of the following rules, drafted by Bhagat Singh for the Punjab Naujawan Bharat Sabha, reflected his secular outlook?","o":["Members would have nothing to do with communal bodies and would propagate tolerance, treating religion as a matter of personal belief","Members must belong to a single religious community for organisational unity","Members were required to take religious oaths before joining","Members would prioritise religious education over political work"],"a":0,"e":"Bhagat Singh's rules for the Sabha explicitly barred association with communal bodies and promoted religious tolerance, reflecting his conscious secularism."})

qs.append({"q":"Bhagat Singh's redefinition of revolution, as expressed in his court statement, held that revolution meant:","o":["Changing the present unjust order of things, not merely 'the cult of bomb and pistol' or personal vendetta","Purely individual acts of violence against colonial officials","A religious crusade against foreign rule","The restoration of pre-colonial monarchical structures"],"a":0,"e":"Bhagat Singh insisted that revolution was fundamentally about changing an unjust social and economic order, explicitly rejecting the idea that it was reducible to violence or personal vendetta."})

qs.append({"q":"Bhagat Singh's class analysis held that peasants needed liberation from which combination of oppressive forces?","o":["Both the foreign colonial yoke and the yoke of landlords and capitalists","Only the foreign colonial yoke","Only indigenous landlords, with no reference to colonial rule","Only capitalists, regardless of nationality"],"a":0,"e":"Bhagat Singh argued that true liberation required freeing peasants from both foreign imperial rule and indigenous class exploitation by landlords and capitalists, regardless of nationality."})

qs.append({"q":"In Bengal, after C.R. Das's death (1925), the Bengal Congress split into two factions led by:","o":["J.M. Sengupta (backed by the Anushilan group) and Subhash Bose (backed by the Yugantar group)","Surya Sen and Jatin Das","Bhagat Singh and Chandra Shekhar Azad","Motilal Nehru and Vallabhbhai Patel"],"a":0,"e":"Following C.R. Das's death, Bengal Congress split between J.M. Sengupta (with Anushilan backing) and Subhash Bose (with Yugantar backing)."})

qs.append({"q":"Gopinath Saha's 1924 assassination attempt targeted the notorious Calcutta Police Commissioner, but mistakenly killed:","o":["A man named Day","Charles Tegart himself","Saunders","J.M. Sengupta"],"a":0,"e":"Gopinath Saha's attempt on Police Commissioner Charles Tegart failed, and he mistakenly killed a man named Day instead; Saha was subsequently hanged."})

qs.append({"q":"The Chittagong Armoury Raid, organised by Surya Sen and associates including Anant Singh and Ganesh Ghosh, took place in:","o":["April 1930","1924","1925","1928"],"a":0,"e":"Surya Sen led the Chittagong Armoury Raid in April 1930, involving around 65 activists under the banner of the Indian Republican Army – Chittagong Branch."})

qs.append({"q":"During the Chittagong Armoury Raid, Surya Sen hoisted the national flag, took a salute, and proclaimed:","o":["A provisional revolutionary government","Complete independence for all of Bengal","A ceasefire with British forces","The formation of a new communist state"],"a":0,"e":"Surya Sen proclaimed a provisional revolutionary government during the Chittagong raid, symbolising defiance of British authority, even if only briefly and locally."})

qs.append({"q":"Surya Sen was arrested in February 1933 and executed in:","o":["January 1934","1930","1931","1935"],"a":0,"e":"Surya Sen was arrested in February 1933 and hanged in January 1934, though the Chittagong raid continued to inspire revolutionary recruitment."})

qs.append({"q":"Which women revolutionaries were prominently associated with Surya Sen's Chittagong group and the broader Bengal revolutionary movement of this phase?\n1. Pritilata Waddedar, who died conducting a raid.\n2. Kalpana Dutt, tried alongside Surya Sen and given a life sentence.\n3. Bina Das, who fired at the governor during her convocation in February 1932.\n4. Sarojini Naidu, who led armed actions in Chittagong.\nHow many of the above are correctly identified?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe women revolutionaries of this phase; Sarojini Naidu was a Congress leader and poet, not part of the armed Chittagong revolutionary group."})

qs.append({"q":"Santi Ghosh and Suniti Chandheri, school girls of Comilla, are notable for:","o":["Shooting dead the district magistrate in December 1931","Leading the Chittagong Armoury Raid","Founding the Punjab Naujawan Bharat Sabha","Organising the Kakori Robbery"],"a":0,"e":"Santi Ghosh and Suniti Chandheri, young schoolgirls from Comilla, assassinated the district magistrate in December 1931, exemplifying the participation of young women in Bengal's revolutionary movement."})

qs.append({"q":"Which of the following was a noteworthy feature of the new phase of Bengal's revolutionary movement under Surya Sen, distinguishing it from the earlier Anushilan/Yugantar phase?","o":["A shedding of earlier Hindu religious rituals, which facilitated the participation of Muslims in the movement","An increased emphasis on individual assassination over group action","Complete exclusion of women from all revolutionary work","A total rejection of any connection with the Indian National Congress"],"a":0,"e":"Unlike the earlier phase's Hindu religious overtones (oath-taking rituals, etc.), Surya Sen's group shed such practices, enabling genuine Muslim participation, including figures like Satar and Fakir Ahmed Mian."})

qs.append({"q":"In 1933, Jawaharlal Nehru was arrested for sedition and sentenced to two years primarily because he had:","o":["Condemned imperialism and praised the heroism of the revolutionaries","Organised the Chittagong Armoury Raid","Assassinated a British official","Led the Meerut Conspiracy Case defendants"],"a":0,"e":"Nehru's public condemnation of imperialism and praise for revolutionary heroism led to his sedition conviction in 1933, reflecting continued government sensitivity to sympathetic commentary on revolutionary activity."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_swarajists_socialism_revolutionary",
    "title": "Emergence of Swarajists, Socialist Ideas, Revolutionary Activities and Other New Forces",
    "desc": "Swarajists vs No-Changers, the rise of socialist/communist ideas, trade unionism and caste movements, and the second phase of revolutionary activity (HRA/HSRA in Punjab-UP-Bihar and Surya Sen's Chittagong group in Bengal)",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch17_swarajists_socialism_revolutionary.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
