import json

qs = []

qs.append({"q":"The first session of the Indian National Congress was held in December 1885 at:","o":["Gokuldas Tejpal Sanskrit College, Bombay","Calcutta","Allahabad","Madras"],"a":0,"e":"The first INC session was held at Gokuldas Tejpal Sanskrit College in Bombay in December 1885, organised by A.O. Hume with the cooperation of leading Indian intellectuals."})

qs.append({"q":"The first session of the Indian National Congress (1885), attended by 72 delegates, was presided over by:","o":["Womesh Chandra Bonnerjee","Dadabhai Naoroji","Surendranath Banerjea","A.O. Hume"],"a":0,"e":"Womesh Chandra Bonnerjee presided over the first INC session in 1885, attended by 72 delegates."})

qs.append({"q":"As a prelude to the founding of the INC, two sessions of which organisation were held in 1883 and 1885, with Surendranath Banerjea and Ananda Mohan Bose as its main architects?","o":["Indian National Conference","Indian Association of Calcutta","British Indian Association","East India Association"],"a":0,"e":"The Indian National Conference held two sessions (1883, 1885) with representatives from major Indian towns, serving as a prelude to the INC's foundation."})

qs.append({"q":"Which of the following leaders served as president of the Indian National Congress three times during its early phase?","o":["Dadabhai Naoroji","Pherozshah Mehta","Surendranath Banerjea","Badruddin Tyabji"],"a":0,"e":"Dadabhai Naoroji presided over the INC on three occasions during its early history."})

qs.append({"q":"Kadambini Ganguly, who addressed the 1890 Congress session symbolising the movement's commitment to women's status in national life, was notable as:","o":["The first woman graduate of Calcutta University","The first woman president of the INC","The founder of the All India Women's Conference","The first woman barrister of India"],"a":0,"e":"Kadambini Ganguly, the first woman graduate of Calcutta University, addressed the INC session in 1890."})

qs.append({"q":"According to the 'safety valve' theory of the INC's foundation, A.O. Hume intended the Congress to:","o":["Release the growing discontent of Indians to prevent a popular uprising, with Lord Dufferin's cooperation","Directly challenge British sovereignty in India","Serve exclusively as a social reform organisation","Unite Indian princely states against British rule"],"a":0,"e":"The safety valve theory holds that Hume, with Lord Dufferin's tacit cooperation, formed the Congress to channel and defuse growing Indian discontent rather than let it erupt into rebellion."})

qs.append({"q":"Which of the following leaders is associated with belief in the 'safety valve' theory of Congress's origin?","o":["Lala Lajpat Rai","G.K. Gokhale","Bipan Chandra","Womesh Chandra Bonnerjee"],"a":0,"e":"Extremist leader Lala Lajpat Rai believed in the safety valve theory regarding the Congress's founding."})

qs.append({"q":"R.P. Dutt's Marxist 'conspiracy theory' regarding the INC's foundation held that:","o":["The Congress was born out of a conspiracy to abort a popular uprising, with bourgeois leaders complicit in it","The Congress was formed purely by grassroots peasant demand","Hume had no role whatsoever in founding the Congress","The Congress was created to promote industrial capitalism exclusively"],"a":0,"e":"R.P. Dutt's conspiracy theory viewed the INC as an instrument to preempt and abort a genuine popular uprising, with bourgeois leaders as willing collaborators."})

qs.append({"q":"Historian Bipan Chandra described the early Congress leaders' use of A.O. Hume as a:","o":["'Lightning conductor' to bring together nationalist forces under the guise of a safety valve","'Trojan horse' to infiltrate British institutions","'Puppet' with no independent political agency","'Scapegoat' to deflect British criticism"],"a":0,"e":"Bipan Chandra argued that Indian leaders used Hume as a 'lightning conductor' — a catalyst enabling them to organise nationalist forces even while the British saw it as a safety valve."})

qs.append({"q":"Consider the following statements regarding the aims of the Indian National Congress in its initial stage:\n1. To found a democratic, nationalist movement.\n2. To politicise and politically educate the people.\n3. To develop a feeling of national unity irrespective of religion, caste or province.\n4. To demand complete independence from British rule immediately.\nHow many of the above are correctly listed as initial INC aims?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect the INC's initial aims. Statement 4 is incorrect, as the early Congress under the Moderates did not demand immediate complete independence."})

qs.append({"q":"The Moderate leaders of the INC (1885-1905), such as Dadabhai Naoroji, Pherozshah Mehta and S.N. Banerjea, primarily relied on which method of political activity?","o":["Constitutional agitation through prayer, petition and public opinion within the confines of law","Armed insurrection against British authorities","Boycott of all British goods and institutions","Direct appeal to foreign powers for military intervention"],"a":0,"e":"The Moderates believed in constitutional methods — creating public opinion, and using petitions and resolutions — believing that the British would gradually concede reforms."})

qs.append({"q":"The British Committee of the Indian National Congress, established in London in 1889, published which journal as its organ?","o":["India","Rast Goftar","Kesari","Hitavada"],"a":0,"e":"The British Committee of the INC, established in London in 1889, published the journal India as its organ to campaign for Indian interests in Britain."})

qs.append({"q":"The 'drain theory', put forward by early nationalists like Dadabhai Naoroji, R.C. Dutt and Dinshaw Wacha, sought to explain:","o":["British economic exploitation of India through the transformation of a self-sufficient economy into a colonial supplier of raw materials and market for British goods","The migration of Indian labour to British colonies","The decline of Mughal political authority","The causes of the 1857 Revolt"],"a":0,"e":"The drain theory analysed how British rule converted India's self-sufficient economy into a colonial one — exporting raw materials, importing finished goods, and serving as a field for British capital investment — draining India's wealth."})

qs.append({"q":"Which of the following were among the specific economic demands raised by the early nationalists based on their critique of British imperialism?\n1. Reduction in land revenue.\n2. Abolition of the salt tax.\n3. Reduction in military expenditure.\n4. Tariff protection and government aid to modern industry.\nHow many of the above are correctly listed as their demands?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four were genuine economic demands raised by the early nationalists as part of their critique of colonial economic policy."})

qs.append({"q":"The Imperial Legislative Council, constituted by the Indian Councils Act of 1861, is described in the chapter as:","o":["An impotent body designed to disguise official measures as decisions of a representative body","A fully empowered legislature with budgetary control","An assembly with universal adult suffrage","A body composed entirely of elected Indian members"],"a":0,"e":"The Imperial Legislative Council under the 1861 Act had little real power and mainly served to give official measures a veneer of representative sanction."})

qs.append({"q":"Between 1885 and 1892, the nationalist demand for constitutional reforms centred on which two objectives?","o":["Expansion of councils (greater Indian participation) and reform of councils (more powers, especially over finances)","Complete abolition of the councils and direct rule by Indian princes","Introduction of universal adult franchise and a bicameral legislature","Formation of a constituent assembly and a written constitution"],"a":0,"e":"The nationalists' demands during this period focused on expanding council membership for Indians and reforming councils to grant them greater powers, especially budgetary control."})

qs.append({"q":"The nationalist slogan \"No taxation without representation\" reflected their demand for:","o":["Control over the budget, including the power to vote upon and amend it","Abolition of the salt tax alone","Reservation of seats for women in legislatures","Reduction of import duties on British goods"],"a":0,"e":"The slogan captured the demand that Indians should have real budgetary control in the legislature, not merely nominal representation without financial power."})

qs.append({"q":"Which of the following leaders demanded self-government on the lines of self-governing colonies like Canada and Australia, in the years indicated?\n1. Dadabhai Naoroji (1904)\n2. Gopal Krishna Gokhale (1905)\n3. Lokmanya Tilak (1906)\nHow many of the above are correctly matched?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three leaders — Naoroji (1904), Gokhale (1905) and Tilak (1906) — demanded colonial self-government on the Canadian/Australian model."})

qs.append({"q":"Consider the following statements about the Indian Councils Act, 1892:\n1. It raised the number of additional (non-official) members in the Imperial and Provincial Legislative Councils.\n2. It introduced the principle of representation by allowing non-official members to be recommended by bodies such as universities and chambers of commerce.\n3. It allowed the budget to be voted upon and amended by council members.\n4. Officials retained a majority in the councils.\nHow many of the above statements are correct?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 4 are correct. Statement 3 is incorrect — under the 1892 Act, the budget could only be discussed, not voted upon or amended, which was a major limitation the nationalists criticised."})

qs.append({"q":"Between 1862 and 1892, how many Indians were nominated to the Imperial Legislative Council, according to the chapter?","o":["Forty-five","Ten","One hundred","Five hundred"],"a":0,"e":"Only forty-five Indians were nominated to the Imperial Legislative Council between 1862 and 1892, most of them wealthy, landed, and loyalist in orientation."})

qs.append({"q":"Which of the following administrative reforms did the Moderates campaign for?\n1. Indianisation of government service.\n2. Separation of judicial from executive functions.\n3. Increased expenditure on health, sanitation and education.\n4. Better treatment for Indian labour in other British colonies.\nHow many of the above are correctly listed?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four were genuine administrative reform demands raised by the Moderate nationalists."})

qs.append({"q":"The 1897 arrest of Bal Gangadhar Tilak and other leaders/journalists, along with the deportation of the Natu brothers without trial, is cited in the chapter as an example of:","o":["Increased public consciousness around the defence of civil rights becoming integral to the freedom struggle","The complete suppression of nationalist activity by 1900","The beginning of the Non-Cooperation Movement","The formal split between Moderates and Extremists"],"a":0,"e":"These incidents galvanised public outrage and consciousness about civil rights (speech, association, free press) as a core concern of the nationalist movement."})

qs.append({"q":"Which of the following is a criticism levelled against the early nationalists (Moderates), as acknowledged in the chapter's evaluation?","o":["They failed to widen their democratic base by not including the masses, especially women, and not demanding universal suffrage","They had no interest whatsoever in economic issues","They supported armed revolution against the British","They refused to engage with the legislative councils at all"],"a":0,"e":"Despite their achievements, the Moderates are criticised for a narrow social base — they did not mobilise the masses (including women) or demand universal suffrage."})

qs.append({"q":"According to the chapter's evaluation of the early nationalists, which of the following is NOT listed as one of their positive contributions?","o":["They organised large-scale peasant uprisings against zamindars","They created a wide national awakening based on common interests against a common enemy","They exposed the exploitative character of colonial rule","They trained people in political work and popularised modern ideas"],"a":0,"e":"The early nationalists did not organise mass peasant uprisings; their work was largely constitutional, elite-driven, and focused on political education, exposing colonial exploitation, and fostering national awakening."})

qs.append({"q":"Historian Bipan Chandra characterised the period 1858-1905 (the era of early nationalism) as:","o":["\"The seed time of Indian nationalism\"","\"The golden age of Indian nationalism\"","\"An era of complete failure\"","\"The age of revolutionary terrorism\""],"a":0,"e":"Bipan Chandra described 1858-1905 as the seed time of Indian nationalism, when the early nationalists sowed the seeds well and deep."})

qs.append({"q":"Lord Curzon's remark in 1900 — \"The Congress is tottering to its fall, and one of my great ambitions while in India is to assist it to a peaceful demise\" — reflects:","o":["The hostile attitude of the British government towards the Congress","Curzon's support for expanding the Congress's role","A joint British-Congress plan for gradual self-government","Curzon's admiration for Moderate leadership"],"a":0,"e":"Curzon's statement exemplifies the British government's hostility towards the Congress, despite the organisation's moderate methods and professed loyalty to the Crown."})

qs.append({"q":"Which reactionary organisation did British officials encourage Sir Syed Ahmed Khan and Raja Shiv Prasad Singh of Benaras to form, in order to counter Congress propaganda?","o":["United Indian Patriotic Association","Bharat Dharma Mahamandala","Justice Party","Vokkaliga Sangha"],"a":0,"e":"The British encouraged loyalist figures to organise the United Indian Patriotic Association as a counterweight to Congress propaganda, part of a broader 'divide and rule' strategy."})

qs.append({"q":"Which of the following best explains why the Moderates, despite their achievements, failed to build a mass movement in their initial phase?","o":["They lacked political faith in the masses, viewing them as fragmented and needing to be 'welded into a nation' before political participation","They were legally barred from contacting the peasantry","They believed the masses were already fully politically mobilised","They focused exclusively on violent revolutionary methods that alienated ordinary people"],"a":0,"e":"The Moderates doubted the masses' readiness for political engagement, believing that social unity had to precede political mobilisation — a view later nationalists rejected, arguing that participation itself forges unity."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_inc_foundation_moderate_phase",
    "title": "Indian National Congress: Foundation and the Moderate Phase",
    "desc": "Foundation of the INC, theories of its origin, Moderate leaders and methods, economic critique of imperialism, constitutional reforms, and an evaluation of early nationalism",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch11_inc_foundation.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
