import json

qs = []

qs.append({"q":"The Khilafat Movement in India arose primarily from Muslim anger over the British treatment of:","o":["Turkey and its sultan (the Khalifa) after the First World War","Egypt under British occupation","Persia during the war","Afghanistan's border disputes"],"a":0,"e":"Indian Muslims regarded the Ottoman sultan as their spiritual leader (Khalifa); British dismemberment of Turkey and removal of the Khalifa's power after WWI angered Muslims worldwide, including in India."})

qs.append({"q":"The Khilafat Committee, formed in early 1919 to pressure the British on Turkey, was led by which group of leaders?","o":["The Ali brothers (Shaukat Ali and Muhammad Ali), Maulana Azad, Ajmal Khan and Hasrat Mohani","Gandhi, Tilak and Annie Besant","Motilal Nehru, C.R. Das and Vallabhbhai Patel","Jinnah, Malaviya and Mazhar-ul-Haq"],"a":0,"e":"The Khilafat Committee was led by the Ali brothers, Maulana Azad, Ajmal Khan and Hasrat Mohani, seeking to pressure Britain into a favourable settlement for Turkey."})

qs.append({"q":"At the All India Khilafat Conference held in Delhi in November 1919, which call was made regarding relations with the British?","o":["Boycott of British goods","Immediate armed rebellion","Formation of a parallel government","Non-payment of all taxes nationwide"],"a":0,"e":"The November 1919 Delhi conference called for a boycott of British goods, marking a shift towards a more militant Khilafat agitation."})

qs.append({"q":"Which of the following leaders was initially opposed to an alliance with Muslim leaders over the Khilafat issue and sceptical of satyagraha as a political instrument?","o":["Bal Gangadhar Tilak","Mahatma Gandhi","Maulana Azad","Shaukat Ali"],"a":0,"e":"Tilak initially opposed allying with Muslim leaders on a religious issue and doubted the utility of satyagraha, though Gandhi worked to persuade him."})

qs.append({"q":"Which of the following reasons is cited for the Congress's decision to support the non-cooperation programme on the Khilafat question?\n1. It offered a golden opportunity to cement Hindu-Muslim unity.\n2. The Congress was losing faith in constitutional struggle after the Punjab incidents and the Hunter Committee report.\n3. The Congress was aware that the masses were eager to express their discontent.\n4. The British government had officially requested Congress support for Khilafat.\nHow many of the above are correctly identified as reasons?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly reflect the Congress's reasoning. Statement 4 is false — the British government never requested Congress support for the Khilafat cause."})

qs.append({"q":"The Treaty of Sevres, which completely dismembered Turkey and deepened the Khilafat grievance, was signed in:","o":["May 1920","November 1919","August 1920","December 1920"],"a":0,"e":"The Treaty of Sevres, signed in May 1920, dismembered the Ottoman Empire and intensified Muslim anger, fuelling the Khilafat agitation in India."})

qs.append({"q":"The Khilafat Committee formally launched its non-cooperation campaign on:","o":["August 31, 1920","June 1920","September 1920","February 1920"],"a":0,"e":"The Khilafat Committee formally began its non-cooperation campaign on August 31, 1920 — coincidentally, Tilak had died just a month earlier, on August 1, 1920."})

qs.append({"q":"At the Congress's special session held in Calcutta in September 1920, the non-cooperation programme approved included which of the following elements?\n1. Boycott of government schools, colleges and law courts.\n2. Boycott of legislative councils.\n3. Boycott of foreign cloth and promotion of khadi.\n4. Immediate non-payment of all taxes as the first stage.\nHow many of the above are correctly listed as part of the initial programme?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 were part of the first-stage programme; non-payment of taxes and mass civil disobedience were reserved for a later, second stage rather than being included immediately."})

qs.append({"q":"Which leader was NOT willing to include a boycott of councils in the Non-Cooperation programme but ultimately bowed to Congress discipline?","o":["C.R. Das","Mohammad Ali Jinnah","Annie Besant","G.S. Khaparde"],"a":0,"e":"C.R. Das initially opposed the boycott of councils but accepted Congress discipline, unlike Jinnah, Besant and Khaparde, who left the Congress altogether over disagreements."})

qs.append({"q":"At the Nagpur session of the INC (December 1920), a major change was made in the Congress creed, redefining its goal as:","o":["Attainment of swaraj through peaceful and legitimate means, replacing the earlier goal of self-government through constitutional means","Complete independence with no reference to peaceful methods","Dominion status within five years","Federal self-government under British paramountcy"],"a":0,"e":"The Nagpur session redefined the Congress goal as achieving swaraj through peaceful and legitimate means, marking a shift from purely constitutional methods toward extra-constitutional mass struggle."})

qs.append({"q":"Which organisational changes were introduced at the Nagpur Congress session of December 1920?\n1. A Congress Working Committee (CWC) of 15 members was set up.\n2. Provincial Congress Committees were organised on a linguistic basis.\n3. The entry fee to Congress was reduced to four annas.\n4. Universal adult franchise was introduced for Congress elections.\nHow many of the above are correctly identified as changes made at Nagpur?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe the Nagpur reforms; universal adult franchise for Congress elections was not introduced at this session."})

qs.append({"q":"Following the Nagpur session, which leaders left the Congress because they believed in constitutional and lawful struggle rather than mass non-cooperation?","o":["Mohammad Ali Jinnah, Annie Besant, G.S. Khaparde and B.C. Pal","Motilal Nehru, C.R. Das and Vallabhbhai Patel","The Ali brothers and Maulana Azad","Rajendra Prasad and C. Rajagopalachari"],"a":0,"e":"Jinnah, Besant, Khaparde and B.C. Pal left the Congress over disagreement with the non-cooperation strategy; Surendranath Banerjea similarly founded the Indian National Liberal Federation."})

qs.append({"q":"Which national educational institution founded during the Non-Cooperation Movement had Subhash Chandra Bose as its first principal?","o":["National College at Calcutta","Jamia Millia Islamia, Aligarh","Kashi Vidyapeeth","Gujarat Vidyapeeth"],"a":0,"e":"Subhash Chandra Bose served as the first principal of the National College at Calcutta, one of about 800 national schools and colleges established during the movement."})

qs.append({"q":"Which of the following prominent lawyers gave up their legal practice in response to the Non-Cooperation call?\n1. Motilal Nehru and Jawaharlal Nehru\n2. C.R. Das\n3. Vallabhbhai Patel\n4. Rajendra Prasad\nHow many of the above are correctly listed as lawyers who gave up practice?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four — the Nehrus, C.R. Das, Patel and Rajendra Prasad — gave up their legal practices in response to Gandhi's call during the Non-Cooperation Movement."})

qs.append({"q":"The Tilak Swaraj Fund, launched during the Non-Cooperation Movement, collected approximately how much money?","o":["One crore rupees","Ten lakh rupees","Fifty lakh rupees","Five crore rupees"],"a":0,"e":"The Tilak Swaraj Fund was oversubscribed, collecting approximately one crore rupees to finance the movement."})

qs.append({"q":"In July 1921, the Ali brothers called on Muslims to resign from the Army on the grounds that:","o":["Military service was 'unreligious' given the circumstances of British rule","The Army was underpaying Indian soldiers","The Army denied promotions to Muslims","Military service violated the Rowlatt Act"],"a":0,"e":"The Ali brothers argued that continuing military service under British rule was religiously impermissible ('unreligious'), leading to their arrest in September 1921."})

qs.append({"q":"Which local movements/agitations emerged alongside the broader Non-Cooperation Movement in various regions?\n1. Awadh Kisan Movement and Eka Movement in UP.\n2. Mappila Revolt in Malabar.\n3. Sikh agitation for removal of mahants in Punjab.\n4. Vaikom Satyagraha in Travancore.\nHow many of the above are correctly listed as movements of this specific period (1920-22)?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe movements of the 1920-22 period; the Vaikom Satyagraha occurred later, in 1924, and is a distinct event."})

qs.append({"q":"Strikes in tea plantations, steamer services and the Assam-Bengal Railway during the Non-Cooperation Movement were notably led by:","o":["J.M. Sengupta","Rajendra Prasad","Vallabhbhai Patel","C.R. Das"],"a":0,"e":"J.M. Sengupta was a prominent leader of the Assam labour strikes (tea plantations, steamers, railways) during the Non-Cooperation Movement."})

qs.append({"q":"The visit of which British royal figure to India in November 1921 provoked widespread strikes and demonstrations during the Non-Cooperation Movement?","o":["The Prince of Wales","King George V","Queen Victoria's representative","The Duke of Connaught"],"a":0,"e":"The Prince of Wales's visit to India in November 1921 was met with hartals, strikes and demonstrations across the country."})

qs.append({"q":"Which of the following best describes peasant participation during the Non-Cooperation Movement, according to the chapter?","o":["Peasants participated massively, at times breaking Congress restraint against class war by turning against landlords and traders","Peasants remained entirely uninvolved throughout the movement","Only peasants in Bengal participated, with no involvement elsewhere","Peasant participation was limited strictly to non-violent picketing of shops"],"a":0,"e":"Despite Congress's official stance against class conflict, peasants in many areas turned their agitation against landlords and traders as well as the British, reflecting genuine grassroots mobilisation beyond Congress control."})

qs.append({"q":"Regarding Hindu-Muslim unity during the Non-Cooperation-Khilafat Movement, which of the following is noted as a remarkable achievement?","o":["Muslims constituted about two-thirds of those arrested in many places, reflecting an unprecedented level of participation","No Muslims participated in the movement at all","Communal riots completely ended in India after this movement","Muslims participated only in Bengal and nowhere else"],"a":0,"e":"In many places roughly two-thirds of those arrested were Muslims, an unprecedented level of communal cooperation that had not been seen before nor was to be repeated in quite the same way."})

qs.append({"q":"Talks between Gandhi and Viceroy Lord Reading broke down in May 1921 primarily because:","o":["The government wanted Gandhi to persuade the Ali brothers to remove violent suggestions from their speeches","Gandhi refused to discuss the Khilafat issue at all","The government demanded immediate cessation of the boycott of foreign cloth","Gandhi refused to meet the viceroy under any circumstances"],"a":0,"e":"The talks failed as the government sought Gandhi's help in moderating the Ali brothers' rhetoric; Gandhi refused, sensing an attempt to divide the Khilafat and Congress leadership."})

qs.append({"q":"At the Ahmedabad Congress session of 1921 (with C.R. Das presiding while in jail, and Hakim Ajmal Khan acting as president), which key decision was made?","o":["Gandhi was appointed the sole authority to decide on the launch of civil disobedience","The Congress decided to end the Non-Cooperation Movement entirely","The Congress split into Swarajist and no-changer factions","The Congress adopted Purna Swaraj as its goal"],"a":0,"e":"The Ahmedabad session (1921) made Gandhi the sole authority on the question of launching civil disobedience, giving him decisive control over the movement's next phase."})

qs.append({"q":"On February 1, 1922, Gandhi threatened to launch civil disobedience from which location if political prisoners were not released and press controls not removed?","o":["Bardoli, Gujarat","Champaran, Bihar","Chauri Chaura, United Provinces","Ahmedabad, Gujarat"],"a":0,"e":"Gandhi announced his intention to launch civil disobedience from Bardoli in Gujarat if his conditions regarding political prisoners and press freedom were not met."})

qs.append({"q":"The Chauri Chaura incident, which prompted Gandhi to withdraw the Non-Cooperation Movement, occurred on February 5, 1922 in which district?","o":["Gorakhpur district, United Provinces","Champaran district, Bihar","Kheda district, Gujarat","Midnapore district, Bengal"],"a":0,"e":"The Chauri Chaura incident took place in Gorakhpur district, United Provinces, where an agitated crowd set fire to a police station, killing 22 policemen."})

qs.append({"q":"Following the Chauri Chaura incident, how many policemen were killed when the mob set fire to the police station?","o":["Twenty-two","Five","Fifty","Ten"],"a":0,"e":"Twenty-two policemen were killed at Chauri Chaura when the mob torched the police station in retaliation for police firing on protestors."})

qs.append({"q":"The Congress Working Committee, meeting at Bardoli in February 1922 following Chauri Chaura, resolved to stop civil disobedience and instead focus on:","o":["Constructive work including popularisation of khadi, national schools, temperance, Hindu-Muslim unity and anti-untouchability campaigns","Immediate launch of armed revolution","Negotiating dominion status with the Viceroy","Boycotting the upcoming Round Table Conference"],"a":0,"e":"The Bardoli resolution shifted focus to constructive work — khadi promotion, national education, temperance, communal harmony, and anti-untouchability efforts — rather than law-breaking activities."})

qs.append({"q":"Which of the following nationalist leaders expressed bewilderment or dissent at Gandhi's decision to withdraw the Non-Cooperation Movement after Chauri Chaura?","o":["C.R. Das, Motilal Nehru, Subhash Bose and Jawaharlal Nehru","Only Vallabhbhai Patel","Only the Ali brothers","No leader expressed any disagreement"],"a":0,"e":"Prominent leaders including C.R. Das, Motilal Nehru, Subhash Bose and Jawaharlal Nehru expressed bewilderment at the abrupt withdrawal of a movement that had been gaining momentum."})

qs.append({"q":"In March 1922, Gandhi was arrested and sentenced to six years in jail, during which trial he famously declared himself ready to:","o":["\"Invite and submit cheerfully to the highest penalty that can be inflicted\" for what he considered his highest duty as a citizen","Renounce non-violence permanently","Support armed rebellion against the government","Retire from all political activity"],"a":0,"e":"At his 1922 trial, Gandhi delivered his famous statement embracing the highest penalty as his duty, framing his 'crime' as an act of civic conscience."})

qs.append({"q":"Which of the following is cited as a reason for Gandhi's decision to withdraw the Non-Cooperation Movement after Chauri Chaura?\n1. Fear that a violent movement could be easily suppressed by the colonial regime.\n2. Signs of fatigue in sustaining the movement at a high pitch.\n3. Loss of relevance of the Khilafat issue following developments in Turkey.\n4. Direct orders from the British government to end the movement.\nHow many of the above are correctly identified as reasons?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are genuine reasons cited; there was no direct British order compelling Gandhi's withdrawal — the decision was his own, based on his assessment of the movement's trajectory."})

qs.append({"q":"The Khilafat issue lost its relevance after November 1922 when the people of Turkey, under which leader, deprived the sultan of political power and made Turkey a secular state?","o":["Mustafa Kemal Pasha","Enver Pasha","Abdul Hamid II","Ismet Inonu"],"a":0,"e":"Mustafa Kemal Pasha (Ataturk) led the movement that deposed the sultan in November 1922 and transformed Turkey into a secular state, rendering the Khilafat cause moot."})

qs.append({"q":"The institution of the caliphate (Khilafat) itself was formally abolished by the new Turkish state in:","o":["1924","1922","1919","1930"],"a":0,"e":"The caliphate was formally abolished in Turkey in 1924, completing the process that had already undermined the Khilafat Movement's central rationale."})

qs.append({"q":"Which of the following is identified as a criticism of the Khilafat-Non-Cooperation alliance, as reflected in some historiographical assessments?","o":["It communalised national politics to an extent, since national leaders failed to raise Muslim religious-political consciousness to a secular level","It had no impact whatsoever on Hindu-Muslim relations","It completely eliminated communal politics from India for all future decades","It was universally praised without any historiographical criticism"],"a":0,"e":"While it brought urban Muslims into the national movement, critics note the movement partly communalised politics since religious consciousness, rather than secular political consciousness, was mobilised."})

qs.append({"q":"According to the Marxist interpretation cited in the chapter, why did Gandhi and Congress leaders decide to call off the movement despite rising popular momentum?","o":["To keep the movement a 'controlled' affair 'within safe channels' rather than let it develop into an uncontrolled mass upsurge","To please the British government directly","Because the Congress had run out of funds","Because the Khilafat leaders demanded its termination"],"a":0,"e":"The Marxist interpretation suggests Gandhi and Congress leadership withdrew the movement to keep it within controlled, moderate bounds, fearing it would slip into an uncontrollable revolutionary upsurge."})

qs.append({"q":"Which of the following best summarises the overall significance of the Non-Cooperation-Khilafat Movement, according to the chapter's evaluation?","o":["It politicised and activised millions across all social strata, challenging the colonial myth of British invincibility through mass struggle","It achieved complete independence for India in 1922","It ended all future communal tensions permanently","It had no lasting impact on the national movement"],"a":0,"e":"The movement's key significance lay in mobilising vast sections of Indian society and further eroding the myth of British invincibility, building on the earlier economic critique that had already challenged the myth of benevolent colonial rule."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_non_cooperation_khilafat",
    "title": "Non-Cooperation Movement and Khilafat Aandolan",
    "desc": "The Khilafat issue, Congress-Khilafat alliance, the Non-Cooperation programme, its spread and social participation, government repression, the Chauri Chaura incident, and an evaluation of the movement",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch16_non_cooperation_khilafat.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
