import json

qs = []

qs.append({"q":"Consider the following statements about international events that influenced the rise of militant nationalism in India:\n1. Japan's victory over Russia in 1905.\n2. Ethiopia's (Abyssinia's) defeat of the Italian army in 1896.\n3. British reverses in the Boer Wars (1899-1902).\n4. The complete collapse of the Ottoman Empire before 1900.\nHow many of the above are correctly identified as influences?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe events that demolished myths of European invincibility. The Ottoman Empire did not collapse before 1900 — this is incorrect."})

qs.append({"q":"Which of the following administrative measures under Lord Curzon's viceroyalty is cited as a major reactionary policy that provoked nationalist opposition?\n1. Official Secrets Act (1904)\n2. Indian Universities Act (1904)\n3. Calcutta Corporation Act (1899)\n4. Partition of Bengal (1905)\nHow many of the above are correctly attributed to Curzon's rule?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four measures — the Official Secrets Act, Indian Universities Act, Calcutta Corporation Act, and the partition of Bengal — were part of Curzon's reactionary administration."})

qs.append({"q":"The 'Three Ps' — prayer, petition and protest — describing Moderate methods, which the militant nationalists derided as 'political mendicancy', refer to:","o":["The constitutional methods used by the Moderates","The three-stage government repression strategy","The stages of the Swadeshi Movement","The three demands of the Muslim League"],"a":0,"e":"The Extremists mockingly termed the Moderates' constitutional methods of prayer, petition and protest as 'political mendicancy', viewing them as ineffective."})

qs.append({"q":"Which leaders are identified as the most prominent representatives of the militant nationalist school of thought in Bengal, Maharashtra and Punjab respectively?","o":["Aurobindo Ghosh/Bipin Chandra Pal (Bengal), Bal Gangadhar Tilak (Maharashtra), Lala Lajpat Rai (Punjab)","Surendranath Banerjea (Bengal), Pherozshah Mehta (Maharashtra), Dadabhai Naoroji (Punjab)","Ashwini Kumar Datta (Bengal), M.G. Ranade (Maharashtra), Syed Ahmed Khan (Punjab)","Debendranath Tagore (Bengal), Jyotiba Phule (Maharashtra), Dayananda Saraswati (Punjab)"],"a":0,"e":"Aurobindo Ghosh and Bipin Chandra Pal in Bengal, Tilak in Maharashtra, and Lala Lajpat Rai in Punjab were leading figures of militant nationalism, together known as 'Lal-Bal-Pal' alongside Aurobindo."})

qs.append({"q":"The official reason given by the British government for the partition of Bengal (announced in December 1903) was:","o":["That Bengal, with a population of about 78 million, had become too big to be administered efficiently","That Bengal wanted to be divided into linguistic zones","That Bengal's Muslims demanded a separate province","That Calcutta could no longer serve as a capital"],"a":0,"e":"The stated official justification was administrative convenience given Bengal's large population (about 78 million), though the real motive was to weaken Bengal as the nerve centre of Indian nationalism."})

qs.append({"q":"The partition of Bengal was designed to divide the Bengali people along which two lines, according to the chapter's analysis?","o":["Language (reducing Bengalis to a minority in the new Bengal province) and religion (creating a Hindu-majority west and Muslim-majority east)","Caste and class","Urban and rural population","Coastal and inland regions"],"a":0,"e":"The partition scheme reduced Bengalis to a linguistic minority in the western province (dominated by Hindi/Oriya speakers) and split the population religiously into a Hindu-majority west and Muslim-majority east."})

qs.append({"q":"The formal proclamation of the Swadeshi Movement, including the passage of the Boycott Resolution, was made at a massive meeting held at:","o":["Calcutta Townhall on August 7, 1905","Surat in December 1907","Benaras in December 1905","Nagpur in 1907"],"a":0,"e":"The Boycott Resolution was passed at a massive meeting at the Calcutta Townhall on August 7, 1905, formally proclaiming the Swadeshi Movement."})

qs.append({"q":"October 16, 1905, the day the partition of Bengal formally came into force, was observed throughout Bengal as:","o":["A day of mourning, marked by fasting, bathing in the Ganga and singing Bande Mataram in processions","A day of celebration with fireworks","A public holiday declared by the government","The founding day of the Indian National Congress"],"a":0,"e":"October 16, 1905 was observed as a day of mourning, with people fasting, bathing in the Ganga, tying rakhis to symbolise unity, and singing Bande Mataram in processions."})

qs.append({"q":"'Amar Sonar Bangla', composed during the anti-partition agitation and later adopted as the national anthem of Bangladesh, was written by:","o":["Rabindranath Tagore","Bankim Chandra Chatterjee","Dwijendralal Ray","Subramania Bharati"],"a":0,"e":"Rabindranath Tagore composed Amar Sonar Bangla during the Swadeshi Movement; it was later adopted as Bangladesh's national anthem."})

qs.append({"q":"At which INC session (1906) was the goal of the Congress declared to be \"self-government or swaraj like the United Kingdom or the colonies\" of Australia or Canada?","o":["Calcutta session, presided over by Dadabhai Naoroji","Benaras session, presided over by Gokhale","Surat session, presided over by Rashbehari Ghosh","Bombay session, presided over by Pherozshah Mehta"],"a":0,"e":"At the Calcutta session of 1906, under Dadabhai Naoroji's presidency, the INC for the first time declared 'swaraj' as its goal, though its precise meaning was left undefined."})

qs.append({"q":"Which of the following is identified as one of the three key reasons for the Extremists gaining dominant influence over the Swadeshi Movement in Bengal after 1905?","o":["The Moderate-led movement had failed to yield results, and government repression had embittered the nationalists","The Moderates voluntarily handed over leadership to the Extremists","The British government officially endorsed Extremist leadership","The Muslim League fully supported the Extremist programme"],"a":0,"e":"Among the reasons cited were the failure of Moderate methods to achieve results, divisive government tactics, and severe government repression, all of which embittered nationalists and strengthened Extremist influence."})

qs.append({"q":"Aurobindo Ghosh described the purpose of the Extremist programme of passive resistance as aiming to:","o":["\"Make the administration under present conditions impossible by an organised refusal to do anything which will help either the British commerce or British officialdom\"","Persuade the British Parliament to grant dominion status immediately","Establish a parallel government in exile","Organise an armed uprising against British garrisons"],"a":0,"e":"Aurobindo articulated passive resistance as a strategy of organised non-cooperation to make British administration and commerce unworkable in India."})

qs.append({"q":"The Swadesh Bandhab Samiti, a corps of volunteers that emerged as a powerful means of mass mobilisation during the Swadeshi Movement, was organised in Barisal by:","o":["Ashwini Kumar Dutta","V.O. Chidambaram Pillai","Subramania Siva","Aurobindo Ghosh"],"a":0,"e":"Ashwini Kumar Dutta organised the Swadesh Bandhab Samiti in Barisal, which generated political consciousness through lectures, swadeshi songs, social work, and training."})

qs.append({"q":"V.O. Chidambaram Pillai, along with Subramania Siva, is particularly associated with which swadeshi enterprise at Tuticorin that challenged a British shipping company?","o":["Swadeshi Steam Navigation Company","Bengal National College","Bengal Institute of Technology","Indian Society of Oriental Art"],"a":0,"e":"Chidambaram Pillai founded the Swadeshi Steam Navigation Company at Tuticorin, directly challenging the British India Steam Navigation Company."})

qs.append({"q":"Tilak's use of traditional festivals as vehicles of swadeshi propaganda in western India, later spreading to Bengal too, notably involved which festivals?","o":["Ganapati and Shivaji festivals","Durga Puja and Kali Puja","Ram Navami and Janmashtami","Onam and Pongal"],"a":0,"e":"Tilak popularised the Ganapati and Shivaji festivals as vehicles for spreading swadeshi and nationalist propaganda among the masses."})

qs.append({"q":"The Bengal National College, set up as part of the swadeshi/national education programme and inspired by Tagore's Shantiniketan, had which nationalist leader as its first principal?","o":["Aurobindo Ghosh","Bipin Chandra Pal","Ashwini Kumar Dutta","Rabindranath Tagore"],"a":0,"e":"Aurobindo Ghosh served as the first principal of the Bengal National College, part of the swadeshi national education movement."})

qs.append({"q":"The National Council of Education, set up to organise literary, scientific and technical education on national lines through the vernacular medium, was established on:","o":["August 15, 1906","October 16, 1905","December 30, 1905","August 7, 1905"],"a":0,"e":"The National Council of Education was established on August 15, 1906, as part of the swadeshi education programme."})

qs.append({"q":"Which artist, taking inspiration from Ajanta, Mughal and Rajput paintings, broke the domination of Victorian naturalism in the Indian art scene during the Swadeshi era?","o":["Abanindranath Tagore","Nandalal Bose","Jagdish Chandra Bose","Rajnikant Sen"],"a":0,"e":"Abanindranath Tagore pioneered a new Indian art style drawing from Ajanta, Mughal and Rajput traditions, breaking free from Victorian naturalism."})

qs.append({"q":"Consider the following statements regarding the extent of mass participation during the Swadeshi Movement:\n1. Students actively participated in propagating and practising swadeshi.\n2. Women, especially urban middle-class women, took part in processions and picketing for the first time on a significant scale.\n3. The vast majority of upper and middle-class Muslims actively joined the movement.\n4. Some strikes were organised in jute mills and railway workshops.\nHow many of the above statements are correct?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 4 are correct. Statement 3 is incorrect — most upper and middle-class Muslims stayed away from the movement or, under Nawab Salimullah, even supported the partition."})

qs.append({"q":"The All India Muslim League was founded on December 30, 1905 (some sources say 1906), with support from which loyalist figure who backed the partition of Bengal?","o":["Nawab Salimullah of Dacca","Sir Syed Ahmed Khan","Aga Khan","Maulana Azad"],"a":0,"e":"Nawab Salimullah of Dacca, who supported the partition of Bengal, was closely associated with the founding of the Muslim League, encouraged by the British as a counterweight to the Congress."})

qs.append({"q":"In September 1905, more than 250 Bengali clerks of which company in Howrah walked out in protest against a derogatory work regulation, marking an early instance of labour unrest during the Swadeshi period?","o":["Burn Company","East Indian Railway","British India Steam Navigation Company","Bengal Chamber of Commerce"],"a":0,"e":"Bengali clerks of the Burn Company in Howrah struck work in September 1905 over a discriminatory work rule, an early expression of labour unrest linked to swadeshi sentiment."})

qs.append({"q":"The partition of Bengal was finally annulled in 1911, primarily to:","o":["Curb the menace of revolutionary terrorism","Reward the Moderates for their loyalty","Fulfil a promise made at the Surat session","Appease the Indian National Congress's Extremist wing"],"a":0,"e":"The annulment of the partition in 1911 was mainly a measure to counter rising revolutionary terrorism, and it came as a shock to the Muslim political elite who had supported the partition."})

qs.append({"q":"Which of the following is identified as a reason for the decline of the Swadeshi Movement by 1908?","o":["Severe government repression, lack of an effective organisational structure, and the movement's narrow social base confined largely to upper and middle classes","Complete success in achieving all its demands","Total absence of any government repression","Universal support across all religious communities, making further mobilisation unnecessary"],"a":0,"e":"The movement declined due to harsh repression, absence of a disciplined organisational structure, leaderlessness after arrests/deportations, the Surat split, and failure to reach the peasantry and Muslim masses."})

qs.append({"q":"Despite its decline, the Swadeshi Movement is regarded as a 'turning point' in Indian nationalism mainly because:","o":["It drew in previously untouched sections like students, women and workers, and generated ideas and techniques (passive resistance, non-cooperation) later used in Gandhian politics","It led immediately to full independence for India","It ended the Moderate-Extremist divide within the Congress","It resulted in universal adult franchise being granted"],"a":0,"e":"The movement mobilised new social groups and pioneered techniques of struggle — passive resistance, boycott, non-cooperation — that Gandhian politics would later develop into a mass movement."})

qs.append({"q":"According to the chapter's comparison of Moderates and Extremists, the Moderates' ideological inspiration was drawn mainly from:","o":["Western liberal thought and European history","Indian history and Hindu traditional symbols","Marxist class analysis","Islamic reformist thought"],"a":0,"e":"The Moderates drew their ideological inspiration from Western liberal thought and European history, in contrast to the Extremists who drew on Indian history, cultural heritage and Hindu traditional symbols."})

qs.append({"q":"Which of the following correctly distinguishes the Extremists' view from the Moderates' regarding political connections with Britain?","o":["The Extremists believed such connections would perpetuate British exploitation, while the Moderates believed connections with Britain served India's interests","The Extremists supported closer ties with Britain, while the Moderates opposed any connection","Both groups agreed that British connections were harmful to India","Neither group had any clear position on this issue"],"a":0,"e":"The Moderates believed political connections with Britain served India's social, political and cultural interests, while the Extremists rejected this, seeing such connections as perpetuating exploitation."})

qs.append({"q":"Which of the following is identified as a negative or 'socially reactionary' aspect of the Extremist ideology despite its politically progressive stance on mass mobilisation?","o":["Revivalist and obscurantist undertones, such as Tilak's opposition to the Age of Consent Bill and use of Hindu festivals, which alienated many Muslims","Complete rejection of any religious symbolism in politics","Full support for women's rights and gender equality reforms","Active collaboration with the British government on all policy matters"],"a":0,"e":"The Extremists' association with Hindu symbols and festivals, and figures like Tilak opposing certain social reforms, gave their movement revivalist and communal undertones that alienated Muslims."})

qs.append({"q":"The Congress split at Surat took place in which year, at a session where the Moderates sought to exclude Tilak from the presidency?","o":["December 1907","December 1905","December 1906","October 1909"],"a":0,"e":"The Surat split occurred in December 1907, when the Moderates proposed Rashbehari Ghosh as president instead of Tilak, and sought to drop resolutions on swadeshi, boycott and national education."})

qs.append({"q":"At the Surat session (1907), the Moderates opposed Tilak's presidency partly on the ground that:","o":["A leader from the host province (Tilak from Bombay, where Surat is located) could not be session president","Tilak had never been a Congress member","Tilak supported the partition of Bengal","Tilak was too moderate for the Extremist camp"],"a":0,"e":"Since Surat lay in Bombay Presidency (Tilak's home province), a convention barred a leader from the host province from serving as session president, which the Moderates used against Tilak."})

qs.append({"q":"Which of the following repressive laws were enacted by the British government between 1907 and 1911 to check anti-government activity during the militant nationalist phase?\n1. Seditious Meetings Act, 1907\n2. Criminal Law Amendment Act, 1908\n3. Indian Press Act, 1910\n4. Rowlatt Act, 1919\nHow many of the above are correctly listed as part of this 1907-1911 repression?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correct as part of the 1907-1911 repressive laws. The Rowlatt Act was enacted in 1919, well after this period, and is incorrectly included."})

qs.append({"q":"Bal Gangadhar Tilak was tried for sedition in 1909 for articles he wrote in Kesari regarding:","o":["A bomb thrown by Bengal revolutionaries at Muzaffarpur, which killed two European women","The Ilbert Bill controversy","The partition of Bengal","The formation of the Muslim League"],"a":0,"e":"Tilak was tried and convicted for sedition over his Kesari articles commenting on the Muzaffarpur bomb incident, in which two European women were killed."})

qs.append({"q":"For his 1908 sedition conviction, Tilak was sentenced to six years' transportation and sent to which prison?","o":["Mandalay jail, Burma","Andaman Cellular Jail","Yerwada Jail, Poona","Ahmednagar Fort"],"a":0,"e":"Tilak was sentenced to six years' transportation and imprisoned at Mandalay jail in Burma from 1908 to 1914."})

qs.append({"q":"John Morley, the Secretary of State for India, described the British government's strategy towards nationalists during this phase using which policy metaphor?","o":["'Carrot and stick' — a three-pronged approach of repression, conciliation and further suppression","'Divide and conquer' — encouraging Hindu-Muslim conflict exclusively","'Salami slicing' — gradual territorial annexation","'Scorched earth' — total suppression with no concessions"],"a":0,"e":"Morley's strategy of 'rallying' or 'carrot and stick' involved mildly repressing Extremists while placating Moderates with concessions to isolate the radicals."})

qs.append({"q":"The Simla Deputation of October 1906, led by the Aga Khan, met Lord Minto to demand:","o":["Separate electorates for Muslims and representation in excess of their numerical strength","Abolition of the zamindari system in Bengal","A separate Muslim province carved out of Punjab","Reservation for Muslims in the Indian Civil Service examination alone"],"a":0,"e":"The Simla Deputation, led by the Aga Khan, demanded separate electorates for Muslims and representation beyond their proportional population share, citing their loyalty to the empire."})

qs.append({"q":"The Muslim League, initially floated by Nawab Salimullah of Dacca along with Nawabs Mohsin-ul-Mulk and Waqar-ul-Mulk, was founded in:","o":["December 1906","October 1905","December 1905","July 1905"],"a":0,"e":"The All India Muslim League was founded in December 1906, intended to preach loyalty to the empire and keep Muslim intelligentsia away from the Congress."})

qs.append({"q":"The Morley-Minto Reforms were formally enacted through which legislation?","o":["Indian Councils Act, 1909","Government of India Act, 1919","Indian Councils Act, 1892","Government of India Act, 1935"],"a":0,"e":"The Morley-Minto Reforms translated into the Indian Councils Act of 1909."})

qs.append({"q":"Which of the following was the most detrimental feature of the Morley-Minto Reforms (Indian Councils Act, 1909), from the nationalist perspective?","o":["Introduction of separate electorates for Muslims","Increase in the number of elected members in legislative councils","Permission for legislatures to ask questions and supplementaries","Appointment of Satyendra Sinha to the viceroy's executive council"],"a":0,"e":"The introduction of separate electorates for Muslims is considered the most damaging provision, as it institutionalised communal division in Indian political representation."})

qs.append({"q":"Under the Morley-Minto Reforms, which Indian was appointed as the first Indian member of the viceroy's executive council in 1909?","o":["Satyendra Sinha","Dadabhai Naoroji","Gopal Krishna Gokhale","Surendranath Banerjea"],"a":0,"e":"Satyendra Sinha became the first Indian appointed to the viceroy's executive council under the Morley-Minto Reforms of 1909."})

qs.append({"q":"Regarding the budget provisions under the Indian Councils Act of 1909, legislatures were permitted to:","o":["Vote on separate items of the budget, though the budget as a whole could not be voted upon","Vote upon and amend the entire budget freely","Reject the budget entirely if a majority so wished","Have no role whatsoever in budget matters"],"a":0,"e":"The 1909 reforms allowed legislatures to vote on separate items within the budget, but the budget as a whole remained outside their voting power — a significant limitation."})

qs.append({"q":"Lord Morley's statement — \"If it could be said that this chapter of reforms led directly or indirectly to the establishment of a parliamentary system in India, I, for one, would have nothing at all to do with it\" — reveals that the Morley-Minto Reforms:","o":["Were never intended to lead towards responsible, parliamentary self-government for India","Were explicitly designed to grant full self-government","Aimed to abolish the office of viceroy","Were meant to immediately end separate electorates"],"a":0,"e":"Morley's statement makes clear that the reforms were not intended as a step towards parliamentary or responsible government in India, contrary to nationalist aspirations."})

qs.append({"q":"Jawaharlal Nehru's critique of the separate electorates introduced by the Morley-Minto Reforms described their effect as:","o":["Creating a political barrier that grew with every extension of franchise, corrupting the entire political and social system 'like some canker'","Strengthening national unity across communities","Having a negligible long-term political impact","Improving administrative efficiency without social cost"],"a":0,"e":"Nehru criticised separate electorates as a growing 'canker' that isolated communities politically and corrupted the broader unifying process that had developed over centuries."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_militant_nationalism",
    "title": "Era of Militant Nationalism (1905-1909)",
    "desc": "Causes of militant nationalism, partition of Bengal, the Swadeshi and Boycott Movement, Moderate-Extremist differences, the Surat split, government repression, and the Morley-Minto Reforms",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch12_militant_nationalism.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
