import json

qs = []

# ==================================================================
# History (UPSC) — Chapter 4: India on the Eve of British Conquest
# Source: Spectrum, "A Brief History of Modern India", Chapter 4
# ==================================================================

qs.append({"q":"Consider the following statements about Nadir Shah's invasion of India (1738-39):\n1. He defeated the Mughal army under Muhammad Shah at the Battle of Karnal on 13 February 1739.\n2. Apart from the Peacock Throne and the Kohinoor diamond, he is estimated to have collected around seventy crore rupees from the official treasury and rich nobles.\n3. He permanently annexed Delhi and the Gangetic plains into the Persian empire.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is incorrect — Nadir Shah looted and devastated Delhi but did NOT annex it; he instead gained the Mughal territory WEST of the Indus (including Kabul), leaving Delhi and the Gangetic plains under (weakened) Mughal control."})

qs.append({"q":"Which one of the following correctly identifies the three Battles of Panipat and their outcomes?","o":["First (1526, Babur vs. Ibrahim Lodi) founded the Mughal Empire; Second (1556, Akbar vs. Hemu) secured continuation of Mughal rule; Third (1761, Marathas vs. Ahmad Shah Abdali) ended Maratha ambitions of ruling India","First (1556) founded the Mughal Empire; Second (1526) secured Mughal continuation; Third (1739) ended Maratha ambitions","All three Battles of Panipat were fought exclusively between the Mughals and the Marathas","The Third Battle of Panipat was fought between the English East India Company and Ahmad Shah Abdali"],"a":0,"e":"The correct sequence is: First Battle of Panipat (1526, Babur vs. Ibrahim Lodi) founded the Mughal Empire; Second (1556, Akbar vs. Hemu) secured its continuation; Third (1761, Marathas vs. Ahmad Shah Abdali) ended Maratha ambitions to rule India — none were fought exclusively between Mughals and Marathas, and the Third Battle involved Abdali against the Marathas, not the English."})

qs.append({"q":"Which one of the following is NOT among the reasons cited for Panipat being a recurrently favoured battlefield in Indian history?","o":["Its dense monsoon forests provided natural cover for infantry ambush tactics","Its flat terrain was well suited to cavalry movement, the dominant mode of warfare of the time","Its proximity to Delhi made it easy to transport military supplies while keeping the capital insulated from conflict","It lay on the Grand Trunk Road built by Sher Shah Suri, making it accessible to invaders"],"a":0,"e":"Panipat's actual advantages were its FLAT terrain suited to cavalry (not dense forests, which the region lacks), proximity to Delhi for supply transport, its location on the Grand Trunk Road, short monsoon duration, and local availability of skilled armourers/smiths — dense monsoon forests are not a feature of the Panipat region at all."})

qs.append({"q":"Arrange the following later Mughal emperors in the correct chronological order of their reigns:\n1. Farrukhsiyar\n2. Muhammad Shah\n3. Bahadur Shah I\n4. Shah Alam II","o":["3-1-2-4","1-3-2-4","3-2-1-4","4-3-2-1"],"a":0,"e":"The correct chronological order is: Bahadur Shah I (1709-1712) → Farrukhsiyar (1713-1719) → Muhammad Shah (1719-1748) → Shah Alam II (1759-1806) — Farrukhsiyar reigned before, not after, Muhammad Shah."})

qs.append({"q":"Which one of the following statements about the Sayyid Brothers (Abdulla Khan and Hussain Ali), known as the 'King Makers' of the later Mughal period, is correct?","o":["They helped Farrukhsiyar kill Jahandar Shah to become emperor, but later dethroned Farrukhsiyar himself (with Peshwa Balaji Vishwanath's help), marking the first time in Mughal history that an emperor was killed by his own nobles","They were defeated and killed by Nadir Shah during his 1739 invasion","They founded the independent kingdom of Awadh","They served as the primary architects of the 1717 farmans granted to the English East India Company"],"a":0,"e":"The Sayyid Brothers helped Farrukhsiyar eliminate Jahandar Shah, but later (1719, with Peshwa Balaji Vishwanath's assistance) dethroned, blinded, and killed Farrukhsiyar himself — the first instance of a Mughal emperor being killed by his own nobles. They had no role in Nadir Shah's invasion (which came two decades later), founding Awadh (Saadat Khan's achievement), or in the 1717 English farmans (which Farrukhsiyar himself issued)."})

qs.append({"q":"Which one of the following Mughal emperors granted the East India Company the Diwani (revenue-collection rights) of Bengal, Bihar and Orissa in perpetuity, under the Treaty of Allahabad (August 1765)?","o":["Shah Alam II","Alamgir II","Akbar II","Bahadur Shah II"],"a":0,"e":"Shah Alam II, whose reign saw both the Third Battle of Panipat (1761) and the Battle of Buxar (1764), granted the Diwani of Bengal, Bihar and Orissa to the Company under the 1765 Treaty of Allahabad, after which he came under Company protection at Allahabad."})

qs.append({"q":"Which one of the following statements about Bahadur Shah II (Bahadur Shah Zafar), the last Mughal emperor, is correct?","o":["He was made a symbolic figurehead during the Revolt of 1857, captured by the English afterwards, and died in exile at Rangoon in 1862, with the Mughal Empire legally ending on 1 November 1858 via a declaration of Queen Victoria","He voluntarily abdicated the throne in 1835 when Mughal-named coinage was discontinued","He led the Mughal forces to victory at the Third Battle of Panipat","He granted the Diwani of Bengal to the East India Company"],"a":0,"e":"Bahadur Shah II (Zafar) was declared (symbolically, and ultimately futilely) Emperor of India during the 1857 Revolt, captured by the English, exiled to Rangoon where he died in 1862; the Mughal Empire legally ended on 1 November 1858 via Queen Victoria's declaration — the coinage discontinuation (1835) occurred under Akbar II, Panipat III long predates his reign, and Shah Alam II (not Zafar) granted the Bengal Diwani."})

qs.append({"q":"With reference to the causes of the Mughal Empire's decline, consider the following statements:\n1. The zamindars' shifting allegiance and growing regional loyalty contributed significantly to the empire's fragmentation.\n2. The 'jagirdari crisis' refers to a growing shortage of jagirs available for the expanding nobility, worsened by Aurangzeb's practice of showing artificially enhanced income figures on jagir records.\n3. The Mughal decline is attributed by historians solely to individual character failings of successive emperors, with no structural or economic factors at play.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe genuine structural causes of Mughal decline. Statement 3 is incorrect — historians like Satish Chandra and Irfan Habib emphasise DEEPER structural/economic causes (jagirdari crisis, agrarian stagnation, administrative overreach), explicitly noting that individual character failings, while relevant, must be seen against this broader structural backdrop, not as the sole explanation."})

qs.append({"q":"Which one of the following historians attributed the Mughal Empire's collapse principally to military inefficiency at the centre, arguing the empire was 'already doomed' before Nadir Shah, Ahmad Shah Abdali, Dupleix, or Clive appeared on the scene?","o":["William Irvine","Irfan Habib","J.N. Sarkar","Satish Chandra"],"a":0,"e":"William Irvine (Army of the Indian Mughals) argued that military inefficiency was the principal cause of the Mughal collapse, contending that the empire was already doomed before any external actor (Nadir Shah, Abdali, Dupleix or Clive) appeared — a view distinct from Irfan Habib's agrarian-crisis focus, J.N. Sarkar's 'rottenness of society' thesis, or Satish Chandra's structural/multi-causal analysis."})

qs.append({"q":"According to the book's three-fold classification of regional states that emerged from Mughal decline, which one of the following pairs is correctly matched?","o":["Successor States (e.g., Awadh, Bengal, Hyderabad) — provinces that broke away in practice while nominally not challenging Mughal sovereignty","Independent Kingdoms (e.g., Awadh, Bengal) — states set up directly by rebels against the Mughal empire","The New States (e.g., Mysore, Rajput states) — provinces destabilised from within Mughal control","All three categories describe identical processes with no meaningful distinction"],"a":0,"e":"Successor States (Awadh, Bengal, Hyderabad) emerged from Mughal provinces whose governors established de facto independent, hereditary rule without formally challenging Mughal sovereignty. Independent Kingdoms (Mysore, Rajput states) arose from destabilisation of Mughal control, while New States (Maratha, Sikh, Jat) were founded by actual rebels against the empire — the second and third options in this question scramble these correct category-example pairings."})

qs.append({"q":"Nizam-ul-Mulk (Kilich Khan), founder of the Asaf-Jah dynasty of Hyderabad, established his control over the Deccan after defeating and killing which one of the following rivals at the Battle of Shakr-Kheda (1724)?","o":["Mubariz Khan","Saadat Khan","Alivardi Khan","Murshid Quli Khan"],"a":0,"e":"Nizam-ul-Mulk defeated and killed Mubariz Khan (appointed by the Mughal emperor as full-fledged Deccan viceroy) at the Battle of Shakr-Kheda in 1724, subsequently assuming control of the Deccan and taking the title Asaf-Jah in 1725 — Saadat Khan founded Awadh, Alivardi Khan seized power in Bengal, and Murshid Quli Khan founded independent Bengal, all unrelated to this Deccan contest."})

qs.append({"q":"Which one of the following correctly identifies the founder of the independent state of Bengal and a key later ruler who made Bengal effectively independent of Mughal control by paying only a nominal tribute?","o":["Murshid Quli Khan founded the state; Alivardi Khan later made it effectively independent after killing Sarfaraz Khan at Gheria in 1740","Alivardi Khan founded the state; Murshid Quli Khan later made it independent","Saadat Khan founded the state of Bengal","Shuja-ud-din founded the state of Bengal and made it fully sovereign, ending all Mughal tribute obligations"],"a":0,"e":"Murshid Quli Khan founded independent Bengal (succeeded by his son Shuja-ud-din in 1727); Alivardi Khan later killed Sarfaraz Khan at Gheria (1740) and assumed power, making himself effectively independent while still paying a nominal yearly tribute to the Mughal emperor — Saadat Khan founded Awadh, not Bengal."})

qs.append({"q":"Which one of the following rulers is correctly associated with founding an independent state in Kerala centred at Travancore, extending its boundaries from Kanyakumari to Cochin, and organising his army along Western lines?","o":["Martanda Varma","Haidar Ali","Suraj Mal","Saadat Khan"],"a":0,"e":"Martanda Varma established the independent state of Travancore (Kerala), extending it from Kanyakumari to Cochin and modernising his army along Western lines — Haidar Ali is associated with Mysore, Suraj Mal with the Jat state of Bharatpur, and Saadat Khan with Awadh."})

qs.append({"q":"Under whose rule did the Jat state of Bharatpur reach its zenith, extending territory from the Ganga in the east to the Chambal in the south and encompassing the Subahs of Agra, Mathura, Meerut and Aligarh?","o":["Suraj Mal","Churaman","Badan Singh","Banda Bahadur"],"a":0,"e":"Suraj Mal brought Jat power to its zenith, providing efficient administration and expanding territory across Agra, Mathura, Meerut and Aligarh — Churaman and Badan Singh were earlier founders of the Bharatpur state, while Banda Bahadur was a Sikh (not Jat) leader."})

qs.append({"q":"With reference to Maharaja Ranjit Singh's rise to power in Punjab, consider the following statements:\n1. He belonged to the Sukarchakiya misl, one of the twelve Sikh confederacies (misls) that had organised themselves following the invasions of Nadir Shah and Ahmad Shah Abdali.\n2. He conquered Lahore in 1799 and Amritsar in 1802, subsequently acknowledging British rights over cis-Sutlej territories through the Treaty of Amritsar.\n3. Under British pressure, he signed the Tripartite Treaty (1838) with Shah Shuja and the English Company, agreeing to allow British troop passage through Punjab to place Shah Shuja on the Kabul throne.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — Ranjit Singh's Sukarchakiya misl origins, his 1799/1802 conquests followed by the Treaty of Amritsar (acknowledging British cis-Sutlej rights), and the 1838 Tripartite Treaty (facilitating British passage for the First Anglo-Afghan War's Shah Shuja restoration) are all accurately described."})

qs.append({"q":"Which one of the following statements correctly describes the Marathas' position on the eve of British conquest, as discussed in the context of regional power struggles?","o":["Despite their defeat by Ahmad Shah Abdali at the Third Battle of Panipat (1761), the Marathas recovered quickly and went on to pose the most formidable challenge to English East India Company supremacy in India","The Marathas were permanently destroyed as a political power following their defeat at the Third Battle of Panipat","The Marathas never sought any formal Mughal sanction for collecting taxes like chauth and sardeshmukhi","The Marathas' territorial influence never extended beyond Maharashtra"],"a":0,"e":"Despite the 1761 Panipat defeat, the Marathas recovered swiftly and became the most formidable rival to English supremacy in India — they had, in fact, sought Mughal legal sanction for collecting chauth and sardeshmukhi across India, and by 1740 had extended influence over Gujarat, Malwa and Bundelkhand, well beyond their Maharashtra homeland."})

qs.append({"q":"Which one of the following rulers of Mysore was involved in prolonged warfare with the British, a conflict later continued by his son Tipu Sultan?","o":["Haidar Ali","The Wodeyar dynasty rulers exclusively, without any Haidar Ali involvement","Martanda Varma","Chanda Sahib"],"a":0,"e":"Haidar Ali, who brought Mysore (nominally still under the Wodeyar dynasty) under his effective control, engaged in continuous warfare with the British — a struggle carried forward after him by his son Tipu Sultan; Martanda Varma belongs to Travancore, and Chanda Sahib was a Carnatic claimant unrelated to Mysore."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in qs]
print("Total:", len(qs), "| unique:", len(set(texts)))
for q in qs:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch4_eve_of_conquest.json", "w") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print("Saved.")
