import json

qs = []

# ==================================================================
# History (UPSC) — Chapter 5: Expansion and Consolidation of British Power
# Source: Spectrum, "A Brief History of Modern India", Chapter 5
# ==================================================================

# --- Causes of British Success / debate on conquest ---

qs.append({"q":"With reference to the historiographical debate on whether the British conquest of India was 'accidental' or 'intentional', which one of the following statements is correct?","o":["John Seeley argued the conquest was made 'blindly, unintentionally and accidentally', while other historians hold that the British worked with a clear intention to build an empire; most balanced assessments suggest the Company initially expanded to protect trade interests before later developing a deliberate imperial design","All historians unanimously agree that the British conquest was entirely accidental with no strategic intent at any stage","The 'intentional conquest' school argues that British politicians had no role in shaping Company policy after 1757","John Seeley's 'fit of absent-mindedness' framing is universally accepted as the definitive and uncontested explanation"],"a":0,"e":"John Seeley's 'accidental conquest' view is contrasted with the 'intentional' school; the balanced view (reflected in the text) is that Company officials initially expanded territory to protect trade interests amid factionalised local politics, with a more deliberate imperial design emerging later — no such unanimous or uncontested consensus actually exists among historians."})

qs.append({"q":"Which one of the following is NOT among the factors cited as contributing to British success in establishing empire in India?","o":["A strong sense of unified political nationalism among rival Indian rulers, encouraging them to jointly resist British encroachment","Superior arms, military discipline and regular salary payment for troops","A civil discipline and fair selection system based on merit rather than caste or personal ties","Strong financial backup, including profits from global trade and superior sea power"],"a":0,"e":"The text explicitly notes the OPPOSITE was true — Indian rulers lacked a unified sense of political nationalism and often fought each other as much as the British, at times even supporting the British against neighbouring Indian rulers; superior arms/discipline, merit-based selection, and financial/naval strength were genuine, cited factors in British success."})

# --- Bengal: Plassey, Buxar, Allahabad, Dual Government ---

qs.append({"q":"Consider the following statements about the Battle of Plassey (23 June 1757):\n1. Robert Clive forged a secret alliance with Mir Jafar, Rai Durlabh, Jagat Seth and Omichand prior to the battle, effectively deciding its outcome in advance.\n2. Siraj-ud-daula's 50,000-strong force was defeated by a comparatively small English force, largely due to the conspiracy among the nawab's own officials.\n3. Following the battle, Mir Jafar became Nawab and granted the English company large sums of money along with the zamindari of the 24 Parganas.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — Clive's pre-battle conspiracy with Mir Jafar and other nawab-court figures, the resulting lopsided defeat of Siraj's larger force, and Mir Jafar's post-battle grants (money plus the 24 Parganas zamindari) are all accurately described, making Plassey's outcome effectively predetermined before the fighting began."})

qs.append({"q":"Mir Kasim, considered the ablest Nawab among Alivardi Khan's successors, shifted his capital from Murshidabad to which one of the following locations to gain distance from the Company at Calcutta?","o":["Munger, in Bihar","Patna, in Bihar","Dacca, in Bengal","Allahabad, in the Mughal heartland"],"a":0,"e":"Mir Kasim shifted his capital to Munger (Bihar) specifically to keep a safe distance from Company influence at Calcutta, alongside reorganising his bureaucracy and remodelling his army for greater efficiency."})

qs.append({"q":"Which one of the following was the IMMEDIATE trigger for the tensions that led to war between Mir Kasim and the English, culminating in the Battle of Buxar (1764)?","o":["Disputes over the misuse of the Company's duty-free trading permit (dastak), which caused loss of tax revenue to the Nawab and unequal competition for local merchants","A direct dispute over the zamindari of the 24 Parganas granted after Plassey","Mir Kasim's refusal to accept the Treaty of Allahabad's terms","The Black Hole Tragedy of 1756"],"a":0,"e":"The misuse of the Company's dastak (trade permit exempting goods from duties) by Company servants for their private trade — causing revenue loss to Mir Kasim and unfair competition for Indian merchants — was the immediate trigger for the Nawab-Company tussle that escalated into war; the 24 Parganas grant, the Treaty of Allahabad, and the Black Hole Tragedy are each related to different episodes."})

qs.append({"q":"The Battle of Buxar (22 October 1764) was fought between the English forces (under Major Hector Munro) and a combined force comprising which one of the following?","o":["Mir Kasim, the Nawab of Awadh (Shuja-ud-Daula), and the Mughal Emperor Shah Alam II","Mir Jafar, Siraj-ud-daula, and the Nawab of Awadh","Tipu Sultan, the Nizam of Hyderabad, and the Marathas","The Dutch, the French, and the Nawab of Bengal"],"a":0,"e":"Buxar pitted the English against the combined forces of Mir Kasim, Shuja-ud-Daula (Nawab of Awadh), and the Mughal Emperor Shah Alam II — its significance lay in the fact that even the Mughal Emperor himself was defeated, establishing the English as a major power across northern India."})

qs.append({"q":"Under the Treaty of Allahabad (August 1765), which one of the following correctly describes the terms agreed to by Emperor Shah Alam II?","o":["He agreed to reside at Allahabad under Company protection and issued a farman granting the Diwani of Bengal, Bihar and Orissa to the East India Company in return for an annual payment of Rs 26 lakh","He agreed to cede Allahabad and Kara to Shuja-ud-Daula and pay a war indemnity of Rs 50 lakh to the Company","He was deposed and exiled to Rangoon by the Company","He was granted full sovereign control over Bengal, Bihar and Orissa, superseding Company authority"],"a":0,"e":"Shah Alam II agreed to reside at Allahabad (ceded to him by Shuja-ud-Daula) under Company protection and granted the Diwani of Bengal, Bihar and Orissa via farman for an annual payment of Rs 26 lakh — it was actually Shuja-ud-Daula (not Shah Alam II) who ceded Allahabad/Kara and paid the Rs 50 lakh indemnity; the emperor's exile to Rangoon describes Bahadur Shah II nearly a century later, and the Diwani grant transferred revenue authority TO the Company, not sovereign control to the emperor."})

qs.append({"q":"Which one of the following statements correctly describes the 'Dual Government' system introduced in Bengal (1765-1772) by Robert Clive?","o":["The Company held the diwani (revenue collection) rights while nominally leaving nizamat (police and judicial) functions and the appearance of authority with the Nawab, though the Company effectively controlled army and revenue","The Nawab held all diwani and nizamat functions, with the Company acting purely as a commercial entity with no administrative role","Warren Hastings introduced the system in 1772 and it continued until 1857","The system granted full administrative and military independence to the Nawab of Bengal"],"a":0,"e":"Under Dual Government, the Company held real power via diwani rights (revenue) while leaving the appearance of authority (nizamat functions) with the puppet Nawab — actual control over army and finances rested with the Company. It was Warren Hastings who ABOLISHED (not introduced) the system in 1772, following its administrative breakdown."})

# --- Anglo-Mysore Wars & Tipu Sultan ---

qs.append({"q":"The First Anglo-Mysore War (1767-69) concluded with which one of the following treaties, considered humiliating for the English after Haidar Ali's forces appeared before the gates of Madras?","o":["Treaty of Madras (1769)","Treaty of Mangalore (1784)","Treaty of Seringapatam (1792)","Treaty of Salbai (1782)"],"a":0,"e":"The Treaty of Madras (4 April 1769) ended the First Anglo-Mysore War, providing for exchange of prisoners and mutual restitution of conquests, with the English also promising to assist Haidar Ali if he were attacked by another power — a treaty widely regarded as humiliating for the English given the panic caused by Haidar's approach to Madras."})

qs.append({"q":"Which one of the following was cited as a factor triggering the Second Anglo-Mysore War (1780-84), relating to Haidar Ali's grievances against the English?","o":["The English attempted to capture Mahe, a French possession on the Malabar coast that Haidar Ali considered under his protection, at a time when Haidar found the French more helpful than the English in supplying war material","Haidar Ali's refusal to pay tribute following the Treaty of Madras","The death of Nizam-ul-Mulk and the resulting succession dispute in Hyderabad","The English company's refusal to lease Madras to Haidar Ali"],"a":0,"e":"The Second Anglo-Mysore War was triggered by the English attempt to capture Mahe (a French possession Haidar considered under his protection), compounded by Haidar's growing reliance on French military supplies given English inaction during a prior Maratha attack — unrelated to Nizam-ul-Mulk's succession (a much earlier Hyderabad matter) or any Madras leasing dispute."})

qs.append({"q":"Which one of the following battles during the Second Anglo-Mysore War saw Haidar Ali's forces defeat the English and capture their commander?","o":["Battle of Porto Novo led to an English defeat of Haidar, though he later regrouped and defeated the English, capturing their commander Braithwaite","The Battle of Plassey","The Battle of Ambur","The Battle of Buxar"],"a":0,"e":"Although Haidar Ali suffered a defeat at Porto Novo (November 1781) against Sir Eyre Coote's forces, he subsequently regrouped and defeated an English force, capturing its commander Braithwaite — the war ultimately ended inconclusively with the Treaty of Mangalore (1784) after Haidar's death from cancer in December 1782."})

qs.append({"q":"The Third Anglo-Mysore War (1790-92) arose from a dispute between Tipu Sultan and Travancore over which one of the following issues, and concluded with which treaty?","o":["Travancore's purchase of Jalkottal and Cannanore from the Dutch in Cochin state (a feudatory of Tipu), concluding with the Treaty of Seringapatam (1792)","A dispute over Malabar's pepper trade, concluding with the Treaty of Mangalore","Tipu's refusal to pay the war indemnity from the First Anglo-Mysore War, concluding with the Treaty of Madras","Travancore's alliance with the French, concluding with the Treaty of Salbai"],"a":0,"e":"Tipu declared war on Travancore in 1790 after it purchased Jalkottal and Cannanore from the Dutch within Cochin (Tipu's feudatory), viewing this as a violation of his sovereign rights; the war (with the English siding with Travancore, and Cornwallis capturing Bangalore and besieging Seringapatam) ended with the 1792 Treaty of Seringapatam, under which Tipu ceded nearly half his territory and paid a three-crore-rupee indemnity, with his two sons taken as hostages."})

qs.append({"q":"Which one of the following statements about the Fourth Anglo-Mysore War (1799) is correct?","o":["Lord Wellesley, concerned about Tipu Sultan's growing contacts with the French, used the Subsidiary Alliance system and a charge-sheet alleging treasonable intent to justify war, which ended with Tipu's death defending Seringapatam on 4 May 1799","The war was triggered by Tipu's refusal to release his sons taken hostage after the Treaty of Seringapatam","Tipu Sultan won the war, forcing the English to pay an indemnity","The war was fought primarily between Tipu and the Marathas, with the English playing only a minor supporting role"],"a":0,"e":"Lord Wellesley (Governor-General from 1798) alleged Tipu was plotting with the French and other powers, using this and the Subsidiary Alliance framework to justify the Fourth War (17 April-4 May 1799), which ended with Tipu's death defending Seringapatam — Tipu had actually fulfilled the Treaty of Seringapatam's terms and secured his sons' release BEFORE this war, and it was the ENGLISH (with Maratha and Nizam support) that decisively defeated Tipu, not the reverse."})

qs.append({"q":"Which one of the following is a genuine achievement or characteristic attributed to Tipu Sultan, 'the Tiger of Mysore', in the book's assessment?","o":["He is credited as a pioneer of rocket technology in India, having written a military manual on rocket operation, and also introduced sericulture to Mysore","He is described by the book as an unambiguous religious bigot with no record of protecting any Hindu religious institutions","He refused any European assistance in training his army, relying purely on indigenous training methods","He is uniformly regarded by the book as history's first Indian nationalist, fighting explicitly for India's freedom from British rule"],"a":0,"e":"Tipu is credited as a pioneer of rocket technology (with a written military manual) and as an introducer of sericulture to Mysore. The book explicitly REJECTS both extreme characterisations offered as distractors here: it notes he sanctioned funds for repairing the Sringeri Temple (countering the 'unambiguous bigot' framing) and explicitly states calling him 'the first Indian nationalist' is an anachronistic misreading of history, since no sense of Indian nationalism existed in his time; he also did take French assistance to train his soldiers, without letting them become a pressure group."})

# --- Ring-Fence / Subsidiary Alliance / Doctrine of Lapse ---

qs.append({"q":"Warren Hastings' 'Ring-Fence' policy, aimed at creating buffer zones to protect Company frontiers, is best illustrated by which one of the following arrangements?","o":["The Company undertook to defend Awadh's frontiers (thereby indirectly defending Bengal) on condition that the Nawab of Awadh would bear the costs of the defending army","The Company annexed Awadh outright to eliminate any buffer-state arrangement","The policy was first applied to the Marathas rather than to any northern buffer state","It required Indian rulers to dismiss all non-British Europeans from their service, similar to the later Subsidiary Alliance"],"a":0,"e":"The Ring-Fence policy's defining example was the Company's defence of Awadh's frontiers, funded by the Nawab, effectively making Awadh a buffer protecting Bengal — Awadh was NOT annexed under this policy (annexation came much later, under Dalhousie in 1856), and the clause requiring dismissal of non-British Europeans was a distinct feature of Wellesley's LATER Subsidiary Alliance system, not Ring-Fence."})

qs.append({"q":"Consider the following statements about Lord Wellesley's Subsidiary Alliance system (Governor-General, 1798-1805):\n1. Under the system, an allied Indian ruler had to accept a permanent British force in his territory and pay a subsidy for its maintenance, along with a British Resident at his court.\n2. The allied ruler could not employ non-British Europeans, or wage war or negotiate with other Indian rulers, without prior Company consultation.\n3. In return, the ruler retained full command over his own foreign policy including alliances with other European powers.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe Subsidiary Alliance's core terms. Statement 3 is incorrect — the entire point of the system was that the allied ruler LOST independent control over foreign relations and could not negotiate or war with other rulers without Company consultation, directly contradicting the claim of retained control over foreign policy."})

qs.append({"q":"Which one of the following correctly describes the 'four stages' in the evolution of the Subsidiary Alliance system, as it developed over time?","o":["From offering troop assistance, to joint military campaigns, to demanding money instead of men for a Company-maintained contingent, to finally demanding cession of territory when payment obligations went unmet","From immediate territorial annexation, to joint campaigns, to troop assistance, to final financial demands","The system remained static throughout its application, with no distinct evolutionary stages","From financial demands first, evolving eventually to pure troop-assistance offers with no territorial implications"],"a":0,"e":"The four stages moved from (i) offering troop assistance, to (ii) joint campaigning with the ally's own soldiers, to (iii) demanding money instead of men for a Company-recruited and maintained contingent, to (iv) demanding territorial cession when the fixed payment could not be met — a progressively more exploitative and encroaching relationship, not a static or reverse-ordered one."})

qs.append({"q":"Which one of the following Indian states was the LAST major Maratha confederation to accept the Subsidiary Alliance, doing so in 1818?","o":["The Holkars","The Peshwa","The Bhonsle Raja of Berar","The Sindhia"],"a":0,"e":"The Holkars were the last Maratha confederation to accept the Subsidiary Alliance, in 1818 — the Peshwa (December 1801), the Bhonsle Raja of Berar (December 1803), and Sindhia (February 1804) had all accepted it considerably earlier."})

qs.append({"q":"Under Lord Dalhousie's 'Doctrine of Lapse', which one of the following statements is correct?","o":["The doctrine held that an adopted son could inherit his foster father's private property but not the state itself, with the paramount British power deciding whether to grant or annex the state — Dalhousie applied it with unusual zeal, though he was not its original architect","The doctrine was invented entirely by Dalhousie with no precedent in earlier British-Indian relations","The doctrine automatically granted the state to any legitimately adopted son without exception","The doctrine was based on clear, unambiguous Hindu legal precedent regarding adoption and state succession"],"a":0,"e":"Dalhousie applied the doctrine (adopted sons inherit private property, not the state, with annexation/grant left to British discretion) with unusual zeal, though he did not originate it — earlier instances existed (e.g., Ranjit Singh's own annexations on grounds of 'lapse', and an 1820 Company acquisition of petty Cis-Sutlej states); the doctrine's supposed Hindu-law basis was actually described as inconclusive/unclear, not a settled precedent."})

qs.append({"q":"Which one of the following pairs of a state annexed under the Doctrine of Lapse and its year of annexation is correctly matched?","o":["Satara — 1848; Jhansi and Nagpur — 1854","Satara — 1854; Jhansi and Nagpur — 1848","Awadh — 1848; Satara — 1856","Jhansi — 1856; Nagpur — 1848"],"a":0,"e":"Satara was annexed in 1848 (the earliest major Doctrine of Lapse annexation during Dalhousie's tenure), followed by Jhansi and Nagpur in 1854 — Awadh, notably, was annexed in 1856 on grounds of misgovernment rather than lapse of heirs, making it a distinct case from the other options listed."})

qs.append({"q":"Which one of the following statements about the annexation of Awadh (1856) is correct?","o":["Awadh was annexed on grounds of chronic misgovernment (following reports by Residents Sleeman and Outram), not under the Doctrine of Lapse, with Nawab Wajid Ali Shah refusing to sign away his rights and being exiled to Calcutta","Awadh was annexed strictly under the Doctrine of Lapse due to the absence of a male heir","Dalhousie personally favoured immediate annexation from the outset, overriding the Court of Directors' preference for permanent British administration while retaining the Nawab's titles","Awadh's annexation had no negative political consequences and was widely welcomed across India"],"a":0,"e":"Awadh's 1856 annexation followed reports of chronic misgovernment (from Residents Sleeman and then Outram), and was NOT a Doctrine of Lapse case (Awadh's Nawab was not childless) — in fact, Dalhousie initially preferred retaining British administration while letting the Nawab keep his titles, but the Court of Directors ordered outright annexation instead; Wajid Ali Shah refused to sign away his rights and was exiled to Calcutta, and the annexation is explicitly described as 'a political blunder for which the British had to pay a heavy price during the Revolt of 1857'."})

qs.append({"q":"By the end of his eight-year tenure (1848-56) as Governor-General, Lord Dalhousie had annexed how many states, adding approximately how much territory to British India?","o":["Eight states, adding roughly a quarter million square miles of territory","Three states, adding roughly fifty thousand square miles","Twelve states, adding roughly half a million square miles","Dalhousie annexed no states directly; all annexations occurred under his successors"],"a":0,"e":"Dalhousie annexed eight states during his 1848-56 tenure, adding roughly a quarter million square miles to British India — a process the text describes as having 'almost completed the process of expansion of British power in India' begun with the 1757 victory at Plassey."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in qs]
print("Total:", len(qs), "| unique:", len(set(texts)))
for q in qs:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch5_expansion_british_power.json", "w") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print("Saved.")
