import json

qs = []

# ==================================================================
# History (UPSC) — Chapter 3: Advent of the Europeans in India
# Source: Spectrum, "A Brief History of Modern India", Chapter 3
# Covers: Portuguese, Dutch, English, French (Carnatic Wars)
# ==================================================================

# --- PORTUGUESE ---

qs.append({"q":"Consider the following statements about the background to the European search for a sea route to India:\n1. The fall of Constantinople to the Ottoman Turks in 1453 disrupted the overland flow of Indian goods to European markets via Arab intermediaries.\n2. The Treaty of Tordesillas (1494) divided the non-Christian world between Portugal and Spain along an imaginary line in the Atlantic.\n3. Bartholomew Dias rounded the Cape of Good Hope in 1487, over a decade before Vasco da Gama's expedition reached India.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — the 1453 fall of Constantinople, the 1494 Treaty of Tordesillas dividing the non-Christian world between Portugal and Spain, and Dias's 1487 rounding of the Cape of Good Hope (a decade before da Gama's 1497-98 voyage) collectively set the stage for the Portuguese sea route to India."})

qs.append({"q":"Vasco da Gama's fleet arrived at Calicut in May 1498 and was received by which one of the following local rulers?","o":["The Zamorin (Samuthiri) of Calicut","The Sultan of Bijapur","The Raja of Cochin","The Nawab of Bengal"],"a":0,"e":"Vasco da Gama was given a friendly reception at Calicut by the Hindu ruler, the Zamorin (Samuthiri), whose kingdom's prosperity depended on Calicut's position as a trading entrepot — the Zamorin initially had no apprehensions about Portuguese intentions."})

qs.append({"q":"Which one of the following Portuguese governors in India is credited with introducing the 'Blue Water Policy' (cartaze system) after avenging an earlier naval defeat off Diu against the combined Egyptian and Gujarat fleets?","o":["Francisco De Almeida","Alfonso de Albuquerque","Nino da Cunha","Vasco da Gama"],"a":0,"e":"Francisco De Almeida, appointed governor in 1505, avenged the 1507 defeat off Diu in 1508 and pursued the 'Blue Water Policy' (cartaze system) aimed at making the Portuguese master of the Indian Ocean — Albuquerque succeeded him and became the actual founder of Portuguese power in the East."})

qs.append({"q":"Which one of the following statements about Alfonso de Albuquerque's tenure as Portuguese governor in India is correct?","o":["He acquired Goa from the Sultan of Bijapur in 1510, making it the first Indian territory under European control since Alexander the Great, and abolished the practice of sati during his rule","He acquired Goa from the Mughal emperor Akbar in 1530","He introduced the practice of sati in Portuguese territories for the first time","He was the first Portuguese governor in India, preceding Francisco De Almeida"],"a":0,"e":"Albuquerque acquired Goa from the Sultan of Bijapur in 1510 — described as the first Indian territory under European control since Alexander the Great — and abolished sati as an interesting feature of his rule; he succeeded, not preceded, Almeida as governor, and Goa's acquisition predates Akbar's reign by decades and had no Mughal connection."})

qs.append({"q":"With reference to the decline of Portuguese power in India, consider the following statements:\n1. The Marathas captured Salsette and Bassein from the Portuguese in 1739.\n2. The union of the Spanish and Portuguese crowns (1580-81) dragged Portugal into Spain's wars with England and Holland, damaging Portuguese trade monopoly in India.\n3. The Portuguese were the first Europeans to arrive in India and also the last to leave, with Goa, Daman and Diu recaptured by India only in 1961.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — the 1739 Maratha capture of Salsette and Bassein, the 1580-81 Iberian Union's damaging effect on Portuguese trade, and Goa/Daman/Diu's recapture only in 1961 (making the Portuguese both first to arrive and last to leave) are all accurately described in the text."})

qs.append({"q":"Which one of the following was an important MILITARY contribution attributed to the Portuguese in India, later adopted by other European powers and eventually by Indian rulers such as the Marathas and Sikhs?","o":["A system of drilling groups of infantry on the Spanish model, introduced in the 1630s as a counter to Dutch pressure","The introduction of gunpowder to India for the first time in recorded history","The construction of the first Indian naval dockyards under Chola patronage","The abolition of the mansabdari system"],"a":0,"e":"The Portuguese introduced infantry drilling on the Spanish model in the 1630s (as a counter to Dutch pressure), a practice first adopted by the French and English and later by the Marathas and Sikhs, giving rise to 'sepoy' armies as new tools of empire — gunpowder predates the Portuguese arrival in India, naval dockyards under the Cholas predate this period by centuries, and the mansabdari system is a Mughal administrative institution unrelated to the Portuguese."})

# --- DUTCH ---

qs.append({"q":"Which one of the following statements about the Dutch East India Company (VOC) and its activities in India is correct?","o":["It was formed in 1602 by the States-General of the Netherlands amalgamating several trading companies, and established its first Indian factory at Masulipatnam in 1605","It was formed in 1580 immediately following Francis Drake's circumnavigation voyage","Its first Indian factory was established at Surat, prior to any settlement in the Coromandel region","It never received powers to wage war, conclude treaties, or take possession of territory"],"a":0,"e":"The VOC (East India Company of the Netherlands) was formed in 1602, and its first Indian factory was founded at Masulipatnam (Andhra) in 1605 — it was explicitly empowered to wage war, conclude treaties, take territory, and erect fortresses, quite unlike the fabricated claim of no such powers; Surat's Dutch factory (1616) came later."})

qs.append({"q":"The 'Amboyna Massacre' of 1623, in which the Dutch killed ten Englishmen and nine Japanese at a location in present-day Indonesia, is significant for which one of the following reasons?","o":["It intensified Anglo-Dutch rivalry in the East, eventually contributing to a 1667 compromise under which the English withdrew claims on Indonesia while the Dutch retired from India","It marked the first ever confrontation between any two European powers in Asia","It led directly to the permanent expulsion of the Dutch from all of Asia","It resulted in an alliance between the Dutch and the Portuguese against the English"],"a":0,"e":"The Amboyna Massacre intensified Anglo-Dutch rivalry, eventually leading to an 1667 compromise: the English withdrew claims on Indonesia while the Dutch retired from India to focus on their more profitable Indonesian trade — it did not mark the first ever European confrontation in Asia (the Portuguese predate this rivalry), nor did it end Dutch presence across all of Asia, nor produce any Dutch-Portuguese alliance."})

qs.append({"q":"Which one of the following battles/events dealt a crushing blow to Dutch ambitions in India, occurring during the broader context of Anglo-Dutch rivalry?","o":["The Battle of Hooghly (November 1759)","The Battle of Plassey (1757)","The Battle of Ambur (1749)","The Battle of St. Thome (1746)"],"a":0,"e":"The Battle of Hooghly (November 1759) dealt the crushing blow to Dutch ambitions in India, following the Third Anglo-Dutch War (1672-74) tensions — Plassey, Ambur, and St. Thome are all Anglo-French/Anglo-Indian conflicts unrelated to the Dutch defeat."})

# --- ENGLISH ---

qs.append({"q":"Queen Elizabeth I issued a charter granting exclusive trading rights to the company that would become the English East India Company on which one of the following dates?","o":["31 December 1600","1 January 1600","31 December 1608","1 January 1615"],"a":0,"e":"Queen Elizabeth I issued the charter to the 'Governor and Company of Merchants of London trading into the East Indies' on 31 December 1600, initially granting a 15-year trading monopoly, later extended indefinitely by a fresh charter in 1609."})

qs.append({"q":"With reference to Sir Thomas Roe's mission to the Mughal court (1615-1619), which one of the following statements is correct?","o":["Though he failed to conclude a formal commercial treaty with Emperor Jahangir, he secured permission to set up English factories at Agra, Ahmedabad, and Broach","He successfully concluded a formal commercial treaty with Jahangir covering all of the Mughal empire","He was the first Englishman to ever visit the Mughal court, preceding Captain William Hawkins","He represented the Dutch East India Company rather than the English"],"a":0,"e":"Sir Thomas Roe, accredited ambassador of James I, failed to secure a formal commercial treaty but obtained permission for English factories at Agra, Ahmedabad and Broach — Captain William Hawkins had actually arrived at Jahangir's court earlier (1609), preceding Roe, and Roe represented English (not Dutch) interests."})

qs.append({"q":"Bombay came into the possession of the English East India Company through which one of the following routes?","o":["It was given to King Charles II of England as dowry upon his marriage to the Portuguese princess Catherine of Braganza in 1662, and later transferred to the Company in 1668 for an annual payment of ten pounds","It was purchased directly by the East India Company from the Sultan of Bijapur in 1510","It was seized militarily from the Dutch following the Battle of Hooghly","It was granted by the Mughal emperor Farrukhsiyar as part of his 1717 farman"],"a":0,"e":"Bombay was given to Charles II as dowry on his 1662 marriage to Catherine of Braganza, and the Crown transferred it to the East India Company in 1668 for a nominal annual payment of ten pounds — unrelated to the earlier (1510) Portuguese acquisition of Goa from Bijapur, the Anglo-Dutch conflict, or the 1717 Farrukhsiyar farman (which concerned Bengal, Gujarat and Hyderabad trading privileges)."})

qs.append({"q":"Which one of the following correctly describes the founding of the English settlement that became Calcutta?","o":["Job Charnock negotiated a treaty with the Mughals in February 1690 and returned to Sutanuti in August 1690; the Company later bought the zamindari of Sutanuti, Gobindapur and Kalikata in 1698, with the fortified settlement named Fort William in 1700","Calcutta was founded directly by Sir Thomas Roe during his 1615-1619 mission","The English received Calcutta as part of the Golden Farman issued by the Sultan of Golconda in 1632","Fort William was established in 1751, immediately following the Second Carnatic War"],"a":0,"e":"Job Charnock's 1690 negotiations and return to Sutanuti, followed by the Company's 1698 purchase of the zamindari of the three villages (Sutanuti, Gobindapur, Kalikata), culminated in the 1700 founding of the fortified settlement Fort William (Calcutta) — unrelated to Roe's earlier Mughal-court mission, the Golden Farman (which concerned Golconda/Madras trade), or the Carnatic Wars."})

qs.append({"q":"The 1717 farman issued by the Mughal emperor Farrukhsiyar, popularly known as the 'Magna Carta of the (East India) Company', granted which one of the following privileges?","o":["Exemption from additional customs duties in Bengal (beyond the earlier annual payment), permission to issue dastaks for goods transportation, and currency privileges for Company-minted Bombay coins across the Mughal empire","Full sovereign control over the province of Bengal","The permanent expulsion of the French and Dutch companies from Indian trade","Exclusive rights over the Mughal empire's salt and opium trade"],"a":0,"e":"Farrukhsiyar's 1717 farman granted the Company customs exemptions in Bengal, permission to issue dastaks (passes) for goods, additional land rental rights around Calcutta, duty exemption in Hyderabad, an annual-payment duty exemption in Surat, and currency privileges for Bombay-minted coins — it did NOT grant sovereign control over Bengal, expel rival European companies, or grant a salt/opium trade monopoly, none of which formed part of its actual terms."})

qs.append({"q":"The two rival English trading companies operating in India (following the 1688 English Revolution) were amalgamated in 1708 under which one of the following names?","o":["The United Company of Merchants of England Trading to the East Indies","The Honourable East India Company","The Governor and Company of Merchants of London","The Perpetual Company of the Indies"],"a":0,"e":"The 1708 merger, under pressure from the Crown and Parliament, created the 'United Company of Merchants of England Trading to the East Indies' — this merged entity (the East India Company from 1708 to 1873) went on to establish British political power in India. 'The Perpetual Company of the Indies' was actually the reorganised FRENCH company (from 1720), not English."})

# --- FRENCH & CARNATIC WARS ---

qs.append({"q":"Which one of the following statements about the French East India Company (Compagnie des Indes Orientales) is correct?","o":["It was founded in 1664 under the patronage of Louis XIV's minister Colbert, and was granted a 50-year monopoly on French trade in the Indian and Pacific Oceans","It was founded before the Portuguese, Dutch, and English companies, making the French the first Europeans to trade with India","It never established any settlements on India's east coast, operating exclusively on the west coast","Pondicherry was its first Indian settlement, founded immediately upon the company's establishment in 1664"],"a":0,"e":"The French East India Company was founded in 1664 (Colbert/Louis XIV) with a 50-year Indian/Pacific Ocean trade monopoly — the French were actually the LAST major European power to arrive in India for trade, not the first, and established settlements on BOTH coasts (Surat in the west, Masulipatnam/Chandernagore/Pondicherry in the east); Pondicherry itself was founded only in 1674, a decade after the company's establishment."})

qs.append({"q":"Pondicherry, described as the 'nerve centre of French power in India', was founded in which one of the following years, and under whose stewardship did it later flourish as the most important French settlement?","o":["Founded in 1674; flourished under Francois Martin's guidance","Founded in 1710; flourished under Joseph Dupleix's guidance","Founded in 1664; flourished under Colbert's direct administration","Founded in 1693; flourished under Dutch stewardship after its capture"],"a":0,"e":"Pondicherry was founded in 1674 (Francois Martin obtaining the site from Sher Khan Lodi, governor of Valikondapuram) and flourished under Martin's able guidance, even after a temporary Dutch capture in 1693-97 — Dupleix's prominence came decades later, and Colbert never administered India directly (he was a minister in France)."})

qs.append({"q":"Consider the following statements about the causes and course of the Anglo-French rivalry in India (the Carnatic Wars):\n1. The rivalry reflected the broader traditional rivalry between England and France, beginning with the Austrian War of Succession and ending with the Seven Years' War.\n2. The First Carnatic War (1740-48) concluded with the Treaty of Aix-La-Chapelle, under which Madras was restored to the English.\n3. The Battle of St. Thome during the First Carnatic War demonstrated that a small, disciplined European-style army could defeat a much larger Indian army.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 only"],"a":0,"e":"All three statements are correct — the Carnatic Wars mirrored the broader Anglo-French European rivalry (1740-1763 span), the First Carnatic War ended via the Treaty of Aix-La-Chapelle (Madras restored to the English), and the Battle of St. Thome (a small French force under Captain Paradise defeating a much larger force under Mahfuz Khan) was indeed an eye-opening demonstration of disciplined-army superiority."})

qs.append({"q":"Which one of the following pairs of contenders was supported respectively by the French and the English during the Second Carnatic War (1749-54)?","o":["French supported Muzaffar Jang (for the Deccan) and Chanda Sahib (for the Carnatic); English supported Nasir Jang and Anwar-ud-din Khan","French supported Nasir Jang and Anwar-ud-din Khan; English supported Muzaffar Jang and Chanda Sahib","Both France and England supported Muzaffar Jang and Chanda Sahib jointly","French and English both remained neutral, leaving the succession disputes to be settled by the Marathas"],"a":0,"e":"The French backed Muzaffar Jang's claim to the Deccan subahdari and Chanda Sahib's claim to the Carnatic nawabi, while the English backed the rival claimants Nasir Jang and Anwar-ud-din Khan respectively — this rivalry played out through the Battle of Ambur (1749), where the Anglo-supported Anwar-ud-din was defeated and killed."})

qs.append({"q":"Robert Clive's celebrated defence of Arcot (1751) during the Second Carnatic War is best described by which one of the following?","o":["With only around 210 men, Clive captured Arcot as a diversionary tactic to relieve pressure on the besieged Trichinopoly, prompting Chanda Sahib to rush back with a much larger force but ultimately fail to retake the fort","Clive led a force of over 10,000 men to directly relieve the siege of Trichinopoly without any diversionary manoeuvre","Clive's action at Arcot took place during the Third Carnatic War, following the fall of Dupleix","Clive's Arcot campaign ended in a decisive French victory over the English"],"a":0,"e":"Clive's diversionary capture of Arcot (August 1751) with roughly 210 men successfully drew Chanda Sahib's much larger force (about 4,000 men) away from the siege of Trichinopoly; despite a 53-day siege attempt to retake Arcot, Chanda Sahib failed, and the episode (part of the SECOND, not Third, Carnatic War) is remembered as a major early triumph for Clive and the English."})

qs.append({"q":"Which one of the following statements about Joseph Francis Dupleix, the French governor in India, is correct?","o":["He was conferred the title of 'Nawab' by the Mughal emperor and Muzaffar Jang, the subahdar of the Deccan, and is credited by historians with the qualities of an administrator, diplomat, and leader with broad political vision","He was the founder of Pondicherry as a French settlement in 1674","He was the first French governor to establish a factory at Surat under Francois Caron in 1667","He led the Dutch forces during the Anglo-Dutch rivalry in India"],"a":0,"e":"Dupleix was conferred the Nawab title by the Mughal emperor/Muzaffar Jang and is credited by historians with administrator/diplomat/leadership qualities and broad political vision — Pondicherry's founding (1674) and the Surat factory (1667, under Caron) both predate Dupleix's rise to prominence (Governor-General of Pondicherry from 1741), and he was French, having no connection to Dutch forces."})

qs.append({"q":"As French Governor-General of Pondicherry from 1741, Dupleix undertook which one of the following administrative measures, despite facing several challenges including Maratha invasion and famine?","o":["He reduced public expenditure and balanced income and expenditure (including cutting officers' salaries), while disobeying Company directors by enhancing Pondicherry's fortifications using his own personal wealth","He fully complied with all Company directives, including reducing Pondicherry's fortifications to save costs","He abandoned Pondicherry entirely in favour of relocating French headquarters to Chandernagore","He dismantled Pondicherry's role as a commercial emporium in favour of purely military functions"],"a":0,"e":"Dupleix reduced public expenditure and balanced the budget (despite council opposition) while explicitly DISOBEYING the Company directors' cost-cutting instructions when it came to fortifications, using his own wealth to strengthen Pondicherry's defences, and simultaneously developed it as a commercial emporium of south India — the opposite of abandoning or purely militarising the settlement."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in qs]
print("Total:", len(qs), "| unique:", len(set(texts)))
for q in qs:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch3_advent_europeans.json", "w") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print("Saved.")
