import json

qs = []

# ==================================================================
# History (UPSC) — Chapter 1: Sources for the History of Modern India
# Source: Spectrum, "A Brief History of Modern India" (Rajiv Ahir & Kalpana
# Rajaram), Chapter 1
# ==================================================================

qs.append({"q":"Consider the following statements about 'archives' as a historical source:\n1. Archives refer to a collection of historical records and documents, usually primary source documents.\n2. Archival documents are typically created as a necessary part of some administrative, legal, social or commercial activity, not consciously written to convey information to a future generation.\n3. The records of the East India Company provide a detailed account of trading conditions only for the period after 1857.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 correctly describe archives. Statement 3 is incorrect — the East India Company's records provide a detailed account of trading conditions for the period 1600-1857, i.e., BEFORE the Crown took over, not after 1857."})

qs.append({"q":"Official records relevant to the history of Modern India fall into four broad categories of archival material. Which one of the following is NOT among these four categories?","o":["Foreign missionary society records exclusively","Central Government archives","State Government archives","Judicial records"],"a":0,"e":"The four categories are: (i) central government archives, (ii) state government archives, (iii) records of intermediate and subordinate authorities, and (iv) judicial records — with private archives and foreign archival sources treated as separate, additional categories. 'Foreign missionary society records' is not one of the four official categories, though such records (e.g., of the Church Missionary Society) are a valuable foreign/private source in their own right."})

qs.append({"q":"With reference to the National Archives of India and related records, consider the following statements:\n1. James Rennell was appointed the first Surveyor General of Bengal in 1767, marking the beginning of the scientific mapping of India by the Survey of India.\n2. A separate series of records called 'Home Political' was started in 1907 to deal exclusively with political and communal issues.\n3. The records of the Reforms Office are useful for studying India's constitutional developments from 1920 to 1937.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — James Rennell's 1767 appointment marked the start of the Survey of India's scientific mapping; the Home Political series began in 1907, splitting off from the general home department's public series; and the Reforms Office records cover constitutional developments from 1920-1937."})

qs.append({"q":"The 'Peshwa Daftar', housed in the Alienation Office at Pune, is considered the most valuable single source for studying the history of which one of the following?","o":["The Maratha polity for nearly a century before the fall of the Peshwas","The Mughal administration under Aurangzeb","The Vijayanagara Empire's revenue system","The Sikh Empire under Ranjit Singh"],"a":0,"e":"The Peshwa Daftar (housed in the Alienation Office, Pune) is described as the most valuable single source for studying Maratha history for almost a century before the fall of the Peshwas — unrelated to Mughal, Vijayanagara, or Sikh administrative records."})

qs.append({"q":"Consider the following pairs of princely-state archival collections and their present housing locations:\n1. Records of the Kingdom of Lahore (Khalsa Darbar records, 1800-1849) — housed as part of the Punjab archival collections\n2. Archives of Jaipur, Bikaner, Jodhpur and Udaipur — housed at the Rajasthan State Archives, Bikaner\n3. State papers on Dogra rule in Jammu and Kashmir (from 1846) — housed at Jammu\nHow many of the above pairs are correctly matched?","o":["All three","Only two","Only one","None"],"a":0,"e":"All three are correctly matched per the book — Khalsa Darbar records document the Kingdom of Lahore (1800-1849), Rajasthan princely-state records are consolidated at the Rajasthan State Archives, Bikaner, and Dogra-rule (from 1846) state papers are housed at Jammu."})

qs.append({"q":"With reference to the archival records of the three British Presidencies, which one of the following statements is correct?","o":["The early records of Fort William (Bengal Presidency) were lost during the sack of Calcutta in 1756, but Bengal Presidency records after the Battle of Plassey survive in a more or less complete series","The Madras Presidency's archival records begin only after 1800, well after those of Bombay and Bengal","The Bombay Presidency's archives are housed in the National Archives of India, New Delhi, rather than in Maharashtra","The Madras Presidency records contain no information on the Anglo-French struggle in the Deccan"],"a":0,"e":"Fort William's early Bengal records were lost in the 1756 sack of Calcutta, but post-Plassey Bengal records survive nearly completely (split between the National Archives of India and the West Bengal State Archives). Madras Presidency records actually begin much earlier, from AD 1670 (containing rich Anglo-French struggle material), and Bombay Presidency's archives are housed in the Maharashtra Secretariat Record Office, Mumbai, not in Delhi."})

qs.append({"q":"Which one of the following correctly matches a European power's Indian settlement archives with their present foreign repository location, as they were relocated at the end of colonial rule?","o":["French records of Chandernagore and Pondicherry — taken to Paris; Dutch East India Company records — housed at Rijksarchief, The Hague","Portuguese records preserved in Goa — transferred entirely to Lisbon after 1961","Danish records of Tranquebar and Serampore — transferred to Copenhagen in full, with none remaining in India","Dutch records of Cochin and Malabar — transferred to the Hague, with none remaining in Indian archives"],"a":0,"e":"French Chandernagore/Pondicherry records went to Paris, and Dutch East India Company records are at Rijksarchief, The Hague — correctly matched. However, the Danish sale of Tranquebar and Serampore (1845) saw records split, with remaining Danish material (1777-1845) still housed at the Madras Record Office, and Dutch Cochin/Malabar records are similarly still held at the Madras Record Office, not entirely relocated abroad; Portuguese Goa records (1700-1900) remain in Goa, not fully shifted to Lisbon."})

qs.append({"q":"Which one of the following was the first newspaper published in India, and in what year?","o":["The Bengal Gazette or Calcutta General Advertiser, published by James Augustus Hickey in 1780","The Calcutta Gazette, published in 1784","The Bombay Herald, published in 1789","A newspaper by William Bolts, published in 1776"],"a":0,"e":"James Augustus Hickey published The Bengal Gazette (or Calcutta General Advertiser) in 1780 — the first newspaper in India; his press was seized within two years for criticising government officials. William Bolts had earlier (1776) only ANNOUNCED an intention to publish a newspaper after resigning from the Company, but his plan was blocked before materialising, so no Bolts newspaper was actually published."})

qs.append({"q":"Consider the following pairs of nationalist/revolutionary newspapers published from abroad and their base cities:\n1. Indian Sociologist (Shyamji Krishnavarma) — London\n2. Bande Matram (Madam Cama) — Paris\n3. Talwar (Virendranath Chattopadhyay) — Berlin\n4. Ghadar (Lala Hardayal) — San Francisco\nHow many of the above pairs are correctly matched?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four pairs are correctly matched — these newspapers, published by Indian revolutionaries living abroad, were aimed at infusing nationalist sentiment among overseas Indians: Indian Sociologist from London, Bande Matram from Paris, Talwar from Berlin, and Ghadar from San Francisco."})

qs.append({"q":"Which one of the following journalists is INCORRECTLY paired with the newspaper they edited/founded?","o":["Dadabhai Naoroji — Kesari and Mahratta","Bal Gangadhar Tilak — Kesari and Mahratta","Surendranath Banerjea — Bengalee","Gopal Krishna Gokhale — Sudharak"],"a":0,"e":"Kesari and Mahratta were edited by Bal Gangadhar Tilak, not Dadabhai Naoroji — Naoroji's paper was actually the Voice of India. Surendranath Banerjea (Bengalee) and Gopal Krishna Gokhale (Sudharak) are correctly paired."})

qs.append({"q":"Bankim Chandra Chatterji's novel 'Anandamath' (1882), noted for its powerful lyric 'Vande Mataram', is centred on the depiction of which one of the following historical events?","o":["The Sanyasi Revolt of the 1760s","The Revolt of 1857","The Santhal Rebellion of 1855-56","The Indigo Revolt of 1859-60"],"a":0,"e":"Anandamath (1882) depicts the Sanyasi Revolt of the 1760s — a period of ascetic/monastic uprisings in Bengal — and remains famous chiefly for popularising the song 'Vande Mataram', later a key anthem of the nationalist movement."})

qs.append({"q":"With reference to 'Company Paintings' (also known as 'Patna Kalam'), which one of the following statements is correct?","o":["They emerged under the patronage of the East India Company and remained popular through the 19th century until the introduction of photography in India in the 1840s","They depicted exclusively religious and mythological themes, avoiding any depiction of everyday life, trade or festivals","They were produced only after the introduction of photography in India, as a reaction against the new medium","They originated in Calcutta and were unrelated to any European patronage"],"a":0,"e":"Company Paintings (Patna Kalam) developed under East India Company patronage and depicted everyday scenes — trades, festivals, dances, and attire — remaining popular through the 19th century until photography's introduction in India in the 1840s gradually supplanted them."})

qs.append({"q":"Which one of the following pairs of a painting/artwork and its historical association is correctly matched?","o":["'Relief of Lucknow' (Thomas Jones Barker, 1859) — commemorates British actions during the Revolt of 1857","'In Memoriam' (Joseph Noel Paton) — depicts the coronation of Queen Victoria as Empress of India","Kalighat painting — exclusively depicted British colonial administrators and had no social commentary","The Bengal School — was founded to promote purely European academic realism in Indian art"],"a":0,"e":"'Relief of Lucknow' (1859) by Thomas Jones Barker commemorates British actions during the suppression of the 1857 Revolt. 'In Memoriam' actually depicts anguished British women and children during the revolt (not any coronation); Kalighat painting depicted ordinary people's everyday lives and satirised social evils, not exclusively British administrators; and the Bengal School (led by Abanindranath Tagore, with E.B. Havell and A.K. Coomaraswamy) emerged as a NATIONALIST reaction drawing on Indian mythology and cultural heritage, not to promote European academic realism."})

qs.append({"q":"Consider the following statements about 'oral evidence' as a source for the history of Modern India:\n1. Oral history involves constructing history using non-written sources such as personal reminiscences.\n2. Oral sources allow historians to broaden the boundaries of their discipline and can help corroborate findings from other historical sources.\n3. All professional historians consider oral history to be as reliable and verifiable as official archival records.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct. Statement 3 is incorrect — the text explicitly notes that many historians remain SCEPTICAL of the veracity of oral history, meaning it is not universally regarded as being on par with official archival records in terms of reliability."})

qs.append({"q":"Which one of the following statements about foreign repositories of source material on Modern Indian history is correct?","o":["The India Office Records in London hold the minutes and correspondence of the Board of Control/Commissioners for the Affairs of India, along with records of the Secretary of State and the India Council","The India Office Records are located in Paris, not London","The Archives Nationale in Paris holds records exclusively related to Portuguese colonial possessions in India","The West Pakistan Record Office (Lahore) and Peshawar records hold no information relevant to India's regional or frontier history"],"a":0,"e":"The India Office Records (London) hold Board of Control/Commissioners correspondence, Secretary of State records, and India Council papers. They are located in LONDON, not Paris. The Archives Nationale, Paris holds French (not Portuguese) colonial records, and the West Pakistan Record Office (Lahore)/Peshawar records ARE valuable for regional history and India's frontier relations with Afghanistan and Iran."})

qs.append({"q":"Which one of the following genres of source material is most associated with providing 'interesting as well as useful glimpses' into 18th and early 19th century Indian history, but is generally regarded as less definitively authoritative than official archival records?","o":["Memoirs, biographies and travel accounts of contemporary and semi-contemporary writers","The parliamentary papers of the British Government","The judicial records of the Mayor's Courts","The records of the Survey of India"],"a":0,"e":"Memoirs, biographies and travel accounts (by figures like Bishop Heber, Abbe Dubois, and various British and non-British travellers) are described as giving useful glimpses into the period but are supplementary in nature, unlike official archival material such as parliamentary papers, judicial records, or Survey of India records, which carry more direct administrative authority."})

qs.append({"q":"Nearly one-third of the founding members of the Indian National Congress (1885) shared which one of the following professional backgrounds, reflecting the close link between the press and early nationalist politics?","o":["Journalism","Legal practice as barristers only","Military service","Medicine"],"a":0,"e":"The text specifically notes that nearly one-third of the founding fathers of the Indian National Congress in 1885 were journalists, underscoring the deep connection between the vernacular and English-language press and the early nationalist movement — several of whom also edited influential newspapers of the era."})

qs.append({"q":"Which one of the following statements correctly describes the significance of 'private archives' as a source for Modern Indian history?","o":["They comprise papers and documents of individuals and families of note, including nationalist leaders' papers and Indian National Congress records housed at the Nehru Memorial Museum and Library","They are limited exclusively to business records of banks and chambers of commerce, with no political content","They are housed only in foreign repositories, not within India","They were destroyed systematically after 1947 and are no longer available to researchers"],"a":0,"e":"Private archives include both political papers (nationalist leaders' records and INC papers, housed at the Nehru Memorial Museum and Library, New Delhi) and economic material (bank/business house/chamber of commerce archives) — they are available within India, not solely abroad, and were not systematically destroyed post-1947."})

# ==================================================================
# ASSEMBLY & VALIDATION (structural only)
# ==================================================================

texts = [q["q"] for q in qs]
print("Total:", len(qs), "| unique:", len(set(texts)))
for q in qs:
    assert len(q["o"]) == 4, ("option count", q["q"], len(q["o"]))
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == len(q["o"]), ("duplicate option text!", q["q"])

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch1_sources.json", "w") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print("Saved.")
