import json

qs = []

qs.append({"q":"At the Calcutta Congress session (December 1928), the Nehru Report's dominion status goal was accepted, but the Congress issued a one-year ultimatum after which, if unmet, it would:","o":["Demand complete independence and launch a civil disobedience movement","Immediately merge with the Muslim League","Dissolve itself as an organisation","Accept permanent dyarchy"],"a":0,"e":"The Calcutta session gave the government a one-year deadline (reduced from an initially proposed two years) to accept dominion status, failing which the Congress would demand complete independence and launch civil disobedience."})

qs.append({"q":"Lord Irwin's declaration of October 31, 1929 stated that it was implicit in the Declaration of 1917 that India's constitutional progress would culminate in:","o":["Dominion status, though with no specified timeframe","Immediate complete independence","Permanent dyarchy","A unitary British administration"],"a":0,"e":"Irwin's declaration reaffirmed dominion status as India's eventual constitutional destination but specified no timeline, disappointing nationalists who sought concrete commitments."})

qs.append({"q":"The Delhi Manifesto (November 2, 1929), issued by prominent national leaders, set which condition regarding the proposed Round Table Conference?","o":["That the conference should formulate a constitution to implement dominion status (acting as a constituent assembly) rather than debate whether dominion status should be granted","That the conference should be held in India rather than London","That the Congress should have no representation at the conference","That the conference should focus solely on economic issues"],"a":0,"e":"The Delhi Manifesto demanded the RTC function as a constituent assembly for implementing dominion status (not merely debating its merits), with Congress majority representation and a general amnesty for political prisoners."})

qs.append({"q":"Jawaharlal Nehru was elected president of the Lahore Congress session (December 1929) largely due to Gandhi's backing, despite opposition from how many of the 18 Provincial Congress Committees?","o":["15","5","10","18"],"a":0,"e":"15 out of 18 Provincial Congress Committees had opposed Nehru's candidacy, yet Gandhi's support secured his presidency, symbolising an endorsement of the rising youth movement and complete independence as the goal."})

qs.append({"q":"At the Lahore session (December 1929), the Congress adopted complete independence as its goal and fixed which date as the first Independence (Swarajya) Day?","o":["January 26, 1930","December 31, 1929","March 12, 1930","August 15, 1930"],"a":0,"e":"January 26, 1930 was designated as the first Independence Day, later commemorated as the date on which India's Constitution came into force in 1950."})

qs.append({"q":"At midnight on December 31, 1929, the newly adopted tricolour flag of freedom was hoisted on the banks of the River Ravi by:","o":["Jawaharlal Nehru","Mahatma Gandhi","Subhash Chandra Bose","Motilal Nehru"],"a":0,"e":"Jawaharlal Nehru hoisted the tricolour on the banks of the Ravi at midnight, December 31, 1929, marking the Congress's formal commitment to purna swaraj."})

qs.append({"q":"The Independence Pledge, read out across India on January 26, 1930 and drafted by Gandhi, committed people to prepare for civil disobedience primarily through:","o":["Non-payment of taxes and withdrawal of voluntary association from British government","Armed rebellion","Emigration from British India","Formation of a parallel legislature"],"a":0,"e":"The pledge committed Indians to non-cooperation and non-payment of taxes as the means to attain purna swaraj, alongside withdrawing voluntary association with British rule."})

qs.append({"q":"Among Gandhi's Eleven Demands presented to the government before launching civil disobedience, which was a specific peasant demand?","o":["Abolition of the salt tax and government salt monopoly","Reduction of rupee-sterling exchange ratio to 1s 4d","Reservation of coastal shipping for Indians","Reforms in the Criminal Investigation Department"],"a":0,"e":"Abolishing the salt tax and reducing land revenue by 50 per cent were specific peasant demands; the exchange ratio and coastal shipping reservation were bourgeois demands, while CID reform was a general demand."})

qs.append({"q":"Gandhi chose salt as the central theme of civil disobedience mainly because:","o":["It linked swaraj to a universal grievance of the rural poor without socially divisive implications, unlike a no-rent campaign","It was the most expensive commodity taxed by the British","It affected only urban populations","It had no historical significance in Indian life"],"a":0,"e":"Salt uniquely connected the abstract ideal of swaraj to a concrete, universal grievance affecting the poorest Indians, without the social divisiveness of a class-based campaign like a no-rent movement."})

qs.append({"q":"The Dandi March, beginning on March 12, 1930, covered approximately how many miles from Ahmedabad to the coastal village of Dandi?","o":["240 miles","100 miles","500 miles","50 miles"],"a":0,"e":"Gandhi and 78 followers marched approximately 240 miles from Sabarmati Ashram to Dandi, where he broke the salt law on April 6, 1930."})

qs.append({"q":"In Tamil Nadu, the salt satyagraha march from Thiruchirapalli to Vedaranniyam on the Tanjore coast was organised by:","o":["C. Rajagopalachari","K. Kelappan","P. Krishna Pillai","Gopalbandhu Chaudhuri"],"a":0,"e":"C. Rajagopalachari led the salt march in Tamil Nadu from Thiruchirapalli to Vedaranniyam in April 1930."})

qs.append({"q":"In Malabar, the salt marches were organised by K. Kelappan, while P. Krishna Pillai, who later founded the Kerala Communist movement, defended the national flag against police lathi-charge on which beach in November 1930?","o":["Calicut beach","Vedaranniyam beach","Dandi beach","Chowpatty beach"],"a":0,"e":"P. Krishna Pillai heroically defended the national flag on Calicut beach against a police lathi-charge in November 1930."})

qs.append({"q":"In the North-West Frontier Province, Khan Abdul Gaffar Khan (also called Badshah Khan or Frontier Gandhi) organised a volunteer brigade pledged to non-violence, popularly known as:","o":["Khudai Khidmatgars ('Red-Shirts')","Punjab Naujawan Bharat Sabha","Bharat Sevak Sangh","Hindustan Socialist Republican Association"],"a":0,"e":"Gaffar Khan's Khudai Khidmatgars, popularly called the 'Red-Shirts', were a non-violent volunteer brigade active in the NWFP during the Civil Disobedience Movement."})

qs.append({"q":"Which industrial town in southern Maharashtra saw the fiercest response to Gandhi's arrest, with textile workers striking and establishing a virtual parallel government before martial law was imposed?","o":["Sholapur","Nasik","Poona","Ahmedabad"],"a":0,"e":"Sholapur witnessed the most intense civil disobedience response, with workers burning liquor shops and government buildings, establishing a brief parallel administration until martial law was declared."})

qs.append({"q":"The raid on Dharasana Salt Works (May 21, 1930), which resulted in a brutal lathi-charge leaving 2 dead and 320 injured, was led by:","o":["Sarojini Naidu, Imam Sahib and Manilal (Gandhi's son)","Jawaharlal Nehru and Vallabhbhai Patel","Rajendra Prasad and C.R. Das","Subhash Bose and J.M. Sengupta"],"a":0,"e":"Sarojini Naidu, Imam Sahib and Manilal Gandhi led the raid on Dharasana Salt Works after Gandhi's own arrest, resulting in a widely reported brutal police response."})

qs.append({"q":"American journalist Web Miller's eyewitness report of the Dharasana raid, describing the satyagrahis' calm discipline despite being beaten, had which significant effect?","o":["It brought international attention and condemnation to British repression in India","It was suppressed and never published","It led to immediate British withdrawal from India","It had no impact on international opinion"],"a":0,"e":"Web Miller's widely syndicated report on the Dharasana Satyagraha drew significant international attention to British brutality, damaging Britain's global reputation."})

qs.append({"q":"In Manipur/Nagaland, the young Naga spiritual leader who raised the banner of revolt against British rule at age 13, and was later captured in October 1932, was:","o":["Rani Gaidinliu","Haipou Jadonang","Chandraprabha Saikiani","Bonga Majhi"],"a":0,"e":"Rani Gaidinliu, following her cousin Haipou Jadonang, led resistance against British rule from a young age and evaded capture until October 1932, later serving a life sentence until her release under the 1946 Interim Government."})

qs.append({"q":"Haipou Jadonang, whose reformist religious movement in Manipur turned political, was hanged by British authorities on charges of treason in:","o":["1931","1930","1932","1934"],"a":0,"e":"Haipou Jadonang was executed in 1931 for treason after his movement acquired increasingly political overtones against British rule."})

qs.append({"q":"Which of the following differences between the Civil Disobedience Movement and the Non-Cooperation Movement is correctly identified in the chapter?","o":["The Civil Disobedience Movement's stated objective was complete independence, and it involved law violation from the outset, unlike the earlier movement's focus on specific wrongs","Muslim participation was far greater in the Civil Disobedience Movement than in Non-Cooperation","Labour unrest was a major coinciding feature of the Civil Disobedience Movement, unlike Non-Cooperation","The Civil Disobedience Movement saw fewer imprisonments than Non-Cooperation"],"a":0,"e":"Unlike Non-Cooperation's focus on specific grievances (Punjab wrongs, Khilafat) and a vaguely worded swaraj, Civil Disobedience explicitly aimed at complete independence and involved direct law-breaking from the start; Muslim participation and labour unrest were actually lower, while imprisonments were about three times higher."})

qs.append({"q":"The Gandhi-Irwin Pact (Delhi Pact) was signed on:","o":["February 14, 1931","January 25, 1931","December 1929","March 1930"],"a":0,"e":"The Gandhi-Irwin Pact was signed in Delhi on February 14, 1931, following Gandhi's unconditional release on January 25, 1931."})

qs.append({"q":"Under the Gandhi-Irwin Pact, the government agreed to concessions including which of the following?\n1. Immediate release of political prisoners not convicted of violence.\n2. Right to make salt in coastal villages for personal consumption.\n3. Right to peaceful and non-aggressive picketing.\n4. Public inquiry into police excesses.\nHow many of the above were actually agreed to by the government?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 were agreed to; the government explicitly rejected Gandhi's demand for a public inquiry into police excesses, along with commutation of Bhagat Singh's death sentence."})

qs.append({"q":"Under the Gandhi-Irwin Pact, Gandhi on behalf of the Congress agreed to suspend civil disobedience and to participate in the next Round Table Conference around which three key issues?","o":["Federation, Indian responsibility, and reservations/safeguards in India's interests","Complete independence, dominion status, and separate electorates","Salt tax abolition, land revenue reduction, and prohibition","Universal franchise, linguistic provinces, and fundamental rights"],"a":0,"e":"The pact committed Congress to discuss federation, Indian responsibility (i.e., responsible government), and necessary reservations/safeguards (defence, minorities, financial credit) at the next RTC."})

qs.append({"q":"At the Karachi Congress session (March 1931), held just days after the execution of Bhagat Singh, Sukhdev and Rajguru, the Congress:","o":["Disapproved of political violence while admiring the martyrs' bravery and sacrifice, and endorsed the Gandhi-Irwin Pact","Fully endorsed revolutionary violence as a legitimate method","Rejected the Gandhi-Irwin Pact entirely","Refused to comment on the executions"],"a":0,"e":"The Karachi session struck a balanced note — disapproving political violence in principle while honouring the martyrs' sacrifice, and formally endorsed the Delhi Pact."})

qs.append({"q":"At the Karachi session, the Congress adopted two significant resolutions — on Fundamental Rights and on the National Economic Programme. Which of the following was part of the Fundamental Rights resolution?","o":["Universal adult franchise and neutrality of the state in religious matters","State ownership of key industries","Reduction in land revenue for peasants","Right to workers and peasants to form unions"],"a":0,"e":"The Fundamental Rights resolution included universal adult franchise, free speech, state neutrality in religion, and equal legal rights, among other civil liberties; the economic provisions belonged to the separate National Economic Programme resolution."})

qs.append({"q":"The Karachi Resolution's National Economic Programme included proposals such as:","o":["State ownership and control of key industries, mines and means of transport, along with a living wage and limited working hours","Complete privatisation of all industries","Abolition of trade unions","Elimination of land revenue reduction demands"],"a":0,"e":"The National Economic Programme envisioned state control of key industries and infrastructure, alongside labour protections like living wages and limited hours — marking the Congress's first detailed articulation of economic goals for the masses."})

qs.append({"q":"The First Round Table Conference (November 1930-January 1931), opened by King George V and chaired by Ramsay MacDonald, was notably NOT attended by:","o":["The Indian National Congress","The princely states","The Muslim League","The Depressed Classes representatives"],"a":0,"e":"The Congress, then engaged in Civil Disobedience, boycotted the First RTC, while princely states, the Muslim League, Depressed Classes (represented by Ambedkar), and other groups did attend."})

qs.append({"q":"Which prominent figure led the Muslim League delegation at the First Round Table Conference?","o":["Aga Khan III","Muhammad Ali Jinnah","Muhammad Shafi","Maulana Mohammad Ali Jauhar"],"a":0,"e":"Aga Khan III led the British-Indian Muslim delegation at the First Round Table Conference, though Jinnah, Muhammad Shafi and others also participated."})

qs.append({"q":"The outcome of the First Round Table Conference included general agreement that India would develop into a federation, though the conference achieved little because:","o":["The Indian National Congress, the primary nationalist voice, was absent, and civil disobedience continued in India","All parties reached full consensus immediately","The princely states refused any form of federal participation","Britain granted immediate dominion status, making further talks unnecessary"],"a":0,"e":"With the Congress boycotting the conference and civil disobedience ongoing, the British government realised any lasting constitutional settlement required Congress participation."})

qs.append({"q":"The Second Round Table Conference (September-December 1931) saw the Indian National Congress nominate which leader as its sole representative?","o":["Mahatma Gandhi","Motilal Nehru","Jawaharlal Nehru","Madan Mohan Malaviya"],"a":0,"e":"Gandhi attended as the Congress's sole official representative at the Second Round Table Conference, following the Gandhi-Irwin Pact."})

qs.append({"q":"At the Second Round Table Conference, Gandhi controversially argued that untouchables should NOT be treated as a separate minority because:","o":["He considered them to be Hindus, and thus part of the Hindu community rather than a distinct minority","He believed all minorities should be abolished entirely","He supported the Muslim League's position on separate electorates","He wanted to avoid discussing caste altogether"],"a":0,"e":"Gandhi insisted the depressed classes were Hindus and should not be granted separate electorates as a distinct minority, a position that clashed directly with Ambedkar's stance."})

qs.append({"q":"The Second Round Table Conference became deadlocked primarily over the question of:","o":["Minority representation, with Muslims, depressed classes, Christians and Anglo-Indians uniting in a 'Minorities' Pact' demanding separate electorates","The location of the next conference","The exact wording of the dominion status declaration","The role of the princely states in a future federation"],"a":0,"e":"The 'Minorities' Pact', uniting various communities behind demands for separate electorates, created an impasse Gandhi fiercely opposed, ultimately dooming the conference's progress."})

qs.append({"q":"At the conclusion of the Second RTC, Ramsay MacDonald announced, among other things, the creation of two new Muslim-majority provinces:","o":["North-West Frontier Province and Sindh","Punjab and Bengal","Assam and Bihar","Baluchistan and Kashmir"],"a":0,"e":"MacDonald announced the elevation of NWFP and Sindh to full provincial status as Muslim-majority provinces, alongside setting up expert committees and threatening a unilateral Communal Award if consensus failed."})

qs.append({"q":"The Third Round Table Conference (November-December 1932) differed from the previous two mainly in that:","o":["It was not attended by the Indian National Congress or Gandhi, and was largely ignored by most Indian leaders","It achieved full consensus on India's constitutional future","It resulted in the immediate implementation of dominion status","It was attended by all major Congress leaders"],"a":0,"e":"By the time of the Third RTC, Congress and Gandhi (then engaged in renewed civil disobedience) stayed away, and most prominent Indian leaders showed little interest, reflecting diminishing returns from the conference process."})

qs.append({"q":"The recommendations of the Third Round Table Conference were published in a White Paper in March 1933, eventually leading, via a Joint Select Committee's draft Bill, to which major legislation enacted in July 1935?","o":["The Government of India Act, 1935","The Government of India Act, 1919","The Indian Councils Act, 1909","The Rowlatt Act"],"a":0,"e":"The Third RTC's deliberations culminated in the Government of India Act, 1935, based on a Joint Select Committee's draft Bill produced in February 1935."})

qs.append({"q":"Following the failure of the Second Round Table Conference, the Congress Working Committee decided on December 29, 1931 to:","o":["Resume the civil disobedience movement","Permanently abandon civil disobedience","Merge with the Muslim League","Accept the Communal Award unconditionally"],"a":0,"e":"With the Second RTC's failure and the changed government attitude under Viceroy Willingdon, the CWC decided to resume civil disobedience in December 1931."})

qs.append({"q":"The second phase of Civil Disobedience (1932-1934) was marked by intense government repression sometimes described as a form of:","o":["'Civil Martial Law' — repressive ordinances amounting to virtual martial law under civilian control","Complete government inaction","A negotiated ceasefire with the Congress","Full restoration of civil liberties"],"a":0,"e":"The government's repressive ordinances during this phase created conditions akin to martial law, though technically administered under civilian authority — hence termed 'Civil Martial Law'."})

qs.append({"q":"In the first four months of the resumed Civil Disobedience Movement (from January 1932), approximately how many satyagrahis, mostly urban and rural poor, were jailed?","o":["About 80,000","About 8,000","About 5,00,000","About 15,000"],"a":0,"e":"Approximately 80,000 satyagrahis were jailed in just the first four months of the resumed movement, reflecting the scale of repression as well as continued popular participation."})

qs.append({"q":"Gandhi finally decided to withdraw the second phase of the Civil Disobedience Movement in:","o":["April 1934","December 1931","January 1932","1930"],"a":0,"e":"Gandhi withdrew the second phase of civil disobedience in April 1934, acknowledging that the movement could not be sustained given the lack of preparation time and popular exhaustion."})

qs.append({"q":"The Communal Award, announced by Ramsay MacDonald on August 16, 1932, was based on the findings of which committee?","o":["The Indian Franchise Committee (Lothian Committee)","The Simon Commission","The Nehru Committee","The Hunter Committee"],"a":0,"e":"The Communal Award drew on the recommendations of the Indian Franchise Committee, popularly known as the Lothian Committee."})

qs.append({"q":"Under the Communal Award, how many reserved seats were granted to the depressed classes?","o":["Seventy-eight","Fifty","One hundred","Twenty"],"a":0,"e":"The Communal Award granted 78 reserved seats to the depressed classes, alongside separate electorates for Muslims, Europeans, Sikhs, Christians, Anglo-Indians and even the Marathas in some Bombay seats."})

qs.append({"q":"Which of the following provisions were part of the Communal Award?\n1. Separate electorates for depressed classes for a period of 20 years.\n2. A 'double vote' for depressed classes — one in separate electorates and one in general electorates.\n3. Reservation of 3 per cent seats for women in all provinces except the NWFP.\n4. Complete abolition of communal seat allocation in provincial legislatures.\nHow many of the above are correctly listed as provisions of the Communal Award?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly describe the Communal Award's provisions; the award actually distributed seats on a communal basis in provincial legislatures rather than abolishing such allocation."})

qs.append({"q":"Gandhi's principal objection to the Communal Award's treatment of the depressed classes was that:","o":["Treating them as a separate political entity would undermine the campaign to abolish untouchability, keeping untouchables 'untouchable in perpetuity'","He believed the depressed classes deserved no representation at all","He supported separate electorates for all minorities except the depressed classes","He wanted the depressed classes to have fewer reserved seats"],"a":0,"e":"Gandhi feared that formalising the depressed classes as a distinct political minority via separate electorates would entrench untouchability rather than help eliminate it, undermining the deeper moral goal of its abolition."})

qs.append({"q":"To protest the Communal Award's provision for the depressed classes, Gandhi undertook an indefinite fast beginning:","o":["September 20, 1932","August 16, 1932","February 14, 1931","March 12, 1930"],"a":0,"e":"Gandhi began his indefinite fast on September 20, 1932, pressuring for a compromise on separate electorates for the depressed classes, which culminated in the Poona Pact."})

qs.append({"q":"The Poona Pact, signed by B.R. Ambedkar on behalf of the depressed classes on September 24, 1932, resulted in:","o":["Abandonment of separate electorates for depressed classes, but an increase in reserved seats from 71 to 147 in provincial legislatures","Continuation of separate electorates with fewer reserved seats","Complete removal of any reserved seats for depressed classes","Extension of separate electorates to all Hindu sub-castes"],"a":0,"e":"The Poona Pact replaced separate electorates with joint electorates while substantially increasing reserved seats for depressed classes — from 71 to 147 in provincial legislatures and 18% in the Central Legislature."})

qs.append({"q":"Which of the following is identified in the chapter as a negative long-term impact of the Poona Pact on the depressed classes?","o":["It made depressed class representatives vulnerable to being chosen as compliant 'stooges' by caste Hindu organisations under joint electorates","It granted complete political independence to the depressed classes from caste Hindu influence","It eliminated the need for any future reservation policy","It gave depressed classes a separate, sovereign political existence"],"a":0,"e":"Critics argue the joint electorate system under the Poona Pact allowed caste Hindu organisations to effectively select depressed-class representatives sympathetic to their interests, undermining genuine independent leadership for Dalits."})

qs.append({"q":"Following the Poona Pact, Gandhi launched a campaign against untouchability, establishing the All India Anti-Untouchability League in September 1932 and starting which weekly publication in January 1933?","o":["Harijan","Young India","Navjivan","Indian Opinion"],"a":0,"e":"Gandhi started the weekly Harijan in January 1933 as part of his intensified campaign against untouchability."})

qs.append({"q":"Gandhi's Harijan tour, undertaken from November 1933 to July 1934, covered approximately how many kilometres while collecting funds for the Harijan Sevak Sangh?","o":["20,000 km","5,000 km","50,000 km","1,000 km"],"a":0,"e":"Gandhi's extensive Harijan tour covered about 20,000 km, spreading his anti-untouchability message and raising funds for the Harijan Sevak Sangh."})

qs.append({"q":"Gandhi's approach to caste and untouchability differed from Ambedkar's in that Gandhi:","o":["Distinguished between abolishing untouchability and abolishing the caste system itself, whereas Ambedkar sought annihilation of the caste system entirely","Also sought complete annihilation of the caste system, agreeing fully with Ambedkar","Believed untouchability was sanctioned by scripture and should be preserved","Refused to engage with the issue of untouchability at all"],"a":0,"e":"Gandhi held that untouchability, not the caste/varna system itself, was the moral evil to be eradicated, believing varna could function without hierarchy; Ambedkar, by contrast, saw caste itself as the root problem requiring annihilation."})

qs.append({"q":"Regarding methods of political and social change, which of the following correctly distinguishes Gandhi's and Ambedkar's approaches?","o":["Gandhi relied on persuasion, morality and civil disobedience against unjust laws, while Ambedkar favoured legal and constitutional methods within the framework of law","Gandhi favoured strict legalism while Ambedkar favoured mass civil disobedience","Both leaders relied exclusively on parliamentary methods","Both leaders rejected the use of law entirely in favour of direct action"],"a":0,"e":"Gandhi's method centred on moral appeal, satyagraha and civil disobedience to unjust laws, while Ambedkar was more inclined towards working within legal and constitutional frameworks to secure rights."})

qs.append({"q":"Ambedkar denounced Gandhi's renaming of the Depressed Classes League as the 'Harijan Sevak Sangh' and subsequently left the organisation because he believed:","o":["For Gandhi, removal of untouchability was only a platform, not a sincere programme","Gandhi had fully adopted Ambedkar's programme for annihilation of caste","The new name accurately reflected genuine social transformation","The organisation had become irrelevant to Dalit concerns"],"a":0,"e":"Ambedkar was sceptical that Gandhi's 'Harijan' framing represented genuine structural change, viewing it as more symbolic gesture than substantive commitment to Dalit emancipation."})

qs.append({"q":"Regarding views on democracy and governance, which best captures the Gandhi-Ambedkar difference?","o":["Ambedkar favoured a parliamentary system and mass democracy as pressure on government, while Gandhi had limited respect for parliamentary systems, fearing mass democracy could lead to domination by leaders","Both leaders were equally enthusiastic supporters of parliamentary democracy","Gandhi favoured strong centralised parliamentary rule, while Ambedkar opposed all forms of representative government","Neither leader expressed any views on the nature of democratic governance"],"a":0,"e":"Ambedkar advocated a parliamentary system and believed mass democracy could empower the oppressed, whereas Gandhi was more sceptical of parliamentary structures, favouring decentralised self-governance and fearing leader-driven mass politics."})

qs.append({"q":"Regarding the relationship between religion and untouchability, Ambedkar's position (in his later years) differed from Gandhi's in that Ambedkar:","o":["Ultimately denounced Hinduism as unreformable and later left it, while Gandhi maintained that caste had nothing inherently to do with Hindu religious precepts","Believed Hinduism required no reform whatsoever","Agreed entirely with Gandhi that untouchability was unrelated to Hindu scripture","Refused to discuss the relationship between religion and caste at all"],"a":0,"e":"Ambedkar eventually concluded that Hinduism itself sanctioned caste and untouchability and could not be reformed from within, ultimately renouncing it, while Gandhi maintained caste was a 'perversive degeneration' separate from core religious teaching."})

qs.append({"q":"Justice Krishna Iyer's assessment of Gandhi and Ambedkar, quoted in the chapter, suggests that:","o":["Both shared a common opposition to social evil and imperial injustice, though a fundamental difference — more apparent than real — separated their approaches","The two leaders had no common ground whatsoever","Ambedkar was entirely dependent on Gandhi's guidance","Gandhi fully endorsed all of Ambedkar's constitutional proposals"],"a":0,"e":"Justice Krishna Iyer's assessment captures the nuanced relationship between the two leaders — shared moral concerns about injustice, alongside genuine but perhaps overstated ideological differences."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3
    assert len(set(q["o"])) == 4, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_civil_disobedience_rtc",
    "title": "Civil Disobedience Movement and Round Table Conferences",
    "desc": "Lahore Congress and Purna Swaraj, the Dandi March and Salt Satyagraha, its spread across India, the Gandhi-Irwin Pact, the three Round Table Conferences, the Communal Award and Poona Pact, and the Gandhi-Ambedkar ideological comparison",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch19_civil_disobedience_rtc.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
