import json

qs = []

qs.append({"q":"On what date did Clement Attlee announce the British intention of leaving the Indian subcontinent in the House of Commons?","o":["February 20, 1947","June 3, 1947","July 18, 1947","August 15, 1947"],"a":0,"e":"Attlee's statement of February 20, 1947 declared British intent to transfer power, setting a deadline and signalling the endgame of colonial rule."})

qs.append({"q":"What deadline for the transfer of power did Attlee's statement fix, even if Indian politicians had not agreed on a constitution by then?","o":["June 30, 1948","August 15, 1947","December 31, 1947","January 26, 1948"],"a":0,"e":"Attlee's statement fixed June 30, 1948 as the deadline for transfer of power, regardless of whether Indian political consensus on a constitution had been reached."})

qs.append({"q":"Which of the following was a key provision of Attlee's February 1947 statement regarding the transfer of power?","o":["Power might be transferred either to a central government or, in some areas, to existing provincial governments if the constituent assembly was not fully representative","Power would be transferred only to a single unified central government under all circumstances","The British would retain control over defence indefinitely after transfer of power","All princely states would automatically become part of British India's successor government"],"a":0,"e":"Attlee's statement allowed for a fragmented transfer of power — to a central government or to provincial governments — if Muslim-majority provinces refused to join a representative constituent assembly, hinting at partition."})

qs.append({"q":"According to Attlee's statement, what would happen to British paramountcy over the princely states upon transfer of power?","o":["British powers and obligations toward the princely states would lapse, but would not automatically transfer to any successor government in British India","Paramountcy would be automatically transferred wholesale to whichever government succeeded British India","The princely states would remain permanently under British control even after independence","Paramountcy would be transferred exclusively to the Congress-led government"],"a":0,"e":"Attlee's statement specified that British paramountcy over princely states would simply lapse with the transfer of power, without automatically passing to any successor government — leaving the states' future status open."})

qs.append({"q":"Who did Attlee's February 1947 statement announce would replace Lord Wavell as Viceroy?","o":["Lord Mountbatten","Stafford Cripps","Pethick Lawrence","A.V. Alexander"],"a":0,"e":"Attlee's statement announced that Lord Mountbatten would replace Wavell as Viceroy, tasked with overseeing the final transfer of power."})

qs.append({"q":"Why did the British government fix a specific date for withdrawal in the February 1947 statement?","o":["To shock the parties into agreement, avert the deepening constitutional crisis, and convince Indians of British sincerity, given the irreversible decline in governmental authority","Because international law required a fixed exit date for all colonial powers","Because the United Nations had imposed the deadline on Britain","Because Indian industrialists demanded a fixed date for economic planning purposes"],"a":0,"e":"The fixed deadline aimed to shock the Congress and League into agreement, defuse the escalating crisis, signal genuine British sincerity, and reflected acceptance of Wavell's assessment that governmental authority had irreversibly declined."})

qs.append({"q":"Why was the provision allowing transfer of power to more than one centre acceptable to the Congress?","o":["It meant the existing constituent assembly could proceed to frame a constitution for the areas it represented, offering a way out of the deadlock","It guaranteed the Congress control over the entire subcontinent without any partition","It ensured the immediate abolition of the Muslim League as a political entity","It required unanimous approval from all princely states before proceeding"],"a":0,"e":"Congress found the provision acceptable because it allowed the existing constituent assembly to move forward with constitution-making for its represented areas, breaking the prevailing deadlock even without League participation."})

qs.append({"q":"On March 10, 1947, Nehru suggested that if the Cabinet Mission's plan could not be carried out, the only real alternative was:","o":["The partition of Punjab and Bengal","Complete and unconditional acceptance of the League's demand for full Pakistan","Continuation of British rule indefinitely","Dissolution of the Constituent Assembly altogether"],"a":0,"e":"Nehru stated on March 10, 1947 that if the Cabinet Mission's plan could not be implemented, partitioning Punjab and Bengal was the only realistic alternative to a complete deadlock."})

qs.append({"q":"In April 1947, what message did Congress president Kripalani reportedly convey to the Viceroy regarding Pakistan?","o":["That the Congress would let the League have Pakistan, provided Bengal and Punjab were partitioned in a fair manner rather than fighting a battle over the issue","That the Congress would never under any circumstances accept the idea of Pakistan","That the Congress demanded immediate merger of the Muslim League into itself","That the Congress wanted a plebiscite held in every province of British India"],"a":0,"e":"Kripalani communicated that the Congress preferred to concede Pakistan to the League rather than fight, provided Bengal and Punjab themselves were partitioned fairly to protect non-Muslim-majority areas within them."})

qs.append({"q":"Why was Mountbatten able to act more firmly and quickly as Viceroy than his predecessors?","o":["He was informally given greater powers to decide matters on the spot and had the backing of Britain's firm decision to quit at the earliest","He had significantly less oversight from the British Parliament than any previous Viceroy","He was personally appointed by the Muslim League rather than the British Cabinet","He alone among Viceroys had prior administrative experience in India"],"a":0,"e":"Mountbatten's effectiveness stemmed from being informally granted greater on-the-spot decision-making authority and from operating under Britain's unambiguous commitment to withdraw quickly."})

qs.append({"q":"What was the 'Plan Balkan' that Mountbatten formulated between March and May 1947, before it was abandoned?","o":["A plan to transfer power to separate provinces or a confederation, with princely states free to join India, Pakistan, or remain independent","A plan to divide India into exactly two dominions with no options for individual provinces or states","A plan proposing continued British rule over a confederated India for another decade","A plan to grant complete independence only to Bengal and Punjab while retaining British control elsewhere"],"a":0,"e":"Plan Balkan envisaged transferring power to separate provinces or a pre-transfer confederation, with individual units and princely states (freed by lapsed paramountcy) able to join India, Pakistan, or remain separate — risking the country's Balkanisation."})

qs.append({"q":"Why was Plan Balkan quickly abandoned by Mountbatten?","o":["Nehru reacted violently against it","The Muslim League rejected it outright","The British Cabinet vetoed it directly","Gandhi threatened a fast unto death against it"],"a":0,"e":"Plan Balkan was abandoned after Nehru's strong negative reaction, since it risked fragmenting India into numerous small units rather than preserving maximum possible unity."})

qs.append({"q":"Whose idea was the key innovation in the Mountbatten Plan (June 3, 1947) of immediately transferring power via dominion status with a right of secession, rather than waiting for constituent assembly consensus?","o":["V.P. Menon","Stafford Cripps","Lord Wavell","Sardar Patel"],"a":0,"e":"V.P. Menon suggested the key innovation of an immediate transfer of power through dominion status (with a right of secession), avoiding the need to wait for full constitutional agreement."})

qs.append({"q":"Under the Mountbatten Plan of June 3, 1947, how were Punjab and Bengal's legislative assemblies to decide on partition?","o":["They would meet in two groups (Hindu and Muslim members) to vote, with a simple majority in either group sufficing to trigger partition of that province","A single joint vote of the entire assembly, with a two-thirds majority required","Only the Muslim League members had voting rights on the question","Decision was to be made solely by the Viceroy without any legislative vote"],"a":0,"e":"Under the plan, Punjab and Bengal assemblies met in Hindu and Muslim groups; a simple majority in either group voting for partition would trigger that province's division."})

qs.append({"q":"Under the Mountbatten Plan, what was to happen regarding NWFP and the Sylhet district of Bengal?","o":["Referendums would be held to decide their fate","They would automatically join whichever dominion the adjoining province joined","They would be granted complete independence as separate states","Their status would be decided solely by their ruling princes"],"a":0,"e":"Referendums were to be held in NWFP and the Sylhet district of Bengal to determine which dominion they would join."})

qs.append({"q":"Which of the following outcomes did the Mountbatten Plan rule out, given the Congress's acceptance of a unified (if partitioned) India?\n1. Independence for the princely states.\n2. Independence for Bengal as a separate unit.\n3. Accession of Hyderabad to Pakistan.\n4. Setting up a Boundary Commission if partition occurred.\nWhich of these were ruled OUT (i.e., NOT permitted), rather than provided for?","o":["1, 2 and 3 only","1, 2, 3 and 4","Only 4","Only 1"],"a":0,"e":"The plan ruled out independence for princely states, independence for Bengal, and Hyderabad's accession to Pakistan; a Boundary Commission, by contrast, WAS explicitly provided for if partition occurred, so statement 4 was not something ruled out."})

qs.append({"q":"Which of the following reasons explain why the Congress accepted dominion status despite it conflicting with the spirit of the 1929 Lahore Congress's complete independence resolution?\n1. It would ensure a peaceful and quick transfer of power.\n2. It allowed the Congress to assume authority quickly amid an explosive communal situation.\n3. It permitted continuity in the bureaucracy and army.\n4. It guaranteed permanent British sovereignty over India.\nHow many of the above are correctly listed as reasons?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 correctly explain Congress's pragmatic acceptance of dominion status; statement 4 is false, since dominion status was accepted as a transitional arrangement, not permanent British sovereignty."})

qs.append({"q":"On what date did the Indian Independence Act, 1947 receive royal assent, after being passed by the British Parliament on July 5, 1947?","o":["July 18, 1947","August 15, 1947","June 3, 1947","February 20, 1947"],"a":0,"e":"The Indian Independence Act was passed by Parliament on July 5, 1947 and received royal assent on July 18, 1947, to be implemented on August 15, 1947."})

qs.append({"q":"According to the Indian Independence Act, 1947, what legal framework was to govern the two new dominions during the transitional period until new constitutions were adopted?","o":["The Government of India Act, 1935","The Government of India Act, 1919","A wholly new interim constitution drafted by Mountbatten","No legal framework at all, leaving each dominion in a legal vacuum"],"a":0,"e":"The Act specified that both new dominions would be governed, for the transitional period, in accordance with the Government of India Act, 1935, until each adopted its own new constitution."})

qs.append({"q":"According to the terms of the Indian Independence Act, on which respective dates did Pakistan and India attain independence?","o":["Pakistan on August 14, 1947 and India on August 15, 1947","Both on August 15, 1947 simultaneously","India on August 14, 1947 and Pakistan on August 15, 1947","Pakistan on July 18, 1947 and India on August 15, 1947"],"a":0,"e":"Pakistan became independent on August 14, 1947, one day before India attained independence on August 15, 1947."})

qs.append({"q":"Who became the first Governor-General of Pakistan, while India instead chose to retain Lord Mountbatten in that role?","o":["Muhammad Ali Jinnah","Liaqat Ali Khan","Khwaja Nazimuddin","Iskander Mirza"],"a":0,"e":"M.A. Jinnah became the first Governor-General of Pakistan, while India requested Lord Mountbatten to continue as its Governor-General during the transitional period."})

qs.append({"q":"Which of the following contributed to the failure to prevent the Punjab massacre during the hurried partition process?\n1. Absence of transitional institutional structures to manage partition problems.\n2. Jinnah's insistence on being Pakistan's own Governor-General rather than sharing Mountbatten as a common link.\n3. Deliberate delay in publicly announcing the Radcliffe Boundary Commission award until after independence day.\n4. Complete absence of any boundary commission being constituted at all.\nHow many of the above are correctly listed as contributing factors?","o":["Only three","All four","Only two","Only one"],"a":0,"e":"Statements 1, 2 and 3 are correct contributing factors; statement 4 is false, since a Boundary Commission (under Radcliffe) was indeed constituted — its findings were merely delayed in announcement."})

qs.append({"q":"Who chaired the Boundary Commissions constituted to demarcate the borders of Punjab and Bengal after partition?","o":["Sir Cyril Radcliffe","Lord Mountbatten","V.P. Menon","Lord Wavell"],"a":0,"e":"Sir Cyril Radcliffe chaired the Boundary Commissions for Punjab and Bengal, with the award ready by August 12, 1947 but deliberately made public only after independence."})

qs.append({"q":"Why did Mountbatten decide to delay the public announcement of the Radcliffe Award, even though it was ready by August 12, 1947?","o":["So that the British could escape responsibility for the resulting communal disturbances by having it announced only after the transfer of power on August 15","Because Radcliffe himself requested additional time to revise his boundary lines","Because the Congress and League had not yet agreed to accept the award's contents","Because the princely states needed additional time to review the boundaries"],"a":0,"e":"Mountbatten deliberately delayed the Radcliffe Award's announcement until after August 15, 1947, so the British could distance themselves from responsibility for the ensuing communal violence and displacement."})

qs.append({"q":"Following the referendum process, which of the following outcomes is correctly matched?","o":["NWFP voted in favour of Pakistan (with the Provincial Congress abstaining from the referendum), while Sylhet's referendum resulted in its incorporation into East Bengal (Pakistan)","NWFP voted to join India, while Sylhet voted to remain independent","Both NWFP and Sylhet voted to join India","Both NWFP and Sylhet opted to remain outside both dominions"],"a":0,"e":"The NWFP referendum favoured Pakistan (with the Provincial Congress boycotting the vote), and the Sylhet referendum resulted in that district joining East Bengal, and hence Pakistan."})

qs.append({"q":"Who took charge of the newly created States Department in July 1947, overseeing the integration of princely states into the Indian Union?","o":["Vallabhbhai Patel","Jawaharlal Nehru","V.P. Menon","Rajendra Prasad"],"a":0,"e":"Sardar Vallabhbhai Patel took charge of the States Department in July 1947, leading the rapid political integration of princely states — considered his greatest political achievement."})

qs.append({"q":"By August 15, 1947, which three major princely states had NOT yet signed the Instrument of Accession to India?","o":["Kashmir, Hyderabad and Junagarh","Mysore, Travancore and Baroda","Gwalior, Indore and Bhopal","Jaipur, Jodhpur and Udaipur"],"a":0,"e":"Kashmir, Hyderabad and Junagarh remained holdouts as of August 15, 1947, while all other princely states had signed the Instrument of Accession by that date."})

qs.append({"q":"In the first phase of state integration, why did most princes agree relatively easily to sign the Instrument of Accession covering defence, external affairs and communication?","o":["Because they were merely 'surrendering' functions they never actually held (these had been part of British paramountcy), and their internal political structure remained unchanged","Because the Indian government offered them full sovereignty in exchange","Because the accession was purely symbolic and carried no legal effect","Because the British government directly compelled them to sign under threat of force"],"a":0,"e":"Since defence, external affairs and communication had always been part of British paramountcy (not the princes' own powers), signing away these functions cost the princes little, while their internal authority remained intact initially."})

qs.append({"q":"What was the principal incentive ('bait') offered to princes during the more difficult second phase of state integration?","o":["A generous privy purse, along with appointments as governors and rajpramukhs in free India","Permanent retention of full sovereign powers over their territories","Guaranteed seats in the Indian Parliament for life","Exemption from all future taxation"],"a":0,"e":"During the second, more complex phase of integrating states into larger administrative units, princes were incentivised chiefly through generous privy purses and appointments as governors or rajpramukhs."})

qs.append({"q":"Which new administrative units were formed by integrating smaller princely states during the second phase, according to the chapter?","o":["The Kathiawar Union, Vindhya Pradesh, Madhya Pradesh, Rajasthan and Himachal Pradesh","Only Hyderabad, Mysore and Travancore-Cochin, with no new unions formed","A single unified 'Rajputana State' encompassing all of Rajasthan and Gujarat","Assam, Bengal and Bihar merged into one composite state"],"a":0,"e":"New composite units such as the Kathiawar Union, Vindhya Pradesh, Madhya Pradesh, Rajasthan and Himachal Pradesh were formed through integration of smaller princely states, while larger states like Hyderabad, Mysore and Travancore-Cochin initially retained old boundaries."})

qs.append({"q":"Where did Nehru preside over sessions of the All India States People's Conference, warning that states refusing to join the Constituent Assembly would be treated as hostile?","o":["Udaipur (1945) and Gwalior (April 1947)","Haripura (1938) and Tripuri (1939)","Lahore (1929) and Karachi (1931)","Lucknow (1916) and Nagpur (1920)"],"a":0,"e":"Nehru presided over the States People's Conference sessions at Udaipur (1945) and Gwalior (April 1947), warning that states refusing to join the Constituent Assembly would be regarded as hostile."})

qs.append({"q":"According to the chapter, which of the following best explains the deeper reason why the Congress ultimately accepted partition?","o":["The Congress had succeeded in building national consciousness to pressure Britain to leave, but had failed in its parallel task of fully integrating Muslims into a unified national identity","The Congress fully supported partition from the very beginning of the freedom struggle as an ideological goal","Partition was solely the result of British military coercion against Congress wishes","The Congress accepted partition purely due to Gandhi's personal insistence, against the wishes of all other leaders"],"a":0,"e":"The chapter frames partition as reflecting a 'success-failure dichotomy': the Congress succeeded in building enough national consciousness to force British withdrawal, but failed to complete the parallel task of integrating Muslims fully into the nation."})

qs.append({"q":"Which of the following is cited as a step-by-step concession by the Congress that eventually led to partition?\n1. Acceptance of Muslim-majority provinces' autonomy during the Cripps Mission (1942).\n2. Gandhi's acceptance of self-determination for Muslim-majority provinces in the 1944 Gandhi-Jinnah talks.\n3. Acceptance, without demur, that Cabinet Mission grouping was compulsory (December 1946).\n4. Official CWC reference to partitioning Punjab (and by implication Bengal) if the country was divided, in March 1947.\nHow many of the above are correctly listed as such concessions?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four are cited as sequential Congress concessions — from accepting Muslim-majority provincial autonomy, through Gandhi-Jinnah talks, compulsory grouping, to the explicit CWC statement on partitioning Punjab and Bengal."})

qs.append({"q":"According to the chapter, in what way did Nehru display 'wishful thinking' regarding partition, underestimating the nature of 1940s communalism?","o":["He believed Hindu-Muslim differences would be patched up once the British left, that partition was only temporary, and that it would be peaceful once Pakistan was conceded","He predicted correctly and accurately that partition would cause massive, prolonged violence","He insisted from the outset that partition was permanent and irreversible","He believed communalism in the 1940s was identical in nature to that of the 1920s"],"a":0,"e":"Nehru repeatedly expressed optimistic but ultimately mistaken views — that post-British Hindu-Muslim unity would return, that partition was temporary, and that conceding Pakistan would ensure peace — underestimating the assertive, all-out nature of 1940s communalism."})

qs.append({"q":"Why did Gandhi feel a sense of helplessness regarding the acceptance of partition?","o":["He believed the people themselves had become communalised, making it impossible to sustain a movement against communalism, though he urged Congressmen not to accept partition 'in their hearts'","He believed partition was entirely his own idea and felt guilty for proposing it","He had no opinion on partition and remained indifferent throughout the process","He believed partition was the best possible outcome and celebrated its acceptance"],"a":0,"e":"Gandhi felt helpless because the communalisation of the masses left no base for an anti-communal movement; he reluctantly accepted the political reality of partition while urging Congressmen to reject it in spirit."})

qs.append({"q":"According to historian R.C. Mazumdar's assessment (as cited in the chapter), what combination of factors is credited with bringing freedom to India, beyond the Civil Disobedience Movement alone?","o":["The cumulative effect of Gandhi's campaigns, the INA's efforts under Bose, and the indirect pressure exerted by Hitler and Japan against Britain during the two World Wars","Exclusively the Civil Disobedience Movement, with no role for any other factor","Only the direct diplomatic intervention of the United States and Soviet Union","Solely the economic collapse of British India with no political factors involved"],"a":0,"e":"Mazumdar argued that no single method (Gandhi's non-violence, Bose's INA, or wartime pressure from the Axis powers) alone secured independence, but their cumulative effect — especially the INA trials' impact on army loyalty — was decisive."})

qs.append({"q":"According to the chapter, which factor made it clear to the exhausted British that they could no longer rely on the loyalty of Indian soldiers for maintaining authority?","o":["The revelations made during the INA trials and the popular reaction they produced across India","The outcome of the 1937 provincial elections","The failure of the Cripps Mission in 1942","The passage of the Government of India Act, 1935"],"a":0,"e":"The INA trials' revelations and the massive, unifying public reaction they triggered convinced the war-exhausted British that Indian soldiers' loyalty could no longer be assumed, significantly influencing the final decision to quit India."})

qs.append({"q":"Which princely state's potential accession to Pakistan was explicitly ruled out under the Mountbatten Plan, with Mountbatten himself supporting the Congress's position on this matter?","o":["Hyderabad","Kashmir","Junagarh","Travancore"],"a":0,"e":"The Mountbatten Plan ruled out Hyderabad's accession to Pakistan, with Mountbatten backing the Congress position that Hyderabad, being geographically within India, could not accede to Pakistan."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert isinstance(q["a"], int) and 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, q["q"]
    assert len(q["e"]) > 0, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_independence_partition",
    "title": "Independence with Partition",
    "desc": "Attlee's February 1947 statement, Mountbatten as Viceroy, Plan Balkan, the June 3 Mountbatten Plan, the Indian Independence Act 1947, the Radcliffe Boundary Award, integration of princely states under Patel, and the historiographical debate on why partition became inevitable",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch25_independence_partition.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
