import json

qs = []

qs.append({"q":"According to the chapter, the last two years of British rule witnessed two basic strands of national upsurge. Which of the following correctly describes them?","o":["Tortuous negotiations among government, Congress and League culminating in freedom and partition; and sporadic, militant mass action by workers, peasants and states' peoples","Purely peaceful negotiations with no mass action whatsoever","A single unified armed rebellion led jointly by the Congress and the League","Complete absence of any negotiations, with only violent mass uprisings"],"a":0,"e":"The chapter identifies two strands: prolonged tripartite negotiations ending in freedom and partition amid communal violence, and a parallel wave of localised militant mass action by workers, peasants and states' peoples."})

qs.append({"q":"Which of the following episodes are cited as part of the countrywide strike wave and militant mass action in 1945-46?\n1. The INA Release Movement and RIN revolt.\n2. The Tebhaga movement and Worli revolt.\n3. The Punnapra-Vayalar episode in Travancore.\n4. The Telangana peasant revolt.\nHow many of the above are correctly listed?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four — the INA Release Movement, RIN revolt, Tebhaga, Worli revolt, Punnapra-Vayalar, and Telangana — are cited as part of this wave of militant mass action."})

qs.append({"q":"Who became British Prime Minister in July 1945 after the Labour Party's election victory, and who was appointed Secretary of State for India?","o":["Clement Attlee as Prime Minister and Pethick Lawrence as Secretary of State","Winston Churchill as Prime Minister and Stafford Cripps as Secretary of State","Clement Attlee as Prime Minister and A.V. Alexander as Secretary of State","Lord Wavell as Prime Minister and Pethick Lawrence as Secretary of State"],"a":0,"e":"Clement Attlee became Prime Minister after Labour's 1945 victory, with Pethick Lawrence as the new Secretary of State for India."})

qs.append({"q":"Which of the following factors contributed to the British government's changed attitude towards India after 1945?\n1. The UK's decline as a global power while the USA and USSR emerged as superpowers favouring Indian freedom.\n2. Britain's war-weariness and shattered economy, including a debt of £1.2 billion owed to India.\n3. An anti-imperialist wave in South-East Asia resisting the restoration of French and Dutch colonial rule.\n4. Fear of a renewed and more dangerous version of the 1942 revolt, potentially joined by disaffected army and police.\nHow many of the above are correctly listed as reasons?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors — global power shifts, Britain's economic exhaustion and war debt, Asian anti-imperialism, and fears of a repeat 1942-style revolt with military disaffection — are cited."})

qs.append({"q":"What was the most significant feature of the Congress's 1945-46 election campaign strategy?","o":["It sought to mobilise Indians against the British rather than merely appealing for votes, glorifying Quit India martyrs and condemning repressive officials","It focused exclusively on economic promises to voters with no reference to nationalism","It avoided any mention of the 1942 movement to prevent provoking the government","It was conducted entirely in cooperation with the Muslim League"],"a":0,"e":"The campaign's central feature was mobilising anti-British sentiment by glorifying Quit India martyrs, setting up memorials, collecting relief funds, and condemning officials responsible for 1942 repression — rather than simple vote-seeking."})

qs.append({"q":"Regarding the INA trials, which of the following is correct?","o":["The first trial, held at the Red Fort in Delhi in November 1945, controversially placed a Hindu (Sehgal), a Muslim (Shah Nawaz Khan) and a Sikh (Dhillon) together in the dock","The trials were held in strict secrecy with no public knowledge of the accused","Only Muslim INA officers were put on trial by the British","The trials were held in Singapore rather than in India"],"a":0,"e":"The first INA trial at the Red Fort (November 1945) placed together Prem Kumar Sehgal (Hindu), Shah Nawaz Khan (Muslim) and Gurbaksh Singh Dhillon (Sikh) — a move that inadvertently united communities in the INA's defence."})

qs.append({"q":"Which of the following prominent lawyers organised the legal defence of INA prisoners in court?","o":["Bhulabhai Desai, Tej Bahadur Sapru, Kailash Nath Katju, Jawaharlal Nehru and Asaf Ali","Only Jawaharlal Nehru, acting alone as defence counsel","M.A. Jinnah and Liaqat Ali Khan exclusively","C. Rajagopalachari and Vallabhbhai Patel exclusively"],"a":0,"e":"Bhulabhai Desai, Tej Bahadur Sapru, Kailash Nath Katju, Jawaharlal Nehru and Asaf Ali together organised the legal defence of the INA prisoners."})

qs.append({"q":"Which of the following groups extended support to the INA cause, apart from the Congress?","o":["The Muslim League, Communist Party, Unionists, Akalis, Justice Party, RSS, Hindu Mahasabha and the Sikh League","Only the Congress supported the INA cause; all other parties opposed it","Solely the Communist Party, with all other groups remaining neutral","The British government itself formally endorsed the INA cause"],"a":0,"e":"A remarkably broad coalition — including the Muslim League, Communist Party, Unionists, Akalis, Justice Party, RSS, Hindu Mahasabha and Sikh League — supported the INA cause in varying degrees, reflecting the issue's unifying, anti-British character."})

qs.append({"q":"Which of the following correctly lists the three major upsurges of the winter of 1945-46?","o":["Calcutta (Nov 21, 1945) over INA trials; Calcutta (Feb 11, 1946) over Rashid Ali's sentence; Bombay RIN ratings' strike (Feb 18, 1946)","Bombay riots (1946), Noakhali riots (1946), and Bihar riots (1946)","The Tebhaga movement, the Telangana revolt, and the Worli revolt","The Quit India Movement, the Individual Satyagraha, and the Civil Disobedience Movement"],"a":0,"e":"The three major upsurges were the Calcutta unrest over INA trials (Nov 21, 1945), the Calcutta protest over Rashid Ali's sentence (Feb 11, 1946), and the RIN ratings' strike in Bombay (Feb 18, 1946)."})

qs.append({"q":"The Royal Indian Navy (RIN) ratings' strike of February 1946 was triggered by grievances including which of the following?\n1. Racial discrimination and demand for equal pay with white soldiers.\n2. Poor food and abusive treatment by superior officers.\n3. Arrest of a rating for writing 'Quit India' on HMIS Talwar.\n4. Demand for withdrawal of Indian troops from Indonesia.\nHow many of the above are correctly listed as grievances?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four grievances — racial pay discrimination, poor conditions, the Talwar arrest, and opposition to Indian troops being used in Indonesia — fuelled the RIN ratings' revolt."})

qs.append({"q":"Which two leaders persuaded the RIN ratings to surrender on February 23, 1946, with an assurance against victimisation?","o":["Sardar Patel and Muhammad Ali Jinnah","Jawaharlal Nehru and Liaqat Ali Khan","Mahatma Gandhi and Lord Wavell","C. Rajagopalachari and Baldev Singh"],"a":0,"e":"Patel and Jinnah jointly persuaded the RIN ratings to surrender on February 23, 1946, promising that national parties would prevent victimisation of the participants."})

qs.append({"q":"According to the chapter's evaluation, what was a key limitation of the three 1945-46 upsurges despite their significance?","o":["They were short-lived, confined to a few urban centres, and the communal unity displayed was more organisational (Muslims consulting the League, others the Congress) than a genuine unity among the people","They failed to attract any participation from the armed forces at all","They had no impact whatsoever on British policy or concessions","They were entirely orchestrated and directed by the Congress leadership from the start"],"a":0,"e":"Despite their militancy, the upsurges were short-lived and urban-confined; the apparent communal unity was more organisational than a deep popular unity, since Muslim ratings sought League guidance while others turned to Congress or Socialists."})

qs.append({"q":"What was Gandhi's opinion on the RIN mutiny of February 1946?","o":["He felt the mutiny was badly advised — wrong if aimed at fighting for freedom without guidance, and wrong if it was over grievances since the ratings should have waited for leaders' guidance","He fully endorsed and praised the mutiny as the ideal method of struggle","He called for the ratings to be given full political power immediately","He was indifferent and made no comment on the mutiny"],"a":0,"e":"Gandhi considered the mutiny 'badly advised', arguing it was wrong on both counts — as an attempt at freedom without proper guidance, or as a grievance-based protest that should have awaited leadership direction."})

qs.append({"q":"In the 1945-46 elections, which of the following describes the Congress's performance?","o":["It won 91% of non-Muslim votes, captured 57 of 102 Central Assembly seats, and secured majorities in most provinces except Bengal, Sindh and Punjab","It won a majority of Muslim votes across all provinces","It lost every provincial election held during this period","It captured all 102 seats in the Central Assembly"],"a":0,"e":"The Congress won 91% of non-Muslim votes, 57 of 102 Central Assembly seats, and majorities in most provinces (including NWFP and Assam, both claimed for Pakistan), but not in Bengal, Sindh or Punjab."})

qs.append({"q":"In the same elections, which of the following describes the Muslim League's performance?","o":["It won 86.6% of Muslim votes, captured all 30 reserved Central Assembly seats, and won majorities in Bengal and Sindh, firmly establishing itself as the dominant Muslim party unlike in 1937","It won only a small minority of Muslim votes and failed to establish itself as representative of Muslims","It won a majority in Punjab outright without any coalition","It performed identically to its poor 1937 showing"],"a":0,"e":"Unlike its poor 1937 showing, the League won 86.6% of Muslim votes, all 30 reserved Central Assembly seats, and majorities in Bengal and Sindh, establishing clear dominance among Muslim voters."})

qs.append({"q":"In Punjab, following the 1945-46 elections, which coalition assumed power under Khizr Hayat Khan?","o":["A Unionist-Congress-Akali coalition","A Muslim League-Congress coalition","A purely Muslim League government","A Unionist-League coalition"],"a":0,"e":"A Unionist-Congress-Akali coalition under Khizr Hayat Khan formed the government in Punjab, denying the Muslim League power in the province despite its communal appeal elsewhere."})

qs.append({"q":"Why did the 1945-46 elections show strong communal voting patterns despite the anti-British unity displayed in the mass upsurges of the same period?","o":["Due to separate electorates and a highly limited franchise (under 10% for provinces, under 1% for the Central Assembly)","Because voting was entirely voluntary and open to all adults regardless of religion","Because the Congress and League contested on a joint platform","Because the British banned all communal parties from contesting"],"a":0,"e":"Separate electorates and a highly restricted franchise (under 10% of the population for provincial elections, under 1% for the Centre) meant elections reflected narrower, more communally-organised voting than the broader anti-British street unity."})

qs.append({"q":"The Cabinet Mission of 1946 comprised which three members of the British Cabinet?","o":["Pethick Lawrence (chairman), Stafford Cripps, and A.V. Alexander","Clement Attlee, Winston Churchill, and Lord Wavell","Pethick Lawrence, Lord Linlithgow, and Lord Mountbatten","Stafford Cripps, Lord Wavell, and Muhammad Ali Jinnah"],"a":0,"e":"The Cabinet Mission consisted of Pethick Lawrence (Secretary of State for India and chairman), Stafford Cripps (President of the Board of Trade), and A.V. Alexander (First Lord of Admiralty)."})

qs.append({"q":"Why did British withdrawal seem imminent by 1946, according to the chapter's analysis?\n1. Nationalist forces had succeeded decisively in the struggle for political hegemony.\n2. There was demoralisation among the bureaucracy and loyalist sections after years of war and repression.\n3. The British strategy combining conciliation and repression had reached its internal limits.\n4. An entirely official (non-representative) rule had become administratively impossible.\nHow many of the above are correctly listed as reasons?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four factors are cited: nationalist success, bureaucratic demoralisation, the exhausted conciliation-repression strategy, and the practical impossibility of purely official rule without adequate personnel."})

qs.append({"q":"Why did the Cabinet Mission Plan (May 1946) reject the demand for a full-fledged Pakistan?\n1. It would include large non-Muslim populations (38% in the North-West, 48% in the North-East).\n2. Communal self-determination logic would also justify carving out Hindu-majority western Bengal and Sikh/Hindu areas of Punjab.\n3. Partitioning Bengal and Punjab would disturb deep regional ties.\n4. Division of the armed forces was considered dangerous.\nHow many of the above are correctly listed as reasons for rejecting full Pakistan?","o":["All four","Only three","Only two","Only one"],"a":0,"e":"All four reasons — demographic composition, the self-determination logic cutting both ways, disruption of regional ties, and the danger of dividing the armed forces — were cited against a full Pakistan."})

qs.append({"q":"Under the Cabinet Mission Plan, how were existing provincial assemblies to be grouped into sections?","o":["Section A: Madras, Bombay, CP, UP, Bihar, Orissa; Section B: Punjab, NWFP, Sindh; Section C: Bengal and Assam","Section A: Bengal and Punjab only; Section B: all Hindu-majority provinces; Section C: princely states only","A single undivided section covering all British Indian provinces together","Sections based purely on linguistic rather than religious-demographic criteria"],"a":0,"e":"The Plan grouped Hindu-majority provinces (Madras, Bombay, CP, UP, Bihar, Orissa) into Section A, Muslim-majority Punjab, NWFP and Sindh into Section B, and Muslim-majority Bengal and Assam into Section C."})

qs.append({"q":"How many members were envisaged for the Constituent Assembly under the Cabinet Mission Plan, and how were they to be apportioned?","o":["389 members — 292 from provincial assemblies, 4 from chief commissioners' provinces, and 93 from princely states","500 members elected entirely by adult suffrage","250 members nominated solely by the British government","100 members equally divided between Congress and League"],"a":0,"e":"The Constituent Assembly was to have 389 members: 292 sent by provincial assemblies, 4 from chief commissioners' provinces, and 93 from the princely states, elected by proportional representation across General, Muslim and Sikh groups."})

qs.append({"q":"Under the Cabinet Mission Plan, which subjects would remain under the control of a common centre for India?","o":["Defence, communication and external affairs","All subjects, leaving no autonomy to provinces","Only foreign affairs, with defence left to individual provinces","Finance and commerce alone"],"a":0,"e":"The Plan envisaged a common centre controlling only defence, communication and external affairs, with provinces retaining full autonomy and residual powers otherwise — a genuinely federal structure."})

qs.append({"q":"How did the Congress and the Muslim League differ in their interpretation of the Cabinet Mission's 'grouping' clause?","o":["The Congress saw grouping as optional (making Pakistan effectively rejected), while the League insisted it was compulsory, implying Pakistan; the Mission later clarified in the League's favour","Both parties agreed grouping was entirely optional from the outset","Both parties agreed grouping was compulsory from the outset","The League saw grouping as optional while the Congress insisted it was compulsory"],"a":0,"e":"The Congress interpreted grouping as optional (undermining Pakistan's basis), the League insisted it was compulsory (implying Pakistan); the Cabinet Mission subsequently clarified that grouping was indeed meant to be compulsory, favouring the League's view."})

qs.append({"q":"What was Wavell's 'Breakdown Plan' presented to the Cabinet Mission in May 1946?","o":["A plan envisaging British withdrawal to Muslim-majority North-West and North-East provinces while handing over the rest of the country to the Congress","A plan to hold immediate general elections under adult franchise before any transfer of power","A plan to permanently retain British rule over all of India","A plan proposing complete merger of Congress and the Muslim League"],"a":0,"e":"Wavell's 'Breakdown Plan' envisaged withdrawing British forces and officials to the Muslim-majority North-West and North-East, handing over the rest to the Congress — a middle path between repression and outright scuttle, though it was superseded by the Cabinet Mission Plan."})

qs.append({"q":"On what dates did the Muslim League and the Congress respectively accept the Cabinet Mission's long-term plan?","o":["The League on June 6 and the Congress on June 24, 1946","Both accepted simultaneously on June 6, 1946","The Congress on June 6 and the League on June 24, 1946","Neither party ever formally accepted the plan"],"a":0,"e":"The Muslim League accepted the long-term Cabinet Mission Plan on June 6, 1946, followed by the Congress on June 24, 1946."})

qs.append({"q":"What triggered the Muslim League's withdrawal of its acceptance of the Cabinet Mission's long-term plan on July 29, 1946?","o":["Nehru's July 10, 1946 statement suggesting the Constituent Assembly was sovereign and that grouping might not occur since NWFP and Assam would object to joining sections B and C","The Congress's rejection of the interim government proposal","A unilateral British decision to cancel the Cabinet Mission Plan entirely","The resignation of Lord Wavell as Viceroy"],"a":0,"e":"Nehru's July 10 statement implying the Constituent Assembly's sovereignty and the likely absence of grouping (since NWFP and Assam objected) prompted the League to withdraw its acceptance and call for 'Direct Action'."})

qs.append({"q":"The Muslim League's call for 'Direct Action' to achieve Pakistan was to begin from which date?","o":["August 16, 1946","July 29, 1946","September 2, 1946","October 26, 1946"],"a":0,"e":"The Muslim League gave a call for 'Direct Action' from August 16, 1946, which was followed by communal riots on an unprecedented scale in Calcutta, Bombay, Noakhali, Bihar and Garhmukteshwar."})

qs.append({"q":"Which areas were worst affected by the communal riots that erupted from August 16, 1946?","o":["Calcutta, Bombay, Noakhali, Bihar and Garhmukteshwar (United Provinces)","Only Punjab and NWFP","Delhi and Madras exclusively","Only princely states, with British India remaining calm"],"a":0,"e":"The worst-hit areas of the post-Direct Action communal violence were Calcutta, Bombay, Noakhali, Bihar and Garhmukteshwar in the United Provinces, leaving thousands dead."})

qs.append({"q":"When was the Congress-dominated Interim Government headed by Nehru sworn in?","o":["September 2, 1946","August 16, 1946","October 26, 1946","December 9, 1946"],"a":0,"e":"Fearing renewed mass action, the Congress-dominated Interim Government under Nehru was sworn in on September 2, 1946, with Nehru maintaining opposition to compulsory grouping."})

qs.append({"q":"When did the Muslim League join the Interim Government, and under what conditions?","o":["October 26, 1946, without giving up 'direct action' and despite rejecting the Cabinet Mission's plans and insisting on compulsory grouping","September 2, 1946, alongside the Congress from the very start","It never joined the Interim Government at all","December 9, 1946, only after formally renouncing Direct Action"],"a":0,"e":"Wavell brought the League into government on October 26, 1946, even though it had not renounced Direct Action, had rejected the Cabinet Mission's plans, and still insisted on compulsory grouping."})

qs.append({"q":"In the 14-member Interim Government (September 1946-August 1947), who held the crucial Finance portfolio, and from which party?","o":["Liaquat Ali Khan of the Muslim League","Vallabhbhai Patel of the Congress","Jawaharlal Nehru of the Congress","John Mathai of the Congress"],"a":0,"e":"Liaquat Ali Khan, a Muslim League nominee, held the Finance portfolio, which the chapter notes he used to restrict and encumber the functioning of other ministries."})

qs.append({"q":"Who held the Home, Information and Broadcasting portfolio in the Interim Government?","o":["Vallabhbhai Patel","Jawaharlal Nehru","Rajendra Prasad","C. Rajagopalachari"],"a":0,"e":"Vallabhbhai Patel held Home, Information and Broadcasting in the 1946-47 Interim Government, while Nehru served as Vice President of the Executive Council handling External Affairs."})

qs.append({"q":"Why did the Muslim League boycott the first meeting of the Constituent Assembly on December 9, 1946?","o":["As part of its obstructionist approach after rejecting the Cabinet Mission's plans, seeking to use its foothold in government to continue the fight for Pakistan rather than participate in constitution-making","Because the Assembly denied Muslims any representation whatsoever","Because the Congress refused to allow League members to attend","Because the meeting was postponed indefinitely by the Viceroy"],"a":0,"e":"The League boycotted the Constituent Assembly as part of a deliberate obstructionist strategy, viewing its presence in the Interim Government as a continuation of the political struggle for Pakistan rather than genuine participation in constitution-making."})

qs.append({"q":"Who drafted the 'Objectives Resolution' passed by the Constituent Assembly at its first session in December 1946?","o":["Jawaharlal Nehru","Dr. B.R. Ambedkar","Rajendra Prasad","Maulana Abul Kalam Azad"],"a":0,"e":"Jawaharlal Nehru drafted the Objectives Resolution, outlining the ideals of an independent sovereign republic with autonomous units, minority safeguards, and social, political and economic democracy."})

qs.append({"q":"According to the chapter's framework, what are the three broad stages in the evolution of Indian communalism?","o":["Communal Nationalism, Liberal Communalism, and Extreme Communalism","Colonial Communalism, National Communalism, and Post-Colonial Communalism","Religious Communalism, Political Communalism, and Economic Communalism","Hindu Communalism, Muslim Communalism, and Sikh Communalism"],"a":0,"e":"The chapter identifies three stages: Communal Nationalism (shared secular interests assumed from shared religion), Liberal Communalism (differing secular interests between communities), and Extreme Communalism (belief that these interests are irreconcilably incompatible)."})

qs.append({"q":"Which stage of communalism holds that different religious communities' interests are not just different but fundamentally incompatible, such that the two communities cannot coexist?","o":["Extreme Communalism","Communal Nationalism","Liberal Communalism","Secular Nationalism"],"a":0,"e":"Extreme Communalism represents the most radical stage, positing that the interests of different religious communities are irreconcilably in conflict, making coexistence impossible."})

qs.append({"q":"According to the chapter, what was the social/class basis of communalism, as argued from a Left perspective?","o":["It was rooted in the rising middle classes propagating imaginary communal interests to further their own economic interests, making it 'a bourgeois question par excellence'","It arose purely and exclusively from religious doctrine with no economic basis","It was entirely a peasant-driven, grassroots phenomenon with no elite involvement","It originated solely among industrial workers competing over factory wages"],"a":0,"e":"The chapter notes the Left's view that communalism's social roots lay in the rising middle classes, who propagated communal interests to further their own economic ambitions — hence a fundamentally 'bourgeois' phenomenon."})

qs.append({"q":"Which of the following is cited as a socio-economic reason for the growth of communalism among Muslims?","o":["Muslims lagged in modern education, trade and industry, leaving educated Muslims dependent on government jobs, which reactionary landlords and loyalist leaders exploited to build communal influence","Muslims were uniformly wealthier and more educated than Hindus across all regions","There was no economic dimension whatsoever to the rise of communalism","Muslims controlled the majority of India's industrial capital"],"a":0,"e":"Muslims' relative lag in modern education and commercial/industrial participation left them dependent on government employment, a vulnerability exploited by reactionary landlords, traditional leaders, and loyalist figures like Syed Ahmed Khan to build communal influence."})

qs.append({"q":"What was the British policy of 'divide and rule' regarding Muslims after the 1870s?","o":["Reversing earlier repression, the government began courting Muslims through concessions and favours (via figures like Syed Ahmed Khan) to counter rising nationalism among the educated middle classes","The British consistently repressed Muslims throughout without any change in policy","The British granted Muslims complete political independence from British India","The British banned all Muslim political organisations after 1870"],"a":0,"e":"After the 1870s, faced with rising nationalism, the British reversed earlier repressive policies toward Muslims, instead using concessions and figures like Syed Ahmed Khan to rally Muslim loyalty against the nationalist movement."})

qs.append({"q":"How did communal historiography distort India's historical narrative, according to the chapter?","o":["It portrayed the ancient period as a purely 'Hindu' golden age and the medieval period (Turkish, Afghan, Mughal rule) as a 'Muslim' phase, exaggerating ruling-class conflicts as Hindu-Muslim conflicts","It correctly emphasised that medieval politics was based on religious rather than economic or political interests","It denied any distinction between ancient and medieval periods of Indian history","It was developed exclusively by nationalist historians with no colonial influence"],"a":0,"e":"Communal historiography (both imperialist and later some Indian chauvinist writing) falsely framed ancient India as a Hindu golden age and medieval India as a Muslim phase of decline, ignoring that medieval political conflicts were driven by economic and political, not religious, interests."})

qs.append({"q":"Which of the following are cited as socio-religious reform movements whose militant overtones contributed to communalism?","o":["The Wahabi Movement among Muslims and the Shuddhi movement among Hindus","The Brahmo Samaj and the Aligarh Movement","The Ramakrishna Mission and the Theosophical Society","The Self-Respect Movement and the Justice Party"],"a":0,"e":"The Wahabi Movement (Muslim) and Shuddhi movement (Hindu, aimed at reconversion) are cited as reform movements whose militant overtones inadvertently fed communal consciousness."})

qs.append({"q":"Which of Tilak's initiatives is cited as an example of how militant nationalism inadvertently acquired a Hindu communal tinge?","o":["The Ganapati and Shivaji festivals along with anti-cow slaughter campaigns","The launch of the Kesari newspaper","The Home Rule Movement","The formation of the Congress Socialist Party"],"a":0,"e":"Tilak's Ganapati and Shivaji festivals and anti-cow slaughter campaigns, while intended to mobilise the masses, created suspicion among Muslims and gave nationalist mobilisation a visible Hindu religious colouring."})

qs.append({"q":"According to the chapter, what unease did the Khilafat agitation (1920-22) create among some Congressmen?","o":["The fight was framed around protecting the Caliph and Islamic holy places rather than the economic and political consequences of imperialism, raising concerns about its purely nationalistic character","It was seen as entirely a secular economic agitation with no religious content","It received no Muslim participation at all","It was universally regarded as the most successful and unproblematic Congress-led campaign"],"a":0,"e":"Some Congressmen were uneasy that the Khilafat movement's core motivation — protecting the Caliph and Islamic holy sites — was religious rather than a critique of imperialism's economic and political consequences, even though it was anti-imperialist in effect."})

qs.append({"q":"Which organisation, founded in 1909 by U.N. Mukherjee and Lal Chand, opposed the Congress's attempt to unite Indians into a single nation and urged Hindus to side with the colonial government against Muslims?","o":["The Punjab Hindu Sabha","The All India Hindu Mahasabha","The Rashtriya Swayamsevak Sangh","The Arya Samaj"],"a":0,"e":"The Punjab Hindu Sabha (1909), founded by U.N. Mukherjee and Lal Chand, opposed Congress's unifying nationalism and advocated Hindu alignment with British rule against Muslims."})

qs.append({"q":"In which year was the Rashtriya Swayamsevak Sangh (RSS) established?","o":["1925","1915","1909","1937"],"a":0,"e":"The RSS was established in 1925, later becoming associated with the militant strand of Hindu communal nationalism alongside the Hindu Mahasabha."})

qs.append({"q":"Trace the evolution of the two-nation theory: in 1906, which delegation demanded separate electorates for Muslims from Viceroy Lord Minto?","o":["The Shimla Delegation, led by the Agha Khan","The Lucknow Delegation, led by Jinnah","The Simla Deputation, led by Syed Ahmed Khan","The Aligarh Delegation, led by Iqbal"],"a":0,"e":"The Shimla Delegation (1906), led by the Agha Khan, demanded separate electorates for Muslims commensurate not just with population but their 'political importance' and 'service' to the Empire; Minto assured them of favourable treatment."})

qs.append({"q":"The All India Muslim League was founded in 1906 by which group of leaders, with the initial aim of preaching loyalty to the British government?","o":["The Agha Khan, Nawab Salimullah of Dacca, Nawab Mohsin-ul-Mulk and Nawab Waqar-ul-Mulk","Muhammad Ali Jinnah, Liaqat Ali Khan and Rahmat Ali","Syed Ahmed Khan, Badruddin Tyabji and Hamid Ali Khan","Iqbal, Jinnah and the Agha Khan jointly"],"a":0,"e":"The Muslim League was founded in 1906 by the Agha Khan, Nawab Salimullah of Dacca, Nawab Mohsin-ul-Mulk and Nawab Waqar-ul-Mulk, initially aimed at preaching British loyalty and keeping Muslims away from the Congress."})

qs.append({"q":"Under which constitutional reform were separate electorates for Muslims first awarded?","o":["The Morley-Minto Reforms of 1909","The Montagu-Chelmsford Reforms of 1919","The Government of India Act, 1935","The Communal Award of 1932"],"a":0,"e":"Separate electorates for Muslims were first awarded under the Morley-Minto Reforms of 1909, a landmark step institutionalising communal representation."})

qs.append({"q":"In 1916, the Congress accepted the Muslim League's demand for separate electorates through which agreement, presenting joint demands to the government?","o":["The Lucknow Pact","The Poona Pact","The Gandhi-Irwin Pact","The Nehru Report agreement"],"a":0,"e":"The 1916 Lucknow Pact saw the Congress accept the League's demand for separate electorates, marking joint Congress-League demands but also giving the League political legitimacy as a separate entity."})

qs.append({"q":"What were Jinnah's 'Fourteen Points' (1929), presented in response to the Nehru Report?","o":["A set of demands including separate electorates and reservation for Muslims in government service and self-governing bodies","A blueprint for the immediate creation of Pakistan as a separate sovereign state","A programme for Hindu-Muslim unity based on joint electorates","A demand for complete abolition of communal representation"],"a":0,"e":"Jinnah's Fourteen Points (1929), a response to the Nehru Report, demanded separate electorates and reserved Muslim representation in government service and self-governing institutions, among other communal safeguards."})

qs.append({"q":"The idea of Muslims as a separate nation (rather than a minority) was first proposed in the early 1930s by which young Muslim intellectual, later developed further by the poet Iqbal?","o":["Rahmat Ali","Liaqat Ali Khan","Fazl-ul-Haq","Z.A. Suleri"],"a":0,"e":"Rahmat Ali first proposed the idea of Muslims as a separate nation in the early 1930s, an idea subsequently elaborated by the poet Muhammad Iqbal and later fully embraced by the League after 1937."})

qs.append({"q":"The 1932 Communal Award is significant in the evolution of the two-nation theory because it:","o":["Accepted all Muslim communal demands contained in Jinnah's Fourteen Points","Rejected all separate electorate demands from any community","Abolished separate electorates in favour of joint electorates","Merged the Muslim League into the Indian National Congress"],"a":0,"e":"The Communal Award of 1932 accepted all the Muslim communal demands contained in the Fourteen Points, further entrenching separate communal representation ahead of the 1935 Act."})

qs.append({"q":"What impossible demand did Jinnah make between 1937 and 1939 that blocked avenues for Congress-League conciliation?","o":["That the Congress declare itself a Hindu organisation and recognise the Muslim League as the sole representative of Indian Muslims","That the Congress accept dominion status as a permanent constitutional arrangement","That the British immediately grant full independence with no transitional period","That all princely states be immediately merged into British India"],"a":0,"e":"Jinnah demanded that the Congress declare itself a purely Hindu organisation and accept the League as the sole representative of Muslims — a demand the Congress, claiming to represent all communities, could not accept."})

qs.append({"q":"During the Second World War negotiations (August Offer, Cripps proposals, Shimla Conference, Cabinet Mission), what advantage did the Muslim League consistently exploit?","o":["A virtual veto given to it by the British Indian government on any political settlement","Complete financial control over the war effort","Direct control over the Indian Army's command structure","Sole representation of India at Allied war conferences"],"a":0,"e":"Throughout wartime negotiations, the British government effectively gave the League a virtual veto over political settlements, which it used consistently to press for a separate Pakistan, ultimately achieved in 1947."})

for q in qs:
    assert len(q["o"]) == 4, q["q"]
    assert isinstance(q["a"], int) and 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, q["q"]
    assert len(q["e"]) > 0, q["q"]

print(f"Total questions: {len(qs)}")

out = {
    "id": "hist_upsc_post_war_national_scenario",
    "title": "Post-War National Scenario",
    "desc": "The INA agitation and 1945-46 upsurges (RIN revolt), post-war elections, the Cabinet Mission Plan, Direct Action Day, the Interim Government, and the birth and evolution of communalism and the two-nation theory in India",
    "questions": qs
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/hist_upsc_ch24_post_war_national_scenario.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved.")
