import json

basic = []
intermediate = []
advanced = []
upsc = []

# ---------------- BASIC (18) ----------------
basic.append({"q":"Which country's Constitution was the first in the world to begin with a Preamble, a practice later followed by India?","o":["British Constitution","American Constitution","French Constitution","Irish Constitution"],"a":1,"e":"The <b>American Constitution</b> was the first to begin with a Preamble; many countries, including India, followed this practice."})

basic.append({"q":"Which eminent jurist described the Preamble to the Indian Constitution as the 'identity card of the Constitution'?","o":["M. Hidayatullah","N.A. Palkhivala","K.M. Munshi","Alladi Krishnaswami Iyer"],"a":1,"e":"<b>N.A. Palkhivala</b>, an eminent jurist and constitutional expert, called the Preamble the 'identity card of the Constitution'."})

basic.append({"q":"The Preamble to the Indian Constitution is based on which document, drafted and moved by Pandit Nehru and adopted by the Constituent Assembly?","o":["The Government of India Act, 1935","The Objectives Resolution","The Cabinet Mission Plan","The Cripps Proposals"],"a":1,"e":"The Preamble is based on the '<b>Objectives Resolution</b>', moved by Nehru on 13 December 1946 and adopted by the Constituent Assembly on 22 January 1947."})

basic.append({"q":"Which three words were added to the Preamble by the 42nd Constitutional Amendment Act, 1976?","o":["Sovereign, Democratic, Republic","Socialist, Secular and Integrity","Justice, Liberty, Equality","Fraternity, Unity and Dignity"],"a":1,"e":"The 42nd Amendment Act, 1976 added the words '<b>Socialist</b>', '<b>Secular</b>' and '<b>Integrity</b>' to the Preamble."})

basic.append({"q":"According to the Preamble, the Constitution of India derives its authority from:","o":["The British Parliament","The Constituent Assembly alone","The people of India","The Supreme Court"],"a":2,"e":"The Preamble states that the Constitution derives its authority from '<b>We, THE PEOPLE OF INDIA</b>', making the people the source of authority."})

basic.append({"q":"The Preamble specifies which date as the date of adoption of the Constitution?","o":["15 August 1947","26 January 1950","26 November 1949","9 December 1946"],"a":2,"e":"The Preamble stipulates '<b>this twenty-sixth day of November, 1949</b>' as the date the Constitution was adopted, enacted and given to the people by the Constituent Assembly."})

basic.append({"q":"How many ingredients or components does the Preamble reveal, as identified by the book?","o":["Two","Three","Four","Five"],"a":2,"e":"The Preamble reveals <b>four ingredients</b>: source of authority, nature of the Indian State, objectives of the Constitution, and the date of adoption."})

basic.append({"q":"What does the term 'sovereign' in the Preamble signify about India?","o":["India is a dependency of Britain","India is internally independent but externally controlled by the UNO","India is an independent state, free to conduct its internal and external affairs without any outside authority","India cannot cede or acquire any territory"],"a":2,"e":"'<b>Sovereign</b>' means India is neither a dependency nor a dominion of any other nation; it is a fully independent state with no higher authority above it."})

basic.append({"q":"The Indian brand of socialism, as described in the Preamble discussion, is best characterised as:","o":["Communistic socialism involving nationalisation of all production","Democratic socialism based on a mixed economy","Pure capitalism with no state role","State socialism abolishing all private property"],"a":1,"e":"India follows '<b>democratic socialism</b>', which believes in a mixed economy where public and private sectors coexist, unlike communistic/state socialism which nationalises all means of production."})

basic.append({"q":"Which Articles of the Constitution guarantee the Fundamental Right to Freedom of Religion, cited as reflecting the Preamble's secular character even before the word 'secular' was formally added?","o":["Articles 14 to 18","Articles 19 to 22","Articles 25 to 28","Articles 29 to 30"],"a":2,"e":"<b>Articles 25 to 28</b> guarantee the Fundamental Right to Freedom of Religion, which the Supreme Court in 1974 said reflected the Constitution-makers' clear intent to establish a secular state."})

basic.append({"q":"India follows which type of democracy as provided for in its Constitution?","o":["Direct democracy through referendums","Representative parliamentary democracy","Representative presidential democracy","A mixed monarchy-democracy"],"a":1,"e":"India provides for <b>representative parliamentary democracy</b>, under which the executive remains responsible to the legislature for its policies and actions."})

basic.append({"q":"Which of the following is NOT one of the four classical devices of direct democracy mentioned in relation to countries like Switzerland?","o":["Referendum","Initiative","Impeachment","Recall"],"a":2,"e":"The four devices of direct democracy are <b>Referendum, Initiative, Recall and Plebiscite</b>. Impeachment is a separate constitutional removal procedure, not a device of direct democracy."})

basic.append({"q":"The term 'republic' in the Preamble indicates that the head of the Indian State is:","o":["A hereditary monarch","An elected president for a fixed term","Appointed for life by Parliament","Selected by the Prime Minister"],"a":1,"e":"'<b>Republic</b>' means the head of state — the President — is elected (indirectly, in India's case) for a fixed term, unlike a monarchy where the position is hereditary."})

basic.append({"q":"The three forms of 'justice' mentioned in the Preamble are:","o":["Civil, criminal and constitutional","Social, economic and political","Legal, moral and religious","Individual, collective and national"],"a":1,"e":"The Preamble speaks of justice in three forms: <b>social, economic and political</b>, secured through Fundamental Rights and Directive Principles."})

basic.append({"q":"From which historical event is the ideal of 'justice — social, economic and political' in the Preamble said to be drawn?","o":["The French Revolution (1789)","The American War of Independence","The Russian Revolution (1917)","The English Glorious Revolution (1688)"],"a":2,"e":"The ideal of justice — social, economic and political — has been taken from the <b>Russian Revolution (1917)</b>."})

basic.append({"q":"From which historical event are the ideals of liberty, equality and fraternity in the Preamble said to be drawn?","o":["The French Revolution (1789-1799)","The Russian Revolution (1917)","The American Revolution (1776)","The Industrial Revolution"],"a":0,"e":"The ideals of liberty, equality and fraternity in the Preamble have been taken from the <b>French Revolution (1789-1799)</b>."})

basic.append({"q":"Which single constitutional feature is highlighted as promoting the feeling of 'fraternity' among Indian citizens?","o":["Federal division of powers","Single citizenship","Bicameral legislature","Independent judiciary"],"a":1,"e":"The Constitution promotes fraternity through the system of <b>single citizenship</b>, alongside the Fundamental Duty to promote harmony and common brotherhood."})

basic.append({"q":"According to the Preamble, fraternity has to assure which two things?","o":["Economic growth and political stability","The dignity of the individual and the unity and integrity of the nation","Religious harmony and cultural diversity","Federal balance and judicial independence"],"a":1,"e":"The Preamble declares that fraternity must assure '<b>the dignity of the individual and the unity and integrity of the Nation</b>'."})

# ---------------- INTERMEDIATE (18) ----------------
intermediate.append({"q":"Consider the following statements about the Preamble's key words:\n1. The word 'integrity' was added by the 42nd Constitutional Amendment Act, 1976.\n2. Before 1976, the Constitution had no socialist content at all in any form.\n3. The Preamble's positive concept of secularism means all religions have equal status and equal support from the state.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — even before the word 'socialist' was inserted in 1976, the Constitution already had implicit socialist content through several Directive Principles of State Policy. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements regarding the Objectives Resolution:\n1. It was moved by Pandit Nehru in the Constituent Assembly on 13 December 1946.\n2. It was adopted by the Constituent Assembly on 22 January 1947.\n3. It later formed the basis of the Preamble to the Constitution.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements are correct — this is exactly the sequence and role of the Objectives Resolution as described in the book."})

intermediate.append({"q":"With reference to India's sovereignty, consider the following statements:\n1. India's continued membership of the Commonwealth of Nations after 1949 in no way limits its sovereignty.\n2. India's membership of the United Nations Organisation constitutes a limitation on its sovereignty.\n3. Being sovereign, India can acquire foreign territory or cede part of its own territory to a foreign state.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the book explicitly states that India's UNO membership does <b>not</b> constitute any limitation on its sovereignty. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about socialism as reflected in the Indian Constitution:\n1. The Congress party had adopted a resolution for a 'socialistic pattern of society' at its Avadi session as early as 1955.\n2. Indian socialism, per the Supreme Court, is described as a blend of Marxism and Gandhism leaning heavily towards Gandhian socialism.\n3. The New Economic Policy of 1991 (liberalisation, privatisation, globalisation) has strengthened the socialist credentials of the Indian State.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the 1991 New Economic Policy is said to have <b>diluted</b> (not strengthened) the socialist credentials of the Indian State. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about the secular character of the Indian State:\n1. The Supreme Court in 1974 held that though 'secular state' was not expressly mentioned before 1976, the Constitution-makers clearly intended to establish one.\n2. India's secularism is of the negative type, involving a complete wall of separation between religion and state.\n3. A secular state, unlike a theocratic state, does not declare any particular religion as the state religion.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — Indian secularism is of the <b>positive</b> type (equal respect and support to all religions), not the negative Western type of strict separation. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about democracy under the Indian Preamble:\n1. Direct democracy operates through devices such as Referendum, Initiative, Recall and Plebiscite.\n2. Indirect (representative) democracy can be of two kinds — parliamentary and presidential.\n3. India has adopted a hybrid of direct and indirect democracy for lawmaking at the Union level.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — India follows <b>representative parliamentary democracy</b> only, not a hybrid with direct democracy devices at the Union lawmaking level. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about the word 'democratic' in the Preamble:\n1. It is used in the narrow sense of political democracy alone.\n2. Dr. Ambedkar, in his concluding Constituent Assembly speech, argued that political democracy cannot last without social democracy.\n3. The Supreme Court in 1997 held that the Constitution envisions an egalitarian social order offering social, economic and political justice.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — 'democratic' is used in the <b>broader</b> sense, embracing social and economic democracy as well as political democracy. Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the term 'republic' in the Preamble:\n1. It means the head of state is always elected, directly or indirectly, for a fixed term.\n2. It implies vesting of political sovereignty in the people rather than in a single hereditary individual.\n3. It implies the existence of a privileged class from which alone the head of state can be chosen.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — a republic implies the <b>absence</b> of any privileged class, with all public offices open to every citizen without discrimination. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about equality as secured by the Preamble:\n1. It embraces three dimensions — civic, political and economic equality.\n2. Article 17, which abolishes untouchability, is cited as a provision ensuring civic equality.\n3. Article 39 under the Directive Principles secures equal pay for equal work to men and women.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct — equality under the Preamble covers civic, political and economic dimensions, with Article 17 (untouchability) supporting civic equality and Article 39 (DPSP) providing for equal pay for equal work."})

intermediate.append({"q":"Consider the following statements about the significance of the Preamble as viewed by various jurists:\n1. K.M. Munshi called it the 'horoscope of our sovereign democratic republic'.\n2. Pandit Thakur Das Bhargava called it the 'soul of the Constitution'.\n3. M. Hidayatullah compared it to the American Declaration of Independence but said it is more than a mere declaration.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements accurately attribute these descriptions of the Preamble's significance to Munshi, Bhargava and Hidayatullah respectively."})

intermediate.append({"q":"Consider the following statements about whether the Preamble is part of the Constitution:\n1. In the Berubari Union case (1960), the Supreme Court held that the Preamble is not a part of the Constitution.\n2. In the Kesavananda Bharati case (1973), the Supreme Court reversed this view and held the Preamble to be a part of the Constitution.\n3. The LIC of India case (1995) further reaffirmed the Preamble as an integral part of the Constitution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct, tracing the evolution of judicial opinion from Berubari Union (1960) through Kesavananda Bharati (1973) to LIC of India (1995), which settled that the Preamble is part of the Constitution."})

intermediate.append({"q":"Consider the following statements about the Preamble's constitutional status:\n1. It was enacted by the Constituent Assembly after the rest of the Constitution had already been enacted.\n2. It is a source of legislative power that Parliament can invoke to justify a law.\n3. It is non-justiciable, meaning its provisions cannot be directly enforced by courts.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the Preamble is <b>neither a source of legislative power nor a limitation on it</b>. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements on the amendability of the Preamble:\n1. The question of whether the Preamble can be amended arose for the first time in the Kesavananda Bharati case (1973).\n2. The Supreme Court held that the Preamble can be amended under Article 368, but not so as to alter its basic features.\n3. The Preamble has, in practice, been amended more than five times since 1950.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Preamble has been amended <b>only once</b>, by the 42nd Amendment Act, 1976. Statements 1 and 2 correctly describe the Kesavananda Bharati ruling on amendability."})

intermediate.append({"q":"Consider the following statements about the reasons the Preamble was placed at the end of the enactment process despite appearing first in the document:\n1. It ensured the Preamble was in conformity with the Constitution as finally adopted.\n2. The President of the Constituent Assembly moved a specific motion that the Preamble 'stands part of the Constitution', which was then adopted.\n3. This sequencing shows the founding fathers themselves treated the Preamble as an essential part of the Constitution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements correctly capture why the Preamble was enacted last and how this reflects the founders' own view that it forms part of the Constitution, later affirmed by the judiciary."})

intermediate.append({"q":"Consider the following statements comparing types of states based on their attitude towards religion:\n1. An atheistic state condemns all religions.\n2. A theocratic state declares one particular religion as the state religion.\n3. India, like the USA, is classified as a secular state that remains neutral towards all religions.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements correctly classify states by religious orientation — atheistic, theocratic, and secular — with India and the USA both cited as examples of secular states."})

intermediate.append({"q":"Consider the following statements regarding the phrase 'unity and integrity of the nation' in the Preamble:\n1. Article 1 describes India as a 'Union of States' partly to make clear that states have no right to secede.\n2. This phrase embraces only the territorial dimension of national integration, not the psychological dimension.\n3. Hindrances to national integration mentioned in this context include communalism, regionalism, casteism and linguism.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the phrase embraces <b>both</b> the psychological and territorial dimensions of national integration. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about fraternity and the Fundamental Duties:\n1. Article 51-A makes it a duty of every citizen to promote harmony and common brotherhood transcending religious, linguistic, regional or sectional diversities.\n2. Article 51-A also makes it a duty to renounce practices derogatory to the dignity of women.\n3. Both these duties are directly enforceable in a court of law like Fundamental Rights.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Fundamental Duties under Article 51-A, like the Directive Principles, are <b>non-justiciable</b> and not directly enforceable by courts. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements regarding scholarly tributes to the Preamble:\n1. Sir Ernest Barker, an English political scientist, called the Preamble the 'key-note' to the Constitution.\n2. Sir Alladi Krishnaswami Iyer said the Preamble expresses what the makers 'had thought or dreamt so long'.\n3. Both Barker and Iyer were members of the Indian Constituent Assembly.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Sir Ernest Barker was <b>not</b> a member of the Constituent Assembly; he was an English political scientist commenting from outside. Alladi Krishnaswami Iyer, however, was indeed a Constituent Assembly member. Statements 1 and 2 are correct."})

# ---------------- ADVANCED (18) ----------------
advanced.append({"q":"Who moved the Objectives Resolution in the Constituent Assembly, on which the Preamble is based, and on what date was it adopted?","o":["Dr. B.R. Ambedkar; adopted 26 November 1949","Pandit Jawaharlal Nehru; adopted 22 January 1947","Dr. Rajendra Prasad; adopted 9 December 1946","Sardar Vallabhbhai Patel; adopted 15 August 1947"],"a":1,"e":"<b>Pandit Nehru</b> moved the Objectives Resolution on 13 December 1946, and it was <b>adopted on 22 January 1947</b> by the Constituent Assembly."})

advanced.append({"q":"Which case first held that the Preamble is NOT a part of the Constitution, a position later reversed by the Supreme Court?","o":["Kesavananda Bharati vs. State of Kerala (1973)","Berubari Union case (1960)","LIC of India vs. Consumer Education and Research Centre (1995)","Minerva Mills vs. Union of India (1980)"],"a":1,"e":"In the <b>Berubari Union case (1960)</b>, the Supreme Court held the Preamble was not part of the Constitution, though it was useful for interpretation. This view was reversed in Kesavananda Bharati (1973)."})

advanced.append({"q":"In the Kesavananda Bharati case (1973), the Supreme Court held that the Preamble can be amended under Article 368, subject to which crucial limitation?","o":["It cannot be amended without a national referendum","No amendment can alter the 'basic features' of the Constitution as reflected in the Preamble","It can only be amended by a unanimous vote of both Houses of Parliament","It cannot be amended within ten years of its enactment"],"a":1,"e":"The Court held that while the Preamble can be amended, <b>no amendment may alter the basic features/elements</b> of the Constitution that the Preamble embodies."})

advanced.append({"q":"Arrange the following judicial developments regarding the Preamble in chronological order:\n1. Kesavananda Bharati case holds the Preamble is part of the Constitution and can be amended, subject to basic features.\n2. Berubari Union case holds the Preamble is not part of the Constitution.\n3. LIC of India case reaffirms the Preamble as an integral part of the Constitution.\n4. The 42nd Amendment Act adds 'Socialist', 'Secular' and 'Integrity' to the Preamble.","o":["2-1-4-3","2-4-1-3","1-2-3-4","2-1-3-4"],"a":0,"e":"Chronologically: Berubari Union (1960) → Kesavananda Bharati (1973) → 42nd Amendment (1976) → LIC of India (1995). Correct order: 2-1-4-3."})

advanced.append({"q":"Which former Chief Justice of India compared the Preamble to the American Declaration of Independence but noted it is 'more than a declaration'?","o":["M. Hidayatullah","P.B. Gajendragadkar","Alladi Krishnaswami Iyer","K.M. Munshi"],"a":0,"e":"<b>M. Hidayatullah</b>, a former Chief Justice of India, made this comparison, calling the Preamble 'the soul of our Constitution' and more than a mere declaration."})

advanced.append({"q":"Which former Chief Justice of India defined Indian secularism as: 'The State does not owe loyalty to any particular religion... it gives equal freedom to all religions'?","o":["M. Hidayatullah","P.B. Gajendragadkar","Alladi Krishnaswami Iyer","H.R. Gokhale"],"a":1,"e":"<b>P.B. Gajendragadkar</b>, a former Chief Justice of India, offered this definition of Indian secularism, distinguishing it from being irreligious or anti-religious."})

advanced.append({"q":"Which Supreme Court case is cited for the observation that 'Democratic socialism aims to end poverty, ignorance, disease and inequality of opportunity'?","o":["Nakara vs. Union of India (1982)","G.B. Pant University of Agriculture and Technology vs. State of Uttar Pradesh (2000)","Minerva Mills vs. Union of India (1980)","Berubari Union case (1960)"],"a":1,"e":"This observation is attributed to the Supreme Court in <b>G.B. Pant University of Agriculture and Technology vs. State of Uttar Pradesh (2000)</b>."})

advanced.append({"q":"Which Supreme Court case describes Indian socialism as 'a blend of Marxism and Gandhism, leaning heavily towards Gandhian socialism'?","o":["Nakara vs. Union of India (1982)","Kesavananda Bharati vs. State of Kerala (1973)","LIC of India vs. Consumer Education and Research Centre (1995)","Berubari Union case (1960)"],"a":0,"e":"This characterisation of Indian socialism comes from <b>Nakara vs. Union of India (1982)</b>."})

advanced.append({"q":"Consider the following statements about India's political status before becoming a republic:\n1. Until 15 August 1947, India was a dependency (colony) of the British Empire.\n2. From 15 August 1947 to 26 January 1950, India's status was that of a dominion within the British Commonwealth.\n3. Pakistan remained a British Dominion even after India became a republic in 1950, continuing so until 1956.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements are historically accurate as recorded in the book — covering India's transition from colony to dominion to sovereign republic, and Pakistan's continued dominion status until 1956."})

advanced.append({"q":"Who, among members of the Drafting Committee, explained that the phrase 'dignity of the individual' in the Preamble signifies that the Constitution recognises every individual's personality as sacred?","o":["Dr. B.R. Ambedkar","K.M. Munshi","Alladi Krishnaswami Iyer","N. Gopalaswamy Ayyangar"],"a":1,"e":"<b>K.M. Munshi</b>, a member of the Drafting Committee, explained the significance of 'dignity of the individual' in the Preamble in this way."})

advanced.append({"q":"Assertion (A): The Preamble was placed at the end of the constitution-making process, even though it appears first in the document.\nReason (R): This sequencing ensured the Preamble conformed to the Constitution exactly as finally adopted by the Constituent Assembly.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true, and R correctly explains A — the Preamble was deliberately enacted last precisely to align it with the finally adopted text of the rest of the Constitution."})

advanced.append({"q":"Which two members of the Constituent Assembly are cited as separately praising the Preamble as, respectively, the 'horoscope' and the 'soul, key, and jewel' of the Constitution?","o":["K.M. Munshi and Pandit Thakur Das Bhargava","Alladi Krishnaswami Iyer and M. Hidayatullah","Dr. B.R. Ambedkar and Dr. Rajendra Prasad","Sir Ernest Barker and P.B. Gajendragadkar"],"a":0,"e":"<b>K.M. Munshi</b> called the Preamble the 'horoscope of our sovereign democratic republic', while <b>Pandit Thakur Das Bhargava</b> called it 'the soul... key... and a jewel set in the Constitution'."})

advanced.append({"q":"Consider the following statements about the Berubari Union case (1960):\n1. It arose from a Presidential Reference under Article 143 concerning implementation of the Indo-Pakistan agreement of 1958.\n2. The Supreme Court held the Preamble to be a useful key to interpreting ambiguous constitutional provisions.\n3. Despite point 2, the Court held that the Preamble is not itself a part of the Constitution.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements accurately describe the Berubari Union case — a Presidential Reference on the Indo-Pakistan border agreement, in which the Court used the Preamble as an interpretive aid while still holding it wasn't formally part of the Constitution."})

advanced.append({"q":"According to the book, why is the Preamble considered non-justiciable despite being held to be a part of the Constitution?","o":["Because it was added after 1950 by amendment","Because its provisions are not enforceable in a court of law","Because only the President can interpret it","Because it applies only to Union territories"],"a":1,"e":"The Preamble is non-justiciable because its provisions <b>cannot be directly enforced by courts</b>, even though it is now recognised as forming part of the Constitution and aids in interpretation."})

advanced.append({"q":"Which of the following statements about the Preamble's amendment history is correct?","o":["It has been amended three times, once for each new word added","It has been amended only once, by the 42nd Amendment Act, 1976, adding three words together","It cannot be amended at all under any circumstances","It was last amended by the 44th Amendment Act, 1978"],"a":1,"e":"The Preamble has been amended <b>only once</b>, by the <b>42nd Amendment Act, 1976</b>, which added the three words Socialist, Secular and Integrity together in a single amendment."})

advanced.append({"q":"Which two provisions are cited in the book as securing 'political equality' under the Preamble's equality clause?","o":["Article 14 and Article 15","Article 16 and Article 17","Article 325 (non-exclusion from electoral rolls) and Article 326 (adult suffrage)","Article 39 and Article 51-A"],"a":2,"e":"Political equality is secured through <b>Article 325</b> (no exclusion from electoral rolls on grounds of religion, race, caste or sex) and <b>Article 326</b> (elections based on adult suffrage)."})

advanced.append({"q":"The combination of social justice and economic justice, as discussed in relation to the Preamble, is together referred to as:","o":["Restorative justice","Distributive justice","Retributive justice","Procedural justice"],"a":1,"e":"The book states that a combination of social justice and economic justice is known as '<b>distributive justice</b>'."})

advanced.append({"q":"Which three types of states, classified by their attitude towards religion, are discussed in the context of explaining India's secular character?","o":["Federal, unitary and confederal states","Atheistic, theocratic and secular states","Monarchical, republican and hybrid states","Presidential, parliamentary and semi-presidential states"],"a":1,"e":"The book distinguishes <b>atheistic, theocratic and secular</b> states based on their stance towards religion, placing India (like the USA) in the secular category."})

# ---------------- UPSC TIER (20) ----------------
upsc.append({"q":"Consider the following statements regarding the Preamble to the Constitution of India:\n1. It is based on the Objectives Resolution moved by Pandit Nehru and adopted by the Constituent Assembly on 22 January 1947.\n2. It has been amended only once so far, by the 42nd Constitutional Amendment Act, 1976.\n3. The amendment of 1976 added the words 'Socialist', 'Secular' and 'Integrity'.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are accurate — this is the exact historical sequence of the Objectives Resolution's adoption and the sole 1976 amendment to the Preamble."})

upsc.append({"q":"Assertion (A): The Preamble is regarded as a part of the Constitution of India.\nReason (R): In the Kesavananda Bharati case (1973), the Supreme Court reversed its earlier view from the Berubari Union case (1960) and held that the Preamble is a part of the Constitution, though subject to the basic structure limitation on its amendment.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true and R correctly explains A — the current position that the Preamble is part of the Constitution stems directly from the Kesavananda Bharati ruling overturning Berubari Union."})

upsc.append({"q":"With reference to the doctrine evolved through Berubari Union (1960), Kesavananda Bharati (1973) and LIC of India (1995) cases, consider the following statements:\n1. Berubari Union held the Preamble is a key to the minds of the Constitution-makers but not itself a part of the Constitution.\n2. Kesavananda Bharati held the Preamble is a part of the Constitution and can be amended, but not so as to damage its basic features.\n3. LIC of India reaffirmed the Preamble as an integral part of the Constitution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements correctly trace the evolving judicial position on the Preamble's constitutional status across these three landmark cases."})

upsc.append({"q":"Consider the following statements about the term 'socialist' in the Preamble:\n1. The word was inserted by the 42nd Amendment Act, 1976.\n2. Even before 1976, the Constitution carried implicit socialist content through certain Directive Principles.\n3. Indian socialism, as interpreted by the Supreme Court, favours a mixed economy over nationalisation of all means of production.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements accurately reflect the book's treatment of 'socialist' — added in 1976, implicit earlier via DPSPs, and interpreted judicially as democratic socialism favouring a mixed economy."})

upsc.append({"q":"Assertion (A): India's continued membership of the Commonwealth of Nations after becoming a republic in 1950 does not compromise its sovereignty.\nReason (R): Membership of the Commonwealth is based on free association terminable by free will, not on binding legal commitments that subordinate a member's independence.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — as Nehru argued in the Constituent Assembly, the Commonwealth is 'an agreement by free will, to be terminated by free will', which is why it does not affect India's sovereignty."})

upsc.append({"q":"With reference to the meaning of secularism embodied in India's Preamble, consider the following statements:\n1. India follows the positive concept of secularism, giving equal respect and support to all religions.\n2. The Western/negative concept of secularism, involving complete separation of religion and state, is considered inapplicable to India's multi-religious society.\n3. A theocratic state, unlike a secular state, declares one particular religion as the state religion.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements correctly describe India's positive secularism, its contrast with Western negative secularism, and the definition of a theocratic state as used for comparison."})

upsc.append({"q":"Consider the following statements about the word 'democratic' as used in the Preamble:\n1. It is used in a broad sense covering political, social and economic democracy.\n2. Dr. Ambedkar held that political democracy cannot endure without a base of social democracy, defined by liberty, equality and fraternity working as a unified trinity.\n3. Direct democracy devices such as Referendum and Initiative are actively used for ordinary Union-level lawmaking in India.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — India follows representative parliamentary democracy at the Union level; direct-democracy devices like Referendum and Initiative are not used for Indian lawmaking (they're associated with countries like Switzerland). Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Key word in the Preamble) with List-II (Historical/ideological source or authority cited) and select the correct answer using the code below.\nList-I:\nA. Justice — social, economic and political\nB. Liberty, Equality, Fraternity\nC. Socialist\nD. Secular\nList-II:\n1. French Revolution (1789-1799)\n2. 42nd Constitutional Amendment Act, 1976 (word inserted; content earlier implicit via DPSP)\n3. Russian Revolution (1917)\n4. Articles 25-28 cited by Supreme Court (1974) as reflecting pre-existing intent, word added in 1976","o":["A-3, B-1, C-2, D-4","A-1, B-3, C-4, D-2","A-3, B-2, C-1, D-4","A-4, B-1, C-3, D-2"],"a":0,"e":"Justice draws from the Russian Revolution (1917); Liberty-Equality-Fraternity from the French Revolution (1789-1799); 'Socialist' was formally inserted in 1976 though implicit earlier; 'Secular' was similarly added in 1976 though Articles 25-28 already reflected the intent. Correct code: A-3, B-1, C-2, D-4."})

upsc.append({"q":"Consider the following statements about the significance of the word 'Republic' in the Preamble:\n1. It implies that the head of the Indian State is always elected, directly or indirectly, for a fixed term.\n2. It implies the vesting of political sovereignty in the people rather than a hereditary monarch.\n3. It implies the existence of no privileged class, with all public offices open to every citizen without discrimination.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements correctly capture the constitutional meaning of 'Republic' as elaborated in the book — elected fixed-term headship, popular sovereignty, and absence of a privileged class."})

upsc.append({"q":"Assertion (A): The Preamble, though held to be part of the Constitution, cannot be used to override the express provisions of any Article.\nReason (R): The Preamble is non-justiciable and serves only as an aid to interpretation when the language of an Article is ambiguous, and is neither a source of legislative power nor a limitation upon it.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true, and R correctly explains A — because the Preamble is non-justiciable and not a source or limitation of legislative power, it functions only as an interpretive aid rather than a provision that can override specific Articles."})

upsc.append({"q":"Consider the following statements regarding equality as guaranteed through the Preamble and related provisions:\n1. Civic equality is ensured through Articles 14 to 18 of the Fundamental Rights.\n2. Political equality is ensured through Articles 325 and 326.\n3. Economic equality in the form of equal pay for equal work is a Directive Principle under Article 39, not a justiciable Fundamental Right.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements accurately map the civic, political and economic dimensions of equality to their respective constitutional provisions as discussed in the chapter."})

upsc.append({"q":"With reference to fraternity in the Preamble, consider the following statements:\n1. It is promoted institutionally through the system of single citizenship.\n2. Article 51-A imposes a Fundamental Duty to promote harmony transcending religious, linguistic, regional or sectional diversities.\n3. Fraternity, as per the Preamble, assures both the dignity of the individual and the unity and integrity of the nation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements correctly capture how fraternity is embedded in the Constitution — through single citizenship, Fundamental Duties under Article 51-A, and the Preamble's own text linking fraternity to dignity and national unity."})

upsc.append({"q":"Consider the following statements on the phrase 'unity and integrity of the nation':\n1. Article 1 describing India as a 'Union of States' is linked to this phrase to signal that states cannot secede.\n2. This phrase covers only the territorial aspect of integration and excludes the psychological aspect.\n3. Hindrances to national integration mentioned include communalism, regionalism, casteism, linguism and secessionism.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the phrase covers <b>both</b> the psychological and territorial dimensions of national integration. Statements 1 and 3 are correct."})

upsc.append({"q":"Assertion (A): The 42nd Amendment Act, 1976 is the only amendment made to the Preamble so far.\nReason (R): The Kesavananda Bharati judgment (1973) held that the basic features embodied in the Preamble cannot be altered by a constitutional amendment, effectively barring any further substantive change.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, but R is NOT the correct explanation of A","Both A and R are true, and R is the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are factually true, but R is NOT the correct explanation of A. The Preamble having been amended only once so far is a historical/political fact, not a legal consequence of the basic structure doctrine — the doctrine restricts the *content* of amendments (basic features cannot be destroyed) but does not itself prevent further amendments to the Preamble from being attempted."})

upsc.append({"q":"Which of the following best explains why the Supreme Court in the Berubari Union case (1960) still found value in the Preamble despite holding it was not part of the Constitution?","o":["Because the Preamble alone could be enforced through writ petitions","Because the Preamble shows the general purposes behind the Constitution's provisions and helps resolve ambiguity in interpreting Articles","Because the Preamble overrides any Article that conflicts with it","Because the Preamble was drafted by the Supreme Court itself"],"a":1,"e":"Even while denying it formal 'part of the Constitution' status, the Court in Berubari Union recognised the Preamble as a key to the minds of the Constitution-makers, useful for resolving ambiguity in interpreting specific Articles."})

upsc.append({"q":"Consider the following statements regarding distinguished tributes paid to the Preamble:\n1. Sir Ernest Barker called it the 'key-note' to the Constitution and quoted it at the opening of his own book.\n2. Pandit Thakur Das Bhargava called it 'the most precious part of the Constitution... a jewel set in the Constitution'.\n3. Both of these individuals were sitting judges of the Supreme Court of India at the time of making these remarks.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":1,"e":"Statement 3 is incorrect — Sir Ernest Barker was an English political scientist (not a judge), and Pandit Thakur Das Bhargava was a Constituent Assembly member, not a sitting Supreme Court judge. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the classification of states by their relationship to religion, as used to explain India's secular character:\n1. An atheistic state condemns all religion.\n2. A theocratic state, exemplified by countries such as Pakistan and Sri Lanka in the book, declares one religion as the state religion.\n3. India and the USA are both cited as examples of secular states that remain neutral among religions.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements are correct, reflecting the book's three-way classification (atheistic, theocratic, secular) used to situate India's secular character."})

upsc.append({"q":"With reference to the four ingredients of the Preamble identified in the book, consider the following statements:\n1. It states the source of the Constitution's authority as the people of India.\n2. It declares India's nature as a sovereign, socialist, secular, democratic and republican polity.\n3. It specifies November 26, 1949 as the date of adoption but does not mention any objectives of the Constitution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the fourth ingredient does include the date of adoption, but the Preamble separately (as a third ingredient) does specify justice, liberty, equality and fraternity as the <b>objectives</b> of the Constitution. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the Preamble's ideal of 'Justice':\n1. It embraces social, economic and political forms, secured through Fundamental Rights and Directive Principles together.\n2. Economic justice focuses on eliminating glaring inequalities in wealth, income and property.\n3. Political justice implies equal political rights, equal access to political offices, and an equal voice in government for all citizens.\nHow many of the statements given above are correct?","o":["Only one","Only two","All three","None"],"a":2,"e":"All three statements correctly describe the three forms of justice — social, economic and political — as elaborated in the chapter on the Preamble."})

upsc.append({"q":"Assertion (A): Liberty as envisaged in the Preamble is not absolute but qualified.\nReason (R): The Fundamental Rights through which liberty is secured are themselves subject to reasonable restrictions laid down in the Constitution.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R correctly explains A — liberty is 'qualified' precisely because the Fundamental Rights that carry it are subject to reasonable restrictions within the Constitution, meaning liberty is not an unrestricted license."})

data = {"basic": basic, "intermediate": intermediate, "advanced": advanced, "upsc": upsc}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q),1))

chapter = {
    "id": "preamble",
    "title": "Preamble",
    "desc": "Text, ingredients, key words, significance, justiciability and amendability of the Preamble to the Constitution of India",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/polity_ch05_preamble_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
