import json

basic = []
intermediate = []
advanced = []
upsc = []

# ---------------- BASIC (18) ----------------
basic.append({"q":"Which Article of the Constitution, in Part XX, deals with Parliament's power to amend the Constitution and the procedure for doing so?","o":["Article 356","Article 360","Article 368","Article 370"],"a":2,"e":"<b>Article 368</b> in <b>Part XX</b> is the master provision on constitutional amendment. It empowers Parliament to amend by way of addition, variation or repeal, while also being subject to the judicially-created limitation that it cannot touch the Constitution's 'basic structure', as established in the Kesavananda Bharati case (1973)."})

basic.append({"q":"Is India's amendment procedure closer to Britain's flexible model or America's rigid model?","o":["Identical to Britain's fully flexible model","Identical to America's fully rigid model","Neither — it is a synthesis of both, neither too easy nor too difficult","It has no comparable model in any other country"],"a":2,"e":"India's Constitution is <b>neither flexible nor rigid but a synthesis of both</b> — some provisions can be changed by a simple parliamentary majority (like Britain's flexible model), others need a special majority, and the most fundamental federal provisions additionally need state ratification (closer to America's more rigid model), all within the same single Article 368 framework."})

basic.append({"q":"Where can a bill to amend the Constitution be introduced?","o":["Only in the Lok Sabha","Only in the Rajya Sabha","In either House of Parliament, but not in any state legislature","In any state legislature, which then forwards it to Parliament"],"a":2,"e":"A constitutional amendment bill can be introduced in <b>either House of Parliament</b> — Lok Sabha or Rajya Sabha — but state legislatures have no power to originate such a bill on their own. This is one of the criticisms levelled at the procedure, since it concentrates the power to initiate amendments entirely within Parliament."})

basic.append({"q":"Does a constitutional amendment bill require the prior permission of the President before it can be introduced in Parliament?","o":["Yes, presidential permission is mandatory before introduction","No, it can be introduced by a minister or a private member without needing prior presidential permission","Yes, but only if introduced by a private member","No, but it requires the Prime Minister's prior permission instead"],"a":1,"e":"Unlike some other categories of bills (such as Money Bills), a constitutional amendment bill <b>does not require prior presidential permission</b> and can be introduced by <b>either a minister or a private member</b>, making the point of entry into the legislative process relatively open."})

basic.append({"q":"What is the minimum majority required in each House of Parliament to pass a constitutional amendment bill under Article 368?","o":["A simple majority of members present and voting","A special majority: majority of total membership of the House, and two-thirds of members present and voting","Three-fourths of the total membership of the House","Unanimous consent of all members"],"a":1,"e":"This is called a '<b>special majority</b>' — it requires BOTH a majority of the House's total membership AND a two-thirds majority of members present and voting, a dual threshold that is harder to achieve than either requirement alone, and is the standard majority for most, though not all, categories of constitutional amendment."})

basic.append({"q":"If the Lok Sabha and Rajya Sabha disagree on a constitutional amendment bill, is there a provision for a joint sitting to resolve the deadlock?","o":["Yes, exactly as with an ordinary bill under Article 108","No, there is no provision for a joint sitting for a constitutional amendment bill","Yes, but only the Rajya Sabha can request it","No, but the President can dissolve Parliament to resolve it"],"a":1,"e":"Unlike ordinary bills (which CAN go to a joint sitting under Article 108 to resolve deadlocks), there is <b>no such joint-sitting provision</b> for constitutional amendment bills — each House must pass the bill separately, making genuine bicameral agreement essential for any amendment to succeed."})

basic.append({"q":"When must a constitutional amendment bill additionally be ratified by state legislatures?","o":["Whenever the bill seeks to amend any provision at all","Only when the bill seeks to amend provisions related to the federal structure of the Constitution","Only when the bill is introduced by a private member","Whenever the Rajya Sabha specifically requests state ratification"],"a":1,"e":"State ratification is required only for the specific, narrower category of amendments touching the <b>federal structure</b> — such as the distribution of powers, the Supreme Court/High Courts, or the President's election method — not for every amendment. This is the third and most demanding of the three amendment routes."})

basic.append({"q":"How many state legislatures must ratify a bill amending a federal provision, and by what majority?","o":["Half of the states, by a simple majority","Two-thirds of the states, by a special majority","Three-fourths of the states, by a simple majority","All states, by a special majority"],"a":0,"e":"Ratification requires <b>half of the state legislatures</b> to approve the bill by a <b>simple majority</b> — notably lower than the two-thirds requirement in Parliament itself, and far less demanding than the American system's three-fourths-of-states requirement."})

basic.append({"q":"Once a constitutional amendment bill has been duly passed by Parliament (and ratified by states where required), what happens next?","o":["It is sent to the Supreme Court for constitutional review before taking effect","It is presented to the President, who must give assent and cannot withhold it or return it for reconsideration","It requires a national referendum before becoming law","It automatically becomes law without any presidential role"],"a":1,"e":"The bill is presented to the <b>President</b>, who <b>must give assent</b> — the <b>24th Amendment Act, 1971</b> made this obligatory, removing any presidential discretion to withhold assent or send the bill back, which had been a point of ambiguity before that amendment."})

basic.append({"q":"Into how many broad categories can constitutional amendments be classified based on the majority/procedure required?","o":["Two","Three: by simple majority, by special majority, and by special majority plus state ratification","Four","Five"],"a":1,"e":"There are <b>three</b> distinct amendment routes: amendment by <b>simple majority</b> (outside Article 368's technical scope), amendment by <b>special majority</b> of Parliament, and amendment by <b>special majority plus ratification by half the states</b> — each reserved for a different category of constitutional provisions depending on how significant or federally sensitive the change is."})

basic.append({"q":"Which of the following can be amended by a simple majority of Parliament, outside the scope of Article 368?","o":["Fundamental Rights","Formation of new states and alteration of boundaries of existing states","Election of the President","Representation of states in Parliament"],"a":1,"e":"Formation of new states and alteration of state boundaries (governed by Articles 2-4) is one of about 18 categories that can be changed by a <b>simple majority</b>, treated as ordinary legislation rather than a 'constitutional amendment' for Article 368 purposes. Fundamental Rights, presidential election, and state representation all require more demanding procedures instead."})

basic.append({"q":"Which category of provisions requires amendment by the special majority of Parliament alone (without state ratification)?","o":["Fundamental Rights and Directive Principles of State Policy","Distribution of legislative powers between Union and states","Election of the President","Representation of states in Parliament"],"a":0,"e":"<b>Fundamental Rights and Directive Principles</b> fall under the 'special majority of Parliament alone' category — a middle tier that is harder to change than simple-majority provisions but doesn't require the additional step of state ratification reserved for the most federally sensitive provisions."})

basic.append({"q":"Which of the following requires amendment by special majority of Parliament PLUS ratification by half the states?","o":["Quorum in Parliament","Salaries and allowances of Members of Parliament","Distribution of legislative powers between the Union and the states","Citizenship — acquisition and termination"],"a":2,"e":"The <b>distribution of legislative powers</b> between the Union and states goes to the heart of India's federal structure, which is precisely why it requires the most demanding route — special majority in Parliament plus ratification by at least half the state legislatures. The other three options are all examples of matters amendable by simple majority instead."})

basic.append({"q":"Is there a time limit within which states must give their consent to a constitutional amendment requiring state ratification?","o":["Yes, six months","Yes, one year","No, the Constitution prescribes no such time limit","Yes, but only for amendments related to the judiciary"],"a":2,"e":"The Constitution is <b>silent on any time limit</b> for state ratification — the amendment process is treated as complete the moment half of the states give their consent, regardless of how long individual states take, and there's likewise no clarity on whether a state can withdraw consent already given, both cited as gaps in the procedure."})

basic.append({"q":"Which famous case established that Parliament's amending power under Article 368 cannot be used to alter the 'basic structure' of the Constitution?","o":["Golaknath case (1967)","Kesavananda Bharati case (1973)","Minerva Mills case (1980)","Maneka Gandhi case (1978)"],"a":1,"e":"The <b>Kesavananda Bharati case (1973)</b> established the basic structure doctrine — the single most important judicial limitation on the otherwise very broad amending power granted to Parliament under Article 368, ensuring that even a duly passed amendment cannot destroy the Constitution's foundational identity."})

basic.append({"q":"Which political scientist praised India's variety of amendment procedures, remarking 'this variety in the amending process is wise but rarely found'?","o":["A.V. Dicey","K.C. Wheare","Ivor Jennings","Granville Austin"],"a":1,"e":"<b>K.C. Wheare</b> made this specific remark admiring India's multi-tiered amendment system. He is also the scholar behind the earlier-noted observation that India's amendment procedure 'strikes a good balance between flexibility and rigidity' — a recurring theme across the chapter's discussion of the procedure's overall design philosophy."})

basic.append({"q":"Who observed in the Constituent Assembly, 'While we want this Constitution to be as solid and permanent as we can make it, there is no permanence in a Constitution... there should be a certain flexibility'?","o":["Dr. B.R. Ambedkar","Pandit Jawaharlal Nehru","Dr. Rajendra Prasad","Sardar Vallabhbhai Patel"],"a":1,"e":"<b>Pandit Nehru</b> made this remark, arguing that excessive rigidity would 'stop the nation's growth' as 'a living, vital, organic people' — a philosophical justification for building meaningful amendability into the Constitution rather than treating it as untouchable."})

basic.append({"q":"Which amendment added the provision relating to the Goods and Services Tax Council, requiring the special majority plus state-ratification procedure?","o":["97th Amendment Act, 2011","101st Amendment Act, 2016","103rd Amendment Act, 2019","44th Amendment Act, 1978"],"a":1,"e":"The <b>101st Amendment Act, 2016</b>, which introduced GST, added the GST Council provision (Article 279-A) to the list of matters requiring special majority plus state ratification — reflecting the genuinely federal, Centre-state cooperative character of India's GST framework."})

# ---------------- INTERMEDIATE (18) ----------------
intermediate.append({"q":"Consider the following statements about the initiation of constitutional amendment bills:\n1. Only Parliament can initiate an amendment bill; state legislatures have no such power.\n2. State legislatures have one narrow exception: they can pass a resolution requesting Parliament to create or abolish a legislative council in their state.\n3. Once a state passes such a resolution, Parliament is constitutionally bound to act on it within a fixed time.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — even after a state legislature passes such a resolution, <b>Parliament can approve, disapprove, or simply take no action on it at all</b>, with no obligation to act within any timeframe. Statements 1 and 2 correctly describe the very narrow, exceptional role states play in the amendment process."})

intermediate.append({"q":"Consider the following statements comparing constitutional amendment bills with ordinary bills:\n1. Both require only a simple majority to pass in each House.\n2. Both can go to a joint sitting of Parliament if there is a deadlock between the two Houses.\n3. Except for the special majority requirement, the process for passing a constitutional amendment bill largely resembles an ordinary legislative process.\nWhich of the statements given above is/are correct?","o":["3 only","1 and 2 only","1 and 3 only","2 and 3 only"],"a":0,"e":"Statements 1 and 2 are incorrect — constitutional amendment bills need a <b>special</b> (not simple) majority in most cases, and there is <b>no joint-sitting provision</b> for them (unlike ordinary bills, which can go to a joint sitting under Article 108). Only statement 3 is correct, and it's precisely this resemblance to ordinary legislative process (apart from the majority requirement) that critics have flagged as a weakness in the procedure's design."})

intermediate.append({"q":"Consider the following statements about the 24th Constitutional Amendment Act, 1971:\n1. It made it obligatory for the President to give assent to a constitutional amendment bill.\n2. It removed the President's power to withhold assent or return the bill for reconsideration.\n3. It was enacted in direct response to the Kesavananda Bharati judgment.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the 24th Amendment Act, 1971 actually <b>predates</b> Kesavananda Bharati (1973) by two years; it was Parliament's response to the earlier <b>Golaknath case (1967)</b>, reasserting Parliament's power to amend Fundamental Rights, not a reaction to Kesavananda Bharati. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about matters amendable by a simple majority of Parliament, outside Article 368's technical scope:\n1. This category includes admission or establishment of new states and citizenship-related matters.\n2. This category includes the number of puisne judges in the Supreme Court and conferring more jurisdiction on it.\n3. This category includes Fundamental Rights, since Parliament frequently needs to update them.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Fundamental Rights fall under the <b>special majority</b> category (not simple majority), reflecting their greater constitutional weight compared to matters like judicial administration details or citizenship rules. Statements 1 and 2 correctly list two of the roughly eighteen simple-majority categories."})

intermediate.append({"q":"Consider the following statements about the 'special majority' required under Article 368:\n1. It means a majority of the total membership of the House and two-thirds of members present and voting.\n2. 'Total membership' is calculated after excluding vacant seats and absent members from the count.\n3. According to Lok Sabha Rules, this special majority standard applies at all effective stages of the bill's passage, not merely at the final voting stage.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — '<b>total membership</b>' means the total number of seats in the House <b>regardless of vacancies or absentees</b>, a stricter and less forgiving baseline than counting only currently filled or attending seats. Statements 1 and 3 correctly describe the special majority's composition and its application throughout the bill's passage, not just at the final vote."})

intermediate.append({"q":"Consider the following statements about provisions requiring special majority plus state ratification:\n1. This category includes the manner of electing the President and the extent of executive power of the Union and states.\n2. This category includes any of the lists in the Seventh Schedule.\n3. This category also includes Article 368 itself — Parliament's own power to amend the Constitution and its procedure.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct — this is a deliberately self-referential design feature: Parliament cannot even change its OWN amending power and procedure (statement 3) without going through the most demanding route, ensuring the amendment mechanism itself can't be casually loosened by a simple parliamentary majority."})

intermediate.append({"q":"Consider the following statements about criticism of India's amendment procedure:\n1. Critics note the absence of a special body like a Constitutional Convention, unlike in the USA.\n2. Critics note that the Constitution requires ratification by three-fourths of state legislatures for federal provisions, mirroring the American requirement exactly.\n3. Critics note that the amendment provisions are sketchy, leaving wide scope for judicial interpretation and litigation.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — India requires ratification by only <b>half</b> of the states, which critics specifically contrast with America's stricter <b>three-fourths</b> requirement, precisely BECAUSE India's threshold is lower and thus considered comparatively easier. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about state legislatures' role in the amendment process compared to the American system:\n1. In the USA, a constitutional convention can be called on the petition of two-thirds of state legislatures.\n2. In India, no equivalent state-initiated convention mechanism exists; states can, at most, request a specific legislative council change.\n3. Despite this difference, both countries require the SAME proportion of states (half) to ratify a federal-provision amendment.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the USA requires ratification by <b>three-fourths</b> of the states for a constitutional amendment, not half; India's much lower <b>half-state</b> threshold is precisely one of the key differences the book highlights between the two systems. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about Dr. Ambedkar's assessment of India's amendment procedure in the Constituent Assembly:\n1. He noted that India, unlike Canada, did not deny the people the right to amend the Constitution at all.\n2. He noted that India, unlike America or Australia, did not make amendment subject to extraordinary terms and conditions.\n3. He concluded that the Constituent Assembly had provided for a genuinely difficult, near-impossible procedure for amending the Constitution.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and contradicts Ambedkar's actual words — he specifically said the Assembly provided for a '<b>facile</b>' (easy) procedure, the opposite of a difficult or near-impossible one. Statements 1 and 2 correctly capture his comparative points about Canada and America/Australia."})

intermediate.append({"q":"Consider the following statements about the absence of a time limit for state ratification:\n1. The Constitution does not specify a deadline by which states must ratify an amendment.\n2. The Constitution is also silent on whether a state can withdraw its ratification after giving it.\n3. Because of this silence, courts have definitively ruled that no state may ever withdraw its consent once given.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 overstates the position — the book identifies this as an unresolved <b>gap or silence</b> in the constitutional text (a criticism of the procedure), not as a matter that has been definitively and conclusively settled by judicial ruling. Statements 1 and 2 correctly identify the two related silences in the text."})

intermediate.append({"q":"Consider the following statements about the design philosophy behind India's amendment procedure, as reflected in the views of Nehru and Wheare:\n1. Nehru argued that excessive rigidity would prevent the growth of a 'living, vital, organic people'.\n2. Wheare praised the procedure for striking a good balance between flexibility and rigidity.\n3. Both scholars agreed the procedure should be made uniformly rigid across all provisions to ensure stability.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — neither Nehru nor Wheare argued for uniform rigidity; in fact, the entire point of both their observations is that the Constitution's <b>variable, multi-tiered</b> amendment scheme (simple majority for some things, special majority plus ratification for others) is precisely what allows it to balance stability with adaptability. Statements 1 and 2 are correct."})

# ---------------- ADVANCED (18) ----------------
advanced.append({"q":"Which of the following correctly identifies the constitutional consequence when an amendment bill is passed by simple majority under provisions like Articles 2-4 (formation of new states)?","o":["It is treated as a constitutional amendment under Article 368 and requires the President's mandatory assent","It is NOT deemed to be a constitutional amendment for the purposes of Article 368, even though it changes the Constitution's text","It requires ratification by all states before taking effect","It cannot be passed without a two-thirds majority in both Houses"],"a":1,"e":"This is a subtle but important technical point: provisions changeable by simple majority (like state reorganisation under Articles 2-4) are explicitly <b>NOT deemed 'amendments' for Article 368 purposes</b>, even though they do alter constitutional text — allowing Parliament to treat these as ordinary legislative matters rather than triggering the heavier special-majority/ratification machinery."})

advanced.append({"q":"Which of the following is the most accurate description of why the amendment procedure has been criticised as resembling the 'ordinary legislative process'?","o":["Because constitutional amendment bills, apart from requiring a special majority, otherwise follow essentially the same procedural steps as ordinary bills","Because constitutional amendment bills can be passed by voice vote just like ordinary bills","Because the President has identical powers over both types of bills, including a veto","Because both types of bills must be ratified by state legislatures"],"a":0,"e":"Critics note that beyond the numerical majority threshold, constitutional amendment bills are processed through Parliament much like <b>ordinary bills</b> — same reading stages, same basic passage mechanics — without a genuinely distinct, more solemn 'constituent' procedure such as a special constitutional convention, which is precisely the point of comparison critics draw with countries like the USA."})

advanced.append({"q":"Which of the following correctly explains why the absence of a joint-sitting provision for constitutional amendment bills is considered structurally significant?","o":["It means a determined Lok Sabha majority can always override Rajya Sabha objections on amendments, just as with ordinary bills","It means genuine agreement between both Houses is indispensable for any constitutional amendment to succeed, since no joint-sitting mechanism exists to break a deadlock","It means only the Rajya Sabha's approval is legally required for constitutional amendments","It means constitutional amendments can bypass Parliament entirely if the Houses disagree"],"a":1,"e":"Because Article 108's joint-sitting mechanism (used to resolve Lok Sabha-Rajya Sabha deadlocks on ordinary bills, where the larger Lok Sabha's numbers typically prevail) is <b>unavailable</b> for constitutional amendments, both Houses must separately and independently agree — making the Rajya Sabha's assent genuinely indispensable for constitutional change in a way it isn't always for ordinary legislation."})

advanced.append({"q":"Which of the following correctly identifies the significance of the phrase 'in exercise of its constituent power' in Article 368?","o":["It means Parliament acts as an ordinary legislature exercising Article 245 powers when amending the Constitution","It means Parliament, when amending the Constitution, is understood to be acting in a special, distinct capacity as a 'constituent' body rather than as an ordinary legislature","It means only a specially elected Constituent Assembly, not the regular Parliament, can amend the Constitution","It has no legal significance and is purely ceremonial language"],"a":1,"e":"The phrase signals that Parliament, when amending the Constitution, operates in a qualitatively <b>different capacity</b> — as a 'constituent' body exercising constitution-making power — distinct from its everyday role as an ordinary legislature making laws under its Article 245 powers, even though procedurally the two processes look similar (a tension critics have pointed to)."})

advanced.append({"q":"Which of the following statements about the interaction between Article 368 and the basic structure doctrine is most accurate?","o":["The basic structure doctrine is explicitly written into the text of Article 368 itself","The basic structure doctrine is a judicial gloss added by the Supreme Court in Kesavananda Bharati (1973), constraining Parliament's otherwise textually broad amending power under Article 368","The basic structure doctrine was inserted into Article 368 by the 24th Amendment Act, 1971","The basic structure doctrine applies only to amendments requiring state ratification, not to those requiring only a special majority"],"a":1,"e":"The basic structure doctrine is a <b>judicial innovation</b>, not textual language within Article 368 — the Article's own wording appears to grant a very broad power to 'amend by way of addition, variation or repeal any provision', but Kesavananda Bharati (1973) read in an implicit limitation that this power cannot be used to destroy the Constitution's foundational identity, regardless of which of the three amendment routes is used."})

advanced.append({"q":"Which of the following correctly captures Dr. Ambedkar's specific three-way international comparison of amendment difficulty in his Constituent Assembly remarks?","o":["Canada denies citizens the right to amend at all; America and Australia impose extraordinary conditions; India provides a facile procedure","Canada has the easiest procedure; America has a moderate procedure; India has the most difficult procedure","All three countries — Canada, America, and Australia — have identical amendment procedures to India's","Ambedkar did not compare India's procedure to any other country"],"a":0,"e":"Ambedkar's specific comparison was: <b>Canada</b> denied its people any right to amend the Constitution at that time; <b>America and Australia</b> made amendment subject to extraordinary, difficult conditions; while <b>India</b>, by contrast, provided a comparatively easy ('facile') procedure — positioning India as deliberately more accessible than these other federal or Commonwealth models."})

advanced.append({"q":"Which of the following correctly identifies why the Goods and Services Tax Council provision requires the special-majority-plus-ratification procedure rather than simple majority?","o":["Because it was inserted very recently, in 2016, and all recent amendments automatically require this procedure","Because it fundamentally affects Centre-state fiscal relations and cooperative federalism, a category the book groups with other 'federal structure' provisions","Because the GST Council itself formally voted to require this higher threshold","Because Article 279-A is located within Part III of the Constitution"],"a":1,"e":"The GST Council provision (Article 279-A, added by the 101st Amendment Act, 2016) was grouped with other genuinely <b>federal-structure</b> matters requiring state ratification, because GST fundamentally restructures how the Centre and states share taxation powers — fitting the same underlying rationale that governs the whole 'special majority plus ratification' category, rather than being a special one-off recent-amendment rule."})

advanced.append({"q":"Which of the following most accurately captures the criticism regarding constituent power distribution between Parliament and state legislatures in India, compared to federal norms elsewhere?","o":["Indian states have MORE constituent power than American states, since India requires only half rather than three-fourths of states to ratify amendments","Indian states have virtually no power to independently initiate constitutional amendments, and only a narrow, non-binding consultative role even in ratification-requiring cases","Indian states have exactly the same constituent power as the Union Parliament","Indian states can unilaterally amend the Constitution's federal provisions without any parliamentary involvement"],"a":1,"e":"Despite occasionally being consulted (through the ratification requirement for certain federal provisions), Indian state legislatures have essentially <b>no independent power to initiate</b> constitutional amendments (barring the one narrow legislative-council exception) — a genuinely more limited role than that of American states, even though the ratification THRESHOLD itself (half vs. three-fourths) is comparatively lower in India."})

advanced.append({"q":"Which of the following statements correctly reflects K.C. Wheare's overall assessment of the Indian amendment procedure?","o":["He criticised it as dangerously rigid, comparing it unfavourably to the British model","He praised it both for striking a good balance between flexibility and rigidity, and for its unusual variety of amendment procedures within a single constitutional framework","He argued it should be replaced entirely with the American model","He considered it identical in substance to the Australian amendment procedure"],"a":1,"e":"Wheare made two separate, positive observations quoted in the book: that the procedure '<b>strikes a good balance between flexibility and rigidity</b>', and separately that '<b>this variety in the amending process is wise but rarely found</b>' — both reflecting genuine admiration for India's multi-tiered design, not criticism."})

advanced.append({"q":"Arrange the following in the correct chronological order: (1) Kesavananda Bharati case establishing the basic structure doctrine; (2) 24th Amendment Act making presidential assent to amendment bills obligatory; (3) Golaknath case holding Fundamental Rights beyond Parliament's amending power; (4) 101st Amendment Act adding the GST Council provision.","o":["3-2-1-4","2-3-1-4","3-1-2-4","1-2-3-4"],"a":0,"e":"Chronologically: Golaknath (1967) → 24th Amendment Act (1971, responding to Golaknath) → Kesavananda Bharati (1973, establishing basic structure) → 101st Amendment Act (2016, GST). Correct order: 3-2-1-4."})

# ---------------- UPSC TIER (20) ----------------
upsc.append({"q":"Consider the following statements about the procedure under Article 368:\n1. An amendment bill can be introduced in either House of Parliament without prior presidential permission.\n2. It must be passed by each House separately, with no joint-sitting mechanism available to resolve inter-House disagreement.\n3. Following the 24th Amendment Act, 1971, the President's assent to a duly passed amendment bill is discretionary.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the 24th Amendment Act, 1971 made presidential assent <b>obligatory</b>, removing discretion, not the opposite. Statements 1 and 2 correctly describe the bill's introduction and the absence of a joint-sitting mechanism."})

upsc.append({"q":"Assertion (A): The Indian Constitution's amendment procedure is described as 'neither too rigid nor too flexible'.\nReason (R): It provides three distinct routes for amendment — simple majority, special majority, and special majority with state ratification — calibrated to the constitutional significance of the provision being changed.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both statements are true, and R directly explains A — it is precisely this three-tiered, calibrated structure that allows India's Constitution to be simultaneously adaptable (for routine matters) and stable (for foundational federal provisions), avoiding the extremes of British-style pure flexibility or American-style uniform rigidity."})

upsc.append({"q":"With reference to the three categories of constitutional amendment, consider the following statements:\n1. Formation of new states (Articles 2-4) requires only a simple majority and is not treated as an 'amendment' under Article 368.\n2. Fundamental Rights and Directive Principles require a special majority of Parliament alone.\n3. The manner of electing the President requires special majority plus ratification by half the states.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct and together illustrate the full three-tier system in action — each example is drawn directly from the book's specific lists for each of the three categories, moving from least demanding (simple majority) to most demanding (special majority plus state ratification)."})

upsc.append({"q":"Consider the following statements about criticisms of India's amendment procedure:\n1. There is no special constitutional convention or assembly analogous to the American model; the constituent power lies mainly with Parliament.\n2. State legislatures can independently initiate constitutional amendment bills on any subject, just like Parliament.\n3. The provisions relating to amendment are considered too sketchy, leaving room for extensive judicial interpretation.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — state legislatures have essentially <b>no power to independently initiate</b> constitutional amendments; their only role is passing a non-binding resolution about legislative councils, which Parliament may or may not act upon. Statements 1 and 3 correctly reflect two genuine, book-cited criticisms."})

upsc.append({"q":"Match List-I (Category of Constitutional Provision) with List-II (Amendment Procedure Required) and select the correct answer using the code below.\nList-I:\nA. Quorum in Parliament\nB. Directive Principles of State Policy\nC. Distribution of legislative powers between Union and states\nD. Delimitation of constituencies\nList-II:\n1. Special majority of Parliament plus ratification by half the states\n2. Simple majority of Parliament\n3. Special majority of Parliament alone\n4. Not amendable under any procedure","o":["A-2, B-3, C-1, D-2","A-1, B-2, C-3, D-4","A-2, B-1, C-3, D-4","A-3, B-2, C-1, D-2"],"a":0,"e":"Quorum in Parliament and delimitation of constituencies both require only simple majority; DPSP requires special majority alone; distribution of legislative powers (a core federal matter) requires special majority plus state ratification. Correct code: A-2, B-3, C-1, D-2."})

upsc.append({"q":"Consider the following statements about the 24th Amendment Act, 1971 and its historical context:\n1. It was Parliament's legislative response to the Golaknath case (1967), which had held Fundamental Rights beyond Parliament's amending power.\n2. It declared Parliament's power to amend any part of the Constitution, including Fundamental Rights, through Article 368.\n3. It made presidential assent to a constitutional amendment bill obligatory.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct — the 24th Amendment Act, 1971 addressed two distinct issues simultaneously: reasserting Parliament's amending power over Fundamental Rights (responding to Golaknath) and separately removing presidential discretion over assent to amendment bills, both significant, related-but-distinct changes made in the same amendment act."})

upsc.append({"q":"Consider the following statements comparing India's and America's amendment procedures:\n1. India requires ratification by half the states for federal provisions, while America requires three-fourths.\n2. America allows a constitutional convention to be called on the petition of two-thirds of state legislatures, a mechanism absent in India.\n3. Both countries provide identical roles for their respective national legislatures in initiating amendments.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the two systems differ meaningfully in this respect too: America allows amendments to be proposed either by Congress OR by a state-initiated constitutional convention, while India's Parliament has a near-monopoly on initiation, with states having only the narrow legislative-council exception. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the significance of Article 368 also covering its own amendment procedure:\n1. Parliament's power to amend the Constitution and the amendment procedure itself, as set out in Article 368, can only be changed via special majority plus ratification by half the states.\n2. This design prevents Parliament from unilaterally making the amendment process easier or harder for itself using only a simple or even special majority.\n3. This self-referential feature exists in every country's constitution as a universal norm.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and overgeneralises — this self-referential entrenchment (requiring the hardest procedure to change the procedure itself) is a specific design feature of India's Constitution, not something the book claims is a universal norm across all countries. Statements 1 and 2 correctly describe this design feature and its rationale."})

upsc.append({"q":"Consider the following statements on the philosophical justification for India's amendment procedure, as expressed by the Constitution's framers:\n1. Nehru argued rigidity would prevent the growth of a 'living, vital, organic people'.\n2. Ambedkar contrasted India's 'facile' procedure with Canada's denial of any amending right and America/Australia's extraordinary conditions.\n3. Both framers argued for making the Constitution completely unamendable to preserve its original vision permanently.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 directly contradicts both framers' actual, quoted positions — both explicitly argued AGAINST permanence/unamendability and FOR a workable, accessible amendment mechanism, precisely because they believed a living constitution needed room to grow and adapt. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the practical operation of the state-ratification requirement:\n1. The moment half of the states give their consent, the ratification requirement is satisfied, regardless of what the remaining states do.\n2. If a state legislature takes no action at all on the bill, this is treated as an automatic rejection, invalidating the ratification process.\n3. There is no specified time limit for states to give their consent under this procedure.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the book explicitly states that if some states 'take no action on the bill, it does not matter'; inaction is simply <b>disregarded</b>, not treated as an automatic rejection that would derail the process. Statements 1 and 3 are correct."})

upsc.append({"q":"With reference to the basic structure doctrine's relationship to Article 368, consider the following statements:\n1. It was established by judicial interpretation in Kesavananda Bharati (1973), not by the constitutional text itself.\n2. It means Parliament's amending power, though textually described as extending to 'any provision' of the Constitution, is not truly unlimited.\n3. It applies uniformly regardless of which of the three amendment procedures (simple majority, special majority, or special majority plus ratification) is used.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":3,"e":"All three statements are correct and together capture the full significance of the basic structure doctrine as an overarching, procedure-independent limitation — no matter which of the three routes Parliament uses to amend the Constitution, none of them can be used to destroy its basic structure, a limit that exists entirely outside and beyond the literal text of Article 368."})

data = {"basic": basic, "intermediate": intermediate, "advanced": advanced, "upsc": upsc}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q),1))

chapter = {
    "id": "amendment_of_constitution",
    "title": "Amendment of the Constitution",
    "desc": "Article 368: procedure, the three types of amendment (simple majority, special majority, special majority plus state ratification), criticism of the procedure, and framers' views on flexibility versus rigidity",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/polity_ch11_amendment_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
