import json

basic = []
intermediate = []
advanced = []
upsc = []

# ---------------- BASIC ----------------
basic.append({"q":"Are Cabinet Committees mentioned in the Constitution of India?","o":["No, they are extra-constitutional, though the Rules of Business provide for their establishment","Yes, they are explicitly detailed under Article 74","Yes, they are explicitly detailed under Article 352","No, and no rule or law anywhere provides for their establishment"],"a":0,"e":"Cabinet Committees are <b>extra-constitutional in emergence</b> — not mentioned anywhere in the Constitution's text — but the <b>Rules of Business</b> do provide for their establishment, giving them a degree of official procedural recognition despite lacking direct constitutional status."})

basic.append({"q":"What are the two types of Cabinet Committees based on their duration?","o":["Standing (permanent) and ad hoc (temporary)","Senior and junior","Political and economic","Central and state-level"],"a":0,"e":"Cabinet Committees are either <b>standing</b> (permanent in nature) or <b>ad hoc</b> (temporary, constituted to deal with special problems and disbanded once their task is complete) — for example, the Emergency Committee set up in 1962 after the Chinese invasion was an ad hoc committee."})

basic.append({"q":"Who sets up Cabinet Committees, and does their number and composition stay fixed over time?","o":["The Prime Minister sets them up, and their number, nomenclature and composition vary according to the exigencies of the time","Parliament sets them up through a fixed statutory law, with unchanging composition","The President sets them up, with composition fixed permanently by the Constitution","The Cabinet Secretary sets them up independently of the Prime Minister"],"a":0,"e":"The <b>Prime Minister</b> sets up Cabinet Committees according to the exigencies of the time and requirements of the situation — which is precisely why their number, nomenclature, and composition VARY from time to time rather than remaining fixed."})

basic.append({"q":"Who usually heads Cabinet Committees, and what happens when the Prime Minister is a member of one?","o":["Mostly the Prime Minister; if the PM is a member of a committee, he/she invariably presides over it","Always a senior Cabinet Minister other than the Prime Minister","The Cabinet Secretary in all cases","A rotating chairmanship among all cabinet ministers"],"a":0,"e":"Cabinet Committees are <b>mostly headed by the Prime Minister</b>, though other senior Cabinet Ministers sometimes act as chairman. Whenever the PM IS a member of a particular committee, he/she invariably presides over it — the PM's presence automatically confers chairmanship."})

basic.append({"q":"Besides sorting out issues and formulating proposals for the Cabinet, what other significant power do Cabinet Committees have?","o":["They can also take actual decisions, though the Cabinet can review such decisions","They can only make non-binding suggestions with no decision-making power at all","They can override the Cabinet's own decisions permanently","They can dissolve the Cabinet itself if they disagree with it"],"a":0,"e":"Cabinet Committees can <b>take actual decisions</b>, not merely prepare proposals — though these decisions remain subject to REVIEW by the full Cabinet, preserving the Cabinet's ultimate authority even while delegating substantial decision-making power downward."})

basic.append({"q":"What is the primary organisational purpose served by Cabinet Committees?","o":["Reducing the Cabinet's enormous workload through division of labour and effective delegation","Replacing the Cabinet entirely as the highest decision-making body","Providing a check on the Prime Minister's constitutional powers","Serving purely ceremonial functions with no real administrative purpose"],"a":0,"e":"Cabinet Committees exist as an <b>organisational device to reduce the Cabinet's enormous workload</b>, facilitating in-depth examination of policy issues and effective coordination — built on the core administrative principles of division of labour and delegation."})

basic.append({"q":"Which Cabinet Committee decides all higher-level appointments in the Central Secretariat, Public Enterprises, Banks and Financial Institutions?","o":["Appointments Committee of the Cabinet","Cabinet Committee on Economic Affairs","Cabinet Committee on Political Affairs","Cabinet Committee on Parliamentary Affairs"],"a":0,"e":"The <b>Appointments Committee of the Cabinet</b> handles this specific function — a crucial gatekeeping role over senior appointments across multiple important institutions of the Central government and public sector."})

basic.append({"q":"Which Cabinet Committee deals with all issues relating to defence, law and order, internal security, and atomic energy?","o":["Cabinet Committee on Security","Cabinet Committee on Political Affairs","Cabinet Committee on Accommodation","Cabinet Committee on Investment and Growth"],"a":0,"e":"The <b>Cabinet Committee on Security</b> covers this critical cluster of national security-related matters — defence, law and order, internal security, and atomic energy — reflecting the interconnected nature of these security domains."})

basic.append({"q":"Which Cabinet Committee is often described as a 'Super-Cabinet' and considered the most powerful among all Cabinet Committees?","o":["Cabinet Committee on Political Affairs","Cabinet Committee on Economic Affairs","Appointments Committee of the Cabinet","Cabinet Committee on Security"],"a":0,"e":"The <b>Cabinet Committee on Political Affairs</b>, which deals with all policy matters pertaining to domestic and foreign affairs, is described as a 'Super-Cabinet' — reflecting its especially broad and powerful role compared to the other, more narrowly focused committees."})

basic.append({"q":"Which Cabinet Committee deals with the allotment of government accommodation to Members of Parliament, central government employees, and other persons/organisations?","o":["Cabinet Committee on Accommodation","Cabinet Committee on Parliamentary Affairs","Appointments Committee of the Cabinet","Cabinet Committee on Employment and Skill Development"],"a":0,"e":"The <b>Cabinet Committee on Accommodation</b> handles this specific administrative function — a narrower, more operationally focused mandate compared to the broader policy committees like Political Affairs or Economic Affairs."})

basic.append({"q":"How many Cabinet Committees are currently listed as functional in the book?","o":["8","5","10","6"],"a":0,"e":"The book lists <b>8</b> functional Cabinet Committees: Political Affairs, Economic Affairs, Appointments, Parliamentary Affairs, Security, Accommodation, Investment and Growth, and Employment and Skill Development — though this number can change over time given the PM's discretion to reconstitute committees."})

basic.append({"q":"What are Groups of Ministers (GoMs), and are they permanent bodies?","o":["Ad hoc bodies formed to recommend on emergent issues, disbanded once their advice is crystallised","Permanent statutory bodies fixed by Parliament with unchanging membership","A subset of Cabinet Committees dealing only with foreign policy","Bodies exclusively composed of non-cabinet ministers with no cabinet ministers included"],"a":0,"e":"GoMs are <b>ad hoc (temporary) bodies</b> formed to give recommendations to the Cabinet on emergent issues and critical problems — ministers heading relevant ministries are inducted in, and once their advice is finalised ('crystallised'), the GoM is disbanded."})

basic.append({"q":"Are all Groups of Ministers (GoMs) empowered to take final decisions on behalf of the Cabinet?","o":["No, some GoMs can take decisions on behalf of the Cabinet, while others only make recommendations to the Cabinet","Yes, all GoMs have full decision-making power identical to the Cabinet itself","No, GoMs have no role in decision-making or recommendations at all","Yes, but only the Cabinet Committee on Political Affairs can authorise this power"],"a":0,"e":"GoMs are of two functional types: some are <b>empowered to take decisions</b> on behalf of the Cabinet, while others merely <b>make recommendations</b> to the Cabinet for its own decision — this distinction reflects varying levels of delegated authority granted to different GoMs."})

basic.append({"q":"Which commission examined the working of Groups of Ministers (GoMs) and made recommendations about their effective functioning, in its 2005-2009 report?","o":["The Second Administrative Reforms Commission","The Sarkaria Commission","The Punchhi Commission","The First Administrative Reforms Commission"],"a":0,"e":"The <b>Second Administrative Reforms Commission (2005-2009)</b>, headed by Veerappa Moily (a senior Congress leader and former Karnataka Chief Minister), examined GoM functioning and made specific recommendations about their more selective and effective use."})

basic.append({"q":"According to the Second Administrative Reforms Commission, what problem arose from constituting too many GoMs?","o":["Many GoMs could not meet regularly to complete their work, causing significant delays on major issues","GoMs became too powerful and began overriding the Cabinet entirely","GoMs led to excessive government spending with no corresponding benefit","GoMs caused a constitutional crisis requiring a fresh amendment"],"a":0,"e":"The Commission found that having a <b>large number of GoMs</b> resulted in many of them being unable to meet regularly, causing <b>significant delays</b> on important issues — precisely the opposite of the coordination efficiency GoMs are meant to provide."})

basic.append({"q":"What did the Second Administrative Reforms Commission recommend to make GoMs function more effectively?","o":["More selective use of GoMs, empowered to decide on behalf of the Cabinet, with prescribed time limits","Abolishing GoMs entirely and replacing them with permanent Cabinet Committees","Doubling the number of GoMs to handle more issues in parallel","Removing all ministers from GoMs and staffing them with civil servants only"],"a":0,"e":"The Commission recommended <b>more selective use</b> of GoMs, giving them clear mandates and the power to decide on behalf of the Cabinet within <b>prescribed time limits</b> — aiming for fewer but more effective, faster-acting GoMs rather than a proliferation of slow-moving ones."})

basic.append({"q":"Which ad hoc Cabinet Committee, cited as a historical example in the book, was set up in 1962?","o":["The Emergency Committee, set up after the Chinese invasion","The Cabinet Committee on Security","The Appointments Committee of the Cabinet","The Cabinet Committee on Economic Affairs"],"a":0,"e":"The <b>Emergency Committee</b> was set up in 1962 following the Chinese invasion — a clear illustration of an AD HOC committee, formed to address a specific, time-bound crisis and presumably disbanded once that immediate situation was resolved."})

basic.append({"q":"Can non-cabinet ministers ever participate in Cabinet Committee proceedings, even though these committees usually include only Cabinet Ministers?","o":["Yes, non-cabinet ministers can be appointed as members or attend as special invitees","No, only Cabinet Ministers are permitted any involvement whatsoever","Yes, but only as silent observers with no speaking rights","No, non-cabinet ministers are constitutionally barred from any Cabinet-level proceedings"],"a":0,"e":"While Cabinet Committees usually include only Cabinet Ministers, <b>non-cabinet ministers CAN be appointed as members</b> in some cases, and can also attend meetings as <b>special invitees</b> — showing the membership rules are flexible rather than rigidly restricted to cabinet rank alone."})

# ---------------- INTERMEDIATE ----------------
intermediate.append({"q":"Consider the following statements about the features of Cabinet Committees:\n1. Their number, nomenclature and composition are fixed permanently once established and cannot be changed by any subsequent Prime Minister.\n2. They usually include only Cabinet Ministers, but non-cabinet ministers can also be members or special invitees.\n3. They include not only ministers in charge of the specific subjects covered but also other senior ministers.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — the book explicitly states these committees are set up 'according to the exigencies of the time', meaning their number, nomenclature, and composition VARY over time rather than being permanently fixed. Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the decision-making power of Cabinet Committees:\n1. They can only formulate proposals for the Cabinet's consideration and cannot take actual decisions themselves.\n2. Decisions taken by a Cabinet Committee can be reviewed by the full Cabinet.\n3. This delegation of decision-making power is based on the principles of division of labour and effective delegation.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — Cabinet Committees CAN and DO take actual decisions, not merely formulate proposals; the Cabinet retains only a REVIEW power over these decisions, not sole decision-making authority. Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements comparing Cabinet Committees and Groups of Ministers (GoMs):\n1. Both are extra-constitutional bodies not mentioned in the Constitution's text.\n2. Cabinet Committees can be standing or ad hoc, while GoMs are always exclusively ad hoc bodies.\n3. GoMs, unlike Cabinet Committees, are never empowered to take decisions and can only make recommendations.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — some GoMs ARE empowered to take decisions on behalf of the Cabinet, not exclusively limited to making recommendations; this power varies by GoM. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about the Second Administrative Reforms Commission's findings on GoMs:\n1. It found that too many GoMs led to delays because many could not meet regularly.\n2. It recommended more selective use of GoMs with prescribed time limits for completing their work.\n3. It recommended abolishing the GoM mechanism altogether in favour of permanent Cabinet Committees.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Commission did NOT recommend abolishing GoMs; it recommended making the EXISTING GoM mechanism function more effectively through selective and time-bound use, not replacing it entirely. Statements 1 and 2 are correct."})

# ---------------- ADVANCED ----------------
advanced.append({"q":"Which of the following best explains why Cabinet Committees are considered an effective 'organisational device' despite having no constitutional basis?","o":["Their extra-constitutional, Rules-of-Business-based flexibility allows the Prime Minister to reshape their number and composition freely in response to changing circumstances, while their delegated (though reviewable) decision-making power genuinely reduces the full Cabinet's workload through effective division of labour","Their lack of constitutional basis makes their decisions legally void and hence practically irrelevant to governance","They derive their authority entirely from Supreme Court judgments rather than any executive rule","They function exactly like the full Cabinet with completely identical powers and status"],"a":0,"e":"The genuine effectiveness of Cabinet Committees comes precisely FROM their extra-constitutional flexibility — being governed by Rules of Business rather than rigid constitutional text lets the PM adapt their number, composition, and mandate to current needs, while their real (though Cabinet-reviewable) decision-making power means they don't merely add another layer of discussion but actually offload substantive work from the full Cabinet."})

advanced.append({"q":"Which of the following best explains why the Cabinet Committee on Political Affairs earns the label 'Super-Cabinet' despite being just one of eight cabinet committees?","o":["Its mandate covers ALL policy matters pertaining to both domestic AND foreign affairs — an unusually broad, cross-cutting scope compared to the other seven committees, which each address a specific, narrower functional domain (economics, security, appointments, accommodation, etc.)","It has the constitutional power to dissolve the full Cabinet at will","It consists of every single Cabinet Minister without exception, making it identical in size to the full Cabinet","It was specifically created to replace the Prime Minister's office entirely"],"a":0,"e":"The 'Super-Cabinet' label reflects the committee's uniquely BROAD jurisdiction — while the other seven committees each have a defined, narrower functional focus (economic affairs, security, appointments, parliamentary affairs, accommodation, investment/growth, employment/skills), the Political Affairs Committee's mandate spans the ENTIRE range of domestic and foreign policy matters, giving it an outsized, near-comprehensive scope relative to its peers."})

# ---------------- UPSC TIER ----------------
upsc.append({"q":"Consider the following statements about Cabinet Committees and Groups of Ministers:\n1. Both institutions serve as coordination mechanisms that reduce the full Cabinet's workload.\n2. Cabinet Committees are established under the Rules of Business, while GoMs derive their existence purely from executive practice with no similar procedural backing mentioned in the book.\n3. Both institutions can, in at least some instances, take binding decisions rather than merely offering recommendations.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 overstates the distinction — while Cabinet Committees are explicitly tied to the Rules of Business, the book does not draw as sharp a procedural contrast for GoMs; both remain executive coordination mechanisms rather than one being clearly 'more official' than the other in the terms the book uses. Statements 1 and 3 are correct."})

upsc.append({"q":"Assertion (A): Cabinet Committees can take actual decisions rather than merely formulating recommendations.\nReason (R): The Cabinet retains the power to review decisions taken by its committees, ensuring ultimate accountability remains with the full Cabinet even while decision-making authority is delegated downward.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the Cabinet's retained REVIEW power is precisely what makes it constitutionally/administratively acceptable to delegate actual decision-making authority to committees, since ultimate oversight remains with the full Cabinet even as day-to-day decisions are made at the committee level."})

upsc.append({"q":"With reference to the Second Administrative Reforms Commission's (2005-2009) recommendations on GoMs, consider the following statements:\n1. It recommended prescribing clear time limits for GoMs to complete their entrusted work.\n2. It recommended that GoMs be empowered to arrive at decisions on behalf of the Cabinet in appropriate cases.\n3. It found that constituting too FEW GoMs was the primary cause of governmental delays.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the Commission's actual finding — it found that constituting a LARGE NUMBER of GoMs (too many, not too few) caused delays, since many could not meet regularly to complete their assigned work. Statements 1 and 2 are correct."})

data = {"basic": basic, "intermediate": intermediate, "advanced": advanced, "upsc": upsc}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q),1))

chapter = {
    "id": "cabinet_committees",
    "title": "Cabinet Committees",
    "desc": "Features, types, composition, and functions of Cabinet Committees; the eight functional Cabinet Committees and their mandates; and Groups of Ministers (GoMs) including the Second Administrative Reforms Commission's recommendations on their effective use",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/polity_ch21_cabinet_committees_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
