import json

basic = []
intermediate = []
advanced = []
upsc = []

# ---------------- BASIC ----------------
basic.append({"q":"In which Part and Articles of the Constitution are the Emergency provisions contained?","o":["Part XVIII, Articles 352 to 360","Part XX, Article 368","Part XI, Articles 245 to 263","Part III, Articles 12 to 35"],"a":0,"e":"The Emergency provisions are in <b>Part XVIII, Articles 352 to 360</b>. They enable the Centre to meet abnormal situations effectively, safeguarding the sovereignty, unity, integrity and security of the country, the democratic political system, and the Constitution itself."})

basic.append({"q":"Which three types of emergencies does the Constitution stipulate?","o":["National Emergency (Art. 352), President's Rule (Art. 356), and Financial Emergency (Art. 360)","National Emergency, State Emergency, and Local Emergency, all under Article 352","Internal Emergency, External Emergency, and Financial Emergency, all under Article 356","War Emergency, Peace Emergency, and Economic Emergency"],"a":0,"e":"The three types are: <b>National Emergency</b> (Article 352, due to war/external aggression/armed rebellion), <b>President's Rule</b> (Article 356, due to failure of constitutional machinery in a state, also called State/Constitutional Emergency), and <b>Financial Emergency</b> (Article 360, due to threat to financial stability/credit of India)."})

basic.append({"q":"What term did the original Constitution use as the third ground for a National Emergency, which was later replaced by 'armed rebellion'?","o":["Internal disturbance","Civil unrest","Domestic insurrection","Public disorder"],"a":0,"e":"The original ground was '<b>internal disturbance</b>', considered too vague with a wide connotation. The <b>44th Amendment Act, 1978</b> substituted it with 'armed rebellion' — meaning a National Emergency can no longer be declared on the ground used in 1975 by Indira Gandhi's government."})

basic.append({"q":"On whose written recommendation alone can the President now proclaim a National Emergency, following the 44th Amendment Act, 1978?","o":["The Cabinet's recommendation","The Prime Minister's advice alone","The Chief Justice of India's advice","The Speaker of the Lok Sabha's advice"],"a":0,"e":"The President can proclaim a National Emergency only after receiving a <b>written recommendation from the Cabinet</b> — requiring cabinet CONCURRENCE, not merely the PM's advice. This safeguard was added specifically because in 1975, Indira Gandhi advised the President without consulting her cabinet, which only learned of the proclamation afterward as a fait accompli."})

basic.append({"q":"Within how many months must a proclamation of National Emergency be approved by both Houses of Parliament, per the 44th Amendment Act, 1978?","o":["One month","Two months","Three months","Six months"],"a":0,"e":"It must be approved within <b>one month</b> — reduced from the original two months by the 44th Amendment Act, 1978, to ensure quicker parliamentary scrutiny of the executive's emergency power."})

basic.append({"q":"By what kind of majority must a resolution approving a National Emergency proclamation or its continuation be passed in each House?","o":["Special majority","Simple majority","Absolute majority of total membership only","No specific majority is required"],"a":0,"e":"A <b>special majority</b> is required — a majority of the total membership of the House AND a majority of not less than two-thirds of members present and voting. This stricter requirement, introduced by the 44th Amendment Act, 1978, replaced the earlier simple-majority standard, making it harder to approve or continue a National Emergency."})

basic.append({"q":"According to Article 358, which Fundamental Rights are automatically suspended the moment a National Emergency is declared, without any separate order?","o":["The six Fundamental Rights under Article 19","All Fundamental Rights without exception","Only the right to property","Rights under Articles 20 and 21"],"a":0,"e":"Article 358 automatically suspends the <b>six Fundamental Rights under Article 19</b> — no separate suspension order is needed. This differs from Article 359, which requires a specific Presidential Order to suspend the ENFORCEMENT of other specified rights."})

basic.append({"q":"Which two Fundamental Rights can NEVER have their enforcement suspended under Article 359, even during a National Emergency, following the 44th Amendment Act?","o":["Articles 20 and 21","Articles 19 and 21","Articles 14 and 19","Articles 25 and 26"],"a":0,"e":"<b>Articles 20</b> (protection in respect of conviction for offences) and <b>21</b> (right to life and personal liberty) can never have their enforcement suspended, even during an Emergency — a critical safeguard added by the 44th Amendment Act, 1978, in direct response to the excesses of the 1975-77 Emergency."})

basic.append({"q":"How many times has a National Emergency been proclaimed in India so far, according to the book?","o":["Three times — 1962, 1971, and 1975","Once, in 1975","Twice, in 1971 and 1975","Four times, including during the 1991 financial crisis"],"a":0,"e":"National Emergency has been proclaimed <b>three times</b>: in <b>1962</b> (Chinese aggression in NEFA), <b>1971</b> (Pakistan's attack), and <b>1975</b> (on the ground of 'internal disturbance', the most controversial of the three, later replaced by 'armed rebellion' in the Constitution's text)."})

basic.append({"q":"Which commission was appointed by the Janata Party government to investigate the circumstances behind the 1975 Emergency declaration?","o":["Shah Commission","Sarkaria Commission","Punchhi Commission","Rajamannar Committee"],"a":0,"e":"The <b>Shah Commission</b> was appointed after the Congress Party's 1977 electoral defeat to investigate the 1975 Emergency. It did NOT justify the declaration, and this finding directly led to the 44th Amendment Act, 1978, which introduced numerous safeguards against future misuse of emergency powers."})

basic.append({"q":"Which Article empowers the President to hold that a state's government cannot be carried on according to the Constitution if the state fails to comply with a Central direction?","o":["Article 365","Article 356","Article 352","Article 360"],"a":0,"e":"<b>Article 365</b> provides this specific ground for President's Rule, working alongside <b>Article 356</b> itself (which allows the President to act on a Governor's report or otherwise, even without a report) — together forming the two grounds on which President's Rule can be proclaimed."})

basic.append({"q":"Within how many months must a proclamation of President's Rule be approved by both Houses of Parliament?","o":["Two months","One month","Three months","Six months"],"a":0,"e":"A President's Rule proclamation must be approved within <b>two months</b> — notably different (longer) than the one-month window for National Emergency approval, reflecting the differing severity and constitutional design of the two provisions."})

basic.append({"q":"What is the maximum total period for which President's Rule can continue in a state, as capped by the 44th Amendment Act, 1978?","o":["Three years","One year","Six months","Indefinitely, with no cap"],"a":0,"e":"President's Rule can continue for a <b>maximum of three years</b>. Beyond the first year, extensions require BOTH a National Emergency to be in operation AND an Election Commission certification that state elections cannot be held — a deliberate double-lock the 44th Amendment introduced to prevent indefinite, unchecked President's Rule."})

basic.append({"q":"By what majority must a resolution approving President's Rule or its continuation be passed by each House of Parliament?","o":["Simple majority","Special majority","Absolute majority","Two-thirds of total membership"],"a":0,"e":"A <b>simple majority</b> suffices for President's Rule resolutions — unlike the special majority required for National Emergency resolutions, reflecting that President's Rule, while serious, is treated as a less drastic and more localised intervention than a full National Emergency."})

basic.append({"q":"In which landmark 1994 case did the Supreme Court hold that the President's satisfaction under Article 356 is subject to judicial review and laid down detailed guidelines on its proper use?","o":["S.R. Bommai case","Kesavananda Bharati case","Minerva Mills case","Golak Nath case"],"a":0,"e":"The <b>S.R. Bommai case (1994)</b> laid down comprehensive propositions on Article 356 — holding the presidential proclamation is subject to judicial review, that courts can restore a dismissed government if the proclamation is found unconstitutional, and that secularism being a basic feature can justify action against an anti-secular state government."})

basic.append({"q":"Article 360 empowers the President to proclaim a Financial Emergency when the financial stability or credit of India (or any part) is threatened. How many times has a Financial Emergency actually been declared in India?","o":["Never, despite a financial crisis in 1991","Once, during the 1991 financial crisis","Twice, in 1991 and 2008","Three times, matching the National Emergency count"],"a":0,"e":"A Financial Emergency has <b>never been declared</b>, even though India faced a genuine financial crisis in 1991 — illustrating that Article 360, unlike Articles 352 and 356, has remained entirely unused since 1950."})

basic.append({"q":"By what majority is a resolution approving the proclamation of Financial Emergency passed, and for how long does it continue once approved?","o":["Simple majority, and it continues indefinitely until revoked","Special majority, and it continues for six months only","Simple majority, and it continues for exactly one year","Special majority, and it continues indefinitely"],"a":0,"e":"A Financial Emergency resolution needs only a <b>simple majority</b>, and once approved, it continues <b>indefinitely until revoked</b> — with no maximum period prescribed and no need for repeated periodic parliamentary approval, unlike both other types of emergency."})

basic.append({"q":"Which amendment made the President's satisfaction in declaring a National Emergency, President's Rule, or Financial Emergency immune from judicial review, a provision later deleted by the 44th Amendment?","o":["38th Amendment Act, 1975","42nd Amendment Act, 1976","24th Amendment Act, 1971","39th Amendment Act, 1975"],"a":0,"e":"The <b>38th Amendment Act, 1975</b> made the President's 'satisfaction' in all three emergency provisions immune from judicial review. The <b>44th Amendment Act, 1978</b> subsequently deleted this immunity, restoring the principle that the President's satisfaction is not beyond judicial scrutiny."})

basic.append({"q":"Which member of the Constituent Assembly famously commented, 'Dr. Ambedkar is dead and the Articles are very much alive,' regarding the frequent misuse of Article 356?","o":["H.V. Kamath","K.T. Shah","T.T. Krishnamachari","H.N. Kunzru"],"a":0,"e":"<b>H.V. Kamath</b> made this pointed observation, referencing Ambedkar's own hope that Article 356 would remain a 'dead-letter' used only as a last resort — a hope that, as the book notes, was contradicted by the more than 125 times President's Rule has actually been imposed since 1950."})

# ---------------- INTERMEDIATE ----------------
intermediate.append({"q":"Consider the following statements about the nature of India's federal system during Emergency:\n1. Dr. Ambedkar observed that, unlike other federations like the USA, India's Constitution can function as both unitary and federal depending on circumstances.\n2. All federal systems, including the American one, can similarly transform into a unitary system during a crisis.\n3. This unitary-during-emergency feature of the Indian Constitution operates without any formal constitutional amendment.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — Ambedkar specifically contrasted India with other federations, saying American-style federal systems are placed in a 'tight mould' and can NEVER become unitary regardless of circumstances, unlike India's uniquely flexible design. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the grounds and scope of National Emergency declarations:\n1. The President can declare a National Emergency even before the actual occurrence of war, if satisfied there is imminent danger.\n2. A National Emergency proclamation always applies to the entire country and can never be limited to a part of it.\n3. When declared on the ground of 'armed rebellion', it is known as 'Internal Emergency'.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the 42nd Amendment Act, 1976 specifically enabled the President to limit a National Emergency's operation to just a specified part of India, rather than requiring it to always cover the whole country. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the revocation of a National Emergency proclamation:\n1. The President can revoke it at any time by a subsequent proclamation without needing parliamentary approval.\n2. The President must revoke it if the Lok Sabha passes a resolution disapproving its continuation.\n3. A resolution of disapproval requires a special majority in the Lok Sabha, identical to the resolution approving continuation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — a resolution of DISapproval needs only a SIMPLE majority and needs to be passed by the Lok Sabha ALONE, whereas a resolution APPROVING continuation needs a special majority passed by BOTH Houses — the two resolutions have different procedural requirements. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about the effects of National Emergency on Centre-state legislative relations:\n1. The legislative power of state legislatures is completely suspended during a National Emergency.\n2. Parliament becomes empowered to make laws on any subject in the State List during the Emergency.\n3. Laws made by Parliament on state subjects during the Emergency become inoperative six months after the Emergency ceases.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — state legislatures are NOT suspended during a National Emergency; their power merely becomes SUBJECT TO the overriding power of Parliament, meaning both continue to function concurrently. Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements comparing Articles 358 and 359:\n1. Article 358 operates in case of both External and Internal Emergency, while Article 359 operates only in External Emergency.\n2. Article 358 automatically suspends rights the moment Emergency is declared, while Article 359 requires a specific Presidential Order.\n3. Both Articles provide immunity from challenge only to laws related to the Emergency, not to other laws.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect and reverses the actual rule — Article 358 operates ONLY in case of External Emergency (war/external aggression), NOT Internal Emergency (armed rebellion), while Article 359 operates in BOTH cases. Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the extension of the Lok Sabha's term during a National Emergency:\n1. The Lok Sabha's term can be extended beyond five years by a law of Parliament, one year at a time, for any length of time.\n2. Such extension can continue indefinitely even after the Emergency has ceased to operate.\n3. The term of the Fifth Lok Sabha (1971-1977) was extended twice, by one year each time.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — such extension CANNOT continue beyond a period of six months after the Emergency has ceased to operate; it is not indefinite once the Emergency ends. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the distinction between National Emergency and President's Rule (per Table 17.1):\n1. During National Emergency, the state executive continues to function, whereas during President's Rule, the state executive is dismissed.\n2. National Emergency has no maximum period, while President's Rule has a maximum period of three years.\n3. Both provisions equally affect the Fundamental Rights of citizens.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — National Emergency DOES affect Fundamental Rights (via Articles 358-359), but President's Rule has NO effect on Fundamental Rights whatsoever, a key distinction the book's comparison table highlights. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about Parliament's law-making power under National Emergency versus President's Rule:\n1. Under National Emergency, Parliament can make State List laws only by itself and cannot delegate this power to any other body.\n2. Under President's Rule, Parliament can delegate its law-making power for the state to the President or another specified authority.\n3. Laws made by the President in this delegated capacity are known as 'President's Acts'.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — this is a genuine structural difference between the two emergency types: National Emergency legislative power stays with Parliament directly, while President's Rule allows delegation, commonly exercised in practice by the President making 'President's Acts' in consultation with MPs from the concerned state."})

intermediate.append({"q":"Consider the following statements about the S.R. Bommai case's (1994) propositions on Article 356:\n1. The burden lies on the Centre to prove that relevant material exists to justify President's Rule.\n2. The court can go into the correctness and adequacy of the material used by the President.\n3. The state legislative assembly should be dissolved only after Parliament has approved the presidential proclamation.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the Court explicitly held it CANNOT go into the correctness or adequacy of the material; it can only examine whether the material is RELEVANT to the action, a narrower and more deferential standard of review. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about proper versus improper use of Article 356, per the Sarkaria Commission/Bommai case framework:\n1. A 'Hung Assembly' after general elections is listed as a situation where President's Rule would be proper.\n2. Maladministration or corruption allegations against a ministry is listed as a situation where President's Rule would be proper.\n3. Using the power to sort out intra-party problems of the ruling party is listed as an improper use.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — maladministration or corruption allegations are explicitly listed among the IMPROPER grounds for imposing President's Rule, not proper ones. Statements 1 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the Financial Emergency provisions under Article 360:\n1. The President can direct the reduction of salaries of persons serving the Union, including Supreme Court and High Court judges.\n2. The Centre can require states to reserve money bills for the President's consideration during a Financial Emergency.\n3. Dr. Ambedkar noted this provision followed the pattern of the UK's wartime emergency legislation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Ambedkar actually referenced the <b>US National Recovery Act of 1933</b>, enacted to address the Great Depression, as the model for this provision — not any UK legislation. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about the 1975 National Emergency:\n1. It was declared on the ground of 'external aggression'.\n2. It was the third proclamation of National Emergency, made while the second (1971) proclamation was still in operation.\n3. It was revoked in March 1977, at the same time as the 1971 proclamation.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect — the 1975 Emergency was declared on the ground of 'internal disturbance' (certain persons inciting police and armed forces against their duties), not external aggression (which was the ground for the 1962 and 1971 proclamations). Statements 2 and 3 are correct."})

intermediate.append({"q":"Consider the following statements about the special sitting provision introduced by the 44th Amendment Act, 1978:\n1. One-tenth of the total Lok Sabha members can give written notice to the Speaker requesting a special sitting.\n2. The special sitting must be held within 14 days of receiving such notice.\n3. This provision applies to considering a resolution approving (not disapproving) the continuation of the Emergency.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — this special sitting mechanism exists specifically for considering a resolution DISapproving the continuation of the proclamation, giving a check against the executive, not for approving it. Statements 1 and 2 are correct."})

intermediate.append({"q":"Consider the following statements about President's Rule imposed in 1992 in Madhya Pradesh, Himachal Pradesh and Rajasthan:\n1. It was imposed by the Congress Party on the ground that these BJP-ruled states were not sincerely implementing a Central ban on religious organisations.\n2. The Supreme Court in the Bommai case upheld its validity on the ground that secularism is a basic feature of the Constitution.\n3. This was the first time in Indian history that President's Rule had ever been imposed anywhere.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — President's Rule was first imposed as far back as 1951 in Punjab, and by the 1990s had already been imposed on more than 125 occasions across nearly all states; the 1992 case was far from the first instance. Statements 1 and 2 are correct."})

# ---------------- ADVANCED ----------------
advanced.append({"q":"Which of the following best explains why the 44th Amendment Act, 1978 required CABINET recommendation (not just PM advice) before a National Emergency could be proclaimed?","o":["Because the 1975 Emergency was declared on Indira Gandhi's sole advice without cabinet consultation, and requiring formal cabinet concurrence distributes responsibility for such a drastic decision across multiple ministers rather than concentrating it in one individual, making future unilateral declarations harder","Because the Cabinet has more constitutional authority than the President under Article 352","Because the Prime Minister no longer has any role in emergency declarations after 1978","Because international law required cabinet-level decisions for emergency declarations"],"a":0,"e":"This safeguard directly targeted the specific 1975 failure mode — a single individual (the PM) unilaterally deciding to impose a National Emergency, with the Cabinet only informed afterward as a 'fait accompli' — by legally mandating that the decision instead reflect the CONCURRENCE of the full Cabinet, distributing accountability and creating a built-in check against impulsive or purely personal political decisions."})

advanced.append({"q":"Which of the following best explains the logic behind Article 358 applying only to External Emergency while Article 359 applies to both External and Internal Emergency?","o":["Article 19's freedoms (like speech, assembly, movement) are considered especially likely to need automatic, blanket suspension specifically during genuine external conflict, whereas the broader menu of rights under Article 359 (subject to specific presidential orders) offers more calibrated, case-by-case flexibility appropriate to the more politically sensitive context of internal unrest","Article 358 was declared void by the Supreme Court and no longer has any legal effect","Internal Emergency was abolished entirely by the 44th Amendment Act","Article 359 only applies to Union Territories, not full states"],"a":0,"e":"This differential design reflects a deliberate post-1978 recalibration: Article 358's AUTOMATIC, blanket suspension of Article 19 rights (with no need for a specific order) is confined to the less politically fraught scenario of EXTERNAL conflict, while the more politically sensitive scenario of INTERNAL armed rebellion is instead handled through Article 359's more calibrated, government-specified, order-by-order approach — a distinction that emerged specifically because the 44th Amendment sought to prevent the kind of broad, automatic rights suspension that characterised the controversial 1975 Emergency."})

advanced.append({"q":"Which of the following best captures why the book treats the transformation from Ambedkar's hoped-for 'dead-letter' to Kamath's observed 'deadly-weapon' as significant?","o":["It illustrates a recurring theme in constitutional design — that a provision's actual operation in practice can diverge dramatically from its framers' stated intentions, especially when the provision grants broad discretionary power without correspondingly strong institutional or judicial checks at the time of framing","It proves that Article 356 was unconstitutional from the moment of the Constitution's adoption","It shows that Ambedkar personally supported the misuse of Article 356 in later decades","It demonstrates that the Constituent Assembly never debated Article 356 at all"],"a":0,"e":"This contrast (over 125 invocations since 1950, against Ambedkar's explicit hope that the provision would 'remain a dead-letter' used only as a 'measure of last resort') illustrates a broader lesson about constitutional design: provisions granting wide executive discretion, absent robust contemporaneous checks, can be — and often are — used far more expansively than their framers intended, which is precisely why later judicial intervention (Bommai) and commission recommendations (Sarkaria) became necessary correctives decades after the original constitutional text was settled."})

advanced.append({"q":"Which of the following best explains why the Bommai case's list of 'improper' uses of Article 356 emphasises procedural fairness toward incumbent state governments (e.g., allowing them to prove majority on the floor of the House)?","o":["Because without such procedural safeguards, a Governor's or Centre's subjective, potentially politically-motivated assessment of a ministry's support could substitute for the objectively verifiable test of an actual floor vote, making the exercise of Article 356 vulnerable to partisan manipulation rather than genuine constitutional necessity","Because the Constitution requires all confidence votes to be certified by the Supreme Court before any dismissal","Because state legislative assemblies have no role whatsoever in matters of ministry formation or dismissal","Because floor votes are only relevant during a Financial Emergency, not President's Rule"],"a":0,"e":"The Court's insistence on floor-tested confidence (rather than a Governor's own subjective assessment) directly targets the risk of PARTISAN MANIPULATION — a Governor sympathetic to the Centre's ruling party could otherwise simply assert (without a genuine test) that a ministry has lost majority support, providing false constitutional cover for what is really a politically motivated dismissal; requiring an actual floor vote replaces subjective judgment with an objectively verifiable, transparent process."})

advanced.append({"q":"Which of the following best explains why Financial Emergency (Article 360) has never been invoked despite the 1991 financial crisis, in contrast to the much more frequent use of National Emergency and President's Rule?","o":["The book does not explicitly state the reason, but the pattern suggests financial crises have historically been managed through other policy tools (like economic reforms and international assistance) rather than requiring the drastic, centralising constitutional mechanism of Article 360, which would involve significant political costs like potentially reducing judicial and civil service salaries","Article 360 was repealed by a constitutional amendment before 1991","The Reserve Bank of India has exclusive authority over financial emergencies, making Article 360 redundant","India has never faced a genuine threat to financial stability or credit since 1950"],"a":0,"e":"While the book doesn't give an explicit causal explanation, the pattern is notable: even during the acute 1991 balance-of-payments crisis, India resorted to economic liberalisation, IMF assistance, and gold pledging rather than invoking Article 360 — likely because the constitutional mechanism carries severe, hard-to-reverse political costs (like directing salary reductions for judges and civil servants) that make it a genuinely last-resort tool, distinct from the more frequently invoked (and more narrowly targeted) National Emergency and President's Rule provisions."})

advanced.append({"q":"Which of the following best explains why President's Rule requires only a simple majority for parliamentary approval while National Emergency requires a special majority?","o":["This reflects a deliberate calibration of procedural difficulty to the scale and severity of impact — National Emergency affects Fundamental Rights and the entire Centre-state relationship nationally, warranting a harder-to-achieve special majority, while President's Rule affects only one state's administration without touching Fundamental Rights, warranting a comparatively easier simple-majority threshold","Both actually require the same special majority, and the book's description is inconsistent","President's Rule requires a HIGHER threshold than National Emergency, not a lower one","The majority requirement depends solely on which political party controls Parliament at the time"],"a":0,"e":"This differential threshold reflects the differing GRAVITY of consequences: National Emergency has nationwide effects, suspends specific Fundamental Rights, and fundamentally reworks the entire federal structure — justifying a harder-to-pass special majority as a check; President's Rule, though serious, is confined to one state's administration with NO effect on Fundamental Rights, justifying the comparatively lower simple-majority bar."})

# ---------------- UPSC TIER ----------------
upsc.append({"q":"Consider the following statements about the 44th Amendment Act, 1978's safeguards on Emergency provisions:\n1. It requires a written recommendation of the Cabinet before a National Emergency can be proclaimed.\n2. It introduced special majority requirements for parliamentary approval of a National Emergency.\n3. It removed the requirement of periodic parliamentary approval for continuing a National Emergency, allowing it to continue indefinitely without renewed approval.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the amendment's actual effect — the 44th Amendment ADDED the requirement of periodic (every six months) parliamentary approval for continuance, replacing the earlier position where the Emergency could continue indefinitely at the Executive's sole discretion once initially approved. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): Article 358 automatically suspends the six Fundamental Rights under Article 19 the moment a National Emergency is declared on the ground of war or external aggression.\nReason (R): Article 358, unlike Article 359, does not require a separate Presidential Order to suspend rights, and applies only to External Emergency, not Internal Emergency, following the 44th Amendment Act's restrictions.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the automatic, order-free nature of Article 358's suspension mechanism, combined with its restriction (post-1978) to External Emergency only, together explain precisely why and when Article 19 rights get automatically suspended."})

upsc.append({"q":"With reference to the use of Article 356, consider the following statements:\n1. President's Rule was first imposed in Punjab in 1951.\n2. In 1977, the Janata Party government imposed President's Rule in nine Congress-ruled states on the ground that assemblies no longer represented the electorate's wishes.\n3. The Supreme Court in the Bommai case (1994) upheld the imposition of President's Rule in Nagaland (1988), Karnataka (1989), and Meghalaya (1991).\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Supreme Court did NOT uphold the validity of President's Rule imposition in Nagaland (1988), Karnataka (1989), or Meghalaya (1991); it instead upheld the 1992 imposition in Madhya Pradesh, Himachal Pradesh, and Rajasthan on secularism grounds. Statements 1 and 2 are correct."})

upsc.append({"q":"Consider the following statements about the comparison between National Emergency and President's Rule:\n1. Under National Emergency, the Centre gets concurrent powers of administration and legislation, while state executive and legislature continue functioning.\n2. Under President's Rule, the state executive is dismissed and the legislature is suspended or dissolved, with the Centre assuming full executive and legislative powers.\n3. Only National Emergency allows the Lok Sabha to pass a resolution for its own revocation; no equivalent provision exists for President's Rule.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct and comprehensively capture the key distinctions from Table 17.1 — National Emergency preserves state institutions under Central overlay, while President's Rule effectively replaces them; and only National Emergency gives the Lok Sabha a specific revocation-forcing mechanism."})

upsc.append({"q":"Match List-I (Bommai case proposition) with List-II (its substantive content) and select the correct answer using the code below.\nList-I:\nA. On judicial review\nB. On burden of proof\nC. On basic feature grounds\nD. On assembly dissolution timing\nList-II:\n1. Secularism being a basic feature justifies action against anti-secular state governments\n2. The presidential proclamation imposing President's Rule is subject to judicial review\n3. The assembly should be dissolved only after Parliament approves the proclamation\n4. The burden lies on the Centre to prove relevant material justifying President's Rule","o":["A-2, B-4, C-1, D-3","A-1, B-2, C-4, D-3","A-2, B-1, C-4, D-3","A-4, B-2, C-3, D-1"],"a":0,"e":"On judicial review: proclamation is subject to review (2); on burden of proof: lies on the Centre (4); on basic features: secularism justifies action against anti-secular governments (1); on dissolution timing: only after parliamentary approval (3). Correct code: A-2, B-4, C-1, D-3."})

upsc.append({"q":"Consider the following statements about criticisms and defences of the Emergency provisions in the Constituent Assembly:\n1. H.V. Kamath feared the provisions would lay the foundation of a totalitarian, police state.\n2. Alladi Krishnaswami Ayyar defended the provisions as 'the very life-breath of the Constitution'.\n3. Dr. Ambedkar categorically denied any possibility that these Articles could ever be misused for political purposes.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Ambedkar actually ACCEPTED the possibility of misuse, stating 'I do not altogether deny that there is a possibility of the Articles being abused or employed for political purposes' — a notably candid admission rather than a categorical denial. Statements 1 and 2 are correct."})

upsc.append({"q":"With reference to the effects of a National Emergency on the Centre-state financial relationship, consider the following statements:\n1. The President can modify the constitutional distribution of revenues between the Centre and states.\n2. Such modification can continue indefinitely, even well beyond the financial year in which the Emergency ceases.\n3. Every such presidential order modifying revenue distribution must be laid before both Houses of Parliament.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — such modification continues only until the end of the financial year in which the Emergency ceases to operate, not indefinitely beyond that. Statements 1 and 3 are correct."})

upsc.append({"q":"Consider the following statements about the President's Rule extension mechanism beyond one year, introduced by the 44th Amendment Act, 1978:\n1. It requires a National Emergency to be in operation in the whole of India, or in the whole or part of the concerned state.\n2. It requires the Election Commission to certify that state assembly elections cannot be held due to difficulties.\n3. Both conditions must be fulfilled simultaneously for the extension beyond one year to be valid.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — the 44th Amendment's dual-condition requirement (both a National Emergency AND an Election Commission certification) makes extending President's Rule beyond one year deliberately difficult, closing a loophole that had previously allowed indefinite extensions with only routine six-monthly parliamentary approval."})

upsc.append({"q":"Consider the following statements about the historical pattern of President's Rule imposition after major electoral shifts:\n1. In 1977, the Janata Party government imposed President's Rule in nine Congress-ruled states after the Congress's Lok Sabha defeat.\n2. In 1980, the returning Congress Party imposed President's Rule in nine states on a similar 'assembly no longer represents electorate' ground.\n3. The Bommai case propositions explicitly listed 'ruling party's massive Lok Sabha defeat' as a situation where President's Rule imposition would be proper, endorsing both the 1977 and 1980 episodes.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the Court's actual position — the Bommai case explicitly listed a ruling party's massive Lok Sabha defeat (citing 1977 and 1980 specifically) as an example of IMPROPER use of Article 356, not proper use, directly criticising both historical episodes. Statements 1 and 2 are correct."})

data = {"basic": basic, "intermediate": intermediate, "advanced": advanced, "upsc": upsc}

all_q = basic + intermediate + advanced + upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q),1))

chapter = {
    "id": "emergency_provisions",
    "title": "Emergency Provisions",
    "desc": "National Emergency, President's Rule, and Financial Emergency under Articles 352-360, their grounds, parliamentary approval, effects on Fundamental Rights and Centre-state relations, and the S.R. Bommai case guidelines on Article 356",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/polity_ch17_emergency_provisions_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
