import json

upsc = []

# ==================================================================
# CHAPTER: HUMAN DEVELOPMENT (NCERT XII Part 2, Ch.3) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Which one of the following statements about the emergence of 'human development' as a concept, per NCERT, is NOT correct?","o":["The First Human Development Report was published by the World Bank in 1985, predating the UNDP's involvement by five years","The First Human Development Report was published by the United Nations Development Programme (UNDP) in 1990","Human development was conceived partly as a response to the prevalent Western/euro-centric view of development as modernisation, industrialisation and affluence","The Human Development Report 1993 stated that 'development must be woven around people, not the people around development'"],"a":0,"e":"This statement is incorrect — NCERT explicitly attributes the First Human Development Report to the UNDP in 1990, not the World Bank in 1985; the UNDP has published the World Human Development Report annually ever since. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about India's Human Development Index (HDI) standing, per NCERT (UNDP 2005 data):\n1. India, with a population of over 1.09 billion, was ranked 127 among 172 countries of the world in terms of HDI.\n2. India's composite HDI value was 0.602, placing it in the group of countries showing 'medium human development'.\n3. NCERT raises no methodological concerns about the HDI approach, treating the UNDP's indicators and rankings as fully adequate for capturing India's developmental reality.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly notes 'some reservations have been expressed about the approach as well as indicators selected,' citing insensitivity to historical factors (colonisation, imperialism), socio-cultural factors and political factors as crucial but under-weighted in the HDI methodology. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about India's economic attainment indicators, per NCERT, is NOT correct?","o":["States like Uttar Pradesh, Bihar, Orissa and Madhya Pradesh had HIGHER per capita consumption expenditure than developed states like Punjab, Haryana, Kerala, Maharashtra and Gujarat","A few developed states like Maharashtra, Punjab, Haryana, Gujarat and Delhi had per capita income of more than Rs. 4,000 (at 1980-81 prices) per year","Poorer states like Uttar Pradesh, Bihar, Orissa, Madhya Pradesh, Assam and Jammu and Kashmir recorded per capita income of less than Rs. 2,000","States like Orissa and Bihar recorded more than 40 per cent of their population living below the poverty line"],"a":0,"e":"This statement is incorrect and reverses the actual data — NCERT states developed states like Punjab, Haryana, Kerala, Maharashtra and Gujarat had HIGHER per capita consumption expenditure (over Rs. 690/month) compared to poorer states like Uttar Pradesh, Bihar, Orissa and Madhya Pradesh (below Rs. 520/month), not the reverse. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about India's health indicators (1951-1999), per NCERT:\n1. Death rate declined from 25.1 per thousand in 1951 to 8.1 per thousand in 1999, and infant mortality declined from 148 per thousand to 70 during the same period.\n2. Life expectancy at birth increased from 37.1 to 62.3 years for males, and from 36.2 to 65.3 years for females, between 1951 and 1999.\n3. With the sole exception of Kerala, child sex ratio (0-6 age group) improved in all Indian states between successive censuses, with the most notable gains recorded in Haryana and Punjab.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual finding — with the exception of Kerala, child sex ratio DECLINED in all states, and this decline was most alarming in the developed states of Haryana and Punjab (below 800 female children per thousand males), not improved there. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (State, per NCERT's 2001 literacy data) with List-II (Approximate Literacy Feature) and select the correct answer using the code below.\nList-I:\nA. Kerala\nB. Bihar\nC. Mizoram\nD. India (national average)\nList-II:\n1. Overall literacy rate of approximately 65.4%, female literacy 54.16%\n2. Highest total literacy rate (90.92%) among Indian states\n3. Very low literacy rate (47.53%), among the lowest in the country\n4. Second-highest literacy rate (88.49%) among Indian states\nCodes:","o":["A-2, B-3, C-4, D-1","A-4, B-3, C-2, D-1","A-2, B-4, C-3, D-1","A-2, B-3, C-1, D-4"],"a":0,"e":"The correct match is A-2, B-3, C-4, D-1: Kerala had the highest state literacy (90.92%); Bihar had one of the lowest (47.53%); Mizoram was second-highest (88.49%); and India's national average was 65.4% (54.16% female)."})

upsc.append({"q":"Which one of the following statements about India's Human Development Index by state (Planning Commission, per NCERT), is NOT correct?","o":["Bihar had the highest composite HDI value (0.638) among the 15 major states, reflecting its strong performance on literacy indicators","Kerala topped the composite HDI value at 0.638, followed by Punjab (0.537), Tamil Nadu (0.531), Maharashtra (0.523) and Haryana (0.509)","States like Bihar (0.367), Assam (0.386), Uttar Pradesh (0.388), Madhya Pradesh (0.394) and Orissa (0.404) were at the bottom among the 15 major states","Kerala's high HDI ranking is attributed largely to its near-hundred-per-cent literacy (90.92 per cent) in 2001, and its narrow gender literacy gap (6.34 per cent, versus 26.75 per cent in Bihar)"],"a":0,"e":"This statement is incorrect and reverses the actual ranking — NCERT explicitly states Bihar had the LOWEST composite HDI value (0.367) among the 15 major states, not the highest; Kerala instead topped the list with 0.638. The other three statements are correct."})

upsc.append({"q":"Assertion (A): The Human Development Report 1993 emphasised the constructive role of 'Civil Societies' in bringing about peace and human development.\nReason (R): The report called on civil society to build opinion for reduced military expenditure, demobilisation of armed forces, and disarmament, particularly reduction of nuclear warheads by developed countries.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly links the 1993 report's emphasis on civil society's constructive role in peace and human development to the specific actions it called for: reduced military spending, demobilisation, and disarmament, especially nuclear disarmament by developed nations."})

upsc.append({"q":"Consider the following statements about the Neo-Malthusian critique of development discussed in NCERT:\n1. Neo-Malthusians, environmentalists and radical ecologists believe a proper balance between population and resources is necessary for a happy, peaceful social life.\n2. NCERT critiques this view by noting that resources are not a neutral category — their uneven social distribution matters more than their mere availability, since rich countries/people access large resource baskets while the poor find their resources shrinking.\n3. NCERT endorses the Neo-Malthusian view without qualification as the definitive explanation for global resource conflicts.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly presents a critical counter-argument to the Neo-Malthusian view, noting its 'intrinsic flaws' regarding the neutrality of resources and their unequal social distribution, rather than endorsing it without qualification. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about Mahatma Gandhi's views on development, as discussed in NCERT, is NOT correct?","o":["Gandhi enthusiastically endorsed rapid industrialisation as the surest path to restoring morality, spirituality and self-reliance in Indian society","Gandhi advocated austerity for the individual, trusteeship of social wealth, and non-violence as keys to attaining higher goals in individual and national life","Gandhi was apprehensive that industrialisation had institutionalised the loss of morality, spirituality, self-reliance, non-violence and mutual cooperation","Gandhi's views were echoed in later reports such as the Club of Rome's 'Limits to Growth' (1972) and the Brundtland Commission's 'Our Common Future' (1987)"],"a":0,"e":"This statement is incorrect and reverses Gandhi's actual position — NCERT explicitly describes Gandhi as 'quite apprehensive about the on-going development particularly the way industrialisation' had undermined morality and self-reliance, not that he enthusiastically endorsed rapid industrialisation. The other three statements are correct."})

upsc.append({"q":"Which one of the following is explicitly identified by NCERT as a report/publication that reinforced concerns similar to Gandhi's views on population, resources and development?\n1. The Club of Rome's 'Limits to Growth' (1972)\n2. Schumacher's 'Small is Beautiful' (1974)\n3. The Brundtland Commission's 'Our Common Future' (1987)\n4. The Rio Conference's 'Agenda-21 Report' (1993)\nWhich of the reports/publications listed above are correctly identified by NCERT?","o":["1, 2, 3 and 4","1 and 2 only","3 and 4 only","1, 2 and 3 only"],"a":0,"e":"NCERT explicitly lists all four — the Club of Rome's 'Limits to Growth' (1972), Schumacher's 'Small is Beautiful' (1974), the Brundtland Commission's 'Our Common Future' (1987), and the Rio Conference's Agenda-21 Report (1993) — as re-echoing Gandhi's concerns about the harmony and balance between population, resources and development."})

upsc.append({"q":"Consider the following statements about the definition of human development, per NCERT/UNDP:\n1. Human development is defined as a process of enlarging the range of people's choices, including opportunities for education, health care, income and empowerment.\n2. This definition explicitly covers the full range of human choices, from a sound physical environment to economic, social and political freedom.\n3. According to this definition, a rising Gross National Product (GNP) is, by itself, a sufficient and complete measure of human development.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly distinguishes human development from mere economic growth (GNP/per capita income), noting that impressive GDP performance can still 'belie' persistent poverty, deprivation, illiteracy and regional disparities; GNP alone is not treated as sufficient. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the three interrelated processes of 'declining capabilities' among the poor, as described by NCERT, is NOT correct?","o":["Economic capabilities decline due to a rigid, unchanging tax structure imposed uniformly on all income groups","Social capabilities decline due to displacement and the weakening of social ties (social capital)","Environmental capabilities decline due to pollution","Personal capabilities decline due to increasing incidence of diseases and accidents"],"a":0,"e":"This statement is incorrect — NCERT identifies the three declining capabilities as social (due to displacement/weakened social ties), environmental (due to pollution) and personal (due to disease/accidents) — a rigid tax structure is not one of the three categories NCERT describes. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "human_development",
    "title": "Human Development",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.3 'Human Development'): the emergence of human development as a concept distinct from Western/euro-centric development (UNDP Human Development Reports since 1990); India's HDI rank and value, and methodological reservations about it; indicators of economic attainment (per capita income, poverty), healthy life (mortality, life expectancy, child sex ratio) and social empowerment (literacy); state-wise HDI rankings in India; and the population-resource-development debate, including Neo-Malthusian views, Gandhi's philosophy of austerity and trusteeship, and related global reports (Limits to Growth, Small is Beautiful, Our Common Future, Agenda-21). A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat human development indices and India-specific socio-economic disparity in this depth.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch37_human_development_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
