import json

upsc = []

# ==================================================================
# CHAPTER: PLANNING AND SUSTAINABLE DEVELOPMENT (NCERT XII Part 2, Ch.9) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Consider the following statements about India's Five Year Plans, per NCERT:\n1. The First Five Year Plan was launched in 1951, covering 1951-52 to 1955-56.\n2. Two successive droughts (1965-66 and 1966-67) and the war with Pakistan in 1965 forced a 'plan holiday' covered by annual/rolling plans in 1966-67 and 1968-69.\n3. The Fifth Five Year Plan ran its full intended course without any early termination by the government.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly states the Fifth Five Year Plan (1974-75) was TERMINATED by the then government one year early, in 1977-78, not completed on its full original schedule. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about approaches to planning in India, per NCERT, is NOT correct?","o":["Sectoral planning refers exclusively to plans with an explicit spatial/regional perspective aimed at reducing imbalances between different areas of the country","Sectoral planning means formulating and implementing schemes aimed at developing various sectors of the economy such as agriculture, irrigation, manufacturing and power","Regional planning is necessitated by the uneven pattern of economic development over space, requiring planners to adopt a spatial perspective","'Target area' and 'target group' approaches were introduced by the Planning Commission to arrest accentuating regional and social disparities"],"a":0,"e":"This statement is incorrect and reverses the actual definitions — NCERT defines SECTORAL planning as focused on developing economic sectors (agriculture, irrigation, manufacturing, etc.), while REGIONAL planning is the one with the explicit spatial perspective aimed at reducing area-based imbalances. The other three statements are correct."})

upsc.append({"q":"Match List-I (Target Area/Group Programme, per NCERT) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Hill Area Development Programme\nB. Drought Prone Area Programme\nC. Small Farmers Development Agency (SFDA)\nD. Command Area Development Programme\nList-II:\n1. A target GROUP (not target area) programme example cited by NCERT\n2. Initiated during the Fifth Five Year Plan, covering 15 districts including hilly Uttar Pradesh, Assam hills, Darjiling and Nilgiri\n3. Initiated during the Fourth Five Year Plan, aimed at employment provision and productive asset creation in drought-affected regions\n4. A target area programme example alongside Desert Development and Hill Area Development programmes\nCodes:","o":["A-2, B-3, C-1, D-4","A-3, B-2, C-1, D-4","A-2, B-1, C-3, D-4","A-2, B-3, C-4, D-1"],"a":0,"e":"The correct match is A-2, B-3, C-1, D-4: the Hill Area Development Programme began in the Fifth Plan covering 15 named districts; the Drought Prone Area Programme began in the Fourth Plan; SFDA is a target group (not area) programme; and Command Area Development is cited as a target area programme."})

upsc.append({"q":"Which one of the following statements about the Hill Area Development Programme, per NCERT, is NOT correct?","o":["The National Committee on the Development of Backward Area (1981) recommended that all hill areas with height BELOW 200 m be treated as backward hill areas","The programme covered 15 districts including all hilly districts of Uttar Pradesh (present Uttaranchal), Mikir Hill and North Cachar hills of Assam, Darjiling district of West Bengal, and Nilgiri district of Tamil Nadu","The programmes aimed at harnessing indigenous resources through horticulture, plantation agriculture, animal husbandry, poultry, forestry and small-scale/village industry","Detailed plans for hill area development were drawn considering topographical, ecological, social and economic conditions"],"a":0,"e":"This statement is incorrect and reverses the actual criterion — NCERT states the 1981 National Committee recommended hill areas with height ABOVE 600 m (not below 200 m) and not covered under the tribal sub-plan be treated as backward hill areas. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Drought Prone Area Programme (DPAP), per NCERT:\n1. It was initiated during the Fourth Five Year Plan, initially emphasising labour-intensive civil works, later shifting to irrigation projects, land development, afforestation and rural infrastructure.\n2. The Irrigation Commission (1972) introduced the criterion of 30 per cent irrigated area to demarcate drought-prone areas.\n3. Drought-prone areas of Punjab, Haryana and north Rajasthan are largely UNPROTECTED from drought despite extensive irrigation development in these regions.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly states the drought-prone areas of Punjab, Haryana and north Rajasthan are largely PROTECTED due to the spread of irrigation in these regions, not left unprotected. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the Bharmaur Integrated Tribal Development Project (ITDP) case study, per NCERT, is NOT correct?","o":["Bharmaur's female literacy rate declined from 42.83 per cent in 1971 to 1.88 per cent in 2001, reflecting the failure of the ITDP","Bharmaur, in Chamba district of Himachal Pradesh, is the homeland of the 'Gaddi' tribal community, who practised transhumance and spoke the Gaddiali dialect","Bharmaur was designated one of five Integrated Tribal Development Projects in Himachal Pradesh under the Fifth Five Year Plan's tribal sub-plan (1974)","Infrastructural development benefits under the ITDP were concentrated mainly in villages along the river Ravi in Holi and Khani areas, while remote Tundah and Kugti areas remained under-served"],"a":0,"e":"This statement is incorrect and reverses the actual trend — NCERT explicitly states Bharmaur's female literacy rate INCREASED from 1.88 per cent in 1971 to 42.83 per cent in 2001, a major social benefit of the ITDP, not a decline. The other three statements are correct."})

upsc.append({"q":"Assertion (A): The declining importance of pastoralism in Bharmaur's economy is evident from the fact that only about one-tenth of households now practise transhumance.\nReason (R): Despite this decline, the Gaddis remain highly mobile, with a sizeable section migrating seasonally to Kangra and surrounding areas for wage labour during winter.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true, but R does not explain A — NCERT presents both facts as parallel, complementary observations (declining traditional transhumance alongside continued, but differently-motivated, seasonal wage-labour migration), rather than R being the causal explanation for the decline in transhumance described in A."})

upsc.append({"q":"Which one of the following statements about the evolving definition of 'development', per NCERT, is NOT correct?","o":["In the immediate post-World War II era, development was understood exclusively in terms of well-being and living standards, with GNP considered an irrelevant measure from the very beginning","In the post-World War II era, development was initially synonymous with economic growth, measured through GNP and per capita income/consumption","By the 1970s, phrases like 'redistribution with growth' and 'growth and equity' were incorporated into the definition, in response to rising poverty despite economic growth","By the 1980s, development had emerged as a concept encapsulating widespread improvement in both social and material well-being of all in society"],"a":0,"e":"This statement is incorrect and reverses the actual chronology — NCERT explicitly states development was INITIALLY (post-WWII) synonymous with economic growth (GNP-based), and only LATER (1970s-1980s) expanded to include equity, well-being and social dimensions — GNP was not considered irrelevant from the outset. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Brundtland Report ('Our Common Future', 1987), per NCERT, is NOT correct?","o":["The report was prepared by a commission headed by the British Prime Minister and defines sustainable development in terms of maximising present GNP growth regardless of future needs","The World Commission on Environment and Development (WCED) was headed by the Norwegian Prime Minister, Gro Harlem Brundtland","The report defines sustainable development as 'development that meets the needs of the present without compromising the ability of future generations to meet their own needs'","The notion of sustainable development emerged from a general rise in environmental awareness in the late 1960s, influenced by works like Ehrlich's 'The Population Bomb' (1968) and Meadows' 'The Limits to Growth' (1972)"],"a":0,"e":"This statement is incorrect on two counts — the WCED was headed by the NORWEGIAN (not British) Prime Minister Gro Harlem Brundtland, and the report's actual definition emphasises balancing present needs with NOT compromising future generations' ability to meet theirs, not simply maximising present GNP growth. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Indira Gandhi Canal (previously Rajasthan Canal), per NCERT:\n1. Conceived by Kanwar Sain in 1948, the canal project was launched on 31 March 1958, originating at Harike barrage in Punjab and running parallel to the Pakistan border through the Thar Desert.\n2. Intensive irrigation under the project has led to twin environmental problems of water logging and soil salinity, despite initially boosting agricultural and livestock productivity.\n3. Traditional crops like gram, bajra and jowar have been largely replaced by more water-intensive crops like wheat, cotton, groundnut and rice due to canal irrigation.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's account of the canal's origin, its dual positive-and-negative ecological impact, and the resulting shift in cropping pattern toward more water-intensive crops."})

upsc.append({"q":"According to NCERT's seven proposed measures for promoting sustainable development in the Indira Gandhi Canal Command Area, which one of the following is correctly identified as NOT among these measures?","o":["Abandoning the warabandi system entirely in favour of unregulated, first-come-first-served water distribution among farmers","Strict implementation of water management policy distinguishing protective irrigation (Stage-I) from extensive irrigation (Stage-II)","Discouraging water-intensive crops in favour of plantation crops such as citrus fruits","Eco-development through afforestation, shelterbelt plantation and pasture development, particularly in the fragile Stage-II environment"],"a":0,"e":"This is NOT among NCERT's measures — the text explicitly recommends STRENGTHENING the warabandi system (equal distribution of canal water in the command area of an outlet) as part of CAD programmes to reduce conveyance loss, not abandoning it for unregulated distribution. The other three are genuine measures listed by NCERT."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "planning_and_sustainable_development",
    "title": "Planning and Sustainable Development",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.9 'Planning and Sustainable Development in Indian Context'): India's Five Year Plan history; sectoral vs. regional planning; target area/target group programmes (Hill Area Development, Drought Prone Area Programme) with the Bharmaur ITDP case study; the evolving concept of 'development' from post-WWII economic growth to 1980s social well-being; the emergence of 'sustainable development' and the Brundtland Report; and the Indira Gandhi Canal Command Area case study on measures for sustainable development. A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India-specific planning history and sustainable development case studies.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch39_planning_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
