import json

upsc = []

# ==================================================================
# CHAPTER: GEOGRAPHICAL PERSPECTIVE ON SELECTED ISSUES (NCERT XII Part 2, Ch.12) - standalone, final NCERT-only chapter
# ==================================================================

upsc.append({"q":"Which one of the following statements about the four broad types of environmental pollution, per NCERT, is NOT correct?","o":["Land pollution is caused primarily by combustion of coal, petrol and diesel, and industrial processes, sources that NCERT instead attributes to air pollution","Water pollution involves pollutants such as ammonia, nitrates, heavy metals and radioactive substances, sourced from sewage disposal, urban run-off and toxic industrial effluents","Air pollution involves oxides of sulphur and nitrogen, carbon monoxide, hydrocarbons and lead, sourced from combustion of fossil fuels and industrial processes","Noise pollution is caused by aircraft, automobiles, trains, industrial processing and advertising media, and is measured in decibels (dB)"],"a":0,"e":"This statement is incorrect and misattributes the sources — NCERT attributes fuel-combustion and industrial-process sources specifically to AIR pollution, while land pollution's sources are listed as human/animal excreta, improper disposal of untreated industrial waste, and pesticide/fertiliser use. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about pollution of the Ganga and Yamuna rivers, per NCERT's Table 12.2:\n1. Polluted stretches of the Ganga include downstream of Kanpur, downstream of Varanasi, and the Farakka Barrage, with pollution from industrial sources (Kanpur), domestic waste from urban centres, and carcass dumping.\n2. Yamuna pollution is attributed to extraction of water by Haryana and Uttar Pradesh for irrigation, agricultural run-off, and domestic/industrial waste from Delhi.\n3. Cities identified by NCERT as releasing domestic waste into the Ganga include Kanpur, Allahabad, Varanasi, Patna and Kolkata.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's Table 12.2 breakdown of polluted stretches, pollution sources and polluting cities for both the Ganga and Yamuna rivers."})

upsc.append({"q":"Which one of the following statements about water-borne disease and pollution in India, per NCERT, is NOT correct?","o":["The World Health Organisation's data shows that water-borne diseases account for a negligible proportion (under 5 per cent) of India's communicable diseases","Diseases commonly caused by contaminated water include diarrhoea, intestinal worms and hepatitis","Almost all surface water sources in India are contaminated and unfit for human consumption, per NCERT's assessment","Chemicals used in modern agriculture, such as inorganic fertilisers, pesticides and herbicides, wash down into rivers, lakes and tanks and also infiltrate the soil to reach groundwater"],"a":0,"e":"This statement is incorrect — NCERT explicitly states about ONE-FOURTH of the communicable diseases in India are water-borne (per WHO data), not a negligible under-5-per-cent share. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about urban solid waste disposal in India, per NCERT:\n1. In metropolitan cities like Mumbai, Kolkata, Chennai and Bangalore, about 90 per cent of solid waste is collected and disposed of.\n2. In most other cities and towns in the country, about 30 to 50 per cent of generated waste is left uncollected, accumulating in streets and open spaces.\n3. NCERT recommends that untreated wastes should be left to ferment naturally, since this process poses no risk of releasing harmful gases to the atmosphere.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly warns that untreated wastes 'ferment slowly and release toxic biogas to the atmosphere, including methane,' and recommends treating waste as a resource for energy/compost generation, not leaving it to ferment naturally. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about noise pollution, per NCERT, is NOT correct?","o":["Noise pollution intensity increases with increasing distance from its source, such as industrial areas, transportation arteries and airports","Traffic is identified as the biggest nuisance among noise pollution sources, with intensity depending on factors like vehicle/aircraft type and road/vehicle condition","In sea traffic, noise pollution is confined mainly to the harbour, due to loading and unloading activities","The level of steady noise is measured in terms of decibels (dB)"],"a":0,"e":"This statement is incorrect and reverses the actual relationship — NCERT explicitly states noise pollution is location-specific and its intensity DECLINES (not increases) with increasing distance from the source. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about India's urban population and rural-urban migration, per NCERT:\n1. India had a predominance of rural population (approximately 72 per cent of the total population in 2001).\n2. Globally, an estimated two-thirds of the world's population is projected to live in urban areas by 2050.\n3. In India, it is estimated that after 1961, urban growth has been attributed roughly equally to natural increase and rural-to-urban migration, with migration contributing about 29 per cent.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's figures on India's rural population share (2001), the global urbanisation projection for 2050, and the roughly 60%/29% natural-increase-versus-migration split in India's post-1961 urban growth (the remainder attributed to reclassification)."})

upsc.append({"q":"Which one of the following statements about the rural-urban migration case study of Ramesh (a contract welder), per NCERT, is NOT correct?","o":["Ramesh's family enjoyed a comfortable, debt-free standard of living even before his migration, and he migrated purely to seek adventure rather than economic necessity","Ramesh was influenced by successful out-migrants from his village who worked in Ludhiana and supported their families by sending money and consumer goods","Ramesh's family was highly in debt with three brothers' families surviving on three acres of land, prompting his decision to migrate","Because his job as a welder is temporary and transferable, Ramesh cannot bring his family with him and bears the pain of separation from his loved ones"],"a":0,"e":"This statement is incorrect and reverses the actual account — NCERT explicitly describes Ramesh's family as passing through 'very tough times' due to abject poverty and heavy debt before his migration, not as comfortable or debt-free; his migration was driven by economic necessity, not adventure-seeking. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about slums in India, per NCERT and the Dharavi case study, is NOT correct?","o":["Dharavi, described as Asia's largest slum, produces only low-value, unskilled goods with no market beyond the immediate neighbourhood","Slums are characterised by dilapidated housing, poor hygienic conditions, overcrowding, and lack of basic amenities like drinking water and toilet facilities","Dharavi produces delicate ceramics, embroidery, leather goods, high-fashion garments and jewellery settings that find their way into some of the richest houses in India and abroad","Slum populations often work in low-paid, high-risk, unorganised sectors of the urban economy and are vulnerable to undernourishment, disease, and social exclusion"],"a":0,"e":"This statement is incorrect and reverses the actual account — the Seabrook excerpt cited by NCERT explicitly describes Dharavi as producing 'some of the most beautiful, valuable and useful articles in India,' including high-fashion garments and fine jewellery destined for wealthy households, not merely low-value goods with no wider market. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about land degradation and wasteland classification in India, per NCERT (NRSA data):\n1. Wastelands caused primarily by natural agents include gullied/ravinous land, desertic/coastal sands, barren rocky areas and glacial areas.\n2. Wastelands caused primarily by human action include degraded shifting cultivation areas, degraded forests, degraded pastures, and mining/industrial wastelands.\n3. NCERT's data (Table 12.3) shows that wastelands caused by natural processes are quantitatively more significant than those caused by man-made processes in India.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual conclusion — the text explicitly states Table 12.3 indicates wastelands caused by MAN-MADE processes are MORE important (quantitatively significant) than those from natural processes, not the reverse. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): The Jhabua watershed management case study is presented by NCERT as a successful example of land degradation reversal.\nReason (R): The Bhils in Petlawad block (Sat Rundi hamlet) revitalised common property resources through household tree-planting, fodder-grass cultivation, and 'social fencing' of pasture lands against open grazing, resolving an encroachment conflict by incorporating the encroacher into their user group.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT presents the Jhabua case as successful precisely because of the specific community-driven actions described: tree-planting, fodder cultivation, social fencing, and the innovative resolution of the encroachment dispute by making the encroacher a benefit-sharing member of the user group."})

upsc.append({"q":"Which one of the following statements about Jhabua district, per NCERT, is NOT correct?","o":["Jhabua is one of the most economically prosperous and least resource-degraded districts in Madhya Pradesh, with minimal tribal population","Jhabua is located in the westernmost agro-climatic zone of Madhya Pradesh and is one of the five most backward districts of the country","Jhabua has a high concentration of tribal population, mostly Bhils, who suffer from poverty accentuated by high rates of forest and land resource degradation","Watershed management programmes funded by the Ministries of Rural Development and Agriculture have been successfully implemented in Jhabua, treating 20 per cent of the district's total area over five years (per the Rajiv Gandhi Mission for Watershed Management)"],"a":0,"e":"This statement is incorrect and reverses the actual description — NCERT explicitly describes Jhabua as one of the five MOST BACKWARD districts in the country, with high tribal concentration and significant resource degradation, not as economically prosperous with minimal tribal population. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "geographical_perspective_selected_issues",
    "title": "Geographical Perspective on Selected Issues",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.12 'Geographical Perspective on Selected Issues and Problems'): the four types of environmental pollution (air, water, land, noise) and their sources; pollution of the Ganga and Yamuna rivers; urban solid waste disposal; rural-urban migration case study; the problem of slums including the Dharavi case study; and land degradation, wasteland classification (NRSA), and the Jhabua watershed management case study. A standalone, concluding NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat these India-specific contemporary geographical issues.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch41_selected_issues_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
