import json

upsc = []

# ==================================================================
# SECTION 1: GROUPS OF INDUSTRIES & FACTORS OF LOCATION
# ==================================================================

upsc.append({"q":"Which one of the following statements about factors of industrial location, per Goh Cheng Leong, is NOT correct?","o":["A cheap and abundant labour force is always a locational advantage, regardless of its skill level or efficiency","No single factor decides the location of an industry; factors are complementary and often offset one another","Modern industries require a wide variety of raw materials, and not all can be sourced locally, making imports necessary","Coalfields remain major industrial areas today partly due to industrial inertia, even though coal is no longer as decisive a locational factor as before"],"a":0,"e":"This statement is incorrect and reverses the text's actual point — it explicitly states a cheap, abundant labour force is NOT always a locational advantage unless the labour is also efficient, since low output or inefficiency can offset the cost saving. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about industrial fuel/power as a locational factor, per Goh Cheng Leong:\n1. In the early Industrial Revolution, roughly twelve tonnes of coal were needed to smelt one tonne of iron ore, making coalfield locations almost indisputable.\n2. With improved fuel efficiency requiring only about one tonne of coal per tonne of iron smelted, coal's pull on location weakened, yet many industries remained at their original coalfield sites.\n3. Petroleum-producing regions like the Middle East and Venezuela have historically become major manufacturing centres precisely because of their abundant oil supply.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual point — the text explicitly states petroleum is seldom a factor of industrial location, and regions like the Middle East and Venezuela have FEW manufacturing industries despite abundant oil. Statements 1 and 2 are correct."})

upsc.append({"q":"According to Goh Cheng Leong, what specific term describes the phenomenon whereby industries remain at their traditional sites even after the original locational advantage (such as coal) has diminished in importance?","o":["Industrial inertia","Industrial decentralization","Industrial dispersal","Footloose industry"],"a":0,"e":"The text explicitly names this phenomenon 'industrial inertia' — explained by the built-up skilled labour force and the huge expense of relocating communications, workshops and worker housing to a new site, not decentralization, dispersal, or footloose industry (a term describing industries with no strong locational pull at all)."})

# ==================================================================
# SECTION 2: PROPERTIES OF IRON/STEEL, TYPES OF ORE, STEELMAKING
# ==================================================================

upsc.append({"q":"Match List-I (Type of Iron Ore) with List-II (Characteristic, per Goh Cheng Leong) and select the correct answer using the code below.\nList-I:\nA. Magnetite\nB. Haematite\nC. Limonite\nD. Siderite\nList-II:\n1. Low-grade residual ore with 20-30% metallic content, e.g. in Cleveland Hills and Lorraine\n2. Richest ore (70% metallic content), black, of igneous origin, e.g. Kiruna, Sweden\n3. Commonest commercially workable ore, brown, sometimes called 'bog iron ore'\n4. High-grade sedimentary ore (50-65% content), reddish, e.g. Lake Superior\nCodes:","o":["A-2, B-4, C-3, D-1","A-2, B-3, C-4, D-1","A-4, B-2, C-3, D-1","A-2, B-4, C-1, D-3"],"a":0,"e":"The correct match is A-2, B-4, C-3, D-1: magnetite is the richest, igneous-origin ore (Kiruna); haematite is high-grade and sedimentary (Lake Superior); limonite is the commonest workable, brown 'bog iron ore'; and siderite is the lowest-grade residual ore (Cleveland Hills, Lorraine)."})

upsc.append({"q":"Which one of the following statements about steelmaking processes, per Goh Cheng Leong, is NOT correct?","o":["The original Bessemer acid process, invented in 1856, effectively removes phosphorus impurities from pig iron, making it suitable for phosphorus-rich ores","The basic Bessemer or Gilchrist-Thomas process (1878) was specifically developed to remove phosphorus and sulphur impurities that the original Bessemer process could not remove","The open-hearth (Martin-Siemens) process is slower (about 12 hours) but produces high-quality steel and can use scrap iron","The oxygen process uses a high-pressure jet of oxygen rather than air, produces excellent steel in about an hour, and accounts for about 75% of Japan's steel output"],"a":0,"e":"This statement is incorrect and reverses the actual limitation — the text explicitly states the ORIGINAL Bessemer process does NOT remove phosphorus impurities, which is precisely why the basic Bessemer (Gilchrist-Thomas) process was later invented in 1878 to address this gap. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about iron/steel alloying, per Goh Cheng Leong:\n1. Alloying iron with chromium retards rusting, as in stainless steel used for cutlery.\n2. Alloying iron with vanadium improves its magnetic qualities, useful for high-speed cutting tools.\n3. Alloying iron with manganese makes it tougher, suitable for manufacturing steam rollers.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect and misattributes the effect — the text states COBALT (not vanadium) improves iron's magnetic qualities for high-speed cutting tools, while vanadium instead makes iron highly resilient, useful for springs. Statements 1 and 3 are correct."})

# ==================================================================
# SECTION 3: LOCATIONAL HISTORY AND WORLD DISTRIBUTION OF IRON/STEEL
# ==================================================================

upsc.append({"q":"Consider the following statements about the changing historical location of the world's iron and steel industry, per Goh Cheng Leong:\n1. In the earliest phase (15th century), iron-making yards were sited near forests and hillsides, using wood, wind (for hillside 'blast') and water.\n2. In the 18th century, the industry moved to coalfields when smelting required about 8 tonnes of coal per tonne of iron.\n3. By the late 19th century, with improved efficiency (1 tonne of coal per tonne of iron), the industry moved back permanently to forested regions rather than to ore-fields.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that by the late 19th century, with the coalfield pull weakened, the industry moved to ORE-FIELDS (e.g., Lorraine, Cleveland Hills, the Urals), not back to forested regions, which had been abandoned in the earlier coalfield-migration phase. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about world iron ore and steel production (1977 data), per Goh Cheng Leong, is NOT correct?","o":["India was, at the time, the world's largest producer of both iron ore and crude steel, surpassing the U.S.S.R. and the U.S.A.","The U.S.S.R. led the world in both iron ore production (27%) and steel production (22% in 1977)","India produced 5.5% of the world's iron ore, mainly haematite from Bihar and Orissa, feeding steelworks at Jamshedpur, Durgapur, Rourkela and Bhilai","Japan's own iron ore (from Kamaishi and Kutchan) supplied only about a tenth of her industrial needs, forcing heavy dependence on imports and scrap"],"a":0,"e":"This statement is incorrect — the text clearly identifies the U.S.S.R. and the U.S.A. as the world's two leading producers of both iron ore and steel, with India producing only 5.5% of world iron ore — India was never described as the world's largest producer of either. The other three statements are correct."})

upsc.append({"q":"Assertion (A): Japan is one of the world's most industrialized countries for iron and steel despite having very little domestic iron ore or coal.\nReason (R): Japan's coastal steel mill locations (e.g., Yokohama, Kobe, Yawata) facilitate the import of raw materials from countries such as the Philippines and Australia.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — Goh Cheng Leong explicitly attributes Japan's steel success, despite meagre domestic ore/coal, to coastal mill locations that facilitate importing ore from the Philippines, Australia and elsewhere, since her own mines at Kamaishi/Kutchan supply barely a tenth of her needs."})

# ==================================================================
# SECTION 4: NCERT — INDIA'S INTEGRATED STEEL PLANTS, COTTON TEXTILE, SUGAR
# ==================================================================

upsc.append({"q":"Match List-I (Indian Integrated Steel Plant) with List-II (Distinguishing Feature, per NCERT) and select the correct answer using the code below.\nList-I:\nA. Visvesvaraiya Iron and Steel Works (VISL)\nB. TISCO\nC. Bhilai Steel Plant\nD. Vizag Steel Plant\nList-II:\n1. India's oldest private-sector plant, near the Mumbai-Kolkata railway line, using Subarnarekha/Kharkai river water\n2. Located near Kemangundi in the Bababudan Hills, has no local coal and switched to Jog Falls hydroelectricity\n3. Set up with Russian collaboration in Chhattisgarh, using Dalli-Rajhara iron ore and Korba coal\n4. India's first port-based integrated steel plant, at Vishakhapatnam\nCodes:","o":["A-2, B-1, C-3, D-4","A-1, B-2, C-3, D-4","A-2, B-1, C-4, D-3","A-2, B-3, C-1, D-4"],"a":0,"e":"The correct match is A-2, B-1, C-3, D-4: VISL lacks local coal and uses Jog Falls hydel power; TISCO is India's oldest private-sector plant; Bhilai was built with Russian collaboration using Dalli-Rajhara ore; and Vizag is India's first port-based integrated plant."})

upsc.append({"q":"Consider the following statements about India's Second-Five-Year-Plan-era public sector steel plants, per NCERT — entirely new content not found in Goh Cheng Leong:\n1. Rourkela, Bhilai and Durgapur were all set up in the 1956-61 period under Hindustan Steel Limited, later absorbed into the Steel Authority of India Limited (SAIL) in 1973.\n2. Rourkela was built in collaboration with Germany, Bhilai with the U.S.S.R., and Durgapur with the United Kingdom.\n3. The Bokaro Steel Plant forms a 'Bokaro-Rourkela combine', where wagons carry iron ore one way and coal the other.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's account of the three Second-Plan-era collaborations, their respective foreign partners, and the Bokaro-Rourkela wagon-exchange arrangement."})

upsc.append({"q":"Which one of the following statements about the cotton textile industry in India, per NCERT, is NOT correct?","o":["Because cotton is a weight-losing raw material like iron ore, Indian cotton mills have always been located strictly at the site of cotton cultivation, never elsewhere","India's first modern cotton mill was established in Mumbai in 1854, aided by proximity to cotton-growing regions, port facilities, capital availability and abundant labour","By 2000, the decentralised sector (powerlooms and handlooms) produced the overwhelming majority of India's cotton cloth, while the organised mill sector's share had fallen to about 6%","Tamil Nadu's rapid cotton textile growth, especially around Coimbatore, was driven substantially by the availability of abundant hydel power rather than local cotton supply alone"],"a":0,"e":"This statement is incorrect and reverses the actual fact — NCERT explicitly states cotton is a 'PURE' (non-weight-losing) raw material, unlike iron ore, so mill location was instead driven by market, labour cost, or power availability rather than being tied strictly to cotton-growing areas. The other three statements are correct."})

upsc.append({"q":"Assertion (A): The sugar industry in India requires factories to be located very close to sugarcane-growing fields.\nReason (R): Sugarcane's sucrose content begins to degrade rapidly after harvesting, and better sugar recovery depends on crushing the cane within 24 hours.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly links sugar factories' proximity to cane fields to sugarcane being a weight-losing crop whose sucrose content deteriorates during haulage, making 24-hour crushing essential for good sugar recovery, a much tighter raw-material constraint than for cotton textiles."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "manufacturing_industry_and_iron_steel",
    "title": "Manufacturing Industry and The Iron and Steel Industry",
    "desc": "Human/economic geography (from Goh Cheng Leong's Physical and Human Geography, Ch.28, and NCERT XII 'India: People and Economy', Ch.8 'Manufacturing Industries'): the eight groups of manufacturing industry; factors of industrial location (raw materials, power, transport, market, human resources, capital, other factors) and industrial inertia; iron/steel ore types, properties, alloying and steelmaking processes (Bessemer, Gilchrist-Thomas, open-hearth, electric, oxygen); the historical shift in iron-and-steel location (forests to coalfields to ore-fields to coastal sites) and world production distribution; merged with NCERT's India-specific integrated steel plants (TISCO, IISCO, VISL, Rourkela, Bhilai, Durgapur, Bokaro, Vizag, Vijaynagar, Salem) and the cotton textile and sugar industries",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch28_manufacturing_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
