import json

upsc = []

# ==================================================================
# CHAPTER: INTERNATIONAL TRADE (NCERT XII Part 2, Ch.11) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Consider the following statements about the changing composition of India's exports (1997-98 to 2003-04), per NCERT:\n1. The share of agriculture and allied products in exports declined continuously over this period.\n2. The share of manufactured goods showed a continuous, uninterrupted increase throughout this period, reaching its highest share in 2003-04.\n3. The share of petroleum and crude products in exports increased, partly due to rising petroleum prices and India's increased refining capacity.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — NCERT's data shows manufactured goods' export share rose from 75.83% (1997-98) to a peak of 80.93% (1999-2000), then DECLINED to 77.9% (2000-01) and 75.96% (2003-04), not a continuous increase to its highest point in 2003-04. Statements 1 and 3 are correct."})

upsc.append({"q":"Which one of the following statements about India's export commodity trends, per NCERT, is NOT correct?","o":["Traditional agricultural export items like coffee, spices, tea and pulses have shown strong, sustained growth due to reduced international competition","There has been an increase in exports of floricultural products, fresh fruits, marine products and sugar","Manufacturing sector alone accounted for 75.96 per cent of India's total export value in 2003-04, with engineering goods showing significant growth","China and other East Asian countries are major competitors to India's textile sector, which could not achieve much despite liberal government measures"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual point — the text explicitly states there has been a DECLINE in exports of traditional agricultural items like coffee, spices, tea and pulses, due to tough international competition, not sustained growth. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the changing composition of India's imports, per NCERT:\n1. During the 1950s and 1960s, India's major imports were foodgrain, capital goods, machinery and equipment, due to serious food shortages.\n2. After the 1970s, foodgrain imports were discontinued due to the success of the Green Revolution, but the 1973 energy crisis pushed up petroleum import costs.\n3. Petroleum crude and products showed a steady DECLINE as a share of India's imports from 1997-98 to 2003-04, reflecting reduced dependence on imported fuel.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual trend — NCERT's data shows petroleum crude and products' import share INCREASED sharply, from 19.68% (1997-98) to 31.32% (2000-01) and 26.32% (2003-04), reflecting a steep rise, not a steady decline. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Trade Partner/Region, 2004-05, per NCERT) with List-II (Trade Feature) and select the correct answer using the code below.\nList-I:\nA. Asia and Oceania\nB. West Europe\nC. U.S.A.\nD. America (region)\nList-II:\n1. India's single largest trading partner and most important export destination\n2. Region accounting for 47.41% of India's exports and 35.40% of its imports\n3. Region accounting for 23.80% of India's exports\n4. Region accounting for 20.42% of India's exports\nCodes:","o":["A-2, B-3, C-1, D-4","A-3, B-2, C-1, D-4","A-2, B-1, C-3, D-4","A-2, B-3, C-4, D-1"],"a":0,"e":"The correct match is A-2, B-3, C-1, D-4: Asia and Oceania accounted for the largest export/import shares; West Europe took 23.80% of exports; the U.S.A. was India's single largest trading partner; and the broader America region took 20.42% of exports."})

upsc.append({"q":"Which one of the following statements about Indian ports, per NCERT, is NOT correct?","o":["India's east coast has significantly more seaports than its west coast, a pattern dating back to ancient times","India has 12 major ports and 185 minor or intermediate ports, with the 12 major ports handling about 75 per cent of the country's oceanic traffic","Major ports are regulated by the central government, while minor ports are regulated by state governments","Partition deprived India of two important ports — Karachi (to Pakistan) and Chittagong (to erstwhile East Pakistan, now Bangladesh)"],"a":0,"e":"This statement is incorrect and reverses the actual pattern — NCERT explicitly notes it is an 'interesting fact' that India's WEST coast has MORE seaports than its east coast, not the reverse. The other three statements are correct."})

upsc.append({"q":"Match List-I (Indian Port, per NCERT) with List-II (Distinguishing Description) and select the correct answer using the code below.\nList-I:\nA. Kandla Port\nB. Marmagao Port\nC. Kochchi Port\nD. Paradwip Port\nList-II:\n1. Natural harbour in Goa that gained significance after 1961 remodelling to handle iron-ore exports to Japan\n2. Located at the head of the Gulf of Kuchchh, designed to receive large quantities of petroleum and fertiliser\n3. Situated at the head of Vembanad Kayal, popularly called the 'Queen of the Arabian Sea', close to the Suez-Colombo route\n4. Situated in the Mahanadi delta with the deepest harbour, developed mainly for large-scale iron-ore export\nCodes:","o":["A-2, B-1, C-3, D-4","A-1, B-2, C-3, D-4","A-2, B-3, C-1, D-4","A-2, B-1, C-4, D-3"],"a":0,"e":"The correct match is A-2, B-1, C-3, D-4: Kandla receives petroleum/fertiliser at the Gulf of Kuchchh; Marmagao is Goa's natural harbour remodelled for iron-ore export to Japan; Kochchi is the 'Queen of the Arabian Sea' near the Suez-Colombo route; and Paradwip has the deepest harbour for iron-ore export."})

upsc.append({"q":"Which one of the following statements about Mumbai and Kolkata ports, per NCERT, is NOT correct?","o":["Kolkata port has GAINED increasing importance over time due to the diversion of exports away from other eastern ports such as Vishakhapatnam and Paradwip toward Kolkata","Mumbai is a natural harbour and the biggest port of the country, with M.P., Maharashtra, Gujarat, U.P. and parts of Rajasthan as its hinterland","Jawaharlal Nehru Port at Nhava Sheva was developed as a satellite port to relieve pressure at Mumbai port and is India's largest container port","Kolkata port faces the problem of silt accumulation in the Hugli river, which provides its link to the sea"],"a":0,"e":"This statement is incorrect and reverses the actual trend — NCERT explicitly states Kolkata port has LOST significance considerably due to the diversion of exports to OTHER ports like Vishakhapatnam, Paradwip and its own satellite port Haldia, not gained increasing importance. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about air transport in India's international trade, per NCERT:\n1. Air transport has the advantage of taking the least time for carriage and handling of high-value or perishable goods over long distances.\n2. Air transport is very costly and unsuitable for carrying heavy and bulky commodities, which reduces its participation in international trade compared to oceanic routes.\n3. India has 12 international airports and 112 domestic airports functioning in the country.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's description of air transport's speed advantage, its cost/bulk limitations, and the count of India's international and domestic airports."})

upsc.append({"q":"Assertion (A): India's trade deficit has increased over recent years despite a rise in total export volume.\nReason (R): This increase in deficit is attributed to the price rise of crude petroleum, which forms a major component of India's import list.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly attributes the rising trade deficit, despite growing import/export volumes, specifically to the price rise of crude petroleum, a major and growing component of India's import basket, directly linking the two."})

upsc.append({"q":"Which one of the following statements about the historical development of Indian ports, per NCERT, is NOT correct?","o":["The emergence of ports as gateways of international trade became important only after Independence in 1947, with no significant colonial-era role for ports in trade","The British used Indian ports as suction points to extract resources from their hinterlands, with railway extension linking local, regional, national and international markets","New ports such as Kandla (west) and Diamond Harbour near Kolkata (east) were developed to compensate for the loss of Karachi and Chittagong after Partition","India's port capacity increased from 20 million tonnes of cargo handling in 1951 to more than 500 million tonnes at present"],"a":0,"e":"This statement is incorrect and reverses the actual chronology — NCERT explicitly states the emergence of ports as gateways of international trade became important AFTER the coming of European traders and British colonisation, not only after 1947; the colonial period was central to this development. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about Chennai and its satellite ports, per NCERT, is NOT correct?","o":["Chennai Port is a natural harbour that requires no dredging and is highly suitable for the world's largest modern container ships","Chennai Port is one of the oldest ports on the eastern coast, an artificial harbour built in 1859","Ennore, developed 25 km north of Chennai, was constructed to relieve pressure at Chennai port","Tuticorin Port was developed to relieve the pressure of Chennai port and deals with a variety of cargo including coal, salt, foodgrains and petroleum products"],"a":0,"e":"This statement is incorrect and reverses the actual description — NCERT explicitly describes Chennai as an ARTIFICIAL harbour (built in 1859) that is 'not much suitable for large ships because of the shallow waters near the coast,' not a natural harbour ideal for the largest vessels. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about India's overall trade profile, per NCERT:\n1. India's external trade was worth Rs. 12,140 million in 1950-51, rising to Rs. 8,371,330 million in 2004-05.\n2. Although India's contribution to world trade volume is as low as about 1 per cent, it still plays a significant role in the world economy.\n3. Reasons for the sharp rise in India's overseas trade include momentum in the manufacturing sector, liberal government policies, and diversification of markets.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's figures on the growth of India's external trade value and its explanation of the reasons behind this sharp rise despite India's still-small share of world trade volume."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "international_trade",
    "title": "International Trade",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.11 'International Trade'): the changing volume, composition and direction of India's foreign trade; changing export commodity composition (agriculture, manufactured goods, petroleum) and import composition (foodgrain to petroleum/capital goods); India's major trading partners and regional trade direction; sea ports as gateways of trade (major/minor ports, hinterlands, and profiles of Kandla, Mumbai, JNPT, Marmagao, New Mangalore, Kochchi, Kolkata, Haldia, Paradwip, Vishakhapatnam, Chennai, Ennore, Tuticorin); and air transport's role in trade. A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India-specific trade statistics and port profiles.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch40_intl_trade_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
