import json

upsc = []

# ==================================================================
# CHAPTER: NATURAL VEGETATION - INDIA (NCERT XI Part 2, Ch.5) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Which one of the following statements about Tropical Evergreen and Semi Evergreen Forests, per NCERT, is NOT correct?","o":["These forests are found in areas with annual precipitation below 100 cm and a mean annual temperature well under 22°C","They are found on the western slope of the Western Ghats, the hills of the northeastern region, and the Andaman and Nicobar Islands","In tropical evergreen forests, trees reach great heights up to 60 m or above, with no definite time for shedding leaves, so the forests appear green all year round","Semi evergreen forests occur in the less rainy parts of these regions and have a mixture of evergreen and moist deciduous trees"],"a":0,"e":"This statement is incorrect and reverses the actual figures — NCERT states these forests occur in areas with annual precipitation OVER 200 cm and mean annual temperature ABOVE 22°C, not below 100 cm and under 22°C. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about Tropical Deciduous (Monsoon) Forests, per NCERT:\n1. These are the most widespread forests in India, found in regions receiving rainfall between 70-200 cm.\n2. Moist deciduous forests, more pronounced where rainfall is 100-200 cm, are found in the northeastern states, eastern slopes of the Western Ghats, and Orissa.\n3. Dry deciduous forests, found where rainfall ranges between 70-100 cm, transition to thorn forests on their drier margins and to moist deciduous forests on their wetter margins.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's rainfall-based classification of tropical deciduous forests into moist and dry types and their respective transition zones."})

upsc.append({"q":"Match List-I (Forest Type, per NCERT) with List-II (Characteristic Region/Feature) and select the correct answer using the code below.\nList-I:\nA. Tropical Thorn Forests\nB. Montane Forests (Himalayan)\nC. Southern Montane Forests\nD. Littoral and Swamp Forests\nList-II:\n1. Called 'Sholas' in the Nilgiri, Anaimalai and Palani hills\n2. Occur in areas receiving less than 50 cm rainfall, e.g. semi-arid Punjab, Haryana, Rajasthan\n3. Include mangrove forests spread over 6,740 sq. km, highly developed in the Sunderbans and Andaman-Nicobar\n4. Show a succession from tropical to tundra vegetation with increasing altitude\nCodes:","o":["A-2, B-4, C-1, D-3","A-4, B-2, C-1, D-3","A-2, B-1, C-4, D-3","A-2, B-4, C-3, D-1"],"a":0,"e":"The correct match is A-2, B-4, C-1, D-3: tropical thorn forests occur in low-rainfall semi-arid areas; Himalayan montane forests show tropical-to-tundra succession with altitude; southern montane (temperate) forests are called Sholas; and littoral/swamp forests include mangroves concentrated in the Sunderbans and Andaman-Nicobar Islands."})

upsc.append({"q":"Which one of the following statements about wetlands and mangrove forests in India, per NCERT, is NOT correct?","o":["India's mangrove forests spread over 6,740 sq. km, which is 7 per cent of the world's mangrove forests, and are being expanded rapidly with no conservation concerns","Two sites, Chilika Lake (Orissa) and Keoladeo National Park (Bharatpur), are protected as waterfowl habitats under the Ramsar Convention","India's wetlands have been grouped into eight categories, including the saline expanses of Rajasthan/Gujarat/Gulf of Kachchh and the delta wetlands of the east coast","Besides the Sunderbans, other significant mangrove areas include the Mahanadi, Godavari and Krishna deltas"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual concern — the text explicitly states these mangrove forests 'are being encroached upon, and hence, need conservation,' not that they are expanding without concern. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about forest area and forest cover in India, per NCERT:\n1. Forest area is the area notified and recorded as forest land irrespective of the actual existence of trees, based on State Revenue Department records, while forest cover is the area actually occupied by forests with canopy, based on aerial photographs and satellite imagery.\n2. According to state records, forest area covers 23.28% of India's total land area, while the actual forest cover (2001) was only 20.55%.\n3. Lakshadweep has zero per cent forest area, while Andaman and Nicobar Islands have 86.93 per cent.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's distinction between recorded forest area and actual satellite-derived forest cover, the national percentages for each, and the extreme state-wise variation between Lakshadweep and the Andaman and Nicobar Islands."})

upsc.append({"q":"Assertion (A): The Government of India's forest policy (1952, modified 1988) aimed at bringing 33 per cent of the geographical area under forest cover.\nReason (R): This target was set specifically because it represents the minimum forest-cover threshold NCERT identifies as necessary for maintaining ecological balance, with 15 states already having forest cover exceeding one-third of their area.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly states that forest cover of more than one-third of the total area is 'the basic requirement for maintaining the ecological balance,' directly matching the 33% target of the forest policy, and notes that 15 states already met this threshold."})

upsc.append({"q":"Which one of the following statements about Social Forestry, as classified by the National Commission on Agriculture (1976) per NCERT, is NOT correct?","o":["Agro-forestry refers exclusively to raising trees on public or community land such as village pastures and temple land, roadside and canal banks","Urban forestry pertains to raising and managing trees on public and privately owned lands in and around urban centres, such as green belts and roadside avenues","Community forestry involves raising trees on public/community land and specifically benefits landless classes who can associate themselves in tree-raising","Farm forestry refers to farmers growing trees for commercial and non-commercial purposes on their own farm lands"],"a":0,"e":"This statement is incorrect and reverses the actual definitions — agro-forestry is defined as raising TREES AND AGRICULTURAL CROPS ON THE SAME LAND (a form of rural forestry), while raising trees on public/community land like village pastures and temple land is the definition of COMMUNITY forestry, not agro-forestry. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about wildlife conservation in India, per NCERT:\n1. The comprehensive Wildlife Act was enacted in 1972 and was further amended in 1991 to make punishments more stringent.\n2. India has 92 National Parks and 492 wildlife sanctuaries covering an area of 15.67 million hectares.\n3. Project Tiger, launched in 1973, has seen the number of tiger reserves increase from an initial nine (covering 16,339 sq. km) to 27 reserves (37,761 sq. km) across 17 states, with the tiger population rising from 1,827 (1972) to 3,642 (2001-02).\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's account of the Wildlife Act's enactment and 1991 amendment, the current count of protected areas, and Project Tiger's documented expansion in reserves, area and tiger population."})

upsc.append({"q":"Match List-I (Biosphere Reserve, per NCERT) with List-II (Distinguishing Feature) and select the correct answer using the code below.\nList-I:\nA. Nilgiri Biosphere Reserve\nB. Nanda Devi Biosphere Reserve\nC. Sunderbans Biosphere Reserve\nD. Gulf of Mannar Biosphere Reserve\nList-II:\n1. Home of nearly 200 Royal Bengal tigers, in the swampy delta of the river Ganga in West Bengal\n2. India's first biosphere reserve, established September 1986, covering Wyanad, Nagarhole, Bandipur and Mudumalai\n3. Located in Uttaranchal, includes parts of Chamoli, Almora, Pithoragarh and Bageshwar districts, with predominantly temperate forest types\n4. Covers 21 islands with estuaries, coral reefs and mangroves, home to the globally endangered dugong (sea cow)\nCodes:","o":["A-2, B-3, C-1, D-4","A-3, B-2, C-1, D-4","A-2, B-3, C-4, D-1","A-2, B-1, C-3, D-4"],"a":0,"e":"The correct match is A-2, B-3, C-1, D-4: Nilgiri was India's first biosphere reserve (1986); Nanda Devi lies in Uttaranchal with temperate forests; Sunderbans hosts nearly 200 Royal Bengal tigers; and the Gulf of Mannar reserve covers 21 islands with dugong habitat."})

upsc.append({"q":"Which one of the following statements about India's tribal population and forests, per NCERT, is NOT correct?","o":["Out of a total of 593 districts, 187 (2001) have been identified as tribal districts, and these districts account for less than 10 per cent of the total geographical area of the country","Forests provide tribal people with food, fruits, edible leaves, honey, nourishing roots and wild game, and materials for their houses, agricultural implements and household articles","The age-old knowledge of tribals regarding forestry can be used in the management and conservation of forests","Tribal people can be made growers of minor forest produce and encouraged to participate in conservation"],"a":0,"e":"This statement is incorrect — NCERT states the 187 tribal districts (2001) account for about 59.8 per cent of the country's forest cover while forming only 33.6 per cent of its total geographical area, not less than 10 per cent — demonstrating a disproportionately high concentration of forest cover in tribal districts. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "natural_vegetation_india",
    "title": "Natural Vegetation (India)",
    "desc": "Indian physical geography (from NCERT XI Part 2 'India: Physical Environment', Ch.5 'Natural Vegetation'): classification of Indian forests (tropical evergreen/semi-evergreen, tropical deciduous, tropical thorn, montane, littoral and swamp); wetlands, mangroves and the Ramsar Convention; forest area vs. forest cover; India's forest conservation policy (1952/1988) and social forestry (urban, rural/agro/community, farm); wildlife conservation, the Wildlife Act (1972/1991), Project Tiger and Project Elephant; and India's Biosphere Reserves (Nilgiri, Nanda Devi, Sunderbans, Gulf of Mannar, and others). A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India's specific vegetation and conservation regime in this depth.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch33_vegetation_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
