import json

upsc = []

# ==================================================================
# CHAPTER: SOILS - INDIA (NCERT XI Part 2, Ch.6) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Which one of the following statements about the soil profile, per NCERT, is NOT correct?","o":["Horizon C is a transition zone containing matter derived from both Horizon A and the parent rock, with noticeably weathered mineral matter","Horizon A is the topmost zone, where organic materials have combined with mineral matter, nutrients and water necessary for plant growth","Horizon B is a transition zone between Horizon A and Horizon C, containing some organic matter along with weathered mineral matter","Underneath the three horizons lies the parent rock or bedrock, and Horizon C is composed of loose parent material, the first stage of soil formation"],"a":0,"e":"This statement is incorrect and misattributes the description — NCERT describes HORIZON B (not Horizon C) as the transition zone containing matter from both above and below with weathered mineral matter; Horizon C is instead the loose parent material layer, the first stage of soil formation. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the history of Indian soil classification, per NCERT:\n1. In ancient times, soils were classified into two main groups, Urvara and Usara, meaning fertile and sterile respectively.\n2. In the 16th century A.D., soils were classified based on inherent characteristics and external features such as texture, colour, slope of land and moisture content.\n3. The Soil Survey of India was established in 1956, and the ICAR later classified Indian soils per the United States Department of Agriculture (USDA) Soil Taxonomy.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's account of the ancient Urvara/Usara classification, the 16th-century texture/colour-based classification, and the modern institutional (Soil Survey of India, ICAR/USDA taxonomy) classification efforts."})

upsc.append({"q":"Which one of the following statements about Alluvial Soils, per NCERT, is NOT correct?","o":["Khadar, the older alluvium deposited away from flood plains, is more fertile than Bhangar, the newer alluvium enriched by annual floods","Alluvial soils are depositional soils, transported and deposited by rivers and streams, covering about 40 per cent of the total area of the country","In the Upper and Middle Ganga plain, two types of alluvial soil have developed: Khadar (new alluvium, deposited annually by floods) and Bhangar (older alluvium, deposited away from flood plains)","Both Khadar and Bhangar soils contain calcareous concretions known as 'Kankars'"],"a":0,"e":"This statement is incorrect and reverses the actual definitions — Khadar is explicitly the NEWER alluvium (enriched annually by floods with fine silt deposits), while Bhangar is the OLDER alluvium deposited away from the flood plains; the statement swaps which is 'newer' and inaccurately claims Khadar is older and less fertile. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about Black Soil (Regur/Black Cotton Soil), per NCERT:\n1. Black soil is generally clayey, deep and impermeable, swelling and becoming sticky when wet and shrinking and developing cracks when dry — a process called 'self-ploughing'.\n2. Black soils are chemically rich in lime, iron, magnesia, alumina and potash but lack phosphorous, nitrogen and organic matter.\n3. Because of its slow absorption and loss of moisture, black soil retains moisture for a long time, which helps rain-fed crops sustain through the dry season.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's description of black soil's self-ploughing swelling/shrinking behaviour, its chemical composition, and its moisture-retention advantage for rain-fed cultivation."})

upsc.append({"q":"Match List-I (Soil Type, per NCERT) with List-II (Distinguishing Characteristic) and select the correct answer using the code below.\nList-I:\nA. Laterite Soil\nB. Arid Soil\nC. Saline Soil (Usara)\nD. Peaty Soil\nList-II:\n1. Contains a large proportion of sodium, potassium and magnesium; infertile and unable to support vegetative growth\n2. Results from intense leaching due to tropical rains; rich in iron oxide and aluminium but poor in humus, nitrogen and phosphate\n3. Found in areas of heavy rainfall/high humidity; organic matter content may reach 40-50 per cent\n4. Sandy in structure and saline in nature; lower horizons have 'kankar' layers restricting water infiltration\nCodes:","o":["A-2, B-4, C-1, D-3","A-4, B-2, C-1, D-3","A-2, B-1, C-4, D-3","A-2, B-4, C-3, D-1"],"a":0,"e":"The correct match is A-2, B-4, C-1, D-3: laterite soil results from tropical leaching; arid soil is sandy with kankar-restricted infiltration; saline (Usara) soil is infertile due to high sodium/potassium/magnesium; and peaty soil has very high organic matter content."})

upsc.append({"q":"Which one of the following statements about Laterite Soil, per NCERT, is NOT correct?","o":["Laterite soils are naturally rich in humus, nitrogen, phosphate and calcium, making them among the most fertile soils in India without needing any fertiliser application","The word 'laterite' derives from the Latin word 'later', meaning brick, and these soils develop under high temperature and high rainfall conditions","With rain, lime and silica are leached away, leaving behind soils rich in iron oxide and aluminium compounds","Red laterite soils in Tamil Nadu, Andhra Pradesh and Kerala are more suitable for tree crops like cashewnut"],"a":0,"e":"This statement is incorrect and reverses the actual characterisation — NCERT explicitly states laterite soils are POOR in organic matter, nitrogen, phosphate and calcium (while iron oxide and potash are in excess), making them generally unsuitable for cultivation unless manures and fertilisers are applied. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about Red and Yellow Soils and Forest Soils, per NCERT:\n1. Red soil develops on crystalline igneous rocks in areas of low rainfall in the eastern and southern Deccan Plateau, appearing reddish due to iron diffusion and yellow when hydrated.\n2. Fine-grained red and yellow soils are normally fertile, whereas coarse-grained soils in dry upland areas are poor in fertility.\n3. Forest soils are uniform in structure and texture everywhere they occur, regardless of the mountain environment, and are always highly fertile at all elevations.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly states forest soils VARY in structure and texture depending on the mountain environment (loamy/silty on valley sides, coarse-grained on upper slopes), with soils in snow-bound Himalayan areas being acidic with low humus, while only lower-valley soils are fertile — not uniform or universally fertile. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): A fairly large area of arable land in India's irrigated zones is becoming saline.\nReason (R): Over-irrigation combined with a dry climate promotes capillary action, which brings salt up from the lower soil profile and deposits it on the top layer, a problem especially seen in areas that benefited first from the Green Revolution, such as Punjab and Haryana.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly attributes the growing salinity of irrigated arable land to over-irrigation's capillary action bringing salts to the surface under dry climatic conditions, a problem NCERT specifically notes in Green-Revolution command areas like Punjab and Haryana, where gypsum application is advised as a remedy."})

upsc.append({"q":"Which one of the following statements about soil erosion in India, per NCERT, is NOT correct?","o":["Sheet erosion is more damaging and visually obvious than gully erosion, since it strips away large, clearly visible chunks of land in a single event","Gully erosion is common on steep slopes, and a region with a large number of deep gullies or ravines is called a 'badland topography', widespread in the Chambal basin","Sheet erosion occurs on level lands after a heavy shower and removes the soil in a manner that is not easily noticeable, yet it removes the finer, more fertile top soil","India loses about 8,000 hectares of land to ravines every year"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual point — sheet erosion is explicitly harmful precisely because the soil removal is NOT easily noticeable (it quietly strips the fertile top soil), unlike the more visually dramatic gully erosion; it is not described as more visible or damaging than gully erosion. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about soil conservation measures in India, per NCERT:\n1. Lands with a slope gradient of 15-25 per cent should not be used for cultivation unless carefully terraced.\n2. The Central Arid Zone Research Institute (CAZRI) has experimented with stabilising sand dunes in western Rajasthan.\n3. Contour bunding, contour terracing, controlled grazing, cover cropping, mixed farming and crop rotation are remedial measures adopted to reduce soil erosion.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's discussion of slope-based cultivation restrictions, CAZRI's sand-dune stabilisation experiments in western Rajasthan, and the listed remedial measures for soil erosion control."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "soils_india",
    "title": "Soils (India)",
    "desc": "Indian physical geography (from NCERT XI Part 2 'India: Physical Environment', Ch.6 'Soils'): the soil profile (Horizons A, B, C) and factors of soil formation; the history of Indian soil classification (Urvara/Usara, 16th-century texture-based, modern ICAR/USDA taxonomy); the eight major Indian soil types (Alluvial, Black/Regur, Red and Yellow, Laterite, Arid, Saline/Usara, Peaty, Forest) with their genesis, chemical properties and distribution; soil degradation and erosion (sheet, gully, badland topography); and soil conservation measures (contour bunding/terracing, CAZRI's sand-dune work, gully control). A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India's specific soil taxonomy in this depth.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch34_soils_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
