import json

upsc = []

# ==================================================================
# CHAPTER: NATURAL HAZARDS AND DISASTERS (NCERT XI Part 2, Ch.7) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Which one of the following statements distinguishing 'natural hazards' from 'natural disasters', per NCERT, is NOT correct?","o":["Natural hazards and natural disasters are entirely synonymous terms with no meaningful distinction between them","Natural hazards are elements/circumstances in the natural environment with the potential to cause harm to people or property, such as ocean currents or unstable structural features in the Himalayas","Compared to natural hazards, natural disasters are relatively sudden and cause large-scale, widespread death, loss of property and disturbance to social systems","Any event can be classed as a disaster when the magnitude of destruction and damage caused by it is very high"],"a":0,"e":"This statement is incorrect — NCERT explicitly notes that though scholars often use 'disasters' and 'natural hazards' interchangeably, they are 'related phenomena, yet quite distinct from each other,' and it is necessary to distinguish between them, not treat them as synonymous. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Yokohama Strategy and Plan of Action for a Safer World, per NCERT:\n1. It was adopted at the World Conference on Natural Disaster Reduction held in Yokohama in May 1994.\n2. It declared the decade 1990-2000 as the International Decade for Natural Disaster Reduction (IDNDR).\n3. It explicitly rejected the idea that individual countries have sovereign responsibility for protecting their citizens from natural disasters, instead placing this responsibility solely on the United Nations.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual resolution — the Yokohama conference explicitly affirmed that 'each country has the sovereign responsibility to protect its citizens from natural disasters,' not that this responsibility rests solely with the UN. Statements 1 and 2 are correct."})

upsc.append({"q":"Match List-I (Category of Natural Disaster, per NCERT's four-category classification) with List-II (Example) and select the correct answer using the code below.\nList-I:\nA. Atmospheric\nB. Terrestrial\nC. Aquatic\nD. Biological\nList-II:\n1. Landslides, volcanic eruptions, avalanches, subsidence\n2. Insect infestations, plant/animal colonisers (locusts), fungal/bacterial/viral diseases like bird flu\n3. Floods, tidal waves, ocean currents, tsunami\n4. Blizzards, thunderstorms, tornadoes, tropical cyclones, drought\nCodes:","o":["A-4, B-1, C-3, D-2","A-1, B-4, C-3, D-2","A-4, B-1, C-2, D-3","A-4, B-3, C-1, D-2"],"a":0,"e":"The correct match is A-4, B-1, C-3, D-2: atmospheric disasters include blizzards and cyclones; terrestrial disasters include landslides and volcanic eruptions; aquatic disasters include floods and tsunamis; and biological disasters include insect infestations and diseases like bird flu."})

upsc.append({"q":"Which one of the following statements about earthquakes in India, per NCERT, is NOT correct?","o":["India has been divided into five earthquake zones based on damage risk, and the stable, mature Peninsular/Deccan plateau landmass is generally considered the most vulnerable of all these zones","The Indian plate's northward/northeastward movement at about one centimetre per year, obstructed by the Eurasian plate, causes energy build-up and eventual release along the Himalayan arch","Central-western India, particularly Gujarat (1819, 1956, 2001) and Maharashtra (1967, 1993), has also experienced severe earthquakes despite being part of an old, stable landmass","A fault line along the river Bhima (Krishna) near Latur and Osmanabad (Maharashtra) has been proposed by some earth scientists to explain earthquakes in the stable Peninsular block"],"a":0,"e":"This statement is incorrect and reverses the actual finding — NCERT explicitly states that most areas of the stable Deccan/Peninsular plateau are considered SAFE (low risk), not the most vulnerable zone; the Himalayan region and areas like Kachchh (Gujarat) are instead classified in the very high damage risk zone. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about tsunamis, per NCERT:\n1. Tsunamis are caused by earthquakes or volcanic eruptions that cause the sea-floor to move abruptly, resulting in sudden displacement of ocean water as high vertical waves.\n2. Over deep water, a tsunami wave has a very long wavelength and limited wave-height, raising a ship only a metre or two, whereas in shallow water the wavelength reduces and wave-height can increase to 15 m or more.\n3. Because their impact is much greater in deep ocean water than near the coast, tsunamis are most dangerous to ships sailing far out at sea rather than to coastal populations.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly states the impact of a tsunami is LESS over the deep ocean and MORE near the coast, where large-scale devastation occurs; a ship at sea is not much affected by a tsunami. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): India volunteered to join the International Tsunami Warning System after 2004.\nReason (R): The 26 December 2004 tsunami, in which more than 300,000 people lost their lives across Indonesia, Sri Lanka, India and other countries, demonstrated that mitigating tsunami hazards is beyond the capacity of any individual state or government.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly links India's decision to join the International Tsunami Warning System to the scale of the 2004 tsunami disaster, which demonstrated that combined international-level efforts, rather than individual state action, are needed to deal with such hazards."})

upsc.append({"q":"Consider the following statements about tropical cyclones, per NCERT:\n1. Tropical cyclones are confined to the area between 30°N and 30°S latitudes and are energised by the release of latent heat from condensation of moisture gathered over oceans.\n2. The absence of Coriolis force near the equator (between 0°-5° latitude) prohibits the formation of tropical cyclones there, despite abundant warm moist air.\n3. In the Bay of Bengal, cyclones mostly develop during October-November, originating between 16°-20° N latitude, while by July the origin point shifts closer to the Sunderban Delta around 18°N.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's account of the latitudinal confinement and energy source of tropical cyclones, the Coriolis-force requirement excluding equatorial cyclone formation, and the seasonal shift in Bay-of-Bengal cyclone origin points."})

upsc.append({"q":"Which one of the following statements about floods in India, per NCERT, is NOT correct?","o":["Floods are entirely a natural phenomenon in India, with human activities playing no role whatsoever in their genesis or intensification","The Rashtriya Barh Ayog (National Flood Commission) identified 40 million hectares of land as flood-prone in India, with Assam, West Bengal and Bihar among the high flood-prone states","Floods can also bring positive contributions, such as depositing fertile silt over agricultural fields, as seen in Majuli (Assam), the world's largest riverine island","Indiscriminate deforestation, unscientific agricultural practices, and colonisation of flood-plains and river-beds are human activities that increase the intensity, magnitude and gravity of floods"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual point — the text explicitly states that, 'unlike other natural disasters,' human beings play an important role in both the genesis and spread of floods, through activities like deforestation and encroachment on flood-plains, not that floods are purely natural with no human role. The other three statements are correct."})

upsc.append({"q":"Match List-I (Type of Drought, per NCERT) with List-II (Defining Feature) and select the correct answer using the code below.\nList-I:\nA. Meteorological Drought\nB. Agricultural Drought\nC. Hydrological Drought\nD. Ecological Drought\nList-II:\n1. Low soil moisture necessary to support crops, leading to crop failures; excluded if over 30% of gross cropped area is irrigated\n2. Availability of water in aquifers, lakes and reservoirs falls below what precipitation can replenish\n3. A prolonged period of inadequate rainfall with mal-distribution over time and space\n4. Productivity of a natural ecosystem fails due to water shortage, causing ecological distress\nCodes:","o":["A-3, B-1, C-2, D-4","A-1, B-3, C-2, D-4","A-3, B-2, C-1, D-4","A-3, B-1, C-4, D-2"],"a":0,"e":"The correct match is A-3, B-1, C-2, D-4: meteorological drought is defined by inadequate/mal-distributed rainfall; agricultural drought by insufficient soil moisture for crops; hydrological drought by depleted water storages; and ecological drought by ecosystem productivity failure."})

upsc.append({"q":"Consider the following statements about drought-prone areas in India, per NCERT:\n1. Nearly 19 per cent of India's total geographical area and 12 per cent of its population suffer from drought every year, with about 30 per cent of the country's total area identified as drought-prone, affecting around 50 million people.\n2. The Extreme Drought Affected Area includes most of Rajasthan west of the Aravali hills (Marusthali) and the Kachchh region of Gujarat.\n3. Districts like Jaisalmer and Barmer, which receive less than 90 mm average annual rainfall, are classified in the Severe Drought Prone Area rather than the Extreme category.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT explicitly places Jaisalmer and Barmer, with their very low (under 90 mm) average annual rainfall, within the EXTREME drought-affected category, not the Severe category. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about landslides in India, per NCERT, is NOT correct?","o":["Landslides are largely controlled by macro or regional factors that make them as predictable and easy to monitor as earthquakes or cyclones","Landslides due to mining and subsidence are most common in states like Jharkhand, Orissa, Chhattisgarh, Madhya Pradesh, Maharashtra, Andhra Pradesh, Karnataka, Tamil Nadu, Goa and Kerala","The Very High Vulnerability Zone includes highly unstable, young mountainous areas in the Himalayas and Andaman-Nicobar, and high-rainfall, steep-slope regions in the Western Ghats and Nilgiris","Landslides have a relatively small and localised area of direct influence, but can still cause far-reaching consequences like roadblocks, railway destruction, and river-course diversions leading to floods"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual characterisation — the text explicitly states landslides are largely controlled by HIGHLY LOCALISED factors (unlike other disasters controlled by macro/regional factors), which is precisely why monitoring and predicting them is difficult and cost-intensive. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about disaster management, per NCERT:\n1. The Disaster Management Bill, 2005, defines a disaster as a catastrophe, mishap, calamity or grave occurrence arising from natural or man-made causes, or by accident or negligence.\n2. NCERT identifies three stages of disaster mitigation and management: pre-disaster management, actions during disasters, and post-disaster operations.\n3. Cyclone-related disasters are described by NCERT as generally less predictable in terms of time and place than earthquakes, tsunamis and volcanic eruptions.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly states cyclone-related disasters are MORE predictable in terms of time and place of occurrence compared to earthquakes, tsunamis and volcanic eruptions, thanks to monitoring techniques, not less predictable. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): Disaster mitigation measures have special significance for a country like India.\nReason (R): India has about two-thirds of its geographical area and an equal proportion of its population vulnerable to various natural disasters.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly states that disaster mitigation measures have special significance for India specifically because about two-thirds of its geographical area, and an equal proportion of its population, are vulnerable to disasters, directly justifying steps like the Disaster Management Bill, 2005, and the National Institute of Disaster Management."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "natural_hazards_and_disasters",
    "title": "Natural Hazards and Disasters",
    "desc": "Indian physical geography (from NCERT XI Part 2 'India: Physical Environment', Ch.7 'Natural Hazards and Disasters'): distinguishing natural hazards from disasters; the Yokohama Strategy and IDNDR; classification of natural disasters (atmospheric, terrestrial, aquatic, biological); earthquakes in India (zones, causes, mitigation); tsunamis (mechanism, 2004 Indian Ocean tsunami); tropical cyclones (structure, Bay of Bengal/Arabian Sea patterns); floods and the Rashtriya Barh Ayog; drought types and India's drought-prone zones; landslide vulnerability zones; and the three-stage disaster management framework plus the Disaster Management Bill, 2005. A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India-specific natural hazard classification and disaster management policy.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch35_hazards_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
