import json

upsc = []

# ==================================================================
# CHAPTER: WATER RESOURCES (NCERT XII Part 2, Ch.6) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Consider the following statements about India's water resources, per NCERT:\n1. India accounts for about 2.45 per cent of world's surface area, 4 per cent of the world's water resources, and about 16 per cent of the world's population.\n2. The total water available from precipitation in India in a year is about 4,000 cubic km, but only 1,869 cubic km is available from surface water and replenishable groundwater.\n3. Of the 1,869 cubic km available, 60 per cent can be put to beneficial use, making the total utilisable water resource in the country only 1,122 cubic km.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's figures on India's global share of area/water/population and its precipitation-to-utilisable-water resource chain."})

upsc.append({"q":"Which one of the following statements about surface water resources in India, per NCERT, is NOT correct?","o":["Due to topographical, hydrological and other constraints, almost all (about 95 per cent) of available surface water can actually be utilised","The Ganga, Brahmaputra and Barak river basins account for only about one-third of the country's total area but hold 60 per cent of the total surface water resources","Much of the annual water flow in south Indian rivers like the Godavari, Krishna and Kaveri has been harnessed, unlike the Brahmaputra and Ganga basins","There are about 10,360 rivers and their tributaries longer than 1.6 km each in the country"],"a":0,"e":"This statement is incorrect and reverses the actual figures — NCERT states only about 690 cubic km (32 per cent) of available surface water can actually be utilised, due to topographical/hydrological constraints, not almost 95 per cent. The other three statements are correct."})

upsc.append({"q":"Match List-I (River Basin, per NCERT's groundwater data) with List-II (Distinguishing Feature) and select the correct answer using the code below.\nList-I:\nA. Ganga and Brahmaputra basins (combined)\nB. Indus basin\nC. Brahmaputra basin (alone)\nD. Punjab, Haryana, Rajasthan and Tamil Nadu\nList-II:\n1. States/region with very high groundwater utilisation rates\n2. Hold about 46 per cent of the total replenishable groundwater resources\n3. Highest level of groundwater utilisation (77.71%) among basins in Table 6.1\n4. Lowest level of groundwater utilisation (3.37%) among basins in Table 6.1, despite large total resources\nCodes:","o":["A-2, B-3, C-4, D-1","A-2, B-4, C-3, D-1","A-3, B-2, C-4, D-1","A-2, B-3, C-1, D-4"],"a":0,"e":"The correct match is A-2, B-3, C-4, D-1: the Ganga-Brahmaputra basins together hold about 46% of replenishable groundwater; the Indus basin has the highest utilisation rate (77.71%); the Brahmaputra basin alone has the lowest utilisation rate (3.37%) despite large resources; and Punjab/Haryana/Rajasthan/Tamil Nadu are states with very high groundwater utilisation."})

upsc.append({"q":"Which one of the following statements about sectoral water usage in India, per NCERT, is NOT correct?","o":["The industrial sector accounts for the largest share of both surface water (89%) and groundwater (92%) utilisation in the country","Agriculture accounts for 89 per cent of surface water utilisation and 92 per cent of groundwater utilisation","The share of the domestic sector in surface water utilisation (9%) is higher than its share in groundwater utilisation","The shares of industrial and domestic sectors are expected to increase in the future with further development"],"a":0,"e":"This statement is incorrect and reverses the actual sectoral breakdown — NCERT explicitly states AGRICULTURE (not industry) accounts for the overwhelming majority of both surface water (89%) and groundwater (92%) usage in India, while industry's share is limited to only 2% of surface water and 5% of groundwater. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about groundwater over-exploitation in India, per NCERT:\n1. Over 85 per cent of net sown area in Punjab, Haryana and Western Uttar Pradesh is under irrigation, with 76.1 per cent of Punjab's net irrigated area irrigated through wells and tube wells.\n2. Over-withdrawal of groundwater in states like Rajasthan and Maharashtra has increased fluoride concentration in groundwater.\n3. Over-withdrawal has led to increased arsenic concentration in parts of West Bengal and Bihar.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's description of intensive well/tube-well irrigation in Punjab and the resulting groundwater contamination patterns (fluoride in Rajasthan/Maharashtra, arsenic in West Bengal/Bihar)."})

upsc.append({"q":"Which one of the following statements about water pollution in India, per NCERT, is NOT correct?","o":["The Yamuna river, throughout its entire course from its Himalayan source to its confluence, is the least polluted major river in the country","The Yamuna river is the most polluted river in the country between Delhi and Etawah","The Central Pollution Control Board (CPCB), in collaboration with State Pollution Control Boards, monitors water quality of national aquatic resources at 507 stations","Other severely polluted rivers include the Sabarmati at Ahmedabad, the Gomti at Lucknow, and the Ganga at Kanpur and Varanasi"],"a":0,"e":"This statement is incorrect and reverses the actual finding — NCERT explicitly identifies the Yamuna (specifically between Delhi and Etawah) as the MOST polluted river in the country, not the least polluted. The other three statements are correct."})

upsc.append({"q":"Assertion (A): Legislative provisions like the Water (Prevention and Control of Pollution) Act, 1974, and the Water Cess Act, 1977, have made only marginal impacts on reducing river pollution in India.\nReason (R): In 1997, 251 polluting industries were still located along rivers and lakes despite these legislative provisions being in place.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly cites the continued presence of 251 polluting industries along rivers/lakes in 1997 as evidence that the Water Act (1974) and Water Cess Act (1977) 'have not been implemented effectively' and made only marginal impact."})

upsc.append({"q":"Consider the following statements about watershed management and rainwater harvesting programmes in India, per NCERT:\n1. Haryali is a Central-Government-sponsored watershed development project executed by Gram Panchayats with people's participation.\n2. Neeru-Meeru ('Water and You') in Andhra Pradesh and Arvary Pani Sansad in Alwar, Rajasthan, have constructed water-harvesting structures like percolation tanks, Johads (dug-out ponds) and check dams.\n3. Rainwater harvesting structures in Rajasthan, locally known as Kund or Tanka, are always constructed as open, uncovered surface reservoirs to maximise evaporative cooling.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual description — the text explicitly describes a Kund or Tanka as a COVERED underground tank, not an open surface reservoir, precisely to reduce evaporation losses. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the Ralegan Siddhi watershed development success story, per NCERT, is NOT correct?","o":["The transformation of Ralegan Siddhi relied primarily on large-scale government financial aid, with minimal contribution from villagers' own voluntary labour","Voluntary labour was used to minimise dependence on government financial aid, described by the activist as 'socialising the costs of the projects'","The village banned open grazing, liquor distilling, and water-intensive crops like sugarcane, replacing them with low-water-requirement crops like pulses and oilseeds","A Rs. 22 lakh school building was constructed using only the resources of the village, without external donations"],"a":0,"e":"This statement is incorrect and reverses the actual account — NCERT explicitly emphasises that Ralegan Siddhi's transformation relied on VOLUNTARY LABOUR to minimise dependence on government financial aid, not on large-scale government funding. The other three statements are correct."})

upsc.append({"q":"According to the National Water Policy 2002, as cited by NCERT, what is the stipulated order of priority for water allocation?","o":["Drinking water; irrigation; hydro-power; navigation; industrial and other uses","Industrial use; irrigation; drinking water; hydro-power; navigation","Irrigation; drinking water; industrial use; hydro-power; navigation","Hydro-power; irrigation; drinking water; industrial use; navigation"],"a":0,"e":"NCERT explicitly states the National Water Policy 2002 stipulates water allocation priorities in the order: drinking water, irrigation, hydro-power, navigation, and industrial and other uses — with providing drinking water to all humans and animals as the first priority, not any of the other orderings."})

upsc.append({"q":"Consider the following statements about lagoons and backwaters as surface water sources in India, per NCERT:\n1. India's vast and, in some states, very indented coastline has led to the formation of numerous lagoons and lakes.\n2. States like Kerala, Orissa and West Bengal have vast surface water resources in such lagoons and lakes.\n3. Water in these lagoons and lakes is generally fresh (non-saline) and is used exclusively for drinking water supply, never for fishing or irrigation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual description — the text explicitly states water in these lagoons/lakes is generally BRACKISH, and is used for fishing and irrigating certain paddy/coconut varieties, not exclusively as fresh drinking water. Statements 1 and 2 are correct."})

upsc.append({"q":"Assertion (A): Multipurpose river valley projects like Bhakra-Nangal, Hirakud, Damodar Valley, Nagarjuna Sagar and the Indira Gandhi Canal Project have been prioritised in India's Five Year Plans.\nReason (R): India's water demand is currently dominated by irrigational needs, since about two-thirds of its population depends on agriculture and rainfall shows high spatio-temporal variability.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — NCERT explicitly links the high priority given to irrigation-focused multipurpose river valley projects to India's agrarian economy and irrigation-dominated water demand, driven by rainfall's spatio-temporal variability and the need for assured water in dry seasons."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "water_resources",
    "title": "Water Resources",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.6 'Water Resources'): India's surface water and groundwater endowment; basin-wise groundwater potential and utilisation; sectoral water demand (agriculture, industry, domestic); the Green Revolution's irrigation dependence and groundwater depletion/contamination; water quality deterioration and pollution of the Ganga/Yamuna; water conservation and management strategies (recycle/reuse, watershed management, rainwater harvesting) including case studies (Ralegan Siddhi, Haryali, Neeru-Meeru, Arvary Pani Sansad); and the National Water Policy 2002. A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India-specific water resource statistics and management policy.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch38_water_resources_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
