import json

upsc = []

# ==================================================================
# CHAPTER: MIGRATION (NCERT XII Part 2, Ch.2) - standalone NCERT-only chapter
# ==================================================================

upsc.append({"q":"Consider the following statements about historical waves of Indian emigration, per NCERT:\n1. During the colonial period, indentured labourers were sent from Uttar Pradesh and Bihar to Mauritius, the Caribbean islands, Fiji and South Africa under the Girmit Act (Indian Emigration Act).\n2. The Portuguese sent indentured labourers from Goa, Daman and Diu to Angola and Mozambique as plantation workers.\n3. The third wave of migrants, comprising professionals such as doctors, engineers, software engineers and financial experts, began flowing to countries like the USA, Canada, UK and Australia only after India's 1991 economic liberalisation, with no earlier professional emigration.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — NCERT dates the third wave of professional migration (doctors, engineers) from the 1960s onwards, with software engineers, management consultants and media persons joining from the 1980s onwards, predating the 1991 liberalisation, which instead intensified education/knowledge-based emigration further. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the recording of migration in the Census of India, per NCERT, is NOT correct?","o":["Migration data collection began only with the 1981 Census, when reasons for migration were first recorded alongside place of birth","Migration was first recorded in the 1881 Census, based on place of birth","The 1961 Census introduced two additional components: place of birth (village/town) and duration of residence if born elsewhere","In the 1971 Census, additional information on place of last residence and duration of stay at the place of enumeration was incorporated"],"a":0,"e":"This statement is incorrect — NCERT explicitly states migration was first recorded in the 1881 Census (based on place of birth), not first in 1981; the 1981 Census instead added the reasons-for-migration question to this decades-long-established recording practice. The other three statements are correct."})

upsc.append({"q":"Match List-I (Migration Concept, per NCERT) with List-II (Definition) and select the correct answer using the code below.\nList-I:\nA. Life-time migrant\nB. Migrant by place of last residence\nC. Rural-to-rural (R-R) stream\nD. Rural-to-urban (R-U) stream\nList-II:\n1. A person whose place of last residence differs from the place of enumeration\n2. Predominantly a male-dominated stream driven mainly by economic reasons\n3. A person whose place of birth differs from the place of enumeration\n4. Predominantly a female-dominated stream, mostly short-distance and marriage-related\nCodes:","o":["A-3, B-1, C-4, D-2","A-1, B-3, C-4, D-2","A-3, B-1, C-2, D-4","A-3, B-4, C-1, D-2"],"a":0,"e":"The correct match is A-3, B-1, C-4, D-2: a life-time migrant is defined by place of birth differing from enumeration place; a migrant by last residence is defined by last residence differing from enumeration place; rural-to-rural migration is female-dominated (largely marriage-related); and rural-to-urban migration is male-dominated (largely economic)."})

upsc.append({"q":"Consider the following statements about India's migration statistics (2001 Census), per NCERT:\n1. Out of 1,029 million people in the country, 307 million (30 per cent) were reported as migrants by place of birth, while 315 million (31 per cent) were migrants by place of last residence.\n2. Out of 315 million migrants by last residence, 98 million had changed residence in the preceding ten years, of which 81 million were intra-state migrants, a stream dominated by female migrants.\n3. Census 2001 recorded that more than 5 million persons migrated to India from other countries, with 96 per cent coming from neighbouring countries, led by Bangladesh, followed by Pakistan and Nepal.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's figures for lifetime vs. last-residence migrants, the intra-state migration breakdown, and the composition of international immigration into India."})

upsc.append({"q":"Which one of the following statements about spatial variation in India's internal migration, per NCERT, is NOT correct?","o":["Bihar recorded the largest number of net in-migrants among all Indian states, ahead of Maharashtra, Delhi and Gujarat","Maharashtra occupied the first place among states with 2.3 million net in-migrants, followed by Delhi, Gujarat and Haryana","Uttar Pradesh (-2.6 million) and Bihar (-1.7 million) were the states with the largest number of net out-migrants","Among urban agglomerations, Greater Mumbai received the highest number of in-migrants, with intra-state migration constituting the largest share"],"a":0,"e":"This statement is incorrect and reverses the actual data — NCERT explicitly identifies Bihar as one of the largest sources of NET OUT-migration (-1.7 million), not a state with the largest net in-migration; Maharashtra instead led with 2.3 million net in-migrants. The other three statements are correct."})

upsc.append({"q":"Assertion (A): Work and employment is the dominant reason for male migration in India (38 per cent), while marriage is the dominant reason for female migration (about 65 per cent).\nReason (R): In Meghalaya, this general pattern of female marriage migration is reversed compared to the rest of rural India.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true, but R does not explain A — NCERT presents Meghalaya's reversed marriage-migration pattern as a notable EXCEPTION to the general male-work/female-marriage migration pattern described in India overall, not as the reason why that general pattern exists elsewhere in the country."})

upsc.append({"q":"Consider the following statements about the economic consequences of migration, per NCERT:\n1. In 2002, India received US$ 11 billion as remittances from international migrants, with Punjab, Kerala and Tamil Nadu receiving very significant amounts.\n2. Migration from rural areas of Eastern Uttar Pradesh, Bihar, Madhya Pradesh and Orissa to rural Punjab, Haryana and Western Uttar Pradesh contributed to the success of the Green Revolution strategy.\n3. Remittances sent by internal migrants are far larger in absolute amount than those sent by international migrants, though both play important economic roles.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly states remittances from internal migrants are 'very meagre as compared to international migrants,' not larger, even though internal remittances still play an important role in the source area's economic growth. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the demographic and social consequences of migration, per NCERT, is NOT correct?","o":["Age and skill selective out-migration from rural areas has no measurable effect on the demographic structure of the source regions, since migrants are eventually replaced by natural population growth","High out-migration from Uttaranchal, Rajasthan, Madhya Pradesh and Eastern Maharashtra has brought serious imbalances in age and sex composition in these states","Migrants act as agents of social change, diffusing new ideas related to technology, family planning and girls' education from urban to rural areas","Migration can lead to social vacuum and a sense of dejection among individuals, sometimes motivating them toward anti-social activities like crime and drug abuse"],"a":0,"e":"This statement is incorrect and reverses NCERT's actual point — the text explicitly states age- and skill-selective out-migration DOES have adverse effects on rural demographic structure, citing serious imbalances in age and sex composition in states like Uttaranchal, Rajasthan, Madhya Pradesh and Eastern Maharashtra, not that it has no measurable effect. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about environmental consequences and the 'brain drain' cost of migration, per NCERT:\n1. Overcrowding due to rural-urban migration leads to unplanned growth of urban settlements, formation of slums, and problems like groundwater depletion and air pollution.\n2. The loss of highly skilled human resources through migration is described as the most serious cost from the point of view of the source region.\n3. NCERT states that the global market for advanced skills has led the most dynamic industrial economies to recruit significant proportions of highly trained professionals from poor regions, reinforcing underdevelopment there.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching NCERT's discussion of environmental degradation from urban overcrowding and the 'brain drain' cost of skilled emigration reinforcing source-region underdevelopment."})

upsc.append({"q":"According to NCERT's classification of causes of migration, which one of the following is correctly categorised as a 'pull factor' rather than a 'push factor'?","o":["Better opportunities, regular work availability and relatively higher wages in urban areas","High population pressure on land in the place of origin","Lack of basic infrastructural facilities like health care and education in the place of origin","Natural disasters such as floods, droughts, cyclonic storms and earthquakes in the place of origin"],"a":0,"e":"NCERT explicitly classifies better opportunities, regular work and higher wages as PULL factors (attracting migrants to a destination), whereas population pressure, lack of infrastructure, and natural disasters are all classified as PUSH factors (causing people to leave their place of origin)."})

upsc.append({"q":"Which one of the following statements about India's international migrants by neighbouring country of origin (2001 Census data), per NCERT, is NOT correct?","o":["Pakistan contributed the largest share of immigrants from neighbouring countries, ahead of Bangladesh and Nepal","Bangladesh contributed the largest single share (about 59.8 per cent) of immigrants from neighbouring countries","Pakistan contributed about 19.3 per cent and Nepal about 11.6 per cent of immigrants from neighbouring countries","Migration from neighbouring countries accounted for about 95.5 per cent of India's total international immigration"],"a":0,"e":"This statement is incorrect and reverses the actual ranking — NCERT's data shows Bangladesh contributed the largest share (about 59.8%) of neighbouring-country immigrants, well ahead of Pakistan (19.3%) and Nepal (11.6%), not the other way around. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Indian diaspora, per NCERT:\n1. It is estimated that there are around 20 million people of Indian Diaspora, spread across 110 countries.\n2. Education and knowledge-based Indian emigration after the 1990s liberalisation has made the Indian Diaspora one of the most powerful diasporas in the world.\n3. Indian migrants abroad, particularly the professional third wave, have played no significant role in the development of their host countries, remaining economically isolated communities.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses NCERT's actual point — the text explicitly states the Indian diaspora has been 'playing an important role in the development of the respective countries' where they have settled, not remaining economically isolated. Statements 1 and 2 are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"basic": [], "intermediate": [], "advanced": [], "upsc": upsc}

all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", {k: len(v) for k, v in data.items()})
print("total:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

chapter = {
    "id": "migration",
    "title": "Migration",
    "desc": "Indian human/economic geography (from NCERT XII Part 2 'India: People and Economy', Ch.2 'Migration: Types, Causes and Consequences'): historical waves of Indian emigration (indentured labour, professional/skilled diaspora); the Census of India's evolving migration questions since 1881; migration streams (R-R, R-U, U-U, U-R) and international immigration into India; spatial variation in net in-/out-migration; push and pull factors; and the economic, demographic, social and environmental consequences of migration, including remittances and 'brain drain'. A standalone NCERT-only chapter, since Goh Cheng Leong's world-geography textbook does not treat India-specific migration statistics and policy in this depth.",
    "questions": data
}

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/geo_ch36_migration_v2.json", "w") as f:
    json.dump(chapter, f, indent=2, ensure_ascii=False)

print("Saved.")
