#!/usr/bin/env python3
"""
generate_chapter.py
====================

End-to-end pipeline that turns a page range of a textbook PDF into a fresh,
UPSC-level-only chapter of questions for the UPSC Prep app
(https://dhananjay09.github.io/upsc-prep-app/), grouped into 10-question
tests, merged into subject_data.json, rebuilt into the app HTML files,
validated, and (optionally) committed and pushed to GitHub.

This is meant to be run locally, from inside your clone of the
upsc-prep-app repo, one chapter at a time.

--------------------------------------------------------------------------
SETUP (one-time)
--------------------------------------------------------------------------
1. Clone the repo and cd into it:
     git clone git@github.com:dhananjay09/upsc-prep-app.git
     cd upsc-prep-app

2. Install dependencies:
     pip install anthropic pymupdf --break-system-packages   # or in a venv
   You also need Node.js installed (used only to rebuild app/index.html
   and to sanity-check the rebuilt JavaScript).

3. Set your Anthropic API key:
     export ANTHROPIC_API_KEY="sk-ant-..."
   (Get one at https://console.anthropic.com if you don't have one.)

4. Make sure `git` can push to the repo without prompting (SSH key set up
   with GitHub, or a credential helper for HTTPS).

--------------------------------------------------------------------------
USAGE
--------------------------------------------------------------------------
Run from the repo root:

    python3 generate_chapter.py \
        --pdf "/path/to/textbook.pdf" \
        --start-page 49 --end-page 58 \
        --subject geography \
        --chapter-id weathering_mass_movement_groundwater \
        --chapter-title "Weathering, Mass Movement and Groundwater" \
        --source-dir source_material/goh_cheng_leong_geography

By default this commits AND PUSHES to origin when it finishes successfully.
Add --dry-run the first few times if you'd rather review locally before
pushing (open app/index.html in a browser to try the new chapter's quiz,
then re-run without --dry-run, or just `git push` yourself when happy).

Page numbers are 1-indexed exactly as your PDF viewer shows them
(e.g. if your PDF reader says "Page 49", pass --start-page 49). The
range is inclusive on both ends.

If --chapter-id is omitted, one is auto-generated by slugifying
--chapter-title. If a chapter with that id already exists in
subject_data.json for this subject, it will be REPLACED (useful for
regenerating/fixing a chapter).

If there's a matching title in the subject's "pending" list (exact,
case-insensitive match against --chapter-title, or pass --pending-title
to match a differently-worded pending entry), it is removed automatically.

Add --dry-run to do everything except commit/push (good for reviewing the
generated questions first — they land in subject_data.json locally, and
you can open app/index.html in a browser to try the quiz before pushing).

Add --no-rebuild if you only want the raw extracted text + generated
question JSON and want to handle merging yourself.

--------------------------------------------------------------------------
HOW QUESTION GENERATION WORKS
--------------------------------------------------------------------------
The script sends the extracted chapter text to Claude in batches, asking
for real UPSC-Prelims-level questions (statement-based, assertion-reason,
and match-the-following formats) that are strictly grounded in the
supplied text — no outside facts. It keeps asking for more batches,
each time telling the model what's already been asked (to avoid repeats),
until either a sensible cap is hit or the model signals the chapter's
content has been reasonably exhausted. Every returned question is
validated (exactly 4 options, valid answer index) and deduplicated
before being written out.

Expect somewhere between 35 and 70 questions for a typical chapter,
depending on how content-rich the source text is — thin chapters
naturally produce fewer good, non-repetitive questions.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from difflib import SequenceMatcher

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("Missing dependency 'pymupdf'. Install with: pip install pymupdf --break-system-packages")

try:
    import anthropic
except ImportError:
    sys.exit("Missing dependency 'anthropic'. Install with: pip install anthropic --break-system-packages")


# ==========================================================================
# 1. PDF TEXT EXTRACTION
# ==========================================================================

def extract_chapter_text(pdf_path, start_page_1indexed, end_page_1indexed):
    """Extract and lightly clean text from a page range of a PDF.

    Page numbers are 1-indexed and inclusive, matching what a normal PDF
    viewer displays.
    """
    doc = fitz.open(pdf_path)
    start_idx = start_page_1indexed - 1
    end_idx = end_page_1indexed - 1  # inclusive
    if start_idx < 0 or end_idx >= doc.page_count or start_idx > end_idx:
        sys.exit(f"Invalid page range {start_page_1indexed}-{end_page_1indexed} "
                  f"for a {doc.page_count}-page PDF.")

    text = ""
    for p in range(start_idx, end_idx + 1):
        text += doc.load_page(p).get_text() + "\n"

    # Strip bare page-number lines and collapse excess blank lines,
    # matching the cleanup used throughout this project.
    lines = text.split("\n")
    cleaned = [ln for ln in lines if not re.fullmatch(r"\d{1,4}\s*", ln)]
    text = "\n".join(cleaned)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# ==========================================================================
# 2. QUESTION GENERATION (Claude API, batched)
# ==========================================================================

SYSTEM_PROMPT = """You write UPSC Civil Services Prelims-level practice questions for an exam-prep app. \
You will be given raw OCR-extracted text from one chapter of a textbook. Your job is to write \
brand-new multiple-choice questions at genuine UPSC Prelims difficulty, testing every distinct \
fact, concept, example, figure, and distinction in the supplied text.

STRICT RULES:
1. Every fact used in a question or its explanation must come from the supplied text. Never invent \
   facts, examples, dates, or figures that are not in the text. If the text is ambiguous or garbled \
   (this is OCR output and may contain typos or broken characters), use your best judgement to \
   interpret it correctly, but do not fabricate content that isn't there.
2. Only UPSC-Prelims-tier difficulty — no basic recall questions. Favour these formats, mixed:
   - "Consider the following statements: 1. ... 2. ... 3. ... Which of the statements given above \
     is/are correct?" with options like "1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3" \
     (adapt wording to however many statements you use, 2 or 3 is typical).
   - Assertion (A) / Reason (R) questions with the four standard options ("Both A and R are true, \
     and R is the correct explanation of A", "Both A and R are true, but R is NOT the correct \
     explanation of A", "A is true, but R is false", "A is false, but R is true").
   - "Match List-I with List-II" questions with a lettered/numbered code table and 4 plausible \
     code combinations as options.
   - Occasionally a direct factual or "which one is NOT correct" question when that suits the content \
     better (e.g. worked numerical examples, or a clean list of items where one is a distractor).
3. Each question needs exactly 4 options and exactly one correct answer.
4. Write a RICH explanation for every question: state clearly why the correct answer is correct, and \
   explicitly explain why the specific incorrect statement/option is wrong, citing or closely \
   paraphrasing the relevant fact from the text. Add brief extra context or a commonly confused \
   related fact when it aids exam prep, but stay grounded in the text.
5. Do not repeat or closely rephrase any question in the "ALREADY WRITTEN" list you're given — write \
   about a different fact, example, or angle each time.
6. Output ONLY a JSON array (no markdown fences, no commentary) of objects with exactly these keys:
   "q": question text (string; use \\n to separate statement lines, assertion/reason lines, or \
        match-list rows — this renders as separate lines in the app),
   "o": array of exactly 4 option strings,
   "a": integer 0-3, the index into "o" of the correct option,
   "e": explanation string (plain text, "<b>...</b>" tags allowed for emphasis).
7. If you genuinely cannot find enough NEW, non-redundant, well-grounded facts to write more good \
   questions beyond what's already been written, return an empty JSON array: []
"""

def _build_user_prompt(chapter_title, chapter_text, already_written, batch_size):
    already_block = ""
    if already_written:
        numbered = "\n".join(f"- {q[:180]}" for q in already_written)
        already_block = f"\n\nALREADY WRITTEN ({len(already_written)} questions so far — do not repeat these facts/angles):\n{numbered}\n"
    return f"""Chapter title: {chapter_title}

CHAPTER TEXT:
\"\"\"
{chapter_text}
\"\"\"
{already_block}
Write up to {batch_size} new UPSC Prelims-level questions per the rules in your system prompt, \
covering facts/concepts from the chapter text not yet used above. Return ONLY the JSON array."""


def _parse_json_array(raw):
    raw = raw.strip()
    # Strip markdown code fences if the model added them despite instructions.
    if raw.startswith("```"):
        raw = re.sub(r"^```(json)?", "", raw).strip()
        raw = re.sub(r"```$", "", raw).strip()
    return json.loads(raw)


def _is_valid_question(q):
    if not isinstance(q, dict):
        return False
    if not isinstance(q.get("q"), str) or not q["q"].strip():
        return False
    if not isinstance(q.get("o"), list) or len(q["o"]) != 4:
        return False
    if not all(isinstance(o, str) and o.strip() for o in q["o"]):
        return False
    if not isinstance(q.get("a"), int) or not (0 <= q["a"] <= 3):
        return False
    if not isinstance(q.get("e"), str) or not q["e"].strip():
        return False
    return True


def _is_near_duplicate(new_q, existing_texts, threshold=0.90):
    for t in existing_texts:
        if SequenceMatcher(None, new_q.lower(), t.lower()).ratio() >= threshold:
            return True
    return False


def generate_questions(chapter_title, chapter_text, model="claude-sonnet-5",
                        batch_size=12, max_questions=70, max_batches=8,
                        min_new_per_batch_to_continue=3):
    """Iteratively call Claude to build up a deduplicated list of UPSC
    questions grounded in chapter_text."""
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
    questions = []

    for batch_num in range(1, max_batches + 1):
        if len(questions) >= max_questions:
            break
        remaining = max_questions - len(questions)
        this_batch_size = min(batch_size, remaining)

        print(f"  Batch {batch_num}: requesting up to {this_batch_size} questions "
              f"({len(questions)} so far)...")

        user_prompt = _build_user_prompt(
            chapter_title, chapter_text,
            [q["q"] for q in questions],
            this_batch_size,
        )

        response = client.messages.create(
            model=model,
            max_tokens=8000,
            temperature=0.5,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        raw_text = "".join(block.text for block in response.content if block.type == "text")

        try:
            batch = _parse_json_array(raw_text)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"    Warning: could not parse batch {batch_num} as JSON ({e}); skipping batch.")
            continue

        if not isinstance(batch, list):
            print(f"    Warning: batch {batch_num} was not a JSON array; skipping.")
            continue

        existing_texts = [q["q"] for q in questions]
        new_count = 0
        for q in batch:
            if len(questions) >= max_questions:
                break  # model over-delivered beyond what we asked for — stop accepting more
            if not _is_valid_question(q):
                continue
            if q["q"] in existing_texts:
                continue
            if _is_near_duplicate(q["q"], existing_texts):
                continue
            questions.append(q)
            existing_texts.append(q["q"])
            new_count += 1

        print(f"    -> {new_count} new valid questions added (total now {len(questions)}).")

        if new_count == 0:
            print("    Model returned nothing new/valid — stopping early.")
            break
        if new_count < min_new_per_batch_to_continue and batch_num > 2:
            print("    Diminishing returns — stopping early.")
            break

    return questions


# ==========================================================================
# 3. VALIDATION + CHUNKING INTO 10-QUESTION TESTS
# ==========================================================================

def validate_questions(questions):
    texts = [q["q"] for q in questions]
    assert len(texts) == len(set(texts)), "Duplicate question text slipped through!"
    for q in questions:
        assert len(q["o"]) == 4, q["q"]
        assert 0 <= q["a"] <= 3, q["q"]
    return questions


def chunk_into_tests(questions, chunk_size=10, min_last_chunk=5):
    """Split into test1, test2, ... of chunk_size each. If the final chunk
    would be smaller than min_last_chunk, merge it into the previous chunk
    instead (so you don't end up with e.g. a 2-question final test)."""
    chunks = [questions[i:i + chunk_size] for i in range(0, len(questions), chunk_size)]
    if len(chunks) >= 2 and len(chunks[-1]) < min_last_chunk:
        chunks[-2].extend(chunks[-1])
        chunks.pop()
    return {f"test{i}": chunk for i, chunk in enumerate(chunks, start=1)}


# ==========================================================================
# 4. MERGE INTO subject_data.json
# ==========================================================================

def slugify(title):
    s = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")
    return s


def update_subject_data(subject_data_path, subject_key, chapter_id, chapter_title,
                         chapter_desc, questions_by_test, pending_title=None):
    with open(subject_data_path) as f:
        sd = json.load(f)

    if subject_key not in sd:
        sd[subject_key] = {"title": subject_key.title(), "chapters": [], "pending": []}

    new_chapter = {
        "id": chapter_id,
        "title": chapter_title,
        "desc": chapter_desc,
        "questions": questions_by_test,
    }

    chapters = sd[subject_key]["chapters"]
    existing_idx = next((i for i, c in enumerate(chapters) if c["id"] == chapter_id), None)
    if existing_idx is not None:
        print(f"  Chapter id '{chapter_id}' already exists — replacing it.")
        chapters[existing_idx] = new_chapter
    else:
        chapters.append(new_chapter)

    match_title = (pending_title or chapter_title).strip().lower()
    before = len(sd[subject_key]["pending"])
    sd[subject_key]["pending"] = [
        p for p in sd[subject_key]["pending"] if p.get("title", "").strip().lower() != match_title
    ]
    removed = before - len(sd[subject_key]["pending"])
    if removed:
        print(f"  Removed '{match_title}' from the pending list.")

    with open(subject_data_path, "w") as f:
        json.dump(sd, f, indent=2, ensure_ascii=False)


# ==========================================================================
# 5. REBUILD APP + VALIDATE JS
# ==========================================================================

def rebuild_app(template_path, subject_data_path, app_index_path, upsc_prep_path):
    with open(template_path, encoding="utf-8") as f:
        template = f.read()
    with open(subject_data_path, encoding="utf-8") as f:
        data = f.read()
    out = template.replace("__SUBJECT_DATA_JSON__", data)
    os.makedirs(os.path.dirname(app_index_path) or ".", exist_ok=True)
    with open(app_index_path, "w", encoding="utf-8") as f:
        f.write(out)
    with open(upsc_prep_path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"  Rebuilt {app_index_path} and {upsc_prep_path} ({len(out)} chars).")


def validate_js(app_index_path):
    """Extract every <script> block from the rebuilt HTML and make sure it
    at least parses as valid JavaScript, using Node's Function constructor."""
    node_snippet = f"""
const fs = require('fs');
const html = fs.readFileSync({json.dumps(app_index_path)}, 'utf8');
const scriptRe = /<script\\b[^>]*>([\\s\\S]*?)<\\/script>/gi;
let m, count = 0, errors = 0;
while ((m = scriptRe.exec(html)) !== null) {{
  const code = m[1];
  if (!code.trim()) continue;
  count++;
  try {{ new Function('window','document','supabase', code); }}
  catch (e) {{ errors++; console.log('SYNTAX ERROR:', e.message); }}
}}
console.log('Checked ' + count + ' script blocks, ' + errors + ' errors.');
if (errors > 0) process.exit(1);
"""
    result = subprocess.run(["node", "-e", node_snippet], capture_output=True, text=True)
    print("  " + result.stdout.strip().replace("\n", "\n  "))
    if result.returncode != 0:
        print(result.stderr)
        sys.exit("JS validation FAILED — not committing. Fix the issue and re-run.")


# ==========================================================================
# 6. GIT COMMIT + PUSH
# ==========================================================================

def git_commit_and_push(repo_dir, paths_to_add, commit_message, push=True):
    def run(cmd):
        print("  $ " + " ".join(cmd))
        result = subprocess.run(cmd, cwd=repo_dir, capture_output=True, text=True)
        if result.stdout.strip():
            print("  " + result.stdout.strip().replace("\n", "\n  "))
        if result.returncode != 0:
            print(result.stderr)
        return result.returncode == 0

    run(["git", "add"] + paths_to_add)
    status = subprocess.run(["git", "diff", "--cached", "--name-only"], cwd=repo_dir,
                             capture_output=True, text=True).stdout.strip()
    if not status:
        print("  Nothing staged — skipping commit.")
        return
    if not run(["git", "commit", "-m", commit_message]):
        sys.exit("git commit failed. If this is a fresh machine, git needs to know who you are:\n"
                  '  git config --global user.name "Your Name"\n'
                  '  git config --global user.email "you@example.com"\n'
                  "Then re-run this script (subject_data.json etc. are already updated on disk, "
                  "so you won't lose the generated questions).")
    if push:
        if not run(["git", "push", "origin", "HEAD"]):
            sys.exit("git push failed.")
    else:
        print("  (--dry-run / push skipped: commit created locally only.)")


# ==========================================================================
# MAIN
# ==========================================================================

def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--pdf", required=True, help="Path to the source textbook PDF.")
    p.add_argument("--start-page", type=int, required=True, help="First page (1-indexed, as shown in your PDF viewer).")
    p.add_argument("--end-page", type=int, required=True, help="Last page (1-indexed, inclusive).")
    p.add_argument("--subject", required=True, help="Subject key in subject_data.json, e.g. geography, polity, economy, history.")
    p.add_argument("--chapter-title", required=True, help="Human-readable chapter title.")
    p.add_argument("--chapter-id", default=None, help="Chapter id (slug). Auto-generated from title if omitted.")
    p.add_argument("--chapter-desc", default=None, help="Short description shown under the chapter title. Auto-generated if omitted.")
    p.add_argument("--pending-title", default=None, help="Title to remove from the subject's pending list, if different from --chapter-title.")
    p.add_argument("--source-dir", default=None, help="Directory to save the raw extracted text and generated question JSON for provenance, e.g. source_material/goh_cheng_leong_geography")
    p.add_argument("--repo-dir", default=".", help="Path to your local clone of the repo (default: current directory).")
    p.add_argument("--model", default="claude-sonnet-5", help="Anthropic model to use.")
    p.add_argument("--max-questions", type=int, default=70, help="Upper cap on questions generated for this chapter.")
    p.add_argument("--batch-size", type=int, default=12, help="Questions requested per API call.")
    p.add_argument("--chunk-size", type=int, default=10, help="Questions per test.")
    p.add_argument("--no-rebuild", action="store_true", help="Skip rebuilding app/index.html and upsc-prep-app.html.")
    p.add_argument("--dry-run", action="store_true", help="Do everything except git commit/push.")
    args = p.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("Set ANTHROPIC_API_KEY in your environment first.")

    repo = args.repo_dir
    subject_data_path = os.path.join(repo, "subject_data.json")
    template_path = os.path.join(repo, "app_template.html")
    app_index_path = os.path.join(repo, "app", "index.html")
    upsc_prep_path = os.path.join(repo, "upsc-prep-app.html")

    for path in (subject_data_path, template_path):
        if not os.path.exists(path):
            sys.exit(f"Expected to find {path} — run this from inside your repo clone, "
                      f"or pass --repo-dir.")

    chapter_id = args.chapter_id or slugify(args.chapter_title)
    chapter_desc = args.chapter_desc or f"UPSC-level questions covering every concept in the '{args.chapter_title}' chapter"

    print(f"[1/6] Extracting pages {args.start_page}-{args.end_page} from {args.pdf} ...")
    chapter_text = extract_chapter_text(args.pdf, args.start_page, args.end_page)
    print(f"  Extracted {len(chapter_text)} characters.")

    if args.source_dir:
        os.makedirs(os.path.join(repo, args.source_dir), exist_ok=True)
        raw_path = os.path.join(repo, args.source_dir, f"{chapter_id}_raw.txt")
        with open(raw_path, "w", encoding="utf-8") as f:
            f.write(chapter_text)
        print(f"  Saved raw text to {raw_path}")

    print(f"[2/6] Generating UPSC-level questions with {args.model} ...")
    questions = generate_questions(
        args.chapter_title, chapter_text, model=args.model,
        batch_size=args.batch_size, max_questions=args.max_questions,
    )
    if not questions:
        sys.exit("No valid questions were generated — aborting without touching subject_data.json.")
    validate_questions(questions)
    print(f"  Generated {len(questions)} unique, validated questions.")

    print(f"[3/6] Splitting into {args.chunk_size}-question tests ...")
    questions_by_test = chunk_into_tests(questions, chunk_size=args.chunk_size)
    for name, qs in questions_by_test.items():
        print(f"  {name}: {len(qs)} questions")

    if args.source_dir:
        chapter_json_path = os.path.join(repo, args.source_dir, f"{chapter_id}_v2.json")
        with open(chapter_json_path, "w", encoding="utf-8") as f:
            json.dump({
                "id": chapter_id, "title": args.chapter_title, "desc": chapter_desc,
                "questions": {"basic": [], "intermediate": [], "advanced": [], "upsc": questions},
            }, f, indent=2, ensure_ascii=False)
        print(f"  Saved generated questions to {chapter_json_path}")

    print(f"[4/6] Merging into subject_data.json (subject: {args.subject}) ...")
    update_subject_data(
        subject_data_path, args.subject, chapter_id, args.chapter_title,
        chapter_desc, questions_by_test, pending_title=args.pending_title,
    )

    paths_to_add = ["subject_data.json"]
    if args.source_dir:
        paths_to_add.append(args.source_dir)

    if not args.no_rebuild:
        print("[5/6] Rebuilding app/index.html and upsc-prep-app.html ...")
        rebuild_app(template_path, subject_data_path, app_index_path, upsc_prep_path)
        print("  Validating rebuilt JavaScript ...")
        validate_js(app_index_path)
        paths_to_add += [app_index_path, upsc_prep_path]
    else:
        print("[5/6] Skipped (--no-rebuild).")

    print("[6/6] Committing" + ("" if args.dry_run else " and pushing") + " to git ...")
    total = sum(len(v) for v in questions_by_test.values())
    commit_message = (
        f"Add {args.subject.title()} chapter - {args.chapter_title} "
        f"(UPSC-tier only, {len(questions_by_test)} tests)\n\n"
        f"- {total} UPSC-level-only questions grounded in the source text, "
        f"split into {len(questions_by_test)} tests of {args.chunk_size} questions each\n"
        f"- Generated via generate_chapter.py"
    )
    git_commit_and_push(repo, paths_to_add, commit_message, push=(not args.dry_run))

    print("\nDone. " + ("(dry run — nothing pushed)" if args.dry_run else "Pushed to GitHub."))


if __name__ == "__main__":
    main()
