import json

upsc = []

# ==================================================================
# NEW UPSC TIER: CAG (Ch.52) + ATTORNEY GENERAL (Ch.53)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the CAG's dual audit approach is correct?","o":["The propriety audit (examining the 'wisdom, faithfulness and economy' of government expenditure) is discretionary for the CAG, whereas the legal and regulatory audit (verifying legal availability and applicability of expenditure) is obligatory","Both the propriety audit and the legal/regulatory audit are equally discretionary for the CAG","The legal and regulatory audit is discretionary, while the propriety audit is obligatory on the CAG","Neither the propriety audit nor the legal/regulatory audit is mentioned in the CAG's (Duties, Powers and Conditions of Service) Act, 1971"],"a":0,"e":"Under the 1971 Act, the legal and regulatory audit (verifying legal availability/applicability of expenditure) is obligatory on the CAG, while the propriety audit (assessing wisdom, faithfulness and economy of expenditure) is discretionary — the reverse of the incorrect options."})

upsc.append({"q":"Which one of the following statements about the CAG's 'performance audit' is NOT correct?","o":["Performance audit was first constitutionally mandated in 1971 through the CAG's (Duties, Powers and Conditions of Service) Act","In 2006, the Ministry of Finance issued an Office Memorandum clarifying that performance audit falls within the CAG's scope of audit","Performance audit is concerned with the audit of economy, efficiency and effectiveness in the receipt and application of public funds","Performance audit is a comprehensive appraisal of the progress and efficiency of the execution of development programmes"],"a":0,"e":"This statement is incorrect — performance audit was clarified/brought within the CAG's audit scope through a 2006 Ministry of Finance Office Memorandum, not through the 1971 Act. The other three statements correctly describe performance audit."})

upsc.append({"q":"Which one of the following limitations on the CAG's auditing role is correctly described?","o":["With regard to secret service expenditure, the CAG cannot call for particulars of expenditure but must accept a certificate from the competent administrative authority that it was incurred under that authority","The CAG has unrestricted access to all secret service expenditure particulars, with no certification-based exception","Secret service expenditure is entirely outside the CAG's constitutional mandate and is audited instead by the Intelligence Bureau","The CAG can only access secret service expenditure records with prior Supreme Court authorisation"],"a":0,"e":"The text explicitly describes this specific limitation: for secret service expenditure, the CAG must accept a certificate of due authorisation from the competent administrative authority rather than calling for the actual particulars — not unrestricted access, exclusion to the IB, or a judicial-authorisation requirement."})

upsc.append({"q":"Which one of the following statements about the difference between India's CAG and Britain's CAG is correct?","o":["India's CAG functions in practice only as an Auditor-General (auditing after expenditure has occurred) and not as a Comptroller, unlike Britain's CAG who controls the issue of money from the public exchequer before it is drawn","India's CAG has greater control over the issue of money from the Consolidated Fund than Britain's CAG","Both India's and Britain's CAG function purely as Auditors-General with no comptroller function","Britain's CAG has no role in controlling the issue of money from the public exchequer, unlike India's CAG"],"a":0,"e":"The text explicitly contrasts India's CAG (who is only an Auditor-General in practice, with departments drawing money without the CAG's specific prior authority) against Britain's CAG (who must approve withdrawals from the public exchequer before they occur, exercising a genuine 'Comptroller' function) — the reverse of the other options."})

upsc.append({"q":"Which one of the following was NOT among Paul H. Appleby's criticisms of the CAG's role in India?","o":["He argued that the CAG's function was a valuable modern innovation with no colonial-era antecedents","He argued that CAG audit is a primary cause of a widespread and paralysing unwillingness among administrators to decide and act","He argued that Parliament had a greatly exaggerated notion of the importance of auditing to parliamentary responsibility","He recommended that the CAG should be relieved of the responsibility of audit, i.e., abolition of the office"],"a":0,"e":"Appleby actually argued the OPPOSITE — that the CAG's function was, in large measure, an inheritance from colonial rule, not a valuable modern innovation free of colonial antecedents. The other three options accurately reflect his actual criticisms, including his recommendation to abolish the CAG's audit role."})

upsc.append({"q":"With reference to the CAG's three-fold relationship with public corporations, which one of the following statements is correct?","o":["Some corporations are audited directly by the CAG, some by private auditors appointed in consultation with the CAG (with scope for CAG supplementary audit), and some are audited exclusively by private auditors with no CAG role at all, reporting directly to Parliament","The CAG directly and exclusively audits all public corporations without exception","Private auditors are never involved in auditing any public corporation in India","The CAG's role in corporation audit is identical to its role in auditing Government companies, with no distinction between the two categories"],"a":0,"e":"The text explicitly lays out three distinct categories of CAG-corporation relationships (direct audit, private audit with CAG consultation/supplementary audit, and fully private audit reporting directly to Parliament) — and separately notes that Government companies (audited by government-appointed private auditors with CAG supplementary/test audit option) are treated as a distinct category from corporations."})

upsc.append({"q":"Which one of the following statements about the CAG's role in compiling government accounts is correct?","o":["The CAG compiles and maintains the accounts of state governments, but was relieved of this responsibility for the Central Government in 1976 due to departmentalisation (separation) of accounts from audit","The CAG compiles and maintains accounts for both the Centre and the states even today, with no historical change","The CAG was never responsible for compiling accounts of any government, only for auditing them","The CAG was relieved of compiling state government accounts in 1976, while retaining this role for the Central Government"],"a":0,"e":"The text specifically notes the CAG still compiles/maintains STATE government accounts, but was relieved of the CENTRAL government accounts compilation role in 1976 due to departmentalisation of accounts — not the reverse, and not a complete absence of any compilation role historically."})

upsc.append({"q":"Consider the following statements regarding the CAG's certification function under Article 279:\n1. The CAG ascertains and certifies the net proceeds of any tax or duty.\n2. The CAG's certificate on net proceeds is final and not subject to further challenge.\n3. 'Net proceeds' means the proceeds of a tax or duty minus the cost of collection.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","1 and 3 only","2 and 3 only"],"a":0,"e":"All three statements accurately describe Article 279's provision — the CAG certifies net proceeds, this certificate is final, and 'net proceeds' is defined as proceeds minus collection cost."})

upsc.append({"q":"Which one of the following statements best captures Dr. B.R. Ambedkar's assessment of the CAG's constitutional significance?","o":["Dr. B.R. Ambedkar stated in the Constituent Assembly that the CAG shall be the most important officer under the Constitution of India","Dr. B.R. Ambedkar argued that the CAG's office was constitutionally unnecessary and could be abolished","Dr. B.R. Ambedkar compared the CAG's importance unfavourably to that of the Election Commission alone","Dr. B.R. Ambedkar held that the CAG should function under the direct administrative control of the Ministry of Finance"],"a":0,"e":"Ambedkar's Constituent Assembly Debates remark (Volume VIII) explicitly described the CAG as the most important officer under the Constitution — not a call for abolition, an unfavourable comparison to just the EC, or subordination to the Finance Ministry."})

upsc.append({"q":"Which one of the following is correctly identified by the Second Administrative Reforms Commission (2005-2009) as a factor impeding the effectiveness of CAG's external audit?","o":["Detailed examination of Audit Report paras by the Public Accounts Committee covers barely 15-20 paras against a total of 1000-1500 paras submitted annually, so Ministries take seriously only those paras discussed in the PAC","The CAG's reports are examined in full detail by the PAC every single year with no pendency at either the Union or State level","CAG audit findings are primarily based on physical, on-ground verification rather than documents and files","CAG's reports are always timely, closely tracking irregularities as soon as they occur, with no post-facto element"],"a":0,"e":"The Second ARC specifically flagged this problem — only 15-20 of 1000-1500 annual paras get detailed PAC examination — as a real impediment. It also noted (contrary to the other options) that audit is largely document/file-based, that there is huge pendency of paras (10-20 years old in some states), and that audit is inherently post-facto and sometimes not timely."})

upsc.append({"q":"Which one of the following limitations on the Attorney General of India's functioning is NOT correct as stated in the Constitution/executive notification?","o":["The Attorney General is barred from private legal practice altogether, being treated as a full-time government servant","The Attorney General should not advise or hold a brief against the Government of India","The Attorney General should not accept appointment as a director in any company or corporation without the permission of the Government of India","The Attorney General should not defend accused persons in criminal prosecutions without the permission of the Government of India"],"a":0,"e":"This statement is incorrect — the Attorney General is explicitly NOT a full-time counsel, does NOT fall in the category of government servants, and is NOT debarred from private legal practice. The other three options are genuine limitations placed on the AG's functioning."})

upsc.append({"q":"Which one of the following statements about the Solicitor General and Additional Solicitor General of India is correct?","o":["Unlike the office of the Attorney General, the offices of the Solicitor General and Additional Solicitor General are not created by the Constitution and are not mentioned in Article 76","Article 76 explicitly creates and names both the Solicitor General and Additional Solicitor General alongside the Attorney General","The Solicitor General is senior in constitutional status to the Attorney General","The Additional Solicitor General is appointed directly by the Supreme Court, unlike the Attorney General who is appointed by the President"],"a":0,"e":"The text explicitly notes only the Attorney General's office is created by the Constitution; Article 76 does not mention the Solicitor General or Additional Solicitor General, who are lesser law officers assisting the AG — not constitutionally senior, co-created, or appointed by the Supreme Court."})

upsc.append({"q":"Which one of the following statements about the Attorney General's position in relation to the Union Cabinet and law-related administration is correct?","o":["The Attorney General is not a member of the Central Cabinet; a separate Law Minister in the Cabinet looks after legal matters at the government level","The Attorney General is, by constitutional convention, always included as a member of the Union Cabinet","There is no separate Law Minister, since the Attorney General personally discharges that role within the Cabinet","The Attorney General's advice to ministries can be sought directly, bypassing the Ministry of Law and Justice's Department of Legal Affairs, in all cases"],"a":0,"e":"The Attorney General is explicitly NOT a Cabinet member — a separate Law Minister handles legal matters at the Cabinet level — and, per the stated limitations, ministries/departments must route requests for AG advice through the Ministry of Law and Justice's Department of Legal Affairs, not bypass it."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch52_53_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
