import json

upsc = []

# ==================================================================
# NEW UPSC TIER: HIGH COURT (Ch.34) + SUBORDINATE COURTS (Ch.35)
# ==================================================================

upsc.append({"q":"Which one of the following statements about additional and acting judges of a High Court is NOT correct?","o":["An additional or acting judge of a High Court can continue in office even after attaining the age of 62 years, since this age limit applies only to permanent judges","The President can appoint additional judges for a temporary period not exceeding two years to address a temporary increase in business or arrears of work","An acting judge can be appointed when a High Court judge (other than the Chief Justice) is unable to perform duties, or is acting temporarily as Chief Justice","An acting judge holds office until the permanent judge whose place they filled resumes office"],"a":0,"e":"This statement is incorrect — BOTH additional and acting judges CANNOT hold office after attaining the age of 62 years; this age limit is not confined to permanent judges alone. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the independence safeguards for a High Court is NOT correct?","o":["The pension of a High Court judge is charged on the Consolidated Fund of the concerned state, just like the judges' salaries and allowances","High Court judges are appointed by the President in consultation with the Chief Justice of India and the Chief Justice of the concerned High Court","The salaries and allowances of High Court judges and administrative expenses of the High Court are charged on the Consolidated Fund of the state, hence non-votable by the state legislature","Retired permanent judges of a High Court are barred from pleading or acting in any court or authority in India, except the Supreme Court and other High Courts"],"a":0,"e":"This statement is incorrect — while a High Court judge's SALARY is charged on the state's Consolidated Fund, their PENSION is specifically charged on the Consolidated Fund of INDIA, not the state — a deliberate distinction noted in the text. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the original civil jurisdiction of High Courts:\n1. The Calcutta, Bombay, Madras and Delhi High Courts have original civil jurisdiction in cases of higher pecuniary value.\n2. Before 1973, the Calcutta, Bombay and Madras High Courts also possessed original criminal jurisdiction.\n3. The original criminal jurisdiction of these High Courts was fully abolished by the Criminal Procedure Code, 1973.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — four High Courts (Calcutta, Bombay, Madras, Delhi) retain original civil jurisdiction for higher-value cases, while the original criminal jurisdiction once held by three of them (Calcutta, Bombay, Madras) was abolished by the CrPC, 1973."})

upsc.append({"q":"Which one of the following statements about the writ jurisdiction of a High Court under Article 226 is NOT correct?","o":["A High Court can issue writs only to persons, authorities and governments located within its own territorial jurisdiction, even if the cause of action arose within that jurisdiction but the respondent is located elsewhere","The writ jurisdiction of the High Court is wider than that of the Supreme Court, since it extends to enforcement of ordinary legal rights and not just Fundamental Rights","The writ jurisdiction of the High Court under Article 226 is concurrent with, not exclusive of, the Supreme Court's writ jurisdiction under Article 32","In the L. Chandra Kumar case (1997), the Supreme Court held that the writ jurisdiction of both the High Courts and the Supreme Court forms part of the basic structure of the Constitution"],"a":0,"e":"This statement is incorrect and reverses the actual territorial rule — a High Court CAN issue writs to persons/authorities/governments OUTSIDE its territorial jurisdiction, so long as the cause of action arises within its jurisdiction; it is not confined strictly to respondents located within its territory. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the appellate jurisdiction of a High Court in civil matters:\n1. First appeals from district courts and other subordinate courts lie directly to the High Court on both questions of law and fact, above a stipulated monetary threshold.\n2. Second appeals from district court/subordinate court orders lie to the High Court only on questions of law, not questions of fact.\n3. The appellate jurisdiction of a High Court is narrower in scope than its original jurisdiction.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual comparison — the text explicitly states the High Court's APPELLATE jurisdiction is WIDER in scope than its original jurisdiction, not narrower. Statements 1 and 2 correctly describe first and second civil appeals."})

upsc.append({"q":"Which one of the following statements about the district judge in the subordinate judiciary is NOT correct?","o":["A district judge exercises jurisdiction only over civil matters and has no role whatsoever in criminal proceedings within the district","A district judge, when hearing criminal cases, is designated the sessions judge and possesses power to impose sentences up to life imprisonment and death","A capital (death) sentence passed by a sessions judge is subject to confirmation by the High Court, whether or not an appeal has been filed","The district judge exercises both judicial and administrative powers, including supervisory powers over all subordinate courts in the district"],"a":0,"e":"This statement is incorrect — the district judge, in the same person, exercises BOTH civil jurisdiction (as district judge) AND criminal jurisdiction (as sessions judge) — it is not confined to civil matters alone. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the qualifications for appointment as a district judge is NOT correct?","o":["A serving Central or state government employee is fully eligible for direct appointment as a district judge without any need to leave government service first","A person must have been an advocate or pleader for seven years to be eligible","A person must be recommended by the High Court for appointment as district judge","The appointment, posting and promotion of district judges is made by the Governor in consultation with the High Court"],"a":0,"e":"This statement is incorrect — one of the explicit qualifications is that the person should NOT already be in the service of the Central or state government, contrary to the claim of full eligibility for a serving government employee. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the tiered structure of civil subordinate courts (below the District Court) is NOT correct?","o":["The Court of Munsiff, at the lowest tier, has unlimited pecuniary jurisdiction over civil suits, identical to that of a Subordinate Judge","The Court of Subordinate Judges exercises unlimited pecuniary jurisdiction over civil suits","The Munsiff possesses limited jurisdiction, deciding civil cases of small pecuniary value","A Subordinate Judge may also be vested with the powers of an Assistant Sessions Judge, combining civil and criminal powers"],"a":0,"e":"This statement is incorrect and reverses the actual jurisdictional hierarchy — it is the SUBORDINATE JUDGE (not the Munsiff) who has unlimited pecuniary jurisdiction over civil suits; the Munsiff, at the lowest tier, has LIMITED jurisdiction confined to small-value civil cases. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about criminal subordinate courts below the Sessions Court:\n1. The Chief Judicial Magistrate can decide criminal cases punishable with imprisonment up to seven years.\n2. The Judicial Magistrate, at the lowest tier, tries criminal cases punishable with imprisonment up to three years.\n3. In some states, Panchayat Courts (variously called Nyaya Panchayat, Gram Kutchery, etc.) try petty civil and criminal cases.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the text's description of the criminal subordinate court hierarchy: Chief Judicial Magistrate (up to 7 years), Judicial Magistrate (up to 3 years), and village-level Panchayat Courts for petty matters."})

upsc.append({"q":"Which one of the following statements about Small Causes Courts is NOT correct?","o":["Decisions of Small Causes Courts are entirely beyond any form of judicial oversight, with no revisional power vested in any higher court","Small Causes Courts decide civil cases of small value in a summary manner","Such courts have been established in some states and in the former Presidency towns","Although decisions of Small Causes Courts are generally final, the High Court possesses the power of revision over them"],"a":0,"e":"This statement is incorrect and directly contradicts option D (which is correct) — while Small Causes Courts' decisions are generally final, the High Court DOES retain a power of revision over them; they are not wholly beyond judicial oversight. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about Article 233-A of the Constitution is NOT correct?","o":["It was inserted by the 20th Constitutional Amendment Act, 1966, and prospectively (not retrospectively) validated the appointment of certain district judges going forward only","It retrospectively validated the appointment of certain district judges whose appointments were otherwise constitutionally defective","It also validated the judgements delivered by such district judges whose appointments it retrospectively validated","It was added specifically to address a validation problem concerning certain district judge appointments and their judicial decisions"],"a":0,"e":"This statement is incorrect and reverses the actual effect — Article 233-A RETROSPECTIVELY validated certain district judge appointments and the judgements they delivered, not merely prospectively from the date of insertion. The other three statements are correct."})

upsc.append({"q":"Assertion (A): Control over district courts and other subordinate courts, including posting, promotion and leave of judicial service personnel below the rank of district judge, vests in the High Court.\nReason (R): This arrangement, under Article 235, is designed to insulate the subordinate judiciary from executive interference and secure its functional independence.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — Articles 233 to 237 are explicitly described in the text as provisions meant 'to ensure their independence from the executive,' directly explaining why control over subordinate court personnel is vested in the High Court rather than the state executive."})

upsc.append({"q":"Which one of the following statements about the appointment of persons to the judicial service of a state (other than district judges) is correct?","o":["Such appointments are made by the Governor after consultation with both the State Public Service Commission and the High Court","Such appointments are made solely by the High Court, without any role for the Governor or the State Public Service Commission","Such appointments are made by the President after consultation with the Chief Justice of India","Such appointments require no consultation with any body and are made entirely at the Governor's discretion"],"a":0,"e":"Article 234 provides that appointment of persons (other than district judges) to a state's judicial service is made by the Governor after consultation with BOTH the State Public Service Commission and the High Court — not by any single body acting alone, and not requiring central government or Supreme Court involvement."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch34_35_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
