import json

upsc = []

# ==================================================================
# NEW UPSC TIER: GOVERNOR (Ch.30)
# ==================================================================

upsc.append({"q":"Consider the following statements comparing the veto power of the President and the Governor over an ordinary bill:\n1. The President has three alternatives (assent, withhold assent, or return for reconsideration), while the Governor has four, the fourth being reservation for the President's consideration.\n2. Once an ordinary bill returned by the Governor is passed again by the state legislature and presented again, the Governor must give assent.\n3. When the Governor reserves a bill for the President and the President returns it for reconsideration and it is passed again, it must be presented to the Governor (not the President) for final assent.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual procedure — once the Governor reserves a bill for the President's consideration, the Governor has no further role; a bill returned by the President and re-passed must be presented again to the PRESIDENT (not the Governor) for final assent. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the President's and Governor's assent to a Money Bill is NOT correct?","o":["Both the President and the Governor can return a Money Bill for reconsideration of the legislature, just as they can with an ordinary bill","The President has only two alternatives for a Money Bill: give assent, or withhold assent","The Governor has three alternatives for a Money Bill: give assent, withhold assent, or reserve it for the President's consideration","When the Governor reserves a Money Bill for the President, the President also has only two alternatives — give assent or withhold assent — and cannot return it for reconsideration"],"a":0,"e":"This statement is incorrect — NEITHER the President nor the Governor can return a Money Bill for reconsideration of the legislature (unlike with ordinary bills); their options are limited to assenting or withholding assent (with the Governor also able to reserve it for the President). The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Governor's 'constitutional discretion' (express discretion mentioned in the Constitution):\n1. It includes reservation of a bill for the President's consideration.\n2. It includes recommending the imposition of President's Rule in the state.\n3. It includes determining the amount payable by the governments of Assam, Meghalaya, Tripura and Mizoram to an autonomous Tribal District Council as mining-licence royalty.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct and match the Constitution's four express/constitutional discretion cases for the Governor: reserving bills, recommending President's Rule, functioning as administrator of an adjoining Union Territory, and the Sixth Schedule royalty-determination function for the four named northeastern states."})

upsc.append({"q":"Which one of the following is an example of the Governor's 'situational discretion' (hidden discretion arising from political exigencies) rather than 'constitutional discretion' (express discretion)?","o":["Appointment of the Chief Minister when no party has a clear majority in the state legislative assembly","Recommending the imposition of President's Rule in the state","Reservation of a bill for the consideration of the President","Determining the royalty payable to an autonomous Tribal District Council in certain northeastern states"],"a":0,"e":"Appointing the Chief Minister in a hung Assembly is a case of situational (hidden) discretion, along with dismissing a council of ministers that cannot prove its majority and dissolving the assembly if the ministry has lost majority — distinct from the Constitution's express/constitutional discretion cases (bill reservation, President's Rule recommendation, UT administration, and Sixth Schedule royalty determination), which are the other three options."})

upsc.append({"q":"Match List-I (State) with List-II (Governor's Special Responsibility under Presidential Directions) and select the correct answer using the code below.\nList-I:\nA. Maharashtra\nB. Nagaland\nC. Sikkim\nD. Karnataka\nList-II:\n1. Establishment of a separate development board for the Hyderabad-Karnataka region\n2. Law and order, so long as internal disturbance in the Naga Hills-Tuensang Area continues\n3. Establishment of separate development boards for Vidarbha and Marathwada\n4. Peace and ensuring social/economic advancement of different sections of the population\nCodes:","o":["A-3, B-2, C-4, D-1","A-3, B-4, C-2, D-1","A-2, B-3, C-4, D-1","A-3, B-2, C-1, D-4"],"a":0,"e":"The correct match is A-3, B-2, C-4, D-1: Maharashtra's Governor oversees Vidarbha/Marathwada development boards, Nagaland's Governor has special responsibility for law and order regarding Naga Hills-Tuensang disturbance, Sikkim's Governor safeguards peace and social/economic advancement, and Karnataka's Governor oversees the Hyderabad-Karnataka development board."})

upsc.append({"q":"Which one of the following states is NOT among those where the Governor has been assigned a special responsibility (under Presidential directions) as per the book's account?","o":["Kerala","Gujarat","Assam","Manipur"],"a":0,"e":"Kerala is NOT among the states listed with a Governor's special responsibility — the book lists Maharashtra, Gujarat, Nagaland, Assam, Manipur, Sikkim, Arunachal Pradesh, and Karnataka as the states where such special gubernatorial responsibilities apply, not Kerala."})

upsc.append({"q":"According to the Sarkaria Commission's identification of issues in the Governor's functioning, which one of the following statements is NOT correct?","o":["The Commission found complete uniformity across all Governors in the criteria adopted for dismissal of a Chief Minister, with no variation in practice","The Commission noted that Governors have used varying methods — relying on lists of supporters or physical head-counts — to test which party/group commands a majority","The Commission criticised instances where Governors recommended President's Rule without exhausting all possible steps to induct or maintain a stable government","The Commission noted controversy and lack of uniformity in Governors' reservation of State Bills for the President's consideration"],"a":0,"e":"This statement is incorrect and reverses the Commission's actual finding — the Sarkaria Commission explicitly noted there has been NO uniformity in the criteria adopted by different Governors for dismissing a Chief Minister, not complete uniformity. The other three statements correctly reflect the Commission's findings."})

upsc.append({"q":"Which one of the following statements about the Governor's role as Chancellor of universities is NOT correct?","o":["The Governor's exercise of discretion as Chancellor has never been criticised, since this role is entirely free from any constitutional controversy","The Governor, by virtue of office, is designated Chancellor or head of the university under specific state legislations, which confer certain powers on this office","When exercising powers as Chancellor, the Governor acts under the relevant statute, not in the capacity of Governor as such","Critics have questioned whether the Governor, even while acting as Chancellor, should still be bound by the advice of the Council of Ministers"],"a":0,"e":"This statement is incorrect — the book explicitly notes the Governor's exercise of discretion as Chancellor (e.g., in nominating university council members) HAS been criticised, on the premise that the Governor should still act on ministerial advice even in this capacity. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Sarkaria Commission's observations on Governors 'in choosing a Chief Minister':\n1. When a single party or coalition emerges with a clear majority, there is normally no difficulty in appointing the Chief Minister.\n2. Where no single party/group commands an absolute majority, the Governor should call upon the leader with the largest apparent support to form the government, leaving the confidence question to the Assembly.\n3. This procedure, per the Commission, tends to increase (not reduce) the scope for allegations of partisanship against the Governor.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the Commission's actual assessment — the Commission held that this procedure (calling the largest apparent group and leaving confidence to the Assembly) leaves LITTLE scope for allegations of unfairness or partisanship, not that it increases such scope. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the ordinance-making power of the Governor, in comparison with the President, is NOT correct?","o":["The Governor can promulgate an ordinance even when the state legislature is in full session, exercising this power concurrently alongside ongoing legislative business","The Governor can promulgate an ordinance when the legislative assembly (unicameral) is not in session, or when both Houses (bicameral) are not in session","The President can promulgate an ordinance when both Houses of Parliament are not in session, or when only one House is not in session","Article 213 (Governor's ordinance-making power) is broadly modelled on the President's corresponding power under Article 123"],"a":0,"e":"This statement is incorrect — like the President, the Governor can promulgate an ordinance ONLY when the legislature (or the relevant House(s)) is NOT in session, not while it is sitting; ordinance power exists precisely to address situations when the legislature cannot be immediately convened. The other three statements are correct."})

upsc.append({"q":"Assertion (A): The Constitution assigns a dual role to the office of Governor.\nReason (R): The Governor functions both as the constitutional head of the state and as a representative of the Centre (President) in the state, particularly through discretionary functions and special responsibilities under Presidential directions.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text explicitly concludes that the Constitution's assignment of a dual role to the Governor stems precisely from this combination: constitutional head of the state on one hand, and representative/agent of the Centre discharging special responsibilities on the other."})

upsc.append({"q":"Which one of the following statements about the appointment of District Judges and other judicial officers, as part of the Governor's judicial powers, is NOT correct?","o":["The Governor appoints, posts and promotes District Judges independently, without any consultation requirement involving the state High Court","The Governor makes appointments, postings and promotions of District Judges in consultation with the state High Court","The Governor appoints persons to the judicial service of the state (other than District Judges) in consultation with the state High Court and the State Public Service Commission","The Governor's judicial powers also include the power to grant pardons, reprieves, respites or remissions of punishment in certain cases"],"a":0,"e":"This statement is incorrect and omits a mandatory step — the Governor's appointment/posting/promotion of District Judges must be done IN CONSULTATION WITH the state High Court, not independently. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Governor's reservation of a bill for the President's consideration, as discussed among the Sarkaria Commission's identified issues, is NOT correct?","o":["The practice of Governors reserving State Bills passed by the legislature for the President's consideration has been entirely free of controversy in every instance","Nominations to the Legislative Council by Governors have drawn criticism on the ground that Governors have no discretion in such matters","The exercise of discretion by Governors in dissolving the Legislative Assembly has shown a lack of uniform approach across different Governors","Recommending President's Rule without exhausting all constitutional options to form or maintain a stable government has drawn criticism of partisan behaviour"],"a":0,"e":"This statement is incorrect — the book explicitly states that Governors' reservation of State Bills for the President's consideration HAS created controversy in some cases, not that it has been free of controversy. The other three statements correctly reflect issues identified regarding the Governor's functioning."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch30_governor_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
