import json

upsc = []

# ==================================================================
# NEW UPSC TIER: FINANCE COMMISSION (Ch.46) — large batch
# ==================================================================

upsc.append({"q":"Which one of the following statements about the composition of the Finance Commission is NOT correct?","o":["All four members other than the Chairman must necessarily be judges of a High Court or persons qualified to be appointed as such","The Commission consists of a Chairman and four other members appointed by the President","The Chairman should be a person having experience in public affairs","Members are eligible for reappointment and hold office for such period as the President specifies in the order of appointment"],"a":0,"e":"This statement is incorrect — only ONE of the four other members needs to be a High Court judge (or qualified to be one); the remaining three are selected from persons with specialised knowledge of government finance/accounts, wide experience in financial matters/administration, or special knowledge of economics. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Finance Commission's historical function relating to jute export duty is correct?","o":["Till 1960, the Commission suggested grants to Assam, Bihar, Odisha and West Bengal in lieu of a share of net proceeds of export duty on jute and jute products, for a temporary ten-year period from the Constitution's commencement","This function continues to this day, unmodified, as one of the Commission's four core functions","This function pertained to Punjab, Haryana, Rajasthan and Gujarat in lieu of canal water royalty","This function was permanently enshrined as a fifth core function of the Commission under Article 280(3)"],"a":0,"e":"The text explicitly notes this was a temporary, ten-year, jute-export-duty-related function (for four named eastern states) that lapsed around 1960, not a permanent or unrelated function, and not the described alternative topics/states."})

upsc.append({"q":"Which one of the following statements about Dr. P.V. Rajamannar, Chairman of the Fourth Finance Commission, is NOT correct?","o":["He observed that since the Finance Commission is a quasi-judicial constitutional body, the Government of India could freely reject its recommendations without needing compelling reasons","He observed that the Finance Commission's recommendations should not be turned down by the Government of India unless there are very compelling reasons","He noted an overlapping of functions and responsibilities between the Finance Commission and the erstwhile Planning Commission in federal fiscal transfers","He chaired the Fourth Finance Commission, appointed in 1964 and submitting its report in 1965"],"a":0,"e":"This statement is incorrect and reverses Rajamannar's actual observation — he held that the Commission's recommendations should NOT be turned down without very compelling reasons, precisely because of its quasi-judicial constitutional character, not that they could be freely rejected. The other three statements are correct."})

upsc.append({"q":"Match List-I (Finance Commission) with List-II (Chairman) and select the correct answer using the code below.\nList-I:\nA. Second Finance Commission\nB. Third Finance Commission\nC. Fifth Finance Commission\nD. Sixth Finance Commission\nList-II:\n1. A.K. Chanda\n2. Mahavir Tyagi\n3. K. Santhanam\n4. Brahmananda Reddy\nCodes:","o":["A-3, B-1, C-2, D-4","A-1, B-3, C-2, D-4","A-3, B-1, C-4, D-2","A-3, B-2, C-1, D-4"],"a":0,"e":"The correct match is A-3 (Second FC: K. Santhanam), B-1 (Third FC: A.K. Chanda), C-2 (Fifth FC: Mahavir Tyagi), D-4 (Sixth FC: Brahmananda Reddy) — matching each early Finance Commission to its chairman per Table 46.1."})

upsc.append({"q":"Match List-I (Finance Commission) with List-II (Chairman) and select the correct answer using the code below.\nList-I:\nA. Seventh Finance Commission\nB. Eighth Finance Commission\nC. Ninth Finance Commission\nD. Tenth Finance Commission\nList-II:\n1. Y.B. Chavan\n2. K.C. Pant\n3. J.M. Shelat\n4. N.K.P. Salve\nCodes:","o":["A-3, B-1, C-4, D-2","A-3, B-4, C-1, D-2","A-1, B-3, C-4, D-2","A-3, B-1, C-2, D-4"],"a":0,"e":"The correct match is A-3 (Seventh FC: J.M. Shelat), B-1 (Eighth FC: Y.B. Chavan), C-4 (Ninth FC: N.K.P. Salve), D-2 (Tenth FC: K.C. Pant) — matching each Finance Commission from the 1977-1992 appointment period to its chairman."})

upsc.append({"q":"Which one of the following statements about the Eleventh and Twelfth Finance Commissions is NOT correct?","o":["The Eleventh Finance Commission was chaired by Dr. C. Rangarajan, and the Twelfth by A.M. Khusro","The Eleventh Finance Commission was appointed in 1998 and submitted its report in 2000, covering the period 2000-2005","The Twelfth Finance Commission was chaired by Dr. C. Rangarajan, appointed in 2002 and submitting its report in 2004, covering 2005-2010","The Eleventh Finance Commission was chaired by A.M. Khusro"],"a":0,"e":"This statement is incorrect and reverses the actual chairmen — the Eleventh Finance Commission was chaired by A.M. KHUSRO, and the Twelfth by Dr. C. RANGARAJAN, not the other way around. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Fifteenth Finance Commission's report submission is correct?","o":["It submitted two separate reports — the first on 5 December 2019 covering 2020-21, and the second on 9 November 2020 covering 2021-22 to 2025-26","It submitted only a single report in 2019 covering the entire period 2020-2026","It was constituted in 2019 and submitted its report in 2023","Its report was never formally submitted due to procedural delays caused by the COVID-19 pandemic"],"a":0,"e":"The Fifteenth Finance Commission (chaired by N.K. Singh, appointed 2017) submitted TWO reports — an interim one (December 2019, for 2020-21) followed by the full report (November 2020, for 2021-22 to 2025-26) — not a single unified report, a 2023 submission, or no submission at all."})

upsc.append({"q":"Which one of the following statements about the legal effect of Finance Commission recommendations is NOT correct?","o":["The Constitution explicitly creates a binding legal right in favour of beneficiary states to receive the exact money recommended by the Commission, enforceable in court","It is nowhere laid down in the Constitution that the Commission's recommendations shall be binding on the Government of India","The recommendations are of an advisory nature, and it is up to the Union government to implement them","No legal right in favour of beneficiary states to receive the recommended money arises purely from the Commission's recommendation"],"a":0,"e":"This statement is incorrect — as per the cited constitutional commentary, there is explicitly NO binding legal right created in favour of beneficiary states merely because the Commission recommended a sum; the recommendations are advisory only. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the relationship between the Finance Commission and the erstwhile Planning Commission (prior to 2015) is correct?","o":["Dr. P.V. Rajamannar noted an overlap of functions and responsibilities between the Finance Commission and the Planning Commission in the sphere of federal fiscal transfers","The two bodies had entirely separate, non-overlapping spheres of activity with no observed friction between them","The Planning Commission was a constitutional body created under Article 280, exactly like the Finance Commission","The Finance Commission's role was strengthened, not undermined, by the Planning Commission's parallel involvement in Centre-state fiscal transfers"],"a":0,"e":"Rajamannar's own report explicitly noted an overlap in functions/responsibilities between the two bodies in fiscal transfers, and the text states the Finance Commission's role was actually UNDERMINED (not strengthened) by the non-constitutional, non-statutory Planning Commission until the latter's 2015 replacement by NITI Aayog."})

upsc.append({"q":"Which one of the following statements about the First Finance Commission is correct?","o":["It was chaired by K.C. Neogy, appointed in 1951, submitted its report in 1952, covering the implementation period 1952-57","It was chaired by K. Santhanam and covered the period 1957-62","It was appointed in 1956 and submitted its report in 1957","It was never actually constituted, as the Constitution's Finance Commission provisions took effect only from the Fourth Commission onward"],"a":0,"e":"The First Finance Commission was chaired by K.C. Neogy, appointed in 1951 and submitting its report in 1952 for the implementation period 1952-57 — the other options describe the Second Finance Commission's details or make a false claim about the First Commission never being constituted."})

upsc.append({"q":"Consider the following statements about the Finance Commission's core functions under Article 280(3):\n1. It recommends the distribution of net proceeds of taxes between the Centre and states, and their allocation among the states.\n2. It recommends principles governing grants-in-aid to states from the Consolidated Fund of India.\n3. It recommends measures to augment a state's Consolidated Fund to supplement panchayat/municipality resources, based on the state finance commission's recommendations.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct and match the Commission's core functions under Article 280(3): vertical/horizontal tax devolution, grants-in-aid principles, and (since the 73rd/74th Amendments, 1992) augmenting state funds for local bodies."})

upsc.append({"q":"Which one of the following statements about how many Finance Commissions have been constituted, and Article 281, is correct?","o":["Fifteen Finance Commissions have been constituted till the Fifteenth Commission (2017), and Article 281 requires the President to lay the Commission's report, along with an explanatory memorandum on action taken, before Parliament","Twelve Finance Commissions have been constituted, and Article 281 deals solely with the Commission's composition","Fifteen Finance Commissions have been constituted, but Article 281 has no bearing on parliamentary presentation of the report","Ten Finance Commissions have been constituted, and Article 281 empowers the Commission to directly disburse funds to states without government involvement"],"a":0,"e":"The text confirms fifteen Finance Commissions were constituted up to the Fifteenth (2017), and Article 281 specifically requires the President to lay the Commission's report before both Houses of Parliament along with an explanatory memorandum on the action taken — not the other incorrect characterisations."})

upsc.append({"q":"Which one of the following statements about the Finance Commission's constitutional description is correct?","o":["Article 280 establishes the Finance Commission as a quasi-judicial body, constituted by the President every fifth year or earlier if considered necessary","Article 280 establishes the Finance Commission as a purely executive body with no quasi-judicial character","The Finance Commission must be constituted at fixed ten-year intervals with no discretion for the President to constitute it earlier","The Finance Commission is a permanent, standing body that is never reconstituted"],"a":0,"e":"Article 280 explicitly describes the Finance Commission as a quasi-judicial body constituted every fifth year, OR at such earlier time as the President considers necessary — not a purely executive body, a fixed ten-year-interval body, or a permanent non-reconstituted body."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch46_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
