import json

upsc = []

# ==================================================================
# NEW UPSC TIER: NITI AAYOG (Ch.56)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the National Institute of Labour Economics Research and Development (NILERD) is correct?","o":["NILERD, formerly known as the Institute of Applied Manpower Research (IAMR), was established in 1962 and is a central autonomous organisation functioning under NITI Aayog","NILERD is a statutory body created by an Act of Parliament in 2014","NILERD is an attached office of NITI Aayog formed by merging the Programme Evaluation Organization and the Independent Evaluation Office","NILERD was established in 2015 as the successor to the Development Monitoring and Evaluation Office"],"a":0,"e":"NILERD (renamed from IAMR in 2014) is a central autonomous body under NITI Aayog, originally established in 1962 under the Societies Registration Act — it is not a statutory Act-created body, and it is the DMEO (not NILERD) that was formed by merging the Programme Evaluation Organization and Independent Evaluation Office."})

upsc.append({"q":"Which one of the following statements about NILERD is NOT correct?","o":["NILERD's headquarters has always been located in Central Delhi and has never been relocated since its founding","NILERD's primary objectives include research, data collection, education and training in human capital planning and human resource development","NILERD is mainly funded by grants-in-aid from NITI Aayog, supplemented by revenue from its own contracted research and training activities","The Institute moved to its own campus at Narela, a special economic zone for knowledge in the National Capital Region, in 2002"],"a":0,"e":"This statement is incorrect — NILERD (as IAMR) relocated to its own campus at Narela in 2002; it was not perpetually headquartered in Central Delhi. The other three statements about its funding, objectives, and Narela relocation are correct."})

upsc.append({"q":"Which one of the following statements about the erstwhile Planning Commission's origins is correct?","o":["The Planning Commission was established in March 1950 by an executive resolution of the Government of India, on the recommendation of the Advisory Planning Board (constituted in 1946) chaired by K.C. Neogy","The Planning Commission was established by an Act of Parliament in 1950, based on the recommendations of the Sapru Committee","The Planning Commission was established in 1952 on the recommendation of the National Development Council","K.C. Neogy chaired the Planning Commission itself as its first Deputy Chairman"],"a":0,"e":"The Planning Commission (March 1950, an executive resolution, not a statute) followed the recommendation of the 1946 Advisory Planning Board chaired by K.C. Neogy — the same K.C. Neogy who later became the First Finance Commission's chairman, not the Planning Commission's Deputy Chairman, and not linked to the Sapru Committee or the NDC (which came later, in 1952)."})

upsc.append({"q":"Consider the following statements about the composition of the erstwhile Planning Commission:\n1. The Prime Minister was its chairman and presided over its meetings.\n2. It had a Deputy Chairman who served as its de facto full-time executive head.\n3. State governments were directly represented in the Commission through their Chief Ministers.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 only"],"a":0,"e":"Statements 1 and 2 are correct, but statement 3 is false — the erstwhile Planning Commission had NO state government representation at all; it was wholly a Centre-constituted body, unlike the National Development Council or NITI Aayog's Governing Council."})

upsc.append({"q":"Which one of the following was NOT among the critical descriptions applied to the erstwhile Planning Commission by its critics?","o":["The 'Rubber Stamp Cabinet'","The 'Super Cabinet'","The 'Parallel Cabinet'","The 'Fifth Wheel of the Coach'"],"a":0,"e":"Critics variously described the Planning Commission as a 'Super Cabinet', 'Economic Cabinet', 'Parallel Cabinet' and the 'Fifth Wheel of the Coach' — but 'Rubber Stamp Cabinet' was not among these actual descriptions used."})

upsc.append({"q":"Which one of the following statements about criticisms of the erstwhile Planning Commission's domineering role is NOT correct?","o":["K. Santhanam observed that the Planning Commission had strengthened federalism and made India function more like a genuine federation","The First Administrative Reforms Commission observed that the Planning Commission had, in some measure, earned the reputation of being a 'Parallel Cabinet' and sometimes a 'Super Cabinet'","K. Santhanam observed that planning had superseded federation and that the country was functioning like a unitary system in many respects","Dr. P.V. Rajamannar observed an overlapping of functions between the erstwhile Planning Commission and the Finance Commission in federal fiscal transfers"],"a":0,"e":"This statement is incorrect and reverses K. Santhanam's actual view — he argued planning had SUPERSEDED federation, making India function more like a UNITARY system, not that it had strengthened federalism. The other three statements accurately reflect the cited criticisms."})

upsc.append({"q":"Which one of the following statements about the National Development Council (NDC) is correct?","o":["The NDC was established in August 1952 by an executive resolution on the recommendation of the First Five Year Plan's draft outline, and is neither a constitutional nor a statutory body","The NDC was established by a constitutional amendment in 1952 and is thus a constitutional body","The NDC's composition never included Union Cabinet Ministers, being restricted to the Prime Minister and Chief Ministers alone","The NDC was formally abolished by a Cabinet resolution in January 2016, with its powers transferred to the NITI Aayog Governing Council"],"a":0,"e":"The NDC (established August 1952 by executive resolution, non-constitutional/non-statutory) has NOT been formally abolished — as of the text, a proposed 2016 transfer of its powers to NITI Aayog's Governing Council was reported but no such resolution has actually been passed. Also, all Union Cabinet Ministers have been NDC members since 1967."})

upsc.append({"q":"Which one of the following statements about the National Development Council's last meeting is correct?","o":["The 57th and last meeting of the NDC was held on 27 December 2012 to approve the Twelfth Five Year Plan (2012-2017)","The NDC last met in January 2015, immediately before NITI Aayog's establishment, to formally dissolve itself","The NDC has never held any meeting after the establishment of NITI Aayog, having been abolished simultaneously with the Planning Commission in 2014","The 57th meeting of the NDC approved the Eleventh Five Year Plan (2007-2012)"],"a":0,"e":"The text specifically records the NDC's 57th (and till now, last) meeting on 27 December 2012, held to approve the TWELFTH Five Year Plan (2012-2017) — not the Eleventh Plan, a 2015 dissolution meeting, or simultaneous abolition with the Planning Commission."})

upsc.append({"q":"Consider the following statements regarding NITI Aayog's guiding principles as laid out in its founding document:\n1. 'Antyodaya' reflects Pandit Deendayal Upadhyay's idea of prioritising the upliftment of the poorest and most marginalised.\n2. 'Village' emphasises integrating villages into the development process.\n3. These guiding principles were formally notified as a Presidential Regulation under Article 77.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1, 2 and 3","2 and 3 only","1 and 3 only"],"a":0,"e":"Statements 1 and 2 correctly describe two of NITI Aayog's seven guiding principles (Antyodaya and Village); statement 3 is false, as these are guiding principles from a Government of India policy document, not a Presidential Regulation under Article 77."})

upsc.append({"q":"Which one of the following is NOT one of NITI Aayog's indices launched to promote competitive federalism among States/UTs?","o":["The Foreign Direct Investment Confidence Index","The School Education Quality Index","The Composite Water Management Index","The India Innovation Index"],"a":0,"e":"NITI Aayog has launched indices such as the School Education Quality Index, State Health Index, Composite Water Management Index, SDG Index, India Innovation Index and Export Competitiveness Index to encourage healthy inter-state competition — but a 'Foreign Direct Investment Confidence Index' is not among NITI Aayog's stated indices."})

upsc.append({"q":"Which one of the following statements about NITI Aayog's cooperative federalism initiatives is correct?","o":["Development Support Services to States and Union Territories (DSSS) and the Sustainable Action for Transforming Human Capital (SATH) programme are among NITI Aayog's Centre-state partnership models","DSSS and SATH are programmes exclusively run by the erstwhile Planning Commission and were discontinued after 2015","SATH stands for 'State Aid for Transformative Housing', a rural housing scheme unrelated to human capital","DSSS is a scheme for direct cash transfers to States, bypassing all NITI Aayog technical advice functions"],"a":0,"e":"DSSS and SATH are genuinely NITI Aayog-established Centre-state partnership/technical-advice models for infrastructure development and human capital transformation respectively — not Planning Commission legacy schemes, a housing scheme, or a cash-transfer mechanism."})

upsc.append({"q":"Which one of the following statements about the Development Monitoring and Evaluation Office's (DMEO) predecessor bodies is correct?","o":["The Programme Evaluation Organization was established in 1952 for independent impact evaluation of Central Government-funded programmes, and the Independent Evaluation Office was established in 2010 to accord more functional autonomy to this mechanism, before both were merged into DMEO in 2015","The Programme Evaluation Organization was established in 2010 and the Independent Evaluation Office in 1952, in reverse chronological order to what is commonly assumed","DMEO was established before either the Programme Evaluation Organization or the Independent Evaluation Office existed","The Regional Development Monitoring and Evaluation Offices (RDMEOs) continue to function actively across 15 regions to this day"],"a":0,"e":"The correct chronology is Programme Evaluation Organization (1952) followed by the Independent Evaluation Office (2010) for greater functional autonomy, with both merged to form DMEO in 2015 — and the RDMEOs (15 regional offices) were actually closed in 2017, with staff transferred to DMEO's Delhi headquarters, not still functioning today."})

upsc.append({"q":"Which one of the following statements about the erstwhile Planning Commission's own functions is NOT correct?","o":["The Planning Commission had executive responsibility for implementing the Five Year Plans directly, without depending on the Central and State Governments","The Planning Commission was to make an assessment of the material, capital and human resources of the country and investigate possibilities of augmenting them","The Planning Commission was to determine priorities and define the stages in which the plan should be carried out","The Planning Commission was only a staff agency with an advisory role and had no executive responsibility of its own"],"a":0,"e":"This statement is incorrect and directly contradicts the text — the Planning Commission was explicitly only a staff/advisory agency with NO executive responsibility; implementation responsibility rested with the Central and State Governments, not the Commission itself. The other statements correctly describe its assessment/prioritisation functions."})

upsc.append({"q":"Which one of the following statements about the rationale for replacing the Planning Commission with NITI Aayog, as articulated by the Union Government, is correct?","o":["The Union Government characterised the Planning Commission as having become a redundant organisation suited to a command economy, unfit for India's diversified, competitive, globalised economic context","The Union Government held that the Planning Commission's 'one-size-fits-all' approach remained fully suited to India's diversified economy and needed no change","NITI Aayog was created specifically to reintroduce a centre-to-state one-way flow of policy, reversing the direction NITI itself claims to pursue","The rationale document explicitly rejected any 'bottom-up' approach in favour of continuing the Planning Commission's 'top-down' model"],"a":0,"e":"Then-Finance Minister Arun Jaitley's remarks and the official rationale document explicitly criticised the Planning Commission as redundant for a command-economy era and called for moving away from the 'one-size-fits-all', 'top-down', one-way Centre-to-State policy flow — the exact opposite of the other three options."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch56_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
