import json

upsc = []

# ==================================================================
# NEW UPSC TIER: CHIEF MINISTER (Ch.31) + STATE COUNCIL OF MINISTERS (Ch.32)
# ==================================================================

upsc.append({"q":"According to the Sarkaria Commission's recommended order of preference for the Governor in selecting a Chief Minister when no single party has an absolute majority, which one of the following correctly orders the categories from first to last preference?","o":["Pre-electoral alliance; largest single party staking claim with outside support; post-electoral coalition with all partners in government; post-electoral alliance with some parties in government and others supporting from outside","Largest single party staking claim; pre-electoral alliance; post-electoral alliance with some parties in government; post-electoral coalition with all partners in government","Post-electoral coalition with all partners in government; pre-electoral alliance; largest single party staking claim; post-electoral alliance with outside support","Post-electoral alliance with outside support; post-electoral coalition; largest single party staking claim; pre-electoral alliance"],"a":0,"e":"The Sarkaria Commission's recommended order is: (1) a pre-electoral alliance of parties, (2) the largest single party staking a claim with outside/independent support, (3) a post-electoral coalition with all partners joining the government, and (4) a post-electoral alliance with some parties in government and others supporting from outside — in that specific order of preference."})

upsc.append({"q":"Which one of the following statements about the Sarkaria Commission's recommendations on Chief Minister selection is NOT correct?","o":["The Governor's task, per the Commission, is to identify and appoint a Chief Minister who will pursue policies that the Governor personally approves of","If a single party has an absolute majority in the Assembly, the leader of that party should automatically be asked to become Chief Minister","A Chief Minister, unless leading a party with an absolute majority, should seek a vote of confidence within 30 days of taking office","When rival claims to majority support are contested, the Governor should have them tested on the floor of the House rather than determining the issue independently"],"a":0,"e":"This statement is incorrect and reverses the Commission's actual recommendation — the Governor's task is merely to ensure a government is FORMED, not to try to form one that pursues policies the Governor personally approves of. The other three statements correctly reflect the Commission's recommendations."})

upsc.append({"q":"Consider the following statements about the Chief Minister's roles beyond the state government:\n1. The Chief Minister acts as vice-chairman of the concerned zonal council by rotation, holding office for one year at a time.\n2. The Chief Minister is a member of the Inter-State Council and the Governing Council of NITI Aayog, both headed by the Prime Minister.\n3. The Chief Minister also serves as the chairman of the State Planning Board.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — the Chief Minister serves as zonal council vice-chairman by rotation (with the Union Home Minister as chairman of all zonal councils), sits on the PM-headed Inter-State Council and NITI Aayog Governing Council, and chairs the State Planning Board."})

upsc.append({"q":"Which one of the following statements about a Chief Minister who is not a member of the state legislature at the time of appointment is NOT correct?","o":["Such a person can continue as Chief Minister indefinitely without ever becoming a member of the state legislature, provided the Governor's confidence continues","Such a person can be appointed Chief Minister for up to six months, within which time he/she must be elected to the state legislature","If such a person fails to get elected to the state legislature within six months, he/she ceases to be Chief Minister","A Chief Minister may be a member of either House of the state legislature, though most have historically come from the Legislative Assembly"],"a":0,"e":"This statement is incorrect — a person appointed Chief Minister without being a member of the state legislature must get elected within six months, failing which they cease to hold the office; continuing indefinitely without election is not permitted. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the mandatory Tribal Welfare Minister provision under Article 164(1) is NOT correct?","o":["This provision currently applies to Bihar, Chhattisgarh, Jharkhand, Madhya Pradesh and Odisha, with no state ever having been exempted from it","The 94th Constitutional Amendment Act, 2006 exempted Bihar from this requirement, since it has no Scheduled Areas and a very small Scheduled Tribe population","The 94th Amendment extended the requirement to the newly formed states of Chhattisgarh and Jharkhand","This Minister may, in addition to tribal welfare, also be in charge of welfare of Scheduled Castes and Backward Classes, or any other work"],"a":0,"e":"This statement is incorrect — Bihar was originally covered by this provision but was EXEMPTED by the 94th Amendment Act, 2006; the provision currently applies to Chhattisgarh, Jharkhand, Madhya Pradesh and Odisha, not Bihar. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the three categories of ministers in a state Council of Ministers is NOT correct?","o":["Ministers of State are full members of the cabinet and attend all cabinet meetings as a matter of right, on par with cabinet ministers","Cabinet Ministers head important departments (such as home, education, finance) and are members of the cabinet","Ministers of State may be given independent charge of departments or attached to cabinet ministers, but are not cabinet members","Deputy Ministers are not given independent charge of departments and are attached to cabinet ministers to assist them"],"a":0,"e":"This statement is incorrect and reverses the actual hierarchy — Ministers of State are NOT members of the cabinet and do NOT attend cabinet meetings as a matter of right (only when specially invited for matters concerning their department); only Cabinet Ministers are full cabinet members. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the state Cabinet's role, as distinguished from the full Council of Ministers:\n1. The Cabinet is the highest decision-making authority in a state's politico-administrative system.\n2. The Cabinet exercises control over higher appointments like constitutional authorities and senior secretariat administrators.\n3. The Cabinet, being a smaller body, has no advisory role towards the Governor and functions entirely independently of gubernatorial oversight.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Cabinet's listed roles explicitly include being an ADVISORY BODY to the Governor, among its eight functions (highest decision-making authority, chief policy-formulating body, supreme executive authority, chief coordinator, advisory body to the governor, chief crisis manager, handling legislative/financial matters, and control over higher appointments). Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about 'individual responsibility' of a state minister under Article 164 is NOT correct?","o":["The Governor can remove any minister at will, entirely independent of and without regard to the advice of the Chief Minister","Ministers hold office during the pleasure of the Governor, meaning the Governor can in principle remove a minister even while the council enjoys the Assembly's confidence","The Governor can remove a minister only on the advice of the Chief Minister","This mechanism allows the Chief Minister to enforce collective responsibility by having a dissenting minister removed"],"a":0,"e":"This statement is incorrect and omits the critical constraint — the Governor can remove a minister ONLY ON THE ADVICE OF THE CHIEF MINISTER, not independently at the Governor's own will. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about 'legal responsibility' of ministers in the Indian states is correct?","o":["There is no provision in the Constitution for legal responsibility of ministers in the states, unlike some other parliamentary systems that require countersignature of executive orders","A Governor's public act requires countersignature by a minister to be legally valid, similar to certain other Westminster-style systems","Courts can freely enquire into the nature of advice rendered by ministers to the Governor to establish legal responsibility","Legal responsibility exists at the state level but not at the Centre, creating an asymmetry between Union and state ministerial accountability"],"a":0,"e":"The text explicitly states there is no system of legal responsibility of ministers in the states (as at the Centre) — a Governor's public act does not require ministerial countersignature, and courts are barred from enquiring into the advice rendered by ministers to the Governor. The other three options misstate this position."})

upsc.append({"q":"Consider the following statements about the collective responsibility of a state Council of Ministers:\n1. When the Legislative Assembly passes a no-confidence motion against the Council of Ministers, all ministers must resign, including those who are members of the Legislative Council.\n2. Cabinet decisions bind all ministers even if a minister personally disagreed during the cabinet meeting, obligating them to publicly defend the decision or resign.\n3. Each minister must submit an individual, separate letter of resignation to the Governor; the Chief Minister's resignation alone does not automatically dissolve the council.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the actual rule — the Chief Minister's resignation (or death) BY ITSELF amounts to the resignation of the entire council of ministers; individual ministers need not resign separately. Statements 1 and 2 correctly describe collective responsibility."})

upsc.append({"q":"Which one of the following statements about Article 166 (Conduct of Business of the Government of a State) is NOT correct?","o":["All executive action of a State Government must be expressed to be taken in the name of the Chief Minister, not the Governor","Orders and instruments made in the Governor's name must be authenticated as specified in rules made by the Governor","The validity of a duly authenticated order cannot be questioned merely on the ground that it was not made or executed by the Governor personally","The Governor makes rules for convenient transaction of state government business and for allocating business among ministers (except discretionary matters)"],"a":0,"e":"This statement is incorrect and reverses the actual provision — Article 166 requires all executive action to be expressed as taken in the name of the GOVERNOR (the nominal/constitutional head), not the Chief Minister. The other three statements correctly describe Article 166's provisions."})

upsc.append({"q":"Which one of the following statements about the term 'ministry' versus 'department' in Indian governmental usage, per the text, is correct?","o":["The term 'ministry' or 'ministries' is used only at the Centre; state governments are divided into 'departments', not ministries","Both the Centre and the states use the term 'ministry' interchangeably with 'department' without any distinction in usage","The term 'department' is used only at the Centre, while states use 'ministry' exclusively","Neither the Centre nor the states use the term 'ministry'; both use 'department' exclusively in official terminology"],"a":0,"e":"The text explicitly notes that the term 'ministry'/'ministries' is used only at the Centre, while state governments are organisationally divided into 'departments', not ministries — a specific terminological distinction, not interchangeable or reversed usage."})

upsc.append({"q":"Assertion (A): The nature of advice tendered by ministers to the Governor cannot be enquired into by any court.\nReason (R): This provision, combined with the Governor's discretion being final and unquestionable on that specific ground, is meant to emphasise the intimate and confidential relationship between the Governor and the Council of Ministers.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — Article 163's bar on judicial enquiry into ministerial advice, together with the finality of the Governor's discretion determination, is explicitly described in the text as emphasising the confidential, intimate working relationship between the Governor and the Council of Ministers."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch31_32_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
