import json

upsc = []

# ==================================================================
# NEW UPSC TIER: JUDICIAL ACTIVISM (Ch.28) + PUBLIC INTEREST LITIGATION (Ch.29)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the origins of judicial activism is NOT correct?","o":["Judicial activism originated and developed first in India before being adopted by the United States","The term 'judicial activism' was first coined in 1947 by Arthur Schlesinger Jr., who introduced it in an article on the American Supreme Court published in Fortune magazine","In India, the doctrine of judicial activism was introduced in the mid-1970s","Justice V.R. Krishna Iyer, Justice P.N. Bhagwati, Justice O. Chinnappa Reddy and Justice D.A. Desai laid the foundations of judicial activism in India"],"a":0,"e":"This statement is incorrect and reverses the actual origin — judicial activism originated and developed FIRST IN THE USA, with the term coined in 1947 by Arthur Schlesinger Jr.; India adopted the doctrine later, in the mid-1970s. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the two major aspects of judicial activism followed by the Indian judiciary:\n1. The first aspect comes through directions issued by courts to government authorities for protecting citizens' rights and public interest, exemplified by Public Interest Litigation.\n2. The second aspect lies in the interpretation of Fundamental Rights, particularly Articles 14, 19 and 21, where courts have expanded the scope of these rights.\n3. Judicial activism in India is confined exclusively to civil disputes between private parties and has no bearing on Fundamental Rights interpretation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — judicial activism's second major aspect is precisely the expanded interpretation of Fundamental Rights (Articles 14, 19, 21), not a confinement to private civil disputes. Statements 1 and 2 correctly describe the two aspects identified in the text."})

upsc.append({"q":"Which one of the following best captures the distinction between 'judicial review' and 'judicial activism' as explained in the text?","o":["Judicial review is interpretation of law within constitutional parameters, while judicial activism involves moulding the law to suit changing social and economic conditions, making constitutional ideals meaningful and real","Judicial review and judicial activism are entirely unrelated concepts with no conceptual overlap whatsoever","Judicial activism is a narrower, purely procedural subset of judicial review with no scope for policy-making by judges","Judicial review refers only to executive action, while judicial activism refers only to legislative action"],"a":0,"e":"The text explicitly distinguishes the two: judicial review is interpreting law against constitutional parameters, while judicial activism goes further — moulding the law to changing social/economic scenarios so constitutional ideals become meaningful in practice — making the concepts closely related, not unrelated or narrower/broader in the other senses listed."})

upsc.append({"q":"According to Dr. B.L. Wadehra, which of the following is NOT cited as a reason for judicial activism in India?","o":["A constitutional mandate requiring the judiciary to review at least 10 percent of all legislative enactments annually, regardless of any other consideration","Near collapse of responsible government, when the Legislature and Executive fail to discharge their functions","Citizens' pressure on the judiciary to protect their rights and freedoms when other organs fail","Legislative vacuum in certain areas, prompting courts to indulge in judicial legislation to meet changing social needs"],"a":0,"e":"This is NOT a reason cited by Wadehra — there is no such fixed constitutional review quota; Wadehra's actual reasons include near-collapse of responsible government, citizen pressure on the judiciary, judicial enthusiasm, legislative vacuum, and constitutional provisions enabling an active judicial role."})

upsc.append({"q":"Consider the following statements about Subhash Kashyap's eventualities justifying judicial 'overstepping' into legislative/executive domains:\n1. A 'hung' legislature producing a weak government unable to take decisions displeasing any group.\n2. Those in power referring public issues to courts to delay decisions or pass on the odium of hard decision-making.\n3. Situations where courts themselves might become victims of a 'craze for populism, publicity, playing to the media'.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct and match Kashyap's listed eventualities/observations, including his caution (echoed by the text) about courts themselves becoming susceptible to publicity-seeking tendencies as a risk associated with judicial activism."})

upsc.append({"q":"Match List-I (Upendra Baxi's Activator Group) with List-II (Focus Area) and select the correct answer using the code below.\nList-I:\nA. People Rights Activists\nB. Consumer Rights Groups\nC. Indigenous People's Rights Groups\nD. Custodial Rights Groups\nList-II:\n1. Prisoners' rights, women under state 'protective' custody, and persons under preventive detention\n2. Forest dwellers, citizens of the Fifth and Sixth Schedules, and identity rights\n3. Accountability of the polity and economy in matters of consumer rights\n4. Social and economic rights within the context of state repression of people's movements\nCodes:","o":["A-4, B-3, C-2, D-1","A-4, B-3, C-1, D-2","A-3, B-4, C-2, D-1","A-4, B-2, C-3, D-1"],"a":0,"e":"The correct match is A-4, B-3, C-2, D-1: People Rights Activists focus on social/economic rights amid state repression; Consumer Rights Groups raise accountability issues in consumer matters; Indigenous People's Rights Groups address forest dwellers and Fifth/Sixth Schedule areas; and Custodial Rights Groups cover prisoners and persons in preventive detention."})

upsc.append({"q":"Which one of the following is NOT among Upendra Baxi's typology of 'fears' generated by judicial activism?","o":["Electoral fears — concern that judicial activism might directly reduce a judge's chances of being elected to a future political office","Ideological fears — concern about judges usurping powers of the legislature, executive, or other autonomous civil society institutions","Legitimation fears — concern that public interest litigation orders bypassed or ignored by the executive might erode people's faith in the judiciary","Biographic fears — concern about a judge's own place in national affairs after superannuation if they 'overdo' such litigation"],"a":0,"e":"This is NOT one of Baxi's six fear categories — judges in India are not elected, so 'electoral fears' about election chances is not a real category Baxi describes; his actual typology includes ideological, epistemic, management, legitimation, democratic, and biographic fears."})

upsc.append({"q":"Which one of the following statements about the doctrine of 'judicial restraint' is NOT correct?","o":["Judicial restraint holds that judges should exercise maximal, unconstrained discretion in shaping social policy, unbound by considerations of legislative or executive domains","Judicial restraint is also known as the antithesis of judicial activism, sometimes called 'judicial dynamism'","One assumption underlying judicial restraint in the USA is that courts are basically undemocratic since they are non-elective and not directly responsive to popular will","Another assumption is the separation of powers doctrine, requiring courts to defer to the legislature and executive within their own domains"],"a":0,"e":"This statement is incorrect and reverses the actual meaning — judicial restraint holds that judges' roles should be SCRUPULOUSLY LIMITED, confined to saying what the law is rather than exercising broad policy-making discretion; that description instead fits judicial activism (the antithesis of restraint). The other three statements are correct."})

upsc.append({"q":"With reference to the Supreme Court's December 2007 observations calling for judicial restraint, consider the following statements:\n1. The Bench observed that 'judicial activism must not become judicial adventurism.'\n2. The Bench held that if the legislature or executive is not functioning properly, the remedy lies in the judiciary permanently taking over their functions.\n3. The Bench quoted Montesquieu's 'The Spirit of Laws' on the consequences of not maintaining separation of powers.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect and reverses the Bench's actual holding — the Court explicitly said the remedy is NOT for the judiciary to take over legislative/executive functions, since that would violate the constitutional balance of power and the judiciary lacks the expertise/resources; instead, the remedy lies with the people exercising their franchise properly. Statements 1 and 3 are correct."})

upsc.append({"q":"Which one of the following statements about the origin of Public Interest Litigation (PIL) is NOT correct?","o":["PIL originated and developed in India in the 1960s before being adopted by the United States in the early 1980s","PIL in the USA was designed to provide legal representation to previously unrepresented groups such as the poor, environmentalists, consumers and racial/ethnic minorities","In India, PIL was introduced in the early 1980s, pioneered by Justice V.R. Krishna Iyer and Justice P.N. Bhagwati","PIL is also known as Social Action Litigation (SAL), Social Interest Litigation (SIL) and Class Action Litigation (CAL)"],"a":0,"e":"This statement is incorrect and reverses the actual chronology — PIL originated and developed in the USA in the 1960s, and was introduced in India only later, in the early 1980s, not the reverse. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the traditional rule of 'locus standi' and its relaxation under PIL:\n1. Under the traditional rule, only a person whose own rights are infringed can move the court for remedies.\n2. Under PIL, any public-spirited citizen or social organisation can move the court on behalf of persons unable to approach the court themselves due to poverty, ignorance, or social/economic disadvantage.\n3. The relaxation of locus standi under PIL applies only to disputes purely in the realm of private law between two warring individual parties.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text explicitly states that a dispute between two warring groups purely in the realm of private law would NOT be allowed to be agitated as a PIL; the relaxation is meant for matters of public interest, not private disputes. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following categories of petitions is explicitly listed by the Supreme Court's guidelines as one that will NOT ordinarily be entertained as a PIL?","o":["Landlord-tenant matters","Petitions pertaining to environmental pollution and disturbance of ecological balance","Petitions against police for refusing to register a case or harassment by police","Petitions complaining of bonded labour matters"],"a":0,"e":"Landlord-tenant matters are explicitly listed among the categories the Supreme Court's guidelines say will NOT ordinarily be entertained as PIL, along with service/pension matters, complaints against government departments (except listed categories), admission to educational institutions, and petitions for early hearing of pending cases. The other three options are categories that ARE entertained as PIL."})

upsc.append({"q":"Which one of the following case citations is correctly matched with its role in shaping Supreme Court guidelines/principles on PIL?","o":["State of Uttaranchal vs. Balwant Singh Chaupal (2010) — laid down guidelines for checking the misuse of PIL","BALCO Employees Union vs. Union of India (2001) — formulated the original 1988 guidelines on categories of letters/petitions to be entertained as PIL","Guruvayur Devaswom Managing Committee vs. C.K. Rajan (2003) — coined the term 'Public Interest Litigation' for the first time in Indian jurisprudence","S.P. Gupta vs. Union of India (1981) — evolved the Supreme Court's principles regarding PIL under Articles 32 and 226"],"a":0,"e":"The correct match is State of Uttaranchal vs. Balwant Singh Chaupal (2010), which laid down guidelines for checking misuse of PIL. BALCO Employees Union (2001) is cited for the Court's warning against PIL being turned into 'Publicity/Politics/Private Interest Litigation'; Guruvayur Devaswom (2003) is cited for the Court's principles on PIL under Articles 32/226; and the 1988/1993/2003 guidelines on categories of PIL are separate from these specific case citations."})

upsc.append({"q":"Which one of the following statements about the misuse of PIL, per the Supreme Court's own observations, is NOT correct?","o":["The Supreme Court has held that PIL should be actively encouraged regardless of the petitioner's credentials or motives, since verifying bona fides would defeat its accessible, informal character","The Court observed that PIL should not be allowed to become 'Publicity Interest Litigation', 'Politics Interest Litigation', 'Private Interest Litigation' or 'Paisa Interest Litigation'","The Court should prima facie verify the credentials of the petitioner before entertaining a PIL","The Court should ensure there is no personal gain, private motive, or oblique motive behind the filing of a PIL"],"a":0,"e":"This statement is incorrect and reverses the Court's actual guidance — the Supreme Court explicitly directed courts to verify petitioner credentials, discourage PIL filed for extraneous/oblique motives, and impose exemplary costs on frivolous petitions filed by 'busybodies', not to admit every PIL uncritically. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch28_29_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
