import json

upsc = []

# ==================================================================
# NEW UPSC TIER: UPSC (Ch.44) + STATE PUBLIC SERVICE COMMISSION (Ch.45)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the composition requirements of the UPSC and a SPSC is NOT correct?","o":["The Constitution requires ALL members of the Commission (UPSC or SPSC) to have held office for at least ten years under the Government of India or a state government","No qualifications are prescribed for Commission membership, except that one-half of the members should have held office for at least ten years under the Government of India or a state government","The Constitution does not specify the strength (number of members) of either the UPSC or a SPSC, leaving this to the President's or Governor's discretion respectively","The President/Governor also determines the number of staff members of the Commission and their conditions of service"],"a":0,"e":"This statement is incorrect — the ten-year government service requirement applies to only ONE-HALF of the Commission's members, not all of them. The other three statements are correct."})

upsc.append({"q":"Which one of the following is NOT among the matters on which the UPSC is explicitly NOT consulted (i.e., kept outside its functional jurisdiction)?","o":["Disciplinary matters affecting a person serving under the Government of India in a civil capacity","Selection for a temporary/officiating appointment expected to last less than one year, where a UPSC reference would cause undue delay contrary to public interest","Appointments to a bulk of Group C and Group D Central Services","Appointments to the posts of Heads of Diplomatic, Consular and similar Indian Missions abroad"],"a":0,"e":"This IS a matter on which the UPSC IS consulted (per its listed functions on disciplinary matters affecting civil servants) — it is not one of its excluded/limitation areas. The other three options are genuine limitations explicitly kept outside UPSC's jurisdiction."})

upsc.append({"q":"Which one of the following statements about the difference in the UPSC's and a SPSC's list of 'excluded' matters (limitations) is correct?","o":["The UPSC's limitations list is considerably longer (including temporary appointments, Group C/D posts, board/tribunal chairmen, and diplomatic posts, besides backward class/SC-ST reservations), whereas the SPSC's limitations, as listed in the text, are confined to backward class reservations and SC/ST claims in appointments","The SPSC's limitations list is longer than the UPSC's, since states have more categories of exempted posts","Both the UPSC and SPSC have textually identical, equally long limitations lists with no differences","Neither the UPSC nor SPSC has any limitations on its functional jurisdiction"],"a":0,"e":"The text explicitly lists six limitation categories for the UPSC (including temporary appointments, Group C/D bulk posts, board/tribunal chairmen, diplomatic heads, plus backward class/SC-ST matters) but only two for the SPSC (backward class reservations and SC/ST claims) — a real asymmetry in the text's treatment of the two Commissions' limitations."})

upsc.append({"q":"Which one of the following statements about the 'UPSC (Exemption from Consultation) Regulations, 1958' is correct?","o":["These regulations, made by the President, specify matters in which UPSC consultation is not necessary, and must be laid before each House of Parliament for at least 14 days, with Parliament empowered to amend or repeal them","These regulations were made by the Chief Justice of India and require no parliamentary oversight","These regulations completely abolished the UPSC's advisory role in all recruitment matters","These regulations were struck down as unconstitutional by the Supreme Court shortly after their enactment"],"a":0,"e":"The Constitution empowers the President to make regulations (for all-India/Central services) specifying matters exempted from UPSC consultation, subject to being laid before Parliament for at least 14 days and Parliament's power to amend/repeal — not any of the other incorrect characterisations."})

upsc.append({"q":"Which one of the following statements about the distinction between the UPSC and the Department of Personnel and Training (DoPT) is correct?","o":["The UPSC is only a central recruiting agency (concerned mainly with recruitment, promotion and disciplinary advice), while the DoPT is the central personnel agency handling classification of services, pay, cadre management and training","The UPSC and DoPT perform identical functions and are simply two names for the same body","The DoPT is a constitutional body created directly by Articles 315-323, just like the UPSC","The UPSC handles cadre management and training, while the DoPT handles recruitment examinations"],"a":0,"e":"The text draws this precise distinction: the UPSC (a constitutional recruiting body) is not concerned with classification of services, pay, cadre management or training — these fall under the DoPT (part of the Ministry of Personnel, Public Grievances and Pensions), which is the central personnel agency, not a constitutional body."})

upsc.append({"q":"Which one of the following statements about the relationship between the UPSC and the Central Vigilance Commission (CVC) in disciplinary matters is NOT correct?","o":["The CVC, being an older and more powerful constitutional body, has a clear edge over the UPSC whenever their advice on a disciplinary matter conflicts","Both bodies are consulted by the government while taking disciplinary action against a civil servant, which can create conflicting advice","The CVC was originally created by an executive resolution of the Government of India in 1964 and was given statutory status only in 2003","The UPSC, being an independent constitutional body, has an edge over the CVC when their advice conflicts"],"a":0,"e":"This statement is incorrect and reverses the actual position — it is the UPSC (a constitutional body under Articles 315-323) that has the edge over the CVC (created by executive resolution in 1964, given statutory status only in 2003), not the other way around. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the case concerning appointment of a former UPSC Chairman as a State Governor is correct?","o":["In 1979, the Supreme Court upheld the appointment of A.R. Kidwai, a former UPSC Chairman, as Governor of Bihar, ruling that the office of Governor is a 'constitutional office' and not 'employment' under the government","The Supreme Court struck down A.R. Kidwai's appointment as Governor, holding it violated Article 319's bar on further government employment for a former UPSC Chairman","The case concerned the appointment of a former Chief Election Commissioner, not a former UPSC Chairman, as Governor","The Court held that a former UPSC Chairman can never hold any public office of any kind after retirement"],"a":0,"e":"The 1979 Supreme Court ruling upheld A.R. Kidwai's appointment as Bihar's Governor precisely because it characterised the office of Governor as a 'constitutional office' rather than 'employment under the government', thereby not falling foul of Article 319's post-retirement employment bar."})

upsc.append({"q":"Which one of the following statements about the age limit for members of a State Public Service Commission is NOT correct?","o":["The age limit for SPSC members has always been fixed at 62 years since the Constitution's original commencement, with no subsequent amendment ever changing it","The current age limit is 62 years, which is lower than the UPSC's age limit of 65 years","The 41st Constitutional Amendment Act, 1976 raised the SPSC age limit from its original level to 62 years","Members hold office for a term of six years or until reaching the applicable age limit, whichever is earlier"],"a":0,"e":"This statement is incorrect — the SPSC age limit was ORIGINALLY 60 years and was raised to 62 by the 41st Constitutional Amendment Act, 1976; it was not fixed at 62 from the very beginning. The other three statements are correct."})

upsc.append({"q":"With reference to a 1993 Supreme Court ruling concerning appointment to a State Public Service Commission, which one of the following is correct?","o":["The Court ruled that the appointment of a university professor, known to be blind, as an SPSC member could not be set aside on the ground of 'infirmity of body or mind'","The Court held that blindness automatically disqualifies a person from being appointed as an SPSC member under the 'infirmity' ground for removal","The case concerned removal (not appointment) of a sitting SPSC chairman on health grounds","The ruling applied only to UPSC appointments and had no bearing on State Public Service Commissions"],"a":0,"e":"In 1993, the Supreme Court upheld the appointment of a blind university professor as an SPSC member, ruling that this did not amount to disqualifying 'infirmity of body or mind' — rejecting a challenge to the appointment rather than endorsing automatic disqualification or concerning removal of a sitting chairman."})

upsc.append({"q":"Which one of the following statements about a State Public Service Commission's role in judicial service appointments is correct?","o":["The Governor consults the SPSC (along with the concerned state High Court) while framing rules for appointment to the state's judicial service, other than the posts of district judges","The SPSC has no role whatsoever in any judicial service appointments at the state level","The SPSC alone (without any High Court involvement) frames all rules for judicial service appointments, including district judges","The SPSC's role in judicial appointments extends to district judge appointments, which are otherwise the High Court's exclusive domain"],"a":0,"e":"The text explicitly notes the SPSC is consulted by the Governor (alongside the state High Court) in framing rules for judicial service appointments EXCLUDING district judge posts — not a total absence of role, sole SPSC authority, or extension to district judge appointments (which fall under Articles 233-234, involving the Governor and High Court directly)."})

upsc.append({"q":"Which one of the following statements about a Joint State Public Service Commission (JSPSC) is NOT correct?","o":["A JSPSC is a constitutional body created directly by the Constitution, exactly like the UPSC and individual SPSCs","A JSPSC can be created by an Act of Parliament, on the request of the state legislatures of the concerned states","The chairman and members of a JSPSC are appointed by the President and can be suspended or removed by the President","A JSPSC presents its annual performance report to each of the concerned state Governors, who place it before their respective state legislatures"],"a":0,"e":"This statement is incorrect — unlike the UPSC and individual SPSCs (which ARE constitutional bodies created directly by the Constitution), a JSPSC is a STATUTORY body, created only by an Act of Parliament upon the request of the concerned states. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch44_45_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
