import json

upsc = []

# ==================================================================
# NEW UPSC TIER: UNION TERRITORIES (Ch.41)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the historical evolution of Union Territories is NOT correct?","o":["Union Territories were directly created as such by the original 1950 Constitution, with no prior colonial or Part C/Part D classification ever having existed","During British rule, certain areas were constituted as 'scheduled districts' in 1874, later known as 'chief commissioners provinces'","After independence, these areas were placed in the category of Part 'C' States and Part 'D' Territories","They were constituted as 'union territories' in 1956 by the 7th Constitutional Amendment Act and the States Reorganisation Act, 1956"],"a":0,"e":"This statement is incorrect — Union Territories evolved through a specific historical lineage (1874 scheduled districts, chief commissioners' provinces, then post-independence Part C/Part D classification), only being formally constituted as 'union territories' in 1956, not created directly as such by the original Constitution. The other three statements are correct."})

upsc.append({"q":"Match List-I (Union Territory/Reason Category) with List-II (Rationale for UT Status) and select the correct answer using the code below.\nList-I:\nA. Delhi and Chandigarh\nB. Puducherry and Dadra & Nagar Haveli and Daman & Diu\nC. Andaman & Nicobar Islands and Lakshadweep\nD. Mizoram, Manipur, Tripura and Arunachal Pradesh (formerly)\nList-II:\n1. Strategic importance\n2. Special treatment and care of backward and tribal people\n3. Political and administrative consideration\n4. Cultural distinctiveness\nCodes:","o":["A-3, B-4, C-1, D-2","A-3, B-1, C-4, D-2","A-4, B-3, C-1, D-2","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3, B-4, C-1, D-2: Delhi/Chandigarh were created for political-administrative reasons; Puducherry/DNHDD for cultural distinctiveness (former French/Portuguese possessions); Andaman & Nicobar/Lakshadweep for strategic importance; and Mizoram/Manipur/Tripura/Arunachal Pradesh (now states) for special care of backward/tribal populations."})

upsc.append({"q":"Consider the following statements about the 2019 bifurcation of the former state of Jammu and Kashmir, per reasons given by the government in Parliament:\n1. Ladakh's creation as a Union Territory was justified partly by its sparsely populated, difficult terrain and a long-pending local demand for UT status.\n2. The Union Territory of Ladakh was created with its own legislature.\n3. The creation of a separate Union Territory of Jammu and Kashmir (with a legislature) was partly justified by the prevailing internal security situation and cross-border terrorism.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the Union Territory of Ladakh was explicitly created WITHOUT a legislature, unlike the Union Territory of Jammu and Kashmir, which was given a legislature. Statements 1 and 3 correctly reflect the government's stated reasons."})

upsc.append({"q":"Which one of the following was NOT among the reasons cited by the government for merging the Union Territories of Dadra & Nagar Haveli and Daman & Diu in 2019-2020?","o":["The two territories had entirely separate administrative machinery, cultures and languages with no overlap, making a merger administratively difficult but symbolically important","The two territories shared common officers such as Secretaries, Chief of Police and Chief Conservator of Forest, and similar policies across sectors like tourism and education","Maintaining two separate secretariats and parallel departments caused duplication of infrastructure, manpower and unnecessary financial burden","The merger aligned with the government's policy of 'Minimum Government, Maximum Governance', given the small population and limited area of both territories"],"a":0,"e":"This is NOT a reason cited — the government's actual reasoning was the OPPOSITE: the two territories shared a lot in terms of administrative set-up, history, language and culture (common officers, similar policies), which was cited as a reason favouring merger, not a claim of entirely separate identities. The other three options are genuine reasons cited."})

upsc.append({"q":"Which one of the following statements about the office of 'Administrator' of a Union Territory is NOT correct?","o":["An Administrator is the constitutional head of a Union Territory in the same sense that a Governor is the constitutional head of a state","An Administrator is an agent of the President, and the President can designate this office as Lieutenant Governor, Chief Commissioner, or Administrator","The President can appoint the Governor of a state as the administrator of an adjoining Union Territory, in which capacity the Governor acts independently of the state's Council of Ministers","At present, the designation used is Lieutenant Governor for Delhi, Puducherry, Andaman and Nicobar Islands, Jammu and Kashmir and Ladakh, and Administrator for Chandigarh, Dadra and Nagar Haveli and Daman and Diu, and Lakshadweep"],"a":0,"e":"This statement is incorrect — an Administrator is explicitly described as an AGENT of the President, NOT a constitutional head like a Governor; this is one of the key distinctions between states and Union Territories. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the legislative powers of Union Territory assemblies with a legislature:\n1. The Puducherry assembly can make laws on any subject of the State List and the Concurrent List.\n2. The Delhi assembly can make laws on the State List and Concurrent List, except on public order, police and land.\n3. The Jammu and Kashmir assembly can make laws on the State List and Concurrent List, except on public order, police and land (identical restrictions to Delhi).\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the Jammu and Kashmir assembly's restriction excludes only public order and police (NOT land), unlike Delhi's assembly, which is additionally barred from legislating on land as well. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the President's power to make regulations under Article 240 is NOT correct?","o":["The President can make regulations for peace, progress and good government of Puducherry at any time, irrespective of whether its assembly is functioning or suspended","The President can make regulations for the Andaman and Nicobar Islands, Lakshadweep, Dadra and Nagar Haveli and Daman and Diu, and Ladakh","A regulation made by the President under Article 240 has the same force and effect as an Act of Parliament","Such a regulation can repeal or amend an Act of Parliament in relation to the concerned Union Territories"],"a":0,"e":"This statement is incorrect — for Puducherry specifically, the President can make regulations ONLY when its assembly is suspended or dissolved, not at any time irrespective of the assembly's functioning. The other three statements are correct."})

upsc.append({"q":"Match List-I (Union Territory) with List-II (High Court exercising jurisdiction) and select the correct answer using the code below.\nList-I:\nA. Chandigarh\nB. Lakshadweep\nC. Dadra and Nagar Haveli and Daman and Diu\nD. Andaman and Nicobar Islands\nList-II:\n1. Bombay High Court\n2. Kerala High Court\n3. Calcutta High Court\n4. Punjab and Haryana High Court\nCodes:","o":["A-4, B-2, C-1, D-3","A-4, B-1, C-2, D-3","A-3, B-2, C-1, D-4","A-4, B-2, C-3, D-1"],"a":0,"e":"The correct match is A-4, B-2, C-1, D-3: Chandigarh falls under Punjab and Haryana High Court, Lakshadweep under Kerala High Court, Dadra and Nagar Haveli and Daman and Diu under Bombay High Court, and Andaman and Nicobar Islands under Calcutta High Court. Delhi is the only UT with its own separate High Court (since 1966), and Jammu and Kashmir/Ladakh share a common High Court."})

upsc.append({"q":"Which one of the following statements about the National Capital Territory of Delhi's Council of Ministers, per the 69th Constitutional Amendment Act, 1991, is NOT correct?","o":["The Chief Minister of Delhi is appointed by the Lieutenant Governor, not the President, distinguishing Delhi's arrangement from that of the other ministers","The strength of the Council of Ministers is fixed at ten per cent of the Assembly's total strength, i.e., seven members (one Chief Minister and six other ministers)","The other ministers are appointed by the President on the advice of the Chief Minister","The ministers hold office during the pleasure of the President, and the Council of Ministers is collectively responsible to the Assembly"],"a":0,"e":"This statement is incorrect and reverses the actual position — the Chief Minister of Delhi is appointed by the PRESIDENT, not the Lieutenant Governor; only the other ministers are appointed by the President on the Chief Minister's advice, but the CM's appointment is likewise vested in the President. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Lieutenant Governor of Delhi's ordinance-making power is NOT correct?","o":["The Lieutenant Governor can promulgate an ordinance at any time, including when the Delhi Legislative Assembly stands dissolved or suspended, without any restriction","An ordinance promulgated by the Lieutenant Governor has the same force as an Act of the Assembly","Every ordinance must be approved by the Assembly within six weeks of its reassembly","No ordinance can be promulgated or withdrawn by the Lieutenant Governor without the prior permission of the President"],"a":0,"e":"This statement is incorrect and reverses the actual restriction — the Lieutenant Governor can promulgate an ordinance only during a RECESS of the Assembly, and explicitly CANNOT do so when the Assembly is dissolved or suspended. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the provision resembling Article 356 (President's Rule) as applicable to Delhi is correct?","o":["If the administration of Delhi cannot be carried on in accordance with the special constitutional provisions for Delhi, the President can suspend their operation and make necessary provisions, on the report of the Lieutenant Governor or otherwise","Such a provision does not exist for Delhi since it is a Union Territory and not a state, and Article 356 applies exclusively to states","This provision can be invoked only on the recommendation of the Delhi Legislative Assembly itself, never suo motu by the President","This provision, once invoked, is permanent and cannot be revoked even if normal administration is later restored"],"a":0,"e":"Article 239AB provides a mechanism resembling Article 356 specifically for Delhi — if the special constitutional machinery for Delhi's administration breaks down, the President can suspend its operation (based on the Lieutenant Governor's report or otherwise) and make alternative provisions, contrary to the other three incorrect claims."})

upsc.append({"q":"Which one of the following statements about the Home Minister's Advisory Committee (HMAC) and Administrator's Advisory Committee (AAC) is NOT correct?","o":["These committees exist for all eight Union Territories, including Delhi, Puducherry and Jammu and Kashmir, which already have their own elected legislatures and councils of ministers","HMAC is chaired by the Union Home Minister, while AAC is chaired by the Administrator of the concerned Union Territory","These committees exist for the five Union Territories without a legislature: Andaman and Nicobar Islands, Chandigarh, Dadra and Nagar Haveli and Daman and Diu, Lakshadweep and Ladakh","Members of Parliament and elected members of local bodies (District Panchayats and Municipal Councils) from the respective UTs are among the members of these committees"],"a":0,"e":"This statement is incorrect — HMAC/AAC exist specifically for the FIVE Union Territories WITHOUT a legislature, not for all eight; Delhi, Puducherry and Jammu and Kashmir already have elected legislative assemblies and councils of ministers and are not part of this forum. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements comparing States and Union Territories, per the book's comparison table, is NOT correct?","o":["Parliament cannot make laws on subjects of the State List in relation to Union Territories, just as it generally cannot for the states, except under extraordinary circumstances","States have autonomy while Union Territories do not have any autonomy","There is uniformity in the administrative set-up of states, but no such uniformity exists among Union Territories","States' relationship with the Centre is federal, while Union Territories' relationship with the Centre is unitary"],"a":0,"e":"This statement is incorrect and reverses the actual comparison — Parliament CAN make laws on ANY subject of the three lists (including the State List) in relation to Union Territories, unlike its generally restricted power over State List subjects for the states (barring extraordinary circumstances). The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch41_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
