import json

upsc = []

# ==================================================================
# NEW UPSC TIER: SPECIAL PROVISIONS FOR SOME STATES (Ch.78, Art.371-371J)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the special regime for the Tuensang district of Nagaland under Article 371A is NOT correct?","o":["Members representing the Tuensang district in the Nagaland Legislative Assembly are directly elected by the people of the district, exactly like members from the rest of Nagaland","A regional council of 35 members is established for the district, with the Deputy Commissioner of Tuensang as its ex-officio Chairman","The administration of Tuensang district is carried on by the Governor, who arranges equitable distribution of central funds between Tuensang and the rest of Nagaland","There is a Minister for Tuensang Affairs in the State Council of Ministers, appointed from among members representing Tuensang district"],"a":0,"e":"This statement is incorrect and reverses the actual arrangement — members from Tuensang district in the Nagaland Legislative Assembly are NOT directly elected by the people but are chosen by the regional council. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about Article 371-B (Assam) and Article 371-C (Manipur) is NOT correct?","o":["Both Articles empower the President to create a committee of the state legislature to look after the interests of a specific sub-region, with the Governor bearing no special responsibility whatsoever in either case","Under Article 371-C, the Governor can be given special responsibility to secure the proper functioning of the Manipur Hill Areas committee","Under Article 371-C, the Governor must submit an annual report to the President on the administration of the Hill Areas of Manipur","The Tribal Areas of Assam relevant to Article 371-B are specified in the Sixth Schedule, including North Cachar Hills, Karbi Anglong, and Bodoland Territorial Areas Districts"],"a":0,"e":"This statement is incorrect — under Article 371-C (Manipur), the President CAN direct that the Governor have special responsibility for the Hill Areas committee's proper functioning; it is not true that the Governor bears no special responsibility in either case. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the special provisions for Andhra Pradesh/Telangana under Article 371-D:\n1. The President can require the state government to organise civil posts in local cadres for different parts of the state.\n2. The Administrative Tribunal established under this Article functions under the appellate jurisdiction of the state High Court, from which further appeal lies to the Supreme Court.\n3. Article 371-D was extended to Telangana through the Andhra Pradesh Reorganisation Act, 2014.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — the Administrative Tribunal under Article 371-D functions OUTSIDE the purview of the state High Court, with no court other than the Supreme Court exercising jurisdiction over matters within the tribunal's competence, not under the High Court's appellate jurisdiction. Statements 1 and 3 are correct."})

upsc.append({"q":"Which one of the following statements about the special provisions for Sikkim under Article 371-F is NOT correct?","o":["The Sikkim Legislative Assembly is to consist of not less than 60 members, making it the largest among the small-state assemblies covered under the Article 371 series","Sikkim forms one Parliamentary constituency and is allotted one seat in the Lok Sabha","Parliament is empowered to provide for reserved seats and delimited constituencies to protect different sections of the Sikkim population","The Governor of Sikkim has special responsibility for peace and equitable socio-economic advancement of different sections of the population, acting in discretion subject to Presidential directions"],"a":0,"e":"This statement is incorrect — the Sikkim Legislative Assembly is to consist of not less than 30 members, not 60. The other three statements are correct."})

upsc.append({"q":"Match List-I (State) with List-II (Minimum Legislative Assembly Strength prescribed by the respective Article 371-series provision) and select the correct answer using the code below.\nList-I:\nA. Sikkim (Art. 371F)\nB. Mizoram (Art. 371G)\nC. Arunachal Pradesh (Art. 371H)\nD. Goa (Art. 371-I)\nList-II:\n1. Not less than 40 members\n2. Not less than 30 members\n3. Not less than 30 members\n4. Not less than 30 members\nCodes:","o":["A-2, B-1, C-3, D-4","A-1, B-2, C-3, D-4","A-2, B-1, C-4, D-3","A-3, B-1, C-2, D-4"],"a":0,"e":"The correct match is A-2 (Sikkim: not less than 30), B-1 (Mizoram: not less than 40), C-3 (Arunachal Pradesh: not less than 30), D-4 (Goa: not less than 30) — Mizoram is distinctively prescribed the higher 40-member minimum, while Sikkim, Arunachal Pradesh and Goa all share the 30-member minimum."})

upsc.append({"q":"Which one of the following statements about Article 371-J (Karnataka) is NOT correct?","o":["The Hyderabad-Karnataka region covered by this Article includes only two districts, Gulbarga and Bidar, and no others","Article 371-J was inserted by the 98th Constitutional Amendment Act, 2012","The Governor of Karnataka may have special responsibility for reservation of seats in educational/vocational institutions and state government posts for the region's residents","In 2010, both the Legislative Assembly and Legislative Council of Karnataka passed separate resolutions seeking special provisions for the region"],"a":0,"e":"This statement is incorrect — the Hyderabad-Karnataka region under Article 371-J comprises SIX backward districts of Northern Karnataka: Gulbarga, Bidar, Raichur, Koppal, Yadgir and Bellary, not just two. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the historical evolution of Article 371:\n1. Andhra Pradesh was originally covered under Article 371 before being taken out and given separate treatment under Articles 371-D and 371-E by the 32nd Amendment Act, 1973.\n2. Article 371 was amended by the 7th Constitutional Amendment Act, 1956 and the Bombay Reorganisation Act, 1960, in the context of Maharashtra and Gujarat's formation.\n3. Article 371 currently guarantees special responsibility to the Governors of Maharashtra and Gujarat only for law-and-order matters, not for development boards or fund allocation.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — Article 371's special gubernatorial responsibility for Maharashtra and Gujarat concerns development boards (Vidarbha/Marathwada; Saurashtra/Kutch), equitable fund allocation, and technical education/employment facilities, not law-and-order matters. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following Constitutional Amendment Acts inserted Article 371-A (Nagaland) into the Constitution?","o":["13th Constitutional Amendment Act, 1962","22nd Constitutional Amendment Act, 1969","27th Constitutional Amendment Act, 1971","32nd Constitutional Amendment Act, 1973"],"a":0,"e":"Article 371-A (special provisions for Nagaland) was inserted by the 13th Constitutional Amendment Act, 1962 — distinct from Article 371-B (Assam, 22nd Amendment, 1969), Article 371-C (Manipur, 27th Amendment, 1971), and Articles 371-D/371-E (Andhra Pradesh, 32nd Amendment, 1973)."})

upsc.append({"q":"Match List-I (Article) with List-II (Inserting Constitutional Amendment Act) and select the correct answer using the code below.\nList-I:\nA. Article 371-G (Mizoram)\nB. Article 371-H (Arunachal Pradesh)\nC. Article 371-I (Goa)\nD. Article 371-J (Karnataka)\nList-II:\n1. 56th Amendment Act, 1987\n2. 53rd Amendment Act, 1986\n3. 98th Amendment Act, 2012\n4. 55th Amendment Act, 1986\nCodes:","o":["A-2, B-4, C-1, D-3","A-4, B-2, C-1, D-3","A-2, B-1, C-4, D-3","A-2, B-4, C-3, D-1"],"a":0,"e":"The correct match is A-2 (Mizoram, 53rd Amendment, 1986), B-4 (Arunachal Pradesh, 55th Amendment, 1986), C-1 (Goa, 56th Amendment, 1987), D-3 (Karnataka, 98th Amendment, 2012) — each state's special provision was inserted by a distinct constitutional amendment across different years."})

upsc.append({"q":"Which one of the following statements about the special responsibility of the Governor of Nagaland (Article 371-A) and Arunachal Pradesh (Article 371-H) regarding law and order is NOT correct?","o":["In both cases, the Governor's decision on this matter is subject to prior approval by the State Legislative Assembly before taking effect","In both cases, after consulting the Council of Ministers, the Governor exercises individual judgement and the decision is final","This special responsibility ceases in both cases only when the President so directs","The validity of anything done by the Governor in the exercise of this individual judgement cannot be questioned on the ground that he/she ought or ought not to have so acted"],"a":0,"e":"This statement is incorrect — the Governor's decision on law and order in these matters, after consulting the Council of Ministers, is FINAL as an exercise of individual judgement; it is not subject to prior approval by the State Legislative Assembly. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the overall scope of Articles 371 to 371-J is NOT correct?","o":["These special provisions apply to exactly twelve named states, and the Constitution originally contained them from its commencement in 1950 without any subsequent amendment","These provisions are located in Part XXI of the Constitution, titled 'Temporary, Transitional and Special Provisions'","The purpose of these provisions includes meeting the aspirations of backward regions, protecting tribal cultural/economic interests, and addressing disturbed law and order in parts of certain states","These provisions were incorporated through various amendments in the context of state reorganisation or the conferment of statehood on former Union Territories"],"a":0,"e":"This statement is incorrect — the Constitution originally did NOT contain these special provisions; they were incorporated through various SUBSEQUENT amendments (from 1962 through 2012) as states were reorganised or elevated from Union Territory status, not present from 1950 onward. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch78_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
