import json

upsc = []

# ==================================================================
# NEW UPSC TIER: MUNICIPALITIES (Ch.40)
# ==================================================================

upsc.append({"q":"Match List-I (Committee/Commission on Urban Local Government) with List-II (Chairman) and select the correct answer using the code below.\nList-I:\nA. Rural-Urban Relationship Committee (1963-66)\nB. Committee on Training of Municipal Employees (1963-65)\nC. National Commission on Urbanisation (1985-88)\nD. Local Finance Enquiry Committee (1949-51)\nList-II:\n1. C.M. Correa\n2. P.K. Wattal\n3. A.P. Jain\n4. Nur-Ud-din Ahmed\nCodes:","o":["A-3, B-4, C-1, D-2","A-4, B-3, C-1, D-2","A-3, B-1, C-4, D-2","A-3, B-4, C-2, D-1"],"a":0,"e":"The correct match is A-3 (A.P. Jain), B-4 (Nur-Ud-din Ahmed), C-1 (C.M. Correa), D-2 (P.K. Wattal) — matching each pre-74th-Amendment committee/commission on urban local government to its chairman."})

upsc.append({"q":"Which one of the following statements about pre-1992 committees on urban local government is NOT correct?","o":["The Taxation Enquiry Commission (1953-54), chaired by John Matthai, examined the training needs of municipal employees as its primary mandate","The Committee of Ministers on Augmentation of Financial Resources of Urban Local Bodies (1963) was chaired by Rafiq Zakaria","The Study Group on Constitution, Powers and Laws of Urban Local Bodies and Municipal Corporations (1982) was chaired by K.N. Sahaya","The Committee on Budgetary Reform in Municipal Administration (1974) was chaired by Girijapati Mukharji"],"a":0,"e":"This statement is incorrect — the Taxation Enquiry Commission's mandate concerned taxation matters, not municipal employee training (that was the separate Committee on Training of Municipal Employees, chaired by Nur-Ud-din Ahmed). The other three statements correctly match committees to their chairmen."})

upsc.append({"q":"Which one of the following is NOT among the eight types of urban local bodies created in India for administration of urban areas, per the text?","o":["Village Panchayat Committee","Notified Area Committee","Cantonment Board","Port Trust"],"a":0,"e":"'Village Panchayat Committee' is not one of the eight types of urban local bodies listed — the actual eight are: Municipal Corporation, Municipality, Notified Area Committee, Town Area Committee, Cantonment Board, Township, Port Trust, and Special Purpose Agency. A Panchayat is a rural, not urban, local body."})

upsc.append({"q":"Which one of the following statements comparing the Mayor of a Municipal Corporation with the President/Chairman of a Municipality is NOT correct?","o":["The Mayor plays a significant executive role and is the pivot of corporation administration, while the President of a Municipality is largely an ornamental, formal head","The Mayor is, in a majority of states, elected for a one-year renewable term and is essentially an ornamental figure whose main function is presiding over Council meetings","The President/Chairman of a Municipality, unlike the Mayor, enjoys executive powers in addition to presiding over Council meetings","Both a Municipal Corporation and a Municipality have a Council, standing committees, and a chief executive functionary (Commissioner or Chief Executive Officer)"],"a":0,"e":"This statement is incorrect and reverses the actual comparison — it is the MAYOR who is largely ornamental/formal (mainly presiding over meetings), while the President/Chairman of a MUNICIPALITY plays the more significant, executively empowered role. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Municipal Commissioner of a Municipal Corporation is NOT correct?","o":["The Municipal Commissioner is directly elected by the people alongside the Councillors, functioning as an elected chief executive","The Municipal Commissioner is responsible for implementing decisions taken by the Council and its standing committees","The Municipal Commissioner is the chief executive authority of the corporation","The Municipal Commissioner is appointed by the state government and is generally a member of the IAS"],"a":0,"e":"This statement is incorrect — the Municipal Commissioner is APPOINTED by the state government (typically an IAS officer), not directly elected by the people; only the Councillors are directly elected. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about a Notified Area Committee is NOT correct?","o":["It is a fully elected statutory body, functioning identically to a regular municipality in terms of its members' selection","It is created for a fast-developing industrial town or a town not yet fulfilling all conditions for constitution as a municipality","It is established by a notification in the government gazette, and only those provisions of the State Municipal Act notified in that gazette apply to it","All its members, including the chairman, are nominated by the state government, making it neither an elected nor a statutory body in the conventional sense"],"a":0,"e":"This statement is incorrect and reverses the actual nature — a Notified Area Committee is an ENTIRELY NOMINATED body (all members, including the chairman, nominated by the state government), not an elected statutory body like a regular municipality. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about a Town Area Committee is NOT correct?","o":["It must always be a wholly elected body, since it exercises civic functions of a municipal nature and elected accountability is constitutionally mandated for it","It is a semi-municipal authority entrusted with a limited number of civic functions like drainage, roads, street lighting and conservancy","It is created by a separate Act of a state legislature, which governs its composition and functions","It may be wholly elected, wholly nominated by the state government, or partly elected and partly nominated"],"a":0,"e":"This statement is incorrect — a Town Area Committee's composition is NOT constitutionally mandated to be wholly elected; per the governing state Act, it may be wholly elected, wholly nominated, or a mix of both. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the composition of a District Planning Committee (DPC) is NOT correct?","o":["One-half of the members of a DPC must be nominated by the state government, with the remaining half elected by district panchayats and municipalities","Four-fifths of the members of a DPC should be elected by the elected members of the district panchayat and municipalities in the district, from amongst themselves","The representation of members in a DPC should be in proportion to the ratio between rural and urban populations in the district","The chairperson of a DPC forwards the district's draft development plan to the state government"],"a":0,"e":"This statement is incorrect — the Act specifies that FOUR-FIFTHS (not one-half) of a DPC's members should be elected by district panchayat and municipality members from amongst themselves, not a 50-50 nominated/elected split. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the composition of a Metropolitan Planning Committee (MPC) is NOT correct?","o":["All members of an MPC are nominated by the state government, with no elected component, unlike the DPC which has a significant elected component","Two-thirds of the members of an MPC should be elected by the elected members of municipalities and chairpersons of panchayats in the metropolitan area, from amongst themselves","Representation in the MPC should be proportional to the population ratio between municipalities and panchayats in the metropolitan area","The MPC's draft development plan must have regard to the overall objectives and priorities set by the Government of India and the state government"],"a":0,"e":"This statement is incorrect — like the DPC, the MPC has a substantial ELECTED component: two-thirds of its members are elected by municipal/panchayat representatives, not wholly nominated by the state government. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about Articles 243ZD and 243ZE (District Planning Committee and Metropolitan Planning Committee provisions) is NOT correct?","o":["These provisions apply uniformly and without exception to the National Capital Territory of Delhi, exactly as they do to other states","The state legislature may make provisions on the composition, election manner, and functions of these planning committees","A DPC's draft development plan must have regard to matters of common interest between panchayats and municipalities, such as spatial planning and shared resources","An MPC's draft plan must consider the extent and nature of investments likely to be made in the metropolitan area by Central and state government agencies"],"a":0,"e":"This statement is incorrect — the text explicitly states that Articles 243ZD and 243ZE (DPC and MPC provisions) shall NOT apply to the National Capital Territory of Delhi, unlike their application to other states. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the 'Continuance of Existing Laws and Municipalities' provision under the 74th Amendment Act, 1992 is correct?","o":["All state laws relating to municipalities continued in force for up to one year from the Act's commencement, giving states a transition period to adopt the new constitutional system","All pre-existing municipal laws were repealed with immediate effect on the date of the Act's commencement, with no transition period","Municipalities existing before the Act's commencement were dissolved immediately, regardless of their remaining term","This provision applied only to Municipal Corporations and not to smaller Municipalities or Nagar Panchayats"],"a":0,"e":"Mirroring the equivalent provision for panchayats, the 74th Amendment allowed existing state municipal laws to continue for up to one year from commencement (giving states time to conform their legislation), rather than an immediate repeal, blanket dissolution, or a Corporation-only application."})

upsc.append({"q":"Which one of the following statements about areas exempted from Part IXA (Municipalities) of the Constitution is NOT correct?","o":["Part IXA applies without any exception to all scheduled areas and tribal areas in every state, since urban local governance is considered distinct from the concerns addressed by such exemptions elsewhere","Part IXA does not apply to the scheduled areas and tribal areas in the states","Part IXA does not affect the functions and powers of the Darjeeling Gorkha Hill Council of West Bengal","Parliament may extend Part IXA's provisions to scheduled areas and tribal areas, subject to exceptions/modifications it specifies"],"a":0,"e":"This statement is incorrect — Part IXA explicitly does NOT apply to scheduled areas and tribal areas in the states (mirroring the panchayat exemption), contrary to the claim of unexceptional application. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch40_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
