import json

upsc = []

# ==================================================================
# TOP-UP: PARLIAMENT (Laxmikanth, Ch.23) - covering gaps: Types of Majority,
# Leaders in Parliament, Funds, Cut Motions, Budget stages/grants, Lame-duck session
# ==================================================================

upsc.append({"q":"Match List-I (Type of Majority) with List-II (Matter Requiring It) and select the correct answer using the code below.\nList-I:\nA. Simple Majority\nB. Effective Majority\nC. Absolute Majority\nD. Special Majority-I (majority of total membership + 2/3rd present and voting)\nList-II:\n1. Amendment of the Constitution (Article 368)\n2. Removal of the Deputy Chairman of the Rajya Sabha (Article 90)\n3. Not prescribed standalone by the Constitution for any single purpose, but required as a component of Special Majority-I\n4. Passing of ordinary bills and money bills\nCodes:","o":["A-4, B-2, C-3, D-1","A-4, B-3, C-2, D-1","A-1, B-2, C-3, D-4","A-4, B-2, C-1, D-3"],"a":0,"e":"The correct match is A-4, B-2, C-3, D-1: simple majority governs ordinary/money bill passage; effective majority (of the House excluding vacancies) is needed to remove the Deputy Chairman of the Rajya Sabha; absolute majority (of total membership, vacancies or not) is not prescribed standalone but forms part of Special Majority-I; and Special Majority-I governs constitutional amendments."})

upsc.append({"q":"Which one of the following statements about 'effective majority' under the Indian Constitution is NOT correct?","o":["It means a majority of the total membership of the House, irrespective of vacant seats or absentees","It means a majority of the total membership of the House excluding vacant seats, i.e., a majority of the effective strength","It is constitutionally referred to as 'a majority of all the then members of the House'","It is required for the removal of the Speaker and Deputy Speaker of the Lok Sabha (Article 94)"],"a":0,"e":"This statement is incorrect and actually describes 'absolute majority', not 'effective majority' — effective majority specifically EXCLUDES vacant seats from the total membership, unlike absolute majority which counts the full sanctioned strength regardless of vacancies. The other three statements correctly describe effective majority."})

upsc.append({"q":"Consider the following statements about special majority requirements under the Indian Constitution:\n1. A two-thirds majority of the members present and voting in the Rajya Sabha alone (Special Majority-III) is required for Parliament to legislate on a State List matter under Article 249.\n2. The impeachment of the President under Article 61 requires a two-thirds majority of the total membership of each House (Special Majority-II).\n3. Removal of a Supreme Court or High Court judge requires the same Special Majority-I formula as a constitutional amendment.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct: Article 249 (Rajya Sabha resolution enabling Parliament to legislate on a State subject) requires Special Majority-III; presidential impeachment requires Special Majority-II; and judicial removal (Articles 124/217) requires the same Special Majority-I formula as a constitutional amendment."})

upsc.append({"q":"Which one of the following statements about the 'Leader of the Opposition' in Indian Parliament is NOT correct?","o":["The office was first created by an explicit provision in the original text of the Constitution of India in 1950","The Leaders of Opposition in the Lok Sabha and Rajya Sabha were accorded statutory recognition only in 1977, under the Salary and Allowances of Leaders of Opposition in Parliament Act, 1977","An official Leader of the Opposition was recognised for the first time only in 1969","The minimum numerical strength required for a party's leader to be recognised as Leader of the Opposition is one-tenth of the total membership of that House"],"a":0,"e":"This statement is incorrect — the office of Leader of the Opposition is NOT mentioned in the Constitution at all; it only received statutory recognition via a 1977 Act, and its criteria (one-tenth strength) are laid down by directions of the Speaker/Chairman, not the constitutional text. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the 'Leader of the House' and 'Whips' in Indian Parliament is NOT correct?","o":["The offices of Leader of the House and Chief Whip are both explicitly defined in the text of the Constitution of India","In the Lok Sabha, the 'Leader of the House' is the Prime Minister (if a member of that House) or a minister nominated by the Prime Minister to that role","The office of 'whip' is based on the conventions of parliamentary government and is mentioned neither in the Constitution nor in the Rules of the House","In the US, the equivalent of India's Leader of the House and Leader of the Opposition are called the 'majority leader' and 'minority leader' respectively"],"a":0,"e":"This statement is incorrect — the Leader of the House is mentioned only in the Rules of the House, and the office of whip is mentioned in NEITHER the Constitution nor the Rules of the House, being based purely on convention; neither is defined in the Constitution's text. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the three Central Government funds under the Indian Constitution is NOT correct?","o":["The Public Account of India is operated through parliamentary appropriation in the same manner as the Consolidated Fund of India","The Consolidated Fund of India (Article 266) comprises all government revenues, loans raised, and repayments received, and no money can be withdrawn from it except by parliamentary law","The Contingency Fund of India (Article 267) is placed at the disposal of the President to meet unforeseen expenditure pending parliamentary authorisation, and is operated by executive action","The Public Account of India holds money such as provident fund deposits, judicial deposits and savings bank deposits, and is operated by executive action without needing parliamentary appropriation"],"a":0,"e":"This statement is incorrect and reverses the actual position — the Public Account of India, like the Contingency Fund, is operated by EXECUTIVE ACTION without requiring parliamentary appropriation, unlike the Consolidated Fund, which does require parliamentary law for any withdrawal. The other three statements are correct."})

upsc.append({"q":"Match List-I (Cut Motion Type) with List-II (Description) and select the correct answer using the code below.\nList-I:\nA. Policy Cut Motion\nB. Economy Cut Motion\nC. Token Cut Motion\nList-II:\n1. States that the demand be reduced by ₹100, to ventilate a specific grievance within the Union government's responsibility\n2. States that the demand be reduced to ₹1, representing disapproval of the policy underlying the demand\n3. States that the demand be reduced by a specified (lumpsum or item-wise) amount, representing an economy that can be effected\nCodes:","o":["A-2, B-3, C-1","A-2, B-1, C-3","A-1, B-3, C-2","A-3, B-2, C-1"],"a":0,"e":"The correct match is A-2, B-3, C-1: a Policy Cut Motion reduces the demand to ₹1 (disapproving the underlying policy); an Economy Cut Motion reduces it by a specified amount (representing an economy); and a Token Cut Motion reduces it by ₹100 (ventilating a specific grievance)."})

upsc.append({"q":"Which one of the following statements about 'cut motions' in the Lok Sabha is NOT correct?","o":["A cut motion, once passed by the Lok Sabha, is legally binding and automatically reduces the government's sanctioned budget by the specified amount, regardless of the government's majority","To be admissible, a cut motion must relate to only one demand and must not relate to expenditure charged on the Consolidated Fund of India","The passage of a cut motion by the Lok Sabha amounts to an expression of want of parliamentary confidence in the government and may lead to its resignation","In practice, cut motions have limited utility since they are typically discussed but not passed, given that the government usually enjoys majority support"],"a":0,"e":"This statement is incorrect — cut motions in practice are rarely passed (since the government commands a majority) and their political significance lies in signalling loss of confidence if passed, not in any automatic binding effect on the budget. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about supplementary/additional/excess grants and the Vote of Credit is NOT correct?","o":["A 'Vote of Credit' is granted only for routine, clearly quantifiable expenditure already detailed in the annual budget, and hence requires no special parliamentary procedure","An 'Excess Grant' is granted when money has been spent in a financial year in excess of the amount originally granted, and must be approved by the Public Accounts Committee before being submitted to the Lok Sabha for voting","A 'Supplementary Grant' is granted when the amount authorised by the Appropriation Act for a service in the current year proves insufficient","A 'Token Grant' is granted when funds for a new service can be made available through reappropriation of funds from one head to another"],"a":0,"e":"This statement is incorrect and reverses the actual purpose — a Vote of Credit is specifically for meeting an UNEXPECTED demand on India's resources when, due to the magnitude or indefinite character of the service, the demand CANNOT be stated with the details ordinarily given in a budget (essentially a 'blank cheque'), not for routine, clearly quantifiable expenditure. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the 'lame-duck session' of the Lok Sabha is NOT correct?","o":["It refers to the first session of a newly-elected Lok Sabha, held immediately before the results of the general election are formally announced","Members of the preceding Lok Sabha who could not get re-elected to the new Lok Sabha are referred to as 'lame-ducks'","Such sessions were held in 1957 and 1962, primarily to pass the Vote on Account so the government could function until the new Lok Sabha was constituted","There was no lame-duck session after the Third Lok Sabha, as the Fourth Lok Sabha was constituted soon after the general election results were announced"],"a":0,"e":"This statement is incorrect and reverses the actual definition — a 'lame-duck session' refers to the LAST session of the PRECEDING (outgoing) Lok Sabha, held after a new Lok Sabha has been elected but before it is duly constituted, not the first session of the new Lok Sabha. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the effect of dissolution of the Lok Sabha on pending bills, per the Constitution and parliamentary practice:\n1. A bill pending in the Lok Sabha (whether originating there or transmitted from the Rajya Sabha) lapses on dissolution.\n2. A bill pending in the Rajya Sabha but not yet passed by the Lok Sabha does NOT lapse on dissolution of the Lok Sabha.\n3. A bill passed by both Houses but pending the President's assent lapses on dissolution of the Lok Sabha.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — a bill passed by both Houses but pending the President's assent does NOT lapse on dissolution of the Lok Sabha, since the Rajya Sabha (a permanent body) is unaffected by the dissolution. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the merger of the Railway Budget into the General Budget is NOT correct?","o":["The Railway Budget was separated from the General Budget in 1924 on the recommendation of the Simon Commission Report (1921)","The Railway Budget was merged back into the General Budget in 2017, so there is now only one Union Budget","One objective of the original 1924 separation was to secure stability of general revenues via an assured annual contribution from railway revenues","One objective of the original 1924 separation was to introduce flexibility in railway finance and enable a business approach to railway policy"],"a":0,"e":"This statement is incorrect — the Railway Budget's separation in 1924 was based on the recommendations of the ACWORTH COMMITTEE Report (1921), not the Simon Commission. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the stages of enactment of the Union Budget in Parliament:\n1. During the 'General Discussion' stage, the Lok Sabha can discuss the budget as a whole, but no cut motion can be moved and the budget cannot be put to a vote at this stage.\n2. The 24 Department-Related Standing Committees examine and report on the demands for grants during a gap period after the general discussion, before voting on demands for grants occurs.\n3. The Finance Bill, unlike the Appropriation Bill, permits amendments seeking to reject or reduce a tax proposal.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, reflecting the correct sequence and character of the budget's six enactment stages: general discussion (no cut motions/voting), departmental committee scrutiny of demands for grants, and the Finance Bill's amendability (unlike the Appropriation Bill, which permits no such amendments)."})

upsc.append({"q":"Which one of the following statements about voting methods in the Lok Sabha is NOT correct?","o":["The Speaker of the Lok Sabha votes in the first instance on every question, in addition to exercising a casting vote in case of a tie","A 'Division' can be held by operating the Automatic Vote Recording Equipment, by distributing 'Ayes' and 'Noes' slips, or (now obsolete) by members going into the Lobbies","A 'Voice Vote' is a simple method where the question is determined by the volume of 'Ayes' or 'Noes' called out in response to the Speaker's question","If the Speaker considers a Division unnecessarily claimed, members may be asked to rise in their places for a physical count instead of a formal Division, without their names being recorded"],"a":0,"e":"This statement is incorrect and reverses the constitutional position — the Speaker (or person acting as such) does NOT vote in the first instance; the Speaker only exercises a CASTING vote in case of a tie (equality of votes). The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch23_topup.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
