import json

upsc = []

# ==================================================================
# NEW UPSC TIER: ELECTION COMMISSION (Ch.43)
# ==================================================================

upsc.append({"q":"Consider the following statements about the historical evolution of the Election Commission's composition:\n1. On 16 October 1989, the President appointed two more Election Commissioners, making it a three-member body, to cope with increased work following the lowering of the voting age from 21 to 18.\n2. The two additional Election Commissioner posts created in 1989 were abolished in January 1990, reverting the Commission to a single-member body.\n3. Since October 1993, the Election Commission has continuously functioned as a multi-member body of three Election Commissioners.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, tracing the Commission's fluctuation from a single-member body (1950-1989) through a brief three-member phase (1989-90, reverted in January 1990), before permanently becoming a three-member body from October 1993 onward."})

upsc.append({"q":"Which one of the following is NOT among the constitutional 'flaws' regarding the Election Commission's independence, as noted in the text?","o":["The Constitution mandates that all Election Commissioners must have prior judicial experience, but this requirement is poorly enforced in practice","The Constitution has not prescribed the qualifications (legal, educational, administrative or judicial) for members of the Election Commission","The Constitution has not specified a fixed term for members of the Election Commission","The Constitution has not debarred retiring Election Commissioners from further government appointment"],"a":0,"e":"This is NOT a flaw noted in the text — the Constitution does not prescribe ANY specific qualifications for Election Commissioners (judicial or otherwise), so there is no such judicial-experience mandate to begin with. The genuine flaws noted are the absence of prescribed qualifications, absence of a fixed term, and absence of a bar on post-retirement government appointment."})

upsc.append({"q":"Which one of the following statements about the removal of Election Commissioners (other than the Chief Election Commissioner) is correct?","o":["An Election Commissioner or regional commissioner cannot be removed except on the recommendation of the Chief Election Commissioner","An Election Commissioner enjoys identical security of tenure as the Chief Election Commissioner, requiring a special majority resolution of Parliament for removal","An Election Commissioner can be removed by the President at any time, entirely at his/her own discretion, without any recommendation","An Election Commissioner can only be removed by a resolution of the concerned state legislature"],"a":0,"e":"The text explicitly states that an Election Commissioner or regional commissioner cannot be removed except on the CEC's recommendation — a materially weaker protection than the CEC's own security of tenure (which requires the same process as a Supreme Court judge's removal), not an identical protection, unrestricted presidential discretion, or a state legislature role."})

upsc.append({"q":"Consider the following statements about the administrative hierarchy assisting the Election Commission:\n1. Deputy Election Commissioners are drawn from the civil service and appointed by the Commission on a tenure basis.\n2. At the state level, the Chief Electoral Officer is appointed by the Chief Election Commissioner in consultation with the state government.\n3. At the district level, the Collector acts as the district returning officer and appoints a returning officer for each constituency and a presiding officer for each polling booth.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, describing the Commission's administrative machinery: Deputy Election Commissioners at the top (civil service, tenure-based), Chief Electoral Officers at the state level, and the Collector functioning as district returning officer, further appointing constituency and booth-level officers."})

upsc.append({"q":"Which one of the following is NOT among the powers and functions of the Election Commission listed in the text?","o":["To directly try and convict individuals for electoral offences such as booth capturing, imposing criminal penalties including imprisonment","To advise the President on whether elections can be held in a state under President's Rule, in order to extend the period of emergency beyond one year","To prepare a roster for publicity of political parties' policies on radio and TV during elections","To register political parties for elections and grant them national or state party status based on poll performance"],"a":0,"e":"This is NOT among the Commission's functions — the Commission's role regarding electoral offences like booth capturing is to CANCEL POLLS where such irregularities occur, not to try and criminally convict individuals (which is a judicial function of the courts). The other three are genuine functions listed in the text."})

upsc.append({"q":"Which one of the following statements about the Election Commission's powers and functions, as classified in the text, is correct?","o":["Its powers and functions are classified into three categories: Administrative, Advisory, and Quasi-Judicial","Its powers and functions are classified into two categories: Legislative and Executive","Its powers and functions are classified into four categories: Administrative, Advisory, Judicial, and Constituent","Its powers and functions are not classified into any distinct categories, being treated as a single undifferentiated set"],"a":0,"e":"The text explicitly classifies the Election Commission's powers and functions regarding Parliament, state legislature, and Presidential/Vice-Presidential elections into three categories: Administrative, Advisory, and Quasi-Judicial — not any of the other groupings."})

upsc.append({"q":"Which one of the following statements about the Election Commission's quasi-judicial functions is correct?","o":["It acts as a court for settling disputes related to the grant of recognition to political parties and allotment of election symbols","It exercises appellate jurisdiction over decisions of the High Courts in election petition matters","It has the power to try election petitions in the first instance as a court of original jurisdiction","It functions as a quasi-judicial body only in disputes between the Union and state governments over election matters"],"a":0,"e":"The Commission's quasi-judicial role, as described in the text, is specifically to act as a court for settling disputes over political party recognition and election symbol allotment — it does not hear election petitions (which go to High Courts) or Union-state disputes."})

upsc.append({"q":"Which one of the following statements about the Delimitation Commission Acts is correct?","o":["Parliament has enacted Delimitation Commission Acts in 1952, 1962, 1972 and 2002","Parliament has enacted only a single, permanent Delimitation Commission Act that has never required re-enactment","Delimitation Commission Acts are enacted by State Legislatures, not Parliament","The Election Commission itself enacts Delimitation Commission Acts without any parliamentary involvement"],"a":0,"e":"The text explicitly lists four Delimitation Commission Acts enacted by Parliament — in 1952, 1962, 1972 and 2002 — periodically re-enacted for successive delimitation exercises, not a single permanent Act, state-level enactment, or Commission self-legislation."})

upsc.append({"q":"Which one of the following statements about the salary and service conditions of Election Commissioners under the Election Commission (Conditions of Service of Election Commissioners and Transaction of Business) Act, 1991 is NOT correct?","o":["The Chief Election Commissioner receives a materially higher salary than the other two Election Commissioners, reflecting his/her seniority as chairman of the Commission","The Chief Election Commissioner and the two other Election Commissioners have equal powers and receive equal salary, allowances and other perquisites","These emoluments are similar to those of a judge of the Supreme Court","In case of a difference of opinion among the Commissioners, the matter is decided by the Commission by majority"],"a":0,"e":"This statement is incorrect — the 1991 Act explicitly provides that the CEC and the other two Election Commissioners have EQUAL powers and receive EQUAL salary/allowances/perquisites, with no salary differential based on seniority. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Election Commission's relationship with elections to Panchayats and Municipalities is correct?","o":["The Election Commission of India is not concerned with elections to panchayats and municipalities, for which the Constitution provides for separate State Election Commissions","The Election Commission of India directly conducts all panchayat and municipal elections across the country","State Election Commissions were created by ordinary parliamentary legislation rather than constitutional amendment","The Election Commission of India shares concurrent jurisdiction with State Election Commissions over local body elections"],"a":0,"e":"The text is explicit — the Election Commission of India has no role in panchayat/municipal elections, which are instead handled by separate State Election Commissions created via the 73rd and 74th Constitutional Amendment Acts of 1992, not via ordinary legislation or concurrent jurisdiction with the ECI."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch43_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
