import json

upsc = []

# ==================================================================
# NEW UPSC TIER: SUPREME COURT (Ch.26) + JUDICIAL REVIEW (Ch.27)
# ==================================================================

upsc.append({"q":"Consider the following statements about the growth in strength of the Supreme Court of India:\n1. Originally, the Supreme Court's strength was fixed at eight (one Chief Justice and seven other judges).\n2. The number of other judges was raised to seventeen in 1977 and to twenty-five in 1986.\n3. The Supreme Court (Number of Judges) Amendment Act, 2019 raised the number of other judges to thirty-three, taking the total strength to thirty-four.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, tracing the Supreme Court's growth from its original 8-judge strength (Article 124) through successive amendments in 1956, 1960, 1977, 1986, 2008 and 2019, reaching 34 (1 CJI + 33 other judges) today."})

upsc.append({"q":"Which one of the following statements about the qualifications for appointment as a judge of the Supreme Court of India is NOT correct?","o":["The Constitution prescribes a minimum age of 45 years for appointment as a judge of the Supreme Court","A person must be a citizen of India to be appointed as a judge of the Supreme Court","A person who has been a judge of a High Court (or High Courts in succession) for five years is qualified for appointment","A person who has been an advocate of a High Court (or High Courts in succession) for ten years, or is a distinguished jurist in the President's opinion, is also qualified"],"a":0,"e":"This statement is incorrect — the Constitution does NOT prescribe any minimum age for appointment as a Supreme Court judge, unlike some other constitutional offices. The other three statements correctly state the qualification routes (High Court judge for 5 years, High Court advocate for 10 years, or distinguished jurist)."})

upsc.append({"q":"Match List-I (Category of Judge) with List-II (Appointing Authority/Process) and select the correct answer using the code below.\nList-I:\nA. Acting Chief Justice of India\nB. Ad hoc Judge of the Supreme Court\nC. Retired Judge sitting temporarily\nD. Regular Judge (other than CJI)\nList-II:\n1. Appointed by the President after consultation with the CJI and such other judges as deemed necessary\n2. Appointed by the President when the office of CJI is vacant or the CJI is absent/unable to act\n3. A High Court judge appointed by the CJI (with consultation and the President's prior consent) due to lack of quorum\n4. A retired SC/HC judge requested by the CJI, with the prior consent of both the President and the judge concerned\nCodes:","o":["A-2, B-3, C-4, D-1","A-2, B-4, C-3, D-1","A-1, B-3, C-4, D-2","A-2, B-3, C-1, D-4"],"a":0,"e":"The correct match is A-2, B-3, C-4, D-1: the President appoints an Acting CJI when the office is vacant/CJI is unavailable; the CJI appoints an ad hoc judge from a High Court to address quorum shortages; the CJI requests a retired judge with dual consent; and regular judges are appointed by the President after consultation with the CJI and other judges."})

upsc.append({"q":"Which one of the following statements about the seat and procedure of the Supreme Court is NOT correct?","o":["The Constitution mandates that the Supreme Court must hold sittings in at least four different cities on a rotational basis, and this provision is compulsory, not optional","The Constitution declares Delhi as the seat of the Supreme Court, but authorises the Chief Justice of India to appoint other place(s) as seat, only with the President's approval","Constitutional cases or Presidential references under Article 143 are decided by a Bench of at least five judges","No court can direct the President or the Chief Justice to appoint any other place as a seat of the Supreme Court, since this provision is optional"],"a":0,"e":"This statement is incorrect — there is no such constitutional mandate requiring rotational sittings in multiple cities; the provision for an alternate seat (beyond Delhi) is explicitly OPTIONAL, exercisable only by the CJI with the President's approval, not a rotational requirement. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about safeguards for the independence of the Supreme Court:\n1. The salaries, allowances and pensions of Supreme Court judges and staff, along with the Court's administrative expenses, are charged on the Consolidated Fund of India and hence non-votable by Parliament.\n2. The Constitution completely prohibits any discussion in Parliament regarding the conduct of Supreme Court judges under all circumstances, including during impeachment proceedings.\n3. Retired judges of the Supreme Court are prohibited from pleading or acting in any court or before any authority within the territory of India.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect — discussion of a judge's conduct is prohibited EXCEPT when an impeachment motion is under consideration of Parliament, not under all circumstances. Statements 1 and 3 are correct safeguards of judicial independence."})

upsc.append({"q":"Which one of the following statements about the Supreme Court's advisory jurisdiction under Article 143 is NOT correct?","o":["In both categories of Presidential references under Article 143, the Supreme Court is bound to tender its opinion and cannot refuse to do so","On any question of law or fact of public importance, the Supreme Court may tender or may refuse to tender its opinion to the President","On disputes arising from pre-constitution treaties/agreements excluded from its original jurisdiction, the Supreme Court 'must' tender its opinion","The opinion expressed under Article 143 is advisory only and not binding on the President, who may or may not follow it"],"a":0,"e":"This statement is incorrect and reverses the actual distinction — the Supreme Court MAY refuse to tender an opinion in the first category (general public importance questions), while it MUST tender an opinion only in the second category (pre-constitution treaty disputes); it is not bound in both categories. The other three statements are correct."})

upsc.append({"q":"Consider the following statements comparing the Indian and American Supreme Courts:\n1. The Indian Supreme Court's original jurisdiction is confined to federal (Centre-State/inter-State) cases, while the American Supreme Court's original jurisdiction also covers cases relating to ambassadors and maritime activities.\n2. The Indian Supreme Court's appellate jurisdiction covers constitutional, civil and criminal cases, while the American Supreme Court's appellate jurisdiction is confined to constitutional cases only.\n3. The Indian Supreme Court protects citizens' rights via 'due process of law', giving it a wider scope of judicial review than the American Supreme Court's 'procedure established by law' standard.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 reverses the actual comparison — it is the AMERICAN Supreme Court that applies 'due process of law' (giving it a wider scope of judicial review), while the Indian Supreme Court applies the narrower 'procedure established by law' standard. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements about the Contempt of Courts Act, 1971 is NOT correct?","o":["The Act was based on the recommendations of a special committee headed by H.N. Sanyal, and it classifies contempt of court exclusively as 'criminal contempt', with no separate category for civil contempt","Under the Act, contempt of court is punishable with simple imprisonment up to six months, a fine up to ₹2,000, or both","No court can initiate contempt proceedings after the expiry of one year from the date the contempt is alleged to have been committed","Fair and accurate reporting of judicial proceedings and fair criticism of judicial acts do not amount to contempt of court under the Act"],"a":0,"e":"This statement is incorrect — the Act recognises TWO categories of contempt, both civil (wilful disobedience of a court order/undertaking) and criminal (scandalising the court, prejudicing proceedings, or obstructing justice), not criminal contempt alone. The other three statements are correct."})

upsc.append({"q":"With reference to the Supreme Court's review and curative jurisdiction, consider the following statements:\n1. A review petition must be filed within thirty days of the judgment or order sought to be reviewed, and must go to the same judge or bench that delivered it.\n2. A curative petition can only be filed before a review petition has been dismissed, never after.\n3. Grounds for a curative petition include violation of natural justice, preventing abuse of court process, and bias of the judge.\nWhich of the statements given above is/are correct?","o":["1 and 3 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 2 is incorrect and reverses the actual sequence — a curative petition is available precisely AFTER a review petition has been dismissed, as a further recourse on limited grounds, not before. Statements 1 and 3 are correct."})

upsc.append({"q":"Consider the following statements about the Ninth Schedule and judicial review, per the Supreme Court's rulings:\n1. In the Kesavananda Bharati case (1973), the Court ruled that laws in the Ninth Schedule are wholly immune from judicial review under all circumstances.\n2. In the Waman Rao case (1980), the Court held that acts included in the Ninth Schedule after 24 April 1973 are valid only if they do not damage the basic structure of the Constitution.\n3. In the I.R. Coelho case (2007), the Court held there can be no blanket immunity from judicial review for laws placed in the Ninth Schedule after 24 April 1973 if they violate Articles 14, 15, 19 or 21, or the basic structure.\nWhich of the statements given above is/are correct?","o":["2 and 3 only","1 and 2 only","1 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 1 is incorrect and reverses the actual ruling — Kesavananda Bharati (1973) held that Ninth Schedule laws ARE open to challenge on basic-structure grounds, not wholly immune. Statements 2 and 3 correctly state the Waman Rao and I.R. Coelho holdings."})

upsc.append({"q":"Which one of the following correctly lists Justice Syed Shah Mohamed Quadri's three-fold classification of judicial review in India?","o":["Review of constitutional amendments; review of legislation of Parliament, State Legislatures and subordinate legislation; and review of administrative action of Union/State authorities","Review of executive orders only; review of legislative acts only; and review of judicial precedents only","Review of Fundamental Rights violations; review of Directive Principles violations; and review of Fundamental Duties violations","Review of Central laws only; review of State laws only; and review of Concurrent List laws only"],"a":0,"e":"Quadri's classification, as cited in the book, identifies three categories: judicial review of constitutional amendments, judicial review of legislation (Parliament, State Legislatures, and subordinate legislation), and judicial review of administrative action of Union and State authorities — not any of the other groupings."})

upsc.append({"q":"Which one of the following statements about the scope of judicial review in India is NOT correct?","o":["A legislative enactment or executive order can be challenged in court only on the single ground that it infringes Fundamental Rights, with no other permissible ground","A legislative enactment or executive order can be challenged on the ground that it is outside the competence of the authority that framed it","A legislative enactment or executive order can be challenged on the ground that it is repugnant to the constitutional provisions","The narrower scope of judicial review in India, compared to the USA, stems from India's 'procedure established by law' standard versus the American 'due process of law' standard"],"a":0,"e":"This statement is incorrect — Indian law recognises THREE grounds for challenging a law's constitutional validity (infringement of Fundamental Rights, want of legislative competence, and repugnancy to constitutional provisions), not just the Fundamental Rights ground alone. The other three statements are correct."})

upsc.append({"q":"Assertion (A): The power of judicial review in India cannot be curtailed or excluded even by a constitutional amendment.\nReason (R): The Supreme Court has declared judicial review to be a basic feature of the Constitution, forming part of its basic structure.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — because judicial review has been judicially recognised as part of the Constitution's basic structure, it falls outside the amending power of Parliament under Article 368 (per the basic structure doctrine), directly explaining why it cannot be curtailed even by constitutional amendment."})

upsc.append({"q":"Which one of the following statements about the removal (impeachment) of a Supreme Court judge, per the Judges Enquiry Act, 1968, is NOT correct?","o":["Justice V. Ramaswami remains the only Supreme Court judge ever actually removed from office through the impeachment process, in 1993","A removal motion requires signatures of 100 members (Lok Sabha) or 50 members (Rajya Sabha) before being given to the Speaker/Chairman","If admitted, a three-member committee (a Supreme Court judge, a High Court Chief Justice, and a distinguished jurist) investigates the charges","The motion, if the judge is found guilty, must still be passed by each House of Parliament by special majority before an address is presented to the President"],"a":0,"e":"This statement is incorrect — no judge of the Supreme Court has ever actually been removed through impeachment; Justice V. Ramaswami's 1991-93 case was found guilty by the enquiry committee but the impeachment motion was DEFEATED in the Lok Sabha (the Congress Party abstained), so he was not removed. The other three statements correctly describe the procedure."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch26_27_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
