import json

upsc = []

# ==================================================================
# TOP-UP: PARLIAMENTARY COMMITTEES (Laxmikanth, Ch.24) - covering gaps:
# Committee on Petitions, Ethics Committee, Papers Laid on Table,
# Welfare of SC/ST, Empowerment of Women, Offices of Profit,
# Day-to-day business committees, House-keeping committees, Consultative Committees
# ==================================================================

upsc.append({"q":"Which one of the following statements about the Committee on Petitions is NOT correct?","o":["It has no role regarding petitions on bills, being confined exclusively to representations from foreign entities","It examines petitions on bills and on matters of general public importance","It entertains representations from individuals and associations on matters pertaining to Union subjects","The Lok Sabha committee consists of 15 members, while the Rajya Sabha committee consists of 10 members"],"a":0,"e":"This statement is incorrect and reverses the actual scope — the Committee on Petitions DOES examine petitions specifically on bills (in addition to matters of general public importance), and it entertains representations from individuals/associations, not exclusively foreign entities. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Ethics Committee of Parliament is NOT correct?","o":["It was constituted in the Lok Sabha in 1997 and in the Rajya Sabha in 2000, in that chronological order","It enforces the code of conduct of members of Parliament and examines cases of misconduct, recommending appropriate action","It is engaged in maintaining discipline and decorum in Parliament","The Lok Sabha committee has 15 members while the Rajya Sabha committee has 10 members"],"a":0,"e":"This statement is incorrect and reverses the actual chronology — the Ethics Committee was constituted in the RAJYA SABHA first, in 1997, and in the LOK SABHA later, in 2000 — not the other way around. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Committee on Papers Laid on the Table is NOT correct?","o":["It was constituted in 1975 and examines statutory notifications and orders that also fall under the jurisdiction of the Committee on Subordinate Legislation","It examines all papers laid on the table of the House by ministers to see whether they comply with the provisions of the Constitution, or the related Act or Rule","The Lok Sabha Committee has 15 members, while the Rajya Sabha Committee has 10 members","It is distinct in scope from the Committee on Subordinate Legislation, which handles statutory notifications and orders"],"a":0,"e":"This statement is incorrect and reverses the actual jurisdictional boundary — the Committee on Papers Laid on the Table explicitly does NOT examine statutory notifications and orders, since those fall under the separate jurisdiction of the Committee on Subordinate Legislation. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the Committee on Welfare of SCs and STs and the Committee on Empowerment of Women:\n1. The Committee on Welfare of SCs and STs consists of 30 members (20 from Lok Sabha and 10 from Rajya Sabha).\n2. The Committee on Empowerment of Women was constituted in 1997 and also consists of 30 members (20 from Lok Sabha and 10 from Rajya Sabha).\n3. The Committee on Empowerment of Women considers the reports of the National Commission for Women.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the book's description of both committees' composition (30 members each, split 20:10 between Lok Sabha and Rajya Sabha), the Empowerment of Women committee's 1997 constitution, and its function of considering National Commission for Women reports."})

upsc.append({"q":"Which one of the following statements about the Joint Committee on Offices of Profit is NOT correct?","o":["It consists of 30 members equally divided between the Lok Sabha and Rajya Sabha (15 each)","It examines the composition and character of committees and other bodies appointed by the Central, state and union territory governments","It recommends whether persons holding such offices should be disqualified from being elected as members of Parliament","It consists of 15 members in total, drawn 10 from the Lok Sabha and 5 from the Rajya Sabha"],"a":0,"e":"This statement is incorrect — the Joint Committee on Offices of Profit actually consists of 15 members (10 from the Lok Sabha and 5 from the Rajya Sabha), not 30 members split evenly. The other three statements (its functions) are correct, and are consistent with option D's correct 15-member composition."})

upsc.append({"q":"Match List-I (Day-to-Day Business Committee) with List-II (Distinguishing Feature) and select the correct answer using the code below.\nList-I:\nA. Business Advisory Committee\nB. Committee on Private Members' Bills and Resolutions\nC. Rules Committee\nD. Committee on Absence of Members from Sittings\nList-II:\n1. Special committee of the Lok Sabha with the Deputy Speaker as its chairman; no equivalent exists in the Rajya Sabha\n2. Regulates the programme and time-table of the House; the presiding officer is its ex-officio chairman in both Houses\n3. Considers matters of procedure and conduct of business, recommending amendments to House rules\n4. Examines cases of members absent for 60 days or more without permission; exists only in the Lok Sabha\nCodes:","o":["A-2, B-1, C-3, D-4","A-2, B-3, C-1, D-4","A-1, B-2, C-3, D-4","A-2, B-1, C-4, D-3"],"a":0,"e":"The correct match is A-2, B-1, C-3, D-4: the Business Advisory Committee regulates the House's programme/timetable with the presiding officer as ex-officio chairman; the Committee on Private Members' Bills is a Lok Sabha-only special committee chaired by the Deputy Speaker; the Rules Committee handles procedure; and the Committee on Absence of Members (Lok Sabha-only) examines 60-day-plus unauthorised absences."})

upsc.append({"q":"Which one of the following statements about the Business Advisory Committee (BAC) is NOT correct?","o":["In the Rajya Sabha, the BAC has 15 members, matching the Lok Sabha's membership exactly, with the Deputy Chairman as its ex-officio chairman","In the Lok Sabha, the BAC consists of 15 members including the Speaker as its chairman","In the Rajya Sabha, the BAC has 11 members including the Chairman as its ex-officio chairman","The BAC allocates time for the transaction of legislative and other government business before the House"],"a":0,"e":"This statement is incorrect — the Rajya Sabha's BAC has 11 members (not 15, and not matching the Lok Sabha's count), with the Rajya Sabha CHAIRMAN (not Deputy Chairman) as its ex-officio chairman. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about House-Keeping (Service) Committees of Parliament is NOT correct?","o":["The Library Committee consists of 15 members, split 10 from Lok Sabha and 5 from Rajya Sabha, and oversees the Parliament library's services","The House Committee deals with residential accommodation and amenities (food, medical aid, etc.) for members, with separate committees in the Lok Sabha (12 members) and Rajya Sabha (10 members)","The General Purposes Committee, in each House, advises on matters concerning the affairs of the House not falling within any other committee's jurisdiction, with the presiding officer as ex-officio chairman","The Joint Committee on Salaries and Allowances of Members of Parliament was constituted under the Salary, Allowances and Pension of Members of Parliament Act, 1954, and frames rules regulating these payments"],"a":0,"e":"This statement is incorrect — the Library Committee actually consists of 9 members (6 from Lok Sabha and 3 from Rajya Sabha), not 15 members split 10:5. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about Consultative Committees is NOT correct?","o":["They are permanent bodies whose membership continues unchanged even after a Lok Sabha is dissolved, since they are attached to ministries rather than to the House","They are attached to various ministries/departments and provide a forum for informal discussion between ministers and members of Parliament on government policies and their implementation","The minister (or minister of state) in charge of the concerned ministry acts as the chairman of that ministry's Consultative Committee","They are constituted by the Ministry of Parliamentary Affairs, with membership voluntary and left to the choice of members and their party leaders (maximum 30, minimum 10 members)"],"a":0,"e":"This statement is incorrect and reverses the actual position — Consultative Committees stand DISSOLVED upon the dissolution of every Lok Sabha and are reconstituted only after a new Lok Sabha is constituted; they are not permanent, continuing bodies. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Railway Convention Committee and other ad hoc Inquiry Committees is NOT correct?","o":["The Railway Convention Committee has, since its inception in 1949, confined itself exclusively to determining the Rate of Dividend payable by the Railways to General Revenues, with no change in scope since then","The Railway Convention Committee, 1949 was the first such committee constituted after independence","Since 1971, Railway Convention Committees have taken up subjects with a bearing on the working of the Railways and Railway finances more broadly, beyond just the dividend rate","The Committee on Members of Parliament Local Area Development Scheme (MPLADS) is an example of an ad hoc Inquiry Committee constituted to inquire into and report on a specific subject"],"a":0,"e":"This statement is incorrect — while the Railway Convention Committee and its immediate successors initially confined themselves to the Rate of Dividend question, SINCE 1971 they have taken up broader subjects bearing on Railway working and finances, not remained unchanged in scope. The other three statements are correct."})

upsc.append({"q":"Assertion (A): Consultative Committees attached to ministries are not classified as 'Parliamentary Committees' in the strict Laxmikanth sense used for Standing/Ad Hoc Committees.\nReason (R): Parliamentary Committees are defined as being appointed/elected by a House (or nominated by the Speaker/Chairman), working under the presiding officer's direction, reporting to the House/presiding officer, and served by a Lok Sabha/Rajya Sabha secretariat — conditions Consultative Committees do not fulfil.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text explicitly defines a parliamentary committee by four conditions (appointment/election, direction of presiding officer, reporting mechanism, House secretariat support) and notes consultative committees, though composed of MPs, do not fulfil these conditions and are therefore excluded from the strict definition."})

upsc.append({"q":"Which one of the following statements about Informal Consultative Committees for Railway Zones is correct?","o":["Separate Informal Consultative Committees are constituted for each Railway Zone, with members of Parliament from the area falling under a particular zone nominated to its committee","There is only a single, unified Informal Consultative Committee covering all Railway Zones in the country","These committees are constituted by the Ministry of Railways independently of the Ministry of Parliamentary Affairs' consultative committee framework","Membership of these committees is compulsory for all MPs whose constituency falls within a Railway Zone"],"a":0,"e":"The text states separate Informal Consultative Committees are constituted for all the Railway Zones, with MPs belonging to the area falling under a particular Railway Zone nominated to that zone's committee — not a single unified committee, and membership is voluntary like other consultative committees, not compulsory."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch24_topup.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
