import json

upsc = []

# ==================================================================
# NEW UPSC TIER: STATE LEGISLATURE (Ch.33)
# ==================================================================

upsc.append({"q":"Consider the following statements about matters where the Legislative Council's powers are broadly EQUAL to the Legislative Assembly's:\n1. Introduction and passage of ordinary bills, though the Assembly's will prevails in case of disagreement.\n2. Approval of ordinances issued by the Governor.\n3. Selection of ministers, including the Chief Minister, who can be members of either House though responsible only to the Assembly.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct and match the book's list of spheres where the Council's status is broadly equal to the Assembly's: ordinary bill passage (subject to Assembly primacy on disagreement), ordinance approval, and minister selection (with responsibility resting solely on the Assembly)."})

upsc.append({"q":"Which one of the following statements about matters where the Legislative Council is UNEQUAL to the Legislative Assembly is NOT correct?","o":["The Legislative Council can amend or reject a Money Bill outright, exercising powers identical to the Assembly in financial matters","A Money Bill can be introduced only in the Assembly, and the Council can at most return it within 14 days with or without recommendations","The Council can detain an ordinary bill for a maximum of four months (three in the first instance, one in the second) but cannot ultimately block it","The Council cannot remove the Council of Ministers through a no-confidence motion, since ministers are collectively responsible only to the Assembly"],"a":0,"e":"This statement is incorrect and reverses the actual position — the Council CANNOT amend or reject a Money Bill; it can only return it (with or without recommendations) within 14 days, and the Assembly may accept or reject those recommendations. The other three statements are correct."})

upsc.append({"q":"Which one of the following is NOT among the reasons given in the text for why the Legislative Council has been assigned much less importance than the Rajya Sabha?","o":["The Council's members serve longer terms than Rajya Sabha members, making it less accountable to changing public opinion","The Rajya Sabha reflects the federal element of the polity (representing states) and must therefore be an effective revising body, whereas no such federal significance attaches to the Council","The Council is heterogeneously constituted with differently elected and nominated members, weakening its effectiveness as a revising body, unlike the homogeneously constituted Rajya Sabha","The pattern of Assembly-Council relations follows the British model, where the House of Lords cannot oppose or obstruct the House of Commons"],"a":0,"e":"This is NOT a reason given in the text — term length differences are not cited as a reason for the Council's weaker status; the actual reasons given are the absence of federal significance, the Council's heterogeneous composition (versus Rajya Sabha's homogeneity), and the British-model pattern of Lower House predominance."})

upsc.append({"q":"Which one of the following statements about the final authority to decide whether a bill is a Money Bill, and to detain an ordinary state bill, is correct?","o":["The Speaker of the Assembly has final power to certify a Money Bill, and the Assembly has final power over passing ordinary bills, with the Council able only to delay (not block) an ordinary bill for up to four months","The Chairman of the Legislative Council has final power to certify a Money Bill, while the Speaker of the Assembly controls ordinary bill passage","Both Houses jointly and equally decide whether a bill is a Money Bill, requiring a joint sitting in case of disagreement","The Governor has final power to certify a Money Bill, overriding both the Speaker and the Chairman"],"a":0,"e":"The text is explicit: the Speaker of the Assembly has the final power to decide whether a bill is a Money Bill, and the Assembly has the final say on ordinary bills, with the Council functioning only as a delaying (dilatory) chamber able to detain such a bill for a maximum of four months, not as a co-equal revising body like the Rajya Sabha."})

upsc.append({"q":"Which one of the following critical descriptions has been used by critics of the Legislative Council, per the text?","o":["'Costly ornamental luxury' and 'white elephant'","'Third chamber of Parliament'","'Shadow cabinet of the states'","'Constitutional watchdog of federalism'"],"a":0,"e":"The text explicitly notes critics have described the Legislative Council as a 'secondary chamber', 'costly ornamental luxury', and 'white elephant' — given its weak, powerless position — not any of the other descriptive phrases listed."})

upsc.append({"q":"Consider the following statements about the utility of the Legislative Council, as argued in its defence:\n1. It checks hasty, defective, or ill-considered legislation made by the Assembly by enabling revision and further thought.\n2. It facilitates representation of eminent professionals and experts who may be unable to face direct elections, partly through the Governor's nomination of one-sixth of its members.\n3. It has historically served exclusively as a training ground for first-time entrants to politics who have never previously held any public office.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect — the text notes critics say the Council has served as a 'refuge' for those DEFEATED in assembly elections (i.e., experienced but rejected politicians), not as a training ground exclusively for first-time entrants. Statements 1 and 2 are correct arguments for the Council's utility."})

upsc.append({"q":"Which one of the following statements about the collective privileges of the state legislature is NOT correct?","o":["Courts are fully empowered to inquire into the internal proceedings of a House or its Committees at any time, without restriction","Each House can exclude strangers from its proceedings and hold secret sittings to discuss important matters","Each House can punish members and outsiders for breach of privilege or contempt, through reprimand, admonition, imprisonment, suspension or expulsion","No person can be arrested, and no civil or criminal legal process served, within the precincts of the House without the presiding officer's permission"],"a":0,"e":"This statement is incorrect and reverses the actual position — courts are explicitly PROHIBITED from inquiring into the proceedings of a House or its Committees, not fully empowered to do so at will. The other three statements are correct collective privileges."})

upsc.append({"q":"Which one of the following statements about the individual privileges of members of a state legislature is NOT correct?","o":["Freedom from arrest applies equally to civil and criminal cases, protecting a member from arrest in any case during the session and 40 days before/after it","Members cannot be arrested during the session and for 40 days before its start and 40 days after its end, but only in civil cases, not criminal or preventive detention cases","Members have freedom of speech in the legislature and cannot be proceeded against in any court for anything said or any vote given in the House or its committees","Members are exempted from jury service and can refuse to appear as witnesses in a pending case when the legislature is in session"],"a":0,"e":"This statement is incorrect — the freedom-from-arrest privilege applies ONLY to civil cases, not to criminal cases or preventive detention, contrary to the claim that it applies equally to both. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about privileges extended to non-members participating in state legislature proceedings is correct?","o":["The Advocate General of the state and state ministers, when entitled to speak and participate in House proceedings, are also extended the privileges of the state legislature","The Governor, being an integral part of the state legislature, is also entitled to the privileges of the state legislature, on par with the Advocate General","Privileges are extended only to elected members and never to any non-member functionary under any circumstance","Only the Speaker and Deputy Speaker among non-elected functionaries can claim legislative privileges"],"a":0,"e":"The text explicitly extends legislative privileges to persons entitled to speak/participate in proceedings, namely the Advocate General and state ministers — while explicitly clarifying that the Governor, despite being an integral part of the state legislature, is NOT extended these privileges."})

upsc.append({"q":"Assertion (A): The Legislative Council's position vis-a-vis the Assembly is much weaker than the Rajya Sabha's position vis-a-vis the Lok Sabha.\nReason (R): The Rajya Sabha has equal powers with the Lok Sabha in all spheres except financial matters and control over the government, whereas the Council is subordinate to the Assembly in virtually all respects.\nWhich one of the following is correct in respect of the above Assertion (A) and Reason (R)?","o":["Both A and R are true, and R is the correct explanation of A","Both A and R are true, but R is NOT the correct explanation of A","A is true, but R is false","A is false, but R is true"],"a":0,"e":"Both are true and R explains A — the text draws this exact comparison, noting the Rajya Sabha's broad equality with the Lok Sabha (barring finance and government-control matters) contrasts sharply with the Council's near-total subordination to the Assembly, directly explaining why the Council's relative position is weaker."})

upsc.append({"q":"Which one of the following statements about the fate of a bill originating in the Legislative Council and rejected by the Legislative Assembly is correct?","o":["The bill ends and becomes dead once rejected by the Assembly, with no revival mechanism available to the Council","The bill must be sent back to the Council for reconsideration, and if passed again, becomes law regardless of the Assembly's view","The bill automatically proceeds to the Governor for assent despite the Assembly's rejection","The bill is referred to a joint sitting of both Houses of the state legislature for final resolution"],"a":0,"e":"The text is explicit: when an ordinary bill originating in the Council and sent to the Assembly is rejected by the Assembly, the bill simply ends and becomes dead — there is no joint-sitting mechanism at the state level (unlike Parliament) and no revival procedure for the Council."})

upsc.append({"q":"Which one of the following statements about the Legislative Council's role in constitutional matters is NOT correct?","o":["The Legislative Council participates on an equal footing with the Assembly in the election of the President of India and in electing the state's representatives to the Rajya Sabha","The Council has no effective say in the ratification of a constitutional amendment bill, with the Assembly's will prevailing","The very existence of the Council depends on the will of the Assembly, since Parliament can abolish it on the Assembly's recommendation","The Council does not participate in the election of the President of India or in electing the state's Rajya Sabha representatives"],"a":0,"e":"This statement is incorrect and directly contradicts the text and option D — the Council explicitly does NOT participate in the election of the President of India or in choosing the state's representatives to the Rajya Sabha; only elected MLAs (not MLCs) have this role. The other three statements are correct."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch33_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
