import json

upsc = []

# ==================================================================
# NEW UPSC TIER: NHRC (Ch.57) + CVC (Ch.64) + CBI (Ch.65) + LOKPAL/LOKAYUKTAS (Ch.66)
# Large merged batch — 4 distinct bodies, proportionally larger question count
# ==================================================================

# ---------------- NHRC ----------------

upsc.append({"q":"Which one of the following statements about the composition of the National Human Rights Commission (NHRC) is correct?","o":["Besides the Chairperson and five full-time members, the NHRC also has seven ex-officio members, including the chairpersons of the National Commissions for Minorities, SCs, STs, Women, BCs, Child Rights, and the Chief Commissioner for Persons with Disabilities","The NHRC consists only of a Chairperson and five full-time members, with no provision for ex-officio members","The NHRC has ten full-time members besides the Chairperson, with no ex-officio members at all","The seven ex-officio members of NHRC are all sitting judges of various High Courts"],"a":0,"e":"The NHRC's composition explicitly includes seven ex-officio members — the chairpersons of the National Commissions for Minorities, SCs, STs, Women, BCs, Child Rights, plus the Chief Commissioner for Persons with Disabilities — in addition to the Chairperson and full-time members, not merely five members with no ex-officio component."})

upsc.append({"q":"Which one of the following is NOT among the grounds on which the President can remove the Chairperson or a member of the NHRC (other than proved misbehaviour/incapacity requiring a Supreme Court reference)?","o":["If he/she has been absent from three consecutive meetings of the Commission without leave","If he/she is adjudged insolvent","If he/she is of unsound mind and stands so declared by a competent court","If he/she is convicted and sentenced to imprisonment for an offence"],"a":0,"e":"'Absence from three consecutive meetings' is not among the NHRC's listed removal grounds — the actual grounds include insolvency, unsoundness of mind (declared by a competent court), conviction and sentence for an offence, engaging in paid outside employment, and unfitness due to infirmity of mind/body."})

upsc.append({"q":"Which one of the following statements about the NHRC's power to inquire into complaints is correct?","o":["The NHRC is not empowered to inquire into any matter after the expiry of one year from the date on which the alleged human rights violation occurred","The NHRC can inquire into any human rights violation regardless of how much time has elapsed since its occurrence","The NHRC's limitation period for inquiry is five years from the date of the alleged violation","The one-year limitation period applies only to complaints against private individuals, not public servants"],"a":0,"e":"The NHRC is explicitly barred from inquiring into a matter after one year has elapsed from the date of the alleged violation — there is no five-year period, no unlimited timeframe, and no distinction based on whether the accused is a public servant or private individual (NHRC's core jurisdiction concerns public servants specifically)."})

upsc.append({"q":"Which one of the following statements about the NHRC's role concerning the armed forces is correct?","o":["The NHRC has a limited role, and in this sphere it may seek a report from the Central Government and make recommendations, with the Central Government required to inform the Commission of action taken within three months","The NHRC has exactly the same full powers and jurisdiction over the armed forces as it does over other public servants","The NHRC has no role whatsoever concerning human rights violations by the armed forces","The three-month reporting requirement for armed forces cases applies to the NHRC, not the Central Government"],"a":0,"e":"The text explicitly notes the NHRC has a LIMITED role/jurisdiction regarding armed forces violations, confined to seeking a report and making recommendations, with the Central Government (not the NHRC) obligated to report back on action taken within three months (compared to one month for ordinary cases)."})

upsc.append({"q":"Consider the following statements about the NHRC's compliance with the Paris Principles and the constraints identified in its own Annual Report:\n1. The Paris Principles require National Human Rights Institutions to have adequate funding and staff to remain independent of government financial control.\n2. The NHRC has identified administrative, financial and manpower constraints as challenges to its effective functioning.\n3. In 2017, the Supreme Court expressed concern over the shortage of manpower in the NHRC and directed the Government to remedy it.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct — the Paris Principles' funding/staffing independence requirement, the NHRC's self-identified constraints (administrative, financial, manpower), and the 2017 Supreme Court intervention on manpower shortage are all explicitly documented in the text."})

upsc.append({"q":"Which one of the following functions is explicitly assigned to the NHRC under the Protection of Human Rights Act, 1993?","o":["To visit jails and other detention places to study the living conditions of inmates and make recommendations thereon","To directly award monetary compensation to victims, enforceable as a court decree","To try and convict public servants found guilty of human rights violations","To exercise superintendence over the Central Bureau of Investigation in human rights cases"],"a":0,"e":"Visiting jails/detention places and studying inmates' living conditions is an explicit NHRC function. The Commission has no power to directly award enforceable compensation, to try/convict violators, or to superintend the CBI — its role is recommendatory only."})

# ---------------- CVC ----------------

upsc.append({"q":"Which one of the following statements about the composition and appointment of the Central Vigilance Commission (CVC) is correct?","o":["The CVC consists of a Central Vigilance Commissioner and not more than two Vigilance Commissioners, appointed by the President on the recommendation of a three-member committee comprising the Prime Minister, the Union Home Minister, and the Leader of the Opposition in the Lok Sabha","The CVC consists of a Central Vigilance Commissioner and exactly two Vigilance Commissioners, with no discretion to appoint fewer","The CVC's appointing committee includes the Chief Justice of India as a mandatory member","The CVC's Vigilance Commissioners are appointed directly by the Central Vigilance Commissioner, without any committee recommendation"],"a":0,"e":"The CVC comprises the Commissioner plus UP TO (not exactly) two Vigilance Commissioners, appointed by the President on a three-member committee's recommendation (PM, Home Minister, Leader of Opposition in Lok Sabha) — the CJI is not part of this particular committee (unlike the NHRC or Lokpal committees)."})

upsc.append({"q":"Which one of the following is NOT among the grounds for removal of the Central Vigilance Commissioner or a Vigilance Commissioner listed in the CVC Act, 2003?","o":["If he/she has, without reasonable cause, failed to attend meetings of the Commission for a continuous period of six months","If he/she has been convicted of an offence which, in the opinion of the Central Government, involves moral turpitude","If he/she has acquired such financial or other interest as is likely to affect prejudicially his/her official functions","If he/she is adjudged an insolvent"],"a":0,"e":"'Failure to attend meetings for six months' is not among the CVC's actual removal grounds — the genuine grounds include insolvency, conviction involving moral turpitude, engaging in paid outside employment, infirmity of mind/body, and acquisition of prejudicial financial interests."})

upsc.append({"q":"Which one of the following statements about the CVC's internal organisational wings is correct?","o":["The Chief Technical Examiners' Wing conducts technical audits of government construction works from a vigilance angle and assists the CBI in investigations involving technical matters","The Commissioners for Departmental Inquiries (CDIs) form the technical engineering wing responsible for construction audits","The CVC's Secretariat is headed by a retired Supreme Court judge rather than a Secretary-rank officer","The CVC has no distinct internal wings and operates through a single unified office"],"a":0,"e":"The Chief Technical Examiners' (CTE) Wing genuinely handles technical audit of construction works and assists CBI with technical evaluations — the CDIs are a separate wing that conducts oral departmental inquiries (not construction audits), and the CVC does have distinct internal wings (Secretariat, CTE, CDIs), contrary to the other options."})

upsc.append({"q":"With reference to the CVC's jurisdiction, which one of the following categories of officials is correctly included within its ambit?","o":["Officers of the rank of Scale V and above in Public Sector Banks","Officers of any scale or grade in Public Sector Banks, without any seniority threshold","Only officers of the All-India Services, with Public Sector Undertaking employees entirely excluded","State government employees of all ranks in state-owned public sector undertakings"],"a":0,"e":"The CVC's jurisdiction specifically covers Public Sector Bank officers of Scale V and above (not all scales), in addition to All-India Service members/Group A Central officers and specified-grade PSU/RBI/NABARD/SIDBI officers — state government employees in state PSUs fall outside the CVC's (a Central body's) jurisdiction."})

upsc.append({"q":"Which one of the following statements about the Whistle Blowers Protection Act (2014) is NOT correct?","o":["The Act was originally enacted in 2014 without any prior legislative history and has not been renamed or redated since its passage","The Act lays down punishment of up to two years imprisonment and a fine of up to ₹30,000 for false or frivolous complaints","The Act designates the Central Vigilance Commission as the competent authority to receive public interest disclosures on corruption","The Act is not applicable to the Special Protection Group"],"a":0,"e":"This statement is incorrect — the Act was originally introduced as the Whistle Blowers Protection Act of 2011, and only later renamed/redated to 2014 upon actual enactment; it does have this prior legislative history. The other three statements about punishment, the CVC's role, and the SPG exemption are correct."})

# ---------------- CBI ----------------

upsc.append({"q":"Which one of the following statements about the historical origins of the CBI is correct?","o":["The CBI traces its origin to the Special Police Establishment set up in 1941 to investigate bribery and corruption in the War and Supply Department, with the Delhi Special Police Establishment Act of 1946 later transferring its superintendence to the Home Department and expanding its functions to all government departments","The CBI was directly established in 1941 as a fully constituted central investigating agency","The Delhi Special Police Establishment Act was enacted in 1963, the same year as the CBI's own establishment","The Special Police Establishment of 1941 was, from its inception, under the administrative control of the Ministry of Personnel"],"a":0,"e":"The correct lineage is: Special Police Establishment (1941, under the War and Supply Department) → Delhi Special Police Establishment Act (1946, transferring superintendence to Home Department, expanding scope) → CBI established by a 1963 MHA resolution, later moved to the Ministry of Personnel — not a direct 1941 full establishment or simultaneous 1963 DSPE Act enactment."})

upsc.append({"q":"Which one of the following correctly distinguishes the National Investigation Agency (NIA) from the CBI, as per the text?","o":["The NIA, constituted after the 2008 Mumbai terror attack, mainly investigates terrorism-related crimes, whereas the CBI investigates corruption, economic offences and serious organised crime other than terrorism","The NIA and CBI have identical jurisdictions and were both established as a direct response to the 2008 Mumbai attacks","The CBI was constituted specifically to investigate terrorism-related crimes, while the NIA handles corruption cases","The NIA is a division functioning directly under the CBI's administrative control"],"a":0,"e":"The NIA (post-2008 Mumbai attack) is focused on terrorism-related crime, while the CBI's mandate covers corruption, economic offences, and organised crime OTHER than terrorism — the two are separate, differently-focused agencies, not identical or hierarchically linked."})

upsc.append({"q":"Which one of the following statements about the 2014 and 2021 amendments to the Delhi Special Police Establishment Act concerning the CBI Director is correct?","o":["The 2021 amendment allows the Central Government to extend the CBI Director's fixed two-year tenure by up to three annual extensions, with the total tenure not exceeding five years","The 2021 amendment abolished the fixed two-year tenure altogether, making the CBI Director's term open-ended","The 2014 amendment changed the CBI Director's appointing committee to include the Chief Justice of India, replacing the Prime Minister as chairperson","The 2021 amendment permits unlimited annual extensions to the CBI Director's tenure with no upper cap"],"a":0,"e":"The 2021 amendment specifically permits up to three one-year extensions (capping total tenure at five years, including the initial two years) — it did not create an open-ended term, does not allow unlimited extensions, and the 2014 amendment concerned the Leader of Opposition clause (single largest opposition party when no recognised LoP exists), not the CJI replacing the PM as committee chair."})

upsc.append({"q":"Which one of the following statements about the requirement of 'prior permission' for CBI investigations is correct?","o":["In 2014, the Supreme Court struck down as unconstitutional (violative of Article 14) the provision under Section 6A of the DSPE Act that required prior Central Government approval before the CBI could even conduct a preliminary inquiry against Joint Secretary-rank officers and above in corruption cases","The Supreme Court upheld the constitutionality of Section 6A of the DSPE Act in its entirety in 2014","The prior permission requirement under Section 6A applied only to officers below the rank of Under Secretary","Section 6A's prior-permission requirement was struck down by a Parliamentary resolution, not a judicial ruling"],"a":0,"e":"A Constitution Bench in 2014 struck down Section 6A of the DSPE Act (which shielded Joint Secretary-and-above officers from even a preliminary CBI inquiry without prior government sanction) as violative of Article 14 — not upheld, not applicable to junior officers, and struck down by judicial ruling, not a parliamentary resolution."})

upsc.append({"q":"Which one of the following administrative arrangements correctly describes how the CBI (Delhi Special Police Establishment) and state police forces avoid overlapping jurisdiction, as per the text?","o":["The DSPE takes up cases essentially and substantially concerned with Central Government affairs or employees, even if some state government employees are also involved, while the state police handle cases substantially concerned with state government affairs","The DSPE handles only cases with zero state government employee involvement, however minor","State police forces have no concurrent powers of investigation under the DSPE Act, 1946, in any circumstances","The DSPE can never take up cases against employees of Central Government-financed public undertakings"],"a":0,"e":"The actual arrangement allocates cases based on which government's affairs/employees are 'essentially and substantially' concerned — even with some overlap involving the other government's employees — and DSPE does enjoy concurrent powers alongside state police under the 1946 Act, and does take up cases against Central-financed public undertaking employees."})

# ---------------- LOKPAL & LOKAYUKTAS ----------------

upsc.append({"q":"Which one of the following statements about the global origins of the Ombudsman institution is correct?","o":["The institution of Ombudsman was first created in Sweden in 1809, and subsequently spread to Finland (1919), Denmark (1955) and Norway (1962), with New Zealand becoming the first Commonwealth country to adopt it in 1962","The institution of Ombudsman originated in New Zealand in 1962 and later spread to Scandinavian countries","The United Kingdom was the first country in the world to adopt the Ombudsman institution, in 1809","Finland adopted the Ombudsman institution before Sweden did"],"a":0,"e":"Sweden (1809) was the originator; Finland (1919), Denmark (1955) and Norway (1962) followed among Scandinavian countries, with New Zealand (1962) as the first Commonwealth adopter and the UK only adopting an Ombudsman-like institution in 1967 — not the reverse chronology in the other options."})

upsc.append({"q":"Which one of the following scholars is correctly matched with their description of the Ombudsman institution?","o":["Donald C. Rowat — described the Ombudsman as a 'bulwark of democratic government against the tyranny of officialdom'","Gerald E. Caiden — described the Ombudsman as 'a uniquely appropriate institution for dealing with citizens' complaints'","Donald C. Rowat — described the Ombudsman as 'institutionalised public conscience'","Gerald E. Caiden — first proposed the Swedish Ombudsman system in 1809"],"a":0,"e":"Donald C. Rowat is correctly credited with the 'bulwark of democratic government against the tyranny of officialdom' description (as well as the 'uniquely appropriate institution' quote), while Gerald E. Caiden is the one who separately described it as 'institutionalised public conscience' — the other pairings mismatch the scholars and their actual quotes/roles."})

upsc.append({"q":"Which one of the following statements about the First Administrative Reforms Commission's (1966-1970) recommendations on Lokpal and Lokayukta is NOT correct?","o":["The ARC recommended that the judiciary be brought within the purview of both the Lokpal and Lokayukta, following the Swedish Ombudsman model","The ARC recommended that the Lokpal be appointed by the President after consultation with the Chief Justice of India, the Speaker of the Lok Sabha, and the Chairman of the Rajya Sabha","The ARC recommended that the Lokpal deal with complaints against ministers and secretaries at the Central and state levels","The ARC recommended that the institutions' proceedings should not be subject to judicial interference"],"a":0,"e":"This statement is incorrect and reverses the ARC's actual recommendation — the ARC explicitly kept the JUDICIARY OUTSIDE the purview of Lokpal/Lokayukta (following the New Zealand model, not Sweden, where the judiciary IS within Ombudsman purview). The other three statements accurately reflect the ARC's recommendations."})

upsc.append({"q":"With reference to the ten official legislative attempts to enact a Lokpal law before 2013, which one of the following statements is correct?","o":["The first Lokpal Bill was introduced in May 1968 by the Congress Government headed by Indira Gandhi, and the tenth attempt (the Lokpal and Lokayuktas Bill, 2011) was finally enacted as the Lokpal and Lokayuktas Act, 2013","The first Lokpal Bill was introduced in 1977 by the Janata Government headed by Morarji Desai","All ten Lokpal Bills introduced between 1968 and 2011 lapsed due to dissolution of the Lok Sabha, with none being withdrawn","The Lokpal and Lokayuktas Act, 2013 was enacted based on a bill first introduced in 2001 by the NDA government"],"a":0,"e":"The first bill was indeed introduced in May 1968 (Indira Gandhi's Congress government), and it was the TENTH bill (December 2011, UPA government) that was finally enacted in 2013 — not all bills lapsed via dissolution (the fifth and ninth were explicitly withdrawn by their respective governments), and the enacted bill was not the 2001 NDA-era one."})

upsc.append({"q":"Which one of the following is NOT among the drawbacks (shortcomings) of the Lokpal and Lokayuktas Act, 2013 as identified in the text?","o":["The Lokpal has been granted suo motu power to proceed against any public servant without any complaint","There is heavy punishment for false and frivolous complaints against public servants, which may deter genuine complaints","Anonymous complaints are not allowed under the Act","There is a very non-transparent procedure for dealing with complaints against the Prime Minister"],"a":0,"e":"This is the reverse of an actual drawback — the Act is criticised precisely because the Lokpal CANNOT proceed suo motu against any public servant, not because it has unrestricted suo motu power. The other three are genuine, textually-identified drawbacks of the 2013 Act."})

upsc.append({"q":"Which one of the following statements about the institution of Lokayukta at the state level is correct?","o":["The institution of Lokayukta was established first in Maharashtra in 1971, although Odisha had passed an enabling Act in 1970","The institution of Lokayukta was established first in Odisha in 1970, with full implementation preceding Maharashtra's 1971 establishment","All states have a uniform Lokayukta structure that includes both a Lokayukta and an Upalokayukta","The Chief Minister is uniformly included within the jurisdiction of the Lokayukta in every state"],"a":0,"e":"Maharashtra was the first state to actually ESTABLISH the Lokayukta institution (1971), even though Odisha had passed its enabling Act earlier (1970) without corresponding establishment — and there is explicitly no uniformity across states regarding Upalokayukta structure or Chief Minister's inclusion within Lokayukta jurisdiction."})

upsc.append({"q":"Consider the following statements about the Lokpal and Lokayuktas Act, 2013's provisions strengthening the CBI:\n1. It provides for a Directorate of Prosecution headed by a Director of Prosecution functioning under the overall control of the Director of CBI.\n2. The Director of Prosecution is appointed by the Central Government on the recommendation of the Central Vigilance Commission.\n3. Transfer of CBI officers investigating Lokpal-referred cases requires the Lokpal's approval.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements accurately reflect the Act's CBI-strengthening provisions — the Directorate of Prosecution under the CBI Director's overall control, CVC-recommended appointment of its Director, and Lokpal-approval-gated transfers of investigating officers."})

upsc.append({"q":"Which one of the following statements about the Lokpal's enhancement of punishment under the Prevention of Corruption Act is correct?","o":["The Lokpal and Lokayuktas Act, 2013 enhanced the maximum punishment under the Prevention of Corruption Act from seven years to ten years","The 2013 Act reduced the maximum punishment under the Prevention of Corruption Act from ten years to seven years","The 2013 Act left the punishment provisions of the Prevention of Corruption Act entirely unchanged","The minimum punishment under Sections 7, 8, 9 and 12 of the Prevention of Corruption Act was reduced to one year by the 2013 Act"],"a":0,"e":"The Act genuinely raised the maximum punishment from seven to ten years, and also raised (not reduced) the minimum punishment under Sections 7, 8, 9 and 12 to three years (and under Section 15 to two years) — not a reduction or a status quo scenario."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch57_64_65_66_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
