import json

upsc = []

# ==================================================================
# NEW UPSC TIER: PANCHAYATI RAJ (Ch.39)
# ==================================================================

upsc.append({"q":"Which one of the following statements about the Ashok Mehta Committee (1977-78) on Panchayati Raj is NOT correct?","o":["It recommended replacing the two-tier system with a three-tier system, adding the Gram Panchayat as an intermediate level between Zila Parishad and Mandal Panchayat","It recommended replacing the existing three-tier system with a two-tier system: Zila Parishad at the district level and Mandal Panchayat below it (covering a population of 15,000-20,000)","It recommended official participation of political parties at all levels of panchayat elections","It recommended that the chief electoral officer of a state, in consultation with the Chief Election Commissioner, should organise and conduct panchayati raj elections"],"a":0,"e":"This statement is incorrect and reverses the Committee's actual recommendation — the Ashok Mehta Committee recommended replacing the THREE-tier system with a TWO-tier system (Zila Parishad and Mandal Panchayat), not adding a third tier. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about the G.V.K. Rao Committee (1985):\n1. It concluded that the developmental process had become bureaucratised and divorced from Panchayati Raj, describing the phenomenon as 'grass without roots'.\n2. It recommended creating a post of District Development Commissioner to act as the chief executive officer of the Zila Parishad.\n3. It recommended reducing the Zila Parishad's importance in favour of a state-level planning body.\nWhich of the statements given above is/are correct?","o":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"a":0,"e":"Statement 3 is incorrect and reverses the Committee's actual view — the G.V.K. Rao Committee assigned the Zila Parishad PIVOTAL importance as the principal body for managing district-level development programmes, not reduced importance in favour of a state-level body. Statements 1 and 2 are correct."})

upsc.append({"q":"Which one of the following statements correctly distinguishes the Hanumantha Rao Committee (1984) from the G.V.K. Rao Committee (1985) on decentralised planning?","o":["The Hanumantha Rao Committee advocated a significant coordinating role for the District Collector in decentralised planning, whereas the G.V.K. Rao Committee recommended reducing the Collector's developmental role in favour of Panchayati Raj institutions","Both committees identically recommended eliminating the District Collector's role entirely in favour of the Zila Parishad","The Hanumantha Rao Committee recommended reducing the Collector's role, while the G.V.K. Rao Committee wanted to strengthen it","Neither committee addressed the role of the District Collector in decentralised planning"],"a":0,"e":"This is the correct distinction — the Hanumantha Rao Committee (like the Dantwala Committee) advocated a significant coordinating role for the District Collector, while the G.V.K. Rao Committee (following the Balwantrai Mehta, First ARC, and Ashok Mehta line) recommended reducing the Collector's developmental role and assigning a major role to Panchayati Raj institutions instead."})

upsc.append({"q":"Which one of the following statements about the L.M. Singhvi Committee (1986) on Panchayati Raj is NOT correct?","o":["It recommended that Nyaya Panchayats be abolished entirely, considering them incompatible with modern judicial administration","It recommended constitutional recognition, protection and preservation of Panchayati Raj institutions through a new chapter in the Constitution","It described the Gram Sabha as the embodiment of direct democracy","It recommended establishing judicial tribunals in each state to adjudicate controversies about elections to Panchayati Raj institutions and their dissolution"],"a":0,"e":"This statement is incorrect and reverses the Committee's actual recommendation — the L.M. Singhvi Committee recommended ESTABLISHING Nyaya Panchayats for a cluster of villages, not abolishing them. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the Thungon Committee (1988) is NOT correct?","o":["It recommended a maximum supersession period of twelve months for a Panchayati Raj body, twice the period later adopted in the 73rd Amendment","It recommended a three-tier system of Panchayati Raj at village, block and district levels, with the Zilla Parishad as its pivot","It recommended a fixed five-year tenure for Panchayati Raj bodies","It recommended constitutional recognition of Panchayati Raj bodies and a detailed constitutionally-incorporated list of subjects for them"],"a":0,"e":"This statement is incorrect — the Thungon Committee recommended a maximum supersession period of SIX months (matching what was eventually adopted in Article 243E), not twelve months. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the 'Continuance of Existing Laws and Panchayats' provision under the 73rd Amendment Act, 1992 is NOT correct?","o":["All pre-existing state panchayat laws were immediately repealed on the date of commencement of the Act (24 April 1993), with no transition period allowed","All state laws relating to panchayats continued in force until the expiry of one year from 24 April 1993, giving states that period to adopt the new system","Panchayats existing immediately before the Act's commencement were to continue until the expiry of their term, unless dissolved sooner by the state legislature","Consequently, the majority of states passed new Panchayati Raj Acts in 1993 and 1994 to adopt the system envisaged by the 73rd Amendment"],"a":0,"e":"This statement is incorrect — pre-existing state panchayat laws were NOT immediately repealed; they continued in force for up to ONE YEAR from 24 April 1993, giving states a transition period to enact conforming legislation. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about states/areas exempted from the 73rd Amendment's Part IX provisions is NOT correct?","o":["The Act applies without exception to Nagaland, Meghalaya and Mizoram, since these states have no special constitutional arrangements that would conflict with Part IX","The hill areas of Manipur, where district councils exist, are exempted from Part IX","Darjeeling district of West Bengal, where the Darjeeling Gorkha Hill Council exists, is exempted","Parliament may extend Part IX's provisions to Scheduled Areas and tribal areas with such exceptions/modifications as it specifies, which it did via the PESA Act, 1996"],"a":0,"e":"This statement is incorrect and reverses the actual position — the 73rd Amendment's Part IX does NOT apply to Nagaland, Meghalaya and Mizoram; these states are explicitly exempted, along with certain scheduled/tribal areas, Manipur's hill areas, and Darjeeling district. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the audit of Panchayat accounts and Union Territory application under the 73rd Amendment is NOT correct?","o":["The Constitution itself fixes a uniform, detailed auditing procedure for all panchayats nationwide, leaving no room for state legislatures to legislate on this matter","The state legislature may make provisions regarding the maintenance of accounts by panchayats and the auditing of such accounts","Part IX's provisions apply to Union Territories, though the President may direct their application subject to exceptions/modifications he/she specifies","The Central Finance Commission also suggests measures to augment a state's Consolidated Fund to supplement panchayats' resources, based on the state finance commission's recommendations"],"a":0,"e":"This statement is incorrect — the Constitution leaves the maintenance and auditing of panchayat accounts to be provided for BY THE STATE LEGISLATURE, not a uniform Constitution-fixed procedure. The other three statements are correct."})

upsc.append({"q":"Which one of the following statements about the bar on court interference in panchayat electoral matters under the 73rd Amendment is NOT correct?","o":["Courts retain full original jurisdiction to entertain direct challenges to the delimitation of panchayat constituencies or allotment of seats to such constituencies, without any procedural restriction","The validity of any law relating to delimitation of panchayat constituencies or seat allotment cannot be questioned in any court","No election to any panchayat can be questioned except by an election petition presented to an authority and in a manner provided by the state legislature","This bar is structurally similar to the bar on court interference in electoral matters for Parliament and state legislatures"],"a":0,"e":"This statement is incorrect and reverses the actual bar — courts are explicitly PROHIBITED from entertaining direct challenges to delimitation/seat-allotment laws; such challenges can only be raised, if at all, through the prescribed election petition mechanism. The other three statements are correct."})

upsc.append({"q":"Consider the following statements about early committees on Panchayati Raj finance and administration, prior to the 73rd Amendment:\n1. The Study Team on Panchayati Raj Finances (1963) was chaired by K. Santhanam.\n2. The Committee on Panchayati Raj Elections (1965) was also chaired by K. Santhanam.\n3. The Study Team on the Audit and Accounts of Panchayati Raj Bodies (1965) was chaired by R.K. Khanna.\nWhich of the statements given above is/are correct?","o":["1, 2 and 3","1 and 2 only","2 and 3 only","1 and 3 only"],"a":0,"e":"All three statements are correct, matching the book's list of pre-73rd-Amendment study teams/committees and their respective chairmen and years."})

upsc.append({"q":"Which one of the following statements about the fate of the Ashok Mehta Committee's recommendations is correct?","o":["Due to the collapse of the Janata Government before completion of its term, no action was taken on the recommendations at the central level, though Karnataka, West Bengal and Andhra Pradesh took steps informed by some of its recommendations","All of its 132 recommendations were fully implemented nationwide through a Central Act within two years of submission","The recommendations were rejected outright by all state governments without exception","The Committee's recommendations were superseded entirely by the L.M. Singhvi Committee before any state could act on them"],"a":0,"e":"The text explicitly states that the Janata Government's collapse prevented central-level action on the Ashok Mehta Committee's recommendations, but Karnataka, West Bengal and Andhra Pradesh nonetheless took steps to revitalise Panchayati Raj informed by some of its recommendations — contrary to the other three incorrect claims."})

# ==================================================================
# ASSEMBLY & VALIDATION
# ==================================================================

data = {"upsc": upsc}
all_q = upsc
texts = [q["q"] for q in all_q]
print("counts:", len(all_q))
print("unique:", len(set(texts)))
for q in all_q:
    assert len(q["o"]) == 4, q["q"]
    assert 0 <= q["a"] <= 3, q["q"]
    assert len(set(q["o"])) == 4, ("duplicate option text!", q["q"])
multi = sum(1 for q in all_q if "\n" in q["q"] or "List-" in q["q"] or "Assertion" in q["q"])
print("multi-format %:", round(100*multi/len(all_q), 1))

with open("/sessions/vigilant-wonderful-volta/mnt/outputs/pol_ch39_upsc.json", "w") as f:
    json.dump(upsc, f, indent=2, ensure_ascii=False)

print("Saved.")
